### ISSUE TITLE
JSoup cannot parse IDs with underscores

### ISSUE THREAD

**Issue by svivian** [jhy/jsoup#10]
Example:
Elements id = doc.select( "#An_ID_name" );

Error output:
Could not parse query #An_ID_name

Underscores are valid characters for IDs, but JSoup seems to choke on them. Regular IDs are working fine. There are other valid characters that I haven't tested, like dashes - these should all be accepted.

**Comment by gp2you** [comment]
doesnt work for class name which start with underscore <h3 class="_U6c">
