### ISSUE TITLE
Jsoup.parse fails in case if white space is added for style property

### ISSUE THREAD

**Issue by AbhijitKurane** [jhy/jsoup#1001]
Hello,
For the Jsoup.parse method we provided the below html string as input,
```
<html>
           <body>
                      <div style=text-align: right;>
                      </div>
           </body>
</html>
```
and output of the parse method which is Document is as below,
```
<html>
 <head></head>
 <body> 
  <div style="text-align:" right;> 
  </div> 
 </body>
</html>
```
From the output we can see that the text-align property is misplaced. The "right" value for the property text-align is out of the double quotes.

The same input will work if the white space in between **colon**(:) and  **right** text is removed for property text-align.
For the HTML text input which we provide for Jsoup.parse method is actually dependent  on the third party library so we cannot remove the white space programmatically. 
Please let us know if you observed the same and possible solution for this.

--
Thanks,
Abhijit

**Comment by krystiangorecki** [comment]
Jsoup behaves correctly. [HTML specification](https://html.spec.whatwg.org/multipage/introduction.html#intro-early-example) says:
> Attributes are placed inside the start tag, and consist of a name and a value, separated by an "=" character. **The attribute value can remain unquoted if it doesn't contain ASCII whitespace** or any of " ' ` = < or >. Otherwise, it **has to be quoted** using either single or double quotes. The value, along with the "=" character, can be omitted altogether if the value is the empty string.
