### ISSUE TITLE
Iframe with src="" and .absUrl

### ISSUE THREAD

**Issue by blacelle** [jhy/jsoup#1002]
Hello,

Given an iframe with a present but empty src attribute, `org.jsoup.nodes.Node.absUrl(String)` will resolve the iframe url as current document base href.

    public String absUrl(String attributeKey) {
        Validate.notEmpty(attributeKey);

        if (!hasAttr(attributeKey)) {
            return ""; // nothing to make absolute with
        } else {
            return StringUtil.resolve(baseUri, attr(attributeKey));
        }
    }

Given actual browser behavior and some sources like [https://stackoverflow.com/questions/5946607/is-an-empty-iframe-src-valid](url), it seemed such an iframe is expected to remain empty.

Wouldn't it be better to behave like browser, i.e. as if there was no src parameter at all and return an empty String?

Thanks

**Comment by AJITSURYA** [comment]
Wouldn't it be better to behave like browser,didn't get you actually.

JSoup can't handle dynamic content.We should simulate the work of a browser using Selenium or any other alternative

**Comment by jhy** [comment]
Closing -- sorry for the late reply. I can't see anything in the [parsing spec](https://html.spec.whatwg.org/multipage/parsing.html) or [iframe element](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element) that says an input empty src URL should be treated other than a doc relative URL.

If the input HTML sets it to empty, that is not valid (per the iframe doc above), but it doesn't read to me that the value should be left empty.
