### ISSUE TITLE
XML Parsing: Tags and Attributes changed to lowercase

### ISSUE THREAD

**Issue by biniamf** [jhy/jsoup#1004]
I had to rebuild the library by setting changing to lowercase OFF. Though the default is fine for HTML, I think it should be available as an option in the parser that can be set/unset by the caller; specially for the XML parser as there are cases where we need to preserve the cases (e.g., AndroidManifest files)

**Comment by jhy** [comment]
I'm not following - the XML parser does default to preserving tag case. You can see the tests here: https://github.com/jhy/jsoup/blob/e5210d1f9ef4f1d41ff0a8c4a2ab8e9192d5e087/src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java#L181

And, you can use the [ParseSettings](https://jsoup.org/apidocs/org/jsoup/parser/ParseSettings.html) to control it.

You are using the XML parser when parsing XML, right? The default is HTML, and if you parse XML as HTML you will run into more problems than just the tags having the wrong case. 

Here's an [example](https://stackoverflow.com/questions/9886531/how-to-parse-xml-with-jsoup)

Please reopen if I've missed something.
