### ISSUE TITLE
This problem has been bothering me ,about escape。

### ISSUE THREAD

**Issue by ljwps** [jhy/jsoup#1010]
# my program：
```
String template = "<input id=\"q\" name=\"q\" type=\"text\" maxlength=\"50\" autocomplete=\"off\" class=\"ui-search-q\" value=\"&lt;&gt;\">";
Document document = Jsoup.parse(StringUtil.getString(template));
System.out.println(document.outerHtml());
```
===================================================
# out is：
```
<input id="q" name="q" type="text" maxlength="50" autocomplete="off" class="ui-search-q" value="<>"> 
```
# problem ：
`&lt;&gt;`  has bean unescaped to <>

### How can I make unescaped in this case is not effective

**Comment by cketti** [comment]
It's valid for `<` and `>` to appear unescaped in quoted attribute values. See https://www.w3.org/TR/html51/syntax.html#attribute

**Comment by ljwps** [comment]
@cketti all right，but doing that can lead to cross-site scripting. many detection software found < or >, will think it is dangerous

**Comment by jhy** [comment]
How can it lead to and XSS? I don't think it makes sense to avoid the spec to make some dumb analysis tool feel good about itself.
