### ISSUE TITLE
java.nio.charset.IllegalCharsetNameException: "UTF-8"

### ISSUE THREAD

**Issue by marcleidner** [jhy/jsoup#1014]
I found this one in my logs. Most likely the quotes should be stripped before calling Charset.forName.

Cheers,
Marc

java.nio.charset.IllegalCharsetNameException: "UTF-8"
  java.nio.charset.Charset.checkName (Charset.java:315)
  java.nio.charset.Charset.lookup2 (Charset.java:484)
  java.nio.charset.Charset.lookup (Charset.java:464)
  java.nio.charset.Charset.forName (Charset.java:528)
  org.jsoup.helper.DataUtil.parseByteData (DataUtil.java:137)
  org.jsoup.helper.DataUtil.load (DataUtil.java:60)
  org.jsoup.Jsoup.parse (Jsoup.java:118)

**Comment by jhy** [comment]
Hi -- do you have the URL or HTML that this was for? I couldn't get a replication, and there is already a quote stripper there.

**Comment by marcleidner** [comment]
Hi Jonathan,

I can't remember, but I  think I have solved this one also by stripping quotes on my end.
Thanks for the reply, and keep up the good work!

Cheers,
Marc

**Comment by jhy** [comment]
OK, thanks. Please reopen if you catch a recurrence, would be good to root cause.
