### ISSUE TITLE
avoiding jsoup encoding during connection

### ISSUE THREAD

**Issue by ALEXSSS** [jhy/jsoup#1018]
I try to use Jsoup to crawler some sites. 
For example, I have such URL: 

    https://makeupmarket.ru/category/kisti-dlja-makijazha/?prednaznachenie_kistey%5B%5D=2568&vid_kistey%5B%5D=2554&vid_kistey%5B%5D=2555&vid_kistey%5B%5D=2556&vid_kistey%5B%5D=2558&vid_kistey%5B%5D=2559&vid_kistey%5B%5D=2560&vid_kistey%5B%5D=2561&vid_kistey%5B%5D=2572&vid_kistey%5B%5D=2573&vid_kistey%5B%5D=2576&vid_kistey%5B%5D=2578&vid_kistey%5B%5D=3115

During Jsoup connection which can be written this way:

    Jsoup.connect(uri.toString())..//some extra set attributes
    
    Connection.Response response = connection.execute();
    
    Document doc = response.parse();

I've got doc file which was taken from encoded URL:

    https://makeupmarket.ru/category/kisti-dlja-makijazha/?prednaznachenie_kistey%255B%255D=2568&vid_kistey%255B%255D=2554&vid_kistey%255B%255D=2555&vid_kistey%255B%255D=2556&vid_kistey%255B%255D=2558&vid_kistey%255B%255D=2559&vid_kistey%255B%255D=2560&vid_kistey%255B%255D=2561&vid_kistey%255B%255D=2572&vid_kistey%255B%255D=2573&vid_kistey%255B%255D=2576&vid_kistey%255B%255D=2578&vid_kistey%255B%255D=3115&mpCatId=1092

As you can see during connection `%` character was replaced by `%25`, and a site hasn't been able to answer correctly with this URL.

How can I prohibit this behavior to force Jsoup not encode URLs?

I was trying use 1.10.2 and 1.11.2 all of them don't work for me.

**Comment by jhy** [comment]
Sorry for the late reply. Reviewed this and tested in try.jsoup, and looks to be the correct data (e.g. product numbers I can see when loaded via Chrome are visible in the jsoup fetched source). So must have been fixed along the way.
