### ISSUE TITLE
fail to parse elements with \"

### ISSUE THREAD

**Issue by Trigun87** [jhy/jsoup#1020]
i noticed an error when try to parse something like this

`<annotations style=\"display: none;\"><ol class=\"tinymce-annotation-container\"><li data-annotation-id=\"9f4032b0-f8ba-3dea-f2f9-1d2707d04ffd\">It means Blue Dome of Heaven</li></ol></annotations>`

with .html() i get

```
<annotations style="\&quot;display:" none;\">
 <ol class="\&quot;tinymce-annotation-container\&quot;">
  <li data-annotation-id="\&quot;9f4032b0-f8ba-3dea-f2f9-1d2707d04ffd\&quot;">It means Blue Dome of Heaven</li>
 </ol>
</annotations>
```

the line
`<li data-annotation-id="\&quot;9f4032b0-f8ba-3dea-f2f9-1d2707d04ffd\&quot;">`
is parsed in that way instead
`<li data-annotation-id=\"9f4032b0-f8ba-3dea-f2f9-1d2707d04ffd\">`

and this break all 

**edit**
forgot to say i'm using .connect(url) and that code is inside a JSON response (is a string and not a html)

all body is:

`{"code":0,"data":{"isAuth":1,"content":"<p>[.. lot of text ..]</p><annotations style=\"display: none;\"><ol class=\"tinymce-annotation-container\"><li data-annotation-id=\"9f4032b0-f8ba-3dea-f2f9-1d2707d04ffd\">It means Blue Dome of Heaven</li></ol></annotations>","isRichFormat":1},"msg":"Success"}`

**Comment by jhy** [comment]
You should use a json parser first. Then the quotes will be unescaped and actually HTML.
