### ISSUE TITLE
In Jsoup , Why getElementById() returning null object and the given HTML string printing with twice with syntax error when .outerHTML() called?

### ISSUE THREAD

**Issue by RageshAntony** [jhy/jsoup#1021]
I am developing an application using Java which reads html tags. I am using JSOUP library to read HTML tags

**My Problem**</br>
</br> I created an `Element` tag by giving a html content as string ..

The html tag;

    <li id="comment_layout">
             <div class="img"><img src="http://www.prankmenot.com/assets/images/facebook/profile.jpg" width="32" height="32"></div>
             <div class="txt">
                <strong><a href="#" id="post_commenter">Sathish Kumar</a></strong> 
                <p id="post_comment" >Yes. Let develop this. </p>
                <div class="txtbottom"><a href="#" class="text-liketext">Like</a> · <a href="#">Reply</a> ·  <img src="http://www.prankmenot.com/assets/images/facebook/facebook_like_thumb.png"> <a href="#">5</a>  · <span style="color:#9197a3;">5 mins</span>
             </div>
             </div><div class="clearfix"></div>                            
          </li>

The HTML string object 

     public static final String CommentLi = "<li id=\"comment_layout\">" +
                " <div class=\"img\"><img src=\"http://www.prankmenot.com/assets/images/facebook/profile.jpg\" width=\"32\" height=\"32\"></div>" +
                " <div class=\"txt\"> <strong><a href=\"#\" id=\"post_commenter\">Sathish Kumar</a></strong> " +
                "<p id=\"post_comment\" >Yes. Let develop this. </p>" +
                " <div class=\"txtbottom\">" +
                "<a href=\"#\" class=\"text-liketext\">Like</a> · <a href=\"#\">Reply</a>" +
                " · <img src=\"http://www.prankmenot.com/assets/images/facebook/facebook_like_thumb.png\">" +
                " <a href=\"#\">5</a> · <span style=\"color:#9197a3;\">5 mins</span>" +
                " </div> " +
                "</div>" +
                "<div class=\"clearfix\">" +
                "</div>" +
                " </li>";

Now I created the `Element` Object:

            Element commmentLayout = new Element(TagStore.CommentLi);
            String commentLAyoutHTML = commmentLayout.outerHtml();
            System.out.println("The comments layout==>   "+commentLAyoutHTML);
    
            Element commentContent=commmentLayout.getElementById("post_comment");
            String commenContentHTML = commentContent.outerHtml();
            System.out.println(commenContentHTML);

**Now my problem is , when I execute the `commentContent.outerHtml()` , it produces null pointer execption since `commentContent` is null because `commmentLayout.getElementById("post_comment")` method invocation returns `null` object.**

Now my problem is , when I execute the `commentContent.outerHtml()` , it produces null pointer execption since `commentContent` is null because `commmentLayout.getElementById("post_comment")` method invocation returns `null` object.

I examined the html content. It having the "`post_comment`" id tag. (  `<p id="post_comment" >Yes. Let develop this. </p>`).

But I cant figure out why `getElementById` returning null even html contains the tag with that ID.

In order test the input , I printed the commmentLayout object. The output is weired.

    The comments layout ==>  <<li id="comment_layout"> <div class="img"><img src="http://www.prankmenot.com/assets/images/facebook/profile.jpg" width="32" height="32"></div> <div class="txt"> <strong><a href="#" id="post_commenter">Sathish Kumar</a></strong> <p id="post_comment" >Yes. Let develop this. </p> <div class="txtbottom"><a href="#" class="text-liketext">Like</a> · <a href="#">Reply</a> · <img src="http://www.prankmenot.com/assets/images/facebook/facebook_like_thumb.png"> <a href="#">5</a> · <span style="color:#9197a3;">5 mins</span> </div> </div><div class="clearfix"></div> </li>></<li id="comment_layout"> <div class="img"><img src="http://www.prankmenot.com/assets/images/facebook/profile.jpg" width="32" height="32"></div> <div class="txt"> <strong><a href="#" id="post_commenter">Sathish Kumar</a></strong> <p id="post_comment" >Yes. Let develop this. </p> <div class="txtbottom"><a href="#" class="text-liketext">Like</a> · <a href="#">Reply</a> · <img src="http://www.prankmenot.com/assets/images/facebook/facebook_like_thumb.png"> <a href="#">5</a> · <span style="color:#9197a3;">5 mins</span> </div> </div><div class="clearfix"></div> </li>>

Examine the above console output.. The html tag starts with `<<li ...` instead of `<li ...` . And the same html repeated twice in the output. (Note that the `<li id = "comment_layout">` repeating twice in the output. Also the joining place of repeated html having wrong syntax   `</li>></<li` )

I can't figure out the issue. My questions are :

 - Why this issue occurring. ?
 -  Why I can't get elementbyid() ? 
 - Why theElement object returing input html two times with syntax errors ?

**Comment by himanshu-pro** [comment]
This happens because the Element constructor gives you a tag from a string tag name. For example you would say:`new Element("div")` but not `new Element("<div></div>")`.

What you're trying to do is parse html. You should try Jsoup.parse or Jsoup.parseFragment.
A starting reference could be [https://www.tutorialspoint.com/jsoup/jsoup_parse_body.htm](url)

**Comment by jhy** [comment]
Thanks @himanshu-pro
