### ISSUE TITLE
different response XML 

### ISSUE THREAD

**Issue by ipinz** [jhy/jsoup#1022]
Using 1.10.3  when Jsoup grab some RSSfeed, I've got the following string

```
<link>
https://www.somesite.com/link-72689/
</link> 
```

and i've got result correctly 

But using latest 1.11.3, this is the response
```
<link>
https://www.somesite.com/link-72689/&lt;/link&gt; 

```
and messed the rest of elements.

Any idea? #

**Comment by jhy** [comment]
Can you show me the code? Are you using the XML parser?

I can't replicate using either the HTML or XML parser. https://try.jsoup.org/~glfMXwTOXaXCRuixsf4kOSdGg-w

**Comment by ipinz** [comment]
I did simple get document
```
document = Jsoup.connect(strUrl)
                    .parser(org.jsoup.parser.Parser.xmlParser())
                    .get();
```
Result Jsoup v 1.11.3
`document.toSting()`

[parse1.txt](https://github.com/jhy/jsoup/files/1912943/parse1.txt)

Result Jsoup v 1.10.3 
`document.toSting()`
[parse2.txt](https://github.com/jhy/jsoup/files/1912955/parse2.txt)

Did I missing something?

its happened randomly from some of Rss urls from myList

I didnt change my code. Just changed the library only. I double checked with
XML viewer [https://codebeautify.org/xmlviewer](url) and its went ok.
I believe it was the response. Thanks

**Comment by ipinz** [comment]
Ups my bad.. it wasnt 1.11.3 lol. 
Yeah. I'll wait for 1.11.3

Thanks
