### ISSUE TITLE
isValid() with baseUri parameter?

### ISSUE THREAD

**Issue by rwalkerands** [jhy/jsoup#1024]
I use Jsoup.isValid(), and am now finding that this rejects a relative URI for the IRI:

```
<a href="../../etc">...
```
As noted at #979, there's no variant of Jsoup.isValid() that takes a baseUri parameter.

**Comment by rwalkerands** [comment]
Forgot to mention: I did already use `preserveRelativeLinks(true)` on my whitelist, but this didn't help.

**Comment by dstoch** [comment]
It looks like easy to implement by adding baseUri argument Cleaner.isValidBodyHtml(...).
:+1:  from me :)

**Comment by willpowerforever** [comment]
This is quite useful. When can we get this implemented?

**Comment by jhy** [comment]
I simplified it for users such that if preserve relative links is enabled, `isValid` will pass, without otherwise having to set a base URI.
