### ISSUE TITLE
select() -> selectFirst() feature request

### ISSUE THREAD

**Issue by ogolovanov** [jhy/jsoup#1031]
Hello.

The problem with **select()** method is that it will fully traverse node so it is a time consuming operation.
It would be nice to have something like "selectFirst()" method.
Difference: it will traverse node until it will meet first proper and then stop.

So, instead of .select(cssSelector).first() it will be possible to use .selectFirst(cssSelector) which will work faster.

Thanks.

**Comment by jhy** [comment]
Thanks, I implemented that a while ago, it's in 1.1.1.
