### ISSUE TITLE
Entity parsing of CP-1252 code points

### ISSUE THREAD

**Issue by yawkat** [jhy/jsoup#1034]
Code points that are illegal characters in unicode (such as `&#0128;`) are parsed by browsers as CP-1252 ([blink](https://chromium.googlesource.com/chromium/blink/+/b69618018614278cda72077611adc093f460dc57/Source/core/html/parser/HTMLEntityParser.cpp#40), [gecko](https://github.com/mozilla/gecko-dev/blob/master/parser/html/nsHtml5NamedCharacters.cpp#L40)). This can lead to certain invalid symbols showing up in browsers but not being parsed in jsoup.

Test case HTML: `&#0128;` [in chromium](https://s.yawk.at/aV1I), [in firefox](https://s.yawk.at/PwKs)

jsoup test case:

```java
import java.util.Arrays;
import org.jsoup.Jsoup;

public final class Test {
    public static void main(String[] args) {
        System.out.println(Arrays.toString(Jsoup.parse("&#0128;").text().codePoints().toArray()));
    }
}
```

Prints out `[128]` at the moment, but should be `[8364]` (the € sign).

Unless I missed something this issue looks pretty straight-forward, so I'm willing to write a fix and associated test for this.

**Comment by jhy** [comment]
Thanks, would welcome a fix. Can you find a HTML5 spec for this mapping? I can't.

Should they be mapped, or is it an indication that the doc is actually in CP-1252 and should be re-parsed as that?

**Comment by yawkat** [comment]
I haven't found any spec for it either. I think it's just unspecified behavior but the browsers do it this way.

It doesn't look like it affects document encoding. At least gecko seems to [just map it and move on](https://github.com/mozilla/gecko-dev/blob/0819f35e51864e99f05179b53fa06fffb9e77948/parser/html/nsHtml5Tokenizer.cpp#L4291).

PR incoming.
