### ISSUE TITLE
:has() + ">"

### ISSUE THREAD

**Issue by ogolovanov** [jhy/jsoup#1035]
Hello.

As i understand it is not possible to build selectors like following ( select all divs that has "span" child ):
div:has(>span)

Or more complex like following ( select all divs that does not have children expect "b" and "strong" ):
div:has(>*:not(b,strong))

Do i understand right?
It would be nice if it could be implemented ;(
It is the only thing i miss after switching from xpath libraries to jsoup.

Thanks.

**Comment by jhy** [comment]
These work now now, was implemented a bit ago.

https://try.jsoup.org/~jKFWqLRtJSZAtSphLAdIf9XKv8A
