### ISSUE TITLE
null value is returning for get the playstore app version

### ISSUE THREAD

**Issue by Prasannakumarkannan** [jhy/jsoup#1036]
try {
   newVersion = Jsoup.connect("https://play.google.com/store/apps/details?id=com.xxx.xxx&hl=en")
         .timeout(30000)
         .userAgent("Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6")
         .referrer("http://www.google.com")
         .get()
         .select("div[itemprop=softwareVersion]")
         .first()
         .ownText();
   return newVersion;
} catch (Exception e) {
   return newVersion;
}

every time it returning null using jsoup 1.8.3

**Comment by suddutta** [comment]
Yes,I also facing this issue...please guys provide some solution.

**Comment by suddutta** [comment]
private class GetVersionCode extends AsyncTask<Void, String, String> {
        @Override
        protected String doInBackground(Void... voids) {

            try {
                newVersion = Jsoup.connect("https://play.google.com/store/apps/details?id=" + "pakagename" + "&hl=it")
                        .timeout(30000)
                        .userAgent("Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6")
                        .referrer("http://www.google.com")
                        .get()
                        .select("div[itemprop=softwareVersion]")
                        .first()
                        .ownText();
                return newVersion;
            } catch (Exception e) {
                return newVersion;
            }
        }

        @Override
        protected void onPostExecute(String onlineVersion) {
            super.onPostExecute(onlineVersion);

            if (!currentVersion.equalsIgnoreCase(onlineVersion)) {
                //show dialog
                new AlertDialog.Builder(MapsActivity.this)
                        .setTitle("Updated app available!")
                        .setMessage("Want to update app?")
                        .setPositiveButton("Update", new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int which) {
                                // continue with delete
                                final String appPackageName = getPackageName(); // getPackageName() from Context or Activity object
                                try {
                                    Toast.makeText(getApplicationContext(), "App is in BETA version cannot update", Toast.LENGTH_SHORT).show();
                                    startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=" + "pakagename")));
                                } catch (ActivityNotFoundException anfe) {
                                    startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=" + "pakagename")));
                                }
                            }
                        })
                        .setNegativeButton("Later", new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int which) {
                                // do nothing
                                dialog.dismiss();
                                new GetVersionCode().execute();
                            }
                        })
                        .setIcon(android.R.drawable.ic_dialog_alert)
                        .show();

            }
        }
    }



into on create 

 new GetVersionCode().execute();
        try {
            currentVersion = getPackageManager().getPackageInfo(getPackageName(), 0).versionName;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }

**Comment by jhy** [comment]
Try catching the exception and reviewing that, vs just throwing it away and returning a null object. The exception will show you what's wrong. Probably either your .get() failed, or the select failed and so .ownText() is being called on a null object.

I'd suggest using StackOverflow or another forum for programming hints.
