### ISSUE TITLE
Erroneous parsing HTML

### ISSUE THREAD

**Issue by ITonyLi** [jhy/jsoup#1044]
Case:
`<dd isdg="0,1,1,1,0"> </dd>`
Result:
`<dd isdg="0"> </dd>`
Expect：
`<dd isdg="0,1,1,1,0"> </dd>`

**Comment by jhy** [comment]
I tried this on try.jsoup.org and it works fine: http://try.jsoup.org/~kLEfl79rCA4ykT4VhwYolIKkrRM

What version are you using? Can you provide a testcase code?

**Comment by ITonyLi** [comment]
Sorry！ I found repeated attributes。
Like this:

<dd isStop = "0" matchcode="201804172004" matchnumcn ="周二004" starttime = "1523962800000" endtime ="1523962680000" isattention = "0"  isDg = "1,1,1,1,0" isDg = "0" hostname="广州恒大" guestname="大阪樱花" leagueid = "328" hostteamid = "5065" visitteamid = "2226" matchid="1370806" leagueName="亚冠杯" class="league_328 "  ishot="1" score="-1">    <span class="co1"><i class="jtip" inf="周二004">004</i></span>
--
