### ISSUE TITLE
Text in <script> should not escape entities.

### ISSUE THREAD

**Issue by cvillfon** [jhy/jsoup#1049]
According to the spec in HTML, the content of <script> tag is declared as CDATA, which means is unencoded, unparsed text data. However, Jsoup converts entities on output producing syntactically incorrect scripts. For example, the statement "if ( x > 0 ) " is converted by Jsoup to "if ( x &amp;gt; 0)" which gives a syntax error in the browser, breaking all of my embedded scripts. Note, that this is not the case in XHTML in which the content is declared as #PCDATA and it should be encoded. See https://www.w3schools.com/tags/tag_script.asp, Differences between XHTML and HTML.
As a workaround, I use 'String html = Parser.unescapeEntities(doc.outerHtml(), false);' however, this turns off entity escaping globally, which might be needed in other tags.

**Comment by jhy** [comment]
Can you show example code? I can't replicate: https://try.jsoup.org/~DtcDVm-ROfzvUhstCbsIPWk44iQ

**Comment by pflagerd** [comment]
> Parser.unescapeEntities(doc.outerHtml(), false);

Yes, I experience the same problem, and cvillfon I am grateful for your work-around.

HtmlCleaner doesn't have this problem.

**Comment by brett-smith** [comment]
Same problem here. `Parser.unescapeEntities` is not a solution for me, I have other entities that do need encoding. It is easy to replicate.

```java
		Document doc = Document.createShell("/");
		Element scriptEl = doc.body().appendElement("script");
		scriptEl.text("if(a > 1) { url = 'myUrl?parm1=val1&parm2=val2' };");
		System.out.println(doc);
```

gives

```html
<html>
 <head></head>
 <body>
  <script>if(a &gt; 1) { url = 'myUrl?parm1=val1&amp;parm2=val2' };</script>
 </body>
</html>
```
