### ISSUE TITLE
Pretty print should not reformat content of <style> and <script> tags.

### ISSUE THREAD

**Issue by cvillfon** [jhy/jsoup#1050]
The content of the <style> and <script> tags should be left untouched in prettyPrint output mode, unless Jsoup really knows how to pretty print CSS and JavaScript. Currently it is normalizing the space, converting everything to one long line, which I think is actually the opposite of pretty print in this case!

**Comment by jhy** [comment]
Do you have a code sample / test case? I can't replicate.

https://try.jsoup.org/~B6JbJVaM_oXJAlAcz9tilc4GOug

Are you using the XML parser instead of the HTML parser? The XML parser doesn't know anything about HTML tags...
