### ISSUE TITLE
Unable to select id has dot(.)

### ISSUE THREAD

**Issue by swarooppallapothu** [jhy/jsoup#1055]
I am parsing some page. It has div like below.

`<div id="submit.add" class="pre current">Some text</div>`

I want to fetch all divs with "submit.add.pre". In jquery i am escaping dot(.) with **\\\\**. how i can do in JSOUP?

**Comment by jhy** [comment]
Per the spec, ID's can't contain dots. So you can use the attribute selector, like this: `div[id=submit.add]`

E.g.: https://try.jsoup.org/~Rar9NhONcu3TbVc7WdvE90fAyAc

Backslash escapes would make sense, would welcome a PR.

**Comment by mahozad** [comment]
The same problem here.

```kotlin
val element = """<h3 id="wear-phone-interactions-1.0.1">Wear-Phone-Interactions Version 1.0.1</h3>"""
val document = Jsoup.parse(element)

val first = document.select("#wear-phone-interactions-1.0.1").text()
val second = document.select("[id=wear-phone-interactions-1.0.1]").text()
```

The `first` one does not work. Had to use the `second` one.

**Comment by jhy** [comment]
@mahozad not sure the point of this comment? I'm sure there are innumerable variations of invalid ID attributes.

**Comment by mahozad** [comment]
Sorry, you're right. This is not a problem.

I was not aware that `#some.thing` selects an element with id `some` and class `thing` ([1], [2]).

  [1]: https://stackoverflow.com/a/1028260/8583692
  [2]: https://stackoverflow.com/a/12310128/8583692
