### ISSUE TITLE
How can I control unescaped

### ISSUE THREAD

**Issue by ljwps** [jhy/jsoup#1057]
`
String s = "<input id="q" name="q" type="text" maxlength="50"  value=\"1&quot; onclick=&quot;prompt(27067)\">";
`
Document document = Jsoup.parse(s);
System.out.println(document.html());

out is：
`<html><head></head><body><input id="q" name="q" type="text" maxlength="50" value="1" onclick="prompt(27067)"></body></html>
`

see, value  unescaped
it caused the cross-site scripting

**Comment by jhy** [comment]
I can't repro that, see: https://try.jsoup.org/~AzIpO5wSlGuSjBOmgsKWPmw7lM0

Do you have a full testcase you can repro with? Can you confirm which version you're using?

**Comment by ljwps** [comment]
oh.....  update to 1.10.3 this  problem is fixed,thank you!!!!
old version is 1.8.3
