### ISSUE TITLE
[Enhancement] Element.firstParent(String query)

### ISSUE THREAD

**Issue by FlamingFox911** [jhy/jsoup#1060]
It would be nice if there was a function that allows one to find the nearest parent using a specific query, for readability purposes.

Currently what is happening is
`Element.parents().select(query).first()`

What it would look like
`Element.firstParent(query)`

**Comment by jhy** [comment]
Thanks -- this is available as Elements#closest

https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#closest(java.lang.String)
