### ISSUE TITLE
Unable to get ownText when text value has <> characters

### ISSUE THREAD

**Issue by eos1d3** [jhy/jsoup#1062]
When text value has <> characters, ownText returns null.

Example: 		
```
<h2 class="end_tit">
	<유>일진다이아, 전일 대비 7.11% 상승.. 일일회전율은 1.22% 기록
</h2>
```

"<유>" is actually part of the text but is parsed as real tag. So when getting the value of above class, ownText() returns nothing.

**Comment by krystiangorecki** [comment]
>"<유>" is actually part of the text

Parser recognizes it as another HTML tag. You cant use `<` and `>` inside HTML tag. The only way to use them is to escape them as `&gt;` and `&lt;`.

**Comment by eos1d3** [comment]
Right. It is the web page error instead.
