### ISSUE TITLE
Non-breakable spaces are collapsed into a single space with `.text()`

### ISSUE THREAD

**Issue by OndrejSkalicka** [jhy/jsoup#1063]
# Summary

Non-breakable spaces (`&nbsp;` / 160 / U+00A0) are considered as non-collapsible in HTML. In d3f0240 this was changed, so now you can either call `TextNode.text()` (and lose nonbreakable spaces) or `TextNode.getWholeText()` (but then you won't get rid of normal spaces).

There was some discussion over the topic in https://github.com/jhy/jsoup/issues/529 , but the solution is not really feasible as you either get "no collapsing" or "collapse everything, even whitespace that should not be collapsed".

# Expected behavior

`TextNode.text()` method to work like it is displayed in browsers. Eg. collapse all whitespace, but do not remove `&nbsp+`.

```java
@Test
void testNbsp() {
    final TextNode textNode = Jsoup.parseBodyFragment("NB&nbsp;&nbsp;&nbsp;SPACES")
            .body().textNodes().get(0);
    // three `&nbsp;` are replaced with three spaces 160/U+00A0 and kept.
    assertThat(textNode.text(), is("NB\u00A0\u00A0\u00A0SPACES"));
}

@Test
void testNormalSpaces() {
    final TextNode textNode = Jsoup.parseBodyFragment("NORMAL   \n\n\t\t SPACES")
            .body().textNodes().get(0);
    // normal spaces are reduced to a single one
    assertThat(textNode.text(), is("NORMAL SPACES"));
}
```

**Comment by OndrejSkalicka** [comment]
Note that you can use this HTML to test out in browser:

```html
<h2>Normal spaced <code style="white-space: pre">foo     bar</code></h2>
<div style="font-family: monospace;">
foo     bar
</div>

<h2>Non-breakable spaced <code style="white-space: pre">foo&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;bar</code></h2>
<div style="font-family: monospace;">
foo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bar
</div>

<h2>Mixed spaced <code style="white-space: pre">foo &amp;nbsp;&amp;nbsp;  bar</code></h2>
<div style="font-family: monospace;">
foo &nbsp;&nbsp;  bar
</div>
```

non-breakable spaces do not collapse. Single space + non-breakable space still does not collapse. Two normal spaces + non-breakable space results in single normal space + non-breakable space. Generally `&nbsp` are considered non-whitespace for purposes of collapsing.

**Comment by dportabella** [comment]
I agree. I've proposed this pull-request:
https://github.com/jhy/jsoup/pull/1071

**Comment by jhy** [comment]
I like the current implementation and we have specifically written code for it. Most times, nbsps are there for presentation and are not what a user is trying to extract from the DOM when calling the normalized text() method.

The wholeText() method will give you the non-normalized text when required.

**Comment by bbulgarelli-yseop** [comment]
As you mentioned in a pull request before, could it be possible to plan the making of an option to control the automatic shrink on non breakable spaces ?
On our side, we are handling various user input formats where non breakable spaces are used to indicate specific things, in contrary to the classic char 32 space.

The problem using `wholeText` for this case against `text` is that the following HTML: `<div><p>Hello</p><p>World</p></div>` produces the output `HelloWorld` with `wholeText` instead of the more expected `Hello World`.

Thanks in advance
