### ISSUE TITLE
element.outerHtml add some weird spaces 

### ISSUE THREAD

**Issue by eakteam** [jhy/jsoup#1069]
This parse happened from jsoup : 

`<div id="SIvCob"> Google ofrohet në:  <a href="https://www.google.com/setprefs?sig=0_ydJVQupCVMmjSavYZwsO33V0DlI%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj4xfbVtJ_bAhXD_aQKHexgB2AQ2ZgBCAg">English</a> </div>`

And this is from javascript - e.target.outerHTML() : 

`<div id="SIvCob">Google ofrohet në:  <a href="https://www.google.com/setprefs?sig=0_bqv4CoHWwCgTNiJovn8MQ2NT3jI%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjp0YPXq5_bAhUC2CwKHYG6BS0Q2ZgBCA4">English</a>  </div>`

So if you see there in jsoup version right after `<div id="SIvCob">` we have an extra white space that outerHTML from javascript doesn't have, and in the end of jsoup before `</div>` close tag we see 2 white spaces (1 white space extra) than javascript version. 

This is very important for my project and for everyone who need to make a `equal` condition between those two outputs

For the moment i have solved it by calling .replace(" ",""); to both of strings, but anyway this should be solved i think to be full compatible with javascript in most of functions

**Comment by clarcharr** [comment]
I'm running into a similar problem as well. In my tests, `Jsoup.parse(document.outerHtml()) != document` which is very not good.

**Comment by clarcharr** [comment]
One workaround is that disabling pretty printing does make this work. Although because pretty printing is the default, I would recommend that it do this anyway.

**Comment by eakteam** [comment]
I will try , thanks for your time

**Comment by jhy** [comment]
Fixed with #1689
