### ISSUE TITLE
ascii bad encoding Jsoup.clean()

### ISSUE THREAD

**Issue by suxaryk** [jhy/jsoup#1072]
`Jsoup.clean("ą, ć, ę, ł, ń, ó, ś, ź, ż.", Whitelist.simpleText())`

ą, ć, ę, ł, ń, `&oacute;`, ś, ź, ż.

ó -> `&oacute;`

**Comment by jhy** [comment]
Not sure which version you used - but current version gives what I expect:

https://try.jsoup.org/~Tpeqi4XwKb849sgrluogJiiH8p4

`&#x105;, &#x107;, &#x119;, &#x142;, &#x144;, &oacute;, &#x15b;, &#x17a;, &#x17c;.`

OAcute is the only named entity by the spec, so it's the only named one here. Rest are not ascii so need to be escaped.
