### ISSUE TITLE
.text cannot be computed in isolation for removing/normalizing trailing spaces

### ISSUE THREAD

**Issue by dportabella** [jhy/jsoup#1075]
opening a web page in a Web browser and executing the following code:
```
p = document.createElement("span");
p.innerHTML="   hello  6  world";
document.body.appendChild(p);
p.innerText // it returns "hello 6 world"

p = document.createElement("span");
p.innerHTML="   hello  6  world";
document.body.appendChild(p);
p.innerText // it returns " hello 6 world"
```
we see that it produces different results (the second node has a trailing space).
this means that `jsoup` `Element.text()` should also see the previous tags to see if it can remove the training space.

**Comment by jhy** [comment]
Hi there, if you're still impacted by this, could you add some detail on what you're trying to do? The text() method does aim to provide normalized and trimmed output per invocation. It is not aiming to ape the innerText method directly but is aimed to pull clean text out of the DOM. It does consider surrounding elements when working at an aggregate level (e.g. if you call text() on a div containing multiple P tags, they will be space seperated.
