### ISSUE TITLE
cookies with duplicate names not properly sent

### ISSUE THREAD

**Issue by lbouis** [jhy/jsoup#1076]
Hi,
There seems to be an issue with the way cookies with duplicate names are handled.
The wrong cookie seems to be sent to the next request, at least after a redirect
In my example,
we send a POST to a url, which sends a response back with redirect 302 to a GET (same domain www.swabiz.com, different url):
The response sets the following cookies, 2 of them with the name 'corporateToken', one empty, the other not.
A browser (Chrome in this instance) will sent the non empty value in the next request. Jsoup sends the empty one..
Not sure what the specs say exactly on how an http client should handle this, but at least it doesn't behave like a browser and that's an issue. Instinctively, I would have expected the non empty value to be passed to the GET (since the domain is more specifc, www.swabiz.com vs .swabiz.com)
I have tried with jsoup version 1.11.3.

SetCookie:
corporateToken | eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTd2FiaXoiLCJleHAiOjE4NDQ1MDY4OTIsIm5iZiI6MTUyODkzNzUxMiwiYm9va2luZ1R5cGUiOiJBTk9OWU1PVVMiLCJjb21wYW55SWQiOiI5OTYxMTc5NCIsImNvbXBhbnlOYW1lIjoiVHJpcEFjdGlvbnMiLCJwcm94eVRyYXZlbGVyQWNjb3VudE51bWJlciI6bnVsbCwicHJveHlUcmF2ZWxlck5hbWUiOm51bGwsInRyYXZlbE1hbmFnZXJOYW1lIjpudWxsLCJhdWQiOiJTb3V0aHdlc3QgQWlybGluZXMiLCJpc3MiOiJTb3V0aHdlc3QgQWlybGluZXMifQ.iyDYpB-LkhkAMx8Yyt-S49wnL7lmd9IPN9QeUSXFNZA
-- | --
Expires | Tue, 13-Jun-2028 11:01:32 GMT
Domain | www.swabiz.com
Path | /
corporateToken | ""
Expires | Thu, 01-Jan-1970 00:00:10 GMT
Domain | .swabiz.com
Path | /

and in the next request after redirect we see the cookie:

corporateToken ""

**Comment by jhy** [comment]
This is fixed with #1476
