### ISSUE TITLE
Wrongly resolve jar protocol,

### ISSUE THREAD

**Issue by AoEiuV020** [jhy/jsoup#1079]
jsoup 1.11.3,

        val file = File("/home/aoeiuv/tmp/panovel/epub/yidm/Re：从零开始的异世界生活_第十一卷.epub")
                .toURI()
        assertEquals("file:/home/aoeiuv/tmp/panovel/epub/yidm/Re：从零开始的异世界生活_第十一卷.epub", file.toString())
        val url = "jar:$file!/OEBPS/Text/CoverPage.xhtml"
        val html = """<img src="../Image/Cover.jpg"></img>"""
        val root = Jsoup.parse(html,url )
        root.select("img").forEach {
            assertEquals("../Image/Cover.jpg",it.attr("src"))
            // wrongly add slash after jar:
            assertEquals("jar:/$file!/OEBPS/Image/Cover.jpg", it.attr("abs:src"))
            assertEquals("jar:$file!/OEBPS/Image/Cover.jpg", URL(URL(url),"../Image/Cover.jpg" ).toString())
            URL(it.attr("abs:src"))
                    .openStream()
                    .read().let {
                        println(it.toString(16))
                    }
        }

org.jsoup.helper.StringUtil#resolve(java.net.URL, java.lang.String)
https://github.com/jhy/jsoup/blob/2b1ea0633ff5d4cba5db0e202a4ce0fbdccc19db/src/main/java/org/jsoup/helper/StringUtil.java#L202

![wronglyslash](https://user-images.githubusercontent.com/11682198/41595868-ec3634c8-73fa-11e8-9ebd-309feb17ee78.png)

**Comment by jhy** [comment]
Jsoup doesn't fetch file:// urls. That's noted in the connect() documentation - http and https. You can supply a File to the parse() method instead.
