### ISSUE TITLE
self-closing xml tag modified

### ISSUE THREAD

**Issue by dbrezoev** [jhy/jsoup#1080]
Cleaning this valid xml tag `<xs:element />` results in this `<xs:element ></xs:element>.`
I use `new OutputSettings().syntax(Document.OutputSettings.Syntax.xml)`

**Comment by sbe1** [comment]
I have a related problem with self-closing tags.

I'm trying to clean MathML embedded in HTML and Jsoup keeps trying to close self-closing MathML tags like `<infinity/>`

Does not work
```
        final Document doc = Jsoup.parse(str, "UTF-8");
        final Document.OutputSettings settings = doc.outputSettings()
                .syntax(Document.OutputSettings.Syntax.xml)
                .escapeMode(EscapeMode.xhtml).charset("ASCII").prettyPrint(false);
        Jsoup.clean(doc.html(), "", basicWithImagesMD, settings);
```
Also does not work:
```
        final Document doc = Jsoup.parse(str, "", Parser.xmlParser());
        final Document.OutputSettings settings = doc.outputSettings()
                .syntax(Document.OutputSettings.Syntax.xml)
                .escapeMode(EscapeMode.xhtml).charset("ASCII").prettyPrint(false);
        Jsoup.clean(doc.html(), "", basicWithImagesMD, settings);
```

Note: To be clear, I have a carefully compiled whitelist of all MathML tags and attributes (basicWithImagesMD argument in Jsoup.clean() above). Jsoup cleans the HTML properly and leaves all the MathML tags intact except for the self-closing ones. If you add closing tags to self-closing MathML tags, it is no longer valid MathML and is not parsable by math libraries like MathJax.

Example MathML inside HTML block:

INPUT:

```
<div class="mathblock">
<math xmlns="http://www.w3.org/1998/Math/MathML">
<infinity/>
</math>
</div>
```

OUTPUT:

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<infinity></infinity>
</math>
```

**Comment by sbe1** [comment]
This might be a relevant place to propose a new Whitelist method. Something like .allowSelfClosingTags() and the argument would be a list of html tag names that will be left as is regardles of whether they're found in closed or self-closed form.

So, .allowSelfClosingTags("my-tag") would mean that <my-tag/> and <my-tag></my-tag> would be considered valid. The parser/cleaner would just leave the tags alone (other than maybe removing unauthorized attributes) regardless of whether the tag is closed or self-closed.

This would allow things like MathML and even SVG to make it through the cleaner unscathed, provided the whitelist is properly set up to handle those tags. I think this would be tremendously useful to many people.

**Comment by jhy** [comment]
Thanks for the report. This was fixed in a previous version. https://try.jsoup.org/~2TqyYxub4Cl-CF5FjgfImsdeXXU
