### ISSUE TITLE
html parser remove whitespace between markup tags unlike xml parser

### ISSUE THREAD

**Issue by tamervi** [jhy/jsoup#1081]
Hello,
I'm encountering an annoying issue when using html parser. If you have a formatted input html like :

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<body>

    <div>

        <span>hello world!</span>

    </div>

</body>

</html>

```

Calling:

 

```java
Document doc = Jsoup.parse(input, "", Parser.htmlParser());
doc.outputSettings.prettyPrint(false);
System.out.println(doc.toString());
```

 will return:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head></head><body>

    <div>

        <span>hello world!</span>

    </div>

</body></html>
```

If I use xmlParser, it will display any xml compliant parsed document just fine without problems using `prettyPrint(false)`.

My Question how can I avoid any kind of formatting in case of html parser??
I'm using JSoup 1.11.3

**Comment by jhy** [comment]
Implemented in 9675a92b41593244d6d3ecd99425aeb19e2a6219
