### ISSUE TITLE
Preserve case results in broken HTML with additional emtpy lines

### ISSUE THREAD

**Issue by FelixSFD** [jhy/jsoup#1083]
With preserve case enabled for tags, the `.html()` returns additional empty lines in some cases and does some weird stuff with the `<P>`-tags.

### Input HTML
```
<P>Test Line 1</P>
<P>Test Line 2</P>
<P>Test Line 3</P>
```

### Code

```
String input = "<P>Test Line 1</P>\n<P>Test Line 2</P>\n<P>Test Line 3</P>";
Parser customParser = Parser.htmlParser();
customParser.settings(new ParseSettings(true, true));
Document doc = Jsoup.parse(input, "", customParser);

String output = doc.body().html();
```

### Output HTML

```
<P>
 Test Line 1
 <p></p> 
 <P>
  Test Line 2
  <p></p> 
  <P>
   Test Line 3
   <p></p>
  </P>
 </P>
</P>
```

When preserve case is disabled for tags, it works as expected.
```
customParser.settings(new ParseSettings(false, true));
```

Unfortunately, I need to preserve the case of tags.

The same happens when I use the XML-parser to parse the HTML, since it preserves the tag's case by default.

**Comment by jhy** [comment]
Hi, thanks for the report. I confirmed that this issue is fixed with this commit: 7ff7c43e9fbf4bbaf2b4517b3d4f8a429d87d3bb

Which is in HEAD now and will be in 1.12.1
