### ISSUE TITLE
CSSSelector() function should return the unique CSS selector

### ISSUE THREAD

**Issue by abhinav1708** [jhy/jsoup#1085]
In my Web App, I have multiple elements with same Id's and if i call CSS Selector function on those elements - It returns the ID only which is not unique and can't be used to uniquely identify the Page.

Using duplicate ID is bad designing practice and page is designed like that, Only one element of all the Duplicate id's are displayed at a time others are hidden in page but present in DOM(HTML Source)

**Comment by jhy** [comment]
Thanks, I have updated the cssSelector method so that for elements with IDs, it tests to see if that is unique and selects the desired element. If not, it will return a more detailed selector.
