### ISSUE TITLE
JSoup returns an invalid HTML

### ISSUE THREAD

**Issue by etcware** [jhy/jsoup#1087]
I'm working with JSoup 1.11.3 from Maven. I'm trying to make absolute relatives href, my code is in the following:    

    public String updateHrefs (String htmlContent, String baseUrl, String currentUrl) {
		org.jsoup.nodes.Document doc = Jsoup.parse(htmlContent);
		Elements links = doc.getElementsByTag("a");
		for (org.jsoup.nodes.Element link : links) {
		  String absHref = link.attr("href");
		  System.out.println("URL before " + absHref);
		  if (absHref.equals("")) {
			  absHref = baseUrl;
		  } else if ((absHref.length()>1) && absHref.substring(0, 2).equals("//")) {
			  absHref = absHref;
		  } else if (absHref.equals("http")) {
			  absHref = absHref;
		  } else if (absHref.substring(0, 1).equals("/")) {
			  absHref = baseUrl + absHref;
		  } else if (absHref.substring(0, 1).equals("#")) {
				  absHref = baseUrl + currentUrl + absHref;
		  } else {
			  absHref = baseUrl + "/" + absHref;
		  }
		  System.out.println("URL after " + absHref);
		  
		  link.attr("href", absHref);
		}
		return doc.outerHtml();
	}

At the end I pass the result to a html-to-pdf engine and it returns the error that a 

     <p> 

tag is not closed. I tried the html-to-pdf engine with the original html and it works: is it possible that there is an issue in JSoup? thanks

**Comment by jhy** [comment]
Jsoup creates a DOM tree so I can't imagine a path where a tag that is not self closing would be output in the generated HTML. I'm not sure how your `a href` changes would be relevant to that anyway.

Can you provide more code so we can replicate? I.e. what's the input, what's the output, which `p` is unbalanced.

Also you might like to look at the `abs:href` pseudo attribute as discussed [in this article](https://jsoup.org/cookbook/extracting-data/working-with-urls).
