### ISSUE TITLE
Element.attr("href") returning "#"

### ISSUE THREAD

**Issue by ladiesman6969** [jhy/jsoup#1089]
I am making a web-scraping project that basically fetches me images from Google Images. In order to get the image src, i use

Element.attr("href")

However, it returns

"#"

My Code

Document shivWall = Jsoup.connect(searchURL).get(); Elements smallImgElements = shivWall.getElementsByClass("rg_bx rg_di rg_el ivg-i"); smallImgElements.get(0).select("a.rg_l").get(0).attr("href");

I have tried numerous ways, but none of them worked. I even checked again by changing the attr argument to some random value, and it returns null as expected. But, for "href", it just returns a "#". Please help.

**Comment by razafinarivohanania** [comment]
The issue is due to **javascript rendering**. Try to open this link for example on your browser.

https://www.google.com/search?q=poisson&hl=fr&biw=1280&bih=686&tbm=isch&gbv=2&sei=8NKwW4v2NMeIgAbS66wQ

Save the html code source and clean it from https://www.freeformatter.com/ to indent tags. Now, lets see an "rg_bx rg_di rg_el ivg-i" and then find "rg_l".

```html
<div jscontroller="Q7Rsec" data-ri="63" class="rg_bx rg_di rg_el ivg-i" data-ved="0ahUKEwiJ-L_L6-LdAhUrCsAKHRwoDnQQMwh2KD8wPw">
   <a jsname="hSRGPd" href="#" jsaction="fire.ivg_o;mouseover:str.hmov;mouseout:str.hmou" class="rg_l" rel="noopener" style="background:rgb(248,133,50)">
      <div class="THL2l"></div>
      <img class="rg_ic rg_i" data-src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREkh5gjNIZrrPwvU-bBzJC-TioLCGhZnj6ayuzjnA9n7nXpAxE" jsaction="load:str.tbn" alt='Résultat de recherche d&#39;images pour "poisson"' onload="typeof google==='object'&&google.aft&&google.aft(this)">
      <div class="rg_ilmbg"> 568&nbsp;&#215;&nbsp;568 </div>
   </a>
   <a class="iKjWAf a-no-hover-decoration irc-nic" href="#" jsaction="mouseenter:QEDpme;focus:QEDpme;" rel="noopener" target="_blank">
      <div class="mVDMnf nJGrxf">Chaussons Poisson-Globe - Cute Land</div>
      <div class="nJGrxf FnqxG">cute.land</div>
   </a>
   <div class="rg_meta notranslate">{"cb":9,"cl":3,"cr":6,"ct":6,"id":"BQRe0XN-KbcAHM:","isu":"cute.land","itg":0,"ity":"jpg","oh":568,"ou":"https://cute.land/1357-big_default/chaussons-poisson-globe.jpg","ow":568,"pt":"Chaussons Poisson-Globe - Cute Land","rh":"cute.land","rid":"khat6BOchaioyM","rt":0,"ru":"https://cute.land/chaussons/313-chaussons-poisson-globe","s":"Chaussons Poisson-Globe","st":"Cute Land","th":224,"tu":"https://encrypted-tbn0.gstatic.com/images?q\u003dtbn:ANd9GcREkh5gjNIZrrPwvU-bBzJC-TioLCGhZnj6ayuzjnA9n7nXpAxE","tw":224}</div>
</div>
```

What we get? an href with "#" as value

```html
<a jsname="hSRGPd" href="#" jsaction="fire.ivg_o;mouseover:str.hmov;mouseout:str.hmou" class="rg_l" rel="noopener" style="background:rgb(248,133,50)">
```

So where is the image? This is found on img.rg_ic by using "data-src" as attribute.

```html
<img class="rg_ic rg_i" data-src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREkh5gjNIZrrPwvU-bBzJC-TioLCGhZnj6ayuzjnA9n7nXpAxE" jsaction="load:str.tbn" alt='Résultat de recherche d&#39;images pour "poisson"' onload="typeof google==='object'&&google.aft&&google.aft(this)">
```

Keep in mind that Jsoup doesn't interpret javascript. :)

**Comment by ladiesman6969** [comment]
I understood. Thanks for explaining :)
