### ISSUE TITLE
White list attributes are filtered！！

### ISSUE THREAD

**Issue by KevinBlandy** [jhy/jsoup#1091]
> Is there a problem with my operation? 
Thank you very much!

![image](https://user-images.githubusercontent.com/17979625/42511940-da6793ea-8485-11e8-9bbe-8dcde6b35577.png)

**Comment by KevinBlandy** [comment]
### Help!

**Comment by krystiangorecki** [comment]
Try lowercase attribute names:
`whitelist.addAttributes("marker", "markerheight", "markerheight", "refx", "refy", "id", "style");`

**Comment by jhy** [comment]
Thanks for the explanation @krystiangorecki
