### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by AJITSURYA** [jhy/jsoup#1095]
Can't load the sites with iframe

**Comment by krystiangorecki** [comment]
It's not a bug, it's a feature.
But you can easily get contents of an iframe with another request:
```
		Document doc = Jsoup.connect("...").get();
		String iframeUrl = doc.selectFirst("iframe").attr("src");
		doc = Jsoup.connect(iframeUrl).get();
```

**Comment by nances** [comment]
@krystiangorecki   您好，无法获取iframe 里面的src的数据
 网站源码见截图
![wx20181212-104012](https://user-images.githubusercontent.com/6659276/49843485-600e4780-fdfa-11e8-9e05-a48ba76cee8b.png)




无法获取到Iframe src 的数据   document_url.select("td.playleft").attr("src");
请问这个如何解决，谢谢
