### ISSUE TITLE
invalid XML file produced after org.jsoup.nodes.Document to org.w3c.dom.Document conversion

### ISSUE THREAD

**Issue by dportabella** [jhy/jsoup#1098]
I have an XML `org.w3c.dom.Document`, coming from an HTML `org.jsoup.nodes.Document`.

When I serialize the `org.w3c.dom.Document`, it produces an invalid XML file: it does not close the `META` tag.

Why? Is this a bug? from `jsoup`? from java `org.w3c.dom`?

Related bugs:

- `W3CDom.fromJsoup fails when xmlns is defined`  https://github.com/jhy/jsoup/issues/1096
- Should `org.jsoup.nodes.Document.toString()` produce a valid XML file?  https://github.com/jhy/jsoup/issues/1097

Example code:

    import org.jsoup.Jsoup;
    import org.jsoup.helper.W3CDom;
    import org.w3c.dom.Document;
    
    import javax.xml.parsers.DocumentBuilder;
    import javax.xml.parsers.DocumentBuilderFactory;
    import javax.xml.transform.OutputKeys;
    import javax.xml.transform.Transformer;
    import javax.xml.transform.TransformerException;
    import javax.xml.transform.TransformerFactory;
    import javax.xml.transform.dom.DOMSource;
    import javax.xml.transform.stream.StreamResult;
    import java.io.ByteArrayInputStream;
    import java.io.StringWriter;
    import java.nio.charset.StandardCharsets;
    
    public class Test130e {
        public static void main(String[] args) throws Exception {
            String html = "<html><head><script async src=\"http://example.com/script.js\"></script></head></html>";
    
            org.jsoup.nodes.Document jsoupDoc = Jsoup.parse(html); 
            System.out.println("+++ jsoupDoc.toString()");
            System.out.println(jsoupDoc.toString());
    
    
            Document w3cDoc = new W3CDom().fromJsoup(jsoupDoc);
            String xml = w3cDocToString(w3cDoc);

            System.out.println("+++ xml");
            System.out.println(xml);
    
            // this previous xml file is invalid, and so it fails to parse it
            // The element type "META" must be terminated by the matching end-tag "</META>".
            Document w3cDoc2 = parseXml(xml);
        }
    
        static Document parseXml(String content) throws Exception {
            DocumentBuilder documentBuilder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            return documentBuilder.parse(new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8)));
        }

    private static String w3cDocToString(Document w3cDoc) throws TransformerException {
        Transformer transformer = TransformerFactory.newInstance().newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");
        transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
        StreamResult result = new StreamResult(new StringWriter());
        DOMSource source = new DOMSource(w3cDoc);
        transformer.transform(source, result);
        return result.getWriter().toString();
    }

    }

Output:

    +++ jsoupDoc.toString()
    <html>
     <head>
      <script async src="http://example.com/script.js"></script>
     </head>
     <body></body>
    </html>

    +++ xml
    <html>
    <head>
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script async="" src="http://example.com/script.js"></script>
    </head>
    <body></body>
    </html>
    
    [Fatal Error] :5:3: The element type "META" must be terminated by the matching end-tag "</META>".
    Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 3; The element type "META" must be terminated by the matching end-tag "</META>".
    	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    	at playground.Test130e.parseXml(Test130.java:116)
    	at playground.Test130e.main(Test130.java:110)

Why does `w3cDocToString` build an invalid XML file (it does not close the `META` tag)?

Is this a bug? from `jsoup`? from java `org.w3c.dom`?

**Comment by jhy** [comment]
Thanks. The issue was that the default w3c output transformer was seeing a HTML tag and switching to HTML output mode. Resolved by setting output mode = XML.

**Comment by jhy** [comment]
Actually, I'm rolling this back. The W3C DOM can be HTML or XML, so hard-coding it to XML doesn't make sense I don't think. I have added a method and helpers to W3CDom to select between HTML and XML mode, and document that if not specified, it will default to checking the document content.
