### ISSUE TITLE
Can't able to parse the whole document using Jsoup

### ISSUE THREAD

**Issue by AJITSURYA** [jhy/jsoup#1101]
Problem_Statement_Stackoverflow:

The Jsoup is not able to parse the whole webpage,so the specific data that I am trying to extract out is also missing.In my project,I want to fetch some specific data out from the webpages.In most of the cases due to some search filters/iframes/since the content is in JS I am not able to extract the info I exactly need from the webpage.

It is only able to fetch some parts of the document.I have to parse thousands of webpages and I am not able to identify which pages are being missed out i.e can't completely be parsed using Jsoup.I have to manually find out which page is not completely parsed and for such kind of websites I use Selenium to simulate the work of a browser in order to parse the document.Is there any way to find out which type of pages can't be parsed using Jsoup or is there a way to indicate that the whole document hasn't been parsed using Jsoup.

I have found that : 1.Pages with Javascript couldn’t be loaded. 2.Pages with search filters can’t be parsed. 3.Page with wrappers aren’t being parsed. 4.Pages which are using iframe aren’t being parsed.

But I am not able to define the particular conditions to redirect them to Selenium.Even though I point out Javascript pages can't be loaded using Jsoup I can't redirect all of them to Selenium since it is really time consuming and reduces the performance drastically.

Eg : https://www.teachers-teachers.com/search-jobs - Search filters

https://jobs.rockwellcollins.com/job-search-results/ - Search filters

http://www.kaplan.com.sg/careers/ - Javascript

http://jobs.ecolab.com/job-search-results/ - Search filters

http://www.autoanything.com/jobs/opportunities - Search filters

http://www.dksh.com/global-en/home/careers/career-opportunities-iframe

**Comment by jhy** [comment]
Hi -- jsoup doesn't execute javascript. Without executing javascript, jsoup isn't going to be able to know that javascript is adding content to the DOM.
