### ISSUE TITLE
why ":nth-of-type(n)" doesn't support ?

### ISSUE THREAD

**Issue by sarika34** [jhy/jsoup#1104]
HTML contents : 
![jsoup](https://user-images.githubusercontent.com/11542748/43265742-4502a0c2-9107-11e8-9962-ad5c01dd5da6.png)

Here, I need to select "dl" tag with class=summary but it is present more than one time. I applied "dl:nth-of-type(1)[class=summary]" but it is selecting all dl tags with class value as summary.
Is there any other way to select a specific one out of similar elemnets ? 
Thanks

**Comment by suarez12138** [comment]
I think it's been fixed. 
Are there any conditions that remain abnormal?

**Comment by JeffXiesk** [comment]
Hi, I just want to add an new method ```nthOfType``` for querying the n th elements so that user can query the n th matching elements easily.

**Comment by jhy** [comment]
Sorry for the late review. Checked in 1.16.2, works correctly. See https://try.jsoup.org/~VQJmMVxTfwHp_IkIIxEvm0--bHA

Per @suarez12138, fixed some time ago.
