### ISSUE TITLE
Can't use selector that have an apostrophe in it

### ISSUE THREAD

**Issue by imtiazhossain** [jhy/jsoup#1105]
Hi, i'm trying to match a dom element that has an apostrophe in the text but I get a Selector.SelectorParseException. It only break when the text has an apostrophe in it. 

Elements elements = articleBody.select("a:matches("^User's matching text$")");

**Comment by razafinarivohanania** [comment]
The same to me

```sh
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'User'

	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.select(Selector.java:91)
	at org.jsoup.nodes.Element.select(Element.java:363)
```

I use version : 1.11.3

**Comment by jhy** [comment]
The matches input doesn't expect quotes, and you should escape the apostrophe, and it'll work. See [this example](https://try.jsoup.org/~tQywDLPdfB0IPT9FFNb5Z7JnjWI).
