### ISSUE TITLE
Comments may contain invalid characters that should have been converted to entities

### ISSUE THREAD

**Issue by hannibal218bc** [jhy/jsoup#1106]
When setting an output charset, Jsoup does not automatically convert characters not supported by the target charset to entities. The resulting document thus contains illegal characters.

Maybe `Comment.getData()` should also use `Entities.escape() like `TextNode` ?

See this live example: http://try.jsoup.org/~e0Nc-LMkpYKPAHhbnuGUICq-4g4
The "ascii" option is activated, so the target document should be valid ASCII. However, it still contains äöü Umlauts.

**Comment by hannibal218bc** [comment]
I see that this issue has not yet been addressed. Is the suggested fix not appropriate?

**Comment by jhy** [comment]
This is the same issue at #1271. When you parse, comments don't get decoded as they are data, so it doesn't make sense to encode them.

**Comment by hannibal218bc** [comment]
OK, agreed by the same reasoning as https://github.com/jhy/jsoup/issues/1271#issuecomment-748521612
