### ISSUE TITLE
XSS attack due to usage of invalid HTML

### ISSUE THREAD

**Issue by alwibrm** [jhy/jsoup#1108]
Some browsers (e.g. Firefox) are recognizing the following snippet as HTML: `<script src="https://malicio.us/xss.js“ <div`. As described in the cookbook [Sanitize untrusted HTML (to prevent XSS)](https://jsoup.org/cookbook/cleaning-html/whitelist-sanitizer), one can use jsoup for sanitizing HTML input. Unfortunately it's not interpreting the above snippet as an embeddable script (which a browser does). The gap between the interpretation of jsoup and common browsers could be used as a vulnerability.

**Comment by jhy** [comment]
Can you provide a minimal test case to show what you mean? It actually parses out to nothing (the script and the div are both dropped) - https://try.jsoup.org/~QJz_1XDNnJIG_-lzwOQu4_43ldU

So taking the output of the cleaned HTML would do the trick.

**Comment by alwibrm** [comment]
Not able to reproduce it anymore.
