### ISSUE TITLE
handle ESI tags in the head

### ISSUE THREAD

**Issue by odedcohen** [jhy/jsoup#1109]
Seems like jsoup doesn't recognize the tag <esi:include src="[url]"/> as a valid html tag that can exist inside the <head> tag. the side effect is that the parser forces the <body> tag to start before that ESI tag. Is it possible to add support for this tag and consider it as a valid tag inside the <head>. The ESI tag is a placeholder that allows CDN like solution to dynamically replace it at runtime with some other info.

Here is some more info about ESI:
https://en.wikipedia.org/wiki/Edge_Side_Includes

**Comment by jhy** [comment]
Thanks - I don't plan on making such a change that would pull the parser out of HTML5 spec
