### ISSUE TITLE
Showing content of downlevel-revealed conditionals for IE

### ISSUE THREAD

**Issue by mino181295** [jhy/jsoup#1117]
I'm parsing with Jsoup the follwing html and the output html and nodes are different in the result of `document.html()`
```        
String html = "<div>"
            + "<![if true]>1<![endif]>" // downlevel-revealed
            + "<!--[if true]>2<![endif]-->" // downlevel-hidden
            + "</div>";
Document document = Jsoup.parse(html);
```
**Output**

```
<html>
 <head></head>
 <body>
  <div>
   <!--[if true]-->1
   <!--[endif]-->
   <!--[if true]>2<![endif]-->
  </div>
 </body>
</html>
```
**Expected**

```
<html>
 <head></head>
 <body>
  <div>
   <![if true]>1<![endif]>
   <!--[if true]>2<![endif]-->
  </div>
 </body>
</html>
```
And the div `document.select("div").first().childNodes()` are like this:

class org.jsoup.nodes.Comment
class org.jsoup.nodes.TextNode
class org.jsoup.nodes.Comment
class org.jsoup.nodes.Comment

I would be happy to contribute to an eventual patch if you give me some hints.

**Comment by eolivelli** [comment]
I have the same problem.
Any news ?

**Comment by LIKP0** [comment]
I would like to have a try to fix it!

**Comment by LIKP0** [comment]
The code:
```
public static void main(String[] args) throws IOException {
        String html = "<div>"
                + "<![if true]>1<![endif]>"
                + "<!--[if true]>2<![endif]-->"
                + "</div>";
        Document doc = Jsoup.parse(html);
        System.out.println(doc.html());
    }
```
gives the output:
```
<html>
 <head></head>
 <body>
  <div>
   <!--[if true]-->1<!--[endif]--><!--[if true]>2<![endif]-->
  </div>
 </body>
</html>
```
jsoup version 1.13.1

**Comment by FKBugMaker** [comment]
Hello, @mino181295, our group are interested in your problem and would like to work on this issue. Can we have a try?
——SE 2022 group haha, SUSTech

**Comment by jhy** [comment]
I don't know that there's a way to implement and maintain compliance to the HTML5 spec. Which is a requirement.

Whatever produced this (some old IE package?) is operating out of spec for a proprietary parser. I don't see it as a priority currently.

**Comment by jhy** [comment]
Closing, as I don't see a way to implement this within the spec, and I don't see it as something that users are frequently hitting in current systems. Happy to revisit if there's a clean way and a critical mass for the requirement.
