### ISSUE TITLE
Everything in iframe tag are recognized as characters

### ISSUE THREAD

**Issue by GrigoriyDidorenko** [jhy/jsoup#1125]
Hi,

I'm facing the same problem, which was described in [issue 546](https://github.com/jhy/jsoup/issues/546).

Do you accept pull requests?

I see that current architecture doesn't support the idea of Document inside another document, but I am eager to find the idea to implement it.

**Comment by krystiangorecki** [comment]
HTML specification states that everything inside iframe is useless except in case of legacy behavior. There's an exception but I don't fully get it. Then it repeats that HTML parser should recognize contents as text.

> Descendants of iframe elements represent nothing. (In legacy user agents that do not support iframe elements, the contents would be parsed as markup that could act as fallback content.)
> 
> When used in HTML documents, the allowed content model of iframe elements is text, except that invoking the HTML fragment parsing algorithm with the iframe element as the context element and the text contents as the input must result in a list of nodes that are all phrasing content, with no parse errors having occurred, with no script elements being anywhere in the list or as descendants of elements in the list, and with all the elements in the list (including their descendants) being themselves conforming.
> 
> The iframe element must be empty in XML documents.
> 
> The HTML parser treats markup inside iframe elements as text.

source:
https://www.w3.org/TR/html52/semantics-embedded-content.html#the-iframe-element

**Comment by GrigoriyDidorenko** [comment]
Thank you, @krystiangorecki 

I've read the article, on the other hand, the question is arising: 
What's the use of threating iframe's content as text?

In this particular situation, I have an HTML page with a lot of iframes inside. How can i search inside them?

**Comment by krystiangorecki** [comment]
Try using XML parser. It will give you the same results but it won't give special meaning to iframe tag.

        Document doc = Jsoup.parse(html, "", Parser.xmlParser());

**Comment by GrigoriyDidorenko** [comment]
@krystiangorecki thank you!
