### ISSUE TITLE
"Creeper tracker code"-tag in a document leaves head tag empty

### ISSUE THREAD

**Issue by accron-1** [jhy/jsoup#1131]
A few sites have the following code at very beginning of the html page (even before the starting `<!DOCTYPE html>` element):

```
<!-- Begin Creeper tracker code -->
<a href="http://gnuheter.com/creeper/senaste" title="Creeper"><img src="http://gnuheter.com/creeper/image" alt="Creeper" width="80" height="15" border="0"/></a>
<!-- End Creeper tracker code -->
```

When this is the case, the `<head>` element in resulting jsoup document object is completely empty.

For a test, see: https://bit.ly/2PqIinY

**Comment by jhy** [comment]
Sorry for the late reply. This is working per the HTML5 spec that we follow - and exactly the same as Chrome etc. As soon as the parser sees content that can only be in the body (the `a` tag in this example), all following content is inserted in the body, leaving the head blank.
