### ISSUE TITLE
about annotation to escape  question

### ISSUE THREAD

**Issue by xuzhaocai** [jhy/jsoup#1135]
I need to add comments to the style element, but the '<' in the added comment is escaped as '&lt' Which method should I use to solve him

**Comment by ttqiadmin** [comment]
Document document = Jsoup.parse("<style id=a>abc:</style>");
		document.getElementById("a").parent()
				.html("<style>" + "" + document.getElementById("a").html() + "</style>"); 
System.out.println(document);

**Comment by xuzhaocai** [comment]
`<style>

</style>`
I want to fill this up with comments

**Comment by ttqiadmin** [comment]
#1049

`Document document = Jsoup.parse("<style > </style>  ");
		String html = Parser.unescapeEntities(document.outerHtml(), false);
		System.out.println(html);`
you could use  Parser.unescapeEntities(document.outerHtml(), false);
but it turns off entity escaping globally.

**Comment by xuzhaocai** [comment]
thank you
