### ISSUE TITLE
Jsoup1.11.3通过POST方法执行execute()无法判断Https响应码并直接报错

### ISSUE THREAD

**Issue by wzc25151** [jhy/jsoup#1137]
具体代码如下：
`Jsoup.connect(url).timeout(1000 * 10).validateTLSCertificates(false).method(Method.POST).execute();`
当执行execute方法时会直接报错，无法使用response.statusCode()来判断：
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=405, URL=https://....（省略）

**Comment by wzc25151** [comment]
machine translation:

The specific code is as follows:
Jsoup.connect(url).timeout(1000 * 10).validateTLSCertificates(false).method(Method.POST).execute();
When executing the execute() method, it will report an error directly, and cannot use response.statusCode() to determine:
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=405, URL=https://...(Omit)

**Comment by krystiangorecki** [comment]
The status you get is `Status=405`
https://zh.wikipedia.org/wiki/HTTP%E7%8A%B6%E6%80%81%E7%A0%81#4xx%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%94%99%E8%AF%AF
Try using `.method(Method.GET)` instead of `.method(Method.POST)`.

**Comment by wzc25151** [comment]
不止Status=405，我的意思代码一旦运行到'execute()'方法时，程序会中断并立即报错，后面‘response.statusCode()’则没有机会运行

More than Status=405, once I run the code to the 'execute()' method, the program will break and report an error immediately, followed by ‘response.statusCode()’ without a chance to run.

**Comment by wzc25151** [comment]
More than Status=405, once I run the code to the 'execute()' method, the program will break and report an error immediately, followed by ‘response.statusCode()’ without a chance to run.

**Comment by hulyang** [comment]
use .ignoreHttpErrors(true) to ignore http error
