### ISSUE TITLE
element.children().select returns elements that are not the immediate children of element

### ISSUE THREAD

**Issue by sangvann** [jhy/jsoup#1141]
Element element;
element.children() returns only the direct children of the element as expected.

But element.children().select("div[class*=someClass]") returns matching children() + grand children of the element.

**Comment by jhy** [comment]
Sorry for the late review. I don't see this as a bug. Element#select is defined as looking for matches down from the current element. Just exclude the grand children in the selector (by making the selector more specific). Is there a reason that won't work?
