### ISSUE TITLE
Two different cookies with same name but different values

### ISSUE THREAD

**Issue by Raakh** [jhy/jsoup#1142]
Hello,

I tried a lot https://stackoverflow.com/questions/52933075/website-is-using-same-name-multiple-cookies-how-to-deal-them-in-jsoup

Finally I seen that I can login but not able to crawl website pages because site is using two different cookies with same name but with different values. How can I deal this in Jsoup?

Best regards

**Comment by Raakh** [comment]
Is there anybody here to reply

**Comment by Raakh** [comment]
Hello,
You are not replying our issues
Best regards

**Comment by Raakh** [comment]
> Is it convenient to post the url address that you calwed.

`try {
			String url 			= "http://www.metalbulletin.com/Login.html";
			String articleURL 	= "https://www.metalbulletin.com/Article/3843914/hot-rolled-coil/CHINA-HRC-Trading-activity-set-to-pick-up-in-export-market.html";
						
			Connection.Response getForm		= Jsoup.connect(url).method(Connection.Method.GET).execute();			
			Map<String, String> formCookies = getForm.cookies();
System.out.println("formCookies=================================>\n"+formCookies+"\n");			
			Document doc					= getForm.parse();
			String token					= authenticityToken(doc);
			String formURL					= getForm.url().toString();
System.out.println(getForm.url());	
			Connection.Response loginForm = Jsoup.connect(formURL)
			.data("idsrv.xsrf", token)
			.data("userName", "kwqbz@daabox.com")
			.data("password", "Khjajfiie7645~")
			.cookies(formCookies)
			.method(Connection.Method.POST)
			.execute();
			Map<String, String> loginCookies = loginForm.cookies();
System.out.println("loginCookies====================================>\n"+loginCookies);			
			Document doc1 		= Jsoup.connect(articleURL).cookies(loginCookies).get();
			Element articleBody	= doc1.getElementById("article-body");				
			Elements lead1		= articleBody.getElementsByClass("articleContainer");		
			System.out.println(lead1.text());
        } catch (IOException e) {
            e.printStackTrace();
        }`

**Comment by ny83427** [comment]
I guess this might be a limitation of jsoup since it use a map to store name and value of cookie, in case same name at different domains or other cases, jsoup will just return one, which result in your failure following.

Have you tried use apache [httpclient](https://hc.apache.org/httpcomponents-client-ga/) to see if it make a difference?

**Comment by ny83427** [comment]
I also reported jsoup issue once here and got very quick reply from the author, as it's open source and the author is contributing using his spare time, so IMHO we cannot assume that he can reply in time each time. However, I believe that the power of community, and what's more important, the power within yourself, will resolve the issue finally.

It will never be a waste of time, especially when you are trying to resolve it on your own. Don't be upset and keep going on🙏

**Comment by rockswang** [comment]
You can try my project java-curl for http requests, it handles cookies gracefully, and use jsoup for html parsing.
here's the link: https://github.com/rockswang/java-curl

**Comment by Raakh** [comment]
Rocks Wang
rockswang
Can you please correct my posted code in this page https://github.com/jhy/jsoup/issues/1142#issuecomment-439468102

Thanks

**Comment by jhy** [comment]
Cookies are explicitly returned as a map - that's in the docs. You can grab the full headers from the response if you want something else. Sorry that you didn't enjoy your experience.

**Comment by DavidPDP** [comment]
This case can be handled with the multi-header method of the response, you'll find all the cookies that have been sent in the response on the Set-Cookie header. It should be noted that in my opinion, the case of the multi-cookie (same name) is exceptional, the ordinary would be to handle each semantically separated cookie (how it's implemented in the cookies method of this library) and I'd believe (I'm searching) that this case is a symptom of bad page creator design.

```
String url = "http://www.metalbulletin.com/Login.html";
Connection.Response loginFormResponse = Jsoup.connect(url).method(Connection.Method.GET).execute();

// Print all headers
loginFormResponse.multiHeaders().forEach((groupHeaderName, groupHeader) -> {
	System.out.println("Group Header: " + groupHeaderName);
	groupHeader.forEach(header -> System.out.println("Header: " + header));
});

//Print cookies headers
loginApiResponse.multiHeaders().get("Set-Cookie").forEach(
	cookie -> System.out.println("Cookie: " + cookie)
);
```
I also recommend using the VM argument to verify requests and responses:

`-Djavax.net.debug=all`

Thank you very much Jhy for such an excellent library.
