### ISSUE TITLE
javax.net.ssl.SSLHandshakeException when site gives incorrect intermediate certificate

### ISSUE THREAD

**Issue by ShayGuy** [jhy/jsoup#1146]
The site I'm attempting to scrape shows the following certification path in Chrome:

> 1) (site url)
> Issued by DigiCert Global CA G2
> 
> 2) DigiCert Global CA G2
> Issued by DigiCert Global Root G2
> 
> 3) DigiCert Global Root G2
> Issued by DigiCert Global Root G2

Running my program with -Djavax.net.debug=ssl shows this chain:

> 1) (site url)
> Issued by DigiCert Global CA G2
> 
> 2) Symantec Class 3 Secure Server SHA256 SSL CA
> Issued by VeriSign Universal Root Certification Authority
> 
> 3) VeriSign Universal Root Certification Authority
> Issued by VeriSign Universal Root Certification Authority

The site works in Chrome and Firefox, but not Jsoup. Apparently the site is sending incorrect additional certificates for the path. Is there a way I can set Jsoup to ignore those and follow the chain properly?

**Comment by rockswang** [comment]
use Connection..validateTLSCertificates(false)

**Comment by ShayGuy** [comment]
I'm not asking how to set it to accept all responses regardless of security. I'm asking how to set it to validate the certificate properly, the way the browser does.

Addendum: An HtmlUnit test shows the same problem, so the issue might be in sun.security.ssl.SSLSocketImpl or something. A .NET test with HtmlAgilityPack shows no such problem; I don't see any reason why it should be happening with Java.

**Comment by jhy** [comment]
Jsoup doesn't really do much with TLS / SSL / certs. All that's handled by the underlying Java URL handler. Typically I see these problems occur with old JDKs that don't have the latest cert handlers. Would look to upgrade your cert jars or the Java SDK. 

Closing as out of scope for Jsoup.
