### ISSUE TITLE
Accept LinkedMultiValueMap instead of Map<String, String> for POST data

### ISSUE THREAD

**Issue by ikocev** [jhy/jsoup#1160]
Hi,

I am submitting a POST request in order to get the page but the problem is that in the payload, there can be multiple fields with the same key and different value. This currently it is not possible with Map<String, String> type as a data while LinkedMultiValueMap<String, String> can. For example, HttpEntity client in Spring Boot can accept multiple fields using LinkedMultiValueMap [link](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpEntity.html#HttpEntity-T-).

**Comment by ikocev** [comment]
OK, I just saw calling connection.data("key", "value") can add multiple values for same key, but it would be still nice to accept MultiValueMap I think. What is your opinion on this?

**Comment by laxika** [comment]
The Apache Httpclient has a similar solution called HeaderGroup. https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/HeaderGroup.html Maybe something similar could be implemented?
