### ISSUE TITLE
Jsoup.parse limiting html string size

### ISSUE THREAD

**Issue by andersonmadeira** [jhy/jsoup#1161]
When building a document from html in a string using `Jsoup.parse`, Jsoup is not loading the whole html into a doc. 
If you fetch directly from a url, it's possible to use `Connection.maxBodySize` but I cannot find equivalent method when parsing directly from string.
That's kind of a feature request.
Thanks.

**Comment by krystiangorecki** [comment]
>  Jsoup is not loading the whole html into a doc.
What do you mean? It always parses whole html string into a doc.

**Comment by andersonmadeira** [comment]
In my code I get the html of the entire page using Volley through a post request and then I send the response html string to `Jsoup.parse`. I heard somewhere that there's actually a size limit for using Jsoup to read directly from a web page, that's I why I mentioned `Connection.maxBodySize`.
Is there any size limit for the string passed to `Jsoup.parse`? If there's such limit, how to increase it just like `Connection.maxBodySize`?

**Comment by ny83427** [comment]
Would you pls provide the large html as a zip file here, so that I can have a try to see whether there is really a limit of Jsoup or some other things happened?

Issue reported without input, expected output and actual output would be difficult to analyze.

**Comment by jhy** [comment]
There's no enforced size limit if you're just passing a string. I've benchmarked jsoup on > 1 GB files. My suspicion is that the page you're looking at uses Javascript and adds more to the DOM after load than is present in the HTML. Or some other integration issue.
