### ISSUE TITLE
JSON data problem

### ISSUE THREAD

**Issue by wt-z** [jhy/jsoup#1166]
![image](https://user-images.githubusercontent.com/17429343/50507413-6ff38000-0ab8-11e9-8012-8b93a20a0db5.png)

This is a normal format of JSON data, but jsoup will process the result, causing JSON data deserialization to fail.

jsoup version ：1.11.3
java version    :   1.8.0_191

**Comment by jhy** [comment]
Sorry, I don't understand why you're parsing the input as HTML if you don't want it parsed as HTML. Entities get un-escaped during parsing.

**Comment by wt-z** [comment]
Thank you very much for your reply, but I tried other solutions.
