### ISSUE TITLE
Empty div returned 

### ISSUE THREAD

**Issue by Rawkush** [jhy/jsoup#1167]
although the div contains elements, but the jsoup does not show its data, when page is loaded in jsoup the div is empty but in website the div conatins elements

**Comment by jhy** [comment]
Without details, no-one can replicate or look into this. Please provide a test case.

Are you sure the HTML source actually contains content in that div? Or is JS adding to the parsed DOM? In Chrome you can check this by comparing View Page Source (the original HTML) with Inspect (the current DOM). Remember that jsoup doesn't execute JS.

**Comment by Rawkush** [comment]
seems like that JS is creating the elements, as you as said I compared the page sources with Inspect.
And since Jsoup can't execute the JS I think we can't solve this issue right now, so I will be closing it
