### ISSUE TITLE
Jsoup code is conflicting with Apache httpclient code - java.io.IOException: Too many redirects

### ISSUE THREAD

**Issue by kbadruka** [jhy/jsoup#1171]
I am trying to read URL body for domain - iv4u.health using Jsoup library (version 1.11.3) but getting "Too many redirects" error. Below is the code I am using - 

`public class Example {

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        crawlDomain("http://iv4u.health");
    }

    public static void crawlDomain(String url) {
        int timeout = 30;
        RequestConfig config = RequestConfig.custom()
            .setConnectTimeout(timeout * 1000)
            .setConnectionRequestTimeout(timeout * 1000)
            .setSocketTimeout(timeout * 1000)
            .setRedirectsEnabled(false)
            .build();

        CloseableHttpClient client = HttpClientBuilder.create().setDefaultRequestConfig(config).build();
        HttpGet request = new HttpGet(url);
        CloseableHttpResponse response;
        try {
            HttpClientContext context = HttpClientContext.create();
            response = client.execute(request, context);
            int status = response.getStatusLine().getStatusCode();
            if (status >= HttpStatus.SC_MULTIPLE_CHOICES && status < HttpStatus.SC_BAD_REQUEST) {
                System.out.println(getURLBody(url));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static String getURLBody(final String url) {
        try {
            String userAgent = "Mozilla";
            Document doc = Jsoup.connect(url)
                .userAgent(userAgent).get();
            return doc.toString();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
}`
The code works sometimes though(mostly first time).

It seems Jsoup code is conflicting with Apache httpclient code. If getURLBody() function is called directly from main method, it works everytime.

**Comment by kbadruka** [comment]
Its even conflicting with Java default HttpURLConnection class. Below code is also not working - 

`public class CopyOfExample {

    public static void main(String[] args) throws Exception {
        crawlDomain("http://iv4u.health");
    }

    public static void crawlDomain(String url) throws IOException {
        try {
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            con.setInstanceFollowRedirects(false);
            int responseCode = con.getResponseCode();
            System.out.println(responseCode);
            System.out.println(getURLBody(url));
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
        }
    }

    private static String getURLBody(final String url) {
        try {
            String userAgent = "Mozilla";
            Document doc = Jsoup.connect(url)
                .userAgent(userAgent).get();
            return doc.toString();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
}`

Its conflicting with setInstanceFollowRedirects() method when its value is false

**Comment by kbadruka** [comment]
Can someone please have a look into the mentioned issue and update this thread ?

**Comment by ttqiadmin** [comment]
followRedirects(false)
