### ISSUE TITLE
Add support for ::before and ::after selectors 

### ISSUE THREAD

**Issue by aleksi1** [jhy/jsoup#1173]
::before and ::after selectors are widely used and supported, can you add support for these selectors?

Example:

`    	Elements e = Jsoup.parse("<span><div>").select("div::before");
`

https://caniuse.com/#feat=css-gencontent

**Comment by Seeyn** [comment]
can you give a more specific example?

**Comment by Seeyn** [comment]
Like:
<div>
 a<span>b</span><span>c</span>
</div>

.select("span:before")

**Comment by aleksi1** [comment]
I think that in browser there is no real element for ::before selection, but you can add CSS styles to that selection. I think it could work as before / after methods in Element. So kind of invisible element, which you could convert to real element by adding html / tag etc to it.

**Comment by Seeyn** [comment]
Thanks for your reply.So, your intention is to convert the invisible element to real element according to the css style. am i right?

**Comment by aleksi1** [comment]
My use case is that I cannot use Element API and my app user can only use CSS selectors, so it would be good if I could somehow use ::before / ::after selectors and append HTML to selected position just like in browser.

**Comment by jhy** [comment]
Thanks for the discussion - I'm not really understanding the use-case or the proposal. How are you going to append HTML to selected items if you can't use the API? Why can't you use the API?

Happy to review with more of a specific use case and a proposal.
