### ISSUE TITLE
Why do Jsoup use StringReader?

### ISSUE THREAD

**Issue by laxika** [jhy/jsoup#1179]
Is there a particular reason why Jsoup use the `java.io.StringReader` class? The `StringReader` is synchronized but I'm unsure if Jsoup has any threading in it?

What about implementing Jsoup's own StringReader that's not synchronized?

I need to parse a huge amount of HTML files (100+TB / month) with limited resources available. Jsoup servers me right but it come a little short on performance (compared to my requirements). I optimized my application code to a point where `Jsoup.parse(String, String)` takes ~85% of the runtime. Because of this I have little to do other than start optimizing Jsoup as well.

**Comment by jhy** [comment]
Jsoup uses StringReader when you give it a String to parse (vs a URL, InputStream, File, etc). As it uses Reader as a convenient interface for the different input types. If you are giving it a String, it's probably more efficient to give it a file (which will use a BufferedReader).

But... are you sure that the synchronization is what is consuming CPU? StringReader syncs on itself and that's super efficient in the Hotspot runtime. I.e. it's not doing any cross thread blocking. Do you have profiling to show that lock contention is getting in the way? Would be useful to see in case something is going wrong.

HTML parsing to the full spec is pretty intensive, so I'm not surprised that it's taking a lot of resources for that scale. Happy to take PRs for further optimizations :)
