### ISSUE TITLE
jsoup cpu is high

### ISSUE THREAD

**Issue by wuhoubing** [jhy/jsoup#1181]
Cpu is very high when parsing large amounts of html using jsoup

**Comment by laxika** [comment]
Yes, it is. But you can't do much with it. I tried to do some optimizations but was only able to improve a little bit. JSoup is quite well optimized out of the box.

**Comment by jhy** [comment]
I don't have anything else to add... If you have a specific HTML chunk that could do with more optimizing, please add and re-open.
