### ISSUE TITLE
How to cancel connection after call connection.get()

### ISSUE THREAD

**Issue by Harlber** [jhy/jsoup#1182]
As title say,how can I cancel a connection

**Comment by jhy** [comment]
You can interrupt the thread (assuming that you're running the .get() in a different thread).

There's an example here: https://github.com/jhy/jsoup/blob/b87c013947d59cca92e853a02f2d2d6ae41ef586/src/test/java/org/jsoup/integration/ConnectTest.java#L235

Generally though I would suggest setting the max timeout and max file size and let jsoup do it internally. Let me know if that doesn't work for you.
