### ISSUE TITLE
Already Escaped HTML with script tag is not getting cleaned

### ISSUE THREAD

**Issue by bhupindersingh04** [jhy/jsoup#1184]
I am trying to clean the escaped html containing script tag , jsoup is not cleaning it.

Link - http://try.jsoup.org/~Oc919LWfD_6WnPlLYkZy1LQ78Wc

Sample Code - `
               Whitelist WHITE_LIST = new Whitelist().addTags("b", "em", "i", "strong", "u", "ul", "li", "p", "br");
		fieldValue = "&lt;script&gt;alert('Hello');&lt;/script&gt;";
		String clean = Jsoup.clean(fieldValue, WHITE_LIST);`

**Comment by jhy** [comment]
Why would jsoup clean this? It's not script, it's escaped code. Not going to be an XSS unless you render it as text and then use that text as HTML...
