### ISSUE TITLE
Not preserving content outside head and body elements

### ISSUE THREAD

**Issue by Vegeeto** [jhy/jsoup#1185]
I'm using Jsoup parser. With prettyPrint option disabled, I'm loosing whitespaces between DOCTYPE definition and html tag. Also, I'm loosing whitespaces between html and head start tag.

I think the main problem is that Jsoup is not keeping whitespaces between html childs, and between document and html element.

I'm using HTML parser. Using XML parser the output is correct, so maybe HTML parser should do the same.
If not, what are the reasons?

Here is a test link: https://try.jsoup.org/~lPGQPj9gNjjfU1yN-pYRvQVfzMY

**Comment by Vegeeto** [comment]
I'm using HTML parser. Using XML parser the output is correct, so maybe HTML parser should do the same.

**Comment by jhy** [comment]
Thanks, this was implemented in 9675a92b41593244d6d3ecd99425aeb19e2a6219.

**Comment by Vegeeto** [comment]
Hi,
Thank you for implementing this!

Now, I realised that whitespace between closing body tag and closing html tag has lost.
Check the example: http://try.jsoup.org/~fETsCv8YuhVF_1ofxxcX9lUvngk
