### ISSUE TITLE
document.html() is not parsing as expected

### ISSUE THREAD

**Issue by ShailajaV** [jhy/jsoup#1187]
I am trying to parse the entire text which has all kinds of html tags. Because i have to parse the string to html, i can't use document.text() so i am using document.html(). But document.html() is not parsing &amp; and it is printing as is. And also it is not parsing html s tag. It is just printing the text within  html /s> tag. It is not striking it out.
What exactly we have to use to parse the entire string to html?.

**Comment by jasonsperske** [comment]
Can you provide some example of the html that it isn't parsing? When running this code:
```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

class Main {
  public static void main(String[] args) {
    System.out.println("Jsoup by parsing html");
    Document doc = Jsoup.parse("<ul><li><s data-thing=1>Thing 1</s></li><li><s data-thing=2>Thing 2</s></li></ul>");
    System.out.println(".text()\t|\t.html()");
    for (Element e : doc.select("li")) {
      System.out.println(e.text() + "\t|\t" + e.html());
    }
    System.out.println("Jsoup updating html");
    doc.html("<ul><li><s data-thing=3>Thing 3</s></li><li><s data-thing=4>Thing 4</s></li></ul>");
    System.out.println(".text()\t|\t.html()");
    for (Element e : doc.select("li")) {
      System.out.println(e.text() + "\t|\t" + e.html());
    }
  }
}
```
I see the following output:
```
Jsoup by parsing html
.text() |   .html()
Thing 1 |   <s data-thing="1">Thing 1</s>
Thing 2 |   <s data-thing="2">Thing 2</s>
Jsoup updating html
.text() |   .html()
Thing 3 |   <s data-thing="3">Thing 3</s>
Thing 4 |   <s data-thing="4">Thing 4</s>
```
(here is a demo that you can play with https://repl.it/@jasonsperske/JSoup-bugs)

**Comment by ShailajaV** [comment]
Thank you for your reply.
From your above example, if we run the actual html file with the above code it will strike out Thing 1, Thing 2, Thing 3 and Thing 4. But this is not happening either with .text() or .html().
Can you please share the command which exactly translate the html. If i am giving<s>Thing1></s> then it should strike out the Thing1. E.g. S̶o̶m̶e̶ ̶T̶e̶x̶t̶ .

**Comment by jasonsperske** [comment]
I'm still having a hard time understanding the HTML that you are trying that isn't working.  Are you talking about parsing a strike-through `<s>` and expecting it appear in the output of `.text()`?  If that's the case then that is not the expected behavior of `.text()`.  `.text()` returns the textual contents of a supplied node (minus any html including `<s>` as well as `<b>`, `<center>`, `<font>` etc.).  If I'm wrong about what you are trying to do then could you reply with the html you are trying?

**Comment by ShailajaV** [comment]
You are right. I need to parse the entire html. It should parse <s>, &amp;,...
Example text is : <p>here is the text</p><s>Some Text</s><p>end &amp;
If i am using .html() then it is printing as
here is the text Text1 end &amp;
But i want the out put as 
here is the text S̶o̶m̶e̶ ̶T̶e̶x̶t̶ end &
Could you please help me what to use to get the above output.

**Comment by jasonsperske** [comment]
The character `S` is the same character as S̶, the difference in appearance comes from the html applied to that character.  The function you want is probably `.html()` you are just attempting to read what it returns as a rendered font.  It may be confusing because `.text()` is doing some transformation (turning the html entity `&amp;` into the `&` character, but this can only go as far finding the unicode code-point that corresponds to the display characters inside each html node.  It cannot apply a font decorations (which is what the strike through is).  To get that line you need to pass the desired text to a rendering engine (probably one that would understand html to eliminate steps in this chain).

**Comment by ShailajaV** [comment]
when i am using .html() it is not striking out the text. It is printing as is. Can you please let me know is there any method which i can use to render all html tags.

**Comment by ShailajaV** [comment]
Can you please help me on the below requirement.
I have a html string and need to parse the same.
Here is the example. Below is my input String:

`<p>hi<s>In early 2018</s>, Services extended their relationship construction &amp; item1, item2 &amp; parts.</p><p><br></p><p><br></p><h1>Here is the header text.</h1><p><br></p><p><br></p><ol><li>Test1</li><li>Test2</li><li>Test3</li></ol><p><br></p><ul><li>Hello</li><li>Hello1</li><li>Hello2</li></ul><p><br></p><p class=\"ql-align-center\">End String .</p>
`

And i need the output as :

hi<s>In early 2018</s>, Services extended their relationship construction & item1, item2 & parts.
Here is the header text.
  
   Test1
   Test2
   Test3
  
  
  
   Hello
   Hello1
   Hello2
  
  End String.

----------------------------------------------------------------------------------
Please help me which method i should use to achieve the above requirement. As i discussed above already .html() is not rendering font, bold, strike tags. But i want a method which should render all the html tags properly.

**Comment by jasonsperske** [comment]
What you are looking for is beyond the scope of jsoup.  Parsing and rendering are separate function.  the `.text()` is a form of rendering but it is limited to extracting the text from inside html tags, so in that sense it is more of a helper function.  To render html you need to first determine what kind of output you are after.  You have several options, if you just need to the pixels as they appear in a browser you can use something like [CSSBox](http://cssbox.sourceforge.net/) which can output a graphic file with the pixels that a browser would draw.  You can also render html as a PDF with a library like [Flyingsaucer](https://github.com/flyingsaucerproject/flyingsaucer) (which also supports image output).  Or if you are really adventurous it should be possible to take the `.text()` output and find corresponding strike through Unicode characters by shifting the code point https://en.wikipedia.org/wiki/Strikethrough#Unicode

**Comment by jhy** [comment]
Thanks @jasonsperske 

Let's please use these issues for jsoup bugs, not general guidance on using jsoup / parsing and rendering HTML. StackOverflow is better suited for that.
