### ISSUE TITLE
How to get rid of node structures with unwrap?

### ISSUE THREAD

**Issue by atbest** [jhy/jsoup#1188]
When an element is unwrapped, it is removed from the element list, however, its node remains in the node list (childNodes). I will use the following codes to explain it.
```Java
        String html = "<p>This is a <span>sample</span> paragraph.</p>";
        Document doc = Jsoup.parse(html);
        // doc.select("span").unwrap(); 
        Elements elements = doc.selectFirst("p").getAllElements();
        for (Element element: elements) {
            System.out.println(element);
            List<Node> nodes = element.childNodes();
            for (Node node: nodes) {
                System.out.println(node.nodeName() + ": " + node);
            }
            System.out.println("");
        }
```
The output is 
```
<p>This is a <span>sample</span> paragraph.</p>
#text: This is a 
span: <span>sample</span>
#text:  paragraph.

<span>sample</span>
#text: sample
```
When `doc.select("span").unwrap()` is uncommented, the output is
```
<p>This is a sample paragraph.</p>
#text: This is a 
#text: sample
#text:  paragraph.
```

As you can see from the outputs, `span` element is gone from `elements` but the node is still present in `nodes`. Is it possible to unwrap the node as well? The expected output is
```
<p>This is a sample paragraph.</p>
#text: This is a sample paragraph.
```

**Comment by jhy** [comment]
It's not that the node is still wrapped, you just have a list of three text nodes in a row. Normally parsed HTML won't give you that, but with this manipulation you do get it. What are you actually trying to do / why does the list of textnodes have an impact? I would just be inclined to call `element.text()` and get the clean text.

I actually thought we had a helper method that would normalize consecutive text nodes into one, but maybe that was from the old parser which didn't accumulate them in the stream.

Here's a bit of a hack which re-normalizes the HTML

```java
        String html = "<p>This is a <span>sample</span> paragraph.</p>";
        Document doc = Jsoup.parse(html);
        doc.select("span").unwrap();
        doc.html(doc.html()); // re-normalize the text nodes into one
        Elements elements = doc.selectFirst("p").getAllElements();
        for (Element element: elements) {
            System.out.println(element);
            List<Node> nodes = element.childNodes();

            for (Node node: nodes) {
                System.out.println(node.nodeName() + ": " + node);
            }
            System.out.println("");
        }
```

Gives
```
<p>This is a sample paragraph.</p>
#text: This is a sample paragraph.
```

Might be worth adding a normalize() method to Element.

**Comment by atbest** [comment]
Thanks for the solution. The major reason is that I want to keep `<br>` tags and convert it to `\n`. However, `element.text()` converts `<br>` to space directly.
