### ISSUE TITLE
optimise memory use

### ISSUE THREAD

**Issue by emmanueltouzery** [jhy/jsoup#119]
Hello, I'm using your library on android and it works great. However I've had performance problems, including seeing jsoup taking around 7 seconds to parse 45kb HTML documents. I've isolated the www fetching and the parsing and I'm sure it's only the parsing which can be so long.

After some looking around I have concluded that what is so slow is the android garbage collector (i'm testing on an HTC Desire on android 2.2). Because android phones are more memory constrained the garbage collector is invoked more often and because they have slower CPUs it's slower to run.

The solution to that problem is to avoid unnecessary allocations. I've used the android DDMS allocations profiler to come up with the top offenders and since I've applied the attached patch to my local jsoup copy, I'm not seeing such pathological slowdowns anymore.

I am aware that the patch makes the code less elegant but unfortunately I didn't find a nicer way. Also of course my patch uses ugly variable names (array1, array2 and so on ,class names T, U), this is because I was not sure whether you'd accept this change at all. If you are interested if you want you can suggest me how to name the variables or how to rework the patch and and I can try to improve it.

You can get the patch from here:
http://dl.dropbox.com/u/22600720/jsoup-memory.diff

emmanuel

**Comment by jhy** [comment]
Some recent perf improvements on Android are similar to these lines. Got about a 1.3x impact from them.
