### ISSUE TITLE
I can't find merged pull request 570

### ISSUE THREAD

**Issue by krystiangorecki** [jhy/jsoup#1190]
File [CHANGES](https://github.com/jhy/jsoup/blob/master/CHANGES) contains this entry:
```
*** Release 1.9.1 [2016-Apr-16]
 * Added support for HTTP and SOCKS request proxies, specifiable per connection.
   <https://github.com/jhy/jsoup/pull/570>
```
When I visit [pull/570](https://github.com/jhy/jsoup/pull/570) I see:

> jhy merged commit [0986da6](https://github.com/jhy/jsoup/commit/0986da6) into jhy:master  on Apr 4, 2016

The commit itself was from 2015

> pafgoncalves committed on May 3, 2015

But I can't see these changes in current version of [Jsoup.java](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/Jsoup.java) and there's no trace of this in [Jsoup.java's history](https://github.com/jhy/jsoup/commits/master/src/main/java/org/jsoup/Jsoup.java).

Why?

**Comment by jhy** [comment]
I just had a look - it's because I tidied up the PR before merging, and I removed the` Jsoup.connect(url, proxy)` method, in favor of `Jsoup.connect(url).proxy(proxy)`.

3f39a5a48504b2a5cc9934b63f3e03420de1abc5
