### ISSUE TITLE
Element should override Node methods, such as removeAttr

### ISSUE THREAD

**Issue by tobia** [jhy/jsoup#1193]
Methods that are inherited from Node and not overridden, return a Node instance, even when they are called on an Element instance. This prevents chaining:

    Element foo = ...
    foo.addClass("isfoo").removeAttr("bar"); // OK
    foo.removeAttr("bar").addClass("isfoo"); // ERROR Node#addClass not found

**Comment by jhy** [comment]
Makes sense, would welcome a PR if you want to do one?
