### ISSUE TITLE
jsoup doesnt seem to read inner #document

### ISSUE THREAD

**Issue by NSBlackMirror** [jhy/jsoup#1198]
`<div id="load-iframe"> 
     <iframe id="embedvideo" src=“https://someurl.com” allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" style="width:100%;height:100%"></iframe> 
#document
<!doctype html>
    </div> 
    <div id="myVideo"></div> `

**Comment by jhy** [comment]
Yes, iframe contents are not part of the document flow. You can fetch the contents and add them to to DOM if you like.
