### ISSUE TITLE
Jsoup 1.11.3 Connection.Response Authorization doesn't work with JRE 1.8.0_201

### ISSUE THREAD

**Issue by radekczdev** [jhy/jsoup#1199]
Hi,
After changing the JRE version from 1.8.0_161 to 1.8.0_201, authorization on website stopped working, there is now an error with code 401 (not authorized). I have been working, why it has stopped. Reverting the JRE version back helped.

> org.jsoup.HttpStatusException: HTTP error fetching URL. Status=401, URL=**

fragment of stack trace:

> at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)

for code:

`this.response = Jsoup
					.connect(url)
					.timeout(30000)
					.method(Connection.Method.GET)
					.userAgent(userAgent)
					.header("Authorization", "Negotiate " + authData)
					.header("DNT", "1")
					.header("Connection", "keep-alive")
					.header("Keep-Alive", "timeout=5, max=1")
					.execute();`

seems like something in new Java version has changed. Is it known issue?

**Comment by radekczdev** [comment]
I have actually found the problem:
I am creating request to Negotiate/NTLM requesting scheme.
Java 1.8.0_161 provides logging in using SSO (for domain user) by default.
Java 1.8.0_201 doesn't take into consideration logging like this by default. 
The solution was working for me, because the windows user, which was starting the JAR file, has sufficient rights to open the URL. Status 401 here means, that negotiate process has been started.

**Comment by jhy** [comment]
@radekczdev how did you enable SSO domain login on _201?

**Comment by radekczdev** [comment]
@jhy Actually, I wanted to use the passed credentials, I didn't want to use SSO. This app will trigger by the remote service. So changing the JRE version helped me to resolve the standard bug "it works for me" :)

I have implemented _Authenticator_, which is trying to login with provided credentials only 2 times (in case of failure - more can cause account lock). Now my Response looks like this:
`this.response = Jsoup
						.connect(url)
						.timeout(30000)
						.method(Connection.Method.GET)
						.userAgent(userAgent)
						.execute();
`

**Comment by ankitpro** [comment]
For me changing the user agent to "Mozilla/5.0" alone fixed the issue.
Document doc = Jsoup.connect(url)
                            .userAgent("Mozilla/5.0")
                            .timeout(30000)
                            .get();

**Comment by jhy** [comment]
Closing out - looks like a site and UA specific issue, not something jsoup can handle.
