### ISSUE TITLE
Jsoup new version,emptyTag : img overTag is not append! But i need append with</img>

### ISSUE THREAD

**Issue by 1026170901** [jhy/jsoup#1200]

**Comment by 1026170901** [comment]
String htmlstr = "<img src=\"{条形码}\" title=\"shape\" width=\"115\" height=\"50\"></img>";
Document document = Jsoup.parse(htmlstr);
String html = document.body().html();
		System.out.println(html);
// resutl : \<img src="{条形码}" title="shape" width="115" height="50">

//notice : \</img> is missing, but i hope it end with </img>!!! so what can i do it?

**Comment by jhy** [comment]
HTML doesn’t need close tags for img tags or other self closing tags. I would suggest reviewing why you. We’d it. You can use the XML output syntax if you want to output xml.
