### ISSUE TITLE
can't able to parse the html with &# 

### ISSUE THREAD

**Issue by curdlx** [jhy/jsoup#1204]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/7258307/55872381-6bfaf200-5bbf-11e9-9463-5f2fb81b2979.png">

result with jsoup:
![1554892361304](https://user-images.githubusercontent.com/7258307/55872292-348c4580-5bbf-11e9-9d94-1231ec978a8c.jpg)

when I parse the html like above, I get the wrong span text。
when I use HtmlCleaner,it's ok。 
what's the problem with me?

**Comment by laxika** [comment]
You are trying to encode characters that are not on any valid UTF-8 range so this is the expected behavior.

**Comment by jhy** [comment]
Also, apart from being out of range... it works?

https://gist.github.com/jhy/0d7de86c49f47ee19c06ae086c520638

I get this char back `undefined u+1875d` which is `&#100189;`

Please don't post pictures of code. Please provide a full code sample with what you want and what you're getting (in a java test case) so we can repro.
