### ISSUE TITLE
NPE: NULL href in <a> causes protocol analysis crash if valid protocols contains '#'

### ISSUE THREAD

**Issue by wolfkopp** [jhy/jsoup#1205]
Version 1.11.3:
if we have &lt;a href&gt; and protocol '#' is allowed -> null pointer.
java.lang.NullPointerException
at org.jsoup.safety.Whitelist.isValidAnchor(Whitelist.java:555)
at org.jsoup.safety.Whitelist.testValidProtocol(Whitelist.java:538)
at org.jsoup.safety.Whitelist.isSafeAttribute(Whitelist.java:507)

Problem: in Whitelist:
private boolean testValidProtocol(Element el, Attribute attr, Set<Protocol> protocols) {
String value = el.absUrl(attr.getKey());
if (value.length() == 0) value = attr.getValue();
// value is now null
..
if (prot.equals("#")) {
if (isValidAnchor(value)) {
->
private boolean isValidAnchor(String value) {
// crash now with null pointer (called in prot.equals("#"))
return value.startsWith("#") && !value.matches(".*\\s.*");
}

**Comment by jhy** [comment]
Hi -- this was fixed in #1065. Need to get a release out! Thanks for the report.
