### ISSUE TITLE
Selector.select removes duplicates

### ISSUE THREAD

**Issue by zeeg-lynch** [jhy/jsoup#1209]
Hi, 
I'd like to apologize in advance if there already is such an issue, but I didn't find one.
I've been using Jsoup for HTML parsing, specifically this page: http://darksouls.lljk.net/1.04/weapon/shortsword

and noticed that Selector.select() method removes duplicates, which, I believe is the wrong behavior. Actually, it doesn't remove them, it just adds them to LHS, which doesn't store duplicate values. Here's an example of what I'm talking about:
```
Elements reinforcementLevelRows = doc.getElementsByClass("level0");
reinforcementLevelRows.forEach(System.out::println);
Elements tds = reinforcementLevelRows.select("td");
tds.forEach(td -> System.out.println(td.text()));
```
and here's the result:
```
<tr class="level0"> 
 <td class="level" valign="middle">+0</td> 
 <td class="damage" valign="middle">78</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">20</td> 
 <td class="bonus" valign="middle">C<br> 51</td> 
 <td class="bonus" valign="middle">C<br> 51</td> 
 <td class="bonus" valign="middle">–</td> 
 <td class="bonus" valign="middle">–</td> 
 <td class="reduction" valign="middle">50.0</td> 
 <td class="reduction" valign="middle">10.0</td> 
 <td class="reduction" valign="middle">35.0</td> 
 <td class="reduction" valign="middle">35.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">38.0</td> 
 <td class="stability" valign="middle">32</td> 
 <td class="required_materials" valign="middle"></td> 
</tr>
+0
78
0
20
C 51
–
50.0
10.0
35.0
40.0
38.0
32
```

As you can see, in the second case, after selecting of "td"-s, it just removed cells which have duplicate values. I can suggest replacing LHS with ArrayList or smth here:
Selector.java, Line 46:
```
 LinkedHashSet<Element> elements = new LinkedHashSet();
```

**Comment by krystiangorecki** [comment]
Can't reproduce. I'm using latest version 1.11.3 and executing your code correctly shows duplicated elements:
```<tr class="level0"> 
 <td class="level" valign="middle">+0</td> 
 <td class="damage" valign="middle">78</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">0</td> 
 <td class="damage" valign="middle">20</td> 
 <td class="bonus" valign="middle">C<br> 51</td> 
 <td class="bonus" valign="middle">C<br> 51</td> 
 <td class="bonus" valign="middle">–</td> 
 <td class="bonus" valign="middle">–</td> 
 <td class="reduction" valign="middle">50.0</td> 
 <td class="reduction" valign="middle">10.0</td> 
 <td class="reduction" valign="middle">35.0</td> 
 <td class="reduction" valign="middle">35.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">40.0</td> 
 <td class="resistance" valign="middle">38.0</td> 
 <td class="stability" valign="middle">32</td> 
 <td class="required_materials" valign="middle"></td> 
</tr>
+0
78
0
0
0
20
C 51
C 51
–
–
50.0
10.0
35.0
35.0
40.0
40.0
40.0
38.0
32

**Comment by zeeg-lynch** [comment]
> Can't reproduce. I'm using latest version 1.11.3 and executing your code correctly shows duplicated elements:
> 
> ```
>  <td class="level" valign="middle">+0</td> 
>  <td class="damage" valign="middle">78</td> 
>  <td class="damage" valign="middle">0</td> 
>  <td class="damage" valign="middle">0</td> 
>  <td class="damage" valign="middle">0</td> 
>  <td class="damage" valign="middle">20</td> 
>  <td class="bonus" valign="middle">C<br> 51</td> 
>  <td class="bonus" valign="middle">C<br> 51</td> 
>  <td class="bonus" valign="middle">–</td> 
>  <td class="bonus" valign="middle">–</td> 
>  <td class="reduction" valign="middle">50.0</td> 
>  <td class="reduction" valign="middle">10.0</td> 
>  <td class="reduction" valign="middle">35.0</td> 
>  <td class="reduction" valign="middle">35.0</td> 
>  <td class="resistance" valign="middle">40.0</td> 
>  <td class="resistance" valign="middle">40.0</td> 
>  <td class="resistance" valign="middle">40.0</td> 
>  <td class="resistance" valign="middle">38.0</td> 
>  <td class="stability" valign="middle">32</td> 
>  <td class="required_materials" valign="middle"></td> 
> </tr>
> +0
> 78
> 0
> 0
> 0
> 20
> C 51
> C 51
> –
> –
> 50.0
> 10.0
> 35.0
> 35.0
> 40.0
> 40.0
> 40.0
> 38.0
> 32
> ```

Oh, alright, looks like I'm using an outdated version (1.8.3), which for some reason popped out as the first link on google search for maven repo. I guess I'll just upgrade my dependency then. Thank you for a  quick response and have a nice day!
