### ISSUE TITLE
simulated login cant get correct cookies when i deploy in my server

### ISSUE THREAD

**Issue by hackedbyxx** [jhy/jsoup#1210]
i'v tried for several time,all result is normal at my local pc,but never login success in server。my project build with springboot

**Comment by laxika** [comment]
Could be an encoding issue? Do you set the default encoding to UTF-8 everywhere?

**Comment by hackedbyxx** [comment]
thank you,but it doesnt work.my project is utf-8,my pc system is windos,and server is centos utf-8,is there something i left?

**Comment by jhy** [comment]
Would suggest asking on StackOverflow and providing enough detail that someone can actually replicate and help you.
