### ISSUE TITLE
Duplicated attribute parsing problem 

### ISSUE THREAD

**Issue by sinichkin** [jhy/jsoup#1219]
In case there is duplicated tag attribute Jsoup parses the last one, but Chrome browser takes the first one.

**Comment by krystiangorecki** [comment]
https://github.com/jhy/jsoup/blob/7ff7c43e9fbf4bbaf2b4517b3d4f8a429d87d3bb/src/main/java/org/jsoup/parser/Token.java#L128

**Comment by jhy** [comment]
Thanks! Fixed
