### ISSUE TITLE
Fixing <textarea/> leaves some unwanted things.

### ISSUE THREAD

**Issue by krystiangorecki** [jhy/jsoup#1220]
Someone noticed [here](https://stackoverflow.com/questions/56296170/jsoup-messing-the-html-with-self-closing-text-area/56297927) jsoup doesn't parse `<textarea/>` correctly.
Parsing this HTML
```
<div>
   <div>
      <textarea/>
   </div>
</div>
```
results in:
```
<div>
   <div>
      <textarea></textarea>&lt;/div&gt;&lt;/div&gt;
   </div>
</div>
```
I appreciate it nicely recovered and resolved textarea to opening and closing tag but it added some unnecessary things.
Using XML parser is not a solution as we're talking about HTML.
To reproduce:
```
Document doc = Jsoup.parse("<div><div><textarea /></div></div>");
System.out.println(doc);
```

**Comment by jhy** [comment]
@krystiangorecki , how come you closed your PR?

**Comment by jhy** [comment]
Oh, I see you have #1222 open instead. Thanks.

**Comment by jhy** [comment]
Thanks, merged!
