### ISSUE TITLE
Add a copy-constructor to the Whitelist

### ISSUE THREAD

**Issue by futaz** [jhy/jsoup#1223]
Hi!

I am using Jsoup in my project to sanitize html content from user inputs. In my application there are a few `Whitelist` configuration which I use most of the time. I have a util class which contains these configurations:

```java
public class HtmlUtil {

    public Whitelist basic(){
        return new Whitelist()
                .addTags("b", "strong", "i", "em", "u");
    }

    public Whitelist forTemplates(){
        return basic()
                .addTags("span", "img")
                .addAttributes("span", "style");
    }
}
```

I would like to introduce a `private static final Whitelist` for each of these configs to prevent unnecessary instantiations every single time I use them. But in some cases it is requred to extend these "basic" rules with some function-specific stuff like `HtmlUtil.basic().addTags("img");`. Now I can safely do this, because every time I call `HtmlUtil.basic()` I get a new instance. But as soon as I introduce the constants to optimize the code and publish them via a getter method, there is a risk to someone call one getter and modifies the basic config, because it is mutable.

It would be asewome if `Whitelist` had a copy constructor to do the following:

```java
public class HtmlUtil {

    private static final Whitelist BASIC_CONFIG = new Whitelist()
                .addTags("b", "strong", "i", "em", "u");

    private static final Whitelist CONFIG_FOR_TEMPLATES = new Whitelist(BASIC_CONFIG)
                .addTags("span", "img")
                .addAttributes("span", "style");

    public Whitelist basic(){
        return new Whitelist(BASIC_CONFIG);
    }

    public Whitelist forTemplates(){
        return new Whitelist(CONFIG_FOR_TEMPLATES);
    }
}
```

Now when someone calls `HtmlUtil.basic()` it is more efficient beacuse of the constant and is safe to modify because of the copy-constructor.

**Comment by jhy** [comment]
Thanks for the suggestion! This is implemented (with #1464).

https://github.com/jhy/jsoup/blob/02bb8a90cad36fe00cf5887a2924df658b084ff5/src/main/java/org/jsoup/safety/Safelist.java#L201
Please take a look at let me know if that suits your usecase.
