### ISSUE TITLE
Incorrect Farsi parsing to plain text

### ISSUE THREAD

**Issue by MarcFletcher** [jhy/jsoup#1227]
Both are expected to produce the same output, although the first one incorrectly strips the 'half-space' `(\u200C)`:

    System.out.println("Incorrect: " + Jsoup.parse("نیمه\u200Cشب").text());
    System.out.println("Correct: " + "نیمه\u200Cشب");

Output:

![Sample Output](https://i.imgur.com/7hfkrIe.png)

In Farsi this is quite a considerable change of meaning.

**Comment by jhy** [comment]
This comes from #978, where we strip invisibles from text, so matching is easier (removing soft hyphens in that case).

This character is not a half-space though, it's the zero-width-non-joiner.

https://unicodelookup.com/#0x200c/1
https://en.wikipedia.org/wiki/Zero-width_non-joiner

Probably need to review what gets stripped in the invisibles method. &shy is OK to strip as it is more of a render time thing (width of browser) vs semantic as in this example.

**Comment by jhy** [comment]
Thanks, fixed with https://github.com/jhy/jsoup/commit/91ca25b341bc5ad1c364b8e7389287c45ca9df2c
