### ISSUE TITLE
Source package doesn't meet standard requirements for source packages

### ISSUE THREAD

**Issue by jcapik** [jhy/jsoup#123]
Hello.

I'd like to kindly ask You to provide Linux distribution maintainers with source package prepared for building with package build-systems. The most common way of building Java from sources is with help of Maven. It would be nice, if You could create a correct source directory tree and place the pom.xml as well as the LICENSE.txt file in the top level directory.

The result should look like this:
./pom.xml
./LICENSE.txt
./src/main/java/org/jsoup/*

But currently there's just the following:
./META-INF/MANIFEST.MF
./org/jsoup/*

We had to recreate the correct structure during the build procedure by moving the org directory to /src/main/java/ and placing the separately downloaded pom file to the new top level directory. 
Please, apply these changes in order to make our lives easier ... I would appreciate that for new jsoup releases and other distribution maintainers probably for the current jsoup release too.

Thanks in advance.

Regards,
Jaromir.

**Comment by jhy** [comment]
Just reviewing this... The files listed on https://github.com/jhy/jsoup/releases seem to meet the bill. And we can't be the only repo on Github that distrubuters want to use. Can you use those zips? Locations are static, just need to follow a redirect which I'm sure is OK.
