### ISSUE TITLE
input with two values

### ISSUE THREAD

**Issue by aditsu** [jhy/jsoup#1234]
I've encountered an input field (type hidden) with two value attributes, such as:
`<input name="test" value="foo" type="hidden" value="bar"/>`
When I submit the form in a browser, the first value gets submitted ("foo" in this case) - tested with Chromium and Firefox.
But when I parse the html with jsoup, the element gets the second value ("bar" in this case), overriding the first one.

**Comment by krystiangorecki** [comment]
Duplicate of #1219

**Comment by jhy** [comment]
Thanks - added testcase to verify fixed with #1219
