### ISSUE TITLE
The Jsoup.isValid return false when the tag and attributes are all defined in whitelist

### ISSUE THREAD

**Issue by willpowerforever** [jhy/jsoup#1239]
The Jsoup.isValid will return false for the input below, the tags and attributes are all in whitelist:
<img src=https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png?test=123 alt='Company Logo' style='background-color:#fff;' />

This can be displayed correctly in browser. In addition, I found if use Jsoup.parse, I printed out the Element returned, I can see the parsing will just add double quote " around the src.

**Comment by dota17** [comment]
Hi,friend. I think we should put single quotes after src and Style is not in the whitelist . You can try this
```
<img src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png?test=123' alt='Company Logo' />
```
thank

**Comment by jhy** [comment]
I also suggest that you run the cleaner and take the output. The isValid() is primarily for quick UI to the user. You should always use the output of the cleaner, and it will always be valid, by definition.
