### ISSUE TITLE
Formatted text

### ISSUE THREAD

**Issue by mazko** [jhy/jsoup#124]
Since v 1.6.1 code below

body().wrap(&quot;&lt;pre&gt;&lt;/pre&gt;&quot;).text()

clear new lines. Instead &quot;hello\n&quot; (html contains &lt;BR/&gt; tag) it returns just &quot;hello&quot;

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
