### ISSUE TITLE
Preserve whitespace with style white-space pre

### ISSUE THREAD

**Issue by dkrahn** [jhy/jsoup#1240]
It would be important to preserve the `white-space` behavior.
If I have a span tag with this style set to `pre` or `pre-wrap` it should preserve it´s characters, in my case a tab(&#9;).

Is it possible?

**Comment by dkrahn** [comment]
Any comments on this? Is there a way I could work around this limitation?

**Comment by dkrahn** [comment]
Any updates?

**Comment by dkrahn** [comment]
Any updates?

**Comment by jhy** [comment]
Jsoup doesn't parse CSS / render the body, so it doesn't know that a tag is styled to do white space preserving. You can either disable Pretty Printing, or you can use the wholeText() method, or grab the TextNodes directly. The spaces are all still in the DOM, just not provided by default on the text() method.

**Comment by dkrahn** [comment]
The problem is that after I process the HTML using JSOUP, I cannot recover the HTML with the TAB character. Is there any way I can do this?

**Comment by jhy** [comment]
I added a testcase in ParserTest (8e7dedbb257d2080b058cb732d068114d4b2bb67) to show the different options. For output HTML, disable the pretty-printer and the tabs will be retained.
