### ISSUE TITLE
If there is a space in the value of the class attribute, it will only recognize the value of the class attribute before the space.

### ISSUE THREAD

**Issue by xiaoyicomic** [jhy/jsoup#1241]
(I am Chinese.My English is not good.Please don't get angry.)
If there is a space in the value of the class attribute, it will only recognize the value of the class attribute before the space.
For example:
<div class="section info"/>
<div class="section"/>

document.selectFirst(".section") will return the div whose class is section info.

**Comment by krystiangorecki** [comment]
That's correct behavior.
`class="section info"` isn't one class, it's two separate classes. According to HTML specification:
> 3.2.3.6 The class attribute
> Every HTML element may have a class attribute specified.
> The attribute, if specified, must have a value
>that is a **set of space-separated tokens representing the various classes** that the element belongs to.
> The classes that an HTML element has assigned to it consists of all the classes returned when
> the value of the class attribute is split on spaces. (Duplicates are ignored.)

https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#classes

**Comment by xiaoyicomic** [comment]
I haven't studied css. Thank you for your answer very much.
