### ISSUE TITLE
In-line styles with nested quotes fails on isValid 

### ISSUE THREAD

**Issue by nazimamin** [jhy/jsoup#1243]
In-line styles with nested quotes fail on Cleaner/Jsoup isValid function

I see #988, but it doesn't fix it completely. 

For example this will return false, even though it should be true:  `<div style="font-family: 'Calibri'">Will fail</div>`

Looks like the above gets converted to `<div style="font-family: " Calibri''>Will fail</div>` in copySafeNodes hence returning false instead of true.

**Comment by jhy** [comment]
Thanks - this doesn't repro in the current HEAD version (didn't try on older versions).

Please open with a testcase if you see a current repro.
