### ISSUE TITLE
Fail to parse the nodes existing  <source>myName</source>

### ISSUE THREAD

**Issue by chenFlyingkite** [jhy/jsoup#1245]
The possible node is from *.xliff files, like XCode's string table

Let we have a file named en.xliff, snippet of content = 

```
    <body>
      <trans-unit id="%@ Error: %ld">
        <source>%1$@ Error: %2$ld</source>
        <target>%1$@ Fehler: %2$ld</target>
        <note>Fallback Error Failure Reason Format</note>
      </trans-unit>
```

JSoup using parse by ( `Element e = Jsoup.parse("D:\en.xliff", "UTF-8")` )
and get those nodes by ( `e.getElementsByTag("source")`  )
visiting its each node, and found each node's only receive 
![x](https://user-images.githubusercontent.com/30795482/62441511-fbd43580-b786-11e9-85b7-9b04d39c272b.PNG)

Expect the node named `<source></source>` being parsed correctly

**Comment by jhy** [comment]
Looks OK to me on current version: https://try.jsoup.org/~wRnNRquKuZuvy_V_DxjSg3zJDtE

If you can repro, please provide a minimal test case.
