### ISSUE TITLE
HttpConnection.java needs a conn.disconnect outside the catch block too

### ISSUE THREAD

**Issue by shikhirsingh** [jhy/jsoup#1249]
I'm getting a too many files open error when I use jSoup to hit over 1000 websites sequentially. It seems we need a conn.disconnect() in the org.jsoup.helper.HttpConnection class in the executor method. Right now, it's only in the catch block. Even the comment say it's needed.

**Comment by jhy** [comment]
Can you point out the flow in the current implementation where you see .close not getting called. The happy path (.parse etc) and the exception paths all call safeClose().

https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/HttpConnection.java#L828

**Comment by Hardcore-fs** [comment]
I would check your code.....
My implementation can run 200-500 threads and easily process 50,000 pages....
The only limit is the connection bandwidth, which has to be throttled .. since it can take most sites down..


perhaps check your os file limit....

**Comment by jhy** [comment]
Closing this out - impl has changed marginally and I have added a couple finally blocks to close streams on error immediately (e.g. 78f42893727546ef1d2843ca581c322292659f1c). But I don't think that was the issue that @shikhirsingh was seeing.
