### ISSUE TITLE
`isBinary` detect proper HTML page as binary

### ISSUE THREAD

**Issue by panthony** [jhy/jsoup#1250]
Failing test case:
```java
    @Test
    public void testBinaryFail() throws IOException {
        Jsoup.parse(new URL("https://www.searspartsdirect.com/repair-parts-for-kenmore-106w14f/0582/0160000.html"), 50000);
    }
```

Detecting a binary file is complicated :/

At one point in my own project I was using something like:

```java
public abstract class NonPrintableDetector {

    private final static Pattern NON_PRINTABLE_PATTERN = Pattern.compile("\\p{C}", Pattern.UNICODE_CHARACTER_CLASS);

    /**
     * @param value Sequence of chars to test against non printable characters
     * @param maxRatio Maximum accepted ratio of non printable characters (between 0.0 and 1.0)
     * @return True if ratio of non printable characters is above maxRatio
     */
    public static boolean isAboveThreshold(final CharSequence value, final float maxRatio) {
        if (value == null || value.length() == 0) {
            return false;
        }

        // check for high ratio of non printable characters
        final Matcher matcher = NON_PRINTABLE_PATTERN.matcher(value);

        int nonPrintableChars = 0;
        while (matcher.find()) {
            nonPrintableChars++;
        }

        return nonPrintableChars > Math.ceil(value.length() * maxRatio);
    }

}
```

But even so I had PDF accepted because it had a bunch of textual metadata near the beginning of the file...

I finally resorted to use the Tika library because of its knowledge of magic bytes, etc.

IMO JSoup should not even attempt to do this or at least give a way to be disabled because I for-see a lot of false positive or negative.

**Comment by jhy** [comment]
@HansBrende thanks for the feedback. I agree, this needs to be reworked. I don't know that we want to bring in Tikka, want to keep the depencies low. My thought is, if we leave it in, to add it to the section where the Connection is tested for MIME type. If there is no MIME type, try and determine if it is binary. Still, that would benefit from an override option, so it might be simplest to remove entirely.

**Comment by jhy** [comment]
Thanks - I removed it.
