### ISSUE TITLE
Evaluator.TagEndsWith and Tag disagree in case-sensitivity

### ISSUE THREAD

**Issue by rillig-tk** [jhy/jsoup#1257]
In jsoup 1.12.1, when a document is parsed using the XML parser, `Document.select` behaves differently when selecting elements with mixed case and namespace. Using the selector `*|mixedCase`, it is not possible to select the elements.

In `QueryParser.byTag`, the tag names in the selector are normalized.
In `Evaluator.TagEndsWith.matches`, the comparison is case-sensitive.
In `Evaluator.Tag.matches`, the comparison is case-insensitive.

~~~java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class JsoupCaseSensitivityTest {

	private final String mixedCase =
		"<html xmlns:n=\"urn:ns\"><n:mixedCase>text</n:mixedCase></html>";
	private final String lowercase =
		"<html xmlns:n=\"urn:ns\"><n:lowercase>text</n:lowercase></html>";

	@Test
	public void html_mixed_case_simple_name() {
		Document doc = Jsoup.parse(mixedCase, "", Parser.htmlParser());

		assertEquals(0, doc.select("mixedCase").size());
	}

	@Test
	public void html_mixed_case_wildcard_name() {
		Document doc = Jsoup.parse(mixedCase, "", Parser.htmlParser());

		assertEquals(1, doc.select("*|mixedCase").size());
	}

	@Test
	public void html_lowercase_simple_name() {
		Document doc = Jsoup.parse(lowercase, "", Parser.htmlParser());

		assertEquals(0, doc.select("lowercase").size());
	}

	@Test
	public void html_lowercase_wildcard_name() {
		Document doc = Jsoup.parse(lowercase, "", Parser.htmlParser());

		assertEquals(1, doc.select("*|lowercase").size());
	}

	@Test
	public void xml_mixed_case_simple_name() {
		Document doc = Jsoup.parse(mixedCase, "", Parser.xmlParser());

		assertEquals(0, doc.select("mixedCase").size());
	}

	@Test
	public void xml_mixed_case_wildcard_name() {
		Document doc = Jsoup.parse(mixedCase, "", Parser.xmlParser());

		// FIXME: should be 1, to behave in the same way as lowercase_wildcard_name.
		assertEquals(0, doc.select("*|mixedCase").size());
	}

	@Test
	public void xml_lowercase_simple_name() {
		Document doc = Jsoup.parse(lowercase, "", Parser.xmlParser());

		assertEquals(0, doc.select("lowercase").size());
	}

	@Test
	public void xml_lowercase_wildcard_name() {
		Document doc = Jsoup.parse(lowercase, "", Parser.xmlParser());

		assertEquals(1, doc.select("*|lowercase").size());
	}
}
~~~

**Comment by Stephan972** [comment]
Jsoup 1.11.2 is also affected.

**Comment by dota17** [comment]
In jsoup, using `Parser.xmlParser()` to generate the DOM is not the same as using `Parser.htmlParser()`.
E.g.
tagName in `Parser.xmlParser()` - case sensitive 
tagName in `Parser.htmlParser()` - lower case.

And when we use the selector - `*|mixedCase` - the string is converted to lowercase.
Therefore, in the case `Parser.xmlParser()`, the selector will find nothing.

**Comment by rillig-tk** [comment]
@dota17 My complaint is that it is not _possible at all_ to select an XML element called `mixedCase` by using a selector. If you know otherwise, please tell me, maybe I didn't get something.

**Comment by jhy** [comment]
Thanks for the report and the test cases! 

I fixed it by standardizing on normalized comparisons - so case-insensitive.

Ideally, the QueryParser would know if we are in case-sensitive or insensitive mode, and act accordingly (for tags and attributes). We could pass that in when creating the selector. That way in XML, you could differentiate between tag `Foo` and tag `foo`. But for now, this should do.
