### ISSUE TITLE
Getting wrong data 

### ISSUE THREAD

**Issue by raysnehanjana** [jhy/jsoup#1262]
<a data-type=\"imglink\"  data-tag=\"IMG\"    data-name=\"PayPal Credit logo\" data-block=\"editable\" href=\"#\" target=\"_blank\" style=\"text-decoration: none;\">\n                                <img  src=\"http://epidm.edgesuite.net/CMS/Coding/PayPal/2018/Global/PayPalCredit_logo_blue2.png\" alt=\"PayPal CREDIT\" title=\"PayPal CREDIT\" height=\"50\" border=\"0\" style=\"display:block; font-family:'pp-sans-big-medium', Tahoma, Arial, sans-serif; font-size:32px; color:#003288;\" `/></a>```

while reading this :

Document doc = Jsoup.connect(urlString).get();
		
		
		Elements body = doc.select("*");
		body.unwrap();
		
		Map<String, Set<String>> map = new HashMap<String, Set<String>>();
		for (Element element : body) {

				System.out.println(elements.get("data-name"));
              }

Output : \"PayPal  Correct Output should be : \"PayPal Credit logo\"

Why this is happening? Any solution? Please mail me at ray.snehanjana@gmail.com

**Comment by dota17** [comment]
Hi,friend.I did not find elements.get().I don't know what it means.But you can try this.
```
for (Element element : body) {
    System.out.println(element.attr("data-name"));
}
```
thanks

**Comment by jhy** [comment]
Thanks @dota17
