### ISSUE TITLE
HTTP PUT method cannot create param url

### ISSUE THREAD

**Issue by anjia0532** [jhy/jsoup#1265]
Spring mvc code
```java
    @RequestMapping(value = "/test/url",
        method = RequestMethod.PUT,
        produces = MediaType.APPLICATION_JSON_VALUE)
    public void test(@RequestParam String id) {
        // something;
    }
```

client code
```java
   Connection conn = Jsoup.connect("http://localhost:8080/test/url").header("Authorization", "bearer  xxx") 
            .header("Content-Type", "application/json;charset=UTF-8").header("Accept", "application/json;charset=UTF-8").ignoreContentType(true) 
            .method(Connection.Method.PUT)
            .data("id", "xxx");
Connection.Response resp = conn.execute();
System.out.println(resp.body());
// http code is 500
// error msg is Required String parameter id is not present
```
the jsoup HttpConnection code
https://github.com/jhy/jsoup/blob/8d1d503913a68e549b5c4a94717c62cf3f64507a/src/main/java/org/jsoup/helper/HttpConnection.java#L716-L726

Method is `PUT` ,so `methodHasBody`  is `true` and skip to `serialiseRequestUrl(req); `

why?

if i want to set body ,i can use `conn.requestBody` ,if i want to set header `conn.header`

**Comment by jhy** [comment]
This is per the HTTP spec - POST and PUT provide their form data in the body. If you want to force it to use the querystring, you can set an empty body or modify the URL directly.

**Comment by anjia0532** [comment]
Thank you for your reply.
