### ISSUE TITLE
On the Processing of P Label

### ISSUE THREAD

**Issue by lanisha** [jhy/jsoup#1267]
I feel like there's something wrong with the processing of P tags.
If the HTML code content is `<p><span>hello</span><div>brother</div></p>`
After formatting is
``` 
<p>
    <span>hello</span>
    <div>brother</div>
</p>
```

why HtmlTreeBuilder.TagSearchEndTags contain p label。

**Comment by jhy** [comment]
I guess that you are having issue with the fact that the parse output is:

```
  <p><span>hello</span></p>
  <div>
   brother
  </div>
  <p></p>
```

?

This is the correct output for HTML5. P tags can't hold DIVs. And then the closing P tag gets uplifted into a full `<p></p>` to hold the (empty) para. Works per HTML5 spec and Chrome browsers etc.
