### ISSUE TITLE
Elements of type E in any namespace ns...

### ISSUE THREAD

**Issue by Stephan972** [jhy/jsoup#1268]
The wildcard namespace matcher seems to miss some elements.

    String xml = "<S:Body>foo</S:Body>";
    Document doc = Jsoup.parse( xml , "",  Parser.xmlParser());

    Element wildcardBody = doc.selectFirst("*|Body"); // wildcardBody == null (incorrect)
    
    Element sBody = doc.selectFirst("S|Body"); // sBody != null (correct)

See it in action here :
http://try.jsoup.org/~WuRM4FW7nY7gso0c_rEIcbc_8aE

**See also :** #1257 (Evaluator.TagEndsWith and Tag disagree in case-sensitivity)
**Jsoup version :** 1.11.2

**Comment by jhy** [comment]
(Comment from #1308)

I think the implementation currently is a bit lazy and only works through the HTML parser, not the XML parser. The latter actually does namespaces; the former just puts it all into the tag name, and the selector does some string matching (from memory). So we'll need to update the selector to test namespaces specifically.

**Comment by jhy** [comment]
Actually no - the namespace code is OK, it's the caps. I should have read your see-also note better :)

**Comment by jhy** [comment]
Same root-case as #1257 . Thanks for the report!
