### ISSUE TITLE
Brotli decompression

### ISSUE THREAD

**Issue by NandanDesai** [jhy/jsoup#1270]
Does Jsoup support decoding Brotli compressed responses?

**Comment by krystiangorecki** [comment]
No, only `gzip` and `deflate`.
https://github.com/jhy/jsoup/blob/4c142cacf4d92b2214b3858e033d518ecdbf57f5/src/main/java/org/jsoup/helper/HttpConnection.java#L786

**Comment by NandanDesai** [comment]
Ok. Do you have any plans of adding it in the future?

**Comment by krystiangorecki** [comment]
I don't know. Looks like not in the near future.

**Comment by NandanDesai** [comment]
ok thank you for your quick response!
