### ISSUE TITLE
<style> may contain invalid characters that should have been escaped

### ISSUE THREAD

**Issue by hannibal218bc** [jhy/jsoup#1271]
When setting an output charset, Jsoup does not automatically convert all characters unsupported by the target charset to something useful. The resulting document thus may contain characters not included in the desired charset, or miss characters at all.

See this live example: http://try.jsoup.org/~XXVcInN27Ap0yOjjTxRii6CCB-I
The <style> element contains non-ASCII characters.

A similar issue with HTML Comments was reported in #1106 , where the fix is simply to use `Entities.escape()` to encode the missing characters to HTML entities.

Within a `<style>` element, HTML entities do not work in the same way, and a different encoding would be needed. And maybe an even different encoding with `<script>`, probably also depending on the content's type...? Is this even still in-scope for JSoup?

**Comment by frostblazergit** [comment]
I don't think jsoup should convert `css/style/comment/javascript` because they are different types and require different parser.

**Comment by hannibal218bc** [comment]
While I agree that those are different types, the CSS/style/... parsing is operating on the parsed element's contents (characters) and is hence dependend on the document being parsed correctly at all. This issue is only about reading/writing the correct characters.
The issue here is that the /characters/ of such data nodes are sometimes not affected by a changed output charset, garbage is produced and no error is raised.


e.g. when you declare a charset by means of `<?xml version="1.0" encoding="UTF-8"?>` or `<meta charset="UTF-8">` then you declare the whole document to be saved in that charset.

Let's say you have this simple document as an example in UTF-8:
```
<html>
<meta charset="UTF-8">
<body>
<script>alert('Script Text with Umlauts ÄÖÜßÄ');</script>
<p>Body Text with Umlauts ÄÖÜßÄ</p>
</html>
```

When you parse that in JSoup, set outputCharset to ASCII, change the `meta charset` declaration and save the file, this is the result:
```
  <script>alert('Script Text with Umlauts ?????');</script>
  <p>Body Text with Umlauts &Auml;&Ouml;&Uuml;&szlig;&Auml;</p>
```

So the characters are preserved/converted for HTML, and destroyed within DataNodes - not even an exception is thrown.

However, if you convert to ISO-8859-1 (where all of the characters are present), then both instances are preserved correctly - which is fine.

**Comment by jhy** [comment]
@hannibal218bc what is the proposal though? Because we can't / shouldn't escape `script` or `style` contents, because they don't get unescaped on parsing. I don't know of a solution here - the format cannot support UTF8 characters when forced into ascii mode.

**Comment by hannibal218bc** [comment]
@jhy thank you for your comments.
I had expected the conversion to either:
- produce useful output, or
- raise an exception somewhere
and not produce garbage output. 

Now I realize this is how `String.getBytes()` is supposed to work - quoting the JavaDoc https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes(java.nio.charset.Charset) :
>  This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement byte array. The CharsetEncoder class should be used when more control over the encoding process is required.

So this isn't JSoup's fault at all.
Sorry for the noise.
