### ISSUE TITLE
Add new language on documents (Korean)

### ISSUE THREAD

**Issue by Changhwan-Son** [jhy/jsoup#1273]
Hello. I’m 23-year-old student in Korea. At first, I am impressed with your project. 
So I want to commit for this project.

But, I am not a professional programmer. I can’t commit things writing codes...
So I would like to add Korean version of your documents so that it can help Korean developers to use this project.

I want to hear your opinion. I hope much more people use this useful project.

If you are okay, reply me.
I will work hard!
Thank you for read.

**Comment by jhy** [comment]
Hi -- thanks for the offer. My concern with this is that it will be exceptionally difficult for anyone to keep this up to date. It's hard enough maintaining just the English version.

Maybe you could create a site with some translations of the introductions and guides? That would be less of an initial set of work and more likely to stay evergreen.
