### ISSUE TITLE
Encoding UTF-8 chars problem while parsing in 1.12.1

### ISSUE THREAD

**Issue by SiriuzNet** [jhy/jsoup#1275]
jsoup version 1.12.1:
```java
Document doc = Jsoup.parse("Ł", "UTF-8");  \\ U+0141
System.out.println(doc);
```
Prints:
```html
<html>
 <head></head>
 <body>
  �?
 </body>
</html>
```

**Comment by krystiangorecki** [comment]
Works for me.
```
<html>
 <head></head>
 <body>
  Ł
 </body>
</html>
```
Jsoup 1.12.1, Windows 7x64, locale pl_PL, Java 1.8 161

**Comment by SiriuzNet** [comment]
Confirmed. I ran this on fresh Eclipse IDE and everything is ok. Issue is related to IntelliJ. I double checked all settings regardles encoding and still don't know why I have this. Closing.
