### ISSUE TITLE
why not support Basic Auth  and Digest Auth?

### ISSUE THREAD

**Issue by zhanglei-1987** [jhy/jsoup#1277]
why not support Basic Auth  and Digest Auth?

**Comment by jhy** [comment]
Because I figured no-one still uses them. Happy to take a PR though!

**Comment by jhy** [comment]
I have added direct support for per-request authentication in `Jsoup.connect().auth()` in #2046. Would be greatly appreciated if folks can test this in a local snapshot version and provide feedback (on the PR - #2046)
