### ISSUE TITLE
Starts with selector not working

### ISSUE THREAD

**Issue by andrfgs** [jhy/jsoup#1279]
I am using JSoup 1.11.3 and everything works flawlessly except for the **starts with** selector.

The following selector `a[href ^= ' mailto']` does not yield any results and throws exception:
> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

This is my code:
`String str = d.select("a[href ^= ' mailto']").get(0).html();`

Running the selector on Opera (Webkit), yields the correct result (by typing `$("a[href ^= ' mailto']")` in the console)

This is the page I am parsing: https://pastebin.com/si1Zy2cz

**Comment by jhy** [comment]
Thanks, confirmed and merged

**Comment by andrfgs** [comment]
Thank you a lot for all your work maintaining this library!
