### ISSUE TITLE
Jsoup version 1.12.1 doesn't support HTTP method PATCH even if in the documentation appears that it does

### ISSUE THREAD

**Issue by andreim2k** [jhy/jsoup#1285]
Hello,

When calling a web service using PATCH http method, it is bringing this error message:
"java.net.ProtocolException: Invalid HTTP method: PATCH"

Can you please tell me how can this HTTP method be supported? I can't use X-HTTP-Method-Override since the server doesn't supports it.

Thanks!

**Comment by MootezSaaD** [comment]
The problem resides in the `createConnection()` method , that returns an object of type `HttpURLConnection`, in the `HttpConnection` class.
In the line 898, the `setRequesMethod()` only accepts the following request methods : GET, POST, HEAD, OPTIONS, PUT, DELETE and TRACE.
I can try and fix this issue.

**Comment by jhy** [comment]
This is unfortunately because the stock Java HttpURLConnection we use does not allow arbitrary method names, and does not support PATCH, and makes the field protected so we can't reflect it safely.

Added an e.g. at ebb235b412dae5264ba46edba88a2bd8d7fe85fe

**Comment by jhy** [comment]
Well per https://travis-ci.org/jhy/jsoup/builds/642219197 it actually does do OK on all JDKs up to 13. And didn't warn. That's interesting, wonder if there is a setting that silently allows that the builder is setting. Might be OK to merge after all.

**Comment by joergrech** [comment]
Should PATCH work in 1.13.1? I can't get it to work - I get a "Invalid HTTP method: PATCH" with Java 11.0.9.1.

**Comment by jhy** [comment]
With current JDKs / closed modules it's not feasible to reflect in and allow PATCH. So if the underlying JDK doesn't allow it, there's no real avenue to allow it. I've added a comment on the enum.

Kind of annoying... The JDK has this source comment:

```java
// This restriction will prevent people from using this class to
// experiment w/ new HTTP methods using java.  But it should
// be placed for security - the request String could be
// arbitrarily long.
```

I think it would have been better just to have placed a string length check or some other validator if this was a concern. And ultimately, the concept of restricting what requests a client can make in the name of security is somewhat befuddling. Surely that can only sensibly be implemented on the responder's side.
