### ISSUE TITLE
Attribute prefix selector doesn't work for strings with unbalanced square brackets '[ ]'

### ISSUE THREAD

**Issue by philipjia123** [jhy/jsoup#1286]
The attribute prefix selector (`[^attrPrefix]`) doesn't work for selectors with unbalanced square brackets (commonly used for data-binding in frameworks like Angular or Polymer).

For example, attempting to select elements like `<div role="grid" [aria-label]="foo"></div>"` and `<button [aria-expanded]="bar"></button>` should be possible with something like:
`document.select("[^\\[aria-]");` or `document.select("[^'[aria-]'");` (using the escaping methods called out by TokenQueue's [chompBalanced](https://jsoup.org/apidocs/org/jsoup/parser/TokenQueue.html#chompBalanced-char-char-) method.

After debugging it looks like the problem stems from the `'\'` and `'''` characters being left in the selector strings.  QueryParser's [byAttribute](https://github.com/jhy/jsoup/blob/8d1d503913a68e549b5c4a94717c62cf3f64507a/src/main/java/org/jsoup/select/QueryParser.java#L239) method doesn't seem to unescape or remove quotes from any of the attribute selectors, including the non-regex ones.

**Comment by jhy** [comment]
Can you give me the example HTML that you are trying to match to? A test case would be ideal.
