### ISSUE TITLE
Vertsion 1.12.1 bug in CharacterReader

### ISSUE THREAD

**Issue by graydovee** [jhy/jsoup#1288]
If the webpage is inserted with some  '\ 0' intentionally, it will throw "java.io.IOException: Input is binaryand unsupported"  in the construction method of **org.jsoup.parser.CharacterReader** and  cannot be parsed

```java
    public CharacterReader(Reader input, int sz) {
        Validate.notNull(input);
        Validate.isTrue(input.markSupported());
        reader = input;
        charBuf = new char[sz > maxBufferLen ? maxBufferLen : sz];
        bufferUp();

        if (isBinary()) {
            throw new UncheckedIOException("Input is binary and unsupported");
        }
    }
  
    private static final int numNullsConsideredBinary = 10; // conservative

    boolean isBinary() {
        int nullsSeen = 0;

        for (int i = bufPos; i < bufLength; i++) {
            if (charBuf[i] == '\0')
                nullsSeen++;
        }

        return nullsSeen >= numNullsConsideredBinary;
    }
```

I consider use "return (double)nullsSeen / bufLength > ratioConsideredBinary " maybe better.
the value of ratioConsideredBinary may be open to question.

```java

    private static final double ratioConsideredBinary = 0.1; // I'm not sure

    boolean isBinary() {
        int nullsSeen = 0;

        for (int i = bufPos; i < bufLength; i++) {
            if (charBuf[i] == '\0')
                nullsSeen++;
        }

        return (double)nullsSeen / bufLength > ratioConsideredBinary;
    }
```

**Comment by jhy** [comment]
Could you give me the URL you are having problems? Whilst I like the idea of a ratio conceptually, this implementation breaks existing test cases. It doesn't detect an actual jpeg as binary, and it incorrectly tags short HTML files with only a couple of nulls.

Would be happy to take a PR if you find a good solution, with passing test cases, too.

**Comment by graydovee** [comment]
Sorry. It's too long. I just remember it's a novel website and there are many '\0' in the content.

My solution was to use HttpClient get bit array, then get the character encoding.If it's not exist,
recode the bit array with UTF-8 and parase is with Jsoup, then get the correct character encoding in html head.Finally, recode and reparse it if the character encoding different. 

I consider the correct file format can be found in the http request head in most cases, maybe we can check it before the original method.I used this method to solve problems in my program, although it maybe need  to parse twice and it can't solve the situation without information in http request header and html head.

If neither exists, we maybe can check the file head, for example, the jpeg file start with 'FFD8FF'.That's just my guess. I haven't tested it

Hoping This Helps

**Comment by jhy** [comment]
Thanks. I'm looking at this issue in #1250

**Comment by jhy** [comment]
Fixed with 5359490c56501b231d0d1d19e7eed4ffb37425d7

**Comment by trantienduchn** [comment]
Hello @jhy, do you know then this fix will be released?

**Comment by jhy** [comment]
Hi @trantienduchn, 1.12.2 is available now. https://jsoup.org/news/release-1.12.2
