### ISSUE TITLE
Current element can't select a child element if they have the same tags.

### ISSUE THREAD

**Issue by tjcoder** [jhy/jsoup#1292]
<span class='currentEl'>
    <span class='child'></span>
</span>

**Comment by jhy** [comment]
Can you add a test case so I can understand what you mean?

**Comment by tjcoder** [comment]
```
String html = "<html>" +
                "<body>" +
                "<span>" +
                "    <span>" +
                "        <h1>Scrapers</h1>" +
                "    </span>" +
                "</span>" +
                "</body></html>";

        Document document = Jsoup.parse(html);
        Element parentSpan = document.selectFirst("span");
        Element childSpan = firstSpan.selectFirst("span");
```

The values of **parentSpan** and **childSpan** are equal, I figured **parentSpan** should return its child.

**Comment by jhy** [comment]
No, select and selectFirst can match themselves. Per the [doc](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#select(java.lang.String)):

> Find elements that match the Selector CSS query, with this element as the starting context. Matched elements may include this element, or any of its children.

So your code is just selecting the current element again. Change it so that it selects a descender:

```
Element childSpan = parentSpan.selectFirst("* span");
```
