### ISSUE TITLE
jsoup removes linebreak from element

### ISSUE THREAD

**Issue by helpermethod** [jhy/jsoup#1293]
The following Kotlin script reads and then writes an XML file.

```kotlin
#!/usr/bin/env kscript

@file:DependsOn("org.jsoup:jsoup:1.12.1")

import java.io.File
import org.jsoup.Jsoup
import org.jsoup.parser.Parser

val pom = Jsoup.parse(File("pom.xml").readText(), "", Parser.xmlParser())
pom.outputSettings().prettyPrint(false)

File("pom.xml").writeText(pom.html())
```

`jsoup` seems to keep the formatting, comments, and even attribute order, which is really nice but somehow messes up the root (`<project>`) element, as shown by the `git` diff

```
-<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
-         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
+<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```

The original element has a line break after the `xmlns` attribute but `jsoup` somehow seems to remove it.

Any way to keep the linebreak?

**Comment by jhy** [comment]
Hi, thanks for the report. I don't plan on changing this. This is non-significant space, and the Attribute node doesn't have a way to encode components that aren't attribute names or values. 

Maybe a way to help here is to add a pretty-print option which wraps and aligns attribute names, but that's low on my priority. Happy if someone feels keen for it to take a PR, though.

**Comment by georgeprincelinj** [comment]
Any workaround for the above issue ?

**Comment by helpermethod** [comment]
Hi @jhy,

would love to contribute this as a PR.

There are almost no XML parsers in existence which keep the formatting intact, but jsoup already comes very close.

There are always cases where you want to make a tiny change to an XML file but keep everything (element order, attribute order, whitespace) intact to keep the number of changes small.

I'm pretty sure a lot of people would welcome this feature :).

**Comment by jhy** [comment]
Hi @helpermethod  - I'm definitely open to a PR! My main concern is increasing the memory footprint of the DOM by having to track a lot more state in the Attributes object, which obviously gets attached to so many Element objects.

One approach would be to extend Attributes to something like WhiteSpacePreservingAttribute, and use that when creating new attributes in the parse phase, if this option is enabled.

Maybe sketch out a design and we can discuss before putting too much code down. I think it would be a useful optional addition if we can keep the memory footprint of non-users down.

**Comment by helpermethod** [comment]
Hi @jhy, 

thanks for your suggestions, I that the functionality should not impact users which do not use this feature.

I'll have to think a little bit about it :).
