### ISSUE TITLE
Invalid HTML parsing with Example URL

### ISSUE THREAD

**Issue by jiminoc** [jhy/jsoup#130]
When calling Jsoup.parse(html) I'm getting odd tag balancing results on this url:

http://www.cnbc.com/id/44614459

If you look at the first paragraph of the artcle, you can see it's wrapped in a <p> tag, however after the Jsoup.parse that closing paratag is closed too soon. 

Here is the RAW HTML sample of the page

https://gist.github.com/1239766

After Parsing it looks like this (Notice now that the first line the paragraph tag is closed before it wraps up table element inside it:

https://gist.github.com/1239768

<pre>
     <p class="textBodyBlack"><span id="byLine"></span></p>
</pre>

**Comment by jhy** [comment]
Looks OK currently in try.jsoup.
