### ISSUE TITLE
I get too many redirects error in higher android api versions while using jsoup with android studio

### ISSUE THREAD

**Issue by mehranj73** [jhy/jsoup#1302]
I have this issue, please help me.

https://stackoverflow.com/questions/59829938/i-get-too-many-redirects-error-in-higher-android-api-versions-while-using-jsoup

**Comment by mehranj73** [comment]
nobody cares?

**Comment by mehranj73** [comment]
Jsoup can not get redirected Persian link.

**Comment by jhy** [comment]
When you say Android Studio - do you mean that it works in other environments other than that? Can you provide a test case?

The URL 404s now so am not able to replicate. Do you have this issue on another URL?

**Comment by mehranj73** [comment]
It has been almost a year.
