### ISSUE TITLE
Stream parser fails HTML comment from OkHttp3 response body (JSoup >= 1.11.1)

### ISSUE THREAD

**Issue by btheu** [jhy/jsoup#1307]
From a very specific HTML page, it got that a HTML comment is badly parsed and that happen (as far i could test) only with OkHttp3 response body stream() and JSoup >= 1.11.1

Please have a look at the dedicated running testcase here: https://github.com/btheu/jsoup-parsing-issue.

    @Test
    public void testJsoup() throws IOException {

        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder()
                .url("https://www.letrot.com/stats/fiche-course/2019-09-22/202/6/partants/tableau").build();

        Response response = client.newCall(request).execute();

        Document parse = Jsoup.parse(response.body().byteStream(), "UTF-8", "https://www.letrot.com/");

        int numberOfCells = parse.select("td").size();

        System.out.println(numberOfCells);

        // Here: JSoup fails parsing the comment for the second html table row
        // 
        // this can be read at line 687 (more or less) from the raw response page
        System.out.println(parse.select("#result_table tr").get(1).select("td").text());
        System.out.println(parse.select("#result_table tr").get(2).select("td").text());
        System.out.println(parse.select("#result_table tr").get(3).select("td").text());

        assertEquals(156, numberOfCells);
    }

Best regards,

**Comment by jhy** [comment]
Hi,

What does "fails parsing" mean, specifically? What do you get? Can you save the bytestream out and the parsed jsoup HTML out, so we can compare easily?

Can you try the same on the HEAD version? Wondering if this is related to #1218 

Thanks!

**Comment by btheu** [comment]
Hi,

I believed that the Junit test cases on https://github.com/btheu/jsoup-parsing-issue will be enough to investigate since it is based on asserts and code comments. Have you tried to run it ?

In the while, I will add asked information directly here.

Regards,

**Comment by btheu** [comment]
Hi,

Testcase does not show the issue any more. The remote web site used for test may fixed some code on their side. 

This ticket can be close.
