### ISSUE TITLE
TextNode.toString() works different for TextNodes with/without parents

### ISSUE THREAD

**Issue by Mr-Mr-X** [jhy/jsoup#1309]
Hello,
thanks a lot for have done this wonderful library.
The TextNode.toString() method shows the following (surprising) behaviour:

    ...
    TextNode tn = new TextNode("Two  spaces"); // there are 2 spaces between the words
    System.out.println(tn.toString()); // prints string with 2 spaces
    tn.setParentNode(...); // set any parent
    System.out.println(tn.toString()); // prints string with 1 space
    ...

From my point of view the expected behaviour is that a single TextNode without parent behaves like a "typical" TextNode.
And the typical behaviour in jsoup is, that whitespace is normalized (the default value in out.prettyPrint() is true).

You may find a running example in the attached source file.

--
My recommendation:
In the method  TextNode.outerHtmlHead(...)
just remove the "instance of" check, since preserveWhitespace(..) already checks for instanceof Element and represents the expected standard behaviour in the case that this check fails:

    ...
    boolean normaliseWhite = out.prettyPrint() && parent() instanceof Element && !Element.preserveWhitespace(parent());
    ...

should become

    ...
    boolean normaliseWhite = out.prettyPrint() && !Element.preserveWhitespace(parent());
    ...

Best Regards
Mr-Mr-X
[JsoupBugExample.zip](https://github.com/jhy/jsoup/files/4128101/JsoupBugExample.zip)

**Comment by jhy** [comment]
Thanks - agree that a standalone TextNode should behave as normal -- i.e. it should normalize whitespace. Impl suggestion looks good.
