### ISSUE TITLE
Bypass dynamic content?

### ISSUE THREAD

**Issue by ganggasta** [jhy/jsoup#1312]
I'm trying to scrape the thread title from Reddit. But, the problem with the new reddit site is I can only scrape the first 7 threads since you have to scroll down or there's a delay till the rest of the content loads, so jsoup doesn't scrape that information. However, I think the old version of reddit does load everything at first load, but I don't know how to scrape that information since I'm not that familiar with HTML

1) From inspect element https://www.reddit.com/r/buildapcsales/top/ each thread has this element
Elements threadTitle = doc.select("h3._eYtD2XCVieq6emjKBH3m")

2) From inspect element https://old.reddit.com/r/buildapcsales/top/ each thread has this element
Elements threadTitle = doc.select(".title may-blank loggedin outbound")

Problem is that it doesn't return anything. Can someone help me out, thanks!

**Comment by jhy** [comment]
You should use View Source, not Inspect Element. Inspect Element shows you the DOM after everything has run -- including javascript fetching off-page data, etc. View Source shows the HTML as the server delivered it.

I'd investigate integrating a JSON parser and load the content out of the page. Or use the old HTML. Or why not just use their published API.

Will close this issue. Q&A for help on using jsoup is best on Stackoverflow or elsewhere.
