### ISSUE TITLE
User/Password authenticated proxies not working.

### ISSUE THREAD

**Issue by robbiecomputing** [jhy/jsoup#1314]
I can't get authenticated proxies to work. I have tried many things such as the authenticator class but that does not work very smoothly for things such as proxy rotation. 

Is there a better way for me use authenticated proxies in Jsoup like I would in apache http? I really love jsoup!

**Comment by zachlandes** [comment]
Did you ever get this working? What did you end up doing?

**Comment by jhy** [comment]
This is implemented in #2046
