### ISSUE TITLE
template element xml serialization removes the inner start/end tags

### ISSUE THREAD

**Issue by rhdunn** [jhy/jsoup#1315]
After parsing the HTML fragment:

    <template id="lorem-ipsum">
      <tr>
        <td>Lorem</td>
        <td>Ipsum</td>
      </tr>
    </template>

using the following:

    doc.outputSettings().prettyPrint(false)
    doc.outputSettings().syntax(Document.OutputSettings.Syntax.xml)
    return doc.outerHtml()

the output is as follows:

    <template id="lorem-ipsum">
      
        Lorem
        Ipsum
      
    </template>

That is, it is the same as the template content excluding the start and end tags. The whitespace is still preserved.

The tree construction in Firefox and Chrome is the same as the source, with a `#document-fragment` node between the template element and the tr content. That is:

    <template id="lorem-ipsum">
      #document-fragment
        <tr>
          <td>Lorem</td>
          <td>Ipsum</td>
        </tr>
    </template>

**Comment by bartektartanus** [comment]
Any progress on this issue? I've reviewed a pull request that should resolve this issue, but it still needs some work.

**Comment by jhy** [comment]
Tracking feature issue: #1634
