### ISSUE TITLE
Provide Evaluator / parsed query selecting method in Element as overloaded method

### ISSUE THREAD

**Issue by VirtualDruid** [jhy/jsoup#1319]
Hi
Would you considered something like this to be added:
```
Evaluator query = QueryParser.parse(".....");
Element.select(query);
Element.selectFirst(query);
```
As #518 described, re-parsing query on every element selecting could be a drawback of performance.

It would make sense if the query is quite complex and we want to reuse the parsed instance instead of parsing the String every time when selecting.

A solution could be using ```Selector.select(Element root, Evaluator eval)``` and ```Collector.findFirst(Element root, Evaluator eval)```  simply.

However, the most common API usage are still ``` Element.select(....) ``` and  ```Element.selectFirst(....)```.

Such change could make it much more convenient .

Thanks.

**Comment by jhy** [comment]
Thanks, I had already added that for Element#is. Added for select and selectFirst, and for the new closest

bd64b0192c7d3485665afdc10805b587df19eab3
