### ISSUE TITLE
Attributes don't accept valid URLs

### ISSUE THREAD

**Issue by aleksi1** [jhy/jsoup#1320]
When I add correct URL to href attribute, Jsoup escapes URL and it becomes incorrect URL. However it should accept valid URLs as href attributes.

Code:
```
Document d = Jsoup.parse("<a href=\"?page=1&search=test\"></a>");		
System.out.println(d.html());
```

Result:
```
<html>
 <head></head>
 <body>
  <a href="?page=1&amp;search=test"></a>
 </body>
</html>
```

**Comment by jhy** [comment]
This is the correct behaviour. HTML attributes need to be HTML encoded, which means the `&` character in the href attribute needs to be replaced with the `&amp;` entity. As it is, it is ambiguous for a (invalid) `&search;` entity.

When the HTML is parsed (by jsoup or a browser) the parsed URL will be correct. You can validate this by:

```
Document d = Jsoup.parse("<a href=\"?page=1&search=test\"></a>");
System.out.println(d.selectFirst("a").attr("href"));
```

Gives:

```
?page=1&search=test
```

I suggest saving the output here and loading it in a browser and verifying.
