### ISSUE TITLE
Security issue | Warning from Google play | Jquery/Jsoup

### ISSUE THREAD

**Issue by saqibusmangithub** [jhy/jsoup#1322]
Hello,

Since we have integrated jsoup android library we are getting warning from Google play that our app has security issue related to jquery, which jsoup internally has dependency on jsoup library
We were using jsoup 1.11.3

Please suggest what to do ? Will upgrade to latest version 1.12.2 solve this issue ? 

Thank you!

**Comment by jhy** [comment]
I'm not sure I follow. Jsoup doesn't, and has never, had a dependency on jquery (which is a JS library, not Java).

I don't understand what you mean by:
> which jsoup internally has dependency on jsoup library

Can you just paste the full notice from Google that you received so that we can understand the issue?

**Comment by saqibusmangithub** [comment]
<img width="556" alt="jquery-jsoup" src="https://user-images.githubusercontent.com/22234754/74460196-cecab300-4e8c-11ea-9883-73365d787470.png">

I have attached the notice above,

So we are suspecting jsoup because It has only started happening once we have integrated jsoup library.

**Comment by jhy** [comment]
jsoup has nothing to do with this. You need to update your jquery library, like the warning and the help message from Google says.

https://stackoverflow.com/q/58316191/153184
https://support.google.com/faqs/answer/9464300

My guess is that you updated you app, including a new version of jsoup, and when you sent it to Play they ran the scan and identified the jquery CVE.

**Comment by saqibusmangithub** [comment]
Hello @jhy 

Thanks for looking into this But We are not using jquery sdk in our app directly And this warning starting coming after we have included jsoup thats we are thinking its because of jsoup as you stated in your last line above 

`My guess is that you updated you app, including a new version of jsoup, and when you sent it to Play they ran the scan and identified the jquery CVE.`

**Comment by jhy** [comment]
Well, Google Play thinks you are. It's in `files/assets/js/jquery-3.1.1.min.js`.

Please, follow the instructions in the help link that they gave you. 

https://support.google.com/faqs/answer/9464300

Like it says, you can reach out on StackOverflow to them. But it looks pretty obvious to me what the problem is - that you've included a vulnerable version of jquery in that directory.
