### ISSUE TITLE
Slower parsing in latest versions

### ISSUE THREAD

**Issue by static-max** [jhy/jsoup#1327]
First of all, jsoup is a create tool and a pleasure to work with! Thanks a lot for your hard work!

We currently use 1.10.2 and I thought I give the newer versions a try, as the release notes mentioned performance improvements. Sadly, I saw the opposite. We have a test suite with hundreds of unit tests reading static HTML files and the time to run all tests increased.

Timings:

- 1.10.2: 63 seconds
- 1.11.2: 62.5 seconds
- 1.12.1: 66 seconds
- 1.12.2: 71 seconds

Some specific tests got significantly slower (25%) with 1.12.2 while others only got 10% slower.

I created a trivial micro benchmark that just calls Jsoup.parse(String) with a the same HTML file from memory (after warming up the JVM) a few thousand times:

- 1.10.2: 7.7 seconds
- 1.11.2: 8.7 seconds
- 1.12.2: 16.4 seconds

All tests run with Oracle JVM 1.8.0_172 and -Xmx8G -Xms8G. I also tried Java 13 with G1, but that gave a consistent performance drop in all jsoup versions. I did not try an alternate GC with Java 13.

Is this a known issue, do you need more information?

**Comment by jhy** [comment]
Hi, and thanks for the report. This is certainly not a known issue, so would love to get deeper and resolve this. On a first pass through the parser (including character reader, tree states, and allocations), nothing immediately jumps out as something that would show regressions, and certainly not of this order.

Most of the improvements in that time have focussed on (1) allocating less memory, which is probably not relevant when you're on an 8GB machine vs its benefit on Android, and (2) stream-based parsing, so that parsing is just about completed by the time the network URL load completes. If you're loading everything via the `Jsoup.parse(String)` method (correct?) you won't see much improvement there, but shouldn't see downsides either.

My feeling is that the data-set that I've been benchmarking against is different enough from yours to lead to this disconnect. Also that your set includes some files that are substantially worse, and that's bringing down the total and average times.

Would you be able to share a representative set of data? You can email them to me directly if it contains data you can't publicly share. 

Also the Java 13 issue sounds odd and counter intuitive. We should probably track a separate issue for that.

**Comment by jhy** [comment]
Thanks for pointing this out. I have expanded the set of files included in the benchmark, and run comparative timings from jsoup 1.7.1 through 1.13.1 (unreleased). Here's the measurements for `Jsoup.parse(File)` on JDK 8. `Jsoup.parse(String)` is generally the same. You can see that the 1.12 series loses a lot of the got perf improvements overall from 1.11. We will need to fix that.

The measurements are nano times, normalized by file size.


Version | Avg | Avg Delta | p0 | p50 | p90 | p100 | p100 Delta
-- | -- | -- | -- | -- | -- | -- | --
jsoup-1.07.1 | 20.21 | 0% | 10.09 | 16.74 | 36.78 | 103.19 | 0%
jsoup-1.07.2 | 20.66 | 2% | 9.56 | 17.31 | 37.48 | 91.7 | -11%
jsoup-1.07.3 | 20.02 | -3% | 8.4 | 16.95 | 34.33 | 88.11 | -3%
jsoup-1.08.1 | 19.58 | -2% | 8.45 | 16.37 | 34.06 | 78.65 | -9%
jsoup-1.08.2 | 19.77 | 1% | 8.88 | 17.29 | 31.65 | 90.31 | 11%
jsoup-1.08.3 | 18.08 | -8% | 7.63 | 15.82 | 29.22 | 78.6 | -11%
jsoup-1.09.1 | 17.38 | -3% | 8.86 | 14.58 | 28.23 | 91.42 | 12%
jsoup-1.09.2 | 17.2 | -1% | 9.36 | 14.73 | 29.17 | 66.97 | -24%
jsoup-1.10.1 | 17.98 | 4% | 8.74 | 15.21 | 29.94 | 63.95 | -3%
jsoup-1.10.2 | 17.14 | -4% | 8.11 | 14.42 | 27.86 | 90.56 | 26%
jsoup-1.10.3 | 17.64 | 2% | 8.26 | 14.96 | 28.28 | 77.54 | -13%
jsoup-1.11.1 | 13.41 | -21% | 3.79 | 12.91 | 19.84 | 43.45 | -33%
jsoup-1.11.2 | 13.12 | -1% | 3.71 | 12.59 | 19.28 | 48.04 | 4%
jsoup-1.11.3 | 13.44 | 2% | 3.77 | 13.02 | 20.27 | 39.27 | -8%
jsoup-1.12.1 | 21.13 | 38% | 4.59 | 18.4 | 31.65 | 74.55 | 34%
jsoup-1.12.2 | 25.97 | 24% | 4.96 | 27.14 | 38.68 | 95.95 | 21%
jsoup-1.13.1-SNAPSHOT | 27.31 | 7% | 6.23 | 27.8 | 38.33 | 105.87 | 10%

![image](https://user-images.githubusercontent.com/76934/75102471-eb5b9f00-55a0-11ea-9019-5adef54f3c50.png)

![image](https://user-images.githubusercontent.com/76934/75102510-7e94d480-55a1-11ea-93ef-6dde878bc78d.png)

![image](https://user-images.githubusercontent.com/76934/75102520-9cfad000-55a1-11ea-82cc-25f1e7258c9d.png)

**Comment by jhy** [comment]
I've fixed most of the regression with 9d9e53c8f5ab7d5dfa689ff39ee9e5dc5f7a881e. That was a pretty dumb issue - was uselessly creating a stringbuilder on every token read, as a warning/validation that never actually gets hit. Streamlined it.

**Comment by static-max** [comment]
Great you figured it out, thanks a lot!
I'm looking forward to test 1.13.1 when it's out.

Regarding G1, it gives me lower throughput (and/or higher CPU usage) in nearly every application, so I stick to `-XX:+UseParallelOldGC`.

**Comment by jhy** [comment]
OK, I've committed a number of improvements, which brings the performance back up to on par or better than any of the previous best versions, and substantially faster than 1.12.2.


Version | Mean | p90 | p99
|--: | --: | --:| --:|
jsoup-1.07.1 | 13.21 | 19.21 | 29.98
jsoup-1.07.2 | 13.48 | 18.84 | 27.83
jsoup-1.07.3 | 12.64 | 17.95 | 28.21
jsoup-1.08.1 | 12.37 | 17.64 | 28.84
jsoup-1.08.2 | 13.32 | 19.25 | 30.00
jsoup-1.08.3 | 13.10 | 18.49 | 28.75
jsoup-1.09.1 | 11.32 | 15.38 | 22.76
jsoup-1.09.2 | 11.62 | 15.67 | 25.71
jsoup-1.10.1 | 11.99 | 16.32 | 24.54
jsoup-1.10.2 | 11.88 | 16.30 | 25.40
jsoup-1.10.3 | 12.13 | 17.37 | 27.05
jsoup-1.11.1 | 11.49 | 15.24 | 22.59
jsoup-1.11.2 | 11.50 | 15.22 | 23.09
jsoup-1.11.3 | 12.12 | 16.48 | 24.54
jsoup-1.12.1 | 18.54 | 21.68 | 49.34
jsoup-1.12.2 | 23.50 | 44.74 | 50.58
jsoup-1.13.1 | **12.71** | 17.27 | 25.53

![image](https://user-images.githubusercontent.com/76934/75617586-e5703b80-5b15-11ea-9616-b859ff8d0355.png)

**Comment by jhy** [comment]
Here's the results of testing some different sites on Android - parse time in millis:


Version | Amazon | Wiki | CNN | SO
--: | --: | --: | --: | --:
1.12.2 | 73 | 42 | 55 | 37
1.13.1 | 26 | 18 | 28 | 10

So, good improvements there also.

**Comment by static-max** [comment]
Good job!
