### ISSUE TITLE
testing and mocking with jsoup

### ISSUE THREAD

**Issue by surli** [jhy/jsoup#1329]
Hi,

I just hit the following usecase: we are currently using this code inside a method:
```
Document doc = Jsoup.connect(xWikiActorURL).get();
String userName = doc.selectFirst("html").attr("data-xwiki-document");
```

and I'm currently trying to improve my code coverage in that class.
It appears that the Jsoup class cannot be mocked: it's just an helper that redirect to other classes.
Right now the only way I found to test this, is by using instead this code:
```
Document doc = this.httpConnection.url(xWikiActorURL).get();
String userName = doc.selectFirst("html").attr("data-xwiki-document");
```

and I inject a mock of `HttpConnection` in my class at the beginning of my test. 
Still it took me some time to figure out this solution, but I didn't find any resource about testing with jsoup. Could be good to add some hint for doing that, and maybe to provide some mock or some helpers for that.

**Comment by jgreen210** [comment]
If https://github.com/jhy/jsoup/issues/363 were implemented, you could use mocking or similar to change the URL to a file (or maybe data) URL.

You could already do that with http or https URLs, if you're willing to run a server in the unit test.

**Comment by dfernandezm** [comment]
Projects MockServer (https://www.mock-server.com/), or WireMock (http://wiremock.org/) are good candidates to support testing with JSoup.

**Comment by jhy** [comment]
(Closing - don't have a plan to change that the Jsoup class is static. Guess this issue can serve as a pointer to other mocking tools.)
