### ISSUE TITLE
Plans on Java 8 / Junit 5?

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1333]
Are there plans to move the project to Java 8 and Junit 5?

**Comment by jhy** [comment]
Yes I think it would make sense to do so now. Maybe we can do as part of 1.14.

Just checking Android support - looks like we can move to API level 10 (from 8) with no impact. 

https://developer.android.com/studio/write/java8-support
https://source.android.com/setup/start/build-numbers
https://developer.android.com/about/dashboards/

**Comment by offa** [comment]
Great, thanks!

**Comment by offa** [comment]
If that's Ok, I'll start porting tests to junit5.
