### ISSUE TITLE
android lint check issue

### ISSUE THREAD

**Issue by lipanpan1030** [jhy/jsoup#1338]
when lint check this issue: TrustAllX509TrustManager , 
this class org.jsoup.helper.HttpConnection$Response$2 report lint exception. 
exactly message below:

Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkClientTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers
Insecure TLS/SSL trust manager (TrustAllX509TrustManager : Warning) :
`checkServerTrusted` is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers

I really want this issue be fixed.
thank you very much

**Comment by jhy** [comment]
Dupe of #912. Please use a current version.
