### ISSUE TITLE
Discussion: LI Tag without parent OL, UL, DIR or MENU

### ISSUE THREAD

**Issue by wolfkopp** [jhy/jsoup#1345]
If we have LI without a parent Element, jsoup says this is valid.

`<li>a</li>`

The question is, is this valid HTML?
a) The W3C-Validatior says: only valid inside a OL, UL, MENU... Tag.
b) The HTML-Spec says: yes it's valid but "should" be inside a OL, UL, MENU Tag..

So what's correct now :-)

`<td>a</td>`
results in
`a`

**Comment by jhy** [comment]
Jsoup tries to follow the HTML5 spec. It's valid.
