### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by gopalanrc** [jhy/jsoup#1347]
I'm not able to get the content for the following url by using Jsoup.

https://www.masterclass.com/

Below is my code:
`Jsoup.connect(url).userAgent(System.getProperty("http.agent")).get();`

Any help is appreciated.

**Comment by MootezSaaD** [comment]
I think the it is the website that does not allow it.

**Comment by gopalanrc** [comment]
MootezSaaD, Thanks for the reply. Yeah, I have found a workaround for this. That is, getting the content thru WebView.
