### ISSUE TITLE
Jsoup cannot parse HTML fragments

### ISSUE THREAD

**Issue by newbie1** [jhy/jsoup#135]
If I want to parse td element from my HTML, I have to wrap it with table element, but that is not possible if you need to parse just HTML fragment that doesn't have td wrapped with table element. Jsoup should have functionality to parse HTML fragments. And if Jsoup parses HTML without html/body/head tags and automatically adds those, why it denys to parse td element without correct parent? It just doesn't seem very logical. What id there was Jsoup.parseFragment method to parse just HTML to Elements?

My question at stackoverflow.com:
http://stackoverflow.com/questions/7985791/why-jsoup-cannot-select-td-element/7986084#7986084

**Comment by jhy** [comment]
You can use the XML parser if you don't want HTML.
