### ISSUE TITLE
Build failure on master

### ISSUE THREAD

**Issue by StarPolygen** [jhy/jsoup#1355]
I'm currently unable to build JSoup 1.14.1-snapshot on master, due to some test failures corresponding to Connect. The Errors occured in testcase: ConnectIT and ConnectTest. I have ever try to ignore maven test and install directly. But thus I still cannot pass the several testcases. Example session follows:

>2020-04-20 11:19:33.183:INFO:oejs.AbstractConnector:main: Started ServerConnector@1503f6b{HTTP/1.1,[http/1.1]}{0.0.0.0:60406}
2020-04-20 11:19:33.183:INFO:oejs.Server:main: Started @5293ms
2020-04-20 11:19:38.121:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@1503f6b{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
[ERROR] Tests run: 32, Failures: 3, Errors: 1, Skipped: 0, Time elapsed: 6.509 s <<< FAILURE! - in org.jsoup.integration.ConnectTest
[ERROR] handlesUnknownEscapesAcrossBuffer  Time elapsed: 4.258 s  <<< ERROR!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jsoup.integration.ConnectTest.handlesUnknownEscapesAcrossBuffer(ConnectTest.java:470)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jsoup.integration.ConnectTest.handlesUnknownEscapesAcrossBuffer(ConnectTest.java:470)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jsoup.integration.ConnectTest.handlesUnknownEscapesAcrossBuffer(ConnectTest.java:470)

>[ERROR] doesPost  Time elapsed: 0.017 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <gzip> but was: <gzip, deflate>
	at org.jsoup.integration.ConnectTest.doesPost(ConnectTest.java:120)

>[ERROR] supportsDeflate  Time elapsed: 0.012 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <deflate> but was: <null>
	at org.jsoup.integration.ConnectTest.supportsDeflate(ConnectTest.java:333)

>[ERROR] doesPut  Time elapsed: 0.008 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <gzip> but was: <gzip, deflate>
	at org.jsoup.integration.ConnectTest.doesPut(ConnectTest.java:221)

>[INFO] Running org.jsoup.integration.ParseTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.959 s - in org.jsoup.integration.ParseTest
[INFO] Running org.jsoup.integration.UrlConnectTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in org.jsoup.integration.UrlConnectTest
[INFO] Running org.jsoup.internal.ConstrainableInputStreamTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.jsoup.internal.ConstrainableInputStreamTest
[INFO] Running org.jsoup.internal.StringUtilTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.internal.StringUtilTest
[INFO] Running org.jsoup.nodes.AttributesTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.nodes.AttributesTest
[INFO] Running org.jsoup.nodes.AttributeTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.nodes.AttributeTest
[INFO] Running org.jsoup.nodes.CommentTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.nodes.CommentTest
[INFO] Running org.jsoup.nodes.DocumentTest
[WARNING] Tests run: 30, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.028 s - in org.jsoup.nodes.DocumentTest
[INFO] Running org.jsoup.nodes.DocumentTypeTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.nodes.DocumentTypeTest
[INFO] Running org.jsoup.nodes.ElementTest
[INFO] Tests run: 108, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.214 s - in org.jsoup.nodes.ElementTest
[INFO] Running org.jsoup.nodes.EntitiesTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.nodes.EntitiesTest
[INFO] Running org.jsoup.nodes.FormElementTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in org.jsoup.nodes.FormElementTest
[INFO] Running org.jsoup.nodes.LeafNodeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.nodes.LeafNodeTest
[INFO] Running org.jsoup.nodes.NodeTest
[INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.nodes.NodeTest
[INFO] Running org.jsoup.nodes.TextNodeTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.nodes.TextNodeTest
[INFO] Running org.jsoup.parser.AttributeParseTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jsoup.parser.AttributeParseTest
[INFO] Running org.jsoup.parser.CharacterReaderTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in org.jsoup.parser.CharacterReaderTest
[INFO] Running org.jsoup.parser.HtmlParserTest
[WARNING] Tests run: 147, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.265 s - in org.jsoup.parser.HtmlParserTest
[INFO] Running org.jsoup.parser.HtmlTreeBuilderStateTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.parser.HtmlTreeBuilderStateTest
[INFO] Running org.jsoup.parser.HtmlTreeBuilderTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.jsoup.parser.HtmlTreeBuilderTest
[INFO] Running org.jsoup.parser.ParserSettingsTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.jsoup.parser.ParserSettingsTest
[INFO] Running org.jsoup.parser.ParserTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.jsoup.parser.ParserTest
[INFO] Running org.jsoup.parser.TagTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in org.jsoup.parser.TagTest
[INFO] Running org.jsoup.parser.TokeniserStateTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s - in org.jsoup.parser.TokeniserStateTest
[INFO] Running org.jsoup.parser.TokeniserTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 s - in org.jsoup.parser.TokeniserTest
[INFO] Running org.jsoup.parser.TokenQueueTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.jsoup.parser.TokenQueueTest
[INFO] Running org.jsoup.parser.XmlTreeBuilderTest
[WARNING] Tests run: 25, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.028 s - in org.jsoup.parser.XmlTreeBuilderTest
[INFO] Running org.jsoup.safety.CleanerTest
[INFO] Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 s - in org.jsoup.safety.CleanerTest
[INFO] Running org.jsoup.select.CssTest
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 s - in org.jsoup.select.CssTest
[INFO] Running org.jsoup.select.ElementsTest
[INFO] Tests run: 39, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 s - in org.jsoup.select.ElementsTest
[INFO] Running org.jsoup.select.QueryParserTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.jsoup.select.QueryParserTest
[INFO] Running org.jsoup.select.SelectorTest
[INFO] Tests run: 82, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.113 s - in org.jsoup.select.SelectorTest
[INFO] Running org.jsoup.select.TraversorTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 s - in org.jsoup.select.TraversorTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ConnectTest.doesPost:120 expected: <gzip> but was: <gzip, deflate>
[ERROR]   ConnectTest.doesPut:221 expected: <gzip> but was: <gzip, deflate>
[ERROR]   ConnectTest.supportsDeflate:333 expected: <deflate> but was: <null>
[ERROR] Errors: 
[ERROR]   ConnectTest.handlesUnknownEscapesAcrossBuffer:470 » SSLHandshake sun.security....
[INFO] 
[ERROR] Tests run: 793, Failures: 3, Errors: 1, Skipped: 5
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.753 s
[INFO] Finished at: 2020-04-20T11:19:41+08:00
[INFO] Final Memory: 20M/112M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project jsoup: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\SEProject\jsoup-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by jhy** [comment]
Errors look like they're in your Java cipher / SSL setup. Jsoup doesn't implement those and they will need to be setup correctly in your stack.

Tests are executing fine across many OS and Java versions - see e.g. GitHub build workflow.
