### ISSUE TITLE
HTML-Tag has now 4 childs instead of 3 as in 12.2

### ISSUE THREAD

**Issue by leomayer** [jhy/jsoup#1361]
I have the following content

```
<html> 
 <head> 
  <title>Example - Text Formating Tags</title> 
 </head> 
 <body> 
  test
 </body>
</html>
```
when I traverse the document with 

			final Document doc = Jsoup.parse(htmlText);
			NodeTraversor.traverse(myRoot, doc);

I get an empty `TextNode` just before the `head` tag. Up till 12.2 there wasn't any additonal `TextNode`. Can this be fixed to have this additonal `TextNode` be omitted?

The `output.prettyprint` has as expected no influence on this behaviour.

**Comment by StarPolygen** [comment]
Could you give test input and output more clearly?

**Comment by StarPolygen** [comment]
Ok, This cannot repo in version 1.13.1 [2020-Feb-29]:
>
String html = "<html><head><title>Example - Text Formating Tags</title></head><body>test</body></html>";
        final StringBuilder accum = new StringBuilder();
        final Document doc = Jsoup.parse(html);
        NodeTraversor.traverse(new NodeVisitor() {
            @Override
            public void head(Node node, int depth) {
                accum.append("<").append(node.nodeName()).append(">");
                return;
            }

            @Override
            public void tail(Node node, int depth) {
                accum.append("</").append(node.nodeName()).append(">");
                return;
            }
        }, doc);
        System.out.println(accum.toString());

And the result is as follows:
>
<#document><html><head><title><#text></#text></title></head><body><#text></#text></body></html></#document>

The empty node did not appeared.

**Comment by StarPolygen** [comment]
Or It may cause by "\n":
For example:
```
String html = "<html>\n" +
                "<head>\n" +
                "<title>Example - Text Formating Tags</title>\n" +
                "</head>\n" +
                "<body>\n" +
                "test\n" +
                "</body>\n" +
                "</html>";
```
The traverse result can be: <#document><html><#text></#text><head><#text></#text><title><#text></#text></title><#text></#text></head><#text></#text><body><#text></#text><#text></#text></body></html></#document>
with the same operation I said above.

**Comment by StarPolygen** [comment]
I think It can be quicker if we can preprocess "\n" such as ignore it in Html text. And maybe some user want to ignore specified context in HTML text. So I add a class to jsoup to solve the prob.

**Comment by leomayer** [comment]
Sorry for being late at the party: I can confirm that the string is built up with `\n` at the very line endings. I honestly would think that each HTML string would have them - especially when being saved into a file. Although I'm not aware that it might be an issue nevertheless I want to point to the CSS style: [`white-space`](https://www.w3schools.com/cssref/pr_text_white-space.asp). Doesn't a fix break up the content - in case the `pre` is used?
Although the `white-space`  wasn't an issue with JSoup 1.12 I have no clue if this might get one. Just as a quick q from my side.

**Comment by StarPolygen** [comment]
OK， Sorry for late. I think your concern is reasonable.  For the fix, I introduce a Class with an API which use to ignore some content specified by users. Maybe some users or cases has serious demand for "white-space". Thus they may not use this API. Thanks for your apply, and I will try to add compatible to this Class later.

**Comment by jhy** [comment]
This is a deliberate change as part of 9675a92b41593244d6d3ecd99425aeb19e2a6219 - we now keep track of whitespace in the head section, so that on output, you can choose to include or exclude it.

PrettyPrint options are used on output only, so the TextNode will correctly still be in the DOM regardless. You can use the text() methods to pull out normalized text (which will ignore these). Or on the TextNode, there is an isBlank() method.

If there's a specific issue you're impacted with, please file that. Vs slight internal changes in the DOM.
