### ISSUE TITLE
Can't find h3 items

### ISSUE THREAD

**Issue by mbostic** [jhy/jsoup#1363]
I am trying to get the headings of Google search results with Jsoup. Here is my code:

```
 String request = "https://www.google.com/search?q=" + query + "&num=5";
 
     try {
         Document doc = Jsoup
                 .connect(request)
                 .userAgent(
                         "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")
                 .timeout(5000).get();
 
         Elements headings = doc.select("h3");
         //headings array is empty
 
     } catch (IOException e) {
         e.printStackTrace();
     }
```

I get no results from doc.select("h3"). What am I doing wrong? Or is it a bug? I have checked the source of the page manually and I have found quite a lot of h3 tags. If, instead I search for tag "a", I get results normally.
I am doing that on Android.

**Comment by accron-1** [comment]
Have you checked the source page as it is received on Android?
What you see on your PC is very likely not the same markup you get on Android.

**Comment by jhy** [comment]
You should save and inspect the actual HTML you are getting back from the Jsoup request. E.g. after fetching, print/save `doc.outerHtml()`. My guess is that the server didn't return the HTML you expected. And remember that Jsoup does not execute Javascript.
