### ISSUE TITLE
JSOUP = Encrypted HTML -> Curl = Encypted???

### ISSUE THREAD

**Issue by masterholdy** [jhy/jsoup#1377]
So i dont know if im at the Righ place but i have a problem :p

i want to scrap this page: https://www.xrel.to/search.html?xrel_search_query=joko+gegen+klaas+das+duell+um+die+welt

When you visit this page you will get redirected to the same page, but they will ad a show_results={key} Parameter.

When i used Jsoup im able to retriev the URL with Show_Results Parameter, if i curl that URL i get the content decrypted

but if i just use jsoup and try to retrieve the content from that url its encrypted

![2020-05-13 15_09_33-megta-serarch – xrelDotToSearchWrapper java IntelliJ IDEA](https://user-images.githubusercontent.com/37812108/81816697-fed92f00-952b-11ea-97c7-aa3be3704d23.png)

```
   protected Connection getConnection(String QUERY_URL, String referrer){
        return Jsoup.connect(QUERY_URL)
                .header("accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
                .header("accept-encoding", "gzip, deflate, sdch, br")
                .header("accept-language", "en-US,en;q=0.8")
                .header("cache-control", "max-age=0")
                .header("user-agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36")
                .header("upgrade-insecure-requests", "1")
                .ignoreContentType(true)
                .ignoreHttpErrors(true)
                .method(Connection.Method.GET)
                .referrer(referrer)
                .timeout(120000)
                .followRedirects(true);
    }
```

if you take a look at the Screen 1) is using ```QUERY_URL={firstURL}```, ```referrer=www.google.de```

```Connection con = this.getConnection(QUERY_URL);```
Then i wait for redirect get the new url and make another request
-> ```QUERY_URL={redirectedURL/secondURL}```, ```referrer={firstURL}```
```        Document doc = null;
        try {
            if(followRedirect){
                String s = con.execute().url().toExternalForm();
                logger.error(s);
                if(!s.equals(QUERY_URL)){
                    String referrer = QUERY_URL;
                    QUERY_URL = s;
                    con = this.getConnection(QUERY_URL, referrer);
                    if(!validHttpConnection(con.response().statusCode())){
                        return new SearchResult(con.response().statusCode(), String.format("[F-4] %s", con.response().statusMessage()));
                    }
                }
            }
            doc = con.get();
        } catch (IOException e) {
            return new SearchResult(-5, "couldn't parse HTML.");
        } 

```
And as you can see on the Screen the Content of the second url is encrypted.

But if i use the same Link and use CURL i get the Content decrypted?

I m not sure if im at the right place, but i hope you guys might be able to help me

**Comment by masterholdy** [comment]
if im at the wrong place, could somebody maybe point me where i can ask those kind of questions?

**Comment by krystiangorecki** [comment]
You're using `.header("accept-encoding", "gzip, deflate, sdch, br")` but Jsoup supports only `gzip` and `deflate` ([src](https://github.com/jhy/jsoup/blob/91fcf208945f458b176c2b6915b53bad095cf527/src/main/java/org/jsoup/helper/HttpConnection.java#L786-L790)) so it can't decode the response. Using `.header("accept-encoding", "gzip, deflate")` solves the problem for me.

btw, better place to ask this would be: https://stackoverflow.com/questions/tagged/jsoup

**Comment by masterholdy** [comment]
thank you very much!
