### ISSUE TITLE
Add Node#noteType() and constants?

### ISSUE THREAD

**Issue by furstenheim** [jhy/jsoup#1378]
Hi,
Very nice library. It seems that there is no way to get NodeType in the API.
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType
Thanks.

**Comment by jhy** [comment]
We could potentially add it. There is `nodeName` which returns a unique string. Generally I've just used the class instanceOf.

**Comment by windsliver** [comment]
I'm interested in working on this issue.

**Comment by jhy** [comment]
Closing, not planned. I would just use instanceof.
