### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment while using jsoup

### ISSUE THREAD

**Issue by shubi9495** [jhy/jsoup#1380]
i have run below command in for loop to get the html data of myurl

doc = Jsoup.connect("myurl").get();
when i am using above code i got below error

 A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007f2bd695c76c, pid=12495, tid=0x00007f2bd4863700

JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x99876c]  oopDesc* PSPromotionManager::copy_to_survivor_space<false>(oopDesc*)+0x7c

Core dump written. Default location: /home/cardekho/tomcat/apache-tomcat-9.0.21/bin/core or core.12495

An error report file with more information is saved as:
 /home/cardekho/tomcat/apache-tomcat-9.0.21/bin/hs_err_pid12495.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

**Comment by krystiangorecki** [comment]
Did you try using older/newer Jsoup version?

**Comment by shubi9495** [comment]
I have try with below version 
Previous version: '1.10.3' 
New version: '1.13.1'

**Comment by tianyeasdw123** [comment]
1.11.3 And that's the problem

**Comment by shubi9495** [comment]
thanks so what's version should i used?

**Comment by shubi9495** [comment]
@jhy  Please help

**Comment by tianyeasdw123** [comment]
不是jsoup的问题，将jdk设置为ipv4=true,

**Comment by shubi9495** [comment]
> 不是jsoup的问题，将jdk设置为ipv4=true,

Please share in English

**Comment by shubi9495** [comment]
right now i am using java - "1.8.0_251"
jsoup version -1.11.3

**Comment by jhy** [comment]
Looks like a JDK bug, not a jsoup bug. See https://bugs.openjdk.java.net/browse/JDK-8179218

Seems to be related to GC settings, see the details in the link.

I'd try updating JDK and Jsoup to current versions.
