### ISSUE TITLE
problems with forms()

### ISSUE THREAD

**Issue by marcoscale98** [jhy/jsoup#1384]
Elements.forms() don't take any forms. 
Try to run example 3 https://www.programcreek.com/java-api-examples/?api=org.jsoup.nodes.FormElement

**Comment by sham0688** [comment]
`Jsoup.parse(form_smaple).select("form").forms()` is empty on v1.13.1 (v1.11.3 OK)
[form_smaple.txt](https://github.com/jhy/jsoup/files/4752091/form_smaple.txt)

**Comment by apflieger** [comment]
A backward compatibility break has been introduced here https://github.com/jhy/jsoup/commit/a657ae0240b875a703a1e4909d56ad59997d362d#diff-4f0778cbabadac4729bae10ebec0c0aaL636

the `forms()` method now return forms from child node only. This is a bug because the code is written to keep the previous behavior as it was. I'll try to make a PR

**Comment by marcoscale98** [comment]
Sorry, how do I download the updated stable version? On the site I still find 1.13.1

**Comment by apflieger** [comment]
I just submitted a pull request. I'm waiting on a feedback from a maintainer (@jhy ? 😄 ). It's not available yet

**Comment by apflieger** [comment]
Well, my PR is still pending 😢

**Comment by jhy** [comment]
Thanks, have applied the PR. 

It's unfortunate at I did have a testcase for this (the sample code referred to by @marcoscale98 is actually from jsoup, not sure why Program Creek is attributing it to another project and GPL when it's MIT). However it is in a disabled test-class as it was relying on an external server from tests I'd written before adding a local server. Need to spend some time updating those.

https://github.com/jhy/jsoup/blob/8e432a5f5fde4694834ce23c5ac1503ce8d381bc/src/test/java/org/jsoup/integration/UrlConnectTest.java#L331
