### ISSUE TITLE
A set-cookie order issue in Jsoup HTTP Module

### ISSUE THREAD

**Issue by erwinyang** [jhy/jsoup#139]
Some website may set a cookie for multiple times with different value.

For example, Jsoup may receive set-cookie headers in such a sequence
cookiename = value1
cookiename = value2

after the header is processed, the correct value of 'cookiename' should be 'value2'.
but unfortunately, Jsoup processed the headers in a reversed order, so the final value would be 'value1'
this problem might cause wrong behavior of the crawler with some websites.

thanks.

**Comment by jenomoto** [comment]
Any news on this issue? It's affecting me as well. Seems like there are some rules for set-cookies header, it's not completely clear to me how this should be resolved. Maybe not storing cookies as a map, but as a list of entries should cover most of the issues.

**Comment by dangxunb** [comment]
I was posted a question to stackoverflow about this:
http://stackoverflow.com/questions/34999764/jsoup-set-cookies-order-error

**Comment by jhy** [comment]
Jsoup now supports multiple headers with the same name, as of ea00e065f6245a94f87becf7d6ea80c46bc21ef1

That's a start on correcting this issue. And now that Jsoup supports Java 7, we can include Java Cookies (and CookieManager etc) which is in 1.6.

**Comment by ozymandias13** [comment]
Still seeing an issue when there is only 1 Set-Cookie header containing the same cookie name more than once. Example (there are 3 cookies in this string, 2 with the same name):

`inactive_popup_time_prod=1; expires=Thu, 01-Jan-1970 00:00:01 GMT,inactive_popup_time_prod=1510970756; expires=Sat, 18-Nov-2017 02:10:56 GMT; path=/,SESSID-EISPROD=9m17dfujbt47q1acu49iabc1e1; expires=Sat, 18-Nov-2017 02:05:57 GMT; path=/; domain=.somedomain.com; secure; HttpOnly`

Notice how there are 2 'inactive_popup_time_prod' cookies - Jsoup is returning a cookie map with only the first cookie in this string, meaning I miss the all important SESSID-EISPROD one in this case.

**Comment by ozymandias13** [comment]
More on this - the website I'm hitting actually returns the three set-cookie headers separately. It appears that Jsoup is somehow appending them all together into 1 set-cookie header in its internal Response structure.

**Comment by Raakh** [comment]
I am facing the same problem and waiting for any solution. Have you found any fix?

**Comment by jhy** [comment]
In 1.14.1 the cookie handling was reimplemented, and these issues are fixed
