### ISSUE TITLE
java.lang.IllegalArgumentException: Request has already been read (with .parse())

### ISSUE THREAD

**Issue by AlexMercier** [jhy/jsoup#1400]
I don't call parse() method but after try to getting response body I got error
STACK_TRACE=```java.lang.IllegalArgumentException: Request has already been read (with .parse())
	at org.jsoup.helper.Validate.isFalse(Validate.java:64)
	at org.jsoup.helper.HttpConnection$Response.prepareByteData(HttpConnection.java:845)
	at org.jsoup.helper.HttpConnection$Response.body(HttpConnection.java:858)```

lib version: jsoup-1.13.1

```
        Connection conn = Jsoup.connect(url);
       
            conn.userAgent(myUserAgent());
            conn.followRedirects(followRedirects);
            conn.ignoreHttpErrors(true);
            conn.cookies(getCookies());
            conn.timeout(getTimeout());
            conn.header("Accept-Encoding", "gzip,deflate,lzma,sdch");
            for (int i = 0; i < postData.length; i++) {
                String[] item = postData[i].split("=", 2);
                conn.data(item[0], item[1]);
            }
            conn.method(Method.POST);
            conn.maxBodySize(maxBodySize);
            conn.header("X-CSRF-TOKEN", getAjaxToken());
            conn.post();

            Connection.Response response = conn.response();
            mStatusCode = response.statusCode();
            if (mStatusCode == 302 && !followRedirects)
                return "";

            saveCookies(response.cookies(), url);
            final String body = response.body(); // HERE IllegalArgumentException error
```
```java.lang.IllegalArgumentException: Request has already been read (with .parse())```

The response body text as I expect must return just a text plain string, not a html structured body. maybe problem here, but I'm not sure, but all other request with html body returns successful

**Comment by jhy** [comment]
Unless you use `bufferUp`, the response body can only be read once (because it is consumed from the server response stream, and can be very large, so we don't maintain a copy by default). Your `.post()` is causing the response to be parsed.

Instead, what you should do something like (pseudo-code):

```java
conn.method(POST);
Connection.Response response = conn.execute();
response.bufferUp();
// other stuff
response.body();
```

See:
https://jsoup.org/apidocs/org/jsoup/Connection.html#post()
https://jsoup.org/apidocs/org/jsoup/Connection.html#execute()
https://jsoup.org/apidocs/org/jsoup/Connection.Response.html#bufferUp()
