### ISSUE TITLE
Form data extraction

### ISSUE THREAD

**Issue by mlsem** [jhy/jsoup#1406]
Hello Jsoup,

I am wondering if Jsoup could extract Form data even with a Get or a Post or Execute method ?

I want to extract Form data received after a postUrl in an Android WebView.

I can see form data on Chrome Devtools, in Network/Doc/Headers/Form Data , but i didn't found  a way to extract them, is Jsoup could do that ?

Thanks

**Comment by jhy** [comment]
Currently, the request/response object is not tracked inside of the parsed Document, so you can't fetch it from there.

(And there is no corresponding Javascript w3cdom method in browsers either).

Can't you just keep the Connection / Response object that you used to fetch the document and get the data you submitted from that?

**Comment by jhy** [comment]
Now in jsoup 1.14.1 you can retrieve the Connection (and so the Request and the Response) objects from a Document: see https://jsoup.org/apidocs/org/jsoup/nodes/Document.html#connection()
