### ISSUE TITLE
jsoup get outerhtml doesn't get the right html content because of the loading url html content 

### ISSUE THREAD

**Issue by tomoyoshki** [jhy/jsoup#1412]
Hi this is my first post so I apologize for any incorrect behavior. 
So here is the problem: 
I am trying to use Jsoup to get html content so I could get data from this website. However, this website has a loading content  html prior to the desired url content. Is there any way to wait until the website is fully loaded and then get the full html content? 
<img width="1271" alt="Screen Shot 2020-07-12 at 2 33 12 PM" src="https://user-images.githubusercontent.com/67913271/87253917-e6629380-c44c-11ea-88aa-52af49fe670d.png">
This is the loading screenshot of the website, which is not the desired content. 
Thank you

**Comment by sebhofmann** [comment]
I dont think jsoup is able to parse and execute Javascript to load the contents. I would recommend you to look at selenium webdriver.

**Comment by krystiangorecki** [comment]
Sebhofmann is right. Jsoup can't parse pages loaded with JavaScript so I have few tips:
1. For that type of questions use https://stackoverflow.com
2. To parse page relying on JavaScript try using https://stackoverflow.com/questions/tagged/selenium-webdriver
3. Sometimes you can grab the data you want anyway. Open your browser's debugger and try looking at Network tab to see content asynchronously loaded by JavaScript. Sometimes you can find the URLs and grab their content directly without parsing main page.
4.  We don't know what you're trying to parse but screenshot shows js.arcgis.com, so maybe you can use their API? https://developers.arcgis.com/javascript/latest/guide/get-api/

**Comment by tomoyoshki** [comment]
> I dont think jsoup is able to parse and execute Javascript to load the contents. I would recommend you to look at selenium webdriver.

Yes I found selenium working. Selenium can wait for the page to fully load and that worked well. Thank you so much, appreciate it!

> 4\. https://developers.arcgis.com/javascript/latest/guide/get-api/
thank you for your tips! Even though I already used selenium, I will dig more into your tips to learn more! Appreciate it!
