### ISSUE TITLE
Replacing text() or html() content of script tag causes jsoup to escape the script contents.

### ISSUE THREAD

**Issue by pflagerd** [jhy/jsoup#1419]
I've created a test in my fork of jsoup [here](https://github.com/pflagerd/jsoup/blob/master/src/test/java/org/jsoup/nodes/ScriptNodeTest.java).

It demonstrates the situation in which I encountered this issue.

Incidentally, this is probably the same as issue #1049 and possibly related to #1057.

**Comment by jhy** [comment]
Thanks, fixed this. It was not apparent to me when #1049 was filed that they were calling the html() method. Thanks for showing the issue with code!
