### ISSUE TITLE
Feature request: Add css method for getting/setting information in the style attribute

### ISSUE THREAD

**Issue by dariusj18** [jhy/jsoup#142]
It would be a nice if the style attribute was parsed into an object and a method "css" added to the Elements class.

Such that given 

```
String html = "<div style=\"font-size:2em;\"><p>Lorem ipsum.</p>";
Document doc = Jsoup.parseBodyFragment(html);
Element elem = doc.select("div").first();
```

You could then do this

```
String fontSize = elem.css("font-size");
```

or

```
elem.css("font-size", ""); or elem.css("font-size", "1.5em");
```

I imagine this would be quite complicated with css shorthand, but even the most basic functionality would be a pretty cool start.

EDIT: Formatting

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
