### ISSUE TITLE
XML Escape mode should escape < in attributes

### ISSUE THREAD

**Issue by RavishaNayak** [jhy/jsoup#1420]
We are extensively using Jsoup version1.7.2 from sometime. Thanks for the library ,it has been wonderful.

But upgrading seems to be bit difficult with one particular issue we faced.
test case:

```
    public static void main(String[] args) {
        final Document doc = Jsoup.parse("<input class=\"text\" value=\" &gt; data  &lt; \"/>");
        doc.outputSettings().escapeMode(org.jsoup.nodes.Entities.EscapeMode.xhtml);
        System.out.println("Output: " + doc.select("input.text").get(0));
    }
```
output is

Jsoup 1.7.2
`Output: <input class="text" value=" &gt; data  &lt; " />`

Jsoup 1.8.2
`Output: <input class="text" value=" > data  < ">
`
Jsoup 1.11.3
`Output: <input class="text" value=" > data  &lt; ">`

This is similar to the issue https://github.com/jhy/jsoup/issues/684.  but point to note here, this works fine in 1.7.2
Could you please help me over here if there is a workaround or better way to parse this

**Comment by zjamshidi** [comment]
I have the same problem with Jsoup version 1.11.2
I'm using XML syntax to convert HTML to XHTML. I got the error:
`Unescaped '<' not allowed in attributes values`

**Comment by rhdunn** [comment]
You need to use the following setting:
> doc.outputSettings().escapeMode(Entities.EscapeMode.xhtml)

That will cause `&lt;` to be preserved (while the other XML entities will have the same behaviour). This allows the resulting output to be parsed as XML/XHTML. __NOTE:__ This is not set when setting the output mode to XML.

**Comment by RavishaNayak** [comment]
Doesn't work for `&gt`. I get below output

`Output: <input class="text" value=" > data  &lt; ">`

**Comment by jhy** [comment]
To confirm, you're referring to generating valid XML, right?

As @rhdunn points out, EscapeMode to xhtml looks to produce the right result. Only `<` needs to be escaped in XML attributes (and quote and `&`). The `>` does not.

We should make XML output mode set the escape more or otherwise make sure `<` gets escaped for XML. It doesn't need to be for HTML, though.

Let me know if I've misunderstood anything.

**Comment by jhy** [comment]
(I'm getting a bit confused by the edit order -- from memory  and from @rhdunn's post, the initial code set the XML parser, not the XML escape mode. Regardless, I think we need to make sure that the XML parser sets XML escape mode, and that XML escape mode escapes `<` in attributes and text. (Although I don't really understand why XML chose that, as within a quoted attribute, a `<` should not be ambiguous.

**Comment by zoey-shan** [comment]
Hi, we are a student group and we plan to fix this issue these days. We wonder if there are some suggestions or other test cases relevant to this issue?
