### ISSUE TITLE
Issue with replaceWith method

### ISSUE THREAD

**Issue by ashimaaaa** [jhy/jsoup#1429]
When I am using replaceWith on an element, it changes the size of childNodes the element has.
On closely examining I found that element ito be replaced with has previous element as  "br" or "br" followed with textnode with just newline (\n) are now after replacement only textnode with newline"\n".  Is it replacing any prev "br" elements and newlines?
Is this a known behvaiour or an issue? Can i change this behaviour or is there a workaround?

**Comment by jhy** [comment]
Can you add a test case please, to better understand the issue.

**Comment by jhy** [comment]
Please reopen if you have a testcase.
