### ISSUE TITLE
childNodes + appendChild = ConcurrentModificationException?

### ISSUE THREAD

**Issue by gMan1990** [jhy/jsoup#1431]
```java
// ConcurrentModificationException
for (Node node : element.childNodes()) {
    element.parent().appendChild(node);
}

// Seems right
for (Node node : new ArrayList<>(element.childNodes())) {
    element.parent().appendChild(node);
}
```

Which is the right way to move child node to another parent in order?

**Comment by gMan1990** [comment]
```java
// maybe like this
for (int i = 0; i < node.childNodeSize();) {
    node.parent().appendChild(node.childNode(i));
}
```

**Comment by hannibal218bc** [comment]
When you move a node to a different parent (as per `appendChild`), the node is removed from the `childNodes` of the original parent element. So I'd say the `ConcurrentModificationException` in the original code snippet is to be expected.

However, there is  a simple workaround: just use`childNodesCopy()`:

```
// ConcurrentModificationException
for (Node node : element.childNodesCopy()) {
    element.parent().appendChild(node);
}
```

**Comment by hannibal218bc** [comment]
BTW your other suggestion:

> ```java
> // maybe like this
> for (int i = 0; i < node.childNodeSize();) {
>     node.parent().appendChild(node.childNode(i));
> }
> ```

... would work if you had used `childNode(0)` (not `i`).
As the child node is removed from its the original parent by `appendChild`, the next node to be processed will always be the "now first" node.

**Comment by jhy** [comment]
The simplest was would be to use [Element#insertChildren(index, nodes)](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#insertChildren(int,java.util.Collection)). Index can be -1 to insert to the end. 

E.g.:

```java
    @Test public void moveChildren() {
        Document doc = Jsoup.parse("<div><p>One<p>Two<p>Three</div><div></div>");
        Elements divs = doc.select("div");
        Element a = divs.get(0);
        Element b = divs.get(1);

        b.insertChildren(-1, a.childNodes());

        assertEquals("<div></div>\n<div>\n <p>One</p>\n <p>Two</p>\n <p>Three</p>\n</div>",
            doc.body().html());
    }
```

Maybe I can add an `appendChildren` alias to make that more obvious.

**Comment by jhy** [comment]
OK, I have added appendChildren and prependChildren to Element. I have also modified Node#childNodes to return a wrapper so that changes to the backing list do not update the view, so the original example will work.

**Comment by hannibal218bc** [comment]
@jhy I think changing the behaviour of `Node#childNodes` is a major and potentially **incompatible** change that might break existing code.
(In my own codebase, out of 13 usages it would break 3 at first glance; including the sample snippet in the comment above https://github.com/jhy/jsoup/issues/1431#issuecomment-748523788 ).

The new behaviour seems to be more consistent with other methods, so it should be fine, but is it really just an `improvement` in the changelog?

**Comment by jhy** [comment]
Good point @hannibal218bc. I do want to proceed with the change as I consider it a bug and confused myself a few times with the change (and also looking at the "UnmodifiableList" and thinking to myself, how is it being modified?).

I've bumped up the note in the changelog and will include in the release notes.
