### ISSUE TITLE
performance of filters -> why so big difference?

### ISSUE THREAD

**Issue by ogolovanov** [jhy/jsoup#1432]
Hi.

It seems that performance of using filters very different in the following 2 cases:
1) document.select("div[class*=test1]:not(:has(span[class*=test2]))")
2) document.select("div[class*=test1]").stream().filter(v -> v.is(":not(:has(span[class*=test2]))"));

Filter here is just an example - it can be any other.
Selector returns 4 elements in my case ( it matters - so we do not expect to spend much time on filters processing ).

**In the second case performance is several times better.
So the question is: how can that be possible at all?**

Thanks.

**Comment by jhy** [comment]
Do you have a sample HTML file? What performance numbers are you seeing? What platform?

**Comment by ogolovanov** [comment]
Hi.

You can take any html and ( i expect ) any platform.
In my case its OSX 10.15.2, java 1.8.0_231, jsoup 1.12.2

HTML:
```
<html>
<body>
</body>
<div class="test1"><span></span></div>
<div class="test1"><span class="test2"></span></div>
<div class="test1"><span class="test2"></span></div>
<div class="test1"></div>
<div class="test1"><span class="test2"></span></div>
</html>
```

Code:

 ```
String response = Files.toString(new File("/tmp/test.html"), Charsets.UTF_8);
Document d = Jsoup.parse(response);

// warm-up
for(int i=0; i<10000; ++i) d.select("*");

// test #1
 long s = System.currentTimeMillis();
 for(int i=0; i<1000000; ++i) d.select("div[class*=test1]:not(:has(span[class*=test2]))");
//for(int i=0; i<1000000; ++i) d.select("div[class*=test1]").stream().filter(v -> v.is(":not(:has(span[class*=test2]))"));
long e = System.currentTimeMillis();
System.out.println((e - s) / 1000000.0);

// test #2
s = System.currentTimeMillis();
for(int i=0; i<1000000; ++i) d.select("div[class*=test1]").stream().filter(v -> v.is(":not(:has(span[class*=test2]))"));
e = System.currentTimeMillis();
System.out.println((e - s) / 1000000.0);
```

Sample output:

> 0.006446
> 0.002264

As you see - there is 3x difference in performance.

**Comment by jhy** [comment]
I haven't focussed on this or seen other issues / repros of it. Happy to reopen if you want to profile it / make an improvement.

**Comment by jhy** [comment]
Might be improved after d80c0a99da0ff53a15d85381dd92a2a8f9742d66 - :has runs a lot faster now and creates a lot less GC. Because there's a RTL evaluation phase for selectors, the second method here probably calls :has less often.
