### ISSUE TITLE
Elements html() and outerHtml() methods adding "\n" in all tags

### ISSUE THREAD

**Issue by Vegeeto** [jhy/jsoup#1433]
Why adding "\n" between elements?

I am processing a set of followed html tags. When I want to get the html result (combination of all tags) with Elements class, the html is not the same as the original.

It could be good to have a method that print all elements one after the other, without adding line feed character, or consider to add only line feed character with block tags. In this case, the code of html() and outerHtml() methods could be:
`if (element.tag().formatAsBlock() && sb.length() != 0)`
instead of
`if (sb.length() != 0)`

**Comment by jhy** [comment]
You can turn off Pretty Printing and you'll get HTML that's closer to the original.

**Comment by Vegeeto** [comment]
I can't do it. I am working with Elements class, and I am adding new elements to list. 
Elements class does not have any parser, and the parser of added elements is not preserved.
