### ISSUE TITLE
Is it possible to use this library in the Swift language to make an app for IOS?

### ISSUE THREAD

**Issue by lucioaguiar** [jhy/jsoup#1435]
I have an android app that uses the library and that app makes many complex requests to different sites and uses that library.

I am starting to make the same app now in an **IOS version**, and I would like to use the same syntax that jsoup uses. My app uses many features of the jsoup, such as:

- :lt(n)
- :not(selector)
- :contains (text)
- [attr ^ = value]
- ancestor child

among others.

Having to make all these rules again in another specific **swift** library in **IOS**, would cost me a lot, I'm talking about over 100 sites with obsolutely different rules. I hope someone can show me a way or alternatives, thanks.

**Comment by jhy** [comment]
You might get better results to your question on a forum like StackOverflow.

**Comment by lucioaguiar** [comment]
Thanks.
