### ISSUE TITLE
Incomplete HTML puts dirty characters in tag's content

### ISSUE THREAD

**Issue by fvasco** [jhy/jsoup#1445]
In our use case we have to handle incomplete/truncated HTML, unfortunately, in this case, the jsoup parser puts dirty characters in the tag's content.

Here a Kotlin reproducer:

```kotlin
fun main() {
    val html = """<html><head><title>test</title >"""
    for (i in 0..9) {
        val part = html.dropLast(i)
        println(part + " ".repeat(i) + " -> " + Jsoup.parse(part).title())
    }
}
```
output

~~~
<html><head><title>test</title > -> test
<html><head><title>test</title   -> test
<html><head><title>test</title   -> test</title
<html><head><title>test</titl    -> test</titl
<html><head><title>test</tit     -> test</tit
<html><head><title>test</ti      -> test</ti
<html><head><title>test</t       -> test</t
<html><head><title>test</        -> test</
<html><head><title>test<         -> test<
<html><head><title>test          -> test
~~~

We expect that, in all case, `title` is equal to "test".

**Comment by jhy** [comment]
Hi - I understand the need, but title tags are special cased as rc_data tags and so therefore are strict about looking for the complete closing tag, and anything else gets interpreted as valid plain text as a child of the title element. This is implemented per the HTML5 spec, and re-confirmed that Chrome handles it the same, so will have to keep the current impl.

**Comment by jhy** [comment]
As a workaround, you could put the parser into XML mode first. That way the `title` tag is not treated specially.

https://try.jsoup.org/~gSFNeXPPGhbghGTWz_UJLKkyqhc
