### ISSUE TITLE
Space not added in between Tags <div> and <span> 

### ISSUE THREAD

**Issue by stephensebastin** [jhy/jsoup#1448]
JSOUP not appends space in between tags while performing .text()

HTML: 
`<div>Abc<span>def</span></div> 
`
Expected : Abc def
Actual : Abcdef

**Comment by sowjanyaboddeti** [comment]
Having the same issue. Will highly appreciate it if someone can look into this.

**Comment by hyscript** [comment]
https://github.com/jhy/jsoup/pull/1471

**Comment by jhy** [comment]
I believe that the current implementation (returning "Abcdef") is correct, as there is no space TextNode between the Abc and the (non-block) span element. It renders in a browser as a continuous string, copies to the clipboard as a continuous string, and the w3cdom innerText property also returns it as "Abcdef".

You could use the TextNode methods to get the individual nodes if required.
