### ISSUE TITLE
document.select("#read_$$deptleaderIdea")  

### ISSUE THREAD

**Issue by ttg432** [jhy/jsoup#1449]
org.jsoup.select.Selector$SelectorParseException: Could not parse query '#read_$$deptleaderIdea': unexpected token at '$$deptleaderIdea'

希望优化一下代码，支持这种方式

**Comment by jhy** [comment]
Please don't file error messages without a description of what you think the bug is.

This seems to be working correctly - HTML IDs can't contain $ marks, so the query parser will throw an exception on that case.
