### ISSUE TITLE
Unable to parse non-html elements via jsoup

### ISSUE THREAD

**Issue by JaiJayanthilal** [jhy/jsoup#1450]
Hi, I work for Oracle, we use OJET, here we have so many components resulting in custom tags .
Can anybody help us to parse non-html tags(custom tags) via JSOUP. ?

**Comment by jhy** [comment]
I'm not understanding what feature request or bug you're filing. Jsoup will parse unknown elements, see https://try.jsoup.org/~SYTsFjRBnq3j-221HGs-IlHNLi4

Think you want to start on StackOverflow or maybe on an interest group in your company.
