### ISSUE TITLE
Null body when parsing page that uses framesets

### ISSUE THREAD

**Issue by sicter** [jhy/jsoup#1453]
When pages have frameset, using Jsoup.parse results in a null body. This goes against the documentation https://jsoup.org/cookbook/input/parse-document-from-string, and results in a NullPointerException if any methods are called on the body Element.

Example pages that cannot sensibly parse: 
[http://www.incacgilbrianza.it/](http://www.incacgilbrianza.it/)
[http://www.fridaythe13thfilms.com/bts/script1/](http://www.fridaythe13thfilms.com/bts/script1/)

**Comment by jhy** [comment]
Thanks, this was fixed with 415f625565edde917945beedb201285d744365d3
