### ISSUE TITLE
Thread contention in OutputSettings()

### ISSUE THREAD

**Issue by jiri-pejchal** [jhy/jsoup#1454]
Thread contention can happen in the constructor of `OutputSettings`.
![image](https://user-images.githubusercontent.com/1450087/99841281-2e699380-2b6e-11eb-8684-590de3def5bb.png)

It can be solved by replacing `Charset.forName("UTF8")` with the constant `StandardCharsets.UTF_8`.

**Comment by 1725636955** [comment]
![image](https://user-images.githubusercontent.com/43667484/100045296-e935b200-2e4a-11eb-9d59-70cb9fdeafac.png)
