### ISSUE TITLE
Header Sec-Fetch-* can not set

### ISSUE THREAD

**Issue by waiterlong** [jhy/jsoup#1460]
I sets the headers like these:

![image](https://user-images.githubusercontent.com/16027138/101850605-0d0c2e00-3b95-11eb-9625-1a20f6be1162.png)

But in the server, I print the request headers, there are no headers Sec-Fetch-* printed. 

![image](https://user-images.githubusercontent.com/16027138/101850642-2319ee80-3b95-11eb-9faa-8c3760d79323.png)

Anybody can help me with this question?

**Comment by waiterlong** [comment]
![image](https://user-images.githubusercontent.com/16027138/101850836-80ae3b00-3b95-11eb-8fac-d80b25ef8194.png)

![image](https://user-images.githubusercontent.com/16027138/101850881-90c61a80-3b95-11eb-9272-bff150b0bab6.png)

**Comment by jhy** [comment]
Please, don't post pictures of code, it breaks search and accessibility. Just paste plain text and use the markdown code escape.

**Comment by waiterlong** [comment]
> Please, don't post pictures of code, it breaks search and accessibility. Just paste plain text and use the markdown code escape.

ok, thank for remind
