### ISSUE TITLE
SSL Certificate Pinning?

### ISSUE THREAD

**Issue by ItzNotABug** [jhy/jsoup#1462]
Any plans to add something like `OkHttpClient`'s `CertificatePinner.Builder()`?
More info:. https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html

This can be very helpful in Jsoup.
Thanks.

**Comment by ItzNotABug** [comment]
Any plans for this?

**Comment by jhy** [comment]
Not really, thanks. Personally, I only see certificate pinning as a way to break apps when a server configuration changes.
