### ISSUE TITLE
jsoup parse string escapes entities when element is nested in title tag

### ISSUE THREAD

**Issue by bkuchi** [jhy/jsoup#1472]
```
Document doc = Jsoup.parse("<html>
  <head></head> 
  <body> 
    <title> 
      <parse-anchor name="Preliminary"> 
        <a id="SECTION_0"> Exhibit</a> 
      </parse-anchor>
    </title>
  </body>
</html>");

doc.outputSettings().escapeMode(Entities.EscapeMode.base).indentAmount(2).outline(true).prettyPrint(true);
```

**results in** 
```
<html>
  <head></head> 
  <body> 
    <title>    &lt;parse-anchor name="Preliminary"&gt;    &lt;a id="SECTION_0"&gt; Exhibit&lt;/a&gt;   &lt;/parse-anchor&gt;</title> 
  </body>
```
</html>

**entities are getting escaped when parsing title tag inside body. other scenarios it works as expected. this un expected behavior is causing selector issues.**

**Comment by jhy** [comment]
The contents of a `title` tag are rcdata -- that is, plain text. Similar to a `textarea` tag. So any contents are parsed as such.

That works the same as a browser - load it in Chrome and see that the title displayed is "<parse-...", not "Exhibit". And similarly if you use the inspector, you'll see the "<parse-.." as text content of the title element, not child elements.

If you want to treat the contents as XML (so you can select a `parse` element), use the XML parser.
