### ISSUE TITLE
jsoup using java 9+

### ISSUE THREAD

**Issue by jjanderson5** [jhy/jsoup#1477]
I'm curious, are the any plans to build a jsoup.jar compiled with java9+ (I'm using java 11)?

**Comment by jjanderson5** [comment]
I'm sorry, I just saw the other thread about java 9+. I will go through that thread.

**Comment by jhy** [comment]
Do you have a specific error? It compiles and runs just fine for me (and pretty much everyone else would be using 9+ as well I would imagine).
