### ISSUE TITLE
Request: selectFirst with Evaluator - Selector.selectFirst(evaluator, root)

### ISSUE THREAD

**Issue by briankolo** [jhy/jsoup#1478]
Selector's selectFirst is currently only implemented for string css queries. Can we have an overloaded method for already constructed evaluator objects?
```Java
public static Element selectFirst(Evaluator evaluator, Element root) {
    return Collector.findFirst(evaluator, root);
}
```

**Comment by jhy** [comment]
Agreed - I added it some time back, in https://github.com/jhy/jsoup/commit/bd64b0192c7d3485665afdc10805b587df19eab3#diff-2039a2cc0acb457fb17a4cc6640fb3815d9d753a39fa59cfaedd9d4e155b43ddR406
