### ISSUE TITLE
Upcoming - release jsoup 1.14.1

### ISSUE THREAD

**Issue by KevinWorkman** [jhy/jsoup#1481]
I'm looking to transition my code away from the Whitelist class, to the Safelist class, which was introduced in jsoup 1.14.

More info in the Whitelist class: https://jsoup.org/apidocs/org/jsoup/safety/Whitelist.html

My code uses Maven to manage its dependencies, and the newest version of jsoup available to Maven seems to be 1.13: https://mvnrepository.com/artifact/org.jsoup/jsoup

What's the process for updating the Maven repository with a newer version of jsoup?

**Comment by jhy** [comment]
Hi Kevin, sorry about the confusion. `1.14.1` has not yet been released, and so that's why it's not yet in Maven.

I was rebuilding the jsoup.org site and javadocs (to fix the docs for mobile support) and that now shows the upcoming version.

Looking to release 1.14 soon (this week or so), externalities permitting.

**Comment by KevinWorkman** [comment]
Thanks for the reply! No rush on my account, I just wanted to make sure I wasn't missing anything. Feel free to close this out, and I'll patiently wait for the new release. Thanks again!

**Comment by matjung** [comment]
Regarding this code repository, is there an easy way available to find out what bugs are expected to be fixed in the upcoming release?

**Comment by BalusC** [comment]
> I was rebuilding the jsoup.org site

Just in case .. don't forget https://jsoup.org/cookbook/cleaning-html/whitelist-sanitizer!

In any case .. thank you very much for keeping Jsoup up to date :)

**Comment by tureArtemis** [comment]
Is 1.14.1 being released soon?

I have been using 1.13.1 but just ran into a bug that is fixed in 1.14.1 so I'd love to upgrade:  

https://github.com/jhy/jsoup/issues/1410
NPE that results when calling Element.toString() for an Element that is from Element.clone()

Thanks!

**Comment by riggsd** [comment]
Sorry to add to the list of nagging requests, but we're hoping to adopt JSoup yet and specifically need to expose the Whitelist/Safelist as public API, so we're waiting for 1.14.1 (even a snapshot) availability in the Maven repository. Is there a timeline for this release, or blocker(s) preventing it?

Thank you!

**Comment by jhy** [comment]
Hi all -- wanted to let you know that I've just released jsoup 1.14.1 and it's available now.

Details at https://jsoup.org/news/release-1.14.1

Sorry it took so long -- I kind of jinxed myself with "externalities permitting" :/
