### ISSUE TITLE
BaseURI wrongly calculated

### ISSUE THREAD

**Issue by leomayer** [jhy/jsoup#1487]
I fetch a document via HTTP request `Jsoup.connect("https://tug.org/FontCatalogue/about.html").get()`. This works fine.

When I try to retrieve the baseURI with `Jsoup.connect("https://tug.org/FontCatalogue/about.html").get().baseUri()` it returns the full path (`https://tug.org/FontCatalogue/about.html`) instead of just `https://tug.org/FontCatalogue` (with or without trailing slash).

Tested with JSoup 1.12.2.

**Comment by jhy** [comment]
That's right. The base URI is the URI that relative URLs in a document are resolved against. Unless it's set differently in the page with a `<base href>` tag, it should the URL that the page was fetched from.

If you want something different (I think you're looking for a parent directory?), you will need to create a URI object and remove the filename, or similar.
