### ISSUE TITLE
HtmlTreeBuilderState.InHead missing in HtmlTreeBuilder.java?

### ISSUE THREAD

**Issue by matjung** [jhy/jsoup#1491]
jsoup-1.13.1.jar
jsoup-1.13.1-sources.jar
When parsing a html string I was having an issue with
Unexpected token [StartTag] when in state [InBody] 7
That made me visit the issues list and have a look into the code.
method void resetInsertionMode()
`            } else if ("head".equals(name)) {
                transition(HtmlTreeBuilderState.InBody);
                break; // frag
`
Should the state not be InHead ?

**Comment by jhy** [comment]
Thanks, looks like the spec (https://html.spec.whatwg.org/multipage/parsing.html#the-insertion-mode) has been updated. Fixed.
