### ISSUE TITLE
escape behavior in 1.13.1

### ISSUE THREAD

**Issue by cortemadera** [jhy/jsoup#1497]
We recently upgraded from jsoup 1.7.3 to 1.13.1, and noticed the following escape behavior change:

1.7.3: 
```
input    attribute        non-attribute
    "        &quot;            &quot;
    '        '                '
    <        &lt;              &lt;
    >        &gt;              &gt;
    &        &amp;          &amp;
```

 1.13.1:
```
  input    attribute        non-attribute
    "          &quot;            "               
    '                '                  '
    <            <                &lt;
    >            >                &gt;
    &        &amp;            &amp;
```
Are the behavior changes for &quot;, &lt;, and &gt; intentional? If so, can someone please elaborate the rationale for these changes?

**Comment by jhy** [comment]
Yes, they are intentional. The goal was to only escape characters when required. The items which changed are not required to be escaped in that context.

Cheers,
Jonathan
