### ISSUE TITLE
oss-fuzz integration of jsoup

### ISSUE THREAD

**Issue by 0roman** [jhy/jsoup#1502]
Hi all,

I prepared the integration (https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/e03329f4b8fde5b361cc68c087fc8290c4631f03) of jsoup into google oss-fuzz. This will enable continuous fuzzing of this project, which will be conducted by google. Bugs that will be found by fuzzing will be reported to you. 

The integration makes only sense if someone will deal with the bug reports submitted by oss-fuzz. Are you interested in the integration? If yes, I would submit a pull request and I would provide your contact information for bug reports. I would use jonathan@hedley.net or any other email that you would prefer. 

For the Fuzzing of Java applications Jazzer is used. [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. 
Jazzer has already found a lot of critical bugs in JVM applications.

If there are any questions regarding fuzzing or the oss-fuzz integration, it would be a pleasure for me to help.

**Comment by 0roman** [comment]
@offa you have also participated in the development of this project. Since @jhy is not responding, could you care about future bug submissions by oss-fuzz for this project? I would provide your contact information then. I only would need an email address of you.

**Comment by offa** [comment]
In general yes, but I do not have any write or merge permissions. Additionally it depends on the amount of work that's reported.

I haven't used oss-fuzz yet, but is it possible to create tickets in in the project instead? Or are the results considered confidential respectively should follow a good disclosure practice?

Have you tried to contact @jhy through email / Twitter? Maybe he's responding there.

**Comment by 0roman** [comment]
I have tried to reach @jhy, but he not responding and was not available in social media channels since february. @inferno-chromium would this be fine for google oss-fuzz, if @offa would handle bug submissions?

**Comment by inferno-chromium** [comment]
yes jsoup looks like a good critical project for oss-fuzz.

**Comment by 0roman** [comment]
Hey @offa, it would be great if you could handle bug submissions. The amount of work should be not that much. Creating Tickets and submitting Pull Requests should be fine. Could you give some contact information here or write me a mail which i can use?

**Comment by offa** [comment]
@0roman do you have received my mail?

**Comment by 0roman** [comment]
hey @offa, jsoup is now integrated ^^ you already should have received some bug reports

**Comment by offa** [comment]
Yes!

**Comment by krystiangorecki** [comment]
Hi @0roman we have the first issues reported but I don't have access to issue details, for example:

_Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=4666538805297152_

Would it be possible to loosen the permissions to allow everyone to access and start fixing these issues?

**Comment by offa** [comment]
> Would it be possible to loosen the permissions to allow everyone to access and start fixing these issues?

:+1:  

@0roman is this possible?

**Comment by inferno-chromium** [comment]
> Hi @0roman we have the first issues reported but I don't have access to issue details, for example:
> 
> _Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=4666538805297152_
> 
> Would it be possible to loosen the permissions to allow everyone to access and start fixing these issues?

Sorry, but people need to be explicitly added to this file - https://github.com/google/oss-fuzz/blob/master/projects/jsoup/project.yaml
There is setting to make everything accessible to everyone, like this -https://github.com/google/oss-fuzz/blob/master/projects/llvm/project.yaml#L28 but be cautious since security vulnerabilities get disclosed to everyone as well (so not recommended unless project has security implications).

**Comment by krystiangorecki** [comment]
Can you add me? ffrr33aakk@gmail.com

**Comment by inferno-chromium** [comment]
> Can you add me? [ffrr33aakk@gmail.com](mailto:ffrr33aakk@gmail.com)

done in https://github.com/google/oss-fuzz/commit/b8a24cf949a8aab99a261de46785589b5a63db6a, in future, please propose a PR in oss-fuzz repo (fyi @offa as well)

**Comment by jhy** [comment]
Thanks all for taking care of setting this up - am excited to have the integration and to get into these issues! My apologies for my lack of correspondence on this project of late. Am planning to be more active now; still catching up.

**Comment by offa** [comment]
@jhy I'd suggest to change the main contact to you, makes more sense to me.

**Comment by jhy** [comment]
> @jhy I'd suggest to change the main contact to you, makes more sense to me.

Thanks, yes, have sent a [PR](https://github.com/CodeIntelligenceTesting/oss-fuzz/pull/3). I wasn't sure if you wanted to be CCed, feel free to add.

**Comment by offa** [comment]
Perfect, thanks! I do not have much time to work on them, so the PR is fine.

**Comment by jhy** [comment]
Thanks again all - I have put in fixes for all of the active issues found (pending a couple of re-run validations). Will close this issue out.
