### ISSUE TITLE
Proxy authentication doesn't work

### ISSUE THREAD

**Issue by marcos-lessa** [jhy/jsoup#1506]
Apparently, Jsoup does not support proxy authentication with username and password. It is only possible to set a proxy that does not require authentication on the connection.

```
public Document fetchWithProxy(final String url, final Proxy proxy) throws IOException {
		return Jsoup.connect(url).proxy(proxy.getIpAddress(), proxy.getPort()).header("Proxy-Authorization",
			"Basic " + Base64.getEncoder().encodeToString("username:password".getBytes())).get();

}
```

When I run this code, the following exception is thrown:

`java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
`

**Comment by marcos-lessa** [comment]
I managed to solve this by doing the following:

```
public Document fetchWithProxy(final String url, final Proxy proxy) throws IOException {
		Authenticator.setDefault(new Authenticator() {

			@Override
			public PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication("username", "password".toCharArray());
			}
		});
		return Jsoup.connect(url).proxy(proxy.getIpAddress(), proxy.getPort()).post();
}
```

But I still think it needs correction, so that it can work by setting the header.

**Comment by PauloArthur99** [comment]
Hey guys, let's fix this problem as soon as possible, please.

**Comment by Barrya42** [comment]
it is important for me, and many of us. Let's fix it
