### ISSUE TITLE
JSOUP not sending Proxy-Authorization header with HTTPS Connections

### ISSUE THREAD

**Issue by benignoms** [jhy/jsoup#1507]
[https://github.com/jhy/jsoup/issues/1155#issue-389335908](url)

This only occurs when the connection is with HTTPS. When you use multithreading there is no way to use the Default Authenticator if you need different users for each connections. Please help us. How to be able to set the credentials for each connection using JSOUP?

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by jhy** [comment]
I implemented this in #2046
