### ISSUE TITLE
Converting HTML page to a HashMap

### ISSUE THREAD

**Issue by IlyasPatel** [jhy/jsoup#1510]
Would it be possible to convert a html page to a HashMap using JSoup please?

**Comment by LIKP0** [comment]
Hello! I think it is an interesting idea to add such a feature. However, we should make it concrete first. For example, what are the keys and vals? Are the attributes pairs suitable? Hope for your discussion!

**Comment by LIKP0** [comment]
Jsoup has provided enough method for "attributes" map. You can use below code to acess:
```
        Document doc = Jsoup.parse(html);
        Map<String, String> map = doc.dataset();
        Set<String> keySet = map.keySet();
        for (String key : keySet) {
            System.out.println(key + "=" + map.get(key));
        }
```
or
```
        List<Attribute> a = doc.attributes().asList();
        for (Attribute x : a){
            System.out.println(x.getKey() + " " + x.getValue());
        }
```

**Comment by jhy** [comment]
(Closing this out - happy to reopen and discuss based on a particular need / use-case.)
