### ISSUE TITLE
removeTags

### ISSUE THREAD

**Issue by jja** [jhy/jsoup#152]
Can you add a removeTags() method to Whitelist?
For example, I might want Whitelist.basic but without the 'a' tag. Because tagNames is private and TagName is package-private, I can't add the method to a subclass. So I have to cut and paste code from Whitelist.

public Whitelist removeTags(String... tags) {
{
        Validate.notNull(tags);
 
        for (String tagName : tags) {
            Validate.notEmpty(tagName);
            tagNames.remove(TagName.valueOf(tagName));
        }
        return this;
    }

**Comment by jhy** [comment]
Sorry for late reply. This was added in 1.8.2 #449
