### ISSUE TITLE
Parser problem for html format

### ISSUE THREAD

**Issue by LIKP0** [jhy/jsoup#1534]
Below test case expects `a"""` but gets `a` instead:
```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import java.io.IOException;

public class Try {
    public static void main(String[] args) throws IOException {
        String path = "<a title=\"a\"\"\"\" <5\">A</a>";
        Document doc = Jsoup.parse(path);
        System.out.println(doc.select("a").attr("title"));
    }
}
```
This problem is actually a format problem. I don't know **whether the format `title=\"a\"\"\"\"`**, which has multiple quotes in a pair of quotes, **is valid**. Should they be replaced by single quote? However, The scene do exist in the real world. **So how do we solve such problems since jsoup itself does not support similar work?** I think the function used for double quote attribute value extract is relatively not strong. It just meets a `"`, turns to AfterAttributeValue immmediately, and leaves out the value after that `"`.
`consumeAttributeQuoted()` in `CharacterReader.java` used in `TokeniserState.java` line 749, which is critical in html reading:
```
String consumeAttributeQuoted(final boolean single) {
        // null, " or ', &
        //bufferUp(); // no need to bufferUp, just called consume()
        int pos = bufPos;
        final int start = pos;
        final int remaining = bufLength;
        final char[] val = charBuf;

        OUTER:
        while (pos < remaining) {
            switch (val[pos]) {
                case '&':
                case TokeniserState.nullChar:
                    break OUTER;
                case '\'':
                    if (single) break OUTER;
                case '"':
                        if (!single) break OUTER;//here it breaks out directly
                default:
                    pos++;
            }
        }
        bufPos = pos;
        return pos > start ? cacheString(charBuf, stringCache, start, pos - start) : "";
    }
```

**Comment by jhy** [comment]
This is implemented to the HTML5 spec, the same as modern browsers implement. So I don't plan on changing it. \ characters in HTML are not escapes and so the `\"` sequence is meaningless.
