### ISSUE TITLE
[34231] jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.HtmlTreeBuilder.resetInsertionMode

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1538]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Reported-2021-05-13 Proj-jsoup
Type: Bug
New issue 34231 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.HtmlTreeBuilder.resetInsertionMode
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34231

Detailed Report: https://oss-fuzz.com/testcase?key=4666538805297152

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: HtmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Uncaught exception
Crash Address: 
Crash State:
  org.jsoup.parser.HtmlTreeBuilder.resetInsertionMode
  org.jsoup.parser.HtmlTreeBuilderState$9.process
  org.jsoup.parser.HtmlTreeBuilder.process
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=4666538805297152

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

------------------
Updates:
	Labels: Fuzz-Blocker

Comment #1 on issue 34231 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.HtmlTreeBuilder.resetInsertionMode
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34231#c1

This crash occurs very frequently on linux platform and is likely preventing the fuzzer HtmlFuzzer from making much progress. Fixing this will allow more bugs to be found.

**Comment by krystiangorecki** [comment]
That's all we have? I mean, no stacktrace with line numbers? No input data to reproduce?

**Comment by offa** [comment]
There's more information (detailed report, reproducer test case) linked in the email. Since none of them is a severe security issue (highest prio is low), I guess I can make them public here!?

**Comment by offa** [comment]
@krystiangorecki I have added all details; other issues follow.

**Comment by krystiangorecki** [comment]
Yes, please. People report exceptions with such details all the time. They often stay unfixed for few months until the next release and no one ever complained. Now it's just not enough info.

**Comment by offa** [comment]
I have updated all issues; #1537 tracks all related issues in this project now.
