### ISSUE TITLE
[34237] jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.helper.Validate.notEmpty

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1541]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Reported-2021-05-13 Proj-jsoup
Type: Bug

New issue 34237 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.helper.Validate.notEmpty
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34237

Detailed Report: https://oss-fuzz.com/testcase?key=5977748817444864

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: HtmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Uncaught exception
Crash Address: 
Crash State:
  org.jsoup.helper.Validate.notEmpty
  org.jsoup.nodes.Node.absUrl
  org.jsoup.nodes.Node.attr
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5977748817444864

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

---------
Updates:
	Labels: Fuzz-Blocker

Comment #2 on issue 34237 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.helper.Validate.notEmpty
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34237#c2

This crash occurs very frequently on linux platform and is likely preventing the fuzzer HtmlFuzzer from making much progress. Fixing this will allow more bugs to be found.

**Comment by jhy** [comment]
The input causing this is:

`b<bodY abs: abs:abs:>`

It's tripping because there is a check in the parser when to not add duplicate attributes, and the hasAttr method has special handling for absolute URLs (e.g. "abs:href") which is bombing. We should disambiguate and test for the literal attribute here.

**Comment by jhy** [comment]
Fixed, thanks for finding and filing!
