### ISSUE TITLE
[34249] jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.CharacterReader.unconsume

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1542]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Reported-2021-05-13 Proj-jsoup
Type: Bug

New issue 34249 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.CharacterReader.unconsume
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34249

Detailed Report: https://oss-fuzz.com/testcase?key=5267962723434496

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: HtmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Uncaught exception
Crash Address: 
Crash State:
  org.jsoup.parser.CharacterReader.unconsume
  org.jsoup.parser.TokeniserState$11.read
  org.jsoup.parser.Tokeniser.read
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5267962723434496

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by jhy** [comment]
I haven't been able to reproduce this one with the provided data file. See testcase at: https://github.com/jhy/jsoup/commit/e718ddd847e15331d7d204a021b7f0aa80628a68

Driver just calls Jsoup.parse(string) - so not sure what I'm missing:
https://github.com/google/oss-fuzz/blob/master/projects/jsoup/HtmlFuzzer.java

Any idea?

**Comment by jhy** [comment]
@0roman thanks very much for setting up the fuzz integration. I've fixed the bulk of the issues tracked here: #1537

This one I can't replicate. I am guessing that I'm decoding the sample test case incorrectly but can't figure what I'm doing wrong. According to:
https://github.com/CodeIntelligenceTesting/jazzer#reproducing-a-bug there should be a .java main class to repro the bug, but I can't find that on the linked report.

Any suggestions?

**Comment by jhy** [comment]
I wasn't able to directly test this with the sample fuzz output, but was able to reconstruct the same code execution path and error with a standard unit test.

Also reviewed all 14 other uses of unconsume() and verified that these all are directly after a consume() and there's no bufferUp() potential, so those cannot trigger this underrun.
