### ISSUE TITLE
[34250] jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.HtmlTreeBuilder.process

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1543]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Security_Severity-Low Reported-2021-05-13 Proj-jsoup
Type: Bug-Security

New issue 34250 by ClusterFuzz-External: jsoup:HtmlFuzzer: Uncaught exception in org.jsoup.parser.HtmlTreeBuilder.process
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34250

Detailed Report: https://oss-fuzz.com/testcase?key=5802255765864448

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: HtmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Uncaught exception
Crash Address: 
Crash State:
  org.jsoup.parser.HtmlTreeBuilder.process
  org.jsoup.parser.HtmlTreeBuilderState$14.process
  java.base/java.util.Arrays.binarySearch0
  
Sanitizer: address (ASAN)

Recommended Security Severity: Low

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5802255765864448

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by krystiangorecki** [comment]
To reproduce:
```
Jsoup.parse("<table><td><table" + (char) 26 + "<tfoot" + (char) 1 + "</tfoot>");

**Comment by offa** [comment]
This causes a StackOverflowException due to endless recursion.

**Comment by krystiangorecki** [comment]
When the StackOverflowError occurs Document being built in HtmlTreeBuilder looks like that:
```
<html>
 <head></head>
 <body>
  <table>
   <tbody>
    <tr>
     <td>
      <table>
       <tfoot></tfoot>
      </table></td>
    </tr>
   </tbody>
  </table>
 </body>
</html>
```
but I don't know how to proceed with this further.

**Comment by jhy** [comment]
Thanks - fixed. I think the spec may have changed since when I originally implemented to handle this (or I mis-implemented originally). https://html.spec.whatwg.org/#parsing-main-intr
