### ISSUE TITLE
[34258] jsoup:XmlFuzzer: Uncaught exception in java.base/java.lang.StringUTF16.newBytesFor

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1545]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Security_Severity-Low Reported-2021-05-13 Proj-jsoup
Type: Bug-Security

New issue 34258 by ClusterFuzz-External: jsoup:XmlFuzzer: Uncaught exception in java.base/java.lang.StringUTF16.newBytesFor
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34258

Detailed Report: https://oss-fuzz.com/testcase?key=5261883784429568

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: XmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Uncaught exception
Crash Address: 
Crash State:
  java.base/java.lang.StringUTF16.newBytesFor
  java.base/java.lang.AbstractStringBuilder.inflate
  java.base/java.lang.AbstractStringBuilder.putStringAt
  
Sanitizer: address (ASAN)

Recommended Security Severity: Low

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5261883784429568

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by jhy** [comment]
This was a OOM related to string creation when parsing recursive XML declarations, which was fixed by f84549e9fb5618cf58e37dc2f00adb8a279da371 (#1539).
