### ISSUE TITLE
[34326] jsoup:XmlFuzzer: Timeout in XmlFuzzer

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1546]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Proj-jsoup Reported-2021-05-15
Type: Bug

New issue 34326 by ClusterFuzz-External: jsoup:XmlFuzzer: Timeout in XmlFuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34326

Detailed Report: https://oss-fuzz.com/testcase?key=6413348544577536

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: XmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address: 
Crash State:
  XmlFuzzer
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105140611

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6413348544577536

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by jhy** [comment]
This was fixed by #1544
