### ISSUE TITLE
Can't specify POST request encoding

### ISSUE THREAD

**Issue by archislav** [jhy/jsoup#155]
For example, I want to make POST request for http://mysite.com with parameter 'a' equals to bookName variable. 

Document searchPage = Jsoup.connect("http://mysite.com").data("a", bookName).post();

That's OK for latin letters, but it fails, when I try to use it with cyrilic letters in windows-1251, bookName is URLencoded with utf-8 encoding in POST data.

You can look at HttpConnection.writePost method, it uses DataUtil.defaultCharset = "UTF-8".

So it will be great if you provide an ability to specify encoding for request. 
For example:

Document searchPage = Jsoup.connect("http://mysite.com").data("a", bookName).requestEncoding("windows-1251").post();

**Comment by jhy** [comment]
Fixed with that merge, thanks.
