### ISSUE TITLE
NBSP creates invalid tags

### ISSUE THREAD

**Issue by rockwotj** [jhy/jsoup#1550]
First - thanks for this library - it's great!

We just ran into an error where we got a bit of HTML that looks like this (encoded as a java string for clarity).

```java
String html = "<a\u00A0href=\"http://example.com/test\">test</a>"
```

This causes the tag to be parsed as: `a\u00A0href="http:`. Should the parser be made more tolerant to this sort of error? I'm assuming it's checking explicitly for ascii space - should any unicode whitespace character be a delimiter?

**Comment by zoey-shan** [comment]
hey, I'm going to fix this issue

**Comment by jhy** [comment]
That will pull it out of the HTML5 spec that jsoup targets, so I don't see this as something we should implement.

https://infra.spec.whatwg.org/#ascii-whitespace
