### ISSUE TITLE
Spurious null bytes in parsed text with accented characters

### ISSUE THREAD

**Issue by ujay68** [jhy/jsoup#1557]
Run this test against Jsoup 1.13.1, OpenJDK 8:

```    
    @Test
    public void testJsoupNullBytes() throws IOException {
        Document parsed = Jsoup.parse(new ByteArrayInputStream("<p>H\u00E9llo, w\u00F6rld!".getBytes("UTF-8")), null, "");
        String text = parsed.selectFirst("p").wholeText();
        assertThat(text, not(is("H\u00E9llo, w\u00F6rld!\0\0"))); 
        assertThat(text, is("H\u00E9llo, w\u00F6rld!"));
    }
```
Both assertions fail. The text in the parsed `p` element, which should be `"Héllo, wörld!"` exactly, instead ends with two null bytes, like so: `"Héllo, wörld!\0\0"`. 

This might be a misalignment resulting from the 2-byte UTF-8 sequences of the characters `é` and `ö`, because if you replace one of the two accented characters with its ASCII base character, only one null byte remains, and if you replace both, the string `"Hello, world!"` is returned with no trailing null bytes. Also note that if you explicitly close the paragraph with `</p>`, the null bytes appear _after_ the closing `</p>` in the output tree.

**Comment by jhy** [comment]
I'm not able to repro this - see test case attached (which passes on all variants - https://github.com/jhy/jsoup/runs/3039924290)

jsoup has supported UTF-8 and these characters from very early days, so I'm surprised you're running into an issue here.

Passing `null` to `parse` as the character encoding will force to UTF-8 unless there's a BOM or a meta character encoding set (which there isn't in this case). So I can't guess the error. Feel free to send in a PR if you can repro it.
