### ISSUE TITLE
Memory leak with jsoup.clean.

### ISSUE THREAD

**Issue by EugenMayer** [jhy/jsoup#1558]
I have quiet extensive JUnit 5 tests (arround 800). Quiet some of those create and delete entities, which include fields like name, title, description and so forth, which I sanitize this way:

```
public class SomeHelper
{
  static Whitelist none = Whitelist.none();

  public static String strip(String input)
  {
    if (input == null) {
      return null;
    }
    // Strip all HTML elements
    input = Jsoup.clean(input, none);
    // For any left overs, encode it so it cannot be used in an HTML content
    return Encode.forHtml(input).replace("\0", "");
  }
}
```

The encoder is `org.owasp.encoder.Encode`

When I do so, my test run out of heap on the CI. Removing `input = Jsoup.clean(input, none);` fixes exactly. I assume there is a memory leak, I tried to analyze it with yourkit but was not able to find it (but this is nothing I do regularly, I'am fairly new to java profiling).

I could not find any other reports but maybe someone with more profiling skills and jsoup internal knowledge can help out getting to the cause?

**Comment by jhy** [comment]
What is the specific exception you get? What is your heap size and the rest of your Java environment details?

The Jsoup.clean() method is static with no global state, and if you follow the implementation you can see all the objects are created new. My guess is that you are not seeing a leak, but one of the inputs is larger than your heap and you are running out of memory.

My suggestion would be to log the filenames / hashes of the input, run until you get an OOM, and then replay just that specific input and validate its the single input creating the OOM (vs a slow leak).

If that's the case, you may look to increase your heap to be able to parse the document into a DOM successfully.

**Comment by EugenMayer** [comment]
I already upped the heap and it was not working. I removed jsoup for this purpose entirely and have no issues since. So i can neither provide informations anymoree nor confirm your theory, sorry.

Feel free to close if you consider this to be not enough context.
