### ISSUE TITLE
builders variable is static causing synchronization between threads in web applications

### ISSUE THREAD

**Issue by manojbglr** [jhy/jsoup#1562]
I observe that the StringUtil.java in the version 1.13.1  has a static declaration. IN some earlier version it was declared as thread local.
When the jsoup.clean is called it has a syncronization block on this object. As a result borrowBuilder and releaseBuilder are blocked on this for some time. This is causing a massive performance  issue in a tomcat basd deployment.
Almost all threads are shown to be waiting on the Stack (/builders).

I see earlier it was declared as thread local which would allow builders to be reused in the thread but not across the jvm. That approach is preferable as it avoids the syncronization block.[](url)

version 1.13.1  StringUtil.java Line number 232 
**private static final Stack<StringBuilder> builders = new Stack<>();**

  public static StringBuilder borrowBuilder() {
        **synchronized** (builders) {
            return builders.empty() ?
                new StringBuilder(MaxCachedBuilderSize) :
                builders.pop();
        }
    }

 public static String releaseBuilder(StringBuilder sb) {
        Validate.notNull(sb);
        String string = sb.toString();

        if (sb.length() > MaxCachedBuilderSize)
            sb = new StringBuilder(MaxCachedBuilderSize); // make sure it hasn't grown too big
        else
            sb.delete(0, sb.length()); // make sure it's emptied on release

        **synchronized** (builders) {
            builders.push(sb);

            while (builders.size() > MaxIdleBuilders) {
                builders.pop();
            }
        }
        return string;
    }

Earlier version :

 private static final **ThreadLocal**<Stack<StringBuilder>> threadLocalBuilders = new ThreadLocal<Stack<StringBuilder>>() {
        @Override
        protected Stack<StringBuilder> initialValue() {
            return new Stack<>();
        }
    };

 public static StringBuilder borrowBuilder() {
        Stack<StringBuilder> builders = threadLocalBuilders.get();
        return builders.empty() ?
            new StringBuilder(MaxCachedBuilderSize) :
            builders.pop();
    }

 public static String releaseBuilder(StringBuilder sb) {
        Validate.notNull(sb);
        String string = sb.toString();

        if (sb.length() > MaxCachedBuilderSize)
            sb = new StringBuilder(MaxCachedBuilderSize); // make sure it hasn't grown too big
        else
            sb.delete(0, sb.length()); // make sure it's emptied on release

        Stack<StringBuilder> builders = threadLocalBuilders.get();
        builders.push(sb);

        while (builders.size() > MaxIdleBuilders) {
            builders.pop();
        }
        return string;
    }

**Comment by jhy** [comment]
Yes - this is fixed by #1402
