### ISSUE TITLE
Report: jsoup working inside Snowflake as a Java UDF [discussion]

### ISSUE THREAD

**Issue by fhoffa** [jhy/jsoup#1563]
Just wanted to add a note that making jsoup work inside Snowflake was quick and seamless - users can now add it as a Java UDF to work within SQL.

- https://stackoverflow.com/questions/68029047/how-can-i-parse-html-with-a-snowflake-udf

Thanks!

**Comment by jhy** [comment]
Super cool! Thanks for the note
