### ISSUE TITLE
[35447] jsoup:XmlFuzzer: Timeout in XmlFuzzer

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1566]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Security_Severity-Low Proj-jsoup Reported-2021-06-21
Type: Bug-Security

New issue 35447 by ClusterFuzz-External: jsoup:XmlFuzzer: Timeout in XmlFuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35447

Detailed Report: https://oss-fuzz.com/testcase?key=5807882221256704

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: XmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address: 
Crash State:
  XmlFuzzer
  
Sanitizer: address (ASAN)

Recommended Security Severity: Low

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202106200602

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5807882221256704

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by jhy** [comment]
Same root cause and fix as #1544
