### ISSUE TITLE
CDATA processing inconsistent

### ISSUE THREAD

**Issue by stefanhh0** [jhy/jsoup#1568]
Hello,

I found that CDATA processing seems to be inconsistent, see the test:
https://github.com/stefanhh0/playground/blob/master/src/test/java/com/github/stefanhh0/playground/JSoupCdataTest.java

The output is as follows:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.github.stefanhh0.playground.JSoupCdataTest
[ERROR] Tests run: 6, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.236 s <<< FAILURE! - in com.github.stefanhh0.playground.JSoupCdataTest
[ERROR] com.github.stefanhh0.playground.JSoupCdataTest.test(String)[2]  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <test]]>>
        at com.github.stefanhh0.playground.JSoupCdataTest.test(JSoupCdataTest.java:28)

[ERROR] com.github.stefanhh0.playground.JSoupCdataTest.test(String)[3]  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <test]]>>
        at com.github.stefanhh0.playground.JSoupCdataTest.test(JSoupCdataTest.java:28)

[ERROR] com.github.stefanhh0.playground.JSoupCdataTest.test(String)[4]  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <<script>test</script>>
        at com.github.stefanhh0.playground.JSoupCdataTest.test(JSoupCdataTest.java:28)

[ERROR] com.github.stefanhh0.playground.JSoupCdataTest.test(String)[5]  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <test]]>>
        at com.github.stefanhh0.playground.JSoupCdataTest.test(JSoupCdataTest.java:28)

[ERROR] com.github.stefanhh0.playground.JSoupCdataTest.test(String)[6]  Time elapsed: 0.013 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <test]]>>
        at com.github.stefanhh0.playground.JSoupCdataTest.test(JSoupCdataTest.java:28)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JSoupCdataTest.test:28 expected: <> but was: <test]]>>
[ERROR]   JSoupCdataTest.test:28 expected: <> but was: <test]]>>
[ERROR]   JSoupCdataTest.test:28 expected: <> but was: <<script>test</script>>
[ERROR]   JSoupCdataTest.test:28 expected: <> but was: <test]]>>
[ERROR]   JSoupCdataTest.test:28 expected: <> but was: <test]]>>
[INFO] 
[ERROR] Tests run: 7, Failures: 5, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.057 s
[INFO] Finished at: 2021-06-25T18:52:40+02:00
[INFO] ------------------------------------------------------------------------
```
The very different result regarding case sensitivity seems to me like a bug. Additionally when passing in a: `<![CDATA[<script>test</script>]]>` then the script is no longer filtered but CDATA is stripped, which seems to me pretty dangerous. Additionally why is CDATA anyway stripped when passed to clean? Shouldn't it be left untouched, since CDATA already escapes the code as being text and should not be executed anyway when inside of CDATA? The other failures show that in case of cdata the script is not fully removed, but leftovers are returned.

I am interested to hear if that is something already known and would be interested in a fix in the not too far future.

Thanks for providing this useful library & best regards
Stefan

**Comment by jhy** [comment]
Input | Cleaned 
----|------
```<![cdata[<script>test</script>]]>``` | ```test]]&gt;```
```<![cdata[<SCRIPT>test</SCRIPT>]]>``` | ```test]]&gt;```
```<![Cdata[<script>test</script>]]>``` | ```test]]&gt;```
```<![cDatA[<script>test</script>]]>``` | ```test]]&gt;```
```<![CDATA[<script>test</script>]]>``` | ```&lt;script&gt;test&lt;/script&gt;```

It looks completely to me. CDATA sections are always [defined ](https://html.spec.whatwg.org/#cdata-sections)with a full uppercase `<![CDATA] ... ]]>`. This is defined in HTML5 and how browsers implement.

None of the other examples are CDATA sections and so are treated as a bogus comment aka `<!--cdata[<script-->`. And so the Cleaner drops that comment and retains the remaining character data.

The actual CDATA section is read in as character data (because that's what it is) and presented as a HTML character stream (hence the escapes). This is functionally the same as emitting it as a CDATA section, and a matter of taste which you prefer. I find the explicit characters more explicit and so that's what is used.

Nothing here is an XSS path.

**Comment by stefanhh0** [comment]
> The actual CDATA section is read in as character data (because that's what it is) and presented as a HTML character stream (hence the escapes). This is functionally the same as emitting it as a CDATA section, and a matter of taste which you prefer. I find the explicit characters more explicit and so that's what is used.

Stripping CDATA is not necessary in such a case and it would be less invasive to just keep the CDATA.

Since the not uppercase is no danger why it is being stripped, then again the trailing ]] is not seen as bogus and not stripped... I'd prefer that jsoup keeps the harmless not uppercase cdata and just removes the script inside.

I'd prefer that Jsoup only cleans where it is necessary and keeps all other places untouched (as is).

**Comment by jhy** [comment]
As I mentioned, the others get removed as the Cleaner removes comments - which is similar to why the CDATA is converted to a character run (and not stripped). 

For cases where you have a particular need for a specific output, the Cleaner is open to extension and relatively straightforward to implement whatever output you prefer.

**Comment by stefanhh0** [comment]
Thank you for your helpful replies and clarifications Jonathan! I don't intend to extend the cleaner since I understand your point that it is not a bug. And some may like to have not uppercase/bogus CDATA string to be removed and regular CDATA sections converted into a character run.

Best regards
Stefan

**Comment by stefanhh0** [comment]
One more Observation, I have changed the test accordingly: https://github.com/stefanhh0/playground/blob/master/src/test/java/com/github/stefanhh0/playground/JSoupCdataTest.java and added a new Test: testScriptRemovedCompletely, the test fails with: expected: <]]&gt;> but was: <test]]&gt;>

While it may not be a bug but it looks to me like asymmetric behavior, the script is not fully removed when it was prepended with a bogus cdata (String "test" is retained). However, if it was not prepended with a bogus cdata, then the script is removed completely (String "test" is gone).
