### ISSUE TITLE
Off topic, is there a discord or mailing list?

### ISSUE THREAD

**Issue by damienhunter30** [jhy/jsoup#1594]
I'd love to learn more and contribute to the project. I don't want to jump right in, because I want to understand the code and the class/package interactions first.

**Comment by jhy** [comment]
Hi! There was a mailing list on Google Groups, but that's pretty defunct now. I have thought potentially around running a slack / mattermost / etc channel, but am not sure that I can commit the time to sitting in it to be not a ghost town. For now, more than happy to have discussion here (flag issues / threads with the Discussion label).

**Comment by damienhunter30** [comment]
Thanks for getting back to me on it.
