### ISSUE TITLE
Feature Request: Implement the org.w3c.dom.ls.DOMImplementationLS interface.

### ISSUE THREAD

**Issue by silnith** [jhy/jsoup#1598]
This is a feature request. It would greatly simplify integrating with existing systems if JSoup implemented `org.w3c.dom.ls.DOMImplementationLS`. This would allow JSoup to be dropped into existing codebases and loaded using the standard DOM bootstrap.

**Comment by jhy** [comment]
Hi,

Are you across the [W3CDom](https://jsoup.org/apidocs/org/jsoup/helper/W3CDom.html#convert(org.jsoup.nodes.Document)) helper, which converts a jsoup document to a w3c document (which then supports those interfaces)?

Does that solve for your use-case?

**Comment by silnith** [comment]
No, because the entire purpose of the `DOMImplementationLS` interface is to hide the specific implementation library from the consuming application. `W3CDom` requires the application to have an explicit dependency on JSoup. `DOMImplementationLS` allows using a DOM at runtime without knowing ahead of time what library is being used. In the case of OSGi, a consuming application would not even be able to cast to an implementation, because the consuming application and the JSoup library would exist in different classloaders.

**Comment by jhy** [comment]
Feels like you just need a shim then... Happy to look at a PR.
