### ISSUE TITLE
Wrong parsed empty elements

### ISSUE THREAD

**Issue by boriskr** [jhy/jsoup#161]
val doc = Jsoup.parseBodyFragment("< div /> < div />")
doc: org.jsoup.nodes.Document = 
"< htm l>
 < head >< /head >
 < body >
  < div > 
   < div >< /div >
  < /div >
 < /body >
< /html >
"

**Comment by jhy** [comment]
Sorry for late reply. Fixed some time ago. Now creates

```
<html>
 <head></head>
 <body>
  <div></div>
  <div></div>
 </body>
</html>
```
