### ISSUE TITLE
Node.absUrl does not work with telephone numbers.

### ISSUE THREAD

**Issue by FlameDuck** [jhy/jsoup#1610]
A Node that contains a telephone number will return a blank string, when parsed with absUrl.

As far as I can tell this is a violation of the contract, which states:

"An absolute URL if one could be made, or an empty string (not null) if the attribute was missing or could not be made successfully into a URL."

Here is a small jUnit test that reproduces the problem, that is it fails, when it should pass.

    @Test
    void test() {
        Jsoup.parse("<!DOCTYPE html>\n" +
                        "<html>\n" +
                        "<head>\n" +
                        "    <title>Not Empty</title>\n" +
                        "</head>\n" +
                        "<body>\n" +
                        "<a href=\"/example.html\">Example Hyperlink</a>\n" +
                        "<a href=\"mailto:example@eample.com\">Example Mailto Link</a>\n" +
                        "<a href=\"tel:202-456-1414 \">Example Telephone Link</a>\n" +
                        "</body>\n" +
                        "</html>\n", "http://localhost/")
                .select("a[href]")
                .stream().map(node -> node.absUrl("href"))
                .forEach(absUrl -> assertFalse(absUrl.isBlank()));
    }

**Comment by jhy** [comment]
Thanks, fixed. It was failing when constructing it as a URL, because Java will throw a MalformedUrlException if there is not a defined URL stream handler for it.

So the change is to catch those, and if the URL starts with a syntactically valid URI scheme, pass it as-is.
