### ISSUE TITLE
Node.equals() does not accept null in Kotlin

### ISSUE THREAD

**Issue by lukas-krecan** [jhy/jsoup#1628]
`Node.equals()` parameter "inherits" non-nullable annotation which causes Kotlin to refuse to compile `node != null`. We can use `node !== null` but it feels strange. I assume it is not intentional.

**Comment by jhy** [comment]
Hi -- could you add a code snippet in Kotlin of what should work but doesn't? I assume you mean that the input parameter should be marked as Nullable?

**Comment by lukas-krecan** [comment]
Yes, the input parameter should be marked as nullable. 

```kotlin
val node: Node? = null
println(node == null) // No method 'equals(Any?): Boolean' available
```

**Comment by jhy** [comment]
Thanks, fixed! Can you please take a look and confirm (using e.g. a snapshot build). And please let me know if you see other areas where the Kotlin integration can be improved.
