### ISSUE TITLE
make EscapeMode a class, not enum

### ISSUE THREAD

**Issue by Nowaker** [jhy/jsoup#163]
Please migrate EscapeMode to be a standard class, not enum. Enum makes the library inflexible - and that's why people beg you to add some new escape modes of their need.

```
doc.outputSettings().prettyPrint(false).escapeMode(EscapeMode.XHTML); // predefined
doc.outputSettings().prettyPrint(false).escapeMode(new EscapeMode() { ... }); // mine
```

Why I need it. I need to write my own escaping mode that will never touch any unknown entity. For example, if the XML document contains `&blah;`, it gets escaped to `&amp;blah;`. Since the code runs on my customers machines, I don't even know what their XMLs look like. It's unacceptable that I agressively escape their entities as their XMLs were already valid and well-formed.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
