### ISSUE TITLE
<template> element closes <head>

### ISSUE THREAD

**Issue by gerdriesselmann** [jhy/jsoup#1630]
A \<template> element inside a \<head> closes the head. 

See the following example: https://try.jsoup.org/~EGp3UZxQe503TJDHQEQEzm8IeUc

The \<template> element is allowed within other elements that accept meta data content (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template).

The \<head> element accepts meta data content (in fact it only accepts meta data content): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head

Therefore \<template> elements are valid inside a \<head>, and the \<head> should not be closed.

This also is like both Firefox and Chrome handle the example code.

**Comment by Noki** [comment]
There is probably a more general problem with the handling of the `<template>` element with other issues present (#1409, #1315).

**Comment by jhy** [comment]
Feature track: #1634
