### ISSUE TITLE
Add [contains|matches][own]Whole

### ISSUE THREAD

**Issue by jhy** [jhy/jsoup#1636]
After reviewing #876 and the related #576. I think we can make some improvements, and also maintain backwards compatibility:

 - (**done**)  for `:contains(text)`, normalize the selector text in the same way that the `text() ` and `ownText()` methods work. That directly fixes this issue. I conceptually like the neatness of using `:contains("text")` to use a non-normalized search, but that's a bit stringly typed, and maybe backwards in-compat.
 - (**done**)  introduce `:containsWholeText` and :containsWholeOwnText which uses `wholeText()` and `wholeOwnText()` and no normalization to either the input or the query. That way we can find content including newlines, tabs, repeated spaces, etc
 - for #576, introduce `:matchesWholeText` and `:matchesWholeOwnText`, to work similarly for regular expressions

**Comment by xiaoxianma** [comment]
@jhy Hi Jon, I'm interested in this ticket. Is this done? Is there anything I can help with for this ticket?

**Comment by jhy** [comment]
Thanks @xiaoxianma for your offer; I've completed these, but you're of course welcome to hit up other issues / help with PRs etc.
