### ISSUE TITLE
About EscapeMode

### ISSUE THREAD

**Issue by kmjuq** [jhy/jsoup#1661]
Can you add this enumerator EscapeMode.NONE 。I use jsoup clean for Http request payload , but the content is escaped.
`"name"kmj -> &quot;name&quot;kmj`

If you agree but don't have time, I can do it myself 。

**Comment by kmjuq** [comment]
```java
public class XssHttpServletRequestWrapper extends HttpServletRequestWrapper{
    static EscapeMode extended;
    static {
        extended = EscapeMode.extended
        extended.getMap().clear();
    }
}
```
Now i use this way

**Comment by jhy** [comment]
This has been discussed before - if we add EscapeMode.None, we create a way to generate invalid HTML. So, no, I don't plan to do that.

Anyway, quotes in HTML element text contents are not escaped:
https://github.com/jhy/jsoup/blob/46b0b9569a76b65f31e75fa94d38f6766709c52a/src/main/java/org/jsoup/nodes/Entities.java#L217-L221

And the content is not escaped when going through the cleaner either:
https://try.jsoup.org/~-Y0E8waf_v2nap-NaOZq342uPrE

So I think you're maybe doing something wrong. If you post a small testcase (input, code, desired and actual output), I can take a look.

**Comment by kmjuq** [comment]
> This has been discussed before - if we add EscapeMode.None, we create a way to generate invalid HTML. So, no, I don't plan to do that.
> 
> Anyway, quotes in HTML element text contents are not escaped:
> 
> https://github.com/jhy/jsoup/blob/46b0b9569a76b65f31e75fa94d38f6766709c52a/src/main/java/org/jsoup/nodes/Entities.java#L217-L221
> 
> And the content is not escaped when going through the cleaner either: https://try.jsoup.org/~-Y0E8waf_v2nap-NaOZq342uPrE
> 
> So I think you're maybe doing something wrong. If you post a small testcase (input, code, desired and actual output), I can take a look.

Thanks, I found out that the reason is the version 。

```java
// jsoup 1.7.3  the result is error
String content1 = "<p>不好意思，我不是很理解您的问题，请用一句话准确描述</p><p><img src=\"1\" onerror=\"alert(1)\"/></p>";
String content2 = "------WebKitFormBoundaryvdmlt4gdBgNBSSP6\n" +
        "Content-Disposition: form-data; name=\"unknownWord\"\n" +
        "\n" +
        "<p>不好意思，我不是很理解您的问题，请用一句话准确描述</p><p><img src=\"1\" onerror=\"alert(1)\"/></p>\n" +
        "------WebKitFormBoundaryvdmlt4gdBgNBSSP6";
System.out.println(String.format("content1 [%s]",Jsoup.clean(content1, Whitelist.relaxed())));
System.out.println(String.format("content2 [%s]",Jsoup.clean(content2, Whitelist.relaxed())));
// jsoup 1.14.3 the result is right
String content1 = "<p>不好意思，我不是很理解您的问题，请用一句话准确描述</p><p><img src=\"1\" onerror=\"alert(1)\"/></p>";
String content2 = "------WebKitFormBoundaryvdmlt4gdBgNBSSP6\n" +
        "Content-Disposition: form-data; name=\"unknownWord\"\n" +
        "\n" +
        "<p>不好意思，我不是很理解您的问题，请用一句话准确描述</p><p><img src=\"1\" onerror=\"alert(1)\"/></p>\n" +
        "------WebKitFormBoundaryvdmlt4gdBgNBSSP6";
System.out.println(String.format("content1 [%s]",Jsoup.clean(content1, Whitelist.relaxed())));
System.out.println(String.format("content2 [%s]",Jsoup.clean(content2, Whitelist.relaxed())));
```
