### ISSUE TITLE
Additional files (README and CHANGES) published in META-INF

### ISSUE THREAD

**Issue by anthonymonori** [jhy/jsoup#1666]
While this can always be filtered out in the consumer side, I find it unnecessary that jsoup ends up putting the `README.md` and `CHANGES` in the `META-INF` folder, resulting in additional 17.4 KB (aprox) extra space.

https://github.com/jhy/jsoup/blob/master/pom.xml#L233-L234

Is there any specific reason why is this being done on purpose? LICENSE file I may understand (although I don't seem to get that -- probably something our android build tools filters out), but not the other two.

Would you consider removing those? Or you see it as something to be done by the users of the library in their use cases?

**Comment by jhy** [comment]
The jar is the canonical published artifact. Yes, I want those files there.

**Comment by mateuszkwiecinski** [comment]
I just stumbled upon the same issue when realized my APKs also contains these files 👀 
They take ~24kb now :/ 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/36954793/156457308-7d895a62-9eeb-46f7-a6d8-800f48e994bf.png">

Would it be possible to somehow improve the experience for Android devs? Can this library publish some additional Proguard/R8 rules, so it gets automatically optimized when shrinking an apk with R8? 

And out of curiosity: what's the purpose of these files? Are there any tools that read jar content and parse it later? Isn't `LICENSE` information already included in `pom` file?

**Comment by anthonymonori** [comment]
Hey @mateuszkwiecinski 

For now, you can exclude them yourself during packaging of the aab/apk by adding the following to your app's `build.gradle.kts` (or equivalent in Groovy)

```kts
android {
    //...
    packagingOptions {
        resources {
            excludes.addAll(listOf("META-INF/README.md", "META-INF/CHANGES")) // https://github.com/jhy/jsoup/issues/1666
        }
    }
}
```

**Comment by mateuszkwiecinski** [comment]
Thanks. That's what I did actually :)  
Although, my concern was it's not obvious every Android project, using this great library, should have such configuration added. So I started wondering if it could be improved. Maybe there is a way to publish R8/Proguard configuration in a way this resources could be removed while shrinking?
