### ISSUE TITLE
Parsing error on empty comment

### ISSUE THREAD

**Issue by dannashirn** [jhy/jsoup#1667]
When parsing some Html like:
```html
<h1>My Header</h1>
<!---->
<p>Lorem ipsum</p>
```
I get the error
```
error:[<2:8>: Unexpected character '
' in input state [CommentStartDash]]
```
If there is a space or some text inside the comment then it does not fail.

I could just replaceAll("","") but it'd be great if they were just not failures.

**Comment by jhy** [comment]
Thanks - looks like the spec has changed a bit since I first implement, and some of the parse errors have been removed.

**Comment by ujali** [comment]
Thanks, @jhy  for the fix. do we have an ETA on the next release?

**Comment by ujali** [comment]
@jhy we need this fix, is there any ETA on the next release?

**Comment by jhy** [comment]
It's out now
