### ISSUE TITLE
Parent elements removed when appendElement method is chained to a constructor

### ISSUE THREAD

**Issue by michaelalandawson** [jhy/jsoup#1669]
I'm attempting to create a hierarchy of simple elements, therefore, I'm using the appendElement.

Sample code.  I'm running this in ColdFusion 2021 using the ability to run native Java code.

````
import org.jsoup.nodes.Element;

public class ClassName {
	public Element getElement1() {
		Element thisElement = new org.jsoup.nodes.Element("div").appendElement("p").appendElement("button");

		return thisElement;
	}

	public Element getElement2() {
		Element thisElement = new org.jsoup.nodes.Element("div");

		thisElement.appendElement("p").appendElement("button");

		return thisElement;
	}
}
````

Desired Results:

````
<div>
  <p>
    <button></button>
  </p>
</div>
````

When I chain the appendElement method directly to a constructor, all parent elements are removed.  (Example function "getElement1".)

Results of getElement1:

````
<button></button>
````

If I separate appendElement from the constructor, I am able to get the desired results.  (Example function "getElement2".)

Results of getElement2:

````
<div>
  <p>
    <button></button>
  </p>
</div>
````

**Comment by Ruisong4** [comment]
According to the documentation, this method returns the new element, so it is actually the expected behavior.

just like in the second example, thisElement.appendElement("p").appendElement("button"); will give you a button

**Comment by michaelalandawson** [comment]
The method does not return consistent results.  If chained to a constructor, it return the new element.  If not chained to a constructor, it returns the first element in the chain.

**Comment by jhy** [comment]
This is an issue due to your code implementation, not the method return in appendElement. It doesn't / can't know if it's in a chained call or not -- java doesn't expose that.

The issue is that in your first method, you are setting and returning `thisElement` as the result of `.appendElement("button");`. So, `button` is the expected correct result.

In getElement2, you are setting `thisElement` to the div, and returning that.
