### ISSUE TITLE
Parsing SequeceInputStream leads to loss of part of html content

### ISSUE THREAD

**Issue by KirylBubovich** [jhy/jsoup#1670]
When using `DataUtil::parseInputStream` with `SequenceInputStream`, the returned document contains only part of the html, and the other part is lost. This is due to the fact that we read more than the specified max bytes in `ConstrainableInputStream::readToByteBuffer`. The consequence of this is that in `DataUtil` the expression `input.read () == -1` returns `true` (although the input stream has not actually been read completely).

**Comment by jhy** [comment]
Thanks!
