### ISSUE TITLE
Jsoup ThreadLocal memory leak (again) #2543

### ISSUE THREAD

**Issue by scrmtrey91** [jhy/jsoup#1672]
### Describe the bug

`The web application [/App] created a ThreadLocal with key of type [org.jsoup.internal.StringUtil$1] (value [org.jsoup.internal.StringUtil$1@361160a7]) and a value of type [java.util.Stack] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]`

Not directly Vaadin related. More JSOUP issue but still.

This is with jsoup from vaadin bom and also from latest jsoup version on maven. This was exact same problem in some version of jsoup in vaadin 8 which has been fixed by using different jsoup version. My workstation starting to freeze because there was no memory left (31.9 used / 32gb). 

![image_2021_11_11T12_29_12_905Z](https://user-images.githubusercontent.com/24773401/141519714-c6f3d1f8-4806-4eae-8e85-025a15b64938.png)

### Expected-behavior

No memory leak / no message like this. 

I have another app with vaadin 19 and there is no such issue (because of different jsoup version).

### Reproduction

It is just a normal vaadin application.

### System Info

Windows 11
Vaadin 14.7.4 - Vaadin 14.7.5 (without spring boot)
Java 8

**Comment by scrmtrey91** [comment]
[vaadin flow issue 12355](https://github.com/vaadin/flow/issues/12355)

**Comment by pleku** [comment]
The used Jsoup version is 1.14.3 (Vaadin versions 14.7 + 21) and apparently it was not an issue with 1.12.1 (Vaadin 19).

**Comment by jhy** [comment]
Without any details on repro, I don't see how we can repro this. Can you create a (non Vaadin) minimal testcase?

Are you using any of the StringUtil methods elsewhere in your app that might not be calling the releaseBuilder() method?

**Comment by jhy** [comment]
I audited the use of borrowBuilder within the library, and each borrow has a corresponding release(). And, if release() isn't called, it doesn't matter too much as objects are only added to the thread local builder pool during the release() phase. If the release method is missed, it just effectively reverts to a new StringBuilder object and typical GC.

So my guess is that your app is retaining objects somewhere else. Would suggest inspecting the heap captured on app shutdown to diagnose.

**Comment by jhy** [comment]
I thought about this some more and from the information provided, I don't see an issue with jsoup here. For context, jsoup uses a threadlocal pool of StringBuilders to reduce the load on GC, as StringBuilders are used extensively during HTML serialization, and to a lesser degree during parsing. The StringBuilders are recycled in the thread(s) doing that work.

They are capped by the count of builders per thread and the size of the backing array of each builder, with the latter being deleted vs recycled on next use if it had to grow beyond its cap.

To my understanding, your app's warning is not meaningful - it is warning that those threads have buffers available for efficient reuse.

My suggestion would be to either null out those threads on app shutdown (if this is a shutdown warning?) or to configure that warning to be ignored.

I'll close this now as resolved. If you see an actual leak (vs a bounded buffer pool), please go ahead and reopen with a memory dump and/or a small code sample that reproduces.

Here's the impl code, for reference:
https://github.com/jhy/jsoup/blob/3bd4d793ad7af94b3596fdf35be86758ff94696b/src/main/java/org/jsoup/internal/StringUtil.java#L333-L365
