### ISSUE TITLE
font family is parse error

### ISSUE THREAD

**Issue by gap1994** [jhy/jsoup#1675]
original html:
`<section style="margin-top: -1px;padding: 16px;outline: 0px;max-width: 100%;letter-spacing: 0.544px;white-space: normal;font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif;background-color: rgb(255, 255, 255);border-color: rgb(95, 156, 239);line-height: 1.4;border-bottom-right-radius: 8px;border-bottom-left-radius: 8px;border-width: 1px;border-style: solid;box-sizing: border-box !important;overflow-wrap: break-word !important;">`

parse html:
`<section style="margin-top: -1px;padding: 16px;outline: 0px;max-width: 100%;letter-spacing: 0.544px;white-space: normal;font-family: -apple-system-font, BlinkMacSystemFont, " helvetica neue, pingfang sc, hiragino sans gb, microsoft yahei ui, yahei, arial, sans-serif;background-color: rgb(255, 255, 255);border-color: rgb(95, 156, 239);line-height: 1.4;border-bottom-right-radius: 8px;border-bottom-left-radius: 8px;border-width: 1px;border-style: solid;box-sizing: border-box !important;overflow-wrap: break-word !important;>`

**Comment by jhy** [comment]
Can you provide a specific, minimal reproducible test case? Can you clarify what specific issue you have? I guess you are complaining that there is no trailing `"` to close the attribute?

I can't repro that. I see:

`<section style="margin-top: -1px;padding: 16px;outline: 0px;max-width: 100%;letter-spacing: 0.544px;white-space: normal;font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif;background-color: rgb(255, 255, 255);border-color: rgb(95, 156, 239);line-height: 1.4;border-bottom-right-radius: 8px;border-bottom-left-radius: 8px;border-width: 1px;border-style: solid;box-sizing: border-box !important;overflow-wrap: break-word !important;"></section>`

https://try.jsoup.org/~swuLtH4SMwtyotTJNHnIFeyl6_A

**Comment by gap1994** [comment]
> Can you provide a specific, minimal reproducible test case? Can you clarify what specific issue you have? I guess you are complaining that there is no trailing `"` to close the attribute?
> 
> I can't repro that. I see:
> 
> `<section style="margin-top: -1px;padding: 16px;outline: 0px;max-width: 100%;letter-spacing: 0.544px;white-space: normal;font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif;background-color: rgb(255, 255, 255);border-color: rgb(95, 156, 239);line-height: 1.4;border-bottom-right-radius: 8px;border-bottom-left-radius: 8px;border-width: 1px;border-style: solid;box-sizing: border-box !important;overflow-wrap: break-word !important;"></section>`
> 
> https://try.jsoup.org/~swuLtH4SMwtyotTJNHnIFeyl6_A

Sorry!It`s my mistake!
That original html was urlencode
