### ISSUE TITLE
JSON parser support for jsoup. Meet: jsoup.json!

### ISSUE THREAD

**Issue by magicprinc** [jhy/jsoup#1679]
https://github.com/magicprinc/jsoup.json

**jsoup.json** is a powerful JSON [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt), 7158, [RFC 7159](http://www.ietf.org/rfc/rfc7159.txt) parser for jsoup.
It can consume almost every text as JSON and convert it internally to an XML-tree.

**Comment by magicprinc** [comment]
@jhy 
Could you remove "private" modifier from insertNode and popStackToClose methods in XmlTreeBuilder class?...
They are private now and I had to copy them in JsonTreeBuilder.

**Comment by jhy** [comment]
Looks like a fun project!

Could you give it a different name so that people don't think it's a sub-project of jsoup?

Thanks!

**Comment by magicprinc** [comment]
Sure!

How about: json4jsoup?

**Comment by jhy** [comment]
Sure, think that works -- thanks
