### ISSUE TITLE
Word Formatting - Line spacing issue

### ISSUE THREAD

**Issue by nikumari** [jhy/jsoup#1680]
Word Formatting - Line spacing issue.
we see a difference in the formatting of this text during Creating Word.
We investigated on the issue and identified that word have their own line-spacing settings.

So how to reduce the spaces in word document as every heading has one more space in word document.

![Capture](https://user-images.githubusercontent.com/95402109/144373451-3c6a04db-d473-481a-a89a-445b4ea40a50.PNG)

**Comment by jhy** [comment]
Sorry, I'm not following this at all. 

Can you post a minimal reproducing test case?

**Comment by damienhunter30** [comment]
Well I'd be as interested in understanding what it is the user is trying to accomplish. Trying to retain the line spacing from HTML to a Word Document, or remove it?

**Comment by jhy** [comment]
Closing, please re-open if you have a testcase demonstrating an issue.
