### ISSUE TITLE
Discussion: How to reproduce vulnerability described in https://github.com/jhy/jsoup/security/advisories/GHSA-m72m-mhq2-9p6c

### ISSUE THREAD

**Issue by jsmrcka** [jhy/jsoup#1681]
In an attempt to verify the vulnerability for our project, we are running tests against unpatched jsoup `1.14.1` (and also `1.13.1`) using reproducer testcases from:
- https://github.com/jhy/jsoup/issues/1611 (https://oss-fuzz.com/download?testcase_id=5920704691306496)
- https://github.com/jhy/jsoup/issues/1612 (https://oss-fuzz.com/download?testcase_id=6533282119417856)

Both tests pass.

What is the proper way to reproduce?

**Comment by jhy** [comment]
Those issues may not have been in a specific release.

**Comment by jsmrcka** [comment]
> Those issues may not have been in a specific release.

@jhy What does that mean? Do you know a way to reproduce the issues? It would really help us if we were able to write a test which would fail/pass for unfixed/fixed release.

**Comment by jhy** [comment]
There are test cases that cover each of the fixes. But to my mind, the simplest way to check if it's a vulnerable version is to look at the version number.
