### ISSUE TITLE
Pretty print of ```<script>``` in html causes extra lines to be added on each subsequent pretty print

### ISSUE THREAD

**Issue by hazendaz** [jhy/jsoup#1688]
Take https://github.com/revelc/formatter-maven-plugin/blob/main/src/test/resources/someFile.html and add <script>doSomething();<script> to the file as a test.  Run the formatting over and over, watch it keep adding extra empty lines every time it encounters a script block with content.  I've been looking into this but have yet to find where this problem is coming from.  Any pointers to help debug and/or suggest where this might be fixed would be greatly appreciated.  This is pretty print and makes it hard to use formatter-maven-plugin to format when this is encountered.  Issues are present in latest master even though we are still using the older releases at the moment.

**Comment by damienhunter30** [comment]
Can we merge this issue with #1689?

**Comment by hazendaz** [comment]
@damienhunter30 This is a different issue.  A script tag with content in it triggers a new line.  So each time the file is reformatted, it gets another new line.  So this continues to grow out of control.  Issue #1689 simply is extra space being left at end of various lines (and always a tag ending >).  In that case there is only ever one there, it doesn't add more extra spaces, just leaves them on lines that they exist instead of properly trimming.

**Comment by jhy** [comment]
@hazendaz can you add a small reproducing testcase here? I haven't been able to repro it using [try.jsoup](https://try.jsoup.org/~Hn6jvmLvU88RUcPDhlcdShk3T0U)

**Comment by hazendaz** [comment]
Can you expose all parameters there?  That site only does single spacing so most of the issues don't expose there.  Need 4 character spacing at least.  I can get the remainder later but suspect that is core to most issues.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Here is a link to config used.  https://github.com/revelc/formatter-maven-plugin/blob/main/src/main/resources/formatter-maven-plugin/jsoup/html.properties

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jhy** [comment]
Thanks, fixed. The issue was that when pretty printing in outlineMode, the closing `</script>` tag was incorrectly being indented, which caused extra newlines to be added to the script data nodes.

**Comment by hazendaz** [comment]
This is confirmed fixed.
