### ISSUE TITLE
ConcurrentModificationException when node.remove

### ISSUE THREAD

**Issue by laisanshan** [jhy/jsoup#1692]
When I manipulate childnodes, ConcurrentModificationException will appear through node.remove, and UnsupportedOperationException will appear through iterator. How should I delete the node of childnodes, this is very important to me, thanks for the answer

```
public static void f(List<Node> nodes) {
       for (Iterator<Node> iterator = nodes.iterator(); iterator.hasNext(); ) {
             Node node = iterator.next();
            if (node instanceof Element) {
                f(node.childNodes());
            } else if (node instanceof TextNode) {
                if (node.outerHtml().contains("some")) {
                    iterator.remove();//1.
                    node.remove();//2.
                }
            }
        }
    }
```

**Comment by jhy** [comment]
Can you add a snippet of the HTML you're testing with, and a description of what you're ultimately trying to do / what you want the final DOM to be?

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by laisanshan** [comment]
Currently, I use another delete list to store that i want to delete node, and delete node at another loop

**Comment by laisanshan** [comment]
> 您能否添加您正在测试的 HTML 片段，以及您最终尝试做什么/您希望最终 DOM 成为什么的描述？



> Can you add a snippet of the HTML you're testing with, and a description of what you're ultimately trying to do / what you want the final DOM to be?

sorry i didnt reply in time, the HTML testing snippet just simple a web page data
