### ISSUE TITLE
Provide an overloaded version of parse which does not require file encoding (charsetName)

### ISSUE THREAD

**Issue by mahozad** [jhy/jsoup#1693]
Is it possible to provide a `Jsoup.parse(file)` method which does not have the charset parameter?
It will make the code a tiny little bit more pleasant.

The method can use either of these approaches:
  - Assume `UTF-8`
  - Determine from `http-equiv` meta tag, if present
  - Try to [guess the encoding](https://tika.apache.org/2.2.0/api/org/apache/tika/parser/txt/CharsetDetector.html)
  - Use the default charset of the JVM

The first two are [what is documented for the parse method](https://jsoup.org/apidocs/org/jsoup/Jsoup.html#parse(java.io.File,java.lang.String)) when it is passed `null`.

I should say that Kotlin language standard library has [File::readText](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/read-text.html) extension function for Java `File` class that treats the file as `UTF-8` if no charset is provided by the user.

**Comment by jhy** [comment]
My thought process when designing that API was to make it explicit to the caller that they should aim to provide the character set, and that if it wasn't set, that jsoup would have to guess. The goal is to make it more explicit that a possibly incorrect default is going to be used.

One of jsoup's goals is to minimize dependencies and the required jar size, so I don't plan to include the Tika scan/guess.

I'm not clear on how we could both assume UTF-8 but also use the default charset of the JVM (if that were not UTF-8).

**Comment by mahozad** [comment]
My suggestion was to use only **one** of the options.

So, it is not possible to provide a method like below?

```java
public static Document parse(File file) throws IOException {
    return DataUtil.load(file, null, file.getAbsolutePath());
    // OR
    // return DataUtil.load(file, "UTF-8", file.getAbsolutePath());
}
```

**Comment by mahozad** [comment]
As for the last option (using the default charset of the JVM), I think [this feature](https://openjdk.java.net/jeps/400) scheduled for JDK 18 may be related.
