### ISSUE TITLE
Empty DIV is converted into non-empty DIV

### ISSUE THREAD

**Issue by toga98** [jhy/jsoup#170]
```java
Parser.parseBodyFragment("<div id=\"fb-comments\"/> <p> Para 1", "").body().html()
```

Yields:

    <div id="fb-comments"> 
    <p> Para 1</p>
    </div>

Expected:

    <div id="fb-comments"/> 
    <p> Para 1</p>

**Comment by jhy** [comment]
Fixed a while back.
