### ISSUE TITLE
Docs mention how to run examples but that doesn't work any longer

### ISSUE THREAD

**Issue by sebkur** [jhy/jsoup#1702]
I just noticed that in https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/examples/HtmlToPlainText.java#L24
we still say that it'd be possible to run the example like this:

    java -cp jsoup.jar org.jsoup.examples.HtmlToPlainText url

while that isn't true anymore and I think I'm responsible due to #700 

I'm wondering if we might want do move the example code into a separate module within the repository and add what's necessary to be able to run the examples somehow when one has cloned the sources locally?

I'm not an expert on how to do that with Maven (always using Gradle...) but could dig into it if you're interested in such a contribution.

Otherwise I have set up a standalone version of the examples here: https://github.com/sebkur/jsoup-examples. I guess having some separate repository for examples could also be a sensible approach, what do you think? Maybe it even inspires others to contribute more examples.

**Comment by ray-vgw** [comment]
Could we do a short-term revert?  We are upgrading to newer versions of JSoup and the HtmlToPlainText example is used in our code base and no longer compiles

**Comment by sebkur** [comment]
Hmm, I don't think the example code should be used in any code base outside this project. It's not really part of the public API, at least that's how I see it. I think a good solution here is to just copy the source code of that class into your project and potentially improve it and adapt it to your needs.

**Comment by jhy** [comment]
Thanks -- fixed with d6ed47079b9daa6734582443ea668963f166abb4. CLI example jar is `jsoup-examples.jar`.
