### ISSUE TITLE
Replacing JSR 305 with Spotbugs?

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1709]
How about replacing JSR 305 with Spotbugs annotations? It's still maintained and has a clear license (context: https://github.com/findbugsproject/findbugs/issues/128).

No strong opinion from my side though.

**Comment by offa** [comment]
ping @jhy

**Comment by jhy** [comment]
My inclination is to stay with the current implementation as it works and is BSD licensed. My specific concern with changing to another annotation API is how that impacts backwards compatibility. Those annotations are part of the contact in some way and I don't know what impacts there will be in changing it.

I am sure there is a path but without a strong motivation to move, prefer to leave as-is.
