### ISSUE TITLE
Whitespace problem on Element.text()

### ISSUE THREAD

**Issue by pippobaudos** [jhy/jsoup#171]
Hi, first thanks for have done this wonderful library.
Second I have found this problem:

<p>
    &nbsp; @Test<br />
    &nbsp; public void testToText() {<br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Document doc = Jsoup.parse(&quot;&lt;h1&gt;Title&lt;/h1&gt;Hello&quot;);<br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.out.println(doc.body().text());<br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Current result on Jsoup 1.6.1 is &quot;TitleHello&quot; without any whitespace<br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assertEquals(&quot;Title Hello&quot;, doc.body().text());<br />
    &nbsp; }</p>

Current result on Jsoup 1.6.1 is "TitleHello" without any whitespace
I have solved the problem modifying Element.text, adding a withespace after block element too:

```
private void text(StringBuilder accum) {
    appendWhitespaceIfBr(this, accum);

    for (Node child : childNodes) {
        if (child instanceof TextNode) {
            TextNode textNode = (TextNode) child;
            appendNormalisedText(accum, textNode);
        } else if (child instanceof Element) {
            Element element = (Element) child;
            if (accum.length() > 0 && element.isBlock() && !TextNode.lastCharIsWhitespace(accum))
              accum.append(" ");
            element.text(accum);
            // Patch Niccolò, modificato per costruire correttamente <h1>Title</h1><p>pippo</p>
            if (accum.length() > 0 && element.isBlock() && !TextNode.lastCharIsWhitespace(accum))
              accum.append(" ");
        }
    }
}
```

Thanks for all
Niccolò Becchi
@pippobaudos

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
