### ISSUE TITLE
Outdated link in cookbook

### ISSUE THREAD

**Issue by mernst** [jhy/jsoup#1718]
At 
  https://jsoup.org/cookbook/extracting-data/selector-syntax
The link with anchor text "CSS" is to
  https://www.w3.org/TR/2009/PR-css3-selectors-20091215/
which displays the message

    This version is outdated!
    For the latest version, please look at https://www.w3.org/TR/selectors-3/.

I don't see a repository for the cookbook where I can submit a pull request.

**Comment by jhy** [comment]
Thanks! Fixed
