### ISSUE TITLE
Currently no support for Unicode domain names!

### ISSUE THREAD

**Issue by ghost** [jhy/jsoup#172]
Hello,

I would like to point out the growing popularity of Unicode domain names in the West part of the world in countries such as Russia. Cyrillic characters in the domain name is now something normal and Jsoup should support it!

Currently when I try to access a url like http://втора-ръка.net for example, I get UnknownHostException.

Perhaps you should consider correctly encoding / decoding the url with the java built in IDN class before making the request?

Thank you for your time!

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
