### ISSUE TITLE
Problem with cloudflare

### ISSUE THREAD

**Issue by K1ssSh0t** [jhy/jsoup#1722]
When I try to make a connection to a CloudFlare site I always get the error "Status:403"

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by jhy** [comment]
@QAQGaeBolg I don't see the value of your comments like this. Can you stop doing that please.

@K1ssSh0t you might like to ask on a programming forum site for support. This Issues section is for tracking bugs in jsoup, which this is not.

**Comment by aumobiletools** [comment]
https://github.com/jhy/jsoup/issues/1797#issuecomment-1197372574
