### ISSUE TITLE
XML Escape mode should escape > in attributes

### ISSUE THREAD

**Issue by ericapradoc** [jhy/jsoup#1724]
The issue for '<' was solved in [#1420](https://github.com/jhy/jsoup/issues/1420) but '>' still not being escaped:

final Document doc = Jsoup.parse("<input class=\"text\" value=\" &gt; data  &lt; \"/>");
        doc.outputSettings().escapeMode(org.jsoup.nodes.Entities.EscapeMode.xhtml);
        System.out.println("Output: " + doc.select("input.text").get(0));

Current Output: `<input class="text" value=" > data  &lt; ">`
Expected Output: `<input class="text" value=" &gt; data  &lt; ">`

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by jhy** [comment]
@ericapradoc what makes you see this as an issue? `>` does not need to be escaped in XML attributes. See the spec here: https://www.w3.org/TR/xml/#syntax

Note that `>` _may_ (not _must_) be escaped.

There's a good summary here: https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/46637835#46637835
