### ISSUE TITLE
Clean: Links with stripped href should  be removed

### ISSUE THREAD

**Issue by cyberbeat** [jhy/jsoup#1731]
JSoup.clean() keeps links with stripped href like

```
<a href="invalid link">my link</a>

=> (JSoup.clean())

<a rel="nofollow">my link</a>
```

This makes no sense to me. The behaviour should be to strip the complete link to plaintext like

```
=>

my link
```

At least there should be a SafeList-Option to remove tags, if they do not have attribute xx after cleaning.

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by 11912916** [comment]
Hello, @cyberbeat, our group are interested in your problem and would like to work on this issue. Can we have a try?
——SE 2022 group haha, Sustech

**Comment by 11912916** [comment]
Hello, @cyberbeat , our group are interested in your problem and would like to work on this issue. Can we have a try?
——SE 2022 group haha,  SUSTech

**Comment by FKBugMaker** [comment]
Hi, @cyberbeat ,
I tried to fix this bug.
My idea is: remove the tag in the front and back of the plain text.

**Comment by cyberbeat** [comment]
Great, yes, simply remove the tag and keep the plain text.

**Comment by cyberbeat** [comment]
I had a quick look at your fix, and it looks a bit ugly?

Shouldn't it simply modify this method:

https://github.com/jhy/jsoup/blob/f4d00c290325935186f75f1206d16397cc157ced/src/main/java/org/jsoup/safety/Cleaner.java#L112

There the unsafe tag is cloned. There you could check, if the element gets invalid, and implement a special behaviour.

Perhaps it would also make sense, to define attributes that must exist after cleaning tag XX (that would be a more common solution, which could perhaps cover some other similar cases). Although such a solution would mean more work (configuration options).

**Comment by FKBugMaker** [comment]
> I had a quick look at your fix, and it looks a bit ugly?
> 
> Shouldn't it simply modify this method:
> 
> https://github.com/jhy/jsoup/blob/f4d00c290325935186f75f1206d16397cc157ced/src/main/java/org/jsoup/safety/Cleaner.java#L112
> 
> There the unsafe tag is cloned. There you could check, if the element gets invalid, and implement a special behaviour.
> 
> Perhaps it would also make sense, to define attributes that must exist after cleaning tag XX (that would be a more common solution, which could perhaps cover some other similar cases). Although such a solution would mean more work (configuration options).

Your solution seems very efficient. Thanks for your instruction!

**Comment by jhy** [comment]
Thanks, but I disagree. A elements are still meaningful in HTML without a href attribute, as for example with an id attribute to use as an inline anchor.

It might be useful to have a new feature which allows optional dropping of elements if they are missing a required attribute - which you could then use to get this described behaviour when desired.

**Comment by cyberbeat** [comment]
@jhy you are right, that elements maybe are meaningful without href. But if jsoup strips the href (with an url), it gets very unlikely, that the link was meant in such a way, and so will be useless, especially, if there are no further attributes like id. So I still think this is more a bug like a feature request.
