### ISSUE TITLE
ConnecTest#handlesUnknownEscapesAcrossBuffer fails if the network is not available

### ISSUE THREAD

**Issue by unshorn** [jhy/jsoup#1733]
The test fails with an unknown host exception when the network is not available.
`
[ERROR] Errors: 
[ERROR]   ConnectTest.handlesUnknownEscapesAcrossBuffer:524 » UnknownHost gist.githubuse...
[INFO] 
[ERROR] Tests run: 1008, Failures: 0, Errors: 1, Skipped: 2
`

**Comment by JeffXiesk** [comment]
The error is because one test needs the internet to request the url from the Internet. So I add a judge that when the connection is unstable, skip the test.

![3c7d3c4d068b0957be2a08b3ea12d23](https://user-images.githubusercontent.com/75991596/164892416-bceeaa8b-6c31-4c4f-983a-6014d86c652f.png)
