### ISSUE TITLE
Jsoup incorrectly removing CR/LF

### ISSUE THREAD

**Issue by Hardcore-fs** [jhy/jsoup#174]
Sometimes the HTML input has the text formatted with: 

0x0d,0x0a
0x0a
0x0d

Within a textarea or table column.

Whilst not HTML correct, removal of these delimiters by jsoup can cause some issues when extracting content.
There needs to be some way of keeping these strings intact.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
