### ISSUE TITLE
Jsoup 1.14.3 : self closing tag with and without slash "/>" at the end. It looks like self closing tags could have children, that's wrong.

### ISSUE THREAD

**Issue by FanJups** [jhy/jsoup#1741]
At [Open Source Society Cameroon](https://github.com/osscameroon), **we are trying to build a library converting html to js using Jsoup 1.14.3 but I'm facing an issue**. In order to reproduce the error, just run this [code](https://github.com/osscameroon/js-generator/blob/self-closing-tag-issue/src/main/java/com/osscameroon/jsgenerator/JSGenerator.java).

After converting this html code

 `String selfClosingTagsNotWorking = "<input type=\"text\">\r\n" + "<img src=\"#URL\" alt=\"image\">";`, 

we get the following js code 

```
var img = document.createElement("img");
img.setAttribute("src", "#URL");
img.setAttribute("alt", "image");

var input = document.createElement("input");
input.setAttribute("type", "text");
input.appendChild(img);
```

**The image tag is considered as a child of input tag but it's false.** `input.appendChild(img)` 

Let's consider another html code `String selfClosingTagsWorking = "<input type=\"text\"/>\r\n" + "<img src=\"#URL\" alt=\"image\">";` then the result is 

```
var input = document.createElement("input");
input.setAttribute("type", "text");

var img = document.createElement("img");
img.setAttribute("src", "#URL");
img.setAttribute("alt", "image");
```

**The image tag is NOT considered as a child of input tag, it's correct.**

This first example uses a self closing tag input without slash and the second uses the input with slash.

**My goal is to get the same result even if the self closing tag doesn't have a slash but it looks like Jsoup 1.14.3 lets self closing tag without slash to have children.**

**Comment by FanJups** [comment]
### UPDATE

Issue : https://github.com/osscameroon/js-generator/issues/41

**It is very important  to understand that there is a bug related to self closing tag in [Jsoup library](https://github.com/jhy/jsoup). It looks like self closing tags could have children, that's wrong.**

Let's take 2 examples : 

`<input type="text"> <img src="#URL" alt="image">`

`<input type="text"/> <img src="#URL" alt="image">`
		  
**Jsoup considers  `<input>` and `<input/>` as self closing tags. Consequently, they should not have children.**
		  
But there is something weird with Jsoup, `<input>` could have children if there is another html tag close to its position, this behavior is incorrect. `<input/>` could not, this is correct.

In the first example, Jsoup considers `<img>` as a child of `<input>`, this is false.  In the second example, Jsoup doesn't  consider `<img>` as a child of `<input/>`, this is true.

How could you verify that ? Just run the tests and look the logs. 

Here is the previous  code with self closing tag issue : https://github.com/osscameroon/js-generator/blob/self-closing-tag-issue/src/main/java/com/osscameroon/jsgenerator/service/ConvertServiceImpl.java

```
	private String appendChild(JsElement jsElement) {
		StringBuilder generatedCode = new StringBuilder();

		if (jsElement.getElement().children().size() > 0) {
			for (Element child : jsElement.getElement().children()) {
				generatedCode.append(jsElement.getElement().tagName()).append(".appendChild(").append(child.tagName())
						.append(");\n");
			}
		}

		return generatedCode.toString();
	}

```
		
In order to correct that, we created a condition to test if the tag is self closing then we do nothing. If it is not self closing and if there are children, only then we append children. Before this change, the only condition was if the element has children as you can see below.

This is why we had self closing tag with the possibility of having children, that's completely wrong.

```
	private String appendChild(JsElement jsElement) {
		
		StringBuilder generatedCode = new StringBuilder();
		
		
		/*
		 * Please, think twice before deleting this log, it helps to understand what is going on under the hood.
		 * It is really helpful to understand that there is a bug in Jsoup library.
		 * 
		 * Let's take an example, 
		 * 
		 * 
		 * <input type="text"> <img src="#URL" alt="image">
		 * 
		 * ------------------------------------------------------
		 * 
		 * <input type="text"/> <img src="#URL" alt="image">
		 * 
		 * Jsoup considers  <input> and <input/> as self closing tags.
		 * 
		 * Consequently, they should not have children.
		 * 
		 * But there is something weird with Jsoup, <input> could have children if there is another html tag close to its position, this behavior is incorrect. 
		 * <input/> could not, this is correct.
		 * 
		 * How could you verify that ? Just run the tests and look the logs. 
		 * 
		 * Here is the previous  code with self closing tag issue : https://github.com/osscameroon/js-generator/tree/self-closing-tag-issue
		 * 
		 * In order to correct that, we created a condition to test if the tag is self closing then we do nothing. 
		 * If it is not self closing and if there are children, only then we append children.
		 * 
		 *  Before this change, the only condition was if the element has children. 
		     This is why we had self closing tag with the possibility of having children, that's completely wrong.
		   
		 *  Useful links:
		 * 
		 *  https://www.educba.com/types-of-tags-in-html/
		
		    https://www.tutorialstonight.com/self-closing-tags-in-html.php#:~:text=HTML%20Self%20Closing%20Tag,%2C%20etc.

		 * */
		
		logger.log(Level.FINEST, " **** Analyze jsElement :"+jsElement.getElement().tag().getName()
				+" -> isEmpty : "+ jsElement.getElement().tag().isEmpty()
				+" -> isSelfClosing : "+ jsElement.getElement().tag().isSelfClosing() 
				+" -> isKnown : "+ jsElement.getElement().tag().isKnownTag()
				+ " -> hasChild : "+ jsElement.getElement().childrenSize()+ " **** ");
		
		if(jsElement.getElement().tag().isSelfClosing()) {
			
		}else {
			
			if (jsElement.getElement().children().size() > 0) {
				
				
				for (Element child : jsElement.getElement().children()) {
					
					
					generatedCode.append(jsElement.getElement().tagName()).append(".appendChild(").append(child.tagName())
							.append(");\n");
				}
			}

			
		}
		
		
		return generatedCode.toString();
	}
```

Useful links:

https://www.educba.com/types-of-tags-in-html/
		
https://www.tutorialstonight.com/self-closing-tags-in-html.php#:~:text=HTML%20Self%20Closing%20Tag,%2C%20etc.

**Comment by FanJups** [comment]
I reopened the issue because I solved that on my side but there is still a problem related to how Jsoup deals with self closing tag with and without slash.

**Comment by jhy** [comment]
I can't follow this issue. HTML5 does not require a trailing / to make an empty tag. If you think there is an issue in the parser, please provide a simple example on https://try.jsoup.org/ . The examples using generated code make this more complex.

**Comment by FanJups** [comment]
Hi @jhy ,
Thanks for reviewing this issue.
Sorry, I changed the title because it was confusing. 
Yes, HTML5 does not require a trailing / to make an empty tag. 

I was trying to explain the problem we faced with Jsoup API.
**Our goal is not to parse HTML to get a parsed HTML as output  as it is done here https://try.jsoup.org/ but we are using Jsoup to turn HTML elements into Java Objects (  [Node](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Node.java), [Element](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Element.java) and [TextNode](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/TextNode.java) from Jsoup ) then our app turns these Java Objects  into JavaScript variables.**

**While working, we noticed that if there are 2 self closing tags following each other then the 2nd one is considered as the child of the 1st one. To be more precise, we also noticed that when the 1st one has slash at the end then everything is correct but when the 1st one doesn't have slash, we got this issue.** It is impossible to see that here https://try.jsoup.org/ . The only way to see that is to deeply analyze the code to get a better idea on how things work under the hood.

I will provide a better way to reproduce this issue asap
