### ISSUE TITLE
"Did not find balanced marker" error!!!

### ISSUE THREAD

**Issue by simos-sigma** [jhy/jsoup#1745]
I am using jsoup library **1.14.3** in Katalon Studio.

I am trying to get the `href` of an `<a>` element which contains specified text each time.

Example:
```
import org.jsoup.Jsoup
import org.jsoup.nodes.Document
import org.jsoup.select.Elements

public class GlobVars {
	public static Document currentPageSource
	public static String currentTitle
}

def get_url() {
	String url = "https://www.website.com/"
	GlobVars.currentPageSource = Jsoup.connect(url).get()

	Elements wElements = GlobVars.currentPageSource.select('a[class="class-name"]:contains('+GlobVars.currentTitle+')')
	if(wElements) {
		/*
		 * Do stuff...
		 * 
		 * */
	}
}
```
The problem is when `GlobVars.currentTitle` contains single quote character!!! For example, if `GlobVars.currentTitle` is `I am here` it "works" fine. But if `desiredText` is `I'm here` i get this error: `Did not find balanced marker at 'I'`.

I tried to use `GlobVars.currentTitle` variable with `double-quoted`, `triple-single-quoted` or `triple-double-quoted` but I get the same error. 

I also read https://github.com/jhy/jsoup/issues/1105 but the "[trick](https://try.jsoup.org/~tQywDLPdfB0IPT9FFNb5Z7JnjWI)" to escape quotes can not be used in my case.

Any idea how can I fix this?

**Comment by MVP-D77** [comment]
Hello,@simos-sigma,our group are interested in your problem and want to try to fix it
            ——SE, Sustech

**Comment by jhy** [comment]
To escape, use a backslash (`\`). Like as described in #1105.

See e.g.: https://try.jsoup.org/~dzgCt64vvJrcnuw4M4RUtcRuXZw

@MVP-D77 not sure what the value of your comment is.
