### ISSUE TITLE
Question about using `document.selectXpath()` in xhtml

### ISSUE THREAD

**Issue by lethal233** [jhy/jsoup#1746]
Hi, 
When I did some web testing in xhtml page, I met such problem:

```java
import org.jsoup.Jsoup;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.IOException;
import java.util.Scanner;

public class DomTest {
    public static void main(String[] args) throws IOException {
        Document doc1 = Jsoup.connect("https://www.sustech.edu.cn/mail").get();
        Element element1 = doc1.selectXpath("//input").first();
        Element element2 = doc1.select("input").first();
        System.out.println(element1);
        System.out.println(element2);
    }
}
```

output:
```sh
null
<a href="https://www.sustech.edu.cn" target="_blank">官网首页</a>
````

As you can see, the `doc1.selectXpath("//input").first();` returns `null`, which is not an anticipated value, but I did not why. When I did some testings in HTML page, the `selectXpath()` is correct.

```java
        Document doc1 = Jsoup.connect("https://mirrors.sustech.edu.cn").get();
        Element element1 = doc1.selectXpath("//a").first();
        Element element2 = doc1.select("a").first();
        System.out.println(element1);
        System.out.println(element2);
```

```sh
<a href="/" aria-current="page" class="home-link router-link-exact-active router-link-active"><img src="/mirrors-logo.svg" alt="SUSTech Open Source Mirrors" class="logo"> <span class="site-name can-hide">SUSTech Open Source Mirrors</span></a>
<a href="/" aria-current="page" class="home-link router-link-exact-active router-link-active"><img src="/mirrors-logo.svg" alt="SUSTech Open Source Mirrors" class="logo"> <span class="site-name can-hide">SUSTech Open Source Mirrors</span></a>
```

Could you help me explain the reason? Thanks very much.

**Comment by QAQGaeBolg** [comment]
XmlDocument can perform XPath query, but in fact the XPath query mentioned here is limited to XML without namespace (no xmlns attribute). Once XML with namespace is encountered, the corresponding XPath query will have no results. You could use the developer tools to check the HTML elements of the website.

**Comment by lethal233** [comment]
> XmlDocument can perform XPath query, but in fact the XPath query mentioned here is limited to XML without namespace (no xmlns attribute). Once XML with namespace is encountered, the corresponding XPath query will have no results. You could use the developer tools to check the HTML elements of the website.

okay, got it, thanks for your kind response! So now the issue can be closed. ^ ^

**Comment by jhy** [comment]
@QAQGaeBolg that's not correct, the XPath support is namespace aware. Alternatively, you can query using the local-name, e.g. `//*[local-name()="input"]`

https://try.jsoup.org/~1sqtrcyvRfRGSOheaQnxoQbNnYc

**Comment by jhy** [comment]
I simplified this by disabling namespace awareness when using selectXpath. See #1801
