### ISSUE TITLE
the addition imprrove for the selectXpath function

### ISSUE THREAD

**Issue by 11910503** [jhy/jsoup#1756]
in the closed issues "Question about using document.selectXpath() in xhtml #1746" Once XML with namespace is encountered, the corresponding XPath query will have no results. That is not a good thing for packet because it is not a easy thing to know is there XML with namespace in the http file. so my term and I plan to add a judge in it to throw a warning when the this case happen. I think this is important because no one want to get a null without the error message.

**Comment by 11910503** [comment]
[https://github.com/jhy/jsoup/issues/1746#issue-1206391817](url)

**Comment by jhy** [comment]
If this refers to #1757, I closed that as mentioned.
