### ISSUE TITLE
Add attempt

### ISSUE THREAD

**Issue by crysan** [jhy/jsoup#1761]
Hi!
You can add to the call parameters the number of attempts to receive an answer from the server.
**.attemp(3)**
This is necessary in order to make several attempts to receive an answer from the server if it is not equal to Code 200
It will be convenient not to create extra cycles.
```
			Document doc = Jsoup.connect(url)
                                        .attemp(3)
					.get();
```
Forgive my bad English.

**Comment by JeffXiesk** [comment]
Hi, I am going to try to add this function in a week.

**Comment by crysan** [comment]
Good!
Thank you!

**Comment by JeffXiesk** [comment]
Hi, I've added a new method of accepting more attempts.
Just try
```
Document doc = Jsoup.connect(url, 3).get();
```

**Comment by crysan** [comment]
Is in new version Jsoup?

**Comment by JeffXiesk** [comment]
Noop, it'll not be in the new version unless the author merge my pr into master. Maybe you can only check my pr and manipulate the library yourself.

**Comment by crysan** [comment]
I understood you.
Everything is correct in code. I constantly use this in the code.
We will wait for the author’s decision.

**Comment by JeffXiesk** [comment]
Yep! Thx for your appreciation.

**Comment by jhy** [comment]
I don't plan on adding such a simplistic retry function, as it doesn't include exponential backoff or jitter or other commonly required retry mechanisms. Would suggest using something like https://github.com/rholder/guava-retrying
