### ISSUE TITLE
Safelist for parse() and parseBodyFragment()

### ISSUE THREAD

**Issue by rujiel** [jhy/jsoup#1765]
Aside from using safelist with clean, is there any way to send a safelist when parsing the document so that there can be custom elements that are seen as comments but are maintained in the output? 

I understand the parse methods are meant to deal only with valid html, but in practice the only way to preserve a pocket of non-standard HTML and circumvent the behavior of certain < and > characters getting encoded, is to comment them, parse, and then uncomment the output. This approach is fragile, and the resulting code isn't very pretty.

Is there any class that I can override such that I could implement this sort of thing? Thanks

**Comment by jhy** [comment]
You would want to extend the HtmlTreeBuilder and related classes. The Cleaner works after the Parser has created the DOM, so it would be too late by then.
