### ISSUE TITLE
Jsoup moves iframe and following contents from document header to document body 

### ISSUE THREAD

**Issue by saiprashanth24** [jhy/jsoup#1766]
Hi,
 If we try to parse iframe tag present inside document header, jsoup moves the iframe tag and the following tags to document body.
refer the below image.
![image](https://user-images.githubusercontent.com/42546847/167831346-959f206c-c57e-411f-9d53-b2cf7e291cd6.png)

**Comment by krystiangorecki** [comment]
If you don't want Jsoup to fix your HTML use XML parser:
`Document doc = Jsoup.parse(html, "", Parser.xmlParser());`

**Comment by sumanth13131** [comment]
> If you don't want Jsoup to fix your HTML use XML parser: `Document doc = Jsoup.parse(html, "", Parser.xmlParser());`

Yes. Good solution... 

But, considering the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) such as ``` meta, area, base, br, col, embed, hr, img, input, link, source, track, wbr ``` are in  invalid XML schema or format, it constricting to the valid XML on parsing, this changing the whole document structure(i.e, adding closing tags  for void elements show in below figs).

### html 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="description" content="This is Meta 1">
    <meta property="og:description" content="This is Meta 2">
    <meta name="twitter:description" content="This is Meta 3">
    <title>Title</title>
</head>
<body>
    <h1>Hello World</h1>
    <br>
    <h1>Statement-1</h1>
    <h1>Statement-2</h1>
</body>
</html> 
```

### html ( Parser.xmlParser() )
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="description" content="This is Meta 1">
    <meta property="og:description" content="This is Meta 2">
    <meta name="twitter:description" content="This is Meta 3">
    <title>Title</title>
</meta></meta></meta></head>
<body>
    <h1>Hello World</h1>
    <br>
    <h1>Statement-1</h1>
    <h1>Statement-2</h1>
</br></body>
</html> 
```

**Comment by jhy** [comment]
jsoup follows the HTML5 spec which does not allow iframes in the head section.
