### ISSUE TITLE
Request data doesn't clean up after calling newRequest()

### ISSUE THREAD

**Issue by galimru** [jhy/jsoup#1778]
Hey

I have an issue when trying to use the same connection after submitting the form.
The method `newRequest()` makes copy `data` params and it leads that this request preserve data from previous request.
There is no way to clean up `data` params. So when I use the same connection to "navigate link" it serializes data params as query parameters:
```java
document.connection().newRequest()
                    .url(confirmationUrl)
                    .get();
```
And moreover it will keep send data from previous form if you use subsequence of form submit calls.
https://github.com/jhy/jsoup/blob/b0ac5e06a75cfe00ab010291c9df03cbbf8d655d/src/main/java/org/jsoup/nodes/FormElement.java#L72-L75

I believe we shouldn't do a copy of  `data` params here:
https://github.com/jhy/jsoup/blob/b0ac5e06a75cfe00ab010291c9df03cbbf8d655d/src/main/java/org/jsoup/helper/HttpConnection.java#L671

**Comment by jhy** [comment]
Thanks @galimru, I'll take a look. Can you confirm that if you start with `Jsoup.newSession()`, and then hit `session.newRequest()`, your flow works (cookies etc) and you don't get the repeated form data?  

https://jsoup.org/apidocs/org/jsoup/Jsoup.html#newSession()

**Comment by jhy** [comment]
Thanks, fixed!
