### ISSUE TITLE
When the JSOUP encounters the tag  table , the tag  tbody  will be automatically generated.

### ISSUE THREAD

**Issue by LYZ1125** [jhy/jsoup#1781]
When the JSOUP encounters the tag `<table>`, the tag `<tbody>` will be automatically generated. When the JSOUP is used to generate the xpath, the xpath '/table/tbody' is incorrect. Chrome cannot identify the element corresponding to the XPath.
For example:
```
        String html = "<html>" +
                "  <body>" +
                " <table ><tr></tr></table>" +
                "  </body>" +
                "  </html>";
        Document document = Jsoup.parse(html);
        for (Element element : document.getAllElements()){
            System.out.println(element.tagName());
        }
        Elements elements = document.getElementsByTag("table");
        Element element = elements.get(0);
        System.out.println(element.children());
```
Result:
```
#root
html
head
body
table
tbody
tr
<tbody>
 <tr></tr>
</tbody>
```

In the result, we can see that jsoup automatically generates the tbody tag.
In this example, Chrome can only identify xpath '/html/body/table/tr', but cannot identify '/html/body/table/tbody/tr'. This will cause trouble for people who use jsoup to generate xpath.
So can this be solved? Or is there a better way to generate xpath?

**Comment by jhy** [comment]
This is correct per the HTML5 spec: insert a `tbody` element when in a `table` and a `tr` start tag is seen: https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable

Not sure what you mean by using jsoup to generate an xpath? Jsoup will parse an xpath query, but doesn't have generators.

I would suggest that you review an xpath created by Chrome Inspector (? what I guess you're doing) against the jsoup DOM. https://try.jsoup.org/ should help.

**Comment by jhy** [comment]
Also, I went and double checked Chrome's behavior and confirmed that it also generates the `tbody` element. With this input HTML:

```html
<table><tr><td>Hello
```

Chrome creates this tree:
![image](https://user-images.githubusercontent.com/76934/170701738-54f9f934-4e23-4ff3-8a0a-b6f540121e35.png)

And this xpath selector:
```xpath
/html/body/table/tbody/tr/td
```

Which jsoup parses and selects, as you can see here: https://try.jsoup.org/~nxJkxOYo9KPe-VaEReC6yynUA8Q

So everything appears to be operating in harmony, as far as I can see.

**Comment by LYZ1125** [comment]
Thank you very much for your reply. @jhy .I really like the jsoup tool and think it's powerful.
**We want to get the xpathes of all elements of an html, which is important for crawlers.
The usual method is to use jsoup to parse the html and generate the corresponding xpath.**
I found that there are also many jsoup users who want to add this feature.https://github.com/jhy/jsoup/issues/187
I've also tried it a lot and found that chrome automatically adds the <tbody> tag in most cases. For example, open a local HTML file.
**We can reproduce it with the following steps.**

1.Install react and create a project.
`npm install create-react-app -g`
`create-react-app react-demo --use-npm`

2.Modify App.js to the following code.
```
import React from 'react';
import './App.css';
function App() {
  return (
    <table>
      <tr>
        <div>ssss</div>
      </tr>
    </table>
  );
}
export default App;
```

3.Start the service.
`npm start`

4.We can see the following at http://localhost:3000/.
```
<div id="root">
  <table>
    <tr>
      <div>ssss</div>
    </tr>
  </table>
</div>
```
5.As we can see, chrome doesn't add `<tbody>` automatically.

6.We can use `$x('/html/body/div/table/tr')` to find the element in chrome, but we can't use `        System.out.println(document.selectXpath("/html/body/div/table/tr"));
` to find the corresponding element in jsoup.

**I know this really doesn't meet HTML5's specs. But the project can be run, so it is difficult to guarantee whether some pages will have this problem.**
I wonder if the `<tbody>` should be added automatically by chrome instead of jsoup.. Usually we get html from chrome and use jsoup to parse it. 
For example:
`Document doc = Jsoup.parse(driver.getPageSource());`
If jsoup cannot guarantee that the parsed html is consistent with chrome's html, it may generate errors when we use xpath..

**Comment by thangaraj1006** [comment]
Document doc = Jsoup.parse(tableHtml);
String tableReady = doc.select("table").outerHtml();
System.out.println(tableReady);
System.out.println(doc.html());
The both output printing additional as -

` 
...
</tr>
 </tbody>
 <tbody></tbody>
</table> 
`

**Comment by jhy** [comment]
If you don't want HTML5 normalized input, use the XML parser.
