### ISSUE TITLE
Newline whitespace between spans is too aggressively removed in HTML output

### ISSUE THREAD

**Issue by leekowalkowski-hmrc** [jhy/jsoup#1787]
This was correct in 1.14.3, but it has broken in 1.15.1

The HTML 
```
<p>
<span>Words</span>
<span>should</span>
<span>have</span>
<span>spaces</span>
<span>between</span>
<span>them</span>
</p>
```

Would render in a browser as `Words should have spaces between them` as a new-line character would be treated as a space. See fiddle: https://jsfiddle.net/uL4h1x0v/

When this is parsed with `Jsoup.parse()` then output with `doc.toString()` in 1.14.3 we get an equivalent representation that still renders correctly in a browser:
```
<html>
 <head></head>
 <body>
  <p> <span>Words</span> <span>should</span> <span>have</span> <span>spaces</span> <span>between</span> <span>them</span> </p> 
 </body>
</html>
```

…but in 1.15.1 it is incorrect, and renders as `Wordsshouldhavespacesbetweenthem`:
```
<html>
 <head></head>
 <body>
  <p><span>Words</span><span>should</span><span>have</span><span>spaces</span><span>between</span><span>them</span></p>
 </body>
</html>
```

**Comment by jhy** [comment]
Thanks, fixed now - and I cleaned up some other whitespace issues in the same commit
