### ISSUE TITLE
Problem cleaning <iframe> under certain conditions.

### ISSUE THREAD

**Issue by da3x** [jhy/jsoup#1803]
I'm trying to adopt `Jsoup.clean(String, Safelist)` to secure my code. Most things I throw at v1.15.2 work as expected... but not the following:

```
Assertions.assertEquals(Jsoup.clean("<p><iframe src=\"...\">Hallo</p>", Safelist.relaxed()),
                                    "<p>Hallo</p>");
```

It results in the following "strange" output:

```
<p>Hallo&lt;/p&gt;</p>
```

Is this a known bug (couldn't find it) or do I need some magic settings to handle those combinations?

**Comment by jeffthomasweb** [comment]
Thanks for the easy to follow example. I was able to reproduce your result when only the starting `<iframe>` tag is included in the HTML fragment. If both `<iframe>` and `</iframe>` tags are included, I no longer see the `&lt;/p&gt;` characters.

**Comment by jhy** [comment]
I believe this is correct in the sense that the initial data is parsed per the spec. An iframe doesn't contain HTML, it contains RCDATA (text only). So unless it's closed, anything like `</p>` is treated as plain text. 

It's not really something the Cleaner is in a position to change.
