### ISSUE TITLE
Reading in and writing out bookmarks.html exported by major Browsers fails

### ISSUE THREAD

**Issue by eGit** [jhy/jsoup#1805]
Example: Brave browser. Export Bookmarks.

Document document = Jsoup.parse(input);
Files.write(output, document.outerHtml().getBytes());

The written out bookmarks.html breaks when I re-import it in Brave. Especially Folders and all the bookmarks they contain are gone.

I played around with different Parsers and Settings but nothing helped.

**Comment by jhy** [comment]
Can you add a snippet of the original HTML? What is causing the error, is it a parse error, or what?

**Comment by jhy** [comment]
One quick thought - are your character set inputs and outputs correct? Using .getBytes() is going to be platform dependant and may not be the same as what the content was initially saved in. Generally I would suggest specifying the charset on output (in the call to getBytes, or use a Writer).

Would be good if you can add a simple and minimal testcase to verify.

**Comment by jhy** [comment]
(Closing, insufficient detail provided to make progress)
