### ISSUE TITLE
wholeText() 1.15.2 now outputs "\n" instead of "\r\n" for some html code

### ISSUE THREAD

**Issue by vaatje** [jhy/jsoup#1808]
after updating dependency jsoup from 1.13.1 to 1.15.2 I noticed some of our QA tests failing: 
mailText= Jsoup.parse(mailContent).wholeText();
The tests expect in mailText the lines to end with "\r\n" but now some lines ended only with "\n".

The html of mailContent that failed:
```
              <span
                  style="font-family: Helvetica, Arial, sans-serif; font-weight: bold; color: #4A4A4A; font-size: 18px;">Talk: Search for work</span><br>
              <p style="margin:0;font-family: Helvetica, Arial, sans-serif;color:#4A4A4A;font-size:16px;">
                  25 July 2022 - 10:00 - STREET BLABLA 1, 1000 BRUSSELS</p>
      </a>
    </td>
```

With 1.13.1 this resulted in: `Talk: Search for work\r\n\r\n`
Now with 1.15.2 it becomes: `Talk: Search for work\n\r\n`

Please fix this bug so that line breaks are the same everywhere: `"\r\n"`
I could fix our tests to deal with this but the next day, because of this, I had a migraine attack at a wedding and I had to throw up and could not enjoy the meal or speak with my family.

**Comment by jeffthomasweb** [comment]
Hi, thanks for sharing the detailed examples. The method `String wholeText()` does not use normalized text while `String text()` uses normalized text and will likely treat spaces in a more consistent manner. I would suggest using `String text()` rather than `String wholeText()` for more predictable handling of spaces in your document. I've included the source code documentation below for the `String text()` method. https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Element.java#L1284

```
  /**
     Gets the <b>normalized, combined text</b> of this element and all its children. Whitespace is normalized and
     trimmed.
     <p>For example, given HTML {@code <p>Hello  <b>there</b> now! </p>}, {@code p.text()} returns {@code "Hello there
    now!"}
     <p>If you do not want normalized text, use {@link #wholeText()}. If you want just the text of this node (and not
     children), use {@link #ownText()}
     <p>Note that this method returns the textual content that would be presented to a reader. The contents of data
     nodes (such as {@code <script>} tags are not considered text. Use {@link #data()} or {@link #html()} to retrieve
     that content.
     @return unencoded, normalized text, or empty string if none.
     @see #wholeText()
     @see #ownText()
     @see #textNodes()
     */
```

**Comment by jhy** [comment]
> I could fix our tests to deal with this but the next day, because of this, I had a migraine attack at a wedding and I had to throw up and could not enjoy the meal or speak with my family.

Sorry to hear that my guy! I hope you got some rest and are feeling better.

Can you please include a reproducing test case to show us what the specific selector is in use, what element you're hitting `wholeText` on, etc. 

The content in the bug report doesn't include any `\r` characters as far as I can tell when I paste into a text editor, perhaps GitHub normalized them. You can attach a file.

**Comment by jhy** [comment]
(Closing, please re-open if this is still an issue and you can provide the requested data.)
