### ISSUE TITLE
Feature Request: (Try JSoup Online) Add a feature to print out the code in use 

### ISSUE THREAD

**Issue by Aptenodyti** [jhy/jsoup#1812]
Some websites that have tools to try out code online, like for CSS for example, you could find a feature that prints out the code that was used to make the specific CSS so that a user can use it in their own code, like www.htmlcssbuttongenerator.com
I think it would be amazing to have that on the Try JSoup tool.

**Comment by jhy** [comment]
Thanks -- it's a good idea that I've also considered in different ways. I don't currently plan to implement it, but might one of these days.
