### ISSUE TITLE
Change in login handling post v1.31.1

### ISSUE THREAD

**Issue by kirbyhaines** [jhy/jsoup#1813]
Recently I upgraded something I wrote to login to a wordpress site and download some content from jsoup v1.13.1 to v1.15.2. Immediately the logged in session started being rejected by the site.

I gradually rolled back through the versions until logins started working again in v1.13.1, so the change that's causing the issue looks like it was introduced in v1.14.1. I noticed some comments in the v1.14.1 release notes around how sessions and cookies are handled, so I suspect it's something to do with this but not sure.

I've attached a file with my "login" method then a subequent "loadPage" method that uses the cookie collection returned from the login response, and at the end the 2 cookie collections tagged with the jsoup version used to generate them. The post login cookie collection has some significant differences between v1.13.1 and later. You can see the wordpress_sec and wordpress_logged_in cookies are both truncated in the later jsoup version which is what's causing the login issue with the site. What I don't know is why this is happening or what I can do to fix it.

The site in question is an indie Australian newsletter, you can create a trial account with 10minutemail etc if you want to check out what's going on for yourself.

Thanks.
[codesnippets.txt](https://github.com/jhy/jsoup/files/9181405/codesnippets.txt)

**Comment by jeffthomasweb** [comment]
I would suggest using the method CookieStore cookieStore() rather than cookies(). The source code comments note that this is since 1.14.1
https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/Connection.java#L302
 ```
/**
     Get the cookie store used by this Connection.
     @return the cookie store
     @since 1.14.1
     */

    CookieStore cookieStore();
```

**Comment by kirbyhaines** [comment]
Thanks Jeff. That's fixed it. Maybe consider deprecating cookies() in a future release if the recommendation is that it should no longer be used.

**Comment by jeffthomasweb** [comment]
Thanks for the update and it's great to hear that worked!
