### ISSUE TITLE
Parser replaced &nbsp; with a space instead of HTML NBSP

### ISSUE THREAD

**Issue by DriesVanbilloen** [jhy/jsoup#1816]
I upgraded Jsoup from version 1.8.1 to version 1.15.2.

Old behaviour:

&nbsp; is replaced by NBSP

New behaviour:
&nbsp; is replaced by a space.

Is it possible to keep this implementation or is there a settings we can use to keep the old behaviour?

**Comment by jeffthomasweb** [comment]
Hi, I was wondering if you could please provide an example HTML fragment and Jsoup code. I'm trying to reproduce this and the following example leaves `&nbsp;` in the final product when running Jsoup 1.15.2. Thanks!

```
Document keepNbsp() throws IOException {
    String htmlWithNbsp = "<p>Hello. &nbsp; &nbsp; &nbsp; Good Bye</p>";
    Document resultingHtml = Jsoup.parse(htmlWithNbsp); 

    return resultingHtml;
    } 
```

The above code produces the following:
```
<html>
 <head></head>
 <body>
  <p>Hello. &nbsp; &nbsp; &nbsp; Good Bye</p>
 </body>
</html>
```

**Comment by DriesVanbilloen** [comment]
This is the string we are using:
`    private static final String ITEM_1_CONTENT_TEXT_IMAGE = "Sparen kan enkel met een maandelijkse spaaropdracht, vanuit een zichtrekening, bij KBC of bij een andere financiële instelling, met een maximum van 500 euro. Er is slechts één opdracht per rekening KBC-Start2Save mogelijk.";`

**Comment by jeffthomasweb** [comment]
Thanks for the example String. I'm not sure I follow though, would you like `&nbsp;` in the final String? I don't see `&nbsp;` in ITEM_1_CONTENT_TEXT_IMAGE . The code example below keeps `&nbsp;` in the final String.

```
String keepNbsp() throws IOException {
    String htmlWithNbsp = "&lt;p>Sparen kan enkel met een&amp;nbsp;&lt;b>maandelijkse spaaropdracht&lt;/b>, vanuit een zichtrekening, bij KBC of bij een andere financiële instelling, met een maximum van 500 euro. Er is slechts één opdracht per rekening KBC-Start2Save mogelijk.&lt;/p>&#xa;";
    Document resultingHtml = Jsoup.parse(htmlWithNbsp);
    String textOfHtml = resultingHtml.text();
    return textOfHtml;
    }
```
This produces the following String for me:
```
<p>Sparen kan enkel met een&nbsp;<b>maandelijkse spaaropdracht</b>, vanuit een zichtrekening, bij KBC of bij een andere financiële instelling, met een maximum van 500 euro. Er is slechts één opdracht per rekening KBC-Start2Save mogelijk.</p>
```
If you'd like to get something similar to String in ITEM_1_CONTENT_TEXT_IMAGE, you could try using Jsoup to parse the result above. It's not an elegant solution, but it matches the example String.

```
 String TwoParsingJsoup() throws IOException {
    String htmlWithNbsp = "&lt;p>Sparen kan enkel met een&amp;nbsp;&lt;b>maandelijkse spaaropdracht&lt;/b>, vanuit een zichtrekening, bij KBC of bij een andere financiële instelling, met een maximum van 500 euro. Er is slechts één opdracht per rekening KBC-Start2Save mogelijk.&lt;/p>&#xa;";
    Document resultingHtml = Jsoup.parse(htmlWithNbsp);
    String textOfHtml = resultingHtml.text();
    Document secondParseOfText = Jsoup.parse(textOfHtml);
    String textOfSecondParse = secondParseOfText.text();
    return textOfSecondParse;
    }

**Comment by jhy** [comment]
@DriesVanbilloen, your report would be a lot simpler for folks to understand if you provided sample code and expected output. As it is, we have to guess as to what methods you are using.

As @jeffthomasweb points out (thanks for digging into this), the document is parsed with `&nbsp;` escapes, and those are preserved in the document.

In the `Element.text()` methods, whitespaces are normalized, and so NBSPs are changed to plain spaces. If you want to get the text as in the original document (not-normalized), you can use the [`Element.wholeText()`](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#wholeText()) methods.

For e.g.:

```java
        String html = "Test&nbsp;test";
        Document doc = Jsoup.parse(html);
        String normalized = doc.body().text();
        String wholeText = doc.body().wholeText();

        System.out.println(normalized);
        System.out.println(wholeText);
```

Outputs: 
<img width="166" alt="Screen Shot 2022-08-07 at 4 07 47 pm" src="https://user-images.githubusercontent.com/76934/183277880-43db92e2-75e4-4bbf-8e7d-5cc1a18be470.png">

([0xa0](https://unicodelookup.com/#0xa0/1) is the non-breaking space character as encoded by `&nbsp`.

**Comment by DriesVanbilloen** [comment]
@jeffthomasweb Yeah, I noticed now that the starting String I send came from the repository Which also xml encodes it :) 
But I tried the solution @jhy stated with the `wholeText()` method which solved the issue with some minor changes to the code
