### ISSUE TITLE
Bug: org.jsoup.integration.TestServer won't stop itself

### ISSUE THREAD

**Issue by FXTi** [jhy/jsoup#1822]
```java
    public static void stop() {
        synchronized (jetty) {
            int count = latch.getAndDecrement();
            if (count == 0) {
                try {
                    jetty.stop();
                } catch (Exception e) {
                    throw new IllegalStateException(e);
                }
            }
        }
    }
```

`int count = latch.getAndDecrement();` will get previous value of `latch`.
The condition should be `--count == 0`.

**Comment by jhy** [comment]
Thanks, well spotted! The method call should be `decrementAndGet`. But, it is actually better for the test cases to keep the same server running throughout the suite (which is how it operates with that off-by-one count now). I changed it to remove the calls to `stop()` entirely and just use the lifecycle of the test suite to manage its shutdown.
