### ISSUE TITLE
Why the Safelist does not support [data:] type of image ?

### ISSUE THREAD

**Issue by MoonLord-LM** [jhy/jsoup#1828]
such as:

```
<img src="data:image/png;base64,XXXXXXXXXX"></img>
```

code:

https://github.com/jhy/jsoup/blob/8b5d2ad19272b8b8265220ff0669518e9eb80734/src/main/java/org/jsoup/safety/Safelist.java#L138

Is there any xss example for this case ?

**Comment by jeffthomasweb** [comment]
Hi, from what I can tell, `Safelist.basicWithImages()` supports your example HTML. 

```java

Document imgDataParse() throws IOException {
        Safelist listOfSafeHtml = Safelist.basicWithImages();
        String htmlImgData = "<img src='data:image/png;base64,XXXXXXXXXX'></img>";
        Document doc = Jsoup.parse(htmlImgData);

        return doc;
    }
```
The code above produces the following HTML for me.
```html
<html>
 <head></head>
 <body>
  <img src="data:image/png;base64,XXXXXXXXXX">
 </body>
</html>
```
If this is not what you're expecting, could you please provide a code snippet and the resulting HTML/text you're expecting? Thanks!
