### ISSUE TITLE
Simple cookie parser keeps first cookie with same name, not most recently set

### ISSUE THREAD

**Issue by lvpiao** [jhy/jsoup#1831]
![image](https://user-images.githubusercontent.com/31591566/187493891-29e07b61-195c-4a27-bfa0-d8bf96aeef5d.png)

**Comment by jeffthomasweb** [comment]
Hi, to help others duplicate this issue, can you please include a code sample and the error you receive? Thanks!

**Comment by jhy** [comment]
Thanks, fixed. I simplified the implementation to have the simple cookie map populated by the set result of the Cookie Store, which corrects for order, path, etc.

**Comment by anonyein** [comment]
All this fix make lots of trouble! "set-cookie" will be none sence by this fix and many "set-cookie"s are ignored after this fix. Maybe you test more cases to check whether it is fine!

**Comment by jhy** [comment]
@anonyein 

> This fix makes lots of trouble! "set-cookie" will be none sence by this fix and many "set-cookie"s are ignored after this fix. You must test more cases to check whether it is fine!

Yeah... I rolled it back in 8dec9c302e2f2d2b5560fefa0d3ed7e1b813e195 and we just keep the last set one.
