### ISSUE TITLE
cookies from successful login passed on to child page is not working

### ISSUE THREAD

**Issue by vikramvi** [jhy/jsoup#1833]
Steps:
1. Login to `https://www.valueresearchonline.com/login` and get cookies ( Result : Working )
2. Use cookies from above step to login `https://www.valueresearchonline.com/funds/26123/motilal-oswal-flexi-cap-fund-regular-plan/#fund-portfolio` ( Result : Not Working )

pom.xml

```
         <dependency>
              <groupId>org.jsoup</groupId>
              <artifactId>jsoup</artifactId>
               <version>1.15.3</version>
          </dependency>
```

STEP 1:  Working

```
        Connection.Response initial = Jsoup.connect("https://www.valueresearchonline.com/login")
                .timeout(15000)
                .userAgent("Mozilla")
                .method(Connection.Method.GET)
                .execute();
```

STEP 2:  Working

```
Connection.Response login = Jsoup.connect("https://www.valueresearchonline.com/login")
                .timeout(15000)
                .userAgent("Mozilla")
                .data("username", "valid_email")
                .data("password", "valid_password")
                .cookies(initial.cookies())
                .method(Connection.Method.POST)
                .execute();
```

STEP 3:  NOT Working

```
        doc = Jsoup.connect("https://www.valueresearchonline.com/funds/26123/motilal-oswal-flexi-cap-fund-regular-plan/#fund-portfolio")
                .timeout(15000)
                .userAgent("Mozilla")
                .cookies(login.cookies())
                .get();
```

**Comment by vikramvi** [comment]
@jhy can you please have a look at above issue and clarify

**Comment by jeffthomasweb** [comment]
Hi, I haven't use Jsoup for anything related to cookies but you may want to try Connection cookieStore(CookieStore cookieStore) or CookieStore cookieStore() to store the cookie information https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/Connection.java#L290 .

```java
/**
     Provide a custom or pre-filled CookieStore to be used on requests made by this Connection.
     @param cookieStore a cookie store to use for subsequent requests
     @return this Connection, for chaining
     @since 1.14.1
     */
    Connection cookieStore(CookieStore cookieStore);

    /**
     Get the cookie store used by this Connection.
     @return the cookie store
     @since 1.14.1
     */
    CookieStore cookieStore();
```

**Comment by vikramvi** [comment]
@jeffthomasweb sorry I didn't fully understand your last comment, 
where shall I store the cookies, 
what purpose will it serve by storing cookies, 
which once to store,
how will it make different against using stored cookies vs current way of using cookies ?

Currently I'm getting 2 cookies namely

1. initial.cookies()
2. login.cookies()

**Comment by jeffthomasweb** [comment]
Apologies, my knowledge of cookies is incomplete. From my limited understanding, one could use `Connection cookieStore(CookieStore cookieStore)` or `CookieStore cookieStore()` to write custom implementations for more advanced cookie handling. As to how to accomplish this, I unfortunately don't know. Sorry.

**Comment by jhy** [comment]
@vikramvi I do not have an account on that site, so have not verified this directly. However, my guess would be that the cookies returned from the login POST are not simple key/val type cookies, but use the cookie path or other attribute to filter which are sent to the required article URL.

The `cookies()` getter and setter are simple `Map<String, String>` interfaces and return the cookies that were set on the response (flattened to only one cookie, if multiple were set with the same name).

As @jeffthomasweb mentioned, the CookieStore in the Connection is the right way to support general cookies which may include paths etc. If you use a session, either explicitly or by calling `newRequest` on a connection, the CookieStore is automatically managed. You don't need to manually copy the cookies onto the next request, and only the appropriate ones will be sent in the request.

So, I expect that this should work:

```java
Connection session = Jsoup.newSession();
Connection.Response initial = session.newRequest().url("https://www.valueresearchonline.com/login")
    .timeout(15000)
    .userAgent("Mozilla")
    .method(Connection.Method.GET)
    .execute();

Connection.Response login = session.newRequest().url("https://www.valueresearchonline.com/login")
    .timeout(15000)
    .userAgent("Mozilla")
    .data("username", "valid_email")
    .data("password", "valid_password")
    .method(Connection.Method.POST)
    .execute();

Document doc = session.newRequest().url("https://www.valueresearchonline.com/funds/26123/motilal-oswal-flexi-cap-fund-regular-plan/#fund-portfolio")
    .timeout(15000)
    .userAgent("Mozilla")
    .get();
```

Can you please test and confirm?

**Comment by jeffthomasweb** [comment]
Thanks for sharing this example @jhy . I was able to customize your sample code to login and access my personalized member data from https://www.metafilter.com. This is an impressive feature!

**Comment by jhy** [comment]
That's great to hear, thanks @jeffthomasweb

**Comment by jhy** [comment]
(Closing, assuming this resolves for @vikramvi as well - please LMK if otherwise.)
