### ISSUE TITLE
Backspace character converted to hex code when Jsoup.parse("\b")

### ISSUE THREAD

**Issue by aditsanputra** [jhy/jsoup#1845]
I'm currently trying to upgrade the jsoup from `1.12.1` to `1.15.3`.
There is a different for the return value between both version and it's currently make one of my unit test failed when I tried to execute the following code:

`1.12.1` version:
```
Document document = Jsoup.parse("<b>\b<b>");
Document.OutputSettings settings = new Document.OutputSettings().prettyPrint(true);
document.outputSettings(settings);
String s = document.html().replaceAll("\\\\n", "\n");
String text = Jsoup.clean(s, "", Whitelist.none(), settings);
```

The `document` will have this value:
```
<html>
 <head></head>
 <body>
  <b></b>
 </body>
</html>
```
and the `text` will be an empty string = ""

While in `1.15.3` version:
```
Document document = Jsoup.parse("<b>\b<b>");
Document.OutputSettings settings = new Document.OutputSettings().prettyPrint(true);
document.outputSettings(settings);
String s = document.html().replaceAll("\\\\n", "\n");
String text = Jsoup.clean(s, "", Safelist.none(), settings);
```
The `document` will have this value:
```
<html>
 <head></head>
 <body>
  <b>&#x8;</b>
 </body>
</html>
```
and the `text` will be a hex code of \b = "\&#x8;"

It seems like the `jsoup.parse()` is converting the \b to \&#x8; in  `1.15.3` version.
Do you think this is a bug?

**Comment by jhy** [comment]
The parse didn't change - it's the same parsed DOM. The serialization changed so that control characters are escaped. Change is 2a4c9decd617e7892fe767a535803b68d2268dca
