### ISSUE TITLE
<del> and <ins> seem to be inline tags

### ISSUE THREAD

**Issue by achifal** [jhy/jsoup#1850]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements `<del>` and `<ins>` are inline tags.

They also look like inline. For example, take a look at
```
<!DOCTYPE html>
<html>
<body>
    <p>My favorite color is <del>blue</del> <ins>red</ins></p>
</body>
</html>
```
Is there any reason they are treated as blocks?

**Comment by jhy** [comment]
As far as I can tell from the HTML5 spec, `ins` and `del` aren't explicitly defined tags, and so therefore are treated as "[ordinary](https://html.spec.whatwg.org/multipage/parsing.html#ordinary)" elements -- noted in "[Any other start tag](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody:ordinary)".

In jsoup, we [define](https://github.com/jhy/jsoup/blob/4b46397a3c6f18f88cac76c6e983e2aa6cbef230/src/main/java/org/jsoup/parser/Tag.java#L256-L259) them as block but format as inline. Really that is just a subtle impact on pretty-printing - if used inline, will format as such, but still OK to wrap a block as well.

Are you experiencing a particular problem with this?

**Comment by jhy** [comment]
Found the spec for it; I was looking in the wrong spot: https://html.spec.whatwg.org/multipage/edits.html#the-del-element

It's content model is Transparent, which jsoup loosely models as block & format as inline. But those aren't very tightly specified in jsoup, as we don't use them for anything else really, other than deciding how to pretty-print.

**Comment by jhy** [comment]
I didn't hear back, so will close; please reopen if you are experiencing a particular problem with this.

**Comment by FooIbar** [comment]
I did encounter a problem might related to this.
A `\n` will be added before `del` in the parse result, which leads to 
`te<del>x</del>st` parse-> `te\n<del>x</del>st` render -> <code>te <del>x</del>st</code>

**Comment by jhy** [comment]
I have revisited this in #2493 - moved `del` and `ins` to inline; as part of a wider revision of the TagSet and Tag definitions.
