### ISSUE TITLE
Space inserted around custom elements when pretty-printing

### ISSUE THREAD

**Issue by jochenberger** [jhy/jsoup#1852]
For the following input
```html
<foo>
  <bar />
</foo>
```
the following output is generated

```html
<html>
 <head></head>
 <body>
  <foo>
   <bar /> 
  </foo>
 </body>
</html>
```

For some reason, there is a space after the `<bar />` element.
This space is *not* added if I omit the newline after the `<bar />` in the input or if I use regular HTML elements like `div`.

Here's a repro as a Groovy script:

```groovy
@Grab('org.jsoup:jsoup:1.15.3')
import org.jsoup.Jsoup

def input = '''\
                <foo>
                  <bar/>
                </foo>'''.stripIndent()

assert Jsoup.parse(input).toString() == '''\
                <html>
                 <head></head>
                 <body>
                  <foo>
                   <bar />
                  </foo>
                 </body>
                </html>'''.stripIndent()
```

**Comment by jochenberger** [comment]
If I add more than one `bar` element, only the *last* one gets an additional space appended.

**Comment by jhy** [comment]
Thanks. Looked to be only if a self-closed element with a following newline is inside a custom element. 

Fixed!
