### ISSUE TITLE
Hamza

### ISSUE THREAD

**Issue by Sadiq512** [jhy/jsoup#1854]
Document doc = Jsoup.connect("https://en.wikipedia.org/").get();
log(doc.title());
Elements newsHeadlines = doc.select("#mp-itn b a");
for (Element headline : newsHeadlines) {
  log("%s\n\t%s", 
    headline.attr("title"), headline.absUrl("href"));
}

Open source
jsoup is an open source project distributed under the liberal [MIT license](https://jsoup.org/license). The source code is available at [GitHub](https://github.com/jhy/jsoup/).

Getting started
[Download](https://jsoup.org/download) the jsoup jar (version [1.15.3](https://jsoup.org/news/release-1.15.3))
Read the cookbook [introduction](https://jsoup.org/cookbook/introduction/)
Enjoy!
Development and support
If you have any questions on how to use jsoup, or have ideas for future development, please get in touch via one of the [discussion methods](https://jsoup.org/discussion).

If you find any issues, please [file a bug](https://jsoup.org/bugs) after checking for duplicates.

The [colophon](https://jsoup.org/colophon) talks about the history of and tools used to build jsoup.

Development of jsoup happens on [GitHub](https://github.com/jhy/jsoup/). There you can see the latest [changes](https://github.com/jhy/jsoup/blob/master/CHANGES), and get the source to [build an unreleased version](https://jsoup.org/download).

Status
jsoup is in general release.

[Cookbook contents](https://jsoup.org/cookbook/)
Introduction
[Parsing and traversing a Document](https://jsoup.org/cookbook/introduction/parsing-a-document)
Input
[Parse a document from a String](https://jsoup.org/cookbook/input/parse-document-from-string)
[Parsing a body fragment](https://jsoup.org/cookbook/input/parse-body-fragment)
[Load a Document from a URL](https://jsoup.org/cookbook/input/load-document-from-url)
[Load a Document from a File](https://jsoup.org/cookbook/input/load-document-from-file)
Extracting data
[Use DOM methods to navigate a document](https://jsoup.org/cookbook/extracting-data/dom-navigation)
[Use selector-syntax to find elements](https://jsoup.org/cookbook/extracting-data/selector-syntax)
[Extract attributes, text, and HTML from elements](https://jsoup.org/cookbook/extracting-data/attributes-text-html)
[Working with URLs](https://jsoup.org/cookbook/extracting-data/working-with-urls)
[Example program: list links](https://jsoup.org/cookbook/extracting-data/example-list-links)
Modifying data
[Set attribute values](https://jsoup.org/cookbook/modifying-data/set-attributes)
[Set the HTML of an element](https://jsoup.org/cookbook/modifying-data/set-html)
[Setting the text content of elements](https://jsoup.org/cookbook/modifying-data/set-text)
Cleaning HTML
[Sanitize untrusted HTML (to prevent XSS)](https://jsoup.org/cookbook/cleaning-html/safelist-sanitizer)

**Comment by jeffthomasweb** [comment]
Hi, I vote to close this issue. This is a nonsense issue, likely from a bot.
