### ISSUE TITLE
Does element.selectXpath() always take from root?

### ISSUE THREAD

**Issue by zaurkadiev** [jhy/jsoup#1856]
org.jsoup:jsoup:1.15.3 

Seems like `element.selectXpath("xpath")` and `element.getRoot().selectXpath("xpath")` have equal result no matter of embedding of `element` in a document. 

`element.select("selector")` takes from element itself and `element.selectXpath("xpath")` takes from root. So similar methods have a different behaviour.

Is it an expected behaviour or a bug?

**Comment by jhy** [comment]
Can you provide a fuller example? The element is used as the context node of the query, and so the query will be relative to the element. 

See the tests at
https://github.com/jhy/jsoup/blob/be24647192f7870da500fb83650bacafed81151f/src/test/java/org/jsoup/select/XpathTest.java#L38

**Comment by zaurkadiev** [comment]
Example:

![save](https://user-images.githubusercontent.com/1666740/214898824-ae441306-80f2-4137-ab94-44e52d5a6dbb.png)

Let's assume we have same elements `div1`, `div2`, `div3` with a similar inner tag structure.

If I have element `div2` and try `element.selectXpath(path)`, I have the result from `div1`. Similar with the element `div3`. If I have the element `div3` and call `element.selectXpath(path)` I have the result from `div1`.

By the way `element.select(selector)` works just as expected, `div1` selects only inside `div1` scope, `div1` inside `div1` scope, etc.


Seems like this is an issue:

Inside mentioned test case.
[https://github.com/jhy/jsoup/blob/be24647192f7870da500fb83650bacafed81151f/src/test/java/org/jsoup/select/XpathTest.java#L38](url)

`assertEquals(1, div.selectXpath("//body").size()); // the whole document is visible on the div context`
