### ISSUE TITLE
Bug: Use text() can not get text  content

### ISSUE THREAD

**Issue by MaLuxray** [jhy/jsoup#1857]
in my java code
``` java
   final String content = "<a>Spider Man</a>";
   Document document = Jsoup.parse(content);

   Elements elements = document.selectXpath("//a/text()");
   System.out.println(elements.outerHtml());
   System.out.println(elements.html());
```

then print empty

**Comment by jeffthomasweb** [comment]
Hi, I'm not familiar how selectXpath was used in previous versions of Jsoup, but to see how it's currently used, I looked at Jsoup's tests. One way to use selectXpath can be found here: https://github.com/jhy/jsoup/blob/2b573de884aad36f3f6be3dc46e51ee06b7269f1/src/test/java/org/jsoup/select/XpathTest.java#L27-L36

So using your example:
```Java
@Test void xpathTesting() {
        String testString = "<a href='https://spiderman.com'>Spider Man</a>";
        Document doc = Jsoup.parse(testString);
        Elements testElements = doc.selectXpath("//a");
        assertEquals(testElements.get(0).text(), "Spider Man");
    }
```
An alternative method can be found here: https://github.com/jhy/jsoup/blob/2b573de884aad36f3f6be3dc46e51ee06b7269f1/src/test/java/org/jsoup/select/XpathTest.java#L122-L129 The above uses two arguments in the selectXpath method and uses `text()` in the xpath String. The source code for selectXpath can be found here https://github.com/jhy/jsoup/blob/eabfcdd25d3d1604baaa78d585ea671540a45adf/src/main/java/org/jsoup/nodes/Element.java#L548.

**Comment by jhy** [comment]
Yes -- `selectXpath(xpath)` returns Elements (per the API). Not text nodes. You can use the `selectXpath(xpath, nodeClassFilter)` method instead.

See
https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#selectXpath(java.lang.String,java.lang.Class) and 
https://github.com/jhy/jsoup/blob/be24647192f7870da500fb83650bacafed81151f/src/test/java/org/jsoup/select/XpathTest.java#L122
