### ISSUE TITLE
Missing newlines. Behavior change from 1.15.1 -> 1.15.2

### ISSUE THREAD

**Issue by sbailliez** [jhy/jsoup#1858]
Looks like there is a behavior change from 1.15.1 to 1.15.2+.

The following code fails on 1.15.2 because it is missing the newlines

```java
    public static String sampleClean(String input) {
        String inputWithoutXmlEntities = cleanXmlEntities(value);
        String escaped = Jsoup.clean(
                input,
                "",
                Safelist.none().addTags("br"),
                new Document.OutputSettings().escapeMode(Entities.EscapeMode.xhtml));
        return Entities.unescape(escaped);
    }

    @Test
    public void sampleTest() {
        String input = "This is <a href=''>html</a> with<br>line<br>breaks";
        Assertions.assertEquals("This is html with\n<br>line\n<br>breaks", sampleClean(input));
    }
```

**Comment by jhy** [comment]
Thanks, implemented. I changed it so that the format is: `Text<br>\nText` (newline follows the tag, vs precedes) to look a bit more logical.

**Comment by dsw2127** [comment]
If the string after cleaning ends with `<br>`, no newline is added at all, following or preceding. Is this expected?

`<div>Hi this is an <b>important</b> message.<br class='myStyle'/></div>` would formerly become `Hi this is an <b>important</b> message.\n<br>`, now it is just `Hi this is an <b>important</b> message.<br>` no newlines.
