### ISSUE TITLE
1.15.3 version  document.selectXpath() method frequently return null 

### ISSUE THREAD

**Issue by lzzchuzw** [jhy/jsoup#1859]
When use 1.14.3 version ,it works stability with selectXpath() method, but the new version(1.15.3),  it frequently parse wrong~

**Comment by jeffthomasweb** [comment]
Hi, I'm not familiar how selectXpath() was used in previous versions of Jsoup, but please see my comment related to a similar issue https://github.com/jhy/jsoup/issues/1857#issuecomment-1344859285.
