### ISSUE TITLE
Veracode static scan vulnerability - CWE 331 Insufficient Entropy

### ISSUE THREAD

**Issue by niraj-100** [jhy/jsoup#1862]
We are using jsoup 1.15.3 in our application. Our code is getting scanned through veracode security scan. It catches medium issues in jsoup 1.15.3 jar. Below are the details. Please let us know the the plan to fix this.

**CWE 331 Insufficient Entropy**
**Flaw Category:** Cryptographic Issues
**Description**: Standard random number generators do not provide a sufficient
amount of entropy when used for security purposes. Attackers can brute
force the output of pseudorandom number generators such as rand().

**Comment by krystiangorecki** [comment]
> do not provide a sufficient amount of entropy **when used for security purposes**

But it's not used for security purposes. 
Duplicate of https://github.com/jhy/jsoup/issues/994
