### ISSUE TITLE
Best way to minimize a html document with given condition

### ISSUE THREAD

**Issue by Richie94** [jhy/jsoup#1865]
Hey, 
I just tried to accomplish following task:
I have an html document, and I want to cut it so, that I split after a given amount of visible text. So e.g. I only want to have the html containing the first 1024 Chars.
At first I tried using the filter Method on the Elements, but its not filtering as I expected it to do. I though it will at the end only keep the elements in the traversal, which are not removed by the FilterResult.REMOVE.

My current kotlin code looks like this:

```
val allowedChars = 1024
var currentChars = 0
val allElements = htmlPage.body().allElements

val filteredElems = allElements.filter { node, i ->
    if (currentChars > allowedChars) {
        FilterResult.REMOVE
    } else if (node is TextNode) {
        currentChars += node.text().length
        FilterResult.CONTINUE
    } else {
        FilterResult.CONTINUE
    }
}
```

Is my task with yout library and the given options easily possible? Or does the filtering not work as I hoped to work like in this case?
Im using current version 1.15.3.

EDIT: I found out, that if I keep the last element which returned CONTINUE and then going all parents upwards, I get the minimized version. But somehow its not returned in the right way from the filter Method.

**Comment by jeffthomasweb** [comment]
Hi, personally I would use something simpler built into the Java/Kotlin language rather one of the more complicated methods in Jsoup. Java offers `substring(int beginIndex, int endIndex)` https://docs.oracle.com/javase/7/docs/api/java/lang/String.html and it looks like Kotlin has substring as well https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/substring.html. Set the end index to 1024. Here's a very basic example below.

```Java
String partOfHtmlString() throws IOException {
    String sampleString = "<body>Hello, testing this today. Trying to cut this string down. Thank you very much.</body>";
    Document doc = Jsoup.parse(sampleString);
    String docToString = doc.outerHtml();
    //Set substring(beginIndex, endIndex) to your desired values
    String docCut = docToString.substring(0,50);
    
    return docCut;
    }
```

**Comment by Richie94** [comment]
Well, I still need the html structure, not only the text because I want to keep the styling. What I didn't tell you is that here im minimizing ePub files.

**Comment by jhy** [comment]
This works OK for me and the filter method works as I expect it:

```java
int maxChars = 512;
String text = "All work and no play makes Jack a dull boy.";
Document doc = Document.createShell("");
Element body = doc.body();
for (int i = 0; i <= maxChars / text.length() * 2; i++) {
    body.append("<p>" + text);
}
System.out.println("Initial length: " + body.text().length());

AtomicInteger countChars = new AtomicInteger();
body.filter((node, depth) -> {
        if (countChars.get() > maxChars) {
            return NodeFilter.FilterResult.REMOVE;
        } else if (node instanceof TextNode) {
            countChars.addAndGet(((TextNode) node).text().length());
        }
        return NodeFilter.FilterResult.CONTINUE;
    }
);

System.out.println("Updated length: " + body.text().length());
System.out.println(doc);
```

Produces:
```text
Initial length: 1011
Updated length: 527
<html>
 <head></head>
 <body>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
  <p>All work and no play makes Jack a dull boy.</p>
 </body>
</html>
```

(Also, it works both with `body.filter()` (on a single element, the filter will descend) and `getAllElements().filter` (which has a little more overhead).

Are you still having issues? Perhaps you can provide a code test so we can see the full details and what's not matching your expectation.

**Comment by Richie94** [comment]
okay, probably this was because I used the filter on ```htmlPage.body().allElements```, with your solution it works as expected.
