### ISSUE TITLE
IndexOutOfBoundsException for embedded PHP in HTML parsed using XML parser

### ISSUE THREAD

**Issue by richardmorleysmith** [jhy/jsoup#1866]
Hi there,

We've been using an XML parser to parse HTML, since we don't want the HTML to be fixed-up during the process. This has been working great, except when there's embedded PHP in the HTML document. It appears to be treated as an XML declaration and parsed as an Element, so as to extract attributes.

This throws an Index 0 out of bounds for length 0.

Here is some HTML that would reproduce the issue:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PHP Test</title>
</head>
<body>
    <p>
        <a href="mailto:not@areal.email">
            <? Html::encode($email); ?>
        </a>
    </p>
</body>
</html>

```

If you try and parse it using the Parser.xmlParser(), it will throw an IndexOutOfBoundsException.

The issue is in org.jsoup.parser.XmlTreeBuilder#insert(org.jsoup.parser.Token.Comment):
```
    void insert(Token.Comment commentToken) {
        Comment comment = new Comment(commentToken.getData());
        Node insert = comment;
        if (commentToken.bogus) { // xml declarations are emitted as bogus comments (which is right for html, but not xml)
            // so we do a bit of a hack and parse the data as an element to pull the attributes out
            String data = comment.getData();
            if (data.length() > 1 && (data.startsWith("!") || data.startsWith("?"))) {
                Document doc = Jsoup.parse("<" + data.substring(1, data.length() -1) + ">", baseUri, Parser.xmlParser());
                if (doc.childNodeSize() > 0) {
                    Element el = doc.child(0);
                    insert = new XmlDeclaration(settings.normalizeTag(el.tagName()), data.startsWith("!"));
                    insert.attributes().addAll(el.attributes());
                } // else, we couldn't parse it as a decl, so leave as a comment
            }
        }
        insertNode(insert);
    }
```

Parsing the PHP as a "doc" and trying to call doc.child(0) is what throws the exception.

**Comment by jeffthomasweb** [comment]
Hi, could you provide the String you're expecting? The following code produces `Html::encode($email);`. I removed the `<?` and `?>` before running `Jsoup.parse`, then ran `selectXpath`.

```Java
@Test
    void phpCode() {
        String sampleString = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PHP Test</title>
</head>
<body>
    <p>
        <a href="mailto:not@areal.email">
            <? Html::encode($email); ?>
        </a>
    </p>
</body>
</html>""";
        String replaceLeftAngleQuestionMark = sampleString.replace("<?","");
        String replaceRightAngleQuestionMark = replaceLeftAngleQuestionMark.replace("?>","");
        Document doc = Jsoup.parse(replaceRightAngleQuestionMark, Parser.xmlParser());
        Elements testElements = doc.selectXpath("//a");
        assertEquals(testElements.get(0).text(), "Html::encode($email);");
    }
```

**Comment by richardmorleysmith** [comment]
Hi Jeff,

What I'd really be hoping for here is that the HTML I provided would parse without an exception, without needing to do fix-ups to remove the PHP code or tags.

Therefore if PHP code is encountered while parsing, I'd actually expect it to ignored.

A simple suggestion would be to change the if condition in:
```
if (doc.childNodeSize() > 0) {
    Element el = doc.child(0);
    insert = new XmlDeclaration(settings.normalizeTag(el.tagName()), data.startsWith("!"));
    insert.attributes().addAll(el.attributes());
}
```
to
```
if (!doc.children().isEmpty()) {
    Element el = doc.child(0);
    insert = new XmlDeclaration(settings.normalizeTag(el.tagName()), data.startsWith("!"));
    insert.attributes().addAll(el.attributes());
}
```
which would mean if there is no Element (i.e it's not an XML declaration like we'd thought), then we'd ignore the PHP as a comment.

**Comment by richardmorleysmith** [comment]
It's been brought to my attention that the examples I've given actually have invalid PHP in them, and if they were valid then we wouldn't be getting an exception.

Which means that I've made a mistake and I'll close the issue. Sorry!

**Comment by richardmorleysmith** [comment]
Although the issue has been closed. It would be great to get some feedback

**Comment by jhy** [comment]
What version of jsoup are you using? It works OK for me using 1.15.3. Can you show a reproducing testcase?

```java
String body = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>PHP Test</title>
    </head>
    <body>
        <p>
            <a href="mailto:not@areal.email">
                <? Html::encode($email); ?>
            </a>
        </p>
    </body>
    </html>
                
    """;

Document doc = Jsoup.parse(body, Parser.xmlParser());
System.out.println(doc);
```

Produces (which matches my expectation): 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PHP Test</title>
</meta></head>
<body>
    <p>
        <a href="mailto:not@areal.email">
            <!--? Html::encode($email); ?-->
        </a>
    </p>
</body>
</html>
```

**Comment by richardmorleysmith** [comment]
Hi @jhy,

You're absolutely right, this appears to be fixed by updating to the latest version.

Apologies for the mix up - I should've tried updating before raising an issue.

I'll close this. Thanks for your help!
