### ISSUE TITLE
is jsoup dead or abandoned?

### ISSUE THREAD

**Issue by garretwilson** [jhy/jsoup#1868]
It's been over three months that I found a pretty serious bug #1837, and even spent a lot of time fixing it and filing a pull request, but nobody has bothered even to respond. Has the owner of jsoup abandoned the project?

**Comment by jeffthomasweb** [comment]
Hi, I’m simply a Jsoup user but there have been 3 releases in 2022, a number of improvements, and the usual bug fixes https://github.com/jhy/jsoup/blob/master/CHANGES. The last release was in August https://github.com/jhy/jsoup/blob/master/CHANGES.

**Comment by jhy** [comment]
Hi, no -- I've just been working on other things. Thanks for checking!
