### ISSUE TITLE
Add Element.xpath()

### ISSUE THREAD

**Issue by OglieOglie** [jhy/jsoup#187]
Add `Element.xpath()` method that would return the xpath from the root of the document to the given element.

Alternatively, this could be done by implementing
`parentElement.xpath(childElement)` that would return the xpath from this parent to the given child.

This is related to issue #50 (add xpath support), but it's a much smaller implementation.

**Comment by GitManager** [comment]
+1111 for xpath support.

**Comment by hamid-rocket** [comment]
+1 for xpath support

**Comment by mauriciol-cit** [comment]
+1 for xpath support

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by zilti** [comment]
That would *still* be a great feature to have.
