### ISSUE TITLE
Strange escaping of ampersand followed by LT

### ISSUE THREAD

**Issue by cgendreau** [jhy/jsoup#1888]
Maybe I missed something but I was surprised by the following result when cleaning some html.

Considering:
```
 String html = "<p>John&LT Dow</p>";
```

`Jsoup.clean(html, Safelist.basic())` will produce `<p>John&lt; Dow</p>`.

I was expecting `<p>John&amp;LT Dow</p>`.

Is there a reason why `&LT` is interpreted as an incomplete `&lt;` as opposed to `&` followed by the letters `LT` ?

**Comment by jhy** [comment]
Yes, that's the expected outcome, as per the HTML5 spec. For named entities not within an attribute, the trailing `;` is optional. See https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state

You can check in a browser, you'll get the same result.

It does get emitted as an error (see this [example](https://try.jsoup.org/~DxmXEqi_-fR9Cee0RQle76VUb-Y)), so you could conceivably handle it differently if you wanted to.
