### ISSUE TITLE
How to parse in-line styles?

### ISSUE THREAD

**Issue by ionutg09** [jhy/jsoup#1890]
Hello,

How can I parse in-line styles?

For example, I have this HTML code:

```
<p>
      <span style="color: #236fa1;">Testing some styling</span>
      <span style="color: #b96ad9;"> with jsoup </span>
</p>
```

I am using wholeText() function to convert this HTML to a string, but the result is this one:
`
 Testing some styling with jsoup`

Is it possible to preserve the CSS styling?

**Comment by jhy** [comment]
It's not clear to me what you are trying to do. If you are taking plain text, how would the span styles be preserved? What is the output that you want?

**Comment by jhy** [comment]
Closing, no response.
