### ISSUE TITLE
Bug: clean() discards text which contains a single '<' character

### ISSUE THREAD

**Issue by whchdorf** [jhy/jsoup#1894]
Hello,

I discovered that `Jsoup.clean()` apparently discards all text after a lower than`<` is followed by another alpha (non-numeric) character. 
Here is a short test to verify the behaviour: 

```java
@Test
public void test() {
    var result = Jsoup.clean("this is <some harmless input text", Safelist.basic());
    assertEquals("this is", result);
}
```
Expected is the assert to work like this:
```java
assertEquals("this is <some harmless input text", result);
```

This is potentially severe, since a harmless input text can be discarded after cleaned with JSoup. 
Might be caused by a logic that tries to unsuccessfully find the end of an opening tag. However, I would expect JSoup to not touch this text at all and the test should return the same input. 

Is there a way to fix this? 
Thanks

**Comment by akshaya57148** [comment]
I guess for reserved chars like < , > etc , you will need to use HTML encoding:
 &lt; for <
&gt; for > and so on.
For details refer :https://www.w3schools.com/HTML/html_entities.asp

**Comment by whchdorf** [comment]
> I guess for reserved chars like < , > etc , you will need to use HTML encoding: < for < > for > and so on. For details refer :https://www.w3schools.com/HTML/html_entities.asp

When I escape the input string, JSoup just does not do anything because the input is already clean. 

In case it was not stated clear enough: I want JSoups cleaning of tags still to work, but an opening tag should not stop it from working. 
here is another test that should be green if JSoup works correctly:

```java
@Test
public void test() {
    var result = Jsoup.clean("<a>RemoveThisTag</a><b>AndThisTag</b>but <not this harmless string", Safelist.none());
    assertEquals("RemoveThisTagAndThisTagbut <not this harmless string", result);
```

**Comment by jhy** [comment]
This is effectively the same as the feature idea in #1230 - rewrite illegal tags as escaped entities.

If implemented, it should be as an option to Cleaner.
