### ISSUE TITLE
SCRIPT element should provide :text() behaviors

### ISSUE THREAD

**Issue by javadoug** [jhy/jsoup#190]
The SCRIPT element is valid HTML, the content of which should be accessible via text() method. Similarly, Element::select("script:contains(somethinguseful)") is expected to work. Finally, remember script type attribute could be application/text. You do NOT have to "parse" the content of the script tag, simply treat it as cdata and expose it to the Element API so we can do simple and important work without having to require a JS parsing lib.

**Comment by maxid** [comment]
hope fix  script:contains(some-js-here) !  the code in Evaluator.java, ContainsText,ContainsOwnText,Matches,MatchesOwn  matches method like this:
        @Override
        public boolean matches(Element root, Element element) {

            return (("script".equalsIgnoreCase(element.tagName()) ? element.html() : element.ownText()).toLowerCase().contains(searchText));
        }

**Comment by lakshmirajagopalan** [comment]
I fixed the `:contains` behaviour for the `<script>` tag by looking at both `data` and `text`. Can you please merge this? @jhy 
https://github.com/lakshmirajagopalan/jsoup/commit/86162fcaecab7c4eda82cca27f86ec5862151af7

**Comment by jhy** [comment]
I added :containsData() to support this usecase.
