### ISSUE TITLE
jsoup1.15.4 'org.jsoup.helper.HttpConnection.encodeUrl(java.net.URL)' is not public in 'org.jsoup.helper.HttpConnection'. Cannot be accessed from outside package

### ISSUE THREAD

**Issue by afish177** [jhy/jsoup#1905]
I upgraded jsoup 1.15.4 to use org.jsoup.helper.HttpConnection.encodeUrl to report an error as shown in the figure
![image](https://user-images.githubusercontent.com/32056262/221091676-d004d23f-c83a-450f-89b8-9e7f1b6db7ef.png)
![image](https://user-images.githubusercontent.com/32056262/221093294-87d337ae-dfc9-4b83-bee1-698ed2483a80.png)

**Comment by jhy** [comment]
Yes? It's always been an internal method. The public API is to access via jsoup.connect(), or set a URL via [Connection.url()](https://jsoup.org/apidocs/org/jsoup/Connection.html#url(java.net.URL)). That gets encoded appropriately automatically.
