### ISSUE TITLE
new line character between closing </div> and new tag is not preserved with jsoup-1.15.4

### ISSUE THREAD

**Issue by Reeniya** [jhy/jsoup#1911]
Hi,
We are trying to upgrade jsoup in our project from 1.11.3 to 1.15.4. We are seeing that the new line character is getting removed between `</div>` and next new tag.

For example:

Input: `<div><br />The Hobbit</div><br /><p>The Movie</p>`

with 1.11.3 the output of the html parser with prettyprint set to true:
```
<html>
 <head></head>
 <body>
  <div>
   <br>
   The Hobbit
  </div>
   <br>
  <p>The Movie</p>
 </body>
</html>
```
with 1.15.4 the output of the html parser with prettyprint set to true:
```
<html>
 <head></head>
 <body>
  <div>
   <br>
   The Hobbit
  </div><br>
  <p>The Movie</p>
 </body>
</html>
```
Issue to re-create: https://try.jsoup.org/~N_NBC-ZuLdJWLSWzpsBenr3129M

@jhy  Please can you confirm if this an issue with jsoup-1.15.4 ? if not how do we ensure that we get similar output from the parser as we see in 1.11.3 version

Thanks....

**Comment by jhy** [comment]
Thanks, fixed.
