### ISSUE TITLE
css ~= returns same as *=

### ISSUE THREAD

**Issue by pisqa** [jhy/jsoup#1915]
Hi,
I've just been playing around with https://try.jsoup.org/ and I'm no css expert, so maybe this is my misunderstanding....

Testing against url https://bonigarcia.dev/selenium-webdriver-java/web-form.html
CSS queries "[class*=col]" and  "[class~=col]" return same 9 results (screenshots)

Don't we expect  "[class~=col]" to return only following 3 elements (matches whole-word col)?
```
<div class="col col-10">
<div class="col col-2">
<div class="col col-12">
```

A quick test in cypress gave me the same 9 results for * and the expected 3 results for ~

![css-tilde](https://user-images.githubusercontent.com/57501449/224027037-e9243682-0a78-4880-8008-32efb325e093.JPG)
![css-asterisk](https://user-images.githubusercontent.com/57501449/224027045-4ab40644-d09d-4834-b456-772093dd0e59.JPG)

Kind Regards,

**Comment by jhy** [comment]
The jsoup selector `[attr~=regex]` runs a [regex match](https://jsoup.org/apidocs/org/jsoup/select/Selector.html#:~:text=a%5Bhref*%3D/search/%5D-,%5Battr~%3Dregex%5D,-elements%20with%20an) against the specified attribute value; it is not exactly the same as the simple whitespace delimited word selector defined in CSS2. You can see the impl here:
https://github.com/jhy/jsoup/blob/8b31aaa144871fcc4856edddf91ac86998550243/src/main/java/org/jsoup/select/Evaluator.java#L290-L292

If you want it to explicitly be a word match (as defined in CSS2, whitespace separated words), you could use a regex like `[class~=(^|\s)col($|\s)]` (see [example](https://try.jsoup.org/~AxL8M8F1YhgU-fQ1fisthzDxSik)).

Of course if you just want to match the `col` class, use the simple class selector `.col` ([example](https://try.jsoup.org/~v-yvQaloIRJ8wvkq-78N3I9irIU)).
