### ISSUE TITLE
Double URL encoding on redirect in 1.15.4

### ISSUE THREAD

**Issue by rickosborne** [jhy/jsoup#1928]
It looks like changes to `encodeUrl` in 1.15.4 are causing URL double-encoding when redirected.

For example, the following exchange:

```
>>> GET /apostrophe-'
<<< 302 Moved
    Location: /apostrophe-%27
```

In 1.15.3, this works, and the new path is followed correctly.  In 1.15.4, the redirect URL ends up being double-encoded to `/apostrophe-%2527` instead.  Which then leads to errors like 404s.

It seems to be this change:

https://github.com/jhy/jsoup/compare/jsoup-1.15.3...jsoup-1.15.4#diff-50cf357d24b529d8ec8ffd200e666d29cb8286c71733da1a27c9b32d1204d676

While tracking this down, I also noticed that the redirect handling code in `HttpConnection$Response#execute(HttpConnection.Request, Response)` also makes a call to `encodeUrl`:

```java
String location = res.header(LOCATION);
// ...
URL redir = StringUtil.resolve(req.url(), location);
req.url(encodeUrl(redir));
```

This implies that any redirect which sends an already-encoded URL will get double-encoded.

**Comment by jhy** [comment]
Thanks for the report. This is fixed in the upcoming 1.16.1 release with #1914 and #1902.

You could use a snapshot version in the meantime - `mvn install` after checking out the tip.
