### ISSUE TITLE
TextNode::getWholeText does not preserve leading newline after <pre> tag

### ISSUE THREAD

**Issue by KennyWongPFPT** [jhy/jsoup#1932]
If we parse the fragment `<pre>\n\tfoo \t\n</pre>`, and then call `getWholeText()` on the text node, the leading `\n` will be missing from the returned value. `getWholeText()` seems to work as documented for all tags (i.e. _Get the (unencoded) text of this text node, including any newlines and spaces present in the original._), except `<pre>`.

Here's a test program that demonstrates the issue:
```
import org.jsoup.nodes.*;
import org.jsoup.parser.*;
import org.jsoup.select.*;

public class Test2 {
    public static void main(String[] args) {
        String expectedText = "\n\tfoo \t\n";

        HtmlTreeBuilder treeBuilder = new HtmlTreeBuilder();
        Parser parser = new Parser(treeBuilder);
        Document document = parser.parseInput("<pre>" + expectedText + "</pre>", "");
        NodeTraversor.traverse((Node node, int depth) -> {
            if (node instanceof TextNode textNode) {
                String actualText = textNode.getWholeText();
                printText("Expected: ", expectedText);
                printText("  Actual: ", actualText);
            }
        }, document);
    }

    static void printText(String prefix, String text) {
        System.out.print(prefix);
        for (int i = 0; i < text.length(); i++) {
            char chr = text.charAt(i);
            switch (chr) {
                case '\n': System.out.print("[\\n] "); break;
                case '\t': System.out.print("[\\t] "); break;
                default: System.out.printf("[%c] ", chr);
            }
        }
        System.out.println();
    }
}
```
And the difference between the expected and the actual results:
```
$ java -cp ~/.m2/repository/org/jsoup/jsoup/1.15.4/jsoup-1.15.4.jar Test2.java
Expected: [\n] [\t] [f] [o] [o] [ ] [\t] [\n] 
  Actual: [\t] [f] [o] [o] [ ] [\t] [\n] # Here the leading \n was not preserved by getWholeText()
```

**Comment by jhy** [comment]
Yes, this is deliberate. Per the [HTML spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing:~:text=A%20start%20tag%20whose%20tag%20name%20is%20one%20of%3A%20%22pre,Set%20the%20frameset%2Dok%20flag%20to%20%22not%20ok%22.), if the first character of a `pre` tag is a newline, it gets dropped from the element's text node.

Could you clarify how this impacts you? Perhaps there is a workaround or another approach.
