### ISSUE TITLE
endSourceRange missing for tags that are accidentally also HTML element tags in XML documents

### ISSUE THREAD

**Issue by jurgenvinju** [jhy/jsoup#1935]
Hi there!

Thanks for making JSoup. We're having a lot of leverage from this library in the rascal project. It is now the default way for parsing XML and HTML for the standard library of Rascal. So thanks.

Having some trouble with `endSourceRange`:

* I parse an XML file using JSoup, and with `.setTrackPosition(true)` 
* Using `node.sourceRange()` and `node.endSourceRange();`
* On nodes which accidentally have HTML element names, like `title`, `endSourceRange()` is always `Untracked`

I was parsing a "glossary" xml file from the web as an example:

```
<!DOCTYPE glossary PUBLIC "-//OASIS//DTD DocBook V3.1//EN">
 <glossary><title>example glossary</title>
  <GlossDiv><title>S</title>
   <GlossList>
    <GlossEntry ID="SGML" SortAs="SGML">
     <GlossTerm>Standard Generalized Markup Language</GlossTerm>
     <Acronym>SGML</Acronym>
     <Abbrev>ISO 8879:1986</Abbrev>
     <GlossDef>
      <para>A meta-markup language, used to create markup
languages such as DocBook.</para>
      <GlossSeeAlso OtherTerm="GML">
      <GlossSeeAlso OtherTerm="XML">
     </GlossDef>
     <GlossSee OtherTerm="markup">
    </GlossEntry>
   </GlossList>
  </GlossDiv>
 </glossary>
 ```
 
 * if I change `title` to `WhatNot` it works again
 * if I change `title` to `ul` or any other HTML tag, it breaks again.
 
 Will have a look in the code to see if anything obvious is going on. Cheers!

**Comment by jhy** [comment]
Hi @jurgenvinju, thanks for the feedback, glad to hear it!

I wasn't able to reproduce this issue. I added a testcase in 78aeac18c6e9a7bc9294e0575bce8e465e5223ac, but it passes. (I also tested your example XML and confirmed the end-source range of those tags.)

Can you add a reproducing code sample?

**Comment by jurgenvinju** [comment]
I think it was caused by me parsing an XML accidentally with a HTML parser. Copy/paste fail! Sorry for wasting your time, because that behavior does make sense if you are parsing an HTML file for those tags that do not have an end tag usually.

**Comment by jhy** [comment]
No worries, thanks for confirming!
