### ISSUE TITLE
Create a java module version of jsoup-xxx.jar

### ISSUE THREAD

**Issue by hbsoftdj** [jhy/jsoup#1943]
I am using jsoup in a javafx desktop app project and jsoup is working beautifully (thank you). However, the jsoup-xxx.jar file is not a java module. It is taken as an automatic module while building the project with module-info.java and everything works fine. It breaks when I try to create a runtime image with jlink. I suspect it is because jsoup jar is not a java module. Is it possible to make the library available as a java module?

**Comment by jhy** [comment]
Yes, I think it does make sense to make it a module now. Some initial work was done but not completed, in particular as I didn't see a specific benefit vs an automatic module. But if tools are being picky about it being an explicitly defined module, I guess it makes sense.

**Comment by cowwoc** [comment]
@jhy Maven and jlink complain unless `module-info.class` is present. Please provide to a full-fledged module.

**Comment by jhy** [comment]
Thanks all - I have implemented this in https://github.com/jhy/jsoup/pull/2025.

It would be great if folks could test this out and report back with confirmation of success or any issues. Please report back on the PR https://github.com/jhy/jsoup/pull/2025 (or a new issue if any problems) as there are a few duplicate issues for this. To use a snapshot, git pull && mvn install, and use version 1.17.1-SNAPSHOT in your project.
