### ISSUE TITLE
Issue with urls like -> https://learnenglish.britishcouncil.org

### ISSUE THREAD

**Issue by Knowledge-Tree-App** [jhy/jsoup#1955]
Hello, jsoup couldn't even connect to such urls to get the needed attributes, this url has them though

**Comment by jhy** [comment]
```java
String url = "https://learnenglish.britishcouncil.org";

Document doc = Jsoup.connect(url)
    .followRedirects(true)
    .get();

log(doc.title());
```

Gives:

```text
Learn English Online | British Council
```

Works for me! It's unclear from your report what "the needed attributes" refers to or what you can't get out. But I don't see an issue with jsoup here. Note that jsoup does not execute Javascript, so will only be able to extract content that is available in the HTML source (i.e. View Source vs Inspect Document).
