### ISSUE TITLE
Duplicate attributes choose last, but browser chooses first

### ISSUE THREAD

**Issue by perfnorm** [jhy/jsoup#196]
`<input name="AutoDetailsControl1$zip_" id="AutoDetailsControl1_zip_" name="zip" type="text" />`

If I parse the above in jsoup, and then ask for elt.attr("name"), I get "zip", but when Firefox submits the form, it chooses "AutoDetailsControl1$zip_" 

Not sure how consistent this is across browsers, but if it is consistent it would be great if jsoup chose the first (or made it an option)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
