### ISSUE TITLE
Json.clean introduced new-line in version 1.16.1

### ISSUE THREAD

**Issue by terrettaz** [jhy/jsoup#1960]
As an answer to this conversion marked as closed, I open an issue.

_Originally posted by @jhy in https://github.com/jhy/jsoup/issues/1916#issuecomment-1562320660_
           
Actually we are not rendenring in a webbrowser but in a mobile app (iOS and Andoid) and the new-line is displayed on mobile. I think this behavior of introducing a new line ( \n ) is not really expected in the clean() method.

What do you think ?

Kind regards,

**Comment by jhy** [comment]
I don't get why it would matter if the browser was on a desktop or a mobile device. In HTML, newlines and space characters are rendered the same in body content. My best guess is that you are treating the output of `clean()` as plain text, vs HTML, and hence the rendering difference. If so, that's the problem. And you would be better off using a `text()` method.

If not, perhaps you can provide some sample code.

**Comment by terrettaz** [comment]
Mobile iOS and Android display some plaintext containing html tags in order to do specific rendering and you're right saying that we treat the string as plain text containing some html tags.

The document is not a real html document So I don't know how to use the text() method you were suggesting.

We can also switch to another library to acheive this. For now we did a quick workaround just to have the same behavior as before:

Previous code that was working on 1.15.4

	String message = "<p>message</p> <br/><strong>container</strong> some html tags";
	Safelist safelist = Safelist.none().addTags("b", "strong", "br");
	String safeMessage = Jsoup.clean(message, safelist);
	safeMessage = safeMessage.replace("<br>", "<br/>");

Workaround since 1.16.1

	String message = "<p>message</p> <br/><strong>container</strong> some html tags";
	// https://github.com/jhy/jsoup/issues/1960
	var random = UUID.randomUUID().toString();
	var newlinePlaceholder = random + "newline";
	var spacePlaceholder = random + "space";
	var alteredMessage = message
			.replaceAll("\n", newlinePlaceholder)
			.replaceAll(" ", spacePlaceholder);
	Safelist safelist = Safelist.none().addTags("b", "strong", "br");
	String safeMessage = Jsoup.clean(alteredMessage, safelist)
			.replaceAll("\n", "")
			.replaceAll(newlinePlaceholder, "\n")
			.replaceAll(spacePlaceholder, " ")
			.replace("<br>", "<br/>");

**Comment by sylantro** [comment]
@jhy
I agree that any extraneous newline characters added to the output won't affect what is rendered in the browser; but, the `String` object returned from `Jsoup.clean()` is now different and unexpected - it has these `\n` characters that weren't there previously. 

In my case, the added newline characters in the cleaned output breaks a number of my Java unit tests, which compares HTML markup before and after sanitization. While I understand these aren't "true" failures in the sense of what the browser will render (I can confirm that manually by looking at it in the browser), my Java code that interacts with JSoup now has to deal with unexpected unrenderable characters in the cleaned output.

While I'd expect `Jsoup.clean()` to add missing closing tags etc, I would not  expect it to add newlines (or other whitespace characters) when pretty-printing is disabled.

Without a fix, I'll need to add code to replace all the unexpected newlines everywhere.

**Comment by jhy** [comment]
Sorry for the late review -- will close as I don't see this as actionable.

**Comment by jhy** [comment]
You could always use the cleaner without the pretty-printer enabled, if you want to preserve the input spaces / newlines.
