### ISSUE TITLE
When prettyPrint(false) is set, \r does not resolve correctly

### ISSUE THREAD

**Issue by zhxzkhz** [jhy/jsoup#1968]
![image](https://github.com/jhy/jsoup/assets/82936352/2e50f8c7-1b76-4748-9769-be5dc9ab6aed)

**Comment by jhy** [comment]
Please rewrite this to not include screen shots, but a simple Junit test case with code showing what you expect.

**Comment by jhy** [comment]
Closing as stale; please reopen if you can rewrite as noted.
