### ISSUE TITLE
Tags disappearing based on which elements are selected

### ISSUE THREAD

**Issue by antiquechrono** [jhy/jsoup#1973]
I'm trying to extract some information by selecting an element by id using the following
```kotlin
doc.select("#des")
```

This returns an empty span with all it's children and text removed
```html
<span id="des"></span>
```

If I select all p tags on the page I get the following output which is rather strange as there are only 2 p tags
```html
0 <p><span id="des"></span></p>
1 <p><span>This is a description </span></p>
2 <p></p>
```

If I switch to the xml parser I get the expected result
```html
0 <p>
    <span id="des"><p><span>This is a description </span></p></span>
</p>
1 <p><span>This is a description </span></p>
```

I have whittled down the html to a minimum reproducible example, I believe this issue is being caused by the illegal p tag inside the span, however I do not have any control over the document I'm parsing. Even though the inner p tag is technically illegal this behavior seems like a bug as tags are disappearing based on which element you select.

```html
<!DOCTYPE html>
<html lang="en">
<body>
<p>
    <span id="des">
        <p>
            <span>This is a description </span>
        </p>
    </span>
</p>
</body>
</html>

```

**Comment by jhy** [comment]
I wouldn't say anything is disappearing - it's just that the HTML is being parsed to a different structure than you expect. The parse tree for your above HTML is:

https://try.jsoup.org/~ggpbAu3rkKf9g2F_c3Oh67iIOzQ
```html
<!doctype html>
<html lang="en">
 <head></head>
 <body>
  <p><span id="des"> </span></p>
  <p><span>This is a description </span></p>
  <p></p>
 </body>
</html>
```

This is the behaviour of jsoup which is a HTML5 conformant parser.

You can either alter your selector, or use the jsoup XML parser, which does not conform documents to HTML5 syntax.
