### ISSUE TITLE
Does HTTPS Proxy not support it?

### ISSUE THREAD

**Issue by weiwill** [jhy/jsoup#1975]
Like HttpClient HttpHost("proxy.com", 8080, "https")

**Comment by lengyue-ck** [comment]
It seems that an HTTPS proxy can be set, but it cannot be authenticated through an account password, and it will return Unable to tunnel through proxy Proxy returns "HTTP/1.1 407 Proxy Authentication Required, if the proxy IP does not have a password, it can be set normally

**Comment by jhy** [comment]
I have added direct support for per-request authentication in `Jsoup.connect().auth()` in #2046. Would be greatly appreciated if folks can test this in a local snapshot version and provide feedback (on the PR - #2046)
