### ISSUE TITLE
":empty" psuedo-class not working

### ISSUE THREAD

**Issue by cjmalloy** [jhy/jsoup#1976]
I am trying to use the :empty psuedo-class to remove empty lists. Instead, it does not select empty &lt;li&gt; tags or any other tags I try:

```Java
var doc = Jsoup.parse(" <p>test</p>\n" +
	" <ul>\n" +
	"   <li>\n" +
	"   </li>\n" +
	" </ul>\n" +
	" <ul>\n" +
	"   <li>\n" +
	"   </li>\n" +
	" </ul>\n" +
	" <p>test</p>");
var lis = doc.select("li:empty");
lis.remove();
```

**Comment by jhy** [comment]
These elements weren't matching the `:empty` selector as they have non-empty textnode children. But that's not very useful, so I updated the Evaluator to match if the textnode children are blank (i.e. just whitespace).
