### ISSUE TITLE
Too much whitespace removed from HTML

### ISSUE THREAD

**Issue by leekowalkowski-hmrc** [jhy/jsoup#1977]
Given the HTML `<h1>Title</h1> <a href="/">Home</a>`

`Jsoup.parse(html).toString()` outputs `<h1>Title</h1><a href="/">Home</a>` (without a space) yet `Jsoup.parse(html).text()` outputs "Title Home" (with a space).  This is a contradiction, if we render this HTML in a browser without a space between the elements, the `textContent` of the document would be "TitleHome" 

I.e. the HTML generated by `toString()` is an inaccurate representation of the HTML that it parsed.

The behaviour was correct in Jsoup 1.14.3 where `toString()` outputs `<h1>Title</h1> <a href="/">Home</a>`, and first broken in 1.15.1.

**Comment by jhy** [comment]
I think you're asking for the opposite of #1977. It's not going to be possible to do both.

The currently implemented behaviour is that when serializing as HTML and pretty-printing is enabled, jsoup will collapse non-significant whitespace. In this case, with an inline tag following a block, that whitespace is non-significant, and so it is dropped.

Note that the `.text()` of `<h1>Title</h1><a>Home</a>` is `Title Home`, so the semantic text was not impacted by serializing this way. 

`.text()` is intended to produce a readable flow of text, similarly to a browser's displaying the title and the link with space between when rendered, regardless of if there is whitespace between the nodes in the input HTML).

Conversely, `.wholeText()` of `"<h1>Title</h1><a>Home</a>"` is `TitleHome`, which is more like a browser's `textContent`.

If you don't want this behaviour, the currently available option is to disable the pretty printer, which will leave whitespace generally as-is from the input source.

At some point it would be nice to refactor the pretty printer and provide more optional control, so differing requirements / preferences can be more readily met.

But at the moment I don't see this as a bug or causing a negative impact. If I've missed something, please feel free to reopen.

**Comment by leekowalkowski-hmrc** [comment]
#1997 is _this_ issue, which issue is the opposite of this one?

We discovered the issue because we were sending the output of pretty-printed HTML to the browser, and the erroneous removal of this significant whitespace (it is not non-significant in the example given!) was affecting users of assistive technology.

**Comment by jhy** [comment]
Sorry, I meant #1802.

I took another look and still believe this is insignificant whitespace. The textnode between the block-level tag (h1) and the inline tag (a) is insignificant. Browsers will render `<h1>Title</h1><a>Home</a>` and `<h1>Title</h1> <a>Home</a>` the same.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

> was affecting users of assistive technology

This seems like the root. Which assistive technology specifically? I'd like to review. It seems incorrect to me that a reader would blithely use the textContent of a super/parent node to read out content, because that's not the semantic meaning of the document's flow. (As evidenced by the visual rendering; and why jsoup's `text()` will treat this as "Title Home".)

**Comment by leekowalkowski-hmrc** [comment]
I've not been able to identify specific assistive technology unfortunately, this might be an unvalidated assumption, as the problem introduced by Jsoup 1.15.1 caused some users to complain, and some complaints mentioned accessibility.

The service we received complaints from is an internal tool that crawls our public pages using chromedriver/selenium and sends a text-only representation of our page to another system for internal use. When we upgraded our service from Jsoup 1.14.3, we received complaints that words were being incorrectly 'squished together' when our screens are scraped by the crawler.

So, in light of not fixing Jsoup, our options are:
- pin Jsoup to 1.14.3 in our service (currently doing)
- upgrade Jsoup, but disable pretty printing
- respond to the complaints and request they finesse their crawler (suspicion is that it simply evaluates document.body.textContent within the browser)

But our opinion still stands that if HTML is to be pretty printed, document.body.textContent in the browser-parsed version of the HTML should yeild the same result as the non-pretty printed HTML, therefore significant whitespace is being removed by Jsoup here.

**Comment by leekowalkowski-hmrc** [comment]
> Browsers will render `<h1>Title</h1><a>Home</a>` and `<h1>Title</h1> <a>Home</a>` the same.

Also, as one of my colleagues has pointed out, it cannot be determined that a browser will render both versions of this HTML the same, as this will depend on the CSS being applied.  i.e. if a `h1 {display:inline}` ruleset is used, both versions of the HTML will render differently.

**Comment by jhy** [comment]
Sure, the Pretty Printer assumes that the display mode, and text mode (e.g. pre-wrap) settings have not been changed. I would recommend not using the Pretty Printer in that circumstance, or in your example where downstream tools are sensitive to whitespace changes.

**Comment by jhy** [comment]
Also just looking a bit more -- a browser's `innerText` value for both of these HTML versions is `Title\nHome`. Which I believe reinforces my point that a whitespace textnode between a block and an inline is correctly treated as insignificant whitespace and can be collapsed.

Perhaps your internal tool would be better off using `innerText`, and that way the implementation will not be so sensitive to how the HTML is authored. (Obviously I don't have all the context on it -- just a thought.)

**Comment by leekowalkowski-hmrc** [comment]
Thanks!  Yes, I think innerText instead of textContent may solve this problem.
