### ISSUE TITLE
Closing tags are added for malformed html 

### ISSUE THREAD

**Issue by cmak9149** [jhy/jsoup#1978]
Our software uses jsoup to convert only text nodes in HTML content. It works well unless the HTML content is malformed, say missing closing `</div>` tag in the following

```
<div>
     <span>content</span>
```

After parsing with html Parser, a closing tag is added. Our use case is to preserve the content as much as possible. Is there a setting to override the normalization?

**Comment by jhy** [comment]
jsoup always parses to a valid parse tree. So no, there is not a configuration to serialize without that normalization.

One approach might be to inspect the TextNodes after the parse, and use the Source Range to identify where in the input they occurred. Then you could merge them into your original (non-normalized) input HTML.
