### ISSUE TITLE
Redirected URL is not being encoded?

### ISSUE THREAD

**Issue by kdekooter** [jhy/jsoup#1979]
I am loading a URL that is being redirected. It looks like the URL that is being redirected to is not being URL encoded first. 
```
Illegal character in query at index 43: https://xxx.xxxxx.xx/xxxxxx/?offering_type="buy"...
                                                                                  ^                                
```
Am I right, and if so, how can this be solved?

**Comment by jhy** [comment]
URLs in redirects are encoded / normalized using the UrlBuilder. The entrance is here:

https://github.com/jhy/jsoup/blob/1e69577e358c75a85b769583f0cf860eedb18a5e/src/main/java/org/jsoup/helper/HttpConnection.java#L906

Can you give a full code example test case so it's possible to reproduce your issue?

**Comment by jhy** [comment]
Closing as there's no reproduction path - if you can supply a reproducer, please reopen.
