### ISSUE TITLE
 Cannot set proxy for account password authentication 

### ISSUE THREAD

**Issue by DokiDoki1103** [jhy/jsoup#1981]
f the proxy IP requires account password verification and Jsoup cannot be set correctly, it will return Unable to tunnel through proxy Proxy returns "HTTP/1.1 407 Proxy Authentication Required", but Httpclient can be set normally, so I believe it should be Jsoup not supporting it. Please modify this bug as soon as possible

**Comment by jhy** [comment]
I have added direct support for per-request authentication in `Jsoup.connect().auth()` in #2046. Would be greatly appreciated if folks can test this in a local snapshot version and provide feedback (on the PR - #2046)
