### ISSUE TITLE
The document object obtained from parsing with jsoup.parse is missing one layer of elements compared to the original HTML.

### ISSUE THREAD

**Issue by 666asd** [jhy/jsoup#1983]
https://test.em.bonahl.com/#/user/login
original :
![image](https://github.com/jhy/jsoup/assets/16465586/53c168e0-1eca-484b-9258-294ffd596f63)
jsoup:
![image](https://github.com/jhy/jsoup/assets/16465586/ee8e9f93-f749-43c0-a5fa-78b6c6cd9bc3)

**Comment by 666asd** [comment]
https://github.com/jhy/jsoup/blob/1762412a28fa7b08ccf71d93fc4c98dc73086e03/src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java#L417
![image](https://github.com/jhy/jsoup/assets/16465586/2607dc4d-c00a-4a20-ba18-14b80a3f3c22)
It seems that nesting forms is not allowed here. However, modern frontend frameworks have implemented nested form nesting.

**Comment by jhy** [comment]
Input:

```html
<div>
<form id=1>
<form id=2>
</form>
</form>
```

jsoup parse:
```
  <div>
   <form id="1">
   </form>
  </div>
```

Chrome parse (Inspect Document)

<img width="292" alt="Screenshot 2023-09-08 at 2 09 07 pm" src="https://github.com/jhy/jsoup/assets/76934/9e7c00df-9d16-4164-b93e-587cc953ec78">

Spec:
https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody
>A start tag whose tag name is "form"
If the form element pointer is not null, and there is no template element on the stack of open elements, then this is a parse error; ignore the token.
>...

I believe jsoup is working per spec and to the same output as current browsers by only allowing one `form` on the stack at a time.

**Comment by skylakeliu** [comment]
Shadow DOM enables you to attach a DOM tree to an element, and have the internals of this tree hidden from JavaScript and CSS running in the page. Modern frontend frameworks have implemented neste HTML forms through Shadow DOM, and it have been widely used. jsoup should adapt to this.
![image](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM/shadowdom.svg)
