### ISSUE TITLE
JSOUP is unencoding '<' in attribute values 

### ISSUE THREAD

**Issue by madhurichaudhari123** [jhy/jsoup#1986]
Jsoup is working fine with greater than symbol(>) but its behavior changed for less than symbol(<)
It has been eliminating the remaining characters after “<“ symbol (Mi<ke —> Mi).
Can we handle it by using any configuration change.
could you Please suggest.

**Comment by jhy** [comment]
Please provide a full repro testcase.

**Comment by jhy** [comment]
I haven't been able to repro this. See e.g. https://try.jsoup.org/~275FTt2Ymv8HyfFwelywizP7I9k

Closing, but if you can supply a repro, please reopen and I'll take another look.
