### ISSUE TITLE
Jsoup clearing thread interruption flag during I/O operations

### ISSUE THREAD

**Issue by artemmukhin** [jhy/jsoup#1991]
I've noticed an issue with how thread interruption handling is managed. I couldn't find any mention of this behaviour in the docs, and I'm not sure whether it's expected.

Jsoup appears to clear the interruption flag of the calling thread during I/O operations, which, I believe, leads to unexpected behaviour when trying to manage thread interruption.

Consider the following client code:
```Java
public void runWhileNotInterrupted() throws InterruptedException {
    final ArrayList<String> bodies = new ArrayList<>();
    Thread runner = new Thread(() -> {
        try {
            int i = 1;
            while (!Thread.currentThread().isInterrupted()) {
                Connection.Response res = Jsoup.connect("https://github.com/jhy/jsoup/issues/" + i).execute();
                bodies.add(res.body());
                i += 1;
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    });

    runner.start();
    Thread.sleep(3 * 1000);
    runner.interrupt(); // Jsoup clears the flag
    runner.join(); // Thread never completes
    System.out.println(bodies);
}
```

The interruption flag is being cleared through `java.lang.Thread#interrupted` in `ConstrainableInputStream.java`:
https://github.com/jhy/jsoup/blob/1762412a28fa7b08ccf71d93fc4c98dc73086e03/src/main/java/org/jsoup/internal/ConstrainableInputStream.java#L49-L56

I would expect either the interruption flag to be preserved or `java.lang.InterruptedException` to be thrown by Jsoup.

Please let me know if that behaviour is indeed unexpected. I will try to come up with a suitable solution and open a PR. Thanks!

**Comment by jhy** [comment]
Thanks, good find! Fixed.

**Comment by artemmukhin** [comment]
Thank you @jhy!
