### ISSUE TITLE
Returns 403  instead of 200 with correct user agent 

### ISSUE THREAD

**Issue by WoodySide** [jhy/jsoup#2006]
`Document document = Jsoup.connect("https://codepen.io/nicolasjesenberger/pen/jOQGgVB")
                .ignoreContentType(true)
                .referrer("http://www.google.com")
                .followRedirects(true)
                .timeout(12000)
                .userAgent("Mozilla/6.0 Chrome/19.0.1084.46 Safari/536.5")
                .execute()
                .parse();`

**Comment by jhy** [comment]
jsoup is making valid requests and so this isn't an issue we can fix within jsoup. The site is using Cloudflare which is configured to block scripted requests. You would need to find a way to pass the javascript + human validation.

`<span id="challenge-error-text">Enable JavaScript and cookies to continue</span>`

**Comment by WoodySide** [comment]
Thank you so much!)
