### ISSUE TITLE
XHTML escape mode should use <![CDATA[ ... ]]> in data nodes

### ISSUE THREAD

**Issue by ghost** [jhy/jsoup#202]
HTML output for a data node that includes an ampersand will blow up XML parsers. Here's an example:

    scala> import org.jsoup._
    scala> val doc = Jsoup.parse("<script>if (a && b) ...</script>")
    scala> doc.outputSettings.escapeMode(nodes.Entities.EscapeMode.xhtml)
    scala> doc.html
    res1: java.lang.String = 
    <html>
     <head>
      <script>if (a && b) ...</script>
     </head>
     <body></body>
    </html>

XML parsers will try and fail to parse the ampersands in the script tag as entities. Wrapping the script tag's contents in a CDATA tag fixes this problem.

**Comment by jhy** [comment]
You can (now) use the XML syntax and they'll be escaped as `&amp;`
