### ISSUE TITLE
Bug: Unable to correctly parse the text of the node <br>.

### ISSUE THREAD

**Issue by LYZ1125** [jhy/jsoup#2020]
Hello Jsoup Team,
I hope this message finds you well. I find an issue I encountered while using Jsoup in my project. 

### Issue Description:
Unable to correctly parse the text of the parent of the node with tag < br >.
For example:
```
<html>
 <head></head>
 <body>
  <div class="msgLine">
   The changes have been carried out correctly 
   <br><strong>textzone_top.inc.html</strong>
  </div>
 </body>
</html>
```

The text of < br > is "" instead of "\n". But in fact, < br > is often used to present the "\n".

In jsoup, the text " The changes have been carried out correctly " and the text "textzone_top.inc.html" are in the same line.
But in fact, they are in different line.

I wonder if can fix this bug and make the text obtained closer to the real situation.

### Reproduce the problem.
jsoup version: 1.16.2
```
public static void main(String[] args) {
            Document document = Jsoup.parse("<html>\n" +
                    " <head></head>\n" +
                    " <body>\n" +
                    "  <div class=\"msgLine\">\n" +
                    "   The changes have been carried out correctly \n" +
                    "   <br><strong>textzone_top.inc.html</strong>\n" +
                    "  </div>\n" +
                    " </body>\n" +
                    "</html>");
            Element html1 =document.getElementsByTag("html").get(0);
            System.out.println("==" + html1.getElementsByTag("br").get(0).text()+ "++");
        }
```
output:
```
==++
```
It means that the text of < br > is "" instead of "\n".

### When will it be affected?

I am a UI testor. In order to speed up the parsing of HTML, we use Jsoup to parse HTML and obtain text. It is then used in Selenium (a web UI test engineer) test cases. However, we found that the text obtained by Selenium was inconsistent with Jsoup. The reason lies in the < br > element. After comparison, we believe that the way Selenium parses the text of br into '\n' is more in line with the real situation. Therefore, we raised this issue, hoping to help the development of Jsoup.

If you think this is not a bug, please forgive my intrusion. Thanks!

**Comment by jhy** [comment]
Hi there,

Thanks for the discussion. On consideration, I don't believe this is a bug. It just works a bit differently then Selenium. In jsoup, the `text()` method normalizes text. Newlines are output as a space, consecutive spaces are collapsed, and a single whitespace collapses to nothing. So a `br` element's `text()` on its own is just `""`, but in a larger selection will add a `" "` if required.

But, the `wholeText()` method does not perform that normalization, and for a `br` is `\n`. So perhaps that method will work better for your tests.

See code at:

[org.jsoup.nodes.Element org/jsoup/nodes/Element.java:1359](https://github.com/jhy/jsoup/blob/2a4a9cf83dea46aff9fc97fc6da808948f5086e0/src/main/java/org/jsoup/nodes/Element.java#L1345-L1402)
