### ISSUE TITLE
Bug: title tag in svg also includes in text

### ISSUE THREAD

**Issue by michaelshekasta** [jhy/jsoup#2023]
Hi,

First of all, thanks guys! You have built a great library!!

I think that I found a bug in jsoup - here is a simple code that simulate the bug:

```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public class JsoupTextSVGTitleBug {

    public static void main(String[] args) {
        String html = """
                <html>
                <body>
                <div>
                Test text
                <svg viewBox="0 0 20 10" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="5" cy="5" r="4">
                    <title>I'm a circle</title>
                  </circle>

                  <rect x="11" y="1" width="8" height="8">
                    <title>I'm a square</title>
                  </rect>
                </svg>
                More text
                </div>
                </body>
                </html>""";
        Document parse = Jsoup.parse(html);
        System.out.println(parse.body().text()); //print Test text I'm a circle I'm a square More text
    }
}
```

As I see that, the TextNode doesn't take the svg scoop in account.

**Comment by jhy** [comment]
It's not immediately clear to me why you want to exclude this text content from `.text()`. What's your use case?

I note that in comparing to Chrome, `textContent` (which is akin to jsoup's `wholeText()`) includes this text, while `innerText` (akin to jsoup's `text()`) does not. However, Chrome renders the SVG graphics, and jsoup doesn't. So including the text y default seems appropriate and useful, assuming that the text is requested for generating a text-only readable version of the page.

**Comment by michaelshekasta** [comment]
@jhy 
First of all, thank you for replying to the message so quick. I am very appreciated.

I will try to explain myself better. If you take the HTML code above, open it with Chrome. And then you will get:

'Test text  More text'

![image](https://github.com/jhy/jsoup/assets/41590425/f89b579c-678e-49e4-bf21-46945a59077b)

But when you ran the code in Jsoup you got a different result ('Test text I'm a circle I'm a square More text')

The reason for this is due to the title tag inside the SVG. After reading the documentation carefully, I think that Chrome probably extract the text correctly:

"Text in a <title> element is not rendered as part of the graphic, but browsers usually display it as a tooltip. If an element can be described by visible text, it is recommended to reference that text with an [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) attribute **rather than using the <title> element.**"
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

**Comment by jhy** [comment]
Yes, I understand the difference between Chrome and jsoup here. I am not sure of the relevance of the quote from Mozdev as that's talking about the context of a visual browser. 

As I said, it seems appropriate and useful to include the text in the text() method. Can you clarify why you think it isn't? Stepping back, whats your use case -- what are you trying to do that is negatively impacted by this? What's your input source?

**Comment by jhy** [comment]
(Closing as no response from requestor. Happy to re-review with further input.)
