### ISSUE TITLE
document.html(T appendable) just stops writing to file

### ISSUE THREAD

**Issue by kicktipp** [jhy/jsoup#2034]
this small java produces an html and writes it to a file. html(appendable)  
correct.html is fine but incorrect.html is not written in full length. it just stops in the middle. Why is it? Looks like a bug to me. 

```
package org.example;

import org.jsoup.Jsoup;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class JsoupTest {

    private static final String TEMPLATE = """
                    <!DOCTYPE html>
                    <html lang="de">
                        <head>
                            <title></title>
                            <meta charset="UTF-8">
                        </head>
                        <body>
                        </body>
                    </html>
            """;

    public static void main(String[] args) throws IOException {
        var jsoup = new JsoupTest();
        jsoup.buildHtml();
    }

    public void buildHtml() throws IOException {
        var document = Jsoup.parse(TEMPLATE);
        document.title("Test");
        for (int i = 0; i < 500; i++) {
            String key = "id" + i;
            document.body()
                    .append("<div id=\"%s\">%s</div>".formatted(key, "Hello"));
        }
        Files.writeString(Path.of("correct.html"), document.outerHtml());
        document.html(new OutputStreamWriter(new FileOutputStream("incorrect.html"), StandardCharsets.UTF_8));
    }
}

```

**Comment by jhy** [comment]
Well, you're not closing the Writer and so its buffered content is dropped.

jsoup is appending all the content  to your Writer, which buffers its output to the FileOutputStream. Some of it gets flushed to the FileOutputStream when it goes past the 8k default buffer size in StreamEncoder. But then when your program terminates, you haven't flushed the remainder and so it is dropped.

Try this:

```java
Writer writer = new OutputStreamWriter(new FileOutputStream("incorrect.html"), StandardCharsets.UTF_8);
document.html(writer);
writer.close();
```

and you'll see all the contents are written correctly.

See: [OutputStreamWriter documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/OutputStreamWriter.html). Which also suggests wrapping in a BufferedStreamWriter to buffer on its input side.

**Comment by kicktipp** [comment]
ups, I am so sorry!  It's embarrassing. You can delete this issue or tag it with "stupid-user"

**Comment by jhy** [comment]
:) no worries! Good to have the code as a sample if others see the same symptoms. I found it surprising that neither IntelliJ nor the compiler warn on this - not closing an open file.
