### ISSUE TITLE
Empty form action should resolve to document's address (should disregard baseuri set with base element)

### ISSUE THREAD

**Issue by jirikopsa** [jhy/jsoup#204]
Empty form action should resolve to document's address - i.e. it should ignore any baseuri set with base element.

See the spec:
http://www.whatwg.org/specs/web-apps/current-work/multipage/association-of-controls-and-forms.html#dom-fs-action

To reproduce:

``` html
<html>
<head>
  <base href="http://example.com/"/>
</head>
<body>
  <form action="">
    <input type="submit" value="foo"/>
  </form>
</body>
</html>
```
- Parse and run form.absurl("action") 
- Observe it returns "http://example.com/", although it should return the document address (the one it was retrieved from).

Note:
- This bug only applies to form's action; empty links should resolve to uri specified by base element

Fix:
- The problem is that Node.absurl does not know about this HTML "specificity"
- Obviously, there is a workaround on the client side, but I believe the expectations on jsoup would be to "behave as close to browsers as possible".

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
