### ISSUE TITLE
selectXpath is not working well in some page

### ISSUE THREAD

**Issue by nghiafaber** [jhy/jsoup#2043]
url: https://www.thegioididong.com/dtdd/iphone-15-pro
xPath: /html/body/section[1]/div[3]/div[1]/div[1]/div[1]/div/div[1]/div[1]/div/div[1]/a/img

Code Example:
```
public static Elements getElementsByXpath(String url, String xpath) {
        try {
            Document doc = Jsoup.connect(url).get();
            Elements eles = doc.selectXpath(xpath);
            return eles;
        } catch (IOException e) {
            return null;
        }
    }
```

I used latest version to select Elements from xpath but it is `empty` although url and xpath are correct.
I expected it is return a image element.

**Comment by jhy** [comment]
The page doesn't load for me, it just times out. I can't test it.

Are you sure the HTML is in the page? Remember that jsoup does not execute javascript so if the DOM content you're looking for is added by executing javascript, you won't be able to directly fetch it using jsoup.

You can check by using `View Source` in your browser. NOT `Inspect` which shows the evaluated DOM.

If the content you are looking for is visible in `View Source`, paste it into https://try.jsoup.org/ and share it so we can have a look.

**Comment by jhy** [comment]
(No update from reporter; closing.)

**Comment by nghiafaber** [comment]
Sorry for the delayed response.
I `View Source` that page on my browser, and the element is visible in HTML.
Now, You can use this link to view HTML content.
https://try.jsoup.org/~_X1uMnR2_p6gH1XyIGaDhJ7X0QQ

**Comment by jhy** [comment]
OK, and have you debugged your selector? Can you show us at which step it fails? 

Where did you get that selector? If you got it from Chrome (or another browser) via Inspect then you are looking at the evaluated DOM which is likely to have been modified from the source. So the selector Chrome produces does not match the source.

I note that cutting to a simpler path like `/html/body/section[1]//div[1]/a/img` matches a set of images. I expect you can whittle down from there to find the specific one you're trying to scrape. [Example](https://try.jsoup.org/~99819uSizj-2q_vV-B92wdNz3DI).
