### ISSUE TITLE
Cleaning noscript doesn't remove element content

### ISSUE THREAD

**Issue by wnm3** [jhy/jsoup#2050]
There was a change to the Safelist addTag [here](https://github.com/jhy/jsoup/commit/5f20fcc2f728a930444c2ba9252ec26b20587a80) in release version 1.16.2 that keeps the `<noscript></noscript>` tags from being retained in the cleansed document because you can't add the tag "noscript" to the Safelist. However, the content between these tags is not removed so an HTML like:
```
 <body>
  <noscript>
   You need to enable JavaScript to run this app.
  </noscript>
  <div id="root">
```
turns into HTML like:
```
 <body>
  You need to enable JavaScript to run this app.
  <div id="root">
```
I would expect the content between the noscript tags would also have been cleansed resulting in HTML like:
```
 <body>
  <div id="root">
```
I need the noscript to be allowed in the safelist to give me the option to see the elements and make a decision whether or not to process them.

Can you either provide an override to addTag to allow noscript to remain in the cleansed document, or remove the content between the noscript elements? The latter is less palatable as there are cases where I want to see and process the noscript content. I'm using the cleansed document to transform the HTML into Markdown.

I'll have to revert to 1.16.1 until a suitable workaround is provided. I believe the intent of the change was to address XSS issues but the implemented fix has had too far reaching consequences.

**Comment by jhy** [comment]
Hi,

The Cleaner's implementation has always been to unwrap dropped tags (that is, remove the element but preserve the inner content, subject to the other safelist rules). It might be an interesting idea to allow configuration of other options (per tag). E.g. drop the inner content, escape the tag, etc.

For your case, if you are planning on explicitly removing the noscript element and descendants. In 1.16.2 the [Safelist's](https://jsoup.org/apidocs/org/jsoup/safety/Safelist.html) [isSafeTag](https://jsoup.org/apidocs/org/jsoup/safety/Safelist.html#isSafeTag(java.lang.String)) and [isSafeAttribute](https://jsoup.org/apidocs/org/jsoup/safety/Safelist.html#isSafeAttribute(java.lang.String,org.jsoup.nodes.Element,org.jsoup.nodes.Attribute)) methods are now overridable. So you can implement your own strategy as required. For example:

```java
String html = "<body><noscript>This document requires JS</noscript><p>Other";
Safelist safelist = new Safelist() {
    @Override
    public boolean isSafeTag(String tag) {
        if ("noscript".equals(tag))
            return true;
        else
            return super.isSafeTag(tag);
    }
};
safelist.addTags("p");

Cleaner cleaner = new Cleaner(safelist);
Document includesNoscript = cleaner.clean(Jsoup.parse(html, "https://example.com/"));
print(includesNoscript.body());

Document nonoscript = includesNoscript.clone();
nonoscript.select("noscript").remove();
print(nonoscript.body());
```

Gives
```html
<body>
 <noscript>
  This document requires JS
 </noscript>
 <p>Other</p>
</body>

<body>
 <p>Other</p>
</body>
```

Would recommend not leaving it in though, as it's a potential vector there given how different browser contexts will handle it depending on if in scripting context or not.

**Comment by wnm3** [comment]
In version 1.16.2, I need to override addTags and it references tagNames and TagName that are not visible.

**Comment by jhy** [comment]
I'm not sure why you're trying to do that vs the working example I provided above? Override `isSafeTag`, which is what the Cleaner will call in Safelist when it's traversing the document, to decide what to keep / drop.

**Comment by jhy** [comment]
Please review my previous comments, including the sample I wrote for you and tested.

https://github.com/jhy/jsoup/issues/2050#issuecomment-1813468434
https://github.com/jhy/jsoup/issues/2050#issuecomment-1815453887

I am **not** suggesting you override `addTag`. I am suggesting you override `isSafeTag`. That is the method that the Cleaner hits to see if it allows a tag.

The sample I gave will allow `noscript` if that's the input, or fallback to the default implementation otherwise (which will then check if tagNames contains the tag -- but crucially, tagNames doesn't have to, because you are overriding isSafeTag and saying "yes" to `noscript`.)

The example I gave produces:

```html
Allows:
<body>
 <noscript>
  This document requires JS
 </noscript>
 <p>Other</p>
</body>

Then removed:
<body>
 <p>Other</p>
</body>
```

**Comment by wnm3** [comment]
I apologize. My code hadn't explicitly used the Safelist constructor but had used the Safelist.basicWithImages() upon which I'd added my addTags and addAttributes method calls. So, I didn't think I could leverage the override solution you'd provided and thought I needed the addTags modification I was advocating.

With a clear head, I revisited the issue and it was simple to use the constructor to provide the override, and add the setup from the basic() and basicWithImages(), and then add my additional tags/attributes.

Thank you, the solution worked as you'd expected ;^)

**Comment by jhy** [comment]
Great -- glad that it's working for you!
