### ISSUE TITLE
The document object obtained from parsing with jsoup.parse is missing one layer of elements compared to the original HTML.

### ISSUE THREAD

**Issue by skylakeliu** [jhy/jsoup#2052]
Input:
```html
<div>
<form id=1>
<form id=2>
</form>
</form>
```
jsoup parse:
```html
  <div>
   <form id="1">
   </form>
  </div>
```
expect:
```html
  <div>
   <form id=1>
    <form id=2>
    </form>
   </form>
  </div>
```

Normal HTML does not allow you to nest HTML forms. But with javascript or Modern frontend frameworks you can be able to do that.

Shadow DOM enables you to attach a DOM tree to an element, and have the internals of this tree hidden from JavaScript and CSS running in the page. Modern frontend frameworks have implemented neste HTML forms through Shadow DOM, and it have been widely used. jsoup should adapt to this.

![shadowdom](https://camo.githubusercontent.com/cafde6d617c9b9239e4a905bd6228c1809b490018670ef685b00f82762b25cdb/68747470733a2f2f646576656c6f7065722e6d6f7a696c6c612e6f72672f656e2d55532f646f63732f5765622f4150492f5765625f636f6d706f6e656e74732f5573696e675f736861646f775f444f4d2f736861646f77646f6d2e737667)

Example:
![image](https://github.com/jhy/jsoup/assets/45391209/13010f69-f606-4632-b335-26efc1003253)

Link issue: [jsoup-issue-1983](https://github.com/jhy/jsoup/issues/1983)

**Comment by jhy** [comment]
But this is not a function of the HTML parse. The shadow DOM is applied via scripting. You can do the same with jsoup by appending contents to the DOM. So logically this is already implemented.

In a browser, Inspect is not the same as View Source. View Source is the source HTML that is parsed.

**Comment by jhy** [comment]
And if you don't want HTML parse rules to apply, you can use the Jsoup XML parser. That would allow parsing of HTML/XML that had nested form structures, if that's in your original source.
