### ISSUE TITLE
JSoup escapes wicket elements in <title>

### ISSUE THREAD

**Issue by krtek** [jhy/jsoup#206]
I have a problem processing a wicket template with `<wicket:message>` in `<title>` tag. Consider following HTML:

```
<html xmlns:wicket="http://wicket.apache.org/dtds.data/wicket-xhtml1.4-strict.dtd">
 <head>
  <title><wicket:message key="title">Page title</wicket:message></title>
 </head>
</html>
```

The `<wicket:message>` tag is escaped like this:

```
<html xmlns:wicket="http://wicket.apache.org/dtds.data/wicket-xhtml1.4-strict.dtd">
 <head>
  <title>&lt;wicket:message key=&quot;title&quot;&gt;Page title&lt;/wicketmessage&gt;</title>
 </head>
 <body></body>
</html>
```

I know that HTML specification says that `<title>` tag may only contain strings, but maybe with explicitly selecting something like `EscapeMode.none` the JSoup might skip escaping the output document?

Test code (in Groovy): 

```
@Grab(group='org.jsoup', module='jsoup', version='1.6.3')

import org.jsoup.* 
import org.jsoup.nodes.*

doc = Jsoup.parse(
    "<html xmlns:wicket=\"http://wicket.apache.org/dtds.data/wicket-xhtml1.4-strict.dtd\">" +
    "<head><title><wicket:message key=\"title\">Page title</wicket:message></title></head></html>")
doc.outputSettings().escapeMode(Entities.EscapeMode.xhtml)
doc.outputSettings().charset("UTF-8");
println doc.html()
```

P.S.: And there is no colon in `</wicket:message>` closing tag - it's just gone.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
