### ISSUE TITLE
Wrong parsing in code tag

### ISSUE THREAD

**Issue by seazon** [jhy/jsoup#2071]
### Context:
https://github.com/seazon/FeedMe/issues/659

### Related page url:
https://rustsec.org/advisories/RUSTSEC-2023-0070.html

### Description:
FeedMe use `Jsoup.parse(html)` to get DOM, and then do some format base on the DOM.

In this issue case, `<Box` in `code` tag was parsed as a `box` tag.
Is there any way to avoid this error?

**Comment by jhy** [comment]
I can't repro. The current content of that URL does not contain the literal `<box`. See https://try.jsoup.org/~Ef66zmmWJXajZQ2vAVwWO4XoQpg

It does contain:

```html
<code>type Dependent&lt;'a&gt; = RefCell&lt;Box&lt;dyn fmt::Display + 'a&gt;&gt;</code>.
```

Which jsoup parses the text content of as:

`type Dependent<'a> = RefCell<Box<dyn fmt::Display + 'a>>`

Which is correct.

If the HTML contained the literal `<box`, it would be treated as an (unknown) tag, per the HTML5 spec.

**Comment by seazon** [comment]
Find the reason, I use `textNode.getWholeText()` to get the string of `TextNode`, this method will return the `value` which convert `&lt;` to `<`. Now I use `textNode.outerHtml()`, then everything is ok.
