### ISSUE TITLE
Add a `[*]` any attribute selector

### ISSUE THREAD

**Issue by eljosemari** [jhy/jsoup#2079]
Hello,

Using selector: .select("p:not([^])") as recommended, and probably working in that version, in https://stackoverflow.com/questions/32623325/getting-element-with-no-attributes-using-jsoup is giving this exception with the last version.

```
<html>
 <head></head>
 <body>
  <div id="intro">
   <h1 class="some class">
    <p id="some_id">Some text 1</p>
    <p name="some_name">Some text A</p>
    <p data>Some text B</p>
    <p>Some text 2</p></h1>
  </div>
 </body>
</html>
```

```
org.jsoup.nodes.Document docc = Jsoup.parse(html);
org.jsoup.select.Elements els = docc.select("p:not([^])");
for (org.jsoup.nodes.Element el:els){
System.out.println(el.text());
}
```

Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: String must not be empty
	at org.jsoup.select.QueryParser.parse(QueryParser.java:48)
	at org.jsoup.select.QueryParser.not(QueryParser.java:433)
	at org.jsoup.select.QueryParser.parsePseudoSelector(QueryParser.java:216)
	at org.jsoup.select.QueryParser.consumeEvaluator(QueryParser.java:179)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:75)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:46)
	at org.jsoup.select.Selector.select(Selector.java:98)
	at org.jsoup.nodes.Element.select(Element.java:452)

Using xpath selector the result is ok but I think that performance is very bad:
.selectXpath("//p[not(@*)]")

It is possible to get the same result using css selector or jsoup selector?

Thanks in advance.

**Comment by jhy** [comment]
Interesting, the `[^]` was relying on the `attribute name starting with` selector and using an empty string.

Probably best to add an explicit `[*]` operator that looks for >0 attributes.

**Comment by eljosemari** [comment]
Hello,

Te result of:

```
org.jsoup.nodes.Document docc = Jsoup.parse(html);
org.jsoup.select.Elements els = docc.select("p:not([*])");
for (org.jsoup.nodes.Element el:els){
System.out.println(el.text());
}
```

is all 'p' elements:

```
Some text 1
Some text A
Some text B
Some text 2
```

Thanks in advance.

**Comment by jhy** [comment]
Yes, sorry, I mean to say it will be best if we add a new selector `[*]` to explicitly find elements with > 0 attributes. It's not supported currently.

**Comment by jhy** [comment]
OK, now `[*]` and `[^]` work. I added and documented `[*]` as it's functionally clearer, IMHO.
