### ISSUE TITLE
Add export to w3c DOM - DocumentFragment

### ISSUE THREAD

**Issue by hsn10** [jhy/jsoup#209]
Currently jsoup is using its own DOM model. This makes integration with other tools coded to work above w3c DOM model difficult. I can not just swap current HTML parser for jsoup and see difference.

I propose to add utility class which will take JSOUP document and DocumentFragment as arguments and it will convert jsoup document to provided documentfragment.

**Comment by dminkovsky** [comment]
+1, maybe just add this right into jsoup.

**Comment by dminkovsky** [comment]
https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/W3CDom.java

**Comment by jhy** [comment]
Thanks. Yes, per @dminkovsky I have been implementing a w3c dom / jsoup dom converter. Keen to get feedback on that. I'll close this bug as the concept is implemented.

**Comment by dminkovsky** [comment]
@jhy Code made sense and worked for me, though I didn't test it extensively.
