### ISSUE TITLE
Parsing a part of an html string

### ISSUE THREAD

**Issue by 821938089** [jhy/jsoup#2093]
I only need something in the head tag of the document, which is a very small part of the document, but I need to parse the whole document to get it, which wastes a lot of time and memory.

What I imagine the API to look like:
```java
Jsoup.parseLazy(html).selectFirst("head")
```

**Comment by jhy** [comment]
Thanks for the suggestion. I have an idea for an implementation for something like this in #2003.

**Comment by jhy** [comment]
I've built out a new feature -- StreamParser -- that should address this. Take a look at the examples in #2096. Would be great if you can give it a try!
