### ISSUE TITLE
Minor performance optimizations

### ISSUE THREAD

**Issue by 821938089** [jhy/jsoup#2098]
https://github.com/jhy/jsoup/blob/2b443dff8770a97fe6f2a49db88f58e30b84abc6/src/main/java/org/jsoup/parser/HtmlTreeBuilder.java#L393-L395

`el.hasAttr` takes a bit of time to execute, which is unnecessary.

**Comment by jhy** [comment]
Cool, can you provide a PR and a benchmark?

**Comment by 821938089** [comment]
I opened a PR. 
https://github.com/jhy/jsoup/pull/2099

**Comment by jhy** [comment]
Thanks merged, as noted.
