### ISSUE TITLE
add raw data option  / raw body for POST

### ISSUE THREAD

**Issue by renkeee** [jhy/jsoup#210]
It would be nice to have a "add raw data to body-option" to be more flexble with a issue like multipart/form-data.
Enabling you to add an individual raw string to the body.

PS
My attempt to work around that issue in splitting a string at the equals sign and put both halfs in  .data() was ruined by the urlencoding.

**Comment by renato2099** [comment]
Hey guys, yeah it is very annoying having such a great library but so limited at the same time!
If you could provide some tips on where to start, I would also like to chim in

**Comment by jhy** [comment]
Implemented some time back in Connection.Request.requestBody(String)
