### ISSUE TITLE
Force JSoup to ignore custom HTML tags

### ISSUE THREAD

**Issue by SkyAphid** [jhy/jsoup#2101]
I'm working with some code that is parsing HTML. This API has worked great so far for being able to dig the data I need out and easily read it, but I've ran into an issue where JSoup is inserting html into the text where it's not wanted or needed. This is supposedly a feature, but unfortunately it's completely ruining my entire implementation.

Here is the text:
`<u>Oh, hello! You must be the person I've been waiting on all morning. </u><strong><u>You wouldn't happen to be <player> would you?</u></strong>`

It's pretty normal outside of the custom <player> tag that's been added. The program is meant to parse that itself and change it into a name. I had presumed that if JSoup did not recognize a tag, it would leave it alone. But instead, it's mangling the text into this:

```
Oh, hello! You must be the person I've been waiting on all morning. You wouldn't happen to be <player>
    would you?
  </player></u></strong> <player>
```

It seemingly even adds a line break for some reason, and then also randomly adds another player tag onto the end, which confuses the system even more.

Is there a way to toggle this functionality off entirely, and have JSoup stick to tags it specifically recognizes? I'd like to solve this, since if I can't keep our custom tags formatted like html tags, then I'll have to write a whole other system to parse a different format with something like` [[]]`, which would be a bit redundant.

Also, just to clarify, all I want is for JSoup to ignore my custom tag entirely. I essentially want it to stay in its own lane and only parse pure HTML, and then ignore anything that isn't.

Thank you for your time.

**Comment by m-heider** [comment]
The reason for this behavior is that your HTML is invalid. 

Any tag must have an end tag, aside from a few exceptions listed here: 
https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

Also, custom elements must contain a hyphen (e.g ```<a-player>```) but JSoup does not seem to enforce this.
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts

I am not aware of any setting that ignores custom tags but there are two other options:

1) You escape the angle brackets in ```<player>```:

```
org.jsoup.nodes.Document doc;
String output;
org.jsoup.nodes.Document.OutputSettings outputSettings;

doc = Jsoup.parse("""
                  <!DOCTYPE html>
                  <html lang="en">
                    <head><title>Title</title></head>
                    <body>
                      <u>Oh, hello! You must be the person I've been waiting on all morning. </u><strong><u>You wouldn't happen to be &lt;player&gt; would you?</u></strong>
                    </body>
                  </html>
                  """);

output = Parser.unescapeEntities(doc.select("body").html(), true);
```

Output:
```
<u>Oh, hello! You must be the person I've been waiting on all morning. </u><strong><u>You wouldn't happen to be <player> would you?</u></strong>
```

2) You deal with the end-tag in your program, disable the additional line breaks in JSoup and hope that future versions of JSoup will neither enforce the rules about end tags nor hyphens in custom elements:

```
org.jsoup.nodes.Document doc;
String output;
org.jsoup.nodes.Document.OutputSettings outputSettings;

doc = Jsoup.parse("""
                  <!DOCTYPE html>
                  <html lang="en">
                    <head><title>Title</title></head>
                    <body>
                      <u>Oh, hello! You must be the person I've been waiting on all morning. </u><strong><u>You wouldn't happen to be <player> would you?</u></strong>
                    </body>
                  </html>
                  """);
                  
outputSettings = new org.jsoup.nodes.Document.OutputSettings();
outputSettings.prettyPrint(false);
doc.outputSettings(outputSettings);

output = doc.select("body").html().trim();
```

Output:
```
<u>Oh, hello! You must be the person I've been waiting on all morning. </u><strong><u>You wouldn't happen to be <player> would you?</player></u></strong>
```

**Comment by SkyAphid** [comment]
Thank you for the input.  I was aware that it required an endpoint since it was being considered an HTML tag. What was I hoping for is that this project could potentially be updated so that there was an option to set it to ignore certain strings, but I knew that was a bit much ask. I was able to work around it in my program thankfully and circumvent the entire thing.

**Comment by jhy** [comment]
@SkyAphid the parser code is mostly in [HtmlTreeBuilder](https://github.com/jhy/jsoup/blob/1f1f72d1e89821c630dcfc35e1a0a7f653cc877b/src/main/java/org/jsoup/parser/HtmlTreeBuilder.java#L30) and the surrounding classes. 

@m-heider thanks for your comments. One point - I don't think this is a custom element per se. It's just an "ordinary" element - the parser follows the flow defined in the [Parsing](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody), and it gets treated as "Any other start tag". And jsoup defaults these unknown elements to block elements.

It's working to spec and to how browsers parse it, so I don't intend to change the behavior. It's not applying an error correction so there's no specific block of code that would make sense to disable.

**Comment by SkyAphid** [comment]
It's fine. I just wrote the functionality into the source myself months ago. Have a nice day guys!
