### ISSUE TITLE
Empty HTML tags are not removed by .text()

### ISSUE THREAD

**Issue by henricook** [jhy/jsoup#2102]
This unit test (scalatest) fails:

```scala
      "work on empty tag content" in {
        val input    = "< />"
        val expected = ""

        val parsed = Jsoup.parse(input).text()

        parsed should be(expected)
      }
```

The output of `Jsoup.parse(input).text()` is `< />`

I think I'd expect this empty HTML tag to be removed - WDYT?

Edit: I appreciate this isn't really a valid HTML tag and you would be well within your rights to tell me it's out of scope for Jsoup as a result!

**Comment by jhy** [comment]
Hi -- the current behavior is correct per jsoup's goal of matching the HTML5 spec, and of parsing as current browsers do.

Specifically, the space character after the tag open is an error (which jsoup emits if you have tracking on) which is recovered by treating the tag open as the "<" character.

See: https://try.jsoup.org/~t-TATJuCSw3Cry1b7naUfOZdKm0 and https://html.spec.whatwg.org/multipage/parsing.html#tag-open-state

Verified that Chrome does the same.

It makes sense to me to implement it this way - it's a common authoring error that people write something like "3 is < 5".

**Comment by henricook** [comment]
Thanks for your time Jonathan
