### ISSUE TITLE
text() is missing a separator space between <button> text nodes

### ISSUE THREAD

**Issue by KennyWongPFPT** [jhy/jsoup#2105]
Hello,

```
Jsoup.parse("<html><button>Reply</button><button>ReplyToAll</button></html>").text();
```
When trying to grab `text()` from this test case, we get `"ReplyReplyToAll"` (expecting `"Reply ReplyToAll"`). Notice that a separator space is missing between the two text nodes `Reply` and `ReplyToAll`. Would it be possible to get a fix for this?

Thank you.

**Comment by MasterChiefNemo** [comment]
What class is this specifically?

**Comment by jhy** [comment]
Thanks, have implemented this. Per the spec it's an inline tag which doesn't really require spaces to be added, but given how browsers render it, I think it makes sense.
