### ISSUE TITLE
Some html tags didn't support by Jsoup?

### ISSUE THREAD

**Issue by spl1nt3r99** [jhy/jsoup#2107]
I am trying to parse html with css code and get some problems.

I've encountered an issue where I am unable to round the corners of the `img` using `border-radius: 50%;`. Additionally, `object-fit: cover;` doesn't seem to work.
The same problem persists with `display: flex;`.

Is there a possible solution to address this?

**Comment by MasterChiefNemo** [comment]
@spl1nt3r99 has anyone provided a solution and pull request for this yet? What output are you expecting from a solution?

**Comment by jhy** [comment]
Closing - incomplete report.
