### ISSUE TITLE
parser fails on simple html page

### ISSUE THREAD

**Issue by soulrebel** [jhy/jsoup#212]
to reproduce:
jsoup 1.6.3, 
parsing the url:
http://www.intesys-srl.it/

the tree obtained is void of any content. It seems like some weird character is not handled properly

// code snippet:
			Document doc = Jsoup.connect(url).timeout(CONNECT_TIMEOUT)
					.userAgent(SPOOFED_USER_AGENT).followRedirects(true).get();
			System.err.println(doc);

// printed output (probably changed by escaping in this form):
<html>
 <head></head>
 <body>
  ��&lt;
 </body>

**Comment by jhy** [comment]
This one was fixed a while back
