### ISSUE TITLE
Missing class when building release on Android in 1.17.2

### ISSUE THREAD

**Issue by akirmse** [jhy/jsoup#2129]
I've just upgraded from jsoup 1.15.4 to 1.17.2.  When building in release mode for Android (Gradle 8.3), I get the following build error:

Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/akirmse/peakbagger/android/peakbagger/build/outputs/mapping/release/missing_rules.txt.
Missing class org.jspecify.annotations.NullMarked (referenced from: org.jsoup.internal.FieldsAreNonnullByDefault and 2 other contexts)

Adding this to my proguard.txt file fixes the problem:
-dontwarn org.jspecify.annotations.NullMarked

but it would be better if the library could take care of this instead.

**Comment by jhy** [comment]
As far as I can tell (reading through the issue @cpovirk linked in), this is an issue of proguard complaining about provided dependencies. And so not something for jsoup is placed to fix.

Alternatively to flagging it as don't warn, I expect you could add the dependency to your pom:


```xml
    <dependency>
      <!-- org.jspecify.annotations.nonnull, with Apache 2 license. Build time only. -->
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
      <version>0.3.0</version>
    </dependency>
```
