### ISSUE TITLE
nested :has() selector not working [v1.17.2]

### ISSUE THREAD

**Issue by ogolovanov** [jhy/jsoup#2131]
Hi.

It seems nested :has() selectors not working.

```
String html =
    "<html>" +
        "<head></head>" +
        "<body>" +
            "<div>" +
                "<div><span>hello</span></div>" +
                "<div><span>world</span></div>" +
            "</div>" +
        "</body></html>";
Document document = Jsoup.parse(html);

System.out.println(document.select("div:has(> div:has(> span) + div:has(> span))").size());
System.out.println(document.select("div:has(> span) + div:has(> span)").stream().filter(v -> v.parent().is("div")).count());
```

Result:
> 0 // = unexpected
> 1 // = as expected

**Comment by jhy** [comment]
General nested `:has()` selectors do work - we have tests here: https://github.com/jhy/jsoup/blob/c3963d4bb19414d56f42986db96d62208309e748/src/test/java/org/jsoup/select/SelectorTest.java#L577-L594

I thought this might be related to #2137, but it doesn't seem to be.

But, your selector doesn't work in Chrome either.

So I'm not 100% sure here...

**Comment by ogolovanov** [comment]
Yes, on one hand - nested :has() is not supported by browsers

> The :has() pseudo-class cannot be nested within another :has(). This is because many pseudo-elements exist conditionally based on the styling of their ancestors and allowing these to be queried by :has() can introduce cyclic querying

On the other hand - "pseudo-elements problem" is a problem for browsers, but not for jsoup
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

Anyway, it would be nice if you could fix it.

**Comment by jhy** [comment]
Looking at it some more. I don't think it's specifically the nested has.

The query can be simplified to:
`div:has(>div + div)`

which fails (yet works in browsers). Both `div:has(div + div)` and `div:has(>div)` work.

https://try.jsoup.org/~0Imle8wRufxJsGLk0Lt2ReHywC8

So there is an incorrect interaction between the ImmediateParentRun and the ImmediatePreviousSibling, somehow.

**Comment by jhy** [comment]
Actually, my reduction of the issue found the same as #2187, but the initial report is something different.

**Comment by jhy** [comment]
`div:has(div:has(span) + div:has(span))` works OK (now) -- without the `>` direct child of. The direct child of is not taking the appropriate (?) root.

**Comment by jhy** [comment]
OK, fixed! Thanks for the report. It wasn't the root being incorrect, it was re-use of the inflight Element Iterator that was trashing the match.
