### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by FOnlyJack** [jhy/jsoup#2136]
The content structure of the URL parsed for the first time after the application is uninstalled is different from that of the URL parsed without the application being uninstalled

**Comment by jhy** [comment]
I don't follow what you mean. You said "uninstalled" twice - do you mean installed vs uninstalled?

But, jsoup is not an installable application. It's an SDK. Provided the same input, the parse tree is deterministic. So I can only guess that somehow your application (?) is getting different input.

Can you provide a simple repeatable testcase, to progress this report?

**Comment by jhy** [comment]
¯\\\_(ツ)\_/¯
