### ISSUE TITLE
MalformedURLException in redirection URL

### ISSUE THREAD

**Issue by RUSLAN-SIMAKOV** [jhy/jsoup#2142]
I'm using URL: https://chrome.google.com/webstore/detail/someAppName/mopnmbcafieddcagagdcbnhejhlodfdd?hl=en
but JSoup can not process redirected URL:
`MalformedURLException: Illegal character in path at index 49: https://chromewebstore.google.com/detail/polkadot{js}-extension/mopnmbcafieddcagagdcbnhejhlodfdd?hl=en`

version JSoup 1.7.2

**Comment by RUSLAN-SIMAKOV** [comment]
also expirienced issue with '<', '>',  '%' in redirecting URLs

**Comment by jhy** [comment]
Thanks, fixed.
