### ISSUE TITLE
cssSelector has a problem with '<div data-v-7a225e99="" class="flex-center gap-[12px]">'

### ISSUE THREAD

**Issue by 666asd** [jhy/jsoup#2146]
The page contains such elements `<div data-v-7a225e99="" class="flex-center gap-[12px]">`.
It seems to be caused by a difference in the handling of "\" by the two functions.
org.jsoup.select.QueryParser#consumeSubQuery
org.jsoup.parser.TokenQueue#chompBalanced
![image](https://github.com/jhy/jsoup/assets/16465586/e8e9dff7-5d75-4426-97b1-2a94870227cd)
![image](https://github.com/jhy/jsoup/assets/16465586/dc0e6859-c26f-4f18-b568-6fa1ccd79fb7)
![image](https://github.com/jhy/jsoup/assets/16465586/414b178c-23d0-4c25-ac19-23a4e89b9c86)

**Comment by jhy** [comment]
Can you provide a small test case that demonstrates what you're trying to do and what you expect?

**Comment by 666asd** [comment]
An error will be raised when getting the cssSelector of the element.

```java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;


public class Demo {
    public static void main(String[] args) throws Exception {
        String html = "<html>\n" +
                "\n" +
                "<head>\n" +
                "  <title>Jsoup Example</title>\n" +
                "</head>\n" +
                "\n" +
                "<body>\n" +
                "  <div data-v-7a225e99=\"\" class=\"flex-center gap-[12px]\">\n" +
                "</body>\n" +
                "\n" +
                "</html>";
        Document doc = Jsoup.parse(html,"UTF-8");

        doc.getElementsByTag("div").first().cssSelector();

    }
}

```
```
Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at '12px\]'
	at org.jsoup.select.QueryParser.parse(QueryParser.java:48)
	at org.jsoup.select.Selector.select(Selector.java:101)
	at org.jsoup.nodes.Element.select(Element.java:474)
	at org.jsoup.nodes.Element.cssSelectorComponent(Element.java:950)
	at org.jsoup.nodes.Element.cssSelector(Element.java:928)
	at Demo.main(Demo.java:21)
```

**Comment by 666asd** [comment]
This seems to be the syntax in tailwindcss.
https://tailwindcss.com/docs/gap
![image](https://github.com/jhy/jsoup/assets/16465586/378ffd48-d302-4260-95b7-ac3587a523ec)

**Comment by jhy** [comment]
Thanks, actual code is worth a thousand pictures :)

**Comment by jhy** [comment]
Thanks, fixed.

This fixes the case that `consumeSubQuery()` didn't handle escape chars.

Per #1998, we also can do a better job of making the escapes, in the first place.
