### ISSUE TITLE
tagName:eq(i) selects i-th element regardless of tagName

### ISSUE THREAD

**Issue by sdrab** [jhy/jsoup#216]
Used JSoup 1.6.2 + 1.6.3 with JUnit4:

```
@Test
public void TestDivs() {
    testStructure("<html><head></head><body><div>TestDiv1</div><div>TestDiv2</div></body></html>");
    testStructure("<html><head></head><body><div>TestDiv1</div><script>alert('Testing Alerts!');</script><div>TestDiv2</div></body></html>");
    testStructure("<html><head></head><body><span>LeadingSpan</span><div>TestDiv1</div><div>TestDiv2</div></body></html>");
}

private void testStructure(String htmlString) {
    Document doc = Jsoup.parse(htmlString);
    assertTrue(doc.select("html").size()>0);
    assertTrue(doc.select("html>body").size()>0);
    assertTrue(doc.select("html>body>div:eq(0)").size()>0);
    assertTrue(doc.select("html>body>div:eq(1)").size()>0);
    assertTrue(doc.select("html>body>div:eq(2)").size()==0);
    assertEquals("TestDiv1", doc.select("html>body>div:eq(0)").text());
    assertEquals("TestDiv2", doc.select("html>body>div:eq(1)").text());
}

private String example = "<html><body><div>1</div><span>2</span><div>3</div></body></html>";
```

Problem seems to be inside the call of the matches-Method in org.jsoup.select.CombiningEvaluator:47

Apperently the index in the tagName:eq(i)-selector references the i-th element regardless of the tagName. 

See the example variable in the above code :
html>body>div:eq(1) selects the span (child index 1) here, the tag name does not match => no element found:
html>body>div:eq(2) should not be existent, because we only have 2 divs, but it selects the second div (child index 2) with the innerHTML "3" because it only counts the child index without checking for the tag-name (span/div).

:eq is partially implemented like :nth-child and partially like :nth-of-type

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
