### ISSUE TITLE
Matching error with getElementsMatchingText()

### ISSUE THREAD

**Issue by nbxiglk0** [jhy/jsoup#2163]
Hi，
When i want to get Elements through regex pattern，The matching result is inconsistent with the expectation.
for example, this is my test code 
```java
public class HtmlParse {

    public static void main(String[] args) throws IOException {
        Document doc = Jsoup.connect("http://127.0.0.1:8090/test.php?q=aa&w=test&e=aa&r=aaa&t=aa").get();
        String html = doc.html();
        System.out.println(html);
        final String regex = ">.*test.*<";
        final Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE);
        Elements element =   doc.getElementsMatchingText(pattern);
        if (!element.isEmpty()){
            element.stream().forEach(System.out::println);
            }
        else {
            System.out.println("Dont find any element");
            }
        }
    }
```
the html response is 
```html
<html>
 <head></head>
 <body>
  <a href="?q=1&amp;w=2&amp;e=3&amp;r=4&amp;t=5"></a>
  <script>
var a = "aa";</script> aa
  <div>
   <textarea>test</textarea>
  </div><input style="color:aa" value="aaa"> <!--
        this is comment
        aa        -->
 </body>
</html>
```
i want get the textarea element by match `">.*test.*<"`，but i got nothing，Is there anything wrong with getElementsMatchingText method?   
![image](https://github.com/jhy/jsoup/assets/24366795/a059f434-5564-403a-9310-1e21666290e6)

**Comment by jhy** [comment]
Well, note that [getElementsMatchingText](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#getElementsMatchingText(java.util.regex.Pattern)) runs the regex against the parsed [text()](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#text()) of elements, not the original HTML source.

In your parsed DOM tree, you have element nodes (e.g. `textarea`) which contain text nodes (e.g. `test`). So there are no `><` characters to match in the `>.*test.*<` regex.

Also note the difference between `getElementsMatchingText` and `getElementsMatchingOwnText`: the former uses `text()` which includes textnodes of the element and its descendants; whilst the latter uses [`ownText()`](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#ownText()) which includes only the element's directly owned textnode(s).

I would suggest doing something like:

```java
String regex = ".*?test.*?";
String selector = String.format("textarea:matchesWholeOwnText(%s)", regex);
Elements els = doc.select(selector);
```

Or if you prefer:

```java
String regex = ".*?test.*?";
Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE);
Elements els = doc.getElementsMatchingOwnText(pattern);
els.forEach(element -> {
    if (element.nameIs("textarea")) {
        System.out.println("matched");
    }
});
```

Both of those find the `textarea` matching the corrected regex.

Hope this helps!
