### ISSUE TITLE
`:not(:has(` and `:has(:not(` are different

### ISSUE THREAD

**Issue by kvtb** [jhy/jsoup#2166]
`:not(:has(` and `:has(:not(` work differently

actually, only `:not(:has(` does what is expected, while `:has(:not(` work exactly as `:has(`, ignoring the negation introduced by `:not(`

**Comment by jhy** [comment]
Can you give an example of each case and show what you expect vs what you get?

I'm trying both cases here: [`:not(:has)`](https://try.jsoup.org/~G-6Ehb7DDE7gEEGm2w-fHaK0n60) and [`:has(:not)`](https://try.jsoup.org/~1-f-Vsdwpo5JtRpizoFDoxKVL3U) and they appear OK there.

Source is here if you want to review & debug: https://github.com/jhy/jsoup/blob/970403cfb442d8c835c83e8f85b9384eb2f34390/src/main/java/org/jsoup/select/StructuralEvaluator.java#L129 and https://github.com/jhy/jsoup/blob/970403cfb442d8c835c83e8f85b9384eb2f34390/src/main/java/org/jsoup/select/StructuralEvaluator.java#L53

**Comment by kvtb** [comment]
```scala

import `org.jsoup:jsoup:1.17.2`, org.jsoup.Jsoup

object Test {
  def main(args: Array[String]): Unit = {
    val doc1 = Jsoup.parse("""<div id="jwplayer-1"> <div> <div class="jw-preview"/> </div> </div>""")

    println("1:" + doc1.select("""[id="jwplayer-1"]:not(:has([class*="jw-preview"]))"""))
    println("2:" + doc1.select("""[id="jwplayer-1"]:has(:not([class*="jw-preview"]))"""))
  }
}
```
