### ISSUE TITLE
Provide Package with just parsing (without HTTP capabilities)

### ISSUE THREAD

**Issue by davidvedvick** [jhy/jsoup#2180]
As an Android application developer, I would like a JSoup package with just the **parsing capabilities**, so that I don't include unnecessary dependencies in my application.

In my case, HTTP fetching is already tightly controlled by OKHttp, so adding in another library that has the ability to create HTTP connections 1) adds to developer confusion and 2) adds a lot of code into the application that won't be used (hopefully R8/Proguard will trim it, but I did notice a pretty big jump in binary size after including this package).

**Comment by jhy** [comment]
I took a look at what practical difference this would make to the JAR size:

Filename | Size (KB)
-- | --
Connection.class | 3.4
Connection$Request.class | 1.9
Connection$Method.class | 1.5
Connection$Base.class | 1.5
Connection$Response.class | 1.1
HttpConnection$Response.class | 23.6
HttpConnection$Request.class | 10.3
HttpConnection$Base.class | 8.3
Misc | 2
  |  
Total HTTP files (unpacked) | 53.6
Total all (unpacked) | 860.6
Relative size | 6.23%
  |  
Compressed total | 453
Ratio | 1.900
HTTP (packed) size | 28.214
Mooted package size | 425
Reduction | 6.23%

A reduction of 6% of the compressed size of the jar doesn't strike me as worth the complexity of publishing another version of the library. It is a perfect use case for using proguard to strip the files that you don't need for your own specific use case. There are probably other files you're not using which you could also remove for a larger saving.

The actual total size is probably smaller again, as when deployed on Android the dex re-packaging of the jar further minimizes the deployed size.

Also note that the HttpConnection code in jsoup is implemented as a wrapper over the platform's HTTP code, with the goal of providing an API that is more ergonomic to use within the context of jsoup. The fetching and parsing of web content is core functionality for jsoup, hence why I don't consider them seperate packages.
