### ISSUE TITLE
jsoup 请求获得的html页面不完整，静态页面的a标签href 属性和类名link消失

### ISSUE THREAD

**Issue by zengjun11** [jhy/jsoup#2193]
这是jsoup得到的
![image](https://github.com/user-attachments/assets/90b7987e-9326-44e5-8060-4ce8c9e01b95)
下面是源代码的
![image](https://github.com/user-attachments/assets/313c2521-7544-4063-899c-28dd878a84d1)

**Comment by zengjun11** [comment]
上面是jsoup get请求解析出来的， 下面是浏览器页面源代码的

**Comment by zengjun11** [comment]
下面是ctrl u 看到的源代码

**Comment by jhy** [comment]
Sorry, but reports need to be in English. Take a look at #2149, possibly relevant.
