### ISSUE TITLE
Element.attr("srcset") method only picks up a single value for a potentially multi-valued attribute

### ISSUE THREAD

**Issue by christianleger** [jhy/jsoup#2196]
Greetings, 

As described here: 

https://html.spec.whatwg.org/#srcset-attributes

A `source` tag can have a multi-valued attribute `srcset`. 

To illustrate, a picture element can look like this: 

```
        <picture>
            <source srcset="pic1.jpg","pic2.jpg" />
            <img> ...
        </picture>
```

Now the issue I'm experiencing: when I use JSoup (currently on 1.17.2), obtaining the `srcset` attribute value from the element `source ` returns pic1.jpg but not pic2.jpg. This seems like a bug to me. If not maybe someone can point me to correct usage in this scenario.

**Comment by jhy** [comment]
Hi,

I think you're misreading the spec. srcsets aren't like your example; that's invalid HTML. A srcset attribute is still a regular HTML attribute and there are no specific rules in the tokenizer or parser phase. It's the contents of the attribute that follow the spec you linked. 

An actual example is:

```html
<picture>
  <source srcset="logo.png, logo-1.5x.png 1.5x" />
  <img src="logo.png" alt="MDN Web Docs logo" height="320" width="320" />
</picture>
```

or

```html
<img
  srcset="logo.png, logo-2x.png 2x"
  src="logo.png"
  height="320"
  width="320"
  alt="MDN Web Docs logo" />
```

Those examples are from Mozilla's [`picture`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element documentation.

You can see that jsoup [parses that correctly](https://try.jsoup.org/~OU4BPKxFnKwjlgH5JyJ2uNq6vLw).

To do something with the value of the attribute (which will be `logo.png, logo-2x.png 2x`), you will need to parse it according to the [srcset](https://html.spec.whatwg.org/#srcset-attributes) spec.

Hope this helps!

**Comment by christianleger** [comment]
Thank you @jhy that does clarify things a bit. I'm still unsure how I can ever see both of the pictures specified in a single attribute line (it has to do with screen resolution or dimensions?) but after rereading the spec I agree with your interpretation. Thank you for taking the time to respond.

**Comment by jhy** [comment]
Yes, a `srcset` lets you define multiple source images for one HTML element. The browser then chooses which of those to render at a given time, based on the device's pixel density, and/or the current layout.

Conceptually, they achieve a similar outcome to mipmap image textures in 3D: keep the dimensions of the image that is loaded in memory as close to the render dimensions as possible. That keeps scaling (up or down) artifacts to a minimum, and optimizes CPU / memory consumption.

For example, I'm using them in an app I'm building for document navigation and reading. A page is displayed with a srcset of say 8 size variations ranging from 128px to 2048px wide. Depending on the pixel density of the screen, and how wide the reading pane is set, the browser will fetch, render, (and cache) the best fitting image. If the user then resizes the pane, that loaded image will be scaled minimally until another instance in the set is a better fit.

The MDN page [Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images has more details and examples.
