### ISSUE TITLE
euro and apos character lost after parsing

### ISSUE THREAD

**Issue by ysimonx** [jhy/jsoup#220]
Hello

i've got some problem with this url
http://www.rueducommerce.fr/Equipement-Automobile-GPS/Assistant-d-aide-a-la-conduite-et-GPS/GPS/TOMTOM/4838275-GPS-TomTom-XXL-IQ-Routes-42-pays-grand-ecran-5.htm

parsing & euro ; is ok 
( 114,95 & euro ; )

however, there is in the html source code "137,95 €"

which jsoup convert into "137,95 ?"

 d'Europe occidentale et d'Europe de l'Est 
is also converted into
 d?Europe occidentale et d?Europe de l?Est 

the character hex 27 is ' and is ok with jsoup
the character hex 92 is also ' and is not ok with jsoup

the character hex 80 for "euro" is not ok with jsoup 
how can i manage this please ?

here is the source code i made

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public class jsoupeuro {

	public static void main(String[] args) {
		try {
			Document doc = Jsoup.connect("http://www.rueducommerce.fr/Equipement-Automobile-GPS/Assistant-d-aide-a-la-conduite-et-GPS/GPS/TOMTOM/4838275-GPS-TomTom-XXL-IQ-Routes-42-pays-grand-ecran-5.htm").get();
			System.out.print(doc.html());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}

**Comment by jhy** [comment]
No problems with encoding. Possibly there was a bug, or your console was not outputting correctly.
