### ISSUE TITLE
Non-terminated HTML Entities are not recognized properly

### ISSUE THREAD

**Issue by Muthukirthan** [jhy/jsoup#2207]
# Case1
**Input:** `<p>a&nbspc</p>`
**Brower result:** `a c`
`&nbsp` is recognized as `&nbsp;` html entity

**Jsoup parsed content:** `<p>a&amp;nbspc</p>`
**Brower result:** `a&nbspc`
`&nbsp` is not recognized which shows different result in browser

---

# Case2
**Input:** `<p>a&nbsp&shyc</p>`
**Brower result:** `a ­c`
`&nbsp` and `&shy` is recognized as `&nbsp;` and `&shy;` respective html entity

**Jsoup parsed content:** `<p>a&nbsp;&amp;shyc</p>`
**Brower result:** `a &shyc`
`&nbsp` is recognized (might be due to succeeding & character), but `&shy` is not recognized as `&shy;`. Shows different result in browser

---

# Case3
**Input:** `<p>a&shyc&nbsp</p>`
**Brower result:** `a­c `
`&nbsp` and `&shy` is recognized as `&nbsp;` and `&shy;` respective html entity

**Jsoup parsed content:** `<p>a&amp;shyc&nbsp;</p>`
**Brower result:** `a&shyc `
`&nbsp` is recognized (as the string ends with that entity), but `&shy` is not recognized as `&shy;`. Shows different result in browser

---

On checking few more cases, this issue is seen only for named entities (like &nbsp;, &amp;, &quot;, and others) where the entity is not ended with semi-colon and followed by letters. Hexa-decimal entities and numeric entities are detected even if they are not ended with semi-colon.

Examples:
Proper detection as expected,
`&nbsp,ddd` (Expected `&nbsp;,ddd` , and got same results)
`&nbsp ddd` (Expected `&nbsp; ddd` , and got same results)
`djdjb&nbsp` (Expected `djdjb&nbsp;` , and got same results)

Invalid detections (ISSUES):
`&nbspdhdj` (Expected `&nbsp;dhdj` but got `&amp;nbspdhdj`)
`&ampdfgsj` (Expected `&amp;dfgsj` but got `&amp;ampdfgsj`)

Browsers are able to detect these html entities. Validated in https://mothereff.in/html-entities as well

Parser: Html parser
Escape mode: Same result for both `base` and `extended`. nbsp entity is replaced by `&#xa0;` in `xhtml` escape mode but the result is same

I also raised this doubt related to entity: https://github.com/jhy/jsoup/issues/2206

**Comment by jhy** [comment]
I guess the spec changed here a bit (https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state). jsoup actually used to work like that way back when. Will need to review.

**Comment by jhy** [comment]
Here's the change from when we used to look for the longest matching prefix: a31ec08e102fd3832f3ff4449e9163440f0afb2c

**Comment by jhy** [comment]
Thanks for the clear report! Fixed.
