### ISSUE TITLE
Invalid character in attribute name is replaced with underscore since 1.18.1

### ISSUE THREAD

**Issue by tomasbelusky** [jhy/jsoup#2216]
Hello,
I wanted to update jsoup to the latest version in our service but I came across this [issue](https://github.com/jhy/jsoup/issues/2143). Unfortunately, for our service and use cases it means a breaking change. I don't want to go into details but we basically have some memory which returns similarity of stored strings with the new ones. With this change we will no longer get expected 100% matching when the same document is uploaded into our system again because attributes are normalized in a different way, i.e. replaced with underscore instead of stripping.

Would it be possible to make this customizable by a client to decide what should happen with illegal characters in an attribute name?

Thanks,
Tomáš

**Comment by jhy** [comment]
It's possible, but I don't feel it's the best approach. The HTML produced was invalid, and outside of niche applications that's not useful.

But further, jsoup will continue to evolve and the exact format of the output HTML definitely will change over time. And I don't want to go down the path of adding complicated configuration to unwind every different change. The complexity of managing and testing all of that is unfeasible.

As an alternate approach, my suggestion would be that you store both the original input HTML and the jsoup produced HTML. When jsoup updates, reprocess the backlog using the original and store the new output. (And / or compare using the original input directly.)
