### ISSUE TITLE
XPath Selector Problems On Version 1.15.x+

### ISSUE THREAD

**Issue by lapperaoclc** [jhy/jsoup#2219]
Hey, 

I'm currently working on updating a project that is using version `1.14.3` of jsoup to the latest version. We have many xpaths that begin with `*//` in our application, and updating from version `1.14.3` to `1.15.x`+ causes elements not to be found when using `Element#selectXpath`. 

I have attached a project that reproduces this issue. 

There is a test in the project that attempts to use the following xpath `"*//div[@data-field=\"EXAMPLE\"]"` on the following HTML document:

```html
<div class="test">
    <div data-field="EXAMPLE">
        <div>
            Example test
        </div>
    </div>
</div>
```

On version `1.14.3` when the HTML test document is queried using xpath, the result is an elements object that contains an element for the div with the data-field attribute of EXAMPLE. On a higher version when the HTML test document is queried using xpath, the result is an elements object that has no elements. 

Is this desired behaviour between the versions and I'm missing something/some extra configuration? or is this something that has be unintentionally changed between versions?

Thanks!

[jsoupXPathProblems.zip](https://github.com/user-attachments/files/17492127/jsoupXPathProblems.zip)

**Comment by jhy** [comment]
Works for me in jsoup 1.18.1: see https://try.jsoup.org/~SP6F2x5iYB_7VjDR09B61GvaLkE

**Comment by lapperaoclc** [comment]
@jhy Hey!

Have you tried the sample project? 

I was able to download the sample project i created - update the version to `1.18.3` and see the test fail, where as it passes on version `1.14.3`.

The test simply does:

```java
      InputStream stream = getClass().getResourceAsStream("/test.html");
        Document document = Jsoup.parseBodyFragment(new String(stream.readAllBytes(), StandardCharsets.UTF_8));
        Elements elements = document.select(".test");

        elements.forEach(element -> {
            Elements elementsByXpath = element.selectXpath("*//div[@data-field=\"EXAMPLE\"]");

            assertFalse(elementsByXpath.isEmpty());
        });
```

I'm not sure if there's something i'm missing here - or if the `try.jsoup` page does something different compared to what is being illustrated in the sample project.

**Comment by jhy** [comment]
OK, reading the changelog for [1.15.1](https://jsoup.org/news/release-1.15.1), there is:

> Improvement: when evaluating an XPath query against a context element, the complete document is now visible to the query, vs only the context element's sub-tree. This enables support for queries outside (parent or sibling) the element, e.g. ancestor-or-self::*. [#1652](https://github.com/jhy/jsoup/issues/1652)

That change fixed up the context node that the xpath evaluator runs against and would be the cause of the difference you see here.

Because you're hitting `selectXpath` with a context element, the path is a bit different. There is nothing that will match the `*` wildcard then the `//` descender.

You could get rid of the wildcard and just use `//div[@data-field="EXAMPLE"]` or `div[@data-field="EXAMPLE"]` depending on what you want to match.

**Comment by lapperaoclc** [comment]
Okay cool - thanks for pointing to the relevant change in the log, I'll give it a shot :)
