### ISSUE TITLE
Entities.EscapeMode.none question

### ISSUE THREAD

**Issue by Arnauec** [jhy/jsoup#2223]
Hi @jhy and first of all thanks for the amazing work with the library.

I'm facing a situation where I would need the Entities.EscapeMode.none option.
In this [pull request](https://github.com/jhy/jsoup/pull/1832) you say:

> If you want plain text output, use one of the .text() methods. If one of those doesn't fit the use case, I'd be happy to hear more about the use case and we can explore ways to improve those.

I was using .text() until now, but I found a weird behaviour. If the input is something like:
`&lt;script src=\\\"https://xss.cacker.io/\\\"&gt;removed script &lt;/script&gt;`
Then JSoup will include it in the document, and when extracting the text we will get:
`<script src=\"https://xss.cacker.io/\">removed script </script>`

This 1) turns encoded-non dangerous input to input that could be dangerous, and most importantly 2) modifies user input. My goal would be to sanitize input but modify it as little as possible and only based on the data in the SafeLists. Data is not always outputted after using Jsoup, but sometimes also saved into a DB, and having encoded text is not desirable. 

I know JSoup tries to do both output encoding (with valid HTML) and input sanitization, but in my case I only need Input Sanitization, so it would be really great to have a flag that allows me to do that.

What could be a way to solve this issue I have? 
Thanks in advance.

**Comment by jhy** [comment]
But if you are taking the text() and storing it in a DB, and then show it to a user in a HTML context, you should escape the entities on output (because it's text, not HTML).

Or, use the html() and then you won't need to escape them. So, I think that is the path that most closely meets your ask - it's only doing sanitization.

If you treat text as text, and HTML as HTML, there is no need for a .none option. I won't ever add it.

**Comment by jhy** [comment]
The cleaner does clean. If you give it HTML that includes a script tag, it will remove it. `&lt;script&gt;` is not a script tag and has no danger to users. It is a textnode in HTML.
