### ISSUE TITLE
Improper Html closing tag results in addition of text nodes

### ISSUE THREAD

**Issue by Muthukirthan** [jhy/jsoup#2230]
Jsoup is not able determine improperly closed html tags.
For example, 
`<a> hello </a<` would result in `<a> hello </a>&lt;`
`<div> hello </div<>` would result in `<div> hello </div>&lt;&gt;`

Browsers will properly close the tags and does not add a `&lt;` or `&gt;` text nodes like Jsoup

**Comment by jhy** [comment]
See #797 - at that point we moved out of spec. But the spec used to add the `<` character as an attribute name, not to the tag name. https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state

Will review moving closer to spec and impact.

**Comment by jhy** [comment]
OK, I've aligned it to the current spec. That allows tag names like `a<b` (and you can see that in Chrome with HTML like `<div> hello </div<> <a>One<a<b>Hello</b>`). That's pretty gross IMO, but better for us to be consistent.

**Comment by jochenberger** [comment]
This change just pointed me to some invalid HTML that I was generating, so thanks! :slightly_smiling_face: 

I was generating (more or less) the following: 
```html
<table><th</></th></table>
```

1.18.1 turned that into
```html
<html>
 <head></head>
 <body>
  <table>
   <tbody>
    <tr>
     <th></th>
    </tr>
   </tbody>
  </table>
 </body>
</html>
```
Now, with 1.18.2, it get
```html
<html>
 <head></head>
 <body>
  <th< />
  <table></table>
 </body>
</html>
```
I assume that it's related to this change. I just wanted to make sure that the new behavior is expected.

**Comment by jhy** [comment]
Thanks @jochenberger -- yes that is what we would expect now. The previous #797 behavior was probably a better experience for this case, but ultimately lead to too much difference betwen browsers/spec and jsoup.

The `th<` tag is getting promoted ahead of the `table` tag in your instance due to the `table` parsing rules that move non-table elements out of the table.
