### ISSUE TITLE
Jsoup Proxy Authentication Fails: Auth Callback Not Triggered on macOS

### ISSUE THREAD

**Issue by capmorganbih** [jhy/jsoup#2233]
I can’t use a per-request proxy with Jsoup.
```
Connection s = Jsoup.newSession()
                .proxy("connect.net", 8080)
                .auth(auth -> {
                    if (auth.isServer()) { 
                        Validate.isTrue(auth.url().getHost().equals("example.com"));
                        return auth.credentials("username", "password");
                    } else { // auth.isProxy()
                        return auth.credentials("proxyUsername", "proxyPassword");
                    }
                });

s.newRequest("https://example.com/adminzone/").execute();
```

This code fails with a 407 Proxy Authentication Required, even though I’m using valid credentials. The key issue is that the auth callback does not get triggered at all

I’m running this on macOS

**Comment by capmorganbih** [comment]
@jhy could you please clarify what am I doing wrong?

**Comment by jhy** [comment]
Hi there,

The flow looks OK. Other than that, it is hard to debug with the information provided.

Did you follow the [implementation note for the Connection.auth()](https://jsoup.org/apidocs/org/jsoup/Connection.html#auth(org.jsoup.helper.RequestAuthenticator)) call -- particularly the System.setProperty to enable basic auth for TLS?

Is it a HTTP or a Socks proxy? What kind of auth is it using?

If setting the system property doesn't resolve the issue, next steps would be to step through the [openConnection()](https://github.com/jhy/jsoup/blob/8dec9c302e2f2d2b5560fefa0d3ed7e1b813e195/src/main/java/org/jsoup/helper/HttpConnection.java#L1081) flow and see why Java isn't calling into your auth function.

**Comment by capmorganbih** [comment]
@jhy yep, I forgot to enable basic auth for TLS. My fault, thank you
