### ISSUE TITLE
Cleaner removing Google Message IDs

### ISSUE THREAD

**Issue by Arnauec** [jhy/jsoup#2237]
Hi @jhy,
We are using JSoup in a service that handles emails.

Some endpoints send emails to users. One of the fields we send across in the case of a reply is the message ID from the third party. The problem is if the sender is using Google, the message ID is formatted as <[base64encodedbytes@mail.google.com](mailto:base64encodedbytes@mail.google.com)>. The sanitiser sees this field in our JSON request as an unsupported HTML tag and removes it.

E.g. we would expect this to go through: `<CA+_0EiqLn=pxe1XNSRJwEwV8EMuS4tJ--9R+RAoBX6UdaSLbJw@mail.gmail.com>`
In reality it doesn't.

Does the library have any configuration options to allow this to go through? Or the format itself is already dangerous and working as expected?

Thank you!

**Comment by jhy** [comment]
Hi, 

Can you attach a simplified code sample to demonstrate the issue? 

Generally, json should not be parsed as html, nor should a message ID be. But it would be good to see the specifics so that I can review.

**Comment by Arnauec** [comment]
This would be an example:
`public class Main {
    public static void main(String[] args) {
        // Example input with HTML tags
        String userInput = "<CA+_0EiqLn=pxe1XNSRJwEwV8EMuS4tJ--9R+RAoBX6UdaSLbJw@mail.gmail.com>";

        // Clean the input using JSoup's Safelist
        String cleanInput = Jsoup.clean(userInput, Safelist.basic());

        // Output the cleaned input
        System.out.println("Cleaned Input: " + cleanInput);
        // Prints: "Cleaned Input:"
    }
}`

**Comment by jhy** [comment]
Hi - I was hoping you might provide a bit more info in the sample as to what kind of input it is, and how you wanted it output. Are you processing email headers, is this in plain text, incorrectly in a HTML body, or what?

Given it's not HTML, perhaps parsing it with the HTML parser is not the right approach. If you have some text and you just want to output it in a HTML context, then a simple flow is:

```java
String inputText = "<CA+_0EiqLn=pxe1XNSRJwEwV8EMuS4tJ--9R+RAoBX6UdaSLbJw@mail.gmail.com>";
Element el = new Element("div").text(inputText);
System.out.println(el.html());
```

Giving the HTML:
```html
&lt;CA+_0EiqLn=pxe1XNSRJwEwV8EMuS4tJ--9R+RAoBX6UdaSLbJw@mail.gmail.com&gt;
```

If you have some input mess of HTML and those marked up elements and need to preserve them, you will probably want to pre-process the input and re-format them before running through the HTML parser and cleaner.

**Comment by Arnauec** [comment]
The info comes as a JSon body in a request. I parse the JSon Object and rebuild it with the cleaned values and then send it to a service which processes the body of the request and does stuff (e.g. save to a db, or render in a page). I'm using the HTML cleaner as I can't differentiate for the specific fields as the structure of the JSon might be different from request to request.

In general I always want to clean dangerous HTML tags and attributes and modify input as little as possible.

In this case, wouldn't this be considered a mistake by the cleaner, which should preserve the fields which are not html attributes?

**Comment by jhy** [comment]
No, I don't consider it a mistake. jsoup parses HTML according to the spec and browsers. You don't have HTML, and so it doesn't make sense to parse it as such.

If it were me, I would validate the json, store it as json, and then make a render time decision as to how it should be rendered on the client. If you don't know what your input is, I don't see how you can sensibly treat it as HTML. Perhaps you could use some heuristics on the content, decide it's HTML, and then treat it as 100%. Vs this concept of mixed maybe HTML / maybe text that you are trying here and in #2223.
