### ISSUE TITLE
set charset manually

### ISSUE THREAD

**Issue by ILAww** [jhy/jsoup#225]
First of all, thank you very much for your convenient and pretty Jsoup. It gives me a lot of help and inspiration. It's very useful. Thx a lot ^ ^

This is the problem I encountered：
I need extract data from a old page with tag-soup. This is a copy of the the pages: http://ilaww.mezoka.com/aInvalidPage.html .
It is encoded with GB2312(a Chinese charset). But as you can see, its content-type meta tag is terrible：

```
<meta HTTP-EQUIV="Pragma" CONTENT="no-cache" ; charset="gb2312">
```

So I have to set charset manually.
I think I must set charset before Jsoup parse and save content to String. So I modified Response Interface a little to add a method which can set charset before parse() uses it.
ILAww/jsoup@9135ff0a5c3654baa7ecdd05f69841fbb4f52b79

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
