### ISSUE TITLE
text  node visited twice after next node was removed

### ISSUE THREAD

**Issue by demidenko** [jhy/jsoup#2253]
simple visitor on `html = "<p>text<a>link</a></p>"` visit `text` node again after `<a>` was removed. this only happens if `a` in end or something like that

```kotlin
fun visit(html: String) {
    Jsoup.parse(html).traverse(
        object : NodeVisitor {
            override fun head(node: Node, depth: Int) {
                println("in")
                println((node as? TextNode)?.text())
                if (node.normalName() == "a") {
                    println("removed")
                    node.remove()
                }
            }
            override fun tail(node: Node, depth: Int) {
                println("out")
                println((node as? TextNode)?.text())
            }
        }
    )
}
```

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the NodeTraversor to keep track of removed nodes and skip revisiting their siblings. This prevents the issue of revisiting text nodes after removing an element.

You can review changes in this commit: https://github.com/jack-samo10000/jhy-jsoup-2253/commit/efe05551b6a590f9cfa7cc862669540d9be53f5a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jhy** [comment]
I am completely uninterested in AI spammers.
