### ISSUE TITLE
Does not parse HTML entities with ISO-8859-1 character set properly.

### ISSUE THREAD

**Issue by starrychloe** [jhy/jsoup#231]
JSoup doesn't return the proper characters when parsing a web page with ISO-8859-1 character encoding. 

Example:
http://www.city-journal.org/2012/22_3_school-discipline.html
&lt;meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /&gt;
... his department was &#147;going to reinvigorate civil rights enforcement.&#148; The secretary was ...
(You have to look at the source of this post to see the above... for some reason GITHUB won't display properly.)

These are opening and closing quotes, but when I print the results from text(), it prints a box character.

```
        try {
            String url = "http://www.city-journal.org/2012/22_3_school-discipline.html";
            doc = Jsoup.connect(url).get();
            Elements divs = doc.getElementsByTag("div");
            for (Element e: divs) {
                Log.d(TAG, "div: " + e.text().substring(0, 200>e.text().length()?e.text().length():200));
            }
        } catch (IOException ioe) {
            Log.e(TAG, "Could not fetch content: " + ioe);
        }
```

/////////////////

```
    Document doc = Jsoup.parseBodyFragment("<div>department was “going to reinvigorate civil rights enforcement.” The secretary was speaking on the 45th anniversary of &#147;Bloody Sunday,&#148; when state troopers</div>");
    Log.d(TAG, "output settings: " + doc.outputSettings());
    Log.d(TAG, "charset: " + doc.outputSettings().charset(java.nio.charset.Charset.availableCharsets().get("ISO-8859-1")));
    Elements divs = doc.getElementsByTag("div");
    for (Element e: divs) {
        Log.d(TAG, "div: " + e.text());
    }
```

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
