### ISSUE TITLE
:eq() doesn't work like sizzle

### ISSUE THREAD

**Issue by mohsen** [jhy/jsoup#232]
Could you please implement :eq() selector same as sizzle library. Here is the difference:

``` xml
<tag1>
  <child1 />
  <child1 />
  <child1 />
  <child2 />
  <child2 /> <!-- A -->
  <child2 />
</tag1>
```

If you select "tag1>child2:eq(1)", it selects the item marked with A if using Sizzle. But JSoup doesn't select anything in this case.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
