### ISSUE TITLE
Wrap and Unwrap

### ISSUE THREAD

**Issue by cdsimpkins** [jhy/jsoup#241]
`Elements.wrap("<div></div>")` does not seem to work.

Also, a call to `Elements.select("p").unwrap()` seems to just remove all p Elements and their child-nodes.

I haven't tested these two methods with any other tags, so I don't know if there are more issues.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
