### ISSUE TITLE
Characters between tags' attribute name/value pairs and nested double quoted attribute values

### ISSUE THREAD

**Issue by deqnstoqnov** [jhy/jsoup#247]
Recently JSoup could not parse this: &lt;div a="abc" b="ghj" ` &gt;  or &lt;div a="abc" % b="ghj"&gt; or other kind of characters between attributes. Other thing that could not be parsed is this &lt;div a="a"b"c" % b="ghj"&gt;  or &lt;div a="a"bc" % b="ghj"&gt; .

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
