### ISSUE TITLE
selector find content have &nbsp;

### ISSUE THREAD

**Issue by nathanyan** [jhy/jsoup#262]
i hava a html Fragment:
```
<td style="width:100px" valign="top">first&nbsp;&nbsp;&nbsp;&nbsp;name：</td>
<td style="width:190px" valign="top">nathan</td>
```
 i use  `Elements el = doc.select("td:containsOwn(first)");`  can find  td element. but 
`Elements el = doc.select("td:containsOwn(first&nbsp;)");`  is not work.

`td:containsOwn(first\&)`  not work too.

**Comment by jhy** [comment]
With d3f02400eca1c5cbf84212c46cebcff511536655, `:contains(first name)` will work
