### ISSUE TITLE
XML Attribute Names are converted to lower case, where they should stay as in the original input

### ISSUE THREAD

**Issue by edgar-philipp** [jhy/jsoup#272]
Hello,

in my current project I stumbled on this curious behaviour:

We use the following version of JSoup:

`<dependency>
	<groupId>org.jsoup</groupId>
	<artifactId>jsoup</artifactId>
	<version>1.7.2</version>
</dependency>`

```java
@Test
public void testJsoupAttributeNameCamelCase() {

        String xml = "<?xml version='1.0' encoding='UTF-8' standalone='no'?>" 
                              + "<rootNode attributeName='someValue' />";
        Document doc = Jsoup.parse(xml, "", Parser.xmlParser());
        Element root = doc.getElementsByTag("rootNode").get(0);
        Attribute first = root.attributes().asList().get(0);

        assertTrue("someValue".equals(first.getValue())); // pass
        assertTrue("attributeName".equals(first.getKey())); // fail
    }
```

Please have a look at this issue.

Thank you and kind regards
Edgar

**Comment by JavaJeffG** [comment]
+1 to allow for case-sensitive retrieval.

I am reading in the contents of an HTML table which may or may not contain XML elements, e.g.,
     <td><firstName>Frank</firstName></td>

When I get the 'td' org.jsoup.nodes.Element, I cannot access the case sensitive contents:

  tdElement.text()        = Frank
  tdElement.html()       = <firstname>Frank</firstname>
  tdElement.toString() = <td><firstname>Frank</firstname></td>

This is part of a case-sensitive Selenium test where <firstName>Frank</firstName> needs to be on the web page.

How about tdElement.htmlRaw() that provides the raw text?

Thanks.

**Comment by itonics-tbeauvais** [comment]
This is incredibly frustrating, is there a solution?

**Comment by cppexpert** [comment]
Guys, any progress on this ?

**Comment by roben** [comment]
This really is frustrating for an otherwise great library. Zazi seems to have provided a ready to use solution. Is there any reason why it has not been merged yet?

**Comment by kamrankashef** [comment]
Please merge.  Case-sensitive nodeName() and getKey() would be extremely helpful.

**Comment by jhy** [comment]
I have implemented a new feature ParseSettings, which allows the user to preserve tag and/or attribute name case at parse (and therefore output) time. For XML it defaults to preserving case, and lower case for HTML parsing.

https://github.com/jhy/jsoup/commit/e38b916ba1ebd3f5c00a6b6b8e77a4cdfea2800f

Thanks for everyone's feedback and contributions.

**Comment by kamrankashef** [comment]
Thanks for the update.  Can you clarify what output I should expect here?  I'm getting "tag", but expect "Tag".  Thanks.

    public static void main(final String... args) throws IOException {

        final Document doc = Jsoup.parse(
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<Tag ID=\"123\"></Tag>", "", Parser.xmlParser());

        final Elements elems = doc.children();
        for (final Element e : elems) {
            System.out.println(e.nodeName());
        }
    }

**Comment by jhy** [comment]
Yes, you should get `Tag`. Did you build from HEAD? It's coming in 1.10.

**Comment by kamrankashef** [comment]
Oh, never mind.  Looks great - thanks!!

**Comment by alexasimonamatei** [comment]
Any idea when 1.10 is being released?

**Comment by kaikilidev** [comment]
i can find out option this problem


   // Method to convert the string
    static String capitailizeWord(String str) {
        StringBuffer s = new StringBuffer();

        // Declare a character of space
        // To identify that the next character is the starting
        // of a new word
        char ch = ' ';
        for (int i = 0; i < str.length(); i++) {

            // If previous character is space and current
            // character is not space then it shows that
            // current letter is the starting of the word
            if (ch == ' ' && str.charAt(i) != ' ') {
                s.append(Character.toUpperCase(str.charAt(i)));
            }else if(ch == '<' && str.charAt(i) != '<'){
                s.append(Character.toUpperCase(str.charAt(i)));
            }else if(ch == '/' && str.charAt(i) != '/'){
                s.append(Character.toUpperCase(str.charAt(i)));
            }else
                s.append(str.charAt(i));
            ch = str.charAt(i);
        }

        // Return the string with trimming
        return s.toString().trim();
    }
 

this to convert string as original format

**Comment by ketanpatel25** [comment]
i can find out option this problem

// Method to convert the string
static String capitailizeWord(String str) {
StringBuffer s = new StringBuffer();

    // Declare a character of space
    // To identify that the next character is the starting
    // of a new word
    char ch = ' ';
    for (int i = 0; i < str.length(); i++) {

        // If previous character is space and current
        // character is not space then it shows that
        // current letter is the starting of the word
        if (ch == ' ' && str.charAt(i) != ' ') {
            s.append(Character.toUpperCase(str.charAt(i)));
        }else if(ch == '<' && str.charAt(i) != '<'){
            s.append(Character.toUpperCase(str.charAt(i)));
        }else if(ch == '/' && str.charAt(i) != '/'){
            s.append(Character.toUpperCase(str.charAt(i)));
        }else
            s.append(str.charAt(i));
        ch = str.charAt(i);
    }

    // Return the string with trimming
    return s.toString().trim();
}
this to convert string as original format
