### ISSUE TITLE
Control over preserveWhitespace

### ISSUE THREAD

**Issue by chris-martin** [jhy/jsoup#276]
I wish the `<code>` tag would preserve whitespace. I understand why it doesn't, because code tags shouldn't _necessarily_ be whitespace-preserving - but I bet it's not uncommon for pages to set a `code { whitespace: pre-wrap; }` style. It would be great if the `preserveWhitespaceTags` list built into the `Tag` class were somehow customizable.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
