### ISSUE TITLE
Disable cookies in favor of Java 1.5/1.6's built-in handler

### ISSUE THREAD

**Issue by davidblackledge** [jhy/jsoup#285]
Java 1.5 introduced java.net.CookieHandler and 1.6 introduced an implementation of it called java.net.CookieManager which work behind the scenes in all HttpURLConnection operations.  Users who want good cookie management should use them and not the Jsoup "cookie" methods.  However, redirect handling uses the "cookie" methods internally which messes things up if you use CookieManager.
Please add an option to disable Jsoup's cookie methods.  Possibly a "cookieHandler" method that calls CookieHandler.setDefault and disables internal handling.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by xehpuk** [comment]
Won't fix?
