### ISSUE TITLE
More information in UnsupportedMimeTypeException

### ISSUE THREAD

**Issue by davidblackledge** [jhy/jsoup#286]
UnsupportedMimeTypeException includes the offending mime type and URL in the exception which is helpful, but often more information about the connection is needed.  Rather than the programmer having to make an additional connection by hand, why not return as much information as possible in the Exception?

Some possibilities:
- getter for the entire headers() set.
- getter for the actual HttpURLConnection object (closed? or open (if the user calls the getter, they take ownership, if they don't call it, close it on finalization). or make leaving it open a setting like you have with throw-or-not for HTTP errors)
  - If you leave the connection open, then the programmer doesn't have to start a new one to handle the content.

FYI, for my own purposes ( http://david.blackledge.com/tivo/enterwebz ), just the headers would usually be enough.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
