### ISSUE TITLE
Jsoup.parse() doesn't seem to load whole HTML content

### ISSUE THREAD

**Issue by xjaphx** [jhy/jsoup#287]
I save stackoverflow.com into a file: input.html
load it inside: 

File input = new File("input.html");
Document doc = Jsoup.parse(input, "UTF-8");
// first query
Elements resultsA = doc.select("h3 > a");
// second query
Elements resultsB = doc.select("div.nav li a");

"resultsA" has no element while "resultsB" contains 6 found elements.
Wondering by it, I extract the html content from "doc" variable; wow, it contains just part of HTML, where "resultsB" html content can be found, but not content for "resultsA".

I've tried to parse several URLs (even, google.com), it all results in the same way.
"Jsoup.parse()" doesn't return whole HTML content.

**Comment by nikhilekbote** [comment]
Hi.I am using Jsoup to parse url and I am using .connect() , timeout() and useragent() methods for parsing, but still I am not able to fetch entire page, some tags are missing.

**Comment by cobr123** [comment]
try
```
Document = Jsoup.connect(url)
    .header("Accept-Encoding", "gzip, deflate")
    .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0")
    .maxBodySize(0)
    .timeout(600000)
    .get();
```

http://jmchung.github.io/blog/2013/10/25/how-to-solve-jsoup-does-not-get-complete-html-document/

**Comment by inohtaf** [comment]
Hi. I have already implemented the suggestion from cobr123 but it did not work. But when I try to get the page on try.jsoup.org it can retrieve a complete html page. Do you have any suggestions?

**Comment by cobr123** [comment]
inohtaf, can you post url which did not work?

**Comment by inohtaf** [comment]
Hi cobr123 for example http://kbbi.web.id/mempelajari, I have experienced on the other site too before. on that site I would like to retrieve :
Element content = doc.select("div.content").first();
Element desc = content.select("div#desc").first();
Element descDetail = desc.select("div#d1").first();

Unfortunately the content of "div#d1" can not be found. But I am pretty sure it should be worked using Jsoup since it can be retrieved perfectly on try.jsoup.org. Hope for your suggestions :)

**Comment by cobr123** [comment]
this work well
```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.IOException;

public class Test {
    public static void main(String[] args) throws IOException {
        String url = "http://kbbi.web.id/mempelajari";
        Document doc = Jsoup.connect(url)
                .header("Accept-Encoding", "gzip, deflate")
                .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0")
                .maxBodySize(0)
                .get();
        Element content = doc.select("div.content > div#desc").first();
        Element desc = content.select("div#desc").first();
        Element descDetail = desc.select("div#d1").first();
        System.out.println(descDetail);
    }
}

```
and print 
```
<div id="d1"> 
 <div id="info"></div>
 <b>ajar</b> 
..
100 lines of text
..
 <b>~ mikro</b> teknik pelatihan mengajar yang jumlah muridnya dibatasi, misalnya 5—10 orang; 
 <b>~ remedial</b> pengajaran yang diberikan khusus untuk memperbaiki kesulitan belajar yang dialami murid 
</div>
```

**Comment by inohtaf** [comment]
Hi cobr123. Yes it works well. It seems I made a mistake on my code yesterday. Btw, Thank you very much for your help :)

**Comment by gwidaz** [comment]
`  Document doc = Jsoup.connect(url)
                .header("Accept-Encoding", "gzip, deflate")
                .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0")
                .maxBodySize(0)
                .get();`

Does not work, I have tested it with soundcloud and it returns null or the error..

**Comment by gwidaz** [comment]
```
 .header("Accept-Encoding", "gzip, deflate")
                .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0")
                .maxBodySize(0)
                .get();
```

Does not work, I have tested it with soundcloud and it returns null or the error..

**Comment by cobr123** [comment]
Give an example of a selector

**Comment by gwidaz** [comment]
Well I got to working it but only after messing by converting the website to txt file as the output is absolutelly different from what you see in inspect element... The html which I received in txt file is now used to grab data from url directly, which partly works for me :)

**Comment by 4sskick** [comment]
`Document document = Jsoup.connect("https://www.instagram.com/p/BRdRSJtgABK/")
                    .header("Accept-Encoding", "gzip, deflate")
                    .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0")
                    .maxBodySize(0)
                    .timeout(600000)
                    .get();`

I used this configuration, but it still not works, I wanna select src attr by img tag , but the result only src from script tag give me the result. When I print the html by using **.html()** give me not whole of html. Please give me some advice how do I get the whole html script

**Comment by k2sss44** [comment]
.header gives cant resolve in android studio what to do?
