### ISSUE TITLE
lower cased html attributes

### ISSUE THREAD

**Issue by aseychell** [jhy/jsoup#29]
As I already stated in a previous post, we are using JSTL tags (java custom tags) and we require the attributes to be camel cased to match some methods in our java code.  Is it possible to give an option to leave the attributes as they are and not modify them by making them lower case?

e.g. <abc:ourtag returnUrl="http://abc.com" /> does not change to <abc:ourtag returnurl="http://abc.com" />

Thanks!

**Comment by jhy** [comment]
You can control case normalization with ParseSettings now - https://github.com/jhy/jsoup/commit/e38b916ba1ebd3f5c00a6b6b8e77a4cdfea2800f
