### ISSUE TITLE
tag select is not parsing properly nested options

### ISSUE THREAD

**Issue by tbarderas** [jhy/jsoup#294]
it fails parsing this html code:

&lt;select id="order-by" name="order-by" class="styled"&gt;
        &lt;option selected="selected" value="RANKING"&gt;Our Selection&lt;/option&gt;
        &lt;option  value="PRICE"&gt;Price&lt;/option&gt;
&lt;/select&gt;

i've tried changing the ID of the select to "orderBy" but the error remains

debugging over the code i've found that in HtmlTreeBuilderState.class , the code executing on the startTag of the select is: 

[...]
                    } else if (name.equals("select")) {
                        tb.error(this);
                        return tb.process(new Token.EndTag("select"));
                    }
[...]

and after this, when it receives the option tag, fails with error:

Unexpected token [EndTag] when in state [InSelect]

**Comment by jhy** [comment]
I can't repro this in current builds -- fixed by another change I expect. Thanks.
