### ISSUE TITLE
TextNode.isBlank() ignores Unicode whitespace 

### ISSUE THREAD

**Issue by mingfai** [jhy/jsoup#296]
TextNode.isBlank() treats only HTML whitespace as blank, instead of all Character.isWhitespace() characters as blank. So some unicode whitespace, such as '\u3000' in a text node will result as !isBlank(). This contradict with typical Java language usage, IMHO.

TextNode.isBlank is being used by other methods such as hasText(), so the change, if accepted, should be applied in the original isBlank.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
