### ISSUE TITLE
Make class org.jsoup.select.QueryParser public

### ISSUE THREAD

**Issue by remisbaima** [jhy/jsoup#308]
This will allow us developers to use the method QueryParser.parse(String) to see how the CSS queries are parsed.

**Comment by remisbaima** [comment]
I guess this feature is a quick-win :-).

**Comment by McSquirrel** [comment]
I second this request.  It would be helpful to be able test an individual element against a selector.  Especially when iterating over elements.

**Comment by jhy** [comment]
Done with 4f707008353e272c12a7a6543d6ecfc666a7cc64. Thanks!
