### ISSUE TITLE
parse methods incorrectly add explicit closing tag to param elements

### ISSUE THREAD

**Issue by alexanderdarino** [jhy/jsoup#309]
Example:

When parsing "<param name='wmode' value='transparent' />", an Element representing <param name='wmode' value='transparent'></param> is returned, confusing some web browsers.

As a work around, I have to invoke the following method after all other html processing:

private static String fixParams(String s){
        return s.replaceAll("></param>","/>")
    }

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
