### ISSUE TITLE
Nth-child behavior is not the same between expression (-n+1) and (-1n+1)

### ISSUE THREAD

**Issue by lykm02** [jhy/jsoup#310]
I found behavior of  :nth-child(-n+1) differs from  :nth-child(-1n+1). So I think it's a bug when parsing an+b expression since we have common sense that -n=-1n.

Besides, I do find behavior of  :nth-child(-n+1) is the same as behavior of  :nth-child(n+1)
By the way I test with jsoup-1.7.2.jar
![jsoup_nthchild](https://f.cloud.github.com/assets/1127403/323131/362cbb3c-9a9a-11e2-9ff1-fc35374e7c0c.jpg)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
