### ISSUE TITLE
IOException: Premature EOF raised when parsing an RSS feed

### ISSUE THREAD

**Issue by rdkrajunus** [jhy/jsoup#314]
I found a page that when read by jsoup v1.7.2, will throw a java.io.IOException: Premature EOF, and believe I've found a bug.

The page is: http://www.dotnetnuke.com/Resources/Blogs/rssid/99.aspx

I tried:
- checking to make sure this is not a known issue.  I don't believe it is.
- parsing it locally per http://jsoup.org/cookbook/input/load-document-from-file.  This was successful.
- using wireshark to watch my browser have a TCP conversation with the page, viewing the header information that was being sent over by my browser, and then trying to mimic that header information using header().  This was not successful. 
- using wireshark to watch jsoup have a TCP conversation so I could see if the web server isn't responding to jsoup, or if jsoup isn't processing correctly.  Jsoup isn't processing correctly; the web server responds identically to jsoup and the browser.
- setting a breakpoint at org.jsoup.helper.DataUtil.java:124, and inspecting the buffer object.  The buffer appears to contain the page in UTF8 after the first call to read(), but the exception is raised on the second call to read().  I believe the buffer contains the page encoded in UTF8, based on the fact that the first index of buffer contains 60 (UTF8 for <) and 62 (UTF8 for >) is the value in the last index not containing a 0. "<" and ">" begin and end the document.

The code that will reproduce the issue is:

```
package com.tallan.jsouptutorial;

import java.io.IOException;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public class StackOverflowQuestion2 {

    public static void main(String[] args) {

        try {
            Document doc = Jsoup.
                connect("http://www.dotnetnuke.com/Resources/Blogs/rssid/99.aspx").
                userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17").
                get();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

The stack trace is:
java.io.IOException: Premature EOF
    at sun.net.www.http.ChunkedInputStream.readAheadBlocking(Unknown Source)
    at sun.net.www.http.ChunkedInputStream.readAhead(Unknown Source)
    at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
    at java.io.BufferedInputStream.read1(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:124)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:464)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410)
    at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164)
    at org.jsoup.helper.HttpConnection.get(HttpConnection.java:153)
    at com.tallan.jsouptutorial.StackOverflowQuestion2.main(StackOverflowQuestion2.java:22)

My research into this bug is motivated by a [StackOverflow question](http://stackoverflow.com/q/13648921/1715565) that I'm trying to answer.  I'm happy to help fix it, but I've never contributed to an open source project before so the community may have to endure a couple of questions about getting someone started.

Thanks for all your work on this library,
Rich

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by AindriyaBarua** [comment]
> I found a page that when read by jsoup v1.7.2, will throw a java.io.IOException: Premature EOF, and believe I've found a bug.
> 
> The page is: http://www.dotnetnuke.com/Resources/Blogs/rssid/99.aspx
> 
> I tried:
> 
> * checking to make sure this is not a known issue.  I don't believe it is.
> * parsing it locally per http://jsoup.org/cookbook/input/load-document-from-file.  This was successful.
> * using wireshark to watch my browser have a TCP conversation with the page, viewing the header information that was being sent over by my browser, and then trying to mimic that header information using header().  This was not successful.
> * using wireshark to watch jsoup have a TCP conversation so I could see if the web server isn't responding to jsoup, or if jsoup isn't processing correctly.  Jsoup isn't processing correctly; the web server responds identically to jsoup and the browser.
> * setting a breakpoint at org.jsoup.helper.DataUtil.java:124, and inspecting the buffer object.  The buffer appears to contain the page in UTF8 after the first call to read(), but the exception is raised on the second call to read().  I believe the buffer contains the page encoded in UTF8, based on the fact that the first index of buffer contains 60 (UTF8 for <) and 62 (UTF8 for >) is the value in the last index not containing a 0. "<" and ">" begin and end the document.
> 
> The code that will reproduce the issue is:
> 
> ```
> package com.tallan.jsouptutorial;
> 
> import java.io.IOException;
> 
> import org.jsoup.Jsoup;
> import org.jsoup.nodes.Document;
> 
> public class StackOverflowQuestion2 {
> 
>     public static void main(String[] args) {
> 
>         try {
>             Document doc = Jsoup.
>                 connect("http://www.dotnetnuke.com/Resources/Blogs/rssid/99.aspx").
>                 userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17").
>                 get();
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>     }
> }
> ```
> 
> The stack trace is:
> java.io.IOException: Premature EOF
> at sun.net.www.http.ChunkedInputStream.readAheadBlocking(Unknown Source)
> at sun.net.www.http.ChunkedInputStream.readAhead(Unknown Source)
> at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
> at java.io.FilterInputStream.read(Unknown Source)
> at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
> at java.io.BufferedInputStream.read1(Unknown Source)
> at java.io.BufferedInputStream.read(Unknown Source)
> at java.io.FilterInputStream.read(Unknown Source)
> at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:124)
> at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:464)
> at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410)
> at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164)
> at org.jsoup.helper.HttpConnection.get(HttpConnection.java:153)
> at com.tallan.jsouptutorial.StackOverflowQuestion2.main(StackOverflowQuestion2.java:22)
> 
> My research into this bug is motivated by a [StackOverflow question](http://stackoverflow.com/q/13648921/1715565) that I'm trying to answer. I'm happy to help fix it, but I've never contributed to an open source project before so the community may have to endure a couple of questions about getting someone started.
> 
> Thanks for all your work on this library,
> Rich

I am still facing the same issue with Jsoup.

> (Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

Hey Jonathan, I am still facing the same issue.

**Comment by jhy** [comment]
@AindriyaBarua do you have a current repro as a testcase you can share? That repros in the current version (1.13.1)? There have been many changes in the releases since the original report (1.7.2). And that URL redirects to a different URL which does not repro for me in current versions.
