### ISSUE TITLE
Whitelist "body" duplicate the tag.

### ISSUE THREAD

**Issue by ckarmann** [jhy/jsoup#315]
I was using Whitelist to only have some tags in my html, and one of them is "body". It seems that since version 1.7.2, whitelisting "body" makes it appear twice in the resulting document.

Here is how I reproduced the problem:

```
public void testBodyBody(){
    String html = "<p>test</p>";

    Document document = Jsoup.parseBodyFragment(html);
    System.out.println("Before:\n" + document + "\n");

    Whitelist clean = Whitelist.none().addTags("body", "p");
    document = new Cleaner(clean).clean(document);
    System.out.println("After:\n" + document + "\n");
}
```

And the result is:

```
Before:
<html>
 <head></head>
 <body>
  <p>test</p>
 </body>
</html>

After:
<html>
 <head></head>
 <body>
  <body>
   <p>test</p>
  </body>
 </body>
</html>
```

It seems also that the resulting document will always contain "body" no matter what I whitelist, so I guess it is not necessary to whitelist "body" in the first place, but the behaviour when whitelisting the body tag is really surprising and it should not be.

It happens with jsoup 1.7.2. I'm positive that it does not happen with version 1.7.1.

It's not an important bug of course (there's an easy workaround), but you might want to look into that.

Thanks for your work on Jsoup.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
