### ISSUE TITLE
Jsoup.parse() overloaded methods works differently

### ISSUE THREAD

**Issue by mikolg** [jhy/jsoup#327]
I'm using jsoup-1.7.2.jar
And tried to load same url using different parse methods and got different results.
Following test shows that same query on doc1 and doc2 (parsed from same url) are different.

@Test
public final void testUrl() throws IOException {
  final String CSS_QUERY = "div.protocol";
  final String testUrl = "http://rusdsu.ru/competitions/results/586864/";

  Document doc1 = Jsoup.parse(new URL(testUrl), 10000);
  Document doc2 = Jsoup.parse(new URL(testUrl).openStream(), "UTF-8", "");

  assertEquals(doc2.select(CSS_QUERY).size(), doc1.select(CSS_QUERY).size());
}

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
