### ISSUE TITLE
Whitelist .relaxed() and .basicWithImages(): src attribute removed from img tag

### ISSUE THREAD

**Issue by keithphw** [jhy/jsoup#333]
Hi jhy,
I have found that the following code removes the src attribute from the img tag, but the docs say it shouldn't:
`System.out.println(Jsoup.clean("<img src='imgFile.png' />", "http://www.somedomain.com", Whitelist.basicWithImages()));
System.out.println(Jsoup.clean("<img src='imgFile.png' />", "http://www.somedomain.com", Whitelist.relaxed()));`

The above code outputs:
`<img />
<img />`

Though I believe it should output:
`<img src='imgFile.png' />
<img src='imgFile.png' />`

Is this a bug or am I doing something incorrectly?

By the way, thank you for a fantastic library. I particularly like your whitelist approach to html cleaning and preventing xss attacks. I used to use OWASP/Anti-samy but it was very strict in the type of html it would allow and would always clean/delete too much of my html. JSoup's whitelist method has worked much better.

Best regards,
keith

**Comment by msarry** [comment]
Thanks for this thread, this was the problem I was experiencing. One additional thing I ran into is that I had to change from clean(String bodyHtml, Whitelist whitelist)  to clean(String bodyHtml, String baseUri, Whitelist whitelist) for the preserveRelativeLinks to work.
