### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by ktobah** [jhy/jsoup#339]
Hello guys,

I am using Jsoup to parse an HTML file (contain a table), which size is more than 600MB, I got the error : 

java.lang.OutOfMemoryError: Java heap space

I augmented my Java heap size, and I also cut the file into 64MB files and tried again, but the same error.

How can I solve this please ? I need to do it, I am in hurry.

Thanks.

**Comment by kamrankashef** [comment]
I'm running into the same issue.  The file is about 250MB.  I have allocated 2GB of memory and after 17 minutes fails with this error:

     [java] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
     [java]     at java.lang.String.toLowerCase(String.java:2647)
     [java]     at java.lang.String.toLowerCase(String.java:2670)
     [java]     at org.jsoup.parser.Token$Tag.appendTagName(Token.java:151)
     [java]     at org.jsoup.parser.TokeniserState$10.read(TokeniserState.java:147)
     [java]     at org.jsoup.parser.Tokeniser.read(Tokeniser.java:50)
     [java]     at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:49)
     [java]     at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:43)
     [java]     at org.jsoup.parser.Parser.parseInput(Parser.java:32)
     [java]     at org.jsoup.Jsoup.parse(Jsoup.java:45)

I use Jsoup in numerous projects.  What I am likely to do is run a stax parser to segment data, then feed the child elements into Jsoup.

**Comment by jhy** [comment]
I've implemented a stream reader in #905. So OOMs caused by the previous full input buffering (which as noted by @trejkaz would grow exponentially) should not happen any more. You still need a heap larger than the input file to get it into the DOM (because of the object overhead, and temporary objects created during parse), but substantially less now (say ~ + 25%).
