### ISSUE TITLE
UTF-8 eof cause truncation of html.

### ISSUE THREAD

**Issue by yhjj0108** [jhy/jsoup#341]
Jsoup.parse(String html) function parse html as utf-8, if a character like xefxbfxbf(utf-8, in unicode as \uffff just EOF) in html, Jsoup will think reading the end of html, but exactly not reading to the end of html. For example: class="msgCnt">xEFxBFxBF什么是子女？就是您一天暴打八回也不让别人辱骂一句的人。￿什么是老婆？就是您八天不想亲一次也不让别人亲一下的人。xEFxBFxBF什么是老公？就是您八月不让碰一次也不许他在外胡搞的人。xEFxBFxBF什么是朋友？就是您一天联系八次也不嫌烦的人！xEFxBFxBF什么是好友？就是您一天收一短信开心一笑也不用回复的人。
this is a problem, I think when parse String, Jsoup can't treat EOF as the end of html, Jsoup should offer a option for use other character replacing xEFxBFxBF, as  web browser use other character replacing xEFxBFxBF.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by ov7a** [comment]
May be it would be better to cover it with test before closing?
