### ISSUE TITLE
Cleaner: Allow to specify if children of unsafe node should be copied or pruned

### ISSUE THREAD

**Issue by raulk** [jhy/jsoup#342]
Provide an option in the Whitelist so that the user can specify what happens for unsafe elements: if they are fully pruned including children, or if children are evaluated too.

A good example is a `<table>` element. It may make more sense to prune the entire table + inner elements, rather than just stripping the HTML tags.

```
<p>Hello</p><table><th>Fruit</th><tr><td>Apple</td></tr></table>
```

Currently up like that with Whitelist.basic().

```
<p>Hello</p>FruitApple
```

Unfortunately we were looking for:

```
<p>Hello</p>
```

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
