### ISSUE TITLE
jsoup's XML parser lowercases tags

### ISSUE THREAD

**Issue by Raynes** [jhy/jsoup#344]
A user of a library of mine that uses jsoup under the hood recently submitted an issue pointing out that XML tags are being lowercased. I did a little experimentation and it appears that JSoup is doing the lower casing.

https://github.com/Raynes/laser/issues/25

Here is an example

```clojure
user> (Jsoup/parse "<Test xmlns:Ex=\"yo\"/>" "" (Parser/xmlParser))
#<Document <test xmlns:ex="yo" />>
```

**Comment by jhy** [comment]
Support for case preservation is in https://github.com/jhy/jsoup/commit/e38b916ba1ebd3f5c00a6b6b8e77a4cdfea2800f
