### ISSUE TITLE
Element.absUrl returns wrong value for relative URL's

### ISSUE THREAD

**Issue by e2bady** [jhy/jsoup#345]
When given a relativ URL org.jsoup.nodes.Element.absUrl(String) does not return the actual adress.

Given "./relative.htm" with baseUri("http://www.example.com/bar/") e.absUrl will return http://www.google.com/./relative.htm which is wrong. The same applies for "relative.htm".

The junit-test proving this can be found at: https://github.com/e2bady/JsoupRelativeLinkTest

which should print out

13:50:34.708 [main] DEBUG ExtractLinksTest - link: http://www.example.com/relative.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link: http://www.example.com/./relative.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link: http://www.example.com/internallink.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link: http://www.google.com

for: 

```String html = "<html><head></head><body>" +
		    "<a href=\"http://www.google.com\">google</a>" +
		    "<a href=\"/internallink.htm\">internal</a>" +
		    "<a href=\"./relative.htm\">internalrelativ</a>" +
		    "<a href=\"relative.htm\">internalrelativ</a>" +
		    "</body></html>";```

which should print out: 

13:50:34.708 [main] DEBUG ExtractLinksTest - link: http://www.example.com/bar/relative.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link: http://www.example.com/bar/./relative.htm OR http://www.tks.de/page/relative.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link:http://www.example.com/internallink.htm
13:50:34.723 [main] DEBUG ExtractLinksTest - link: http://www.google.com

Tested with Version 1.7.1 and 1.7.2.

**Comment by yhon-acurio** [comment]
Hi,
Is planned to resolve this issue in one of the next releases?
Has anybody found any workaround?

Thanks

**Comment by jhy** [comment]
I've not been able to repro this. Unfortunately your example code URL gives a 404.

I added further test cases at https://github.com/jhy/jsoup/commit/84a2dfeced140fca53293b5fa2d5733494191224

As far as I can tell, that matches your report. Please feel free to re-open if you can point out a case that I've missed.
