### ISSUE TITLE
JSoup parses tags with spaces

### ISSUE THREAD

**Issue by chaschev** [jhy/jsoup#352]
After parsing the input text, which could be a part of aformula:

A&lt;B
b&gt;a
a&lt;b

becomes:

A&lt;b>a
a&lt;/b> 

The most weird thing is that github has this bug too!

**Comment by fleaflicker** [comment]
Just to clarify with some examples:

**Truncates contents after '<'**
```Java
Jsoup.parseBodyFragment( "A is less than b: a<b" );
```
Output
```html
<html>
 <head></head>
 <body>
  A is less than b: a
 </body>
</html>
```

**Escapes '<'**
```Java
Jsoup.parseBodyFragment( "One is less than two: 1<2" ) 
```
Output
```html
<html>
 <head></head>
 <body>
  One is less than two: 1&lt;2
 </body>
</html>
```

Is there any way to make Jsoup behave like the second example with numbers?

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
