### ISSUE TITLE
custom charset support!

### ISSUE THREAD

**Issue by maxid** [jhy/jsoup#355]
public static class Response extends Base<Connection.Response> implements Connection.Response {
...
        private static void writePost(Collection<Connection.KeyVal> data, OutputStream outputStream) throws IOException {
            writePost(data, outputStream, null);
        }
        
        private static void writePost(Collection<Connection.KeyVal> data, OutputStream outputStream, String contentType) throws IOException {
            String charset = DataUtil.getCharsetFromContentType(contentType);
            if(charset == null){
                charset = DataUtil.defaultCharset;
            }
...

**Comment by jhy** [comment]
If I understand the request, this was implemented recently with ability to set a post charste.
