### ISSUE TITLE
Jsoup.parse produces attributes with illegal characters in. 

### ISSUE THREAD

**Issue by fiddlemath** [jhy/jsoup#370]
For example,

```
Jsoup.parse("<img src='foo' alt='Sophie's Choice' />");
```

Yields:

```
 <html>
   <head></head>
   <body>
     <img src="foo" alt="Sophie" s="" choice'="" />
   </body>
 </html>
```

But `choice'` is not a valid attribute name in XML, because `'` isn't a valid character in an attribute name: http://www.w3.org/TR/xml/#sec-common-syn (see `NameChar`)

I suppose I haven't found it _specified_ that the output of Jsoup.parse should be valid XML... is it intended to be?

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
