### ISSUE TITLE
Support HTML redirect (Meta tag refresh) ?

### ISSUE THREAD

**Issue by sunng87** [jhy/jsoup#371]
We just got this kind of redirection when parsing html files. Some web sites doesn't use standard HTTP redirection. Instead, they use browser redirection:

``` html
<html>
 <head> 
  <meta http-equiv="Refresh" content="0;URL=http://sports.sina.com.cn/j/2013-11-14/22386885017.shtml" /> 
 </head> 
 <body></body>
</html>
```

We can check the Refresh meta tag: If the content URL doesn't equal to base URL, just treat it as a redirection. This can be done within HTTPConnection. I found a python command line utility [httpie](http://httpie.org) supports this feature. It will be nice to have this feature in Jsoup.

**Comment by zhuhw** [comment]
It does not work for `http://baidu.com` either. The HTML I got is:
```
<html>
 <head>
  <meta http-equiv="refresh" content="0;url=http://www.baidu.com/"> 
 </head>
 <body> 
 </body>
</html>
```
I used `Connection.followRedirects(true)` in version 1.8.3.

**Comment by jhy** [comment]
Closing, no plan to implement.
