### ISSUE TITLE
Self closing iframe causes escaping for the following tags

### ISSUE THREAD

**Issue by alkiskal** [jhy/jsoup#382]
Jsoup will correctly normalize the self closing tag to &lt;iframe&gt;&lt;/iframe&gt; but the problem remains for the following tags.

Replicate by running this: 

<pre>Document doc = Jsoup.parse("&lt;iframe /&gt;&lt;span&gt;test&lt;/span&gt;");
System.out.println(doc.html());</pre>

This runs as it is supposed to

<pre>Document doc = Jsoup.parse("&lt;iframe&gt;&lt;/iframe&gt;&lt;span&gt;test&lt;/span&gt;");
System.out.println(doc.html());</pre>

**Comment by ValiousSwank** [comment]
Hey Guys,

I have a similar problem. I debugged into Jsoup and saw Jsoup handles everything inside iframe as characters and that is why it escapes it.

Is it a bug, or intended?

**Comment by jhy** [comment]
Fixed this sometime back.
