### ISSUE TITLE
Performance issues on Android Kitkat

### ISSUE THREAD

**Issue by animaonline** [jhy/jsoup#383]
For some reason .parse takes 10x more time to complete on devices running kitkat

What could be the problem? This has been confirmed on all official kitkat devices, it doesn't matter how the html looks like.

**Comment by gregko** [comment]
I also find jsoup about 10x slower on Android 4.4 KitKat and v5 Lollipop than on older versions (tested 4.3 and 4.2.2). Under KitKat I tested with both ART and Dalvik VMs, practically no difference. Any idea what could be done about it?

**Comment by jhy** [comment]
What jsoup version -- can you try with Mainline (not 1.8.1)? I optimized a
lot of things that can cause GC. I didn't see a 10x speedup but it did
improve.

Are you looking at parsing or serialization? Can you give me your example
parsing HTML files?

**Comment by gregko** [comment]
Hey, thanks for the answer! I was using before ver. 1.7.4, and after reading your release notes about Android optimizations in 1.8.2, I instantly built it form the latest GitHub source (last build yesterday) and tested this. The issue persists, version 1.8.x is very fast under Android 4.3 and lower, e.g. loads a long chapter from ePub book into my app in about 2 seconds even on slow old devices, while it takes about 20 seconds to load on Galaxy Note 3 - lots of memory and decent processor, with KitKat before, now upgraded to Lollipop. Same on other devices I own and in the emulators. It's probably the inefficient use of memory, as the VM doing garbage collection often? I'm going to try it now with a setting requesting a bigger heap, will report shortly what happens then.

What my app (https://play.google.com/store/apps/details?id=com.hyperionics.avar) does with jsoup: runs my modified version of Readability algorithm to extract text for reading aloud or on screen , reject junk like menus, ads, unrelated links etc.Then, it processes further the cleaned-up jsoup doc e.g. downloading and inserting style nodes and doing further cleanup to have styled HTML text for reading aloud and highlighting the sentences it reads, e.g. it traverses all nodes extracting text, but also keeping text attributes like headers, paragraphs, divs and styles. This last step, which is also slow on Android 4.4 and higher, is based on your text extractor and node visitor. It no longer manipulates the Document object, just visits the nodes and accumulates my "simpliefied HTML" in a StringBuilder object.

Greg

**Comment by gregko** [comment]
Update: just tried android:largeHeap="true" in AndroidManifest.xml of the app, no difference on Android 5 test (Galaxy Note 3 phone).

**Comment by jhy** [comment]
Could you send me (directly, jonathan@hedley.net) a sample of that epub
doc? I'm seeing like 10ms parse times for jsoup.org, 155ms for CNN sites on
Lollipop Nexus 5.

I need to find an old phone to compare pre-kitkat.

**Comment by gregko** [comment]
I was not sure what exactly you need, but assume an ePub chapter. Will try to extract and email it... The jsoup parse is probably pretty fast, the other operations I do take longer. I looked at the jsoup code, and for example Element hasClass(String className) method calls classNames() method that creates a lot of strings and a String table, and then a Set<String> - a lot of objects created on the heap, to give us a simple yes/no answer, and they all have to be garbage collected soon after. Imagine now iterating through all elements in a doc...

I will try to replace hasClass() with just a RegEx "\bclass_name\b" expression lookup and see if that makes a difference in my app. Then will continue searching for other places like that to optimize memory management. If you have suggestions where to look, let me know. If I do get something that works really well, will issue a merge request to your repo.

Greg

**Comment by jhy** [comment]
I dug into why CharsetEncoder#canEncode() is so slow on Android. I can't find why it's changed so much between ICS to KK where it got really slow, but I do see that it's implemented natively and involves creating arrays and copying through the native interfaces. However in the JDK, for at least UTF and Ascii, there are simple one-liner implementations for canEncode. I expect somewhere between ICS and KK, Android moved from using OpenJDK to a native (ICU) implementation and that's where this speed regression comes from.

I think the fix will be to roll some specific encode checks, referring to the simple implementations in the OpenJDK character sets.

**Comment by jhy** [comment]
Thanks to @gregko and everyone else for getting to the bottom of this. The Android implementation of canEncode doesn't use the OpenJDK simple methods, and ends up being very slow. I've built simple tests for ascii and UTF, similarly to Greg's impl. We can extend it simply if there are other charsets in use that get impacted.

**Comment by jhy** [comment]
Here's data on the improved Document.html() time:

OLD impl v New (ms)
Wiki: 1895, 16 (118x)
CNN: 6378,  (115x)
Alterslash: 3013, 28 (107x)
Jsoup: 167, 2 (83x)

**Comment by gregko** [comment]
Yes, that was pretty much my concussion as well. Wrapping chars in character arrays (lots of junk on the heap to dispose) sending them over VM/native boundary, and do this for the file I sent you over 200,000 times... hopefully you can find a more general solution, what I purposed is still the best optimization for the social case of dealing with Unicode. Good luck! 
Greg 

-------- Original message --------

**Comment by jhy** [comment]
I didn't really find a more generic approach. I looked at reimplementing
the encoding loop, or catching an exception on unsupported characters and
replacing with an escape. The problem with these is that we aren't actually
doing the encoding at this phase.

This implementation should be easy to extend if we see issues with other
common encodings.

**Comment by Adonai** [comment]
Hey, thanks! I've been waiting for this for year!
I even reimplemented escaping in a very hacky way just for one site to work properly.

Glad to see you didn't forget your open projects! It brings me some money from time to time - where can I donate few bucks to you?
