### ISSUE TITLE
Parsing inconsistency with tags and text directly inside tables

### ISSUE THREAD

**Issue by jonathandandries** [jhy/jsoup#385]
I'm using jsoup-1.7.3 via Maven.

Tags and text are treated differently when embedded directly inside a table tag. For raw text content, it leaves the text within the table tag as follows:

``` java
System.out.println(Jsoup.parse("<table>Content text</table>").html());
```

``` html
<html>
 <head></head> 
 <body> 
  <table>
    Content text 
  </table>  
 </body>
</html>
```

But, for tag-wrapped text, it pulls the content outside (before) the table like this:

``` java
System.out.println(Jsoup.parse("<table><strong>Content text</strong></table>").html());
```

``` html
<html>
 <head></head> 
 <body> 
  <strong>Content text</strong> 
  <table></table>  
 </body>
</html>
```

Now, this is particularly troubling when you have a combination of raw text (not wrapped inside a tag) and tag-wrapped text. As the following shows, you end up with "Content text" showing as "text Content".

``` java
System.out.println(Jsoup.parse("<table>Content <strong>text</strong></table>").html());
```

``` html
<html>
 <head></head> 
 <body> 
  <strong>text</strong> 
  <table>
    Content 
  </table>  
 </body>
</html>
```

Granted this isn't the best html, but FireFox, IE, and Chrome handle it by pulling all the content (both raw text and tag-wrapped text) out of (before) the table. Given that all three browsers do it that way, you probably want to make sure that raw text is pulled out of the table along with the tags.

I've demonstrated a very scaled down use case compared to my production output so that you can see the heart of the issue. Please let me know if you would like a more complex example. This is an urgent issue for me, so I'd be interested in suggestions for work-arounds. Thanks.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
