### ISSUE TITLE
npe if you set the title with tags in it

### ISSUE THREAD

**Issue by rgwood1234567890** [jhy/jsoup#387]
You are not supposed to have html tags in the title, i know. It took me an hour to figure out that this was the cause of the NPE, though so it's probably better if the lib throws a better error than just an random npe. Psuedo-code to re-create:

		String  rawHtmlStr="<html><head><title>gfgfd</title><body>fdfds</body</html>";
		
		Document doc = Jsoup.parse(rawHtmlStr, "/");
		Element tElem=doc.select("title").first();

		tElem.html("fdfdsf"); //fine
		
		tElem.html("Oh <i>Really</i>?"); //npe

This was with jsoup 1.7.2 and 1.7.3 with jdk 1.7, latest.

**Comment by jhy** [comment]
There's a test in ElementTest.testSetHtmlTitle that confirms this is OK. Thanks.
