### ISSUE TITLE
CSS parser

### ISSUE THREAD

**Issue by cowwoc** [jhy/jsoup#399]
First, thank you for this excellent library!

Would you consider extending this functionality to parse (and rewrite) CSS in the same way that you currently parse (and rewrite) HTML? If so, consider this a feature request.

**Comment by jhy** [comment]
@cowwoc, bit of a late reply I know, but yes I am considering this. Could you (and anyone else!) describe what use-cases you would suggest we implement? I have a few ideas but keen to get more feedback from users so we get the API design right.

**Comment by cowwoc** [comment]
@jhy At the time I requested this feature I was implementing a server-side feature servlet that would take any URL as input and rewrite the HTML, CSS, JS to "inject" our product widget into the right place. The idea was to allow customers to demo what their website would look like if they were to use our product.

Anyway, the product in question is now dead (the company went under) so I am no longer working on this. That said, I think there is value in bringing JSoup's great API to the world of CSS. Unfortunately, I no longer have concrete use-cases for you :)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
