### ISSUE TITLE
Node identification  

### ISSUE THREAD

**Issue by ghost** [jhy/jsoup#405]
Hi,

when working with Jsoup it would be very helpful if all node would habe unique ids assigned (and used in equals/hashcode) in order to know which nodes one already has processed.

This is especially important if one uses different kind of selectors which produces overlapping result sets. I tried the naive way and remembered nodes in a hash set but it seems that nodes are getting created on the fly.

This solution would also allow for comparing nodes of cloned documents.

Kind regards
Lars

**Comment by jhy** [comment]
Node.equals is just ==, so I think that does what you want -- an identity check. Right? Can't remember if it was like that when you filed, as I've revved it a couple of times.

**Comment by jhy** [comment]
Please reopen if you're still having issues in the current version
