### ISSUE TITLE
CDATA fields are lost after calling Jsoup.parse

### ISSUE THREAD

**Issue by ataraxie** [jhy/jsoup#406]
First, congratulations to your great library - it's awesome! However we're having an issue that got us in serious trouble. I'll explain our scenario:

We're running a Search/Replace mechanism on many pages of a CMS. The content of the pages is XHTML. The basic scheme we're doing for each page is

``` java
String xhtml = page.getBody();
Document document = Jsoup.parse(xhtml, "", Parser.xmlParser());
// remove some content from document ...
page.setBody(document.text());
```

The big problem is that there is a lot of content that looks like

``` xml
<some-node><![CDATA[some.string.content=content]]></some-node>
```

As soon as we call Jsoup.parse, the CDATA tag is gone and text() will produce this

``` xml
<some-node>some.string.content=content></some-node>
```

What we have afterwards is a page with corrupt content.

We'd be very glad about some help, since we really enjoy using Jsoup otherwise!

**Comment by jonada** [comment]
I had the exact same challenge with Confluence as @ataraxie. If it helps anyone else, I ended up writing a helper function that restores the CDATA section. Perhaps not the prettiest solution, but it fulfilled my needs.

`	/**
	 * Restores plain text in HTML to it's CDATA equivalent.
	 * For example, jsoup parses CDATA section and returns HTML escaped string. This function restores it.
	 * This is a 
	 * 
	 * @param html The html code
	 * @param tag The enclosing tag of the text that shall be restored.
	 * @return
	 */
	public static String restoreCDATA(String html, String tag) {
		int startIdx;
		int endIdx;
		String startTag = "<" + tag + ">";
		String endTag = "</" + tag + ">";
		
		// 1. Find next occurrence
		startIdx = html.indexOf(startTag);
 		while (startIdx >= 0) {
 			// 2. Find end boundary
 			endIdx = html.indexOf(endTag, startIdx);
 			if (endIdx < 0) break;
 			
 			// 3. Replace with "unescaped" text
 			startIdx += startTag.length();
 			html = html.substring(0, startIdx) + "<![CDATA[" + HtmlUtils.htmlUnescape(html.substring(startIdx, endIdx)) + "]]>" + html.substring(endIdx, html.length());
 			
 			// 5. Repeat for all occurrences
 			startIdx = html.indexOf(startTag, endIdx + endTag.length());
 		}
		return html;
	}
`

**Comment by sunitapatro** [comment]
I too faced this issue. Any update whether this is going to be fixed?

**Comment by saiyinleung** [comment]
My use case 
I have a page that contains CDATA
I used jsoup to parse and update some other tags.
Pass along the updated page (toString()) 
But all the CDATA are gone... which is not what I desired..

Because of this, I simply have to give up using jsoup.

**Comment by Ghouz** [comment]
This also was a problem for me.

The workaround by @jonada is working for me, thank you very much for that.

**Comment by jhy** [comment]
Thanks, this is implemented now.

**Comment by anilktalla** [comment]
@jhy , Please let me know when this fix will be available in maven repository.

**Comment by hoblerone** [comment]
I was surprised to see the changes missing in the current 1.11.2 jar. Looking at the history it looks like it was commited AFTER the release, so it's not yet part of the released version.

Do you have plans for another release (soon) that includes the commit? I'd also love to be able to add explicit new CDATA sections to XHTML documents. Is this possible by manually creating CDataNodes and adding them?

**Comment by hoblerone** [comment]
Regarding my second question: adding CDataNodes to the DOM works nicely and produces the desired output.

**Comment by yury-alpatov** [comment]
Why it’s closed? It’s doesn’t work even in latest version of jsoup.

Document document = Jsoup.parse(xhtml, "", Parser.xmlParser());
