### ISSUE TITLE
Tag to lower case

### ISSUE THREAD

**Issue by lgabardos** [jhy/jsoup#407]
Hi,

I planned to use JSoup in order to clean my XML.

But, with this library, it always transform tags in lowercase... and I really need to keep my tags like they were.

So, I suggest a  thing:
In org.jsoup.parser.Tag, add 

public static boolean TAG_TO_LOWERCASE = true;

And after, when the tagName is lowercased, we have to check if TAG_TO_LOWERCASE is true, like that

if (Tag.TAG_TO_LOWERCASE) {
	tagName = tagName.toLowerCase();
}

If the user want to parse (or clean) XML, before processes, we just need to set 
Tag.TAG_TO_LOWERCASE = false;

And, it's good.

What do you think about that ?

**Comment by Elinow** [comment]
Agree it is required. By specification XML tags are case sensitive.

**Comment by jhy** [comment]
You can now control case sensitivity / normalization with ParseSettings. https://github.com/jhy/jsoup/commit/e38b916ba1ebd3f5c00a6b6b8e77a4cdfea2800f
