### ISSUE TITLE
Does not auto-detect undeclared character sets

### ISSUE THREAD

**Issue by jiminoc** [jhy/jsoup#41]
When looking at: http://money.cnn.com/2010/10/25/news/companies/motley_crue_bp.fortune/index.htm?section=money_latest the umlaut character is being picked up in the paragraph text correctly as htmlentities but if you grab the title it's showing up as invalid unicode characters. 

doc.getElementsByTag("title").first().text();

**Comment by jhy** [comment]
Well it's been a while (!) and I haven't seen much of a problem from this to warrant adding the complexity of a more complete auto-detect mechanism. Will close this, but happy to review.
