### ISSUE TITLE
descend selector does not work for a special case

### ISSUE THREAD

**Issue by xzer** [jhy/jsoup#417]
Assume I have the following structure:

            <div>
              <span></span>
            </div>

Then, I have a node which represent the parent div node:

            Element divElement = doc.select("div").get(0);

Then, I perform a selector again:

            Elements foundElements = divElement.select("div span");

the result of foundElements is empty.

I digged the source and found the following source starting from row 59 of StructuralEvaluator:

            while (parent != root) {
                if (evaluator.matches(root, parent))
                    return true;
                parent = parent.parent();
            }

I believe that the right way of this loop should be as following:

            do {
                if (evaluator.matches(root, parent))
                    return true;
                parent = parent.parent();
            }while (parent != root);

**Comment by jhy** [comment]
Fixed by #619
