### ISSUE TITLE
JSoup.isValid with Whitelist.none() do not works in all cases

### ISSUE THREAD

**Issue by anagram3k** [jhy/jsoup#418]
The code :

  System.out.println(Jsoup.isValid("&lt;frame src=\"a.html\"&gt;", Whitelist.none()));
  System.out.println(Jsoup.isValid("&lt;iframe src=\"a.html\"&gt;", Whitelist.none()));

Returns:

true
false

Expected Result:

Should return false in both cases.

**Comment by jhy** [comment]
Thanks, this was fixed a while back. isValid now aligns fully with any changes to nodes by the Cleaner.
