### ISSUE TITLE
noscript tag in head tag

### ISSUE THREAD

**Issue by ghost** [jhy/jsoup#424]
``` html
<html>
<head>
<noscript><img src="img.jpg"/></noscript>
<title>test</title>
</head>
<body>content</body>
</html>
```

Jsoup Result:
"title" Element parent is "body".

Expected Result:
"title" parent should be "head"

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
