### ISSUE TITLE
wrong parse result when there are many unclosed labels

### ISSUE THREAD

**Issue by russellwang** [jhy/jsoup#430]
when we parse 

```
<a href="aaa"/><b/>aaa<a href="bbb"/>bbb<b><a href="ccc"/>ccc<a href="ddd"/>ddd</b>
```

the result is 

```
<a href="aaa"></a><b></b>aaa<a href="bbb"></a>bbb<b><a href="ccc"></a>ccc<a href="ddd"></a>ddd</b>
```

but actually, in a modern browser ,the result is this
![image](https://cloud.githubusercontent.com/assets/2826960/3383608/c5b3bff6-fc4d-11e3-8e5e-8c8a1d20512e.png)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
