### ISSUE TITLE
Throws 400 exception with ignoreHttpErrors set to true

### ISSUE THREAD

**Issue by tlorentzen** [jhy/jsoup#433]
There is a problem with the way Jsoup is handling urls/redirects im getting the following exception:

URL:  http://nicehair.dk?tduid=922d505a22bd7479ad4fd8d2e351259d
Exception: Server returned HTTP response code: 400 for URL: http://nicehair.dk?tduid=922d505a22bd7479ad4fd8d2e351259d

This error is returned even when ignoreHttpErrors is set to true.

If you add a trailing slash before the query parameters its working.

http://nicehair.dk/?tduid=922d505a22bd7479ad4fd8d2e351259d

This is my connect string.
Jsoup.connect("http://nicehair.dk?tduid=922d505a22bd7479ad4fd8d2e351259d")
          .header("Accept-Language","da-dk").userAgent("Mozilla").ignoreContentType(true).maxBodySize(0).timeout(25000).followRedirects(true).ignoreHttpErrors(true).execute();

**Comment by jhy** [comment]
Wrapped up in a recent commit
