### ISSUE TITLE
Parse  <p><# if>jsoup Bug</# if><p> 

### ISSUE THREAD

**Issue by guowei** [jhy/jsoup#437]
String html = "<p><# if>jsoup Bug</# if><p>";
Document dd = Jsoup.parse(html);
System.out.println(dd.html());

Result:
"<p><# if>jsoup Bug
   </p>"

Why is this the output ？
I ask for help  ， Thank you ！

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
