### ISSUE TITLE
JSoup parsing unclosed tags (continued)

### ISSUE THREAD

**Issue by philippbc** [jhy/jsoup#451]
Similar to this issue (https://github.com/jhy/jsoup/issues/313), the handling of unclosed tags is yet not perfect. Consider the below examples:

```
String html = "<p>textextext<iframe frameborder=\"0\" height=\"420\"</p>";
Document doc = Jsoup.parse(html);
System.out.println(doc);
```

The broken iframe tag is correctly closed:

```
<html>
 <head></head>
 <body>
  <p>textextext<iframe frameborder="0" height="420" <=""></iframe></p>
 </body>
</html>
```

Yet, if I add an enclosing div tag:

```
String html = "<div><p>textextext<iframe frameborder=\"0\" height=\"420\"</p></div>";
Document doc = Jsoup.parse(html);
System.out.println(doc);
```

The broken iframe tag is wrongly closed after the previously enclosing div tag.

```
<html>
 <head></head>
 <body>
  <div>
   <p>textextext<iframe frameborder="0" height="420" <="">&lt;/div&gt;</iframe></p>
  </div>
 </body>
</html>
```

Firefox correctly renders the broken iframe as text. I think this solution is the most appropriate one, since it is impossible to know what the broken iframe was supposed to contain.

Either way, the expected behaviour would be to either fix or render as text anything between the last correct opening tag and the first correct corresponding closing tag. Tags outside of these two tags should not be affected by error correction (in this case, the div tags).

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
