### ISSUE TITLE
Is baseUri a URI or URL?

### ISSUE THREAD

**Issue by cowwoc** [jhy/jsoup#453]
Jsoup.parse() defines `baseUri` as `The URL where the HTML was retrieved from, to resolve relative links against.`

Problem is, a file's URL and URI are not necessarily identical (URI parsing rules are more stringent). So, is this parameter really a URI? Or is it a URL?

If it's the former, I would replace `URL` by `URI` in the Javadoc.
If it's the latter, I would rename the parameter to `baseUrl`.

Or better yet, add a method that actually takes a `URL` or `URI` instead of a `String`.

**Comment by cowwoc** [comment]
@jhy No response?

**Comment by jhy** [comment]
Sorry, don't know what happened to my text. It's effectively interchangable
in this implementation. Haven't seen issues from it other than this one.
