### ISSUE TITLE
Get Cookies value

### ISSUE THREAD

**Issue by gwuhaolin** [jhy/jsoup#456]
# Here is the server's response(Use Charles get it):

HTTP/1.1 302 Moved Temporarily
X-Powered-By: Servlet/2.5
Server: Sun Java System Application Server 9.1_02
Set-Cookie: JSESSIONID=57dacb614d9c6fc19c1d4bf155f9; Path=/ccnuxg
Set-Cookie: SECURITY_AUTHENTICATION_COOKIE=null; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/ccnuxg
Set-Cookie: SECURE_AUTH_ROOT_COOKIE=null; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: SECURITY_AUTHENTICATION_COOKIE=1771d2220bfc52209255b80905ddb0ec; Path=/ccnuxg
Set-Cookie: SECURE_AUTH_ROOT_COOKIE=1771d2220bfc52209255b80905ddb0ec; Path=/
Location: http://202.114.32.143/ccnuxg/application/main.jsp
Content-Type: text/html
Content-Length: 0
Date: Tue, 02 Sep 2014 08:31:41 GMT
# But when I debug jsoup,I get this:

![screen shot 2014-09-02 at 21 01 44](https://cloud.githubusercontent.com/assets/5773264/4118472/99585c2a-32a1-11e4-8a9e-6b51934c3208.png)
the cookies value of SECURITY_AUTHENTICATION_COOKIE and SECURE_AUTH_ROOT_COOKIE is null.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
