### ISSUE TITLE
Attribute selector selects wrong element 

### ISSUE THREAD

**Issue by hampelratte** [jhy/jsoup#461]
jsoup version 1.7.3

The problem is the use of Matcher.find() in class Evaluator.AttributeWithValueMatching. It returns a match for childClassWrong for the pattern childClass, which is wrong in terms of the CSS attribute selector ~= . I think a more sofisticated regex and the use of Matcher.matches() is necessary.

Here is a short, self contained, compilable example:

``` java
package com.example.jsoup.sscce;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

public class AttributeSelectorSscce {
    // @formatter:off
    private static final transient String HTML = 
            "<div class=\"parentClass anotherParentClass\">\n" + 
            "    <div id=\"wrong_target\" class=\"childClassWrong\">\n" + 
            "        <div id=\"target\" class=\"childClass childClassAnother\"></div>\n" + 
            "    </div>\n" + 
            "</div>\n";
    // @formatter:on

    public AttributeSelectorSscce() {
        Document doc = Jsoup.parse(HTML);
        Element elem = doc.select("div[class~=parentClass] div[class~=childClass]").first();
        System.out.println(HTML);
        System.out.println();
        System.out.println(elem.id() + " " + elem.className());
    }

    public static void main(String[] args) {
        new AttributeSelectorSscce();
    }
}
```

**Comment by jhy** [comment]
Hmmm. Problem here is that it is deliberately implemented and defined in Selector as a regex matcher. Not a word match (like it actually is in CSS). I don't think we can change it now. You can use \b matchers to force it to a word.

If you have a suggestion on how to define a "true" word attribute match selector, keen to hear it.

**Comment by hampelratte** [comment]
That's what I assumed. I only had a short look at the code and saw, that the matching was done in a generic way. I had the hope, that you would have had an idea, how to solve this. The word boundary matcher might be a solution, thanks for the hint. Never used that before.
I could solve my original problem with a simpler selector and some node traversing and attribute checking, so it wasn't a big deal for me. I just wanted you to know, that there is a flaw.

Other than that, great library. I'm using it in several private / hobby projects. Before I used the parser from htmlparser.org, but your api is simpler and the css selectors work better. So, keep up the good work.

Leaving this issue open, though. Your decission ;)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
