### ISSUE TITLE
viewBox converted into viewbox in svg files

### ISSUE THREAD

**Issue by Sharcoux** [jhy/jsoup#466]
Hi,
Using JSoup, the attribute "viewBox" is converted into "viewbox" and this causes SVGPanel from SVGSalamander not recognizing it. I don't know if I should consider this a problem with JSoup or SVGSalamander, but I think that Jsoup should leave quiet the viewBox attribute if possible.

Thanks anyway for your useful library !

**Comment by jhy** [comment]
You can use ParseSettings to control case normalization now. Thanks.
