### ISSUE TITLE
Problem parsing double quoted attribute values containing double quotes

### ISSUE THREAD

**Issue by Cimballi** [jhy/jsoup#468]
Of course the original HTML is not correct, but it wold be very cool if JSoup could handle that :
< img src="http://www.marianne.net/photo/art/default/985978-1169260.jpg" alt="Budget : la France va-t-elle se faire "corriger" par Bruxelles ?" title="Budget : la France va-t-elle se faire "corriger" par Bruxelles ?" />

You can see that the word corriger is enclosed in double quotes.

As of version 1.7.2 JSoup output is :
< img src="http://www.marianne.net/photo/art/default/985978-1169260.jpg" alt="Budget : la France va-t-elle se faire " corriger"="" par="" bruxelles="" ?"="" title="Budget : la France va-t-elle se faire " />

It's a bit strange beacuse the output is still incorrect. This should not happen. A "not so bad" solution would be that JSoup remove the whole attribute. The best solution would be that jsoup encodes the inner double quotes.

Thanks !

**Comment by jhy** [comment]
How would anything ever work like that? And this is how browsers parse also, which is the intent of jsoup. Author would have seen the data is incorrect.
