### ISSUE TITLE
val(string) on a select element should select the relevant option rather than setting the value attribute

### ISSUE THREAD

**Issue by jollytoad** [jhy/jsoup#475]
Currently Element.val(String) just sets a 'value' attribute on a 'select' element.
It should really, set the 'selected' attribute on the 'option' elements inside the 'select'.

Element.val() should also find the selected option and return the value of that rather the 'value' attribute of the select.

There is also the matter of handling multiple selects in the above to consider too.

I'll try to post some code if I get time.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
