### ISSUE TITLE
The width and height property of the HTML element 

### ISSUE THREAD

**Issue by jasdeep** [jhy/jsoup#476]
Is there a possibility of having a width and height property for the HTML document/element as there are in javascript:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.offsetWidth
https://developer.mozilla.org/en-US/docs/Web/API/Element.clientWidth

Such that one can know the width or height if the document is to converted to some other format.

Or is there any workaround to deduce this with the current implementation?

**Comment by Chhavi24** [comment]
Any update on this now ?
