### ISSUE TITLE
"charset=latin-1" is not properly detected

### ISSUE THREAD

**Issue by Rico99** [jhy/jsoup#48]
From the mailing list: http://groups.google.com/group/jsoup/browse_thread/thread/09d8325e0e5a46c6#

I just downloaded jsoup 1.3.3 and gave it a try. It works great for  
UTF-8 encoded websites, but dies for LATIN-1 encoded sites. 
The site that caused the error below is: 
        http://www.macupdate.com 
In the html source you'll find this line: 
        <meta http-equiv="Content-Type" content="text/html; charset=latin-1" /> 
Here the full stacktrace: 
Exception in thread "main"  
java.nio.charset.UnsupportedCharsetException: LATIN-1 
        at java.nio.charset.Charset.forName(Charset.java:505) 
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:58) 
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java: 
376) 
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:122) 
        at rgse.test.Main.main(Main.java:15) 
System: 
        Mac OS X 10.5 
        Java 1.6
        jsoup 1.3.3

Reason: 
The general problem: 
In DateUtil.java, line 56, the charset name is identified as  
"LATIN-1". That name is handed to Charset.forName(). However,  
"LATIN-1" does not seem to be recognized as valid character set alias  
as defined in http://www.iana.org/assignments/character-sets 
The correct character set alias for "LATIN-1" should be "latin1". I  
wrote a small test program and the following line runs without problems: 
        Charset c = Charset.forName("latin1"); // WORKS 
        Charset c = Charset.forName("LATIN-1"); // FAILS 
Solution: 
Maybe somewhere in DateUtil.getCharsetFromContentType()? At least this  
is where the character set is parsed and turned into all uppercase  
(breaks for latin1). 
Thanks! 
Rico

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
