### ISSUE TITLE
FormElement's formData ignores input checkbox checked without value.

### ISSUE THREAD

**Issue by Freddy12** [jhy/jsoup#489]
When there is input:         
```
<input type="checkbox" name="testCheckBox" checked="checked" />
```
The "formData()" of FormElement's ignores that default value which should be "on" as submitted by browsers.

HTML fragment:
```
<html>
    <head>
        <title>Test</title>
    </head>
    
    <body>

    <form name="myForm" method="POST">
        <input type="checkbox" name="testCheckBox" checked="checked" /> Something<br/>

        <input type="submit" value="Submit" />
    </form>

    </body>
</html>
```

When submiting from Firefox it sends to sever: testCheckBox=on

Java code:
```
    public static void main(String[] args)
    {
        final String html = "<html>\n"
                            + "    <head>\n"
                            + "        <title>Test</title>\n"
                            + "    </head>\n"
                            + "    \n"
                            + "    <body>\n"
                            + "\n"
                            + "    <form name=\"myForm\" method=\"POST\">\n"
                            + "        <input type=\"checkbox\" name=\"testCheckBox\" checked=\"checked\" /> Something<br/>\n"
                            + "\n"
                            + "        <input type=\"submit\" value=\"Submit\" />\n"
                            + "    </form>\n"
                            + "\n"
                            + "    </body>\n"
                            + "</html>";

        final Document document = Jsoup.parse(html);

        final FormElement formElement = (FormElement) document.select("form[name=myForm]").first();

        for (Connection.KeyVal keyVal : formElement.formData())
        {
            System.out.println(keyVal.key() + "=" + keyVal.value());
        }

    }
```

Output: testCheckBox=

Expected output: testCheckBox=on

Seems like Jsoup doesn't add default value which is sent by browsers. The "submit()" method from FormElement also uses "formData()" method to get form's submission parameters. By sending the empty String for checkbox the server acts as it's not checked when in fact it was checked.

Also while testing noticed that it doesn't check the checkbox'es at all. If there is checkbox with value, but not checked, it will get the value no matter what, for example:
``` 
        <input type="checkbox" name="textCheckBox2" value="testVal" /> 
``` 

This affects radio buttons as well. Not selected radion buttons should not be sent to server, but formData() add their values anyway.

I'm not sure if that's done on purpose, but submit() method will get wrong parameters for submission since not checked input value is not sent to server at all.

Moreover type button value and "disabled" inputs are not sent to server as well (by browsers). 

Looked at the source, one extra else if before the final else in "formData()" method could solve this:
```
else if ("input".equals(el.tagName())) {
                // Not disabled? Ignore disabled inputs.
                if(!el.hasAttr("disabled")) {
                
                    // Deal with checkbox and radio (not checked should not be added to avoid sending to server)
                    if("checkbox".equals(el.attr("type")) || "radio".equals(el.attr("type"))) {
                    
                        // Checked, but no value? Default should be "on".
                        if(el.hasAttr("checked") && !el.hasAttr("value")) {
                            data.add(HttpConnection.KeyVal.create(name, "on"));
                        } 
                        // Checked? Add it's value
                        else if(el.hasAttr("checked")) {
                            data.add(HttpConnection.KeyVal.create(name, el.val()));
                        }
                    } 
                    // Buttons should be ignored.
                    else if(!"button".equals(el.attr("type"))){
                        data.add(HttpConnection.KeyVal.create(name, el.val()));
                    }
                }
            }
``` 

One more thing. If form has multiple type submit inputs, only the clicked input's value should be sent to server, but I have no idea how this could be implemented. Sending all submit input's values can change the server's logic and be bad (result not as expected).

**Comment by jhy** [comment]
I've implemented the "checked" attribute recently. Please feel free to make big changes to improve it.

**Comment by jhy** [comment]
Thanks for the report

**Comment by spark-streamingpreoccupi** [comment]
Look here for the answer https://opencodes.space/questions/what-is-the-method-for-setting-a-default-value-for-a-disabled-input
