### ISSUE TITLE
How to find the position of the characters of a tag ?

### ISSUE THREAD

**Issue by leonelag** [jhy/jsoup#498]
Suppose we are parsing the following snippet of HTML:

```
<html><body><h1 style='font-weight: bold'>Hello world</h1><hr /></body></html>
```

After parsing, I would like to know at what character the h1 header starts. In this case, the opening tag happens from characters 12 (includes) to 42 (exclusive); the closing tag is from characters 53 to 58.

We could also look at the H1 tag as everything from characters 12 to 58, or says that its contents (the text 'Hello world') span from character 42 to 53.

Is there any place in the API where we could find this information ?

If I were to fork in order to add this information, any tips on where to start and pitfalls to avoid ?

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
