### ISSUE TITLE
Unicode Characters are not available for browser to render (&#149; and &#148;)

### ISSUE THREAD

**Issue by jjjworry** [jhy/jsoup#500]
String content = "<ul><li> &#149; Ongoing promotions</li> <li> &#149; Complimentary shipping on orders</li> </ul>";
			doc = Jsoup.parse(content, "" );
			Document.OutputSettings settings = new Document.OutputSettings();
			settings.prettyPrint(doc.outputSettings(settings);
                        doc.toString() --> no unicode content

In the Tokenizer code, i see that it is getting the numeric values but the call to Character.toChars is not returning anything of value as it is below the 127/128 values. Options?

**Comment by jhy** [comment]
Must have been fixed ages ago when I redid the Entities and decoding. See https://try.jsoup.org/~7E9D1UD-Zsig6G8Gx-zrsaSYBZA

(Though not sure why you'd want to have Message Waiting and Cancel control characters in your HTML...)
