### ISSUE TITLE
Performance issue in Parser.parseBodyFragment for nodes with many children

### ISSUE THREAD

**Issue by kguelzau** [jhy/jsoup#504]
We use jsoup to whitelist allowed html tags from html emails:

    Jsoup.clean(html, Whitelist.relaxed()
      .addTags("span")
      .addTags("font")
      .addTags("s")
      .addAttributes(":all", "style")
      .addAttributes("table", "height", "border", "bgcolor", "cellspacing", "cellpadding")
      .addAttributes("th", "height", "bgcolor")
      .addAttributes("tr", "width", "height", "bgcolor")
      .addAttributes("td", "height", "bgcolor")
      .addAttributes("font", "face", "size", "color")
      .addAttributes("a","name","target")
      .addAttributes("img", "border")
      .addProtocols("img", "src", "cid"));

We got some huge mails with a lot of logging output in the html body.
The body element contains ~ 270k childnodes (text, br, hr, h1).

For this mails our JVM was stuck in the jsoup code for about 10 minutes (high CPU + very high garbarge). :-(
Here is a small JUnit-Test to show this behavior. The test should finish in under 1 second.
On my machine it takes about 4 seconds.

    public class JsoupTest {
      private static StringBuilder longBody = new StringBuilder(500000);
      @BeforeClass
      public static void setup () {
        for (int i = 0; i < 25000; i++) {
          longBody.append(i).append("<br>");
        }
      }
  
      @Test
      public void slow() {
        // Arrange
        // Act
        long start = System.currentTimeMillis();
        Document doc = Parser.parseBodyFragment(longBody.toString(), "");
    
        // Assert
        Assert.assertEquals(50000, doc.body().childNodeSize());
        Assert.assertTrue(System.currentTimeMillis() - start < 1000);
      }
    }

I think there are some big-o issues in Node.addChildren():

    protected void addChildren(Node... children) {
        for (Node child: children) {
            // XXX a child with a parent is removed from the old parent
            // -> ArrayList.remove() + reindexChilds() = O(2*n)
            reparentChild(child);
            childNodes.add(child);
            child.setSiblingIndex(childNodes.size()-1);
        }
    }

I was surprised to see an ArrayList for a tree like structure. Isn't a LinkedList a better option?
As a quick optimization for my use case I would suggest to create the nodeList without a parentNode or to remove the parent just before adding the node to the bodyNode.

What do you think? Is there a workaround for this behavior?

**Comment by jhy** [comment]
Thanks for your patch! From memory the reason I went with an Array vs a LinkList was that in my analysis, it was a more common use case to iterate through / query the DOM (with selectors etc) than it was to re-parent a node. And the iteration or fetch by index was faster with an array than a link list.
