### ISSUE TITLE
Update Selector API doc to indicate select may throw SelectorParseException

### ISSUE THREAD

**Issue by savatgithub** [jhy/jsoup#507]
http://jsoup.org/apidocs/org/jsoup/select/Selector.html

select API does not indicate that it may throw SelectorParseException. Please update the doc. An example of this use case would be the following query:

```
a[href=http://jsoup.org/]]

<html>
 <head> 
  <title>Try jsoup</title> 
 </head> 
 <body> 
  <p>This is <a href="http://jsoup.org/]">jsoup</a>.</p>   
 </body>
</html>
```

**Comment by jhy** [comment]
Thanks! Fixed.
