### ISSUE TITLE
parse issue: self closing tag not parsed correctly

### ISSUE THREAD

**Issue by xhite** [jhy/jsoup#511]
\<img src="image.jpg"/\>
after parsing:
toString() should return
\<img src="image.jpg"/\>
or \<img src="image.jpg"\>\</img\>

but returns 
\<img src="image.jpg"\>
with no closing tag

**Comment by martinmatthias** [comment]
I can confirm that this bug doesn`t occur with 1.7.3
This version is still available in Maven Central.

**Comment by jhy** [comment]
I don't really understand this bug. There's no parsing issue. And the serialization is correct. HTML does not use self closing tags, or have empty tags needing a closing tag. Those are hang-overs from the bad old XHTML days. If you don't want HTML output serialization, use the XML serializater.

**Comment by victorskl** [comment]
All you want to get is just well-formed xhtml (like it does in 1.7.3) with latest Jsoup 1.8.2, then parse two times.
```
// first parse and clean up raw html
Document saneHtml = Jsoup.parse(htmlTxt);

// optionally perform whitelist
Whitelist whitelist = Whitelist.relaxed();
whitelist.addTags("style");
whitelist.addAttributes(":all", "style");
whitelist.addAttributes(":all", "class");
whitelist.addProtocols("img", "src", "data"); //for base64 encoded images
String saneHtmlTxt = Jsoup.clean(saneHtml.toString(), whitelist);

// then make well-formed xhtml and closing tags with xmlParser
saneHtml = Jsoup.parse(saneHtmlTxt, "", Parser.xmlParser()); 
saneHtml.outputSettings().escapeMode(Entities.EscapeMode.xhtml);

System.out.println(saneHtml.toString());
```

**Comment by jhy** [comment]
jsoup is HTML 5. HTML 5 does not do self closing tags. There's no need in HTML for that.

If you want old-school syntax, that is what Document.OutputSettings.xml is for.

http://jsoup.org/apidocs/org/jsoup/nodes/Document.OutputSettings.html#syntax(org.jsoup.nodes.Document.OutputSettings.Syntax)

public Document.OutputSettings syntax(Document.OutputSettings.Syntax syntax)
Set the document's output syntax. Either html, with empty tags and boolean attributes (etc), or xml, with self-closing tags.

**Comment by victorskl** [comment]
Thanks jhy. Yes, setting output syntax to xml works.

```
Document saneHtml = Jsoup.parse(htmlTxt);
saneHtml.outputSettings().syntax(Document.OutputSettings.Syntax.xml);
saneHtml.outputSettings().escapeMode(Entities.EscapeMode.xhtml);
System.out.println(saneHtml.toString());
```

**Comment by jhy** [comment]
Cool, thanks. I thought at one point I'd updated try.jsoup.org to have that syntax option, to make it more visible. Guess I just dreamt that :) I should add in most of the output settings.

**Comment by sbe1** [comment]
None of these solutions work. Is there a solution to this. I'm trying to clean MathML embedding in HTML and JSoup keeps trying to close unclosed MathML tags like <infinity/>

Does not work
```
        final Document doc = Jsoup.parse(str, "UTF-8");
        final Document.OutputSettings settings = doc.outputSettings()
                .syntax(Document.OutputSettings.Syntax.xml)
                .escapeMode(EscapeMode.xhtml).charset(AppLiterals.ASCII).prettyPrint(false);
```
Also does not work:
```
        final Document doc = Jsoup.parse(str, "", Parser.xmlParser());
        final Document.OutputSettings settings = doc.outputSettings()
                .syntax(Document.OutputSettings.Syntax.xml)
                .escapeMode(EscapeMode.xhtml).charset(AppLiterals.ASCII).prettyPrint(false);
```

Note: To be clear, I have a carefully compiled whitelist of all MathML tags and attributes. JSoup cleans the HTML properly and leaves all the MathML tags intact except for the self-closing ones. If you add closing tags to self-closing MathML tags, it is no longer valid MathML and is not parsable by math libraries like MathJax.
