### ISSUE TITLE
Auto-calculate Content-Length header

### ISSUE THREAD

**Issue by nathanila** [jhy/jsoup#514]
Please add a method (e.g. autoContentLength(boolean)) to Connection and hence Connection.Request.  If the boolean is set to true, then Jsoup will calculate the length of the content (i.e. data) and add the Content-Length header to the request.

Of course, there should be a method to get the current autoContentLength setting in Connection.Request.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
