### ISSUE TITLE
Option to "escape" unwanted tags instead of "removing" while doing Jsoup.clean()

### ISSUE THREAD

**Issue by khanchandaniprakash** [jhy/jsoup#515]
Currently when we try to clean the html it removes the unwanted tags.

Instead we can provide an option in `Whitelist` to either remove the tags or escape it instead, may be something like `whitelist.escapeUnwantedTags(true)`

```
String unsafeHTML = "<p>Paragraph containing <a href='http://github.com/jhy/jsoup' title=\"Jsoup on Github\">link</a></p>";
Whitelist whitelist = new Whitelist();

whitelist.addTags("a");
whitelist.addAttributes("a", "href", "title", "id", "class", "target")
    .addProtocols("a", "href", "http", "https");

Jsoup.clean(unsafeNewsHTML, whitelist, new OutputSettings().prettyPrint(false));
```

Original HTML string passed:

```
<p>Paragraph containing <a href='http://github.com/jhy/jsoup' title=\"Jsoup on Github\">link</a></p>
```

Output after cleaning:

```
Paragraph containing <a href='http://github.com/jhy/jsoup' title=\"Jsoup on Github\">link</a>
```

It removes the `<p>` tag. But if we set `escapeUnwantedTags` to `true` it should escape it like `&lt;p&gt;`.

So the required output might become:

```
&lt;p&gt;Paragraph containing <a href='http://github.com/jhy/jsoup' title=\"Jsoup on Github\">link</a>&lt;/p&gt;
```

**Comment by hans123456** [comment]
Upping the post =)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
