### ISSUE TITLE
Too much trimming in AttributeKeyPair

### ISSUE THREAD

**Issue by krystiangorecki** [jhy/jsoup#516]
```
package jsoupTooMuchTrimming;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

 public class TooMuchTrimming {
    public static void main(String[] args) {
        String html = "<a title=\"PC Download\">i want to match this link</a>"
                + "<a title=\"PC Access Code\">this link as well</a>"
                + "<a title=\"PC Something Else\">and this one</a>"
                + "<a title=\"PC/MAC\">but NOT this one</a>";
        Document doc = Jsoup.parseBodyFragment(html);
        // selecting tags having titles starting with "PC "
        Elements elements = doc.select("a[title^=\"PC \"]");
        System.out.println("I expect 3 elements, but jsoup 1.8.1 selects "
                + elements.size());
    }
}
```

I love how you trim and clean everything when parsing cssQuery, but this time it's too much and the result differs from what I expected. There's too much trimming in `org.jsoup.select.Evaluator.AttributeKeyPair.AttributeKeyPair(String, String)`
line 284: `this.value = value.trim().toLowerCase();`
"PC " becomes "pc"

**Comment by krystiangor** [comment]
How about replacing

    if (value.startsWith("\"") && value.endsWith("\"")) {
        value = value.substring(1, value.length()-1);
    }
    this.value = value.trim().toLowerCase();

with

    if (value.startsWith("\"") && value.endsWith("\"")) {
        	value = value.substring(1, value.length()-1);
        	this.value = value.toLowerCase();
    } else {
        	this.value = value.trim().toLowerCase();
    }

?
It would still trim unquoted values, but queries within quotes would remain unchanged.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
