### ISSUE TITLE
Selector.select(String query, Iterable<Elements> roots) performance regression

### ISSUE THREAD

**Issue by kzn** [jhy/jsoup#518]
Hello!

There is a performance regression from selecting elements from multiple roots.
It is caused by reparsing of the query string for every root. Which leads to signifiant performance degradation you try to query large number of roots.

The diff is:
<pre>
--- a/src/main/java/org/jsoup/select/Selector.java
+++ b/src/main/java/org/jsoup/select/Selector.java
@@ -119,10 +119,11 @@ public class Selector {
     public static Elements select(String query, Iterable<Element> roots) {
         Validate.notEmpty(query);
         Validate.notNull(roots);
+        Evaluator evaluator = QueryParser.parse(query);
         LinkedHashSet<Element> elements = new LinkedHashSet<Element>();
 
         for (Element root : roots) {
-            elements.addAll(select(query, root));
+            elements.addAll(select(evaluator, root));
         }
         return new Elements(elements);
     }
</pre>

**Comment by jhy** [comment]
Thanks, good idea
