### ISSUE TITLE
Deep cloning doesn't properly handle the class attribute

### ISSUE THREAD

**Issue by nseniak** [jhy/jsoup#519]
When cloning an element that contains a child with a class attribute, the value of the class attribute of the child is not properly copied and is still shared with the original element.

Here's a Groovy script that demonstrates the problem:

doc = org.jsoup.Jsoup.parse("<font class=\"someclass\"></font>")
element = doc.getElementsByTag("font")
System.out.println("Should be true: " + element.hasClass("someclass"));
elementClone = doc.clone().getElementsByTag("font");
element.removeClass("someclass")
System.out.println("Should be false: " + element.hasClass("someclass"));
System.out.println("Should be true: " + elementClone.hasClass("someclass"));

The output is:

Should be true: true
Should be false: false
Should be true: false // Bug

The problems seems to be that the Node#clone method uses doClone instead of clone to copy children, and doClone is not overridden in subclasses so any field in a Node subclass (like Element#className) is not properly handled.

**Comment by jhy** [comment]
@nseniak I can't repro this. Added the linked test case and it passes. Can you review?

**Comment by nseniak** [comment]
@jhy The first line of my test case is incorrect indeed. Please replace it with:

doc = org.jsoup.Jsoup.parse("&lt;font class='someclass'&gt;&lt;/font&gt;")

(I didn't escape &lt;&gt; when I typed it the first time).

**Comment by jhy** [comment]
Sure, but I included similar in the test case I added. I don't think that's
it.

**Comment by nseniak** [comment]
This is weird. I wrote a JUnit test case and it does fail.

Which version of Jsoup are you testing against? I'm using version 1.8.1.

 Are you doing the same tests as in the test case below? Can you send me
your test code?

Here's the test I'm running:

import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import static junit.framework.TestCase.assertFalse;
import static org.junit.Assert.assertTrue;

public class Test {

@org.junit.Test
public void test() {
Document doc = org.jsoup.Jsoup.parse("<font class='someclass'></font>");
Element element = doc.getElementsByTag("font").first();
assertTrue(element.hasClass("someclass"));
Element elementClone = doc.clone().getElementsByTag("font").first();
element.removeClass("someclass");
assertFalse(element.hasClass("someclass"));
assertTrue(elementClone.hasClass("someclass"));
}

}

**Comment by jhy** [comment]
I'm away from my environment so can't review right now. The test case I ran
(and added to jsoup) is at
https://github.com/jhy/jsoup/commit/0c10dbffb475febe05ebaf074278e5d5aa81e32c

I tested against mainline. There hasn't been any substantial changes to
clone since 1.7 when it was refactored to use a traversor.

Can you check against mainline? And see if I missed something in my test?

**Comment by nseniak** [comment]
I tested against mainline and indeed it works. I found why: the field
Element#classNames was removed in commit
https://github.com/jhy/jsoup/commit/8c673ddc1357f00009e38cb800c1c6ebb6ee4beb#diff-e30816f90d9a4cf5d9f4d43079d2d36c
<http://s.bl-1.com/h/nzW3TC8?url=https://github.com/jhy/jsoup/commit/8c673ddc1357f00009e38cb800c1c6ebb6ee4beb#diff-e30816f90d9a4cf5d9f4d43079d2d36c>
("Element.classNames() must not be cached"). Which fixes the bug. So it's
all good.

BTW: **thank you** for jsoup. Great tool.

-- Nitsan

**Comment by jhy** [comment]
Great, thanks for digging into it.
