### ISSUE TITLE
I have a problem about the jsoup parser html tag with "class"

### ISSUE THREAD

**Issue by withnoword** [jhy/jsoup#520]
If html content is:
&lt;a title="" href="http://*.html" target="_blank" class="lk-ellipsis"&gt;
 								sometext							&lt;/a&gt;
I cannt find anything about it in document parsered: 
I think "\n" cannot be parsered absolutely;
Maybe

**Comment by krystiangor** [comment]
Don't worry. Your '\n' is still there :)

    package jsoup.issue520;

    import org.jsoup.Jsoup;
    import org.jsoup.nodes.Document;
    import org.jsoup.select.Elements;

    public class JsoupIssue520 {
    	public static void main(String[] args) {
   		String html = "<a title=\"\" href=\"http://*.html\" target=\"_blank\" class=\"lk-ellipsis\">"
				+ "\nsometext </a>";
    		Document doc = Jsoup.parseBodyFragment(html);
    		Element a = doc.select(".lk-ellipsis").first();
    		System.out.println("white characters are trimmed here: " + a.text());
    		System.out.println("also invisible here: " + a.textNodes().get(0).text());
    		System.out.println("but here you can see it: " + a.textNodes().get(0).getWholeText());
    	}
    }

**Comment by withnoword** [comment]
thank you very mach;
I have find the mistake in my project;
