### ISSUE TITLE
Jsoup.connect().get() takes very long time in android 4.4 versions

### ISSUE THREAD

**Issue by mikell82** [jhy/jsoup#522]
Hi,
the execution time of "Jsoup.connect().get()" takes about 10 sec for my Android 4.1
but when i test on a device that has Android 4.4 it takes x10 times more than that to complete

PLEASE HELP

**Comment by jhy** [comment]
I haven't been able to repro this. Works fast for me on 4.4 (generally 20ms to 150ms depending on server and page). I've improved perf on Android substantially, but not by 10 times. If you still have issues, please provide repro steps, and timing that splits out the difference between the server hit and the parse.
