### ISSUE TITLE
[bug]nth-last-child(-n+2)

### ISSUE THREAD

**Issue by zhonghanyc** [jhy/jsoup#524]
jsoup-1.8.1-javadoc said
"tr:nth-last-child(-n+2) returns the last two rows of a table",in fact,":nth-last-child(-n+2)"equals :nth-last-child(1n+2),but not :nth-last-child(-1n+2)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
