### ISSUE TITLE
Jsoup not retaining &lt in data attributes

### ISSUE THREAD

**Issue by sandev** [jhy/jsoup#528]
Jsoup not retaining &lt in data attributes value if there is &lt;

In the example below &amp;lt; is converted to < in the output after parsing. 
Please let me know how to retain it. 
Example:
http://notes.io/Gww
@uggedal 
@krystiangor 
@tc 
@bbeck

**Comment by krystiangor** [comment]
Can anyone explain why do we parse html entities within org.jsoup.parser.TokeniserState.AttributeValue_doubleQuoted? Shouldn't all quoted values be left unchanged?

**Comment by sandev** [comment]
@krystiangor 

I think the correct fix should be something like below:
I am testing it out to see if it is good in all scenarios. Please let me know your opinion.

case '<':
            		// xhtml and in attribute
            		if (inAttribute && escapeMode == EscapeMode.xhtml)
            			accum.append("&lt;");
            		// NOT in attribute
            		else if (!inAttribute)
            			accum.append("&lt;");
            		 // NON XHTML  and In attribute
            		else
            			accum.append(c);
            		break;

**Comment by krystiangor** [comment]
Tests run: 11, Failures: 3, Errors: 0, Skipped: 1, Time elapsed: 0.107 sec <<< FAILURE!
    testOutputEncoding(org.jsoup.nodes.DocumentTest)  Time elapsed: 0.004 sec  <<< FAILURE!
    org.junit.ComparisonFailure: expected:<...p title="π">π &amp; [&lt;] &gt; </p>> but was:<...p title="π">π &amp; [<] &gt; </p>>

**Comment by jhy** [comment]
It took me a while to understand this -- the allowed characters in an XML attribute are different to HTML

HTML: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
XML: http://www.w3.org/TR/xml/#NT-AttValue
