### ISSUE TITLE
Problem with Android and chunked http transfer encoding

### ISSUE THREAD

**Issue by iMineLink** [jhy/jsoup#530]
I think that Jsoup on Android (from Jelly Bean to Lollipop) can't handle correctly an http chunked response.
The same code that I'm using on Android, works fine on Java 7 desktop.
I already tried so many different things on the Android code that I can be almost sure that the server is not dealing in different ways when receiving request from the desktop code and the Android one.
I get no errors on Android though, but I can access only the very first part of the html response given me from the server.
On desktop as I have already said, I can access the whole page.

Here's the server response (to my POST request), that leads to chunked http transfer encoding:
HTTP/1.1 200 OK
Set-Cookie: *various cookies*
Server: Apache-Coyote/1.1
Allow: GET, HEAD, POST
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=ISO-8859-1
Transfer-Encoding: chunked
Date: Mon, 23 Feb 2015 22:56:51 GMT

Last but not least, I get the same truncated response when using the last Apache HttpClient on Android, so maybe this problem is a deep one.

**Comment by jhy** [comment]
Hi,

I haven't been able to reproduce this. I hadn't heard of other issues reported on this, or come across it myself, so I wrote a specific test (in my Android jsoup benchmark tool). I verified against www.amazon.com (http & https) which I confirmed was using chunked transfer encoding, with gzip. I verified I get the full content body.

I verified on a Nexus 6 (L) and Moto G (K).

Do you have a full code snippet that I can check and try to ID what's going wrong?
