### ISSUE TITLE
meta tag is not being closed correctly

### ISSUE THREAD

**Issue by remisbaima** [jhy/jsoup#531]
The code below:
```java
public static void main(String[] args) throws Exception {
    String bodyHtml = "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />";
    System.out.println(Jsoup.parseBodyFragment(bodyHtml).select("meta"));
}
```
Produces the wrong output (you can see that the last slash was incorrectly removed):
```
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

**Comment by docbrown** [comment]
This is correct behavior. Meta elements are empty, so they don't have a closing tag in HTML.

**Comment by jhy** [comment]
Agree, thanks. You can change the formatter to xml if you want more slashes.
