### ISSUE TITLE
character ":" should be considered valid during parsing of table id

### ISSUE THREAD

**Issue by gasdia73** [jhy/jsoup#532]
With this table I get an exeption from the parser:
<table id="elencoMovimenti_elencoPaginato:elencoMovimenti" ..... </table>
the exception is :
org.jsoup.select.Selector$SelectorParseException: Could not parse query '#elencoMovimenti_elencoPaginato:elencoMovimenti': unexpected token at ':elencoMovimenti'

**Comment by adnbsr** [comment]
use **|** instead of **:** ->
```java
item.select("og|title").attr("content");
```

**Comment by jhy** [comment]
Namespaced selector
