### ISSUE TITLE
selector "h3 a" not working properly

### ISSUE THREAD

**Issue by mrbrdo** [jhy/jsoup#535]
Hello,

According to documentation the selector "h3 a" should behave the same as a normal CSS selector.
However it is not working properly for me:

```scala
div.children.select("h3 a") // results: 0
div.children.select("h3").select("a") // results: 1
div.children.select("h3 > a") // => results: 1
```

These two should return the same results, but they don't. I have the same issue with other similar selectors.

Relevant part of source HTML:
```html
<div><h3 class="r" style="line-height:normal"><a class="l" href="http://sobe-macek.si/" onmousedown="return rwt(this,'','','','2','AFQjCNGL8bH57qrT59_z0XO7HGG6eyhJog','','0CEoQoAIwAQ','','',event)">Macek Rooms</a></h3></div>
```

If needed I can provide the full HTML file.

EDIT:
I realized that `div.select("h3 a")` also works properly. In some way I get it (if `children` is used, it will only search through children). However, this is really a mess now. The problem I have with `div.select` is that it will match the current element as well (which is unlike basically any other HTML parser that supports CSS selectors). I can't understand what you were thinking. It makes me feel like smashing my monitor or throwing my computer out of the window.
Anyway, rant off, but how am I then supposed to achieve the usual behavior, such as that of jQuery for example, that is for `el.select("h3 a")` to work while **not** matching `el` (in a general case)?

**Comment by jhy** [comment]
Fixed by #619.
