### ISSUE TITLE
Using the updated code fixed from the issue #538

### ISSUE THREAD

**Issue by Vanaja1505** [jhy/jsoup#542]
How can I use this issue fixed code. Already am using the jar downloaded from http://jsoup.org/.

How Can I use the updated code as a jar?

**Comment by krystiangor** [comment]
git clone --depth=50 git://github.com/jhy/jsoup.git jhy/jsoup
    cd jhy/jsoup
    mvn package

**Comment by jhy** [comment]
Thanks

**Comment by Vanaja1505** [comment]
Thank you so much @krystiangor and @jhy
