### ISSUE TITLE
jsoup cannot parse head element

### ISSUE THREAD

**Issue by remisbaima** [jhy/jsoup#543]
Hi,
When I run (tested with jsoup v1.8.1):
```java
public static void main(final String[] args) throws Exception {
    final URL url = new URL("http://www.bosch.de/de/de/startpage_1/country-landingpage.php");
    System.out.println(Jsoup.parse(url, 10000).select("head"));
}
```
I get the wrong result:
```
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
```
If you look the HTML code you see:
```
<head>
<title>Bosch in Deutschland </title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-script-type" content="text/javascript" />
<meta http-equiv="content-style-type" content="text/css" />
...
```

Note: maybe this issue relates with #531.

**Comment by jhy** [comment]
I can't repro this. You can see for example here that jsoup is parsing the head correctly: http://try.jsoup.org/~m3PkU_UJ4sEO2xWEP43j7OqTg2Y

Make sure you set a user-agent, in case the server is returning different content based on the user agent and you're getting a bad default.

Seems unrelated to #531 which is how HTML is correctly serialized, and not related to parsing.

**Comment by remisbaima** [comment]
Which version of jsoup is used in http://try.jsoup.org ? v1.8.1 or another?

**Comment by jhy** [comment]
Yes, v 1.8.1. But in reading the HTML I don't see anything than an older
version would have had issues with either.

**Comment by remisbaima** [comment]
I also cannot reproduce it anymore. I really do not know what happened.
Thanks a lot for your support and sorry for the inconvenience.

**Comment by jhy** [comment]
Great, glad you got it sorted!
