### ISSUE TITLE
Javadoc warnings with Java 8

### ISSUE THREAD

**Issue by GerardPaligot** [jhy/jsoup#544]
Since Java 8, Java makes some checks on the javadoc when we would like compile a project but JSoup doesn't pass these checks. There are too many errors to copy/paste here but you can see them when you execute `mvn install` command with Java 8.

**Comment by jhy** [comment]
Wasn't this fixed with https://github.com/jhy/jsoup/pull/517 ? Can you
update to latest and verify?
