### ISSUE TITLE
ClassCastException at getElementsByClass

### ISSUE THREAD

**Issue by raphaelm** [jhy/jsoup#545]
I received a crash report containing the following traceback from a user:
```
java.lang.ClassCastException: java.lang.Object[] cannot be cast to org.jsoup.nodes.Node
at org.jsoup.nodes.Node.nextSibling(Node.java:497)
at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:35)
at org.jsoup.select.Collector.collect(Collector.java:24)
at org.jsoup.nodes.Element.getElementsByClass(Element.java:615)
```
By looking at ``Node.java:497``, I am unable to guess what is going wrong here.
Sadly, I have no way to achieve the HTML document. We are using jsoup 1.8.1 and to my knowledge, this only happened once.

**Comment by jhy** [comment]
Thanks for reporting. I reviewed the code and can't see how this could happen. It's a typed list.

Can you reopen if you can find repro steps?

**Comment by raphaelm** [comment]
Well, I was as surprised as you ;) I will reopen if I find a way to reproduce.
(cc @johan123)
