### ISSUE TITLE
Everything in iframe tag are recognised as characters 

### ISSUE THREAD

**Issue by ValiousSwank** [jhy/jsoup#546]
I have a problem when jsoup parse an `<iframe>` tag, between the iframe every "special" character (`<`, `>`, etc.) is escaped.

input: `<iframe><div class="css"><a href="#">link</a></div></iframe>`
Jsoup.parse creates the Document and that is the result:

```
<html>
 <head></head>
 <body>
  <iframe>&lt;div class=&quot;css&quot;&gt;&lt;a href=&quot;#&quot;&gt;link&lt;/a&gt;&lt;/div&gt;</iframe>
 </body>
</html>
```

In the [description of W3C](http://www.w3resource.com/html/iframe/HTML-iframe-tag-and-element.php) an iframe can contain inline and block level elements. So it seems to be a bug from that perspective.

Please confirm whether it is a bug or not.

**Comment by remisbaima** [comment]
which jsoup version did you use?

**Comment by ValiousSwank** [comment]
I tested it with 1.6.1 then upgrade it to the latest (1.8.1) and the result is the same

**Comment by remisbaima** [comment]
As a workaround you can use:
```java
import org.jsoup.parser.Parser;
...
Parser.unescapeEntities(Jsoup.parseBodyFragment(bodyHtml).toString(), true);
```

**Comment by jhy** [comment]
At the moment this is deliberate as the WHATWG HTML5 spec (at least when I
read and implemented it) had those tokens read as character data. But I'll
review.

**Comment by maxmika** [comment]
Any fixes there?
@ValiousSwank how did you solve your problem? I'm currently trying to save websites including iframes and came accross that bug

**Comment by ValiousSwank** [comment]
Hey,

If I remember well we didn't solve the issue. It wasn't that big issue to take care with. I think you can either remove the whole iframe (and everthing between them) or you change that to another html element.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by henrikrudstrom** [comment]
I have the same issue

**Comment by riimuru** [comment]
i have the same issue too
