### ISSUE TITLE
Maybe shouldn't support self-closing divs

### ISSUE THREAD

**Issue by hmkly** [jhy/jsoup#548]
Hi,

I'm not sure if this is intended behavior, but it seems like there's a parse error with markup that attempts to self-close a non-void element. 

For example parsing this as HTML5:
`<div id="a" /><div id="b"></div></div>`

Yields (with jsoup 1.8.1):
`<div id="a"></div><div id="b"><div></div></div>`

However, I think this should be returned instead (which is what browsers currently do):
`<div id="a"><div id="b"></div></div>`

I couldn't find this described in the spec, but since the self-closing slash is irrelevant in HTML5, it seems like completely ignoring /> is the way to go. Thoughts?

Cheers

**Comment by jhy** [comment]
What version are you using? I can't repro this issue in current versions. Here's a test: http://try.jsoup.org/~ZONF7j2hjcdOZ2jdsfcb-OBKiww

**Comment by hmkly** [comment]
Does that link work for you, I'm getting an "Action not found" message. Using Jsoup 1.8.1 with Clojure 1.6.0

**Comment by hmkly** [comment]
Ah, so sorry for the confusion, this should reproduce: 

```<div class=\"inner\" /><div><span></span></div></div>```

Yields:
```
<html>
    <head></head>
    <body>
        <div class="inner"></div>
        <div>
            <span></span>
        </div>
    </body>
</html>
```

But I believe it should be:
```
<html>
       <head></head>
       <body>
           <div class="inner">
               <div>
                   <span></span>
              </div>
          </div>
       </body>
</html>
```

 Using Jsoup 1.8.1 with Clojure 1.6.0, that link above doesn't seem to work, getting an "Action not found" message.

Cheers!

**Comment by jhy** [comment]
I don't know what's happening with that link. I can get it to fail if I use Firefox and follow the link from GitHub. If I paste it in vs follow, it works OK. Can't get it to fail in Chrome. Is Github doing a link referer track and changing the URL? Will need to dig in.

**Comment by hmkly** [comment]
Ah, got the link to work with Chrome (it was failing in Safari by clicking through from email or Github). 

Does this reproduce the error for you? http://try.jsoup.org/~VQe6XS198ONp6q-ALvEMyNJmgrU

**Comment by jhy** [comment]
OK, I see now with your example. I need to review, from memory it used to work that way but too many people complained it was ignoring the self-closing tag.

**Comment by hmkly** [comment]
I see, I suppose it's ambiguous either way. Not sure if there's room for a parser option to here, but hopefully there's a way to conform to the behavior of modern browsers on this.

**Comment by jhy** [comment]
@hmkly can you try that link again in Safari and let me know? I believe I've fixed it.

**Comment by hmkly** [comment]
@jhy Link is fixed in Safari!

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
