### ISSUE TITLE
url encoding is not done correctly, leading to infinite redirects

### ISSUE THREAD

**Issue by sumiranchugh** [jhy/jsoup#549]
looking at 1.8.1 httpconnection , encoding only replaces spaces . but for arabic characters , it doesnt encode them properly. only after encoding parameters in the redirect location header from response to ISO-8859-1 did it work fine.

there should be an option to specify charset by user and encoding based on that. utf-8 or iso

**Comment by jhy** [comment]
Do you have an example URL that I can test against?

**Comment by sumiranchugh** [comment]
go to https://ssl.souq.com/sa-en/2724288604627/s

you ll get a redirect response. The url in the locations header is the one m talking about
or the below 
java.io.IOException: Too many redirects occurred trying to load URL http://saudi.souq.com/sa-en/Ø¨ÙØ§Ù-Ø§ÙØ¯-Ø¯ÙÙØ±-Ø·ÙÙ-ÙÙÙØ§Øª-19-ÙØ·Ø¹Ø©-a7073-6607415/i/?ctype=dsrch

**Comment by jhy** [comment]
Thanks, this is fixed by 2cad0592106c30b04fe328b3989af619dcb6a49c
