### ISSUE TITLE
Disable output escaping

### ISSUE THREAD

**Issue by michael-simons** [jhy/jsoup#55]
Hi,
i'd like to see an EscapeMode.none that completely disables escaping of textnodes.

Thanks & kind regards,
Michael.

**Comment by Steff972** [comment]
This issue has received [5 upvotes](http://stackoverflow.com/a/35767541/363573) on Stackoverflow...

What does it miss to get handled?

**Comment by jhy** [comment]
Because what happens if there's an `<` in the textnode? Just broke your document. I will not implement this.
