### ISSUE TITLE
Add a selector to find data (script) elements by their content

### ISSUE THREAD

**Issue by Redeeman** [jhy/jsoup#553]
Hello.

It appears that these selectors simply does not work on a script block :)

I also tried the matches stuff, but same deal, however i did not test it nearly as much.

**Comment by Redeeman** [comment]
http://try.jsoup.org/~VMgmrCPJyU_RWZFTCgUAf_tE9b8

**Comment by jhy** [comment]
That's deliberate behavior, as script contents are data nodes, not text nodes. Those selectors only look for text nodes.

Most all of the time that's what people want. Maybe suggest a selector for data contains?

**Comment by Redeeman** [comment]
yeah that would be nice. these days almost every site has strange javascript stuff responsible for the most strange things, and sometimes you simply cant extract the data you need without getting dirty inside the script blocks. a selector like this would atleast allow me to get the block i know contains the keywords im interested in, so i dont have to loop over many handful of script blocks that does not contain the things.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
