### ISSUE TITLE
Cannot decode "deflate" stream in HttpConnection

### ISSUE THREAD

**Issue by XoriieInpottn** [jhy/jsoup#556]
Hi~ Some website uses deflate encoder in there response data (http://comment.bilibili.com/2454692.xml), but HttpConnection in Jsoup can only recognize "gzip". So add code bellow to HttpConnection.execute() can help to read "deflate" stream: 

if (res.hasHeaderWithValue(CONTENT_ENCODING, "deflate")) {
    bodyStream = new InflaterInputStream(dataStream, new Inflater(true));
}

I wish you could fix this, since it is convenient to get a webpage via Jsoup. HttpClient and Htmlunit are too big for me.

Thanks.

**Comment by jhy** [comment]
Thanks. Makes sense to add. I'm kind of surprised that the server is sending back deflated content when it wasn't asked to. I guess they expect everything to support it.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
