### ISSUE TITLE
[Feature] Pass custom certificate store for SSL/TLS

### ISSUE THREAD

**Issue by Nandaka** [jhy/jsoup#557]
In 1.8.2, jSoup allow to disable the SSL/TLS  validation, but is it possible to pass my own cert store to be used for the connection?

Ref: http://nelenkov.blogspot.ie/2011/12/using-custom-certificate-trust-store-on.html

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
