### ISSUE TITLE
changes made to isEqual on the Element now mess up the nextElementSibling / previousElementSibling / indexInList

### ISSUE THREAD

**Issue by andyphillips404** [jhy/jsoup#561]
The updates made between 1.8.1 and 1.8.2 in the isEqual of the Element now make the behavior of all functions utilizing the indexInList (which relies on the isEqual) to behave incorrectly.  The new isEqual only looks at the tag which then correctly gets the wrong element sometimes, in lists that  contain multiple items.

For example, multiple tr in tables, it can't find the current table index!   This shows up in the changes to the isEqual in 1.8.2.   I am more than happy to put a fix in, but i think we can either do two things:
1.  Change the isEqual back (but i'm not sure on the  motivation here why the change)
2.  Change the internal indexInList function in Element to not use isEqual but look for equal elemenet objects.

I am personally concerned that the change to isEqual is not robust enough check for isEqual as it appears to only check if that tag is equal....   But i also may not understand the full impact of the change and motivation

I'll put a pull request in, but was looking at feedback on which direction should be taken above!

**Comment by jhy** [comment]
The motivation of the isEquals change is to make elements and their child trees comparable. Their nodes and attributes should be part of the equality check.

Can you start with a test case that displays the problem? From your description, 2 sounds like the approach to go with.

**Comment by jhy** [comment]
You could think of the new behavior of equals to be like String.equals. I.e. check for same content with .equals. Check for identity with ==. Which is the bug, indexInList should be identity not contents.

**Comment by jhy** [comment]
Thanks for reporting and the detail, fixed now

**Comment by andyphillips404** [comment]
Great, thanks!
