### ISSUE TITLE
Cookie is not parsed by org.json.Cookie.toJSONObject()

### ISSUE THREAD

**Issue by shleym** [jhy/jsoup#566]
this is the code fragment: 

//// MY FRAGMENT START //////////////////////////////////////////////////////// 
//...
        List<String> cookies = headerList.get("Set-Cookie");
        Cookie cookie = null;
        for (int i = 0; i < cookies.size(); i++) {
            String cookieLine = cookies.get(i);
            JSONObject cookieJson = null;
            try {
                cookieJson = org.json.Cookie.toJSONObject(cookieLine);
            } catch (JSONException e) {
                continue;
            }
//...
//// MY FRAGMENT END //////////////////////////////////////////////////////// 

It let you parse only cookie, that does not have parameters without "=", unless the parameter name is "secure".:

//// JSOUP FRAGMENT START //////////////////////////////////////////////////////// 
//...
    public static JSONObject toJSONObject(String string) throws JSONException {

// ...
                if(!n.equals("secure")) {
                    throw x.syntaxError("Missing \'=\' in cookie parameter.");
                }

                v = Boolean.TRUE;

//// JSOUP FRAGMENT END //////////////////////////////////////////////////////// 

As the result, I am getting exception for this cookie, 
because first letter of "secure" starts with capital "S":
JSESSIONID=CB62477EC5DEEA1AA38FD9D638239EBD; Path=/atriumsso; Secure

I test it on www.cars.com. The site try to set 2 cookies. One of them generate exception, because it has parameter "HttpOnly":
Set-Cookie: JSESSIONID=mzhJVBpTBG0yLGn13vpfqTLXznW7GfBS3lnc1pvxspwK8ZT7WGbc!855764017; path=/cs; HttpOnly

//// RESPOND HEADER FROM cars.com starts ////////////////////////////////////////////////////
HTTP/1.1 200 OK
Date: Wed, 29 Apr 2015 18:57:55 GMT
Server: Oracle-Application-Server-12c
Cache-Control: no-store
Content-Length: 35298
Last-Modified: Wed, 29 Apr 2015 20:57:55 CEST
device_type: Desktop;Desktop
host_service: FutureTenseContentServer:11.1.1.8.0
X-Powered-By: Servlet/2.5 JSP/2.1
Set-Cookie: JSESSIONID=mzhJVBpTBG0yLGn13vpfqTLXznW7GfBS3lnc1pvxspwK8ZT7WGbc!855764017; path=/cs; HttpOnly
Keep-Alive: timeout=10, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Content-Language: en
Set-Cookie: rollout=2;expires=Mon, 27-Apr-2020 18:57:53 GMT;path=/;
//// RESPOND HEADER FROM cars.com ends ////////////////////////////////////////////////////

**Comment by shleym** [comment]
My personal suggestion: remove exception and put all those unknown parameters "=TRUE" to JSON object.

**Comment by jhy** [comment]
I think you filed this into the wrong project...
