### ISSUE TITLE
Doesn't support some self-closing tags, e.g. <device />, <source />

### ISSUE THREAD

**Issue by allen501pc** [jhy/jsoup#568]
Current used version: 1.8.1

Jsoup cannot export complete self-close tags after parsing self-closing tags.
For example, considering the following input HTML:

    <!DOCTYPE html>
    <html lang="en">
     <head> 
      <title>Bug Test for Jsoup</title> 
     </head> 
     <body> 
      <source src="test.mpeg4" />  
     </body>
    </html>
Then execute the following procedure codes:

	Document doc2 = Jsoup.parse(new File("test.html"), "UTF-8");
	System.out.println(doc2.toString());

It will output the following result.

    <!DOCTYPE html>
    <html lang="en">
     <head> 
      <title>Bug Test for Jsoup</title> 
     </head> 
     <body> 
      <source src="test.mpeg4">  
     </body>
    </html>

You can see the **< source>** tag cannot output as a self-close tag.
The reason is, that <source /> tag is a known tag in line **206** of **org.jsoup.parser.HtmlTreeBuilder**. After that, **<source />** will be first processed as **<source>** (i.e. open tag) then this element will be stored in HTML Tree Builder. However, while parsing **</ source>** tag, the tag will be ignored in **anyOtherEndTag** of **org.jsoup.parser.HtmlTreeBuilderState**.

I've posted the detail information for tracing this bug in my post.
[http://blog.allenworkspace.net/2015/05/known-bugs-while-processing-htmlxml.html](http://blog.allenworkspace.net/2015/05/known-bugs-while-processing-htmlxml.html)  

Notice that this bug was originally found in parsing XML. However, it also happened in parsing HTML.

**Comment by jhy** [comment]
Hi,

There is not really any such thing as self-closing tags in HTML. It was something that came out of the old XHTML mess. The syntax produced for this source tag is correct, and every browser will parse it correctly.

If the extra trailing space and slash is important to you, you can set the output mode to XML. See http://jsoup.org/apidocs/org/jsoup/nodes/Document.OutputSettings.html#syntax(org.jsoup.nodes.Document.OutputSettings.Syntax)

**Comment by allen501pc** [comment]
Thanks for your advice. I think I should use org.jsoup.nodes.Document.OutputSettings.prettyPrint(false) to print the output as input.
