### ISSUE TITLE
How to deal with parameters like SpringMVC requestBody have no key 

### ISSUE THREAD

**Issue by hyberbin** [jhy/jsoup#571]
How to deal with parameters like SpringMVC requestBody have no key .
I just want post String like :{"name":"hyberbin"} to the connection,it is a json data。
How  do I join your team?I have solved the problem, I want to submit code.

@RequestMapping(value = "/search", method = RequestMethod.POST)
    @ResponseBody
    protected Object search(@RequestBody StudentInfo studentInfo, HttpServletRequest request) {
}

**Comment by jhy** [comment]
Hi -- you can submit a pull request if you have an implementation. Please include tests in URLConnectTest, and docs. Thanks!

**Comment by jhy** [comment]
Although I think there's already a pull request out there to set the post body data directly, not through the KeyPairs.

**Comment by jhy** [comment]
Request body setting is supported now.
