### ISSUE TITLE
problems about single tag

### ISSUE THREAD

**Issue by huanggan429** [jhy/jsoup#572]
Dear jhy, I have a doubt about single tag issues:

for example, a html like this
<xmp>
 <html>
	<head></head>
	<body> 
	<ul>
      <li><a></a><i></i></li>
	  <p></p>
	</ul>
	</body> 
 </html>
</xmp>
I want to print all tag names:

public static void main(String[] args) throws Exception{
		File input=new File("C:/test.html");
		Document doc=Jsoup.parse(input,"gb2312");
		Elements eles=doc.getAllElements();
		for(Element ele:eles){
			System.out.println(ele.tagName()+"	"+ele.ownText());
		}
	}

the result will be: (and it is right)
#root
html
head
body
ul
li
a
i
p

but if I only delete <xmp></i></xmp> in the html page, i.e. <xmp><li><a></a><i></li></xmp>
 and the result will be 
#root
html
head
body
ul
li
a
i
i
p
i

why three " i " in the result..  

Thank you..

**Comment by jhy** [comment]
That's because in the HTML spec, the formatting tags are re-applied to following tags if they're not closed . They are auto-created on other character elements as if it was higher in the tree.
