### ISSUE TITLE
css escaped selector support

### ISSUE THREAD

**Issue by microhello** [jhy/jsoup#577]
Jsoup  don't support escaped selector ,such as: `#Meebo\:AdElement\.Root`  . This issue #30  is the one example too.  
Jquery support escaped selector currently , ref : https://api.jquery.com/category/selectors/  .

Can you add this feature?
Thanks very much.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)

**Comment by ninhthuanntnt** [comment]
Hi @jhy I've used select method and I still got that issue. 
Ex: css selector: html> h\\:m > a\\:b:nth-child... 
When I've used document.querySeletor function it worked ok. But Jsoup wasn't not
