### ISSUE TITLE
Jsoup cannot resolve relative urls starting with dot correctly

### ISSUE THREAD

**Issue by xpadro** [jhy/jsoup#585]
When a site specifies in its 'Location' header a redirection URL starting with ./url, Jsoup does not build a new URL correctly, leading to a 404 error.

- Method: org.jsoup.helper.HttpConnection.Response.execute(..)

- Versions: 1.7.2 and 1.8.2

**Comment by jhy** [comment]
Thanks for the report. Do you have a URL / test case? I can't repro. Test is in https://github.com/jhy/jsoup/commit/5be8b081ce931865d46b49ed44e19d3eafde748d

**Comment by xpadro** [comment]
Hi Jonathan,

I have modified the test with an example URL that makes the test fail.

Here's the pull request:
https://github.com/jhy/jsoup/pull/597
[GitHub](https://github.com/jhy/jsoup/pull/597)

Regards

**Comment by jhy** [comment]
Thanks. The issue wasn't the relative URL, it was that the absolute URL didn't have a path, just a host. I had to work around the way Java resolves those URLs.
