### ISSUE TITLE
Named character references with multiple codepoints are not supported

### ISSUE THREAD

**Issue by robinst** [jhy/jsoup#588]
In HTML 5, there are named character references that result in multiple (combining) characters, such as `&ngE;` - see [here](http://www.w3.org/TR/html5/syntax.html#named-character-references). Those seem to be handled incorrectly by jsoup.

Try this test case:

```java
String html = "<html><body><p>&ngE;</p></body></html>";
Document doc = Jsoup.parse(html);
Element p = doc.body().child(0);
assertEquals("≧̸", p.text());
```

**Comment by jhy** [comment]
These aren't defined in org/jsoup/nodes/entities-full.properties - need to regenerate that file with these updates. Also will need to restructure the dataset as it just expects to hold a single character

**Comment by jhy** [comment]
Thanks. Fixed with https://github.com/jhy/jsoup/commit/aa81e10c34f48a3c4ac7160aa90ee18af4f5c0c2
