### ISSUE TITLE
Problem parsing MS Word generated HTML with jsoup 1.8.2

### ISSUE THREAD

**Issue by klrohe** [jhy/jsoup#589]
Hi all,

I use a modification of the example program http://jsoup.org/cookbook/extracting-data/example-list-links.
I does not show the links in larger HTML files generated by MS Word 2010.
I'm using Java 8 (1.8.0_05), jsoup 1.8.2 on Windows 7 Ultimate.

I can provide the HTML file as a zip.

Kind regards

Klaus

**Comment by jhy** [comment]
Thanks, can you give an example of both ones that work and that don't?

**Comment by klrohe** [comment]
Hi Jonathan,

I have prepared a zip-file with word generated html and a separate zip-file with the Java-program.
How can I sent it to you?

Kind regards

Klaus

**Comment by jhy** [comment]
Can you email it to me? jonathan@hedley.net

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
