### ISSUE TITLE
Parse XML document incorrectly if tag name is chinese

### ISSUE THREAD

**Issue by rongjihuang** [jhy/jsoup#594]
If XML document with chinese tag name, jsoup 1.8.2 parse incorrectly.
---- code start
String xml = "&lt;root&gt;&lt;id&gt;1&lt;/id&gt;&lt;中文&gt;中国&lt;/中文&gt;&lt;/root&gt;";
Document doc = Jsoup.parse(xml, "", Parser.xmlParser());
System.out.println(doc);
---- code end
output is:
----
&lt;root&gt;
 &lt;id>
  1
 &lt;/id&gt;\&lt;中文\&gt;中国
 &lt;!--中文--&gt;
&lt;/root&gt;

**Comment by FunkyYang** [comment]
I have got this problem yet,so is there any way to slove the problem ?  I don't want to seek other technologies to slove this problem

**Comment by jhy** [comment]
Thanks, this was fixed in 1.9.1.
