### ISSUE TITLE
Duplicate body tags are placed when cleaning content

### ISSUE THREAD

**Issue by pmrreddy** [jhy/jsoup#595]
If I have `<html> <p> sample text <p> <html>`

When I use clean method and returning the content `clean.html()`; its placing duplicate body tags twice in the the output text like

```
<html><body><body><p> Sample text <p> </body></body></html>
```

Using 1.8.2.

**Comment by jhy** [comment]
Can you please add a full code sample / test so that I can repro?

**Comment by MichaelCkr** [comment]
Duplicate of #315
