### ISSUE TITLE
Element.select("tr > td:nth-child(3)") do not work OK when td node have same content

### ISSUE THREAD

**Issue by xdxl520** [jhy/jsoup#599]
Test html:

&lt;table&gt;
&lt;tr&gt;
 &lt;td&gt;A&lt;/td&gt;
 &lt;td&gt;B&lt;/td&gt;
 &lt;td&gt;B&lt;/td&gt;
 &lt;td&gt;C&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;
&lt;/body&gt;
&lt;/html&gt;

call select("tr > td:nth-child(2)") will return 2 element: 
 1. &lt;td&gt;B&lt;/td&gt;
 2. &lt;td&gt;B&lt;/td&gt;

call select("tr > td:nth-child(3)") will return 0 element: 

version of Jsoup is  v. 1.8.2

you can try it on http://try.jsoup.org/

java code in  Element.java  V1.8.2 use method : 
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;

        Element element = (Element) o;

        return tag.equals(element.tag);
    }

java code in  Element.java  V1.8.1 use method : 
    @Override
    public boolean equals(Object o) {
        return this == o;
    }

So, the method  indexInList return is not ok 

 private static <E extends Element> Integer indexInList(Element search, List<E> elements) {
        Validate.notNull(search);
        Validate.notNull(elements);

        for (int i = 0; i < elements.size(); i++) {
            E element = elements.get(i);
            if (element.equals(search))
                return i;
        }
        return null;
    }

**Comment by overthink** [comment]
This is probably related to https://github.com/jhy/jsoup/issues/554 (already fixed)

Try a build from HEAD or 1.8.3-SNAPSHOT release.  Worked for me.
