### ISSUE TITLE
Cleaner removes .php links

### ISSUE THREAD

**Issue by larghir** [jhy/jsoup#601]
I am initializing the cleaner with Whitelist.relaxed(), and some extra tags added. 
The document after cleaning has no href property for <a> elements where in the original document there's something like 
```
<a href="site/page2.php" title="page2">
```

After cleaning:
```
<a title="page2">
```
I think this is a bug, since the configuration (see Whitelist.relaxed()) should preserve href attributes.

**Comment by TSkrebe** [comment]
Look at Whitelist#preserveRelativeLinks
To maintain relative href after cleaning you have to set Document#setBaseUri to one of these protocols "ftp", "http", "https", "mailto"

**Comment by jhy** [comment]
As per @TSkrebe. Use the preserve relative links setting. Not related to PHP.
