### ISSUE TITLE
Missing some named entities

### ISSUE THREAD

**Issue by mfulgo** [jhy/jsoup#603]
Some named entities are missing from the [entities-full.properties](https://github.com/jhy/jsoup/blob/jsoup-1.8.2/src/main/java/org/jsoup/nodes/entities-full.properties), specifically, those that translate to more than a single character (within the Basic Multilingual Plane, not the supplementary planes as described in #602).

For example, `&nparsl;` should be decoded into `\u2AFD\u20E5`.  See the chart [here](http://www.w3.org/TR/2012/WD-html5-20121025/named-character-references.html#named-character-references) or its convenient [JSON file](http://www.w3.org/TR/2012/WD-html5-20121025/entities.json).

This could probably be fixed at the same time as fixing #602.

**Comment by jhy** [comment]
Thanks for pointing this out. Fixed with  https://github.com/jhy/jsoup/commit/aa81e10c34f48a3c4ac7160aa90ee18af4f5c0c2
