### ISSUE TITLE
Parsing issue with a <br> as a direct child of <ul> or <ol> tags

### ISSUE THREAD

**Issue by nicolasgavalda** [jhy/jsoup#604]
There seems to be a bug in the HTML parse engine: a \<br\> tag as a direct child of a \<ul\> or \<ol\> tag (outside a list item) is not placed outside the list in the resulting tree, as it's done with a \<table\> tag, for instance.

Example (reproduced using http://try.jsoup.org): parsing the following document
```xml
<html>
  <head></head>
  <body>
    <ul>
      <li>List item</li>
      <br/>
    </ul>
    <ol>
      <li>One</li>
      <br/>
    </ol>
    <table>
      <tr>
        <td>Single cell</td>
      </tr>
      <br/>
    </table>
  </body>
</html>
```
results in the following tree, which is not html-valid, as the br tags still are inside the ul and ol tags:
```html
<html>
 <head></head> 
 <body> 
  <ul> 
   <li>List item</li> 
   <br> 
  </ul> 
  <ol> 
   <li>One</li> 
   <br> 
  </ol> 
  <br>
  <table> 
   <tbody>
    <tr> 
     <td>Single cell</td> 
    </tr>  
   </tbody>
  </table>  
 </body>
</html>
```

**Comment by jhy** [comment]
This is the same as other browsers do it, and I can't see anything in the HTML5 spec that says they should be reparented. Do you have a pointer to one?
