### ISSUE TITLE
Invite you project to GitFund

### ISSUE THREAD

**Issue by wbb** [jhy/jsoup#605]
Hi.

I want invite you to GitFund.ORG. You can register you project on GitFund and all users can make donation for project developent and set up issue priorities.

http://www.gitfund.org

P.S: I am the project owner. GitFund was create for WysiBB, but now can be used for anyone.

**Comment by metaphorcode** [comment]
thanks.

**Comment by jhy** [comment]
I'm not sure why you filed an issue here to promote your project... no thanks.
