### ISSUE TITLE
attribute href is remove in some cases

### ISSUE THREAD

**Issue by helmbold** [jhy/jsoup#608]
I've created a `org.jsoup.safety.Cleaner with the following code:

	new Cleaner(
	    Whitelist.relaxed()
	        .addTags(
	          "meta", "title", "section", "nav", "article", "aside", "header", "footer", "main",
	          "address", "acronym", "caption", "details", "dfn", "figcaption", "mark", "wbr")
	  )

When I clean the [html page](https://drive.google.com/file/d/0ByI3TsZljwVeaXc0OUFuX3RtV2c/view?usp=sharing), some `<a href="...">` tags are returned withour `href="..."`.  For example the link `href="/newsticker/meldung/Autonome-Autos-Was-ist-eigentlich-ein-autonomes-Fahrzeug-2766598.html` is missing.

**Comment by jhy** [comment]
You should use the `preserveRelativeLinks` option of the whitelist.

**Comment by helmbold** [comment]
Thanks. However the behavior does not fully meet the principle of least astonishment.
