### ISSUE TITLE
Node#unwrap()

### ISSUE THREAD

**Issue by vnh19** [jhy/jsoup#610]
In this example I need to dispose of unnecessary spans around chunks of text which follow one another (with spaces between spans) .  Before unwrapping spans:
&lt;p&gt;__Start of string__ &lt;span class="a"&gt;__text_chunk_1__&lt;/span&gt; _space_ _space_ _space_ &lt;span class="b"&gt;__text_chunk_2__&lt;/span&gt; __text text.__&lt;/p&gt;

After unwrapping spans .a and .b: 

&lt;p&gt;__Start of string text_chunk_1text_chunk_2text text.__&lt;/p&gt;

The internal text chunks of spans now glued -- spaces around spans are disappeared.   
I tried to insert TextNode with space before and after spans and then unwrap spans. The result is the same.

**Comment by jhy** [comment]
I wasn't able to reproduce this. You can see the test case I added. If you can still repro in the current release, please add a full test case.
