### ISSUE TITLE
Elements.select() does not return all matching Element objects

### ISSUE THREAD

**Issue by saibotsivad** [jhy/jsoup#614]
During an upgrade from 1.7.1 to 1.8.3 we have come across an issue that could be a bug, but also could be a misunderstanding.

### Setup test

To setup the test, we start with a simple HTML example:

```html
<!DOCTYPE html>
<html>
    <body>
        <div>word</div>
        <div>word</div>
    </body>
</html>
````

And then create en Elements object like this:

```java
Document document = Jsoup.parse("<!DOCTYPE html>...etc...</html>");
Elements elements = document.select("div");
```

### Unexpected/Inconsistent behaviour

If a `.select()` is run on the `elements` object, it only finds a single instance. E.g. this passes in 1.8.3 but not in 1.7.1:

```java
int elementsFoundUsingSelect = elements.select(":contains(word)").size();
Assert.assertEquals("should find two but finds one", 1, elementsFoundUsingSelect);
```

On the other hand, if I loop over the `elements` object and run a select on each `Element`, I get the following:

```java
int elementsFoundUsingSelect = elements.select(":contains(word)").size();
int elementsFoundUsingLoop = 0;
for (Element element : elements) {
	if (element.select("table:contains(word)").size() > 0) {
		elementsFoundUsingLoop++;
	}
}
Assert.assertEquals("should find two", 2, elementsFoundUsingLoop);
```

### Expected behaviour

I would expect `elements.select(":contains(word)")` to return two elements, but in 1.8.3 it only returns one element.

### Other notes

It appears that when the selected HTML content is identical (e.g. the two `<div>` elements in the above example are identical) than running a `.select()` on the `Elements` object will only select the first object.

### What do I do?

Which behaviour is correct? Am I misunderstanding the documentation?

* Previously we were relying on the 1.7.1 behaviour to find all instances of an identical element, and then navigate from *each* of those using `Elements.select()`
* However in 1.8.3 you can find all instances of identical elements, but you can't navigate from them using `Elements.select()` as it will only `select()` within the first one.

**Comment by saibotsivad** [comment]
Here's [a gist](https://gist.github.com/saibotsivad/946916e2ce8bf30490ae) I made that might be easier to see.

**Comment by saibotsivad** [comment]
I've tracked this down to [a change](http://grepcode.com/file_/repo1.maven.org/maven2/org.jsoup/jsoup/1.8.2/org/jsoup/nodes/Element.java/?v=diff&id2=1.8.1#1185) introduced between 1.8.1 and 1.8.2 in the `Element.equals` method.

Previously the `equals` method was simply `this == that` but in the 1.8.2 update it changed to a more complex, but incomplete, comparison.

I'm attempting now to track down in the git logs what the reasoning was for the change.

**Comment by saibotsivad** [comment]
Now that I actually understand the issue, it looks like this is related to https://github.com/jhy/jsoup/issues/561 and https://github.com/jhy/jsoup/issues/554 which are related to the change introduced by @jhy in https://github.com/saibotsivad/jsoup/commit/8749726a79c22451b1f01b14fb2137f734e926b4

The specific issue that I've run into is due to Selector.select(String, Iterable<Element>)` using a `LinkedHashSet` which uses the `Element.equals` to determine if an element is identical to another element.

I am unsure of a good solution at this point.

**Comment by saibotsivad** [comment]
@andyphillips404 wrote on https://github.com/jhy/jsoup/issues/561

>  I am personally concerned that the change to isEqual is not robust enough check for isEqual as it appears to only check if that tag is equal

I would echo that concern as well. For example, we could add a check against the sibling index, e.g.

```java
if (this.siblingIndex != element.siblingIndex) return false;
```

But then that would only match the selected element's sibling index, so I could write another failing test:

```
<div><div class="test">word</div></div><div><div class="test">word</div></div>
```

I'm reluctant to say that we should revert `Element.equals` to be a simple `==` comparison, although I'm still unclear on the benefit. (Maybe a test case comparing the two would be helpful?)

Another possible option would be to compare the full CSS selector:

```
if (!this.cssSelector().equals(element.cssSelector())) return false;
```

**Comment by jhy** [comment]
The intent of the new .equals() behavior is so that users can test if the HTML of two elements is functionally equivalent.

That is probably putting it at odds with the selector behavior which is in this case trying to see if the two elements are the same actual element.

The fix then will be in the selector, not the .equals() check.

Thanks for the deep dive here.

**Comment by jhy** [comment]
I'm thinking of changing .equals and .hashcode back to their originals (object identity), and putting the current equals (content based) into a .compareTo. That will alleviate issues people are getting when using nodes as hashkeys.

**Comment by andyphillips404** [comment]
I think this is a great idea.   Thanks!
Andy P
