### ISSUE TITLE
[Feature] jsoup should render to Appendable instead of StringBuilder in outerHtml

### ISSUE THREAD

**Issue by thomasWeise** [jhy/jsoup#626]
I just started using `jsoup`, so maybe I am overlooking something. Anyway: `jsoup` is really great in parsing HTML, but as far as I can see, writing a parsed and modified `Document` seemingly requires to first transform the `Document` to a `String` and then to write this `String` to its destination.
# Proposal
I believe a simpler way would be to allow a `Document` to be write to an `java.lang.Appendable`. First of all, all `Node`s seemingly can already write themselves to a `StringBuilder` via their `outerHtml(StringBuilder)` method. Now `StringBuilder` implements `Appendable`. If you would make the `outerHtml(StringBuilder)` method public and put `Appendable` as parameter instead of `StringBuilder` (i.e., `outerHtml(Appendable)`), we could store the document to any `Appendable`. Other classes implementing `Appendable` are `java.io.Writer` and `java.nio.CharBuffer`. This would mean that, e.g., I could store a `Document` directly to a `Writer` (maybe wrapped around an `OutputStream` of an internet connection, say belonging to a `HttpServletResponse`...) without taking the detour of creating a `String` and then writing it.
# Advantages
This would

 1. reduce memory consumption,
 2. increase speed (as contents would immediately be written as soon as I start storing), and probably
 3. require relatively few changes in the code.

# Problems
As far as I can see, there are the following issues:

1. The `outerHtmlHead` method `Element` requires to know is `accum.length() > 0`. Such information is not available from an `Appendable`. Thus, the signature of this method would probably need to be changed: It would need to take a `boolean` indicating whether this is the first component in a document or not.
2. `outerHtml` is protected. Someone could have derived new sub-classes and overridden this method. If its signature is changed to use `Appendable` instead of `StringBuilder`, the code of that person won't compile anymore. Thus, this change (slightly) breaks compatibility.
3. `Appendable`'s methods throw `IOExceptions`. Several methods would now need to be changed to carry such an exception in their signature. This includes, e.g., `outerHtml`, `outerHtmlTail`, and `outerHtmlHead`, but also several utility methods.
4. In the existing code (`html()` et al.), `IOException`s would not matter, as `StringBuilder`s implementing `Appendable` do not throw such exceptions and we could simply catch and dismiss them (to make the compiler happy).
4. In a `NodeVisitor` used to serialize the elements of a node (via `Node`s `OuterHtmlVisitor`), the `IOException` issue would be slightly more complex, as we cannot know whether or not they are justified. Here, we could have a new private static final inner to channel the exception, we could do something like:
...
```java
    private static final class MyExceptionWrapper extends IllegalStateException {
      MyExceptionWrapper(final IOException ioe) {
        super(ioe);
      }
    }
```
...
```java
    private static class OuterHtmlVisitor implements NodeVisitor {
      private Appendable accum;
      private Document.OutputSettings out;

      OuterHtmlVisitor(Appendable accum, Document.OutputSettings out) {
        this.accum = accum;
        this.out = out;
      }

      public void head(Node node, int depth) {
        try{
          node.outerHtmlHead(accum, depth, out);
        }catch(IOException ioe) {
          throw new MyExceptionWrapper(ioe);
        }
      }

      public void tail(Node node, int depth) {
        if (!node.nodeName().equals("#text")) // saves a void hit.
        try{
          node.outerHtmlTail(accum, depth, out);
        }catch(IOException ioe) {
          throw new MyExceptionWrapper(ioe);
        }
      }
    }
```
...
```java
    protected void outerHtml(StringBuilder accum) throws IOException {
      try {
        new NodeTraversor(new OuterHtmlVisitor(accum, getOutputSettings())).traverse(this);
      } catch(MyExceptionWrapper mew) {
        throw ((IOException)(mew.getCause()));
      }
    }
```

All in all, with some (not-too-big) changes, storing of `Document`s (or any `Node`) could become more efficient.

**Comment by gouessej** [comment]
I like your suggestion, it would help to use jsoup with a JSP writer for example.

**Comment by thomasWeise** [comment]
Dear @gouessej .
That is exactly the use case I had in mind ^_^
I am 85% sure that I could even implement that. It would require to make some changes to core objects, though. If you are OK with me trying that, I could probably do it at some time next month,
On the other hand, I can also understand if you rather not want that someone touches the core objects and textual serialization routines. Just let me know.
Cheers,
  Thomas.

**Comment by jhy** [comment]
Thanks, implemented in 1.9.1

**Comment by gouessej** [comment]
@jhy Thank you :)

**Comment by thomasWeise** [comment]
@jhy Cool indeed. Many thanks ^_^
