### ISSUE TITLE
cannot set content type in the header

### ISSUE THREAD

**Issue by cklung** [jhy/jsoup#627]
Connection.Response res = Jsoup.connect(url) 
					.header("Content-Type", "application/json")
					.method(Connection.Method.POST)
					.execute();

the content type still is the default value (application/x-www-form-urlencoded).
![1](https://cloud.githubusercontent.com/assets/10297272/9903519/98d3e642-5ca9-11e5-9286-2d5f26531891.PNG)
![2](https://cloud.githubusercontent.com/assets/10297272/9903520/98d884a4-5ca9-11e5-85f9-7235990f99c3.PNG)

**Comment by gouessej** [comment]
Please rather call .ignoreContentType(false), an helpful exception might be thrown. This application type doesn't seem to be supported:
https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/HttpConnection.java#L546

**Comment by jhy** [comment]
This was implemented in 1.9.1 with [requestBody(String)](https://jsoup.org/apidocs/org/jsoup/Connection.Request.html#requestBody-java.lang.String-)
