### ISSUE TITLE
Timeout functionality not working as expected

### ISSUE THREAD

**Issue by KidCrippler** [jhy/jsoup#628]
I'm trying to download a page content using JSoup. If the whole operation (open connection + read) takes more than 8 seconds, I want to abort right away. I assumed that the purpose of the timeout(int millis) method does exactly that.

According to the javadoc of timeout(int millis):
Set the request timeouts (connect and read). If a timeout occurs, an IOException will be thrown. The default timeout is 3 seconds (3000 millis). A timeout of zero is treated as an infinite timeout.

I wrote a simple code that simulates that operation:

    final int TIME_OUT = 8000;
    final String USER_AGENT_STRING = "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)";
    final String url = "http://reguler-pmb-tanggamus.va.web.id/";

    long time = System.currentTimeMillis();
    try {
        Document doc = Jsoup.connect(url).userAgent(USER_AGENT_STRING).timeout(TIME_OUT).get();
        System.out.println("Done crawling " + url + ", took " + (System.currentTimeMillis() - time) + " millis");
        System.out.println("Content: " + doc);
    } catch (Exception e) {
        System.out.println("Failed after " + (System.currentTimeMillis() - time) + " millis");
        e.printStackTrace();
    }
I tried to run this small script on a few "problematic" websites in a single threaded environment. I assumed that whether it succeeded or an exception was caught, the operation time should never exceed 8 seconds (8000 millis). Unfortunately, this is not the case as sometimes it succeeds (no exception) after more than a minute, and sometimes (very rarely though) fail (SocketTimeoutException) after more than a minute.

I'm using version 1.8.3 of JSoup and have additionally posted a question regarding this issue in stackoverflow:
http://stackoverflow.com/questions/32678890/jsoup-timeout-not-working-as-expected

Thanks

**Comment by jhy** [comment]
It sets the connect and the read timeouts. Read timeout means the time between reads. If you have a server dribbling content out over a long time, but each read is < 8 seconds, it won't timeout. 

It might be nice to implement a max timer but that's not straightforward (needs a monitoring thread and a practical way to shutdown a connection), and that's not something many others have asked for.

**Comment by maxid** [comment]
/**
     * Set the maximum bytes to read from the (uncompressed) connection into the body, before the connection is closed,
     * and the input truncated. The default maximum is 1MB. A max size of zero is treated as an infinite amount (bounded
     * only by your patience and the memory available on your machine).
     * @param bytes number of bytes to read from the input before truncating
     * @return this Connection, for chaining
     */
    Connection maxBodySize(int bytes);

Jsoup default recv maximum is 1MB

set "Jsoup.connect(url).maxBodySize(0);" maybe fixed it!
