### ISSUE TITLE
Cannot import manually or via Gradle in Android Studio 

### ISSUE THREAD

**Issue by r0boto** [jhy/jsoup#630]
Hello, 

I tried to to add library v 1.8.3 using:

```
    compile 'org.jsoup:jsoup:1.8.3'

```

Or manually (jar copied into libs folder and added into dependencies)

But i got always following exception during the build process.

```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

```

Android Studio v 1.3.2

Android compile settings

```

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"
```

Many thanks for any advice.

**Comment by jhy** [comment]
Possibly a previous Gradle issue, or local environment issue. Doesn't repro.
