### ISSUE TITLE
JSoup encodes code fragments

### ISSUE THREAD

**Issue by markbernard** [jhy/jsoup#631]
There is no way to turn off EscapeMode when getting HTML out of JSoup. JSoup automatically interprets ASP or JSP code fragments as bad HTML and encodes them. This disables the code so the application wont run. Could there be an exception added to ignore all code fragments for HTML encoding?

eg This ASP <%Response.Write("This is a test") %>
will be changed to &amp;lt;%Response.Write(&amp;quote;This is a test&amp;quote;)%&amp;gt;

**Comment by markbernard** [comment]
Any chance this can be done? I would just like to know either way. Thanks.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
