### ISSUE TITLE
overlapping lines in Java doc

### ISSUE THREAD

**Issue by helmbold** [jhy/jsoup#633]
Lines in the Java api doc are overlapping in some cases. Tested with Firefox 41. I suggest to keep it simple and just use the default style.

![jsoup](https://cloud.githubusercontent.com/assets/5079980/10243453/140f6d3a-68f9-11e5-886f-dee5ffc65778.png)

**Comment by petehouston** [comment]
You can generate the API doc locally, https://github.com/petehouston/jsoup

If you don't want to, check this, https://github.com/petehouston/jsoup-apidocs

**Comment by jhy** [comment]
I fixed this by updating the CSS
