### ISSUE TITLE
enhancements - add annotations & use exceptions 

### ISSUE THREAD

**Issue by c3ph3us** [jhy/jsoup#636]
consider to change code like this:
(throw an exception  to avoid checks for null & use annotations) 

    /**
    *  ...
    * @throws  NoSuchElementException - when element not found 
    */
    @NonNull
    public Element getElementById(@NonNull String id) throws NoSuchElementException {
    /** we  safe remove this - less operations & speed up */        Validate.notEmpty(id);    
        
            Elements elements = Collector.collect(new Evaluator.Id(id), this);
            if (elements.size() > 0)
                return elements.get(0);
            else
               throw new NoSuchElementException("Element for id: " + id + " not found! ");
       }

**Comment by gouessej** [comment]
Some people here want to keep the compatibility with Java 1.5 and the NonNull annotation has been introduced in Java 1.8 as far as I know :s

**Comment by c3ph3us** [comment]
Java 5 is clearly gone for good and shows no signs of returning from the dead.

https://plumbr.eu/blog/java/java-version-statistics-2015-edition

it's time to move forward !!!
but if u insist u still can use exceptions :) 
i m dealing with jsoup often  and constantly i need check for null before every select :D instead  wrap in try block its exhausting :D

**Comment by c3ph3us** [comment]
simply leave 1.3 & create 2.0

**Comment by jhy** [comment]
Android is mostly 1.5.
