### ISSUE TITLE
Element constructor creates broken elements

### ISSUE THREAD

**Issue by helmbold** [jhy/jsoup#637]
The following demo program (in Scala, but that is not important) shows that valid html input creates completely broken html output:

    import org.jsoup.nodes.Element
    import org.jsoup.parser.Tag
    
    object Main extends App {
      val tag = Tag.valueOf("<div>text</div>")
      val element = new Element(tag, "http://example.com")
      println("tag: " + tag)
      println("element: " + element)
    }

Output:

    tag: <div>text</div>
    element: <<div>text</div>></<div>text</div>>

`Tag#valueOf`seems to work properly, but the constructor of `Elements` creates garbage (and garbage collection doesn't help here ;-) ).

**Comment by haggisandchips** [comment]
Is this not a case of garbage in / garbage out ?

The Tag#valueOf method is not designed to receive html it is designed to
receive a tag name - ie "div" or "p" or "myCustomTag".

Arguably the valueOf method lacks validation but other than that your code
snippet has done what I would expect.

**Comment by helmbold** [comment]
I've just learned that I can only provide a tag name in the `valueOf`method. Maybe this method could check this to avoid that others make the same stupid error.
