### ISSUE TITLE
Malforming URL after Redirect (HTTP 301)

### ISSUE THREAD

**Issue by GarciaPL** [jhy/jsoup#639]
At this moment I am trying to write some application on Android platform and for me it was obvious to use Jsoup (1.8.3) for retrieving some content from web. Today I was faced with problem that I have an URL which has a space in it for instance : http://server.com/country=United Kingdom. As far I saw the library correctly replace space with %20 (http://server.com/country=United%20Kingdom). The issue occurs when server after hitting this address sent back **HTTP code 301** (Moved Permanently) and then Jsoup creates new response based on previous connection. The issue is around **setupFromConnection** method when headers fields are retrieved from connection (**conn.getHeaderFields()**) and then from nowhere I see that in **Header** under key **'Location'** there is the same address like this one : **http://server.com/country=United%25%20Kingdom**. The % sign is replaced with %25. Could you put eye on this issue ?

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
