### ISSUE TITLE
[bug] Jsoup fails parsing HTML with large base64 code

### ISSUE THREAD

**Issue by Bouki** [jhy/jsoup#640]
Hello

I just discovered that Jsoup cannot parse html with large base64 img, it stops at the first img

I know large base64 images are not a good practice, but I have to parse a page containing them

you can try with this HTML code : http://fiddle.jshell.net/3txzdyL0/show/

**Comment by jhy** [comment]
What did you set the request max body size to? http://jsoup.org/apidocs/org/jsoup/Connection.html#maxBodySize-int-
