### ISSUE TITLE
connection using proxy

### ISSUE THREAD

**Issue by mjamareh** [jhy/jsoup#641]
As I know there is no way to use proxy with jsoup.
it would be very good if jsoup support connection with https and http proxy
thanks in advance,

**Comment by islanderman** [comment]
Why does ``jsoup`` need to support Proxy?  I thought it should be done in the network level.

http://stackoverflow.com/questions/7482748/how-to-add-proxy-support-to-jsoup-html-parser

**Comment by jhy** [comment]
Implemented.

**Comment by mjamareh** [comment]
thank you @jhy

**Comment by JohnSmith9527** [comment]
@jhy 

thank you for adding proxy to Jsoup. This is very useful.

Would you please further add proxy authentication to it?

(1) authenticate proxy with username,password

(2)support both http/https proxy and socks proxy.

thanks.

**Comment by xuguobiao** [comment]
how can i set proxy when using shadowsocks?
