### ISSUE TITLE
Compilation problem using gradle

### ISSUE THREAD

**Issue by saikirandusari** [jhy/jsoup#642]
Hi there

Am running into the below when I compile my code with gradle. Am using java 1.7 version. Can you please help me on this ?

 error: package com.sun.xml.internal.ws.developer does not exist

C:\.........\FXUpload.java:76: error: cannot find symbol
                WSBindingProvider bindingProvider = (WSBindingProvider) fxRatesService;
                                                     ^
  symbol:   class WSBindingProvider
  location: class FXUpload
3 errors
 FAILED
:buildFxRateUpload FAILED

**Comment by petehouston** [comment]
@saikirandusari based on your output, it is not jsoup-related issue, check your project again. 

Also, more reference for your issue,

http://stackoverflow.com/questions/13068146/how-to-overcome-package-com-sun-xml-internal-xxx-does-not-exist-when-compiling
