### ISSUE TITLE
No Following of Relative Links...

### ISSUE THREAD

**Issue by mediadr** [jhy/jsoup#643]
Not sure if I am missing something, but my code seems to no follow relative links, which is not how you would want it to function in the real world.

doc = jSoup.clean(arguments.html, "http://www.mydomain.com", WhiteList.basic().preserveRelativeLinks(true));

And when I do this...

doc = jSoup.clean(arguments.html, "http://www.mydomain.com", WhiteList.relaxed().preserveRelativeLinks(true));

it drops the no follow functionality altogether.

What I'm trying to achieve is to clean the HTML and no-follow absolute links only. One better would be to leave relative & baseURLs in a whitelist without no follows. How can I achieve this in JSoup?

The no follow functionality seems to be all or nothing.

**Comment by jhy** [comment]
With #2245, rel=nofollow is only added to external links. Not relative links, or absolute links to the same site as the base URI.

rel=nofollow is a default enforced attribute in `basic`, not in `relaxed`, but you can add it to `relaxed` if desired. The behavior will be the same.
