### ISSUE TITLE
Missing table header elements.

### ISSUE THREAD

**Issue by israelconesa** [jhy/jsoup#645]
Hi,

Firstly, thanks for the great parser!. Using Jsoup 1.8.3.

I was working with a table from a Football Fantasy website. I seem to be able to grab the table without issues, however when parsing table headers, I'm missing a couple. 
My code:

```
String html = "http://www.fantasyleague.com/Classic/Stats/playerlist.aspx?dpt=0";
             Document doc = Jsoup.connect(html).get();
             Elements tableElements = doc.select("#playerlist > table");
             Elements tableHeaderEles = tableElements.select("thead > tr > th");
             System.out.println(tableHeaderEles.toString());
```

The screenshot below depicts the difference between the header nodes straight from the site (right) and the ones from the console output on Eclipse (left). The missing nodes are empty but so it's the first one and it is displayed anyway. Ideally, I'd like to get hold of all the nodes, even if they're empty, for formatting purposes. 

![image](https://cloud.githubusercontent.com/assets/12008390/10694524/8cad2144-7996-11e5-9004-f0369a35b348.png)

Thanks,

Israel.

**Comment by jhy** [comment]
Sorry I can't repro. You can see on this example they are parsed - https://try.jsoup.org/~auwOf7EF8fmPA6rsy3Zw0Qm38z4

**Comment by israelconesa** [comment]
E

**Comment by israelconesa** [comment]
Indeed, just got back to it and I couldn't reproduce it. THANKS.

**Comment by jhy** [comment]
Cool, thanks for confirming.
