### ISSUE TITLE
StringIndexOutOfBoundsException on following redirect link

### ISSUE THREAD

**Issue by sajad22** [jhy/jsoup#647]
maybe url size is 5!

Exception in thread "Thread-186" java.lang.StringIndexOutOfBoundsException: String index out of range: 6
     [java]     at java.lang.String.charAt(String.java:658)
     [java]     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:527)
     [java]     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
     [java]     at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
     [java]     at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)

add location.length()>=5 in HttpConnection line 527 to fix it

**Comment by petehouston** [comment]
@sajad22  what is the url on redirect **Location** header?

**Comment by sajad22** [comment]
I don't know what the redirected url, but when I run jsoup to connect "photoshopid.com" instead of error like "no route to host exception" I got StringOutOfBoundException
