### ISSUE TITLE
Cannot use single quotes in selectors

### ISSUE THREAD

**Issue by ipolevoy** [jhy/jsoup#650]
First, cool project!

Found a small issue: this HMTL:

```html
<body>
<p>This is <a data-file='123'>jsoup</a>.</p>
</body>
```

works with this selector: 

```
a[data-file="123"]
```

As you can see, the HTML has single quotes for `data-file` attribute, but the selector must use double quotes, and not working with single quotes: 

```
a[data-file='123']
```

This means that the selector inside Java code must use escaped double quotes: 

```java
Document doc = Jsoup.parse(responseContent());
Elements main = doc.select("a[data-file=\"123\"]");
```

This makes code look a bit dirtier than it should. Are there plans to support single quotes? 

By the way, I intend to use this in tests with http://javalite.io/testing, which looks like a perfect match.

**Comment by derfloscher** [comment]
+1 thank you for the pull request

**Comment by jhy** [comment]
My inclination would just be to use `a[data-file=123]`. The HTML using single- or double-quotes has nothing to do with it; in the DOM there's an attribute with key = `data-file` and value = `123`.

**Comment by ipolevoy** [comment]
:+1:

**Comment by ipolevoy** [comment]
If someone is interested, this is how JSoup is used in JavaLite: http://javalite.io/testing#testing-html-content
