### ISSUE TITLE
xmlParsing for svg files attributes

### ISSUE THREAD

**Issue by girque** [jhy/jsoup#651]
When parsing an svg file (using xmlParser) and rewriting the content in another one, the "viewBox" attribute is transformed to "viewbox".
I think it shouldn't do that as it's modifying the attribute.
SVG parsers are often case sensitive and won't recognize the viewBox attribute nor its value afterwards, that's somehow embarassing to deal with it.

**Comment by jhy** [comment]
A work around for this would be to use ParseSettings and preserve case. That's not specific to SVG so not optimal.

**Comment by jhy** [comment]
Actually, on second read, this is fixed by ParseSettings defaulting to preserving case in XML parser.
