### ISSUE TITLE
Custom SSL connection?

### ISSUE THREAD

**Issue by cooperkong** [jhy/jsoup#654]
Hi 

Thanks for the awesome library, just wondering if it is possible to create API for tweaking HTTPUrlConnection for self signed certificate.
Currently it failed to read any ssl sites when sitting behind proxy.

Cheers,

**Comment by E-lai** [comment]
I have added a proxy support to Jsoup 1.8.4. 
It can refer to https://github.com/E-lai/jsoup-proxy

**Comment by cooperkong** [comment]
Thanks, I will have a look at it !

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
