### ISSUE TITLE
Please create PROGRESS method

### ISSUE THREAD

**Issue by crysan** [jhy/jsoup#656]
Hi,

Can you implement a method of progress?
It is necessary to indicate the progress of the html page downloaded.

Thanks

**Comment by Stephan972** [comment]
Can you please detail what you expect?

**Comment by crysan** [comment]
Example:

Document doc = Jsoup.connect("http://example.com")
  .userAgent("Mozilla")
  .timeout(3000)
  .onProgress (long totalBytes, long downlaodedBytes, int progress){
      tada();
  }
  .post();

**Comment by Stephan972** [comment]
What the `int progress` parameter is supposed to contain?


The code in the example is invalid Java code. Can you adress this?


What happen if the total size is unknown?






On Tue, Aug 23, 2016 at 6:47 AM +0200, "Sani" <notifications@github.com> wrote:





Example:

Document doc = Jsoup.connect("http://example.com")
  .userAgent("Mozilla")
  .timeout(3000)
  .onProgress (long totalBytes, long downlaodedBytes, int progress){
      tada();
  }
  .post();

**Comment by crysan** [comment]
int progress = 0(%) - 100(%) downloaded

The code in the example is invalid Java code. Can you adress this?
I know.  Just gave the example of the approximate realization to obtain information about how to download the object.

What happen if the total size is unknown?
At the beginning of the boot progress = 0. At the end of progress = 100. The intermediate result is unknown.

**Comment by Stephan972** [comment]
Please clarify the code with a valid Java example.


In the case of an unknown total size, what value progress should contain?






On Tue, Aug 23, 2016 at 7:26 AM +0200, "Sani" <notifications@github.com> wrote:





int progress = 0(%) - 100(%) downloaded

The code in the example is invalid Java code. Can you adress this?
I know.  Just gave the example of the approximate realization to obtain information about how to download the object.

What happen if the total size is unknown?
At the beginning of the boot progress = 0. At the end of progress = 100. The intermediate result is unknown.

**Comment by jhy** [comment]
Yes I know what you mean, like in the Android Progress methods. Good idea,
thanks!

**Comment by burtonator** [comment]
It I think this could be implemented by just returning the position of the byte stream every time an element is hit

**Comment by jhy** [comment]
OK it took me a little while to get to this. But still, less then a decade!

Coming with #2164.

The signature looks like:


```java
@FunctionalInterface
public interface Progress<ProgressContext> {
    /**
     Called to report progress. Note that this will be executed by the same thread that is doing the work, so either
     don't take to long, or hand it off to another thread.
     @param processed the number of bytes processed so far.
     @param total the total number of expected bytes, or -1 if unknown.
     @param percent the percentage of completion, 0.0..100.0. If the expected total is unknown, % will remain at zero
     until complete.
     @param context the object that progress was made on.
     */
    void onProgress(int processed, int total, float percent, ProgressContext context);
}

```

So that we can pass a Response in for the context, so you can get the URL, headers etc. And we can also add other progress events, like during parsing, uploads, etc.

**Comment by crysan** [comment]
Thank you!
I am very surprised that you have not forgotten about my request, because you have already forgotten about it.
Yes, this question is also relevant to me.
Thank you for your hard work!
