### ISSUE TITLE
Explicit HTML code is parsed by JSoup incorrectly

### ISSUE THREAD

**Issue by AlexeyCe** [jhy/jsoup#663]
Hello!

I'm using JSoup for parsing HTML. It generally works OK, but in some explicit example it changes element sequence in HTML after parsing. Here is the simple code:

String str1 = originalHtmlFragment;
Document doc = Jsoup.parseBodyFragment(str1);
String str2 = doc.html();
Here are the values of str1 and str2.

str1:

        <table>
            <tbody>
                <tr>
                    <th>
                        <p> </p>
                        <p>10</p>
                    </th>
                </tr>
                <tr>
                    <td colspan="1">
                        <p>
                            <ac:macro ac:name="my-macro">
                                <ac:parameter ac:name="outer-values">Page content</ac:parameter>
                                <ac:parameter ac:name="atlassian-macro-output-type">INLINE</ac:parameter>
                                <ac:rich-text-body>
                                    <p>a1</p>
                                </ac:rich-text-body>
                            </ac:macro>
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>

str2:
...

        <table>
            <tbody>
                <tr>
                    <th>
                        <p>&nbsp;</p>
                        <p>10</p>
                    </th>
                </tr>
                <tr>
                    <td colspan="1">
                        <p>
                            <ac:macro ac:name="my-macro">
                                <ac:parameter ac:name="outer-values">Page content</ac:parameter>
                                <ac:parameter ac:name="atlassian-macro-output-type">INLINE</ac:parameter>
                                <ac:rich-text-body></ac:rich-text-body>
                            </ac:macro>
                        </p>
                        <p>a1</p>
                        <p>
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>

...
Note that a1 is outside ac:macro tag in the second code example. How can I work around that in JSoup? Thanks!

**Comment by alkiskal** [comment]
The ac tags are not valid html tags, so Jsoup is attempting to normalize it. Try using 
Document doc = Jsoup.parse(html, "", Parser.xmlParser());

**Comment by jhy** [comment]
A `p` tag can't contain a `p` tag in HTML.
