### ISSUE TITLE
getElementsByTagNameNS(), getLocalName() and getNamespaceURI() methods return NULL

### ISSUE THREAD

**Issue by ekasumov** [jhy/jsoup#671]
When using the experimental W3CDom.fromJsoup() method to convert a Jsoup Document to a DOM Document, the following methods incorrectly return NULL:
getElementsByTagNameNS()
getLocalName()
getNamespaceURI()

the file in question in a XHTML file on disk
Code:
```java
org.jsoup.nodes.Document jsoupDoc = Jsoup.parse(myFile, "UTF-8");
org.jsoup.helper.W3CDom jDom = new org.jsoup.helper.W3CDom();
Document doc = jDom.fromJsoup(jsoupDoc);
```
the XHTML document:
```html
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" lang="en">
	<head>
		<title>Cover</title>
		<style type="text/css">
			img{
				max-width:100%;
			}
		</style>
	</head>
	<body>
		<figure id="cover-image">
			<img src="covers/9781449328030_lrg.jpg" alt="First Edition" />
		</figure>
	</body>
</html>
```

**Comment by ekasumov** [comment]
committed a fix to a fork, pull request created.  Problem caused by namespace not being included when W3C document and its elements is being created.

**Comment by jhy** [comment]
PR is #677

**Comment by jhy** [comment]
Thanks, merged, with additional support for multiple namespaces and prefixes.
