### ISSUE TITLE
input charset

### ISSUE THREAD

**Issue by orbisvicis** [jhy/jsoup#674]
My application needs to know the html's input charset as detected by jsoup - including if no input charset was specified. If no input charset was specified, jsoup defaults to UTF-8, so the charset() methods can't tell me if the charset wasn't specified or specified as UTF-8.

I'm willing to supply a patch, but please respond by today as I don't have much time.

I suggest adding a private boolean member to OutputSettings() with an accessor method that specifies the if the charset was specified (BOM, meta tag, or by user) or assumed (as UTF-8), then modifying `parseByteData` as necessary. Perhaps named `charset_from_input`. Since the field would have to be updated along with the charset, perhaps it would make more sense to create an `InputSettings` class with the methods `String charset()` and `Charset charset()`.

**Comment by jhy** [comment]
Seems a pretty niche requirement. Probably not going to implement unless there's more demand for it. Thanks for the suggestion and apologies for the late reply.
