### ISSUE TITLE
Maven/ivy version scan fails due to 404

### ISSUE THREAD

**Issue by jcracknell** [jhy/jsoup#675]
Ongoing for a week or so now. The directory listing for `org.jsoup` is returning a 404, preventing Maven/Ivy version scans:
http://repo1.maven.org/maven2/org/jsoup/

The JAR itself is accessible:
http://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar

So this smacks of some kind of bizarre directory permissions issue.

**Comment by jcracknell** [comment]
The problems seems to have been pushed down a level now:
http://repo1.maven.org/maven2/org/jsoup/jsoup/

**Comment by jhy** [comment]
Fixed by https://issues.sonatype.org/browse/MVNCENTRAL-1039
