### ISSUE TITLE
JSoup is not providing the correct Document.

### ISSUE THREAD

**Issue by MLBown** [jhy/jsoup#679]
I'm trying to connect to an imgur URL e.g. "http://imgur.com/gallery/qzc07Mv". I access the page with:

Document doc = Jsoup.connect("http://imgur.com/gallery/qzc07Mv").timeout(0).get();

This works most of the time, however sometimes it trips up and gives me this as the doc: 

`<html>
 <head></head>
 <body>
  1
 </body>
</html>`

I don't understand why this is being returned instead of the actual page.
If I loop the request, it eventually gives me the correct one, so I'm not sure if it's imgur or jsoup.

 Is this a bug?

**Comment by gnash48** [comment]
I am unsure if it's a bug, but, if a workaround does not appear soon, you can connect to the URL using an HttpURLConnection, store the page in a String, and pass that String to the parse() method in the Jsoup class. The parse() also returns a Document object as does the connect() method that you were trying to use.

**Comment by jhy** [comment]
I haven't been able to repro. It works reliably for me. My guess is that imgur was timing out and returning "1" as plain text, which when transformed into HTML gave you that result. If you can find a way to repro, can you capture the network traffic (say using Charles) and provide that? Or let me know how to repro.
