### ISSUE TITLE
Issues with Elements.indexOf() due to Element.equals() implementation

### ISSUE THREAD

**Issue by ks280first** [jhy/jsoup#681]
I am having an issue with the way the equals() method is implemented for Element.  This has been referenced before in issue #405, but I wanted to give a concrete example of how it can go wrong. Here is the implementation:
```java
@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;

        Element element = (Element) o;

        return tag.equals(element.tag);
    } 
```

Notice at the end, if all else fails it just equates them if the tags are the same at **`return tag.equals(element.tag);`**.  I understand that the intention was to implement it similar to java.lang.String so that `<p/>` always equals `<p/>`.  I'm sure there is a reason that it exists this way, but it has repercussions.  Consider the following example:

```html
<div>
    <span>Something here</span>
    <br>
    <span>Something else</span>
    <br>
    <span>Something very different</span>
    <br>
</div>
```
The `Element.equals()` method will return true for any of the empty `<br>` elements which leads to problems like the following.

```java
Element e;  /*Assuming e represents the above HTML*/
Elements breaks = e.select("br");
for(Element br : breaks)
{
    /* The first two will always be the same because "<br>".equals("<br>") == true */
    System.out.println(
              "  index: " + breaks.indexOf(br)
             +"  childIndex: " + e.children().indexOf(br)
             +"  siblingIndex: " + br.siblingIndex()
	);
}
```
Will produce:
> 
   index: 0   childIndex: 1   siblingIndex: 1
   index: 0   childIndex: 1   siblingIndex: 3
   index: 0   childIndex: 1   siblingIndex: 5

One way to get around this is to set a unique id attribute on them so that they are never the same.

**Comment by jhy** [comment]
Fixed in 1.9.1 by going back to using identity equals. Thanks for the depth of your report, helpful.
