### ISSUE TITLE
[Question] Are those attributes safe ?

### ISSUE THREAD

**Issue by Activee** [jhy/jsoup#682]
I've added some attributes to the basic whitelist. Some of them are custom tags that when displayed their attributes is used in javascript. I asked a bit around but didn't manage to have an accurate answer on the subject. Mostly it was "probably safe". So I'm trying my luck here.
My worry is mainly those custom tags which, I reiterate, when displayed, their attribute is used in javascript.

```
		whiteList.addTags("h1","h2","h3","h4","h5","h6","h7","p");
		whiteList.addTags("div","thead");
		
		
		whiteList.addAttributes("a", "href");
		whiteList.addAttributes("p", "class");
		whiteList.addAttributes("img", "class", "src");
		whiteList.addAttributes("span", "class");
		whiteList.addAttributes("code", "class");
		whiteList.addAttributes("table", "class");
		whiteList.addAttributes("th", "class");
		whiteList.addAttributes("tr", "class");
		whiteList.addAttributes("td", "class");
		whiteList.addAttributes("chart", "type", "title", "measured");
		whiteList.addAttributes("chartcolumn", "title", "value");
```

**Comment by jhy** [comment]
I think you'll be safe enough. A browser isn't going to execute any javascript that's been hidden in those unknown tag's attributes, which is what the main protection of the cleaner does. Careful what you do in your own JS though and that you're not eval()ing or anything. Validate.
