### ISSUE TITLE
JavaScript dynamically load the content

### ISSUE THREAD

**Issue by BubikolRamios** [jhy/jsoup#683]
> The goal of jsoup is that is will sensibly parse any real-world HTML page into effectively the same parse tree that a modern browser would.

does not read entire contence, but according to upper statement it should.
first post -- see problematic link
last post -- see the problem:

see here
[http://stackoverflow.com/questions/35600919/jsoup-followredirectstrue-does-not-work](url)

**Comment by jhy** [comment]
Javascript is not supported. Jsoup parses HTML.
