### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by poornima-apakau** [jhy/jsoup#686]
I see the following string appended when I parse :
 {"error":{"code":8,"message":"Unable to process"}}

I fetch the response from the http://erosnow.com/
I convert the response to a string(Charset ISO-8889-1) and pass it to Jsoup using 
Document doc = Jsoup.parse(htmlResponse);

I see that doc.html() contains the error string posted above and leaves out a few script tags at the bottom of the page.

Can you please update me ?

**Comment by poornima-apakau** [comment]
Connect to the url works but not parse.. I have tried different charsets.

**Comment by jhy** [comment]
I had no problems parsing it. Here's an example using Try Jsoup:

http://try.jsoup.org/~ldAtvu7_ro39ueN95BOHKIROH4c

Source code to repro? What useragent are you setting?
