### ISSUE TITLE
hashCode assumes immutable data, breaks hash tables when modified

### ISSUE THREAD

**Issue by kno10** [jhy/jsoup#688]
The hashCode implementation of jsoup fails the following unit test:
```
    Element root = new Element(Tag.valueOf("root"), "");

    HashSet<Element> set = new HashSet<>();
    // Add root node:
    set.add(root);

    root.appendChild(new Element(Tag.valueOf("a"), ""));
    assertTrue(set.contains(root));
```

Having a content-dependant `hashCode` for *mutable* objects is flawed.

Either the API needs to be designed immutable, or the hashCode/equals must only check for identity.

Apart from that, these functions are also rather expensive. They can be made available under a different name, and of course a `compareTo` could be added to check for content identity.

**Comment by jhy** [comment]
I'm coming around to this - think the best path will be to revert the .equals and .hashcode back to identity, and move the .equals into a .compareTo.
