### ISSUE TITLE
Element#appendText(null) does not throw an exception (1.8.3)

### ISSUE THREAD

**Issue by gitastrophe** [jhy/jsoup#690]
A call to `Element#appendText(null)` creates a TextNode child of the Element with its "text" attribute set to null.

A subsequent call to `Element#text()` will then throw a NullPointerException, originating from `StringUtil#appendNormalisedWhitespace` as the NodeTraversor encounters the TextNode child and attempts to append its content to the accumulator.

> java.lang.NullPointerException
> 	at org.jsoup.helper.StringUtil.appendNormalisedWhitespace(StringUtil.java:131)
> 	at org.jsoup.nodes.Element.appendNormalisedText(Element.java:929)
> 	at org.jsoup.nodes.Element.access$000(Element.java:21)
> 	at org.jsoup.nodes.Element$1.head(Element.java:879)
> 	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
> 	at org.jsoup.nodes.Element.text(Element.java:891)

This situation becomes difficult to debug, and could be avoided by throwing an Exception at the time the TextNode is created (or instead, populating the TextNode's content with an empty String).

Example to reproduce:

> Element element = new Element(Tag.valueOf("div"), "");
> element.appendText(null);
> return element.text(); // throws NullPointerException

**Comment by jhy** [comment]
Thanks. Fixed with 941f69b
