### ISSUE TITLE
Doesn't handle self closing <title/> appropriately

### ISSUE THREAD

**Issue by tdumitriu** [jhy/jsoup#691]
Having the following simple html page:
`<html>
  <head>
    <title/>
  </head>
  <body>
    <p>Paragraph</p>
  </body>
</html>`
**Jsoup**._parse_(_InputStream_ **in**, _String_ **charsetName**, _String_ **baseUri**) will produce the following output:
`<html>
 <head> 
  <title></title>
 </head>
 <body>
   &lt;/head&gt;  
  <p>Paragraph</p>   
 </body>
</html>`
The **TITLE** element from the given example might be invalid (`<title />`) but this is not the expected behavior.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
