### ISSUE TITLE
Jcenter

### ISSUE THREAD

**Issue by josinaldobarbosa** [jhy/jsoup#692]
put in a repository to facilitate

**Comment by jhy** [comment]
What would be the benefit? Jcenter already proxies Maven Central, which jsoup is published to.

**Comment by josinaldobarbosa** [comment]
so I can put directly into my build.gradle: compile ...?
how to do it?

**Comment by jhy** [comment]
```groovy
compile 'org.jsoup:jsoup:1.8.3'
```

Same as any other Gradle dependency.
