### ISSUE TITLE
Pseudo-header "refresh"does not get executed

### ISSUE THREAD

**Issue by flyingfischer** [jhy/jsoup#693]
JSOUP does not follow the legacy refresh pseudo-header in a http response:

http://www.imf.org/external/pubs/ft/fandd/index.htm will first send a 301 redirect to

http://www.imf.org/redirect/?URL=$V&404;http://prdwww-legacy-ext.imf.org:80/external/pubs/ft/fandd/index.htm

JSPOUP follows correctly. But then there will be a 200 reponse with the header "refresh" containing:

0; url=/external/pubs/ft/fandd/2016/03/index.htm

Browsers deal with this pseudo-header, but JSOUP gets stuck.

Thanks for considering the situation.

**Comment by jhy** [comment]
[Dupe of #371]
