### ISSUE TITLE
UTF16 streams with BOM are processed as UTF-8

### ISSUE THREAD

**Issue by ArjohnKampman** [jhy/jsoup#695]
The handling of the character encoding in org.jsoup.helper.DataUtil.parseByteData(...) is bugged when the input is an UTF16 stream with unicode BOM. This method does a check for presence of a BOM and, if it finds one, incorrectly assumes that this was a UTF-8 BOM. To fix this, the code would have to check the raw BOM bytes as the distinction between the various BOMs is lost after conversion to characters. See also: http://unicode.org/faq/utf_bom.html#bom4

**Comment by jhy** [comment]
Do you know any example sites I can validate a fix on?

**Comment by ArjohnKampman** [comment]
Perhaps this one, it has a UTF-16LE BOM: http://www.i18nguy.com/unicode/plane1-utf-16.html
