### ISSUE TITLE
JSOUP HTML tree is omitting certain tags during traversing

### ISSUE THREAD

**Issue by amosyeo** [jhy/jsoup#697]
I am trying to traverse the HTML tree of a Wikipedia page, however, it seems that it is omitting certain blocks of HTML elements in the code. 

Program Code:
```java
String url = "https://en.wikipedia.org/wiki/Dresden";
Document doc = Jsoup.connect(url).timeout(10000).userAgent(USER_AGENT).get();
Element tableWithDetails = doc.select("table[class=infobox geography vcard").get(0);
    tableWithDetails.traverse(new NodeVisitor() {
        public void head(Node node, int depth) {
            if(!node.nodeName().equalsIgnoreCase("#text")){
                p("Entering tag: " + node.nodeName());
            }
        }
        public void tail(Node node, int depth) {
            if(!node.nodeName().equalsIgnoreCase("#text")){
                 p("Exiting tag: " + node.nodeName());
            }
        }
    });
```

Wikipedia HTML CODE
```html
<table class="infobox geography vcard" style="width:22em;width:23em"> 
 <tbody>
  <tr> 
    <th colspan="2" style="text-align:center;font-size:125%;font-weight:bold;font-size:1.25em; white-space:nowrap"><span class="fn org"><span class="wrap">Dresden</span></span></th> 
    </tr> 
    <tr> 
    <td colspan="2" style="text-align:center;padding:0.7em 0.8em"><a href="/wiki/File:Dresden_montage.JPG" class="image" title="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger."><img alt="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger." src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/300px-Dresden_montage.JPG" width="300" height="390" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/450px-Dresden_montage.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/600px-Dresden_montage.JPG 2x" data-file-width="610" data-file-height="792"></a> 
  <div>
   Clockwise: Dresden at night, 
   <a href="/wiki/Dresden_Frauenkirche" title="Dresden Frauenkirche">Dresden Frauenkirche</a>, 
  <a href="/wiki/Schloss_Pillnitz" title="Schloss Pillnitz" class="mw-redirect">Schloss Pillnitz</a>, 
   <a href="/wiki/Dresden_Castle" title="Dresden Castle">Dresden Castle</a> and 
   <a href="/wiki/Zwinger_(Dresden)" title="Zwinger (Dresden)">Zwinger</a>.
  </div> </td> 
  </tr>
```

Output:
Entering tag: table
Entering tag: tbody
Entering tag: tr
Entering tag: th
Entering tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: th
Exiting tag: tr
Entering tag: tr
Entering tag: td
Entering tag: a
Entering tag: img
Exiting tag: img
Exiting tag: a
Exiting tag: td
Exiting tag: tr

It is omitting the div just before the td and tr at the end.

**Comment by jhy** [comment]
I can't repro this. Can you post your full code, and the input and output HTML? Not sure what your UserAgent is, could be the issue.

I ran this, on java 1.8 with jsoup 1.8.3. Note that the output is way bigger that yours, and does include the "Dresden at night" div.

```java
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;
import org.jsoup.select.NodeVisitor;

import java.io.IOException;

public class TestDresden {
    public static void main(String[] args) throws IOException {
        String url = "https://en.wikipedia.org/wiki/Dresden";
        Document doc = Jsoup.connect(url)
            .timeout(10000)
            .userAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36")
            .validateTLSCertificates(false)
            .get();
        Element tableWithDetails = doc.select("table[class=infobox geography vcard").get(0);
        System.out.println(tableWithDetails.outerHtml());
        tableWithDetails.traverse(new NodeVisitor() {
            public void head(Node node, int depth) {
                if (!node.nodeName().equalsIgnoreCase("#text")) {
                    System.out.println("Entering tag: " + node.nodeName());
                }
            }

            public void tail(Node node, int depth) {
                if (!node.nodeName().equalsIgnoreCase("#text")) {
                    System.out.println("Exiting tag: " + node.nodeName());
                }
            }
        });
    }
}
```
```
Entering tag: table
Entering tag: tbody
Entering tag: tr
Entering tag: th
Entering tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: th
Exiting tag: tr
Entering tag: tr
Entering tag: td
Entering tag: a
Entering tag: img
Exiting tag: img
Exiting tag: a
Entering tag: div
Entering tag: a
Exiting tag: a
Entering tag: a
Exiting tag: a
Entering tag: a
Exiting tag: a
Entering tag: a
Exiting tag: a
Exiting tag: div
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: td
Entering tag: table
Entering tag: tbody
Entering tag: tr
Entering tag: td
Entering tag: a
Entering tag: img
Exiting tag: img
Exiting tag: a
Entering tag: br
Exiting tag: br
Entering tag: small
Entering tag: b
Entering tag: a
Exiting tag: a
Exiting tag: b
Exiting tag: small
Exiting tag: td
Exiting tag: tr
Exiting tag: tbody
Exiting tag: table
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: td
Entering tag: div
Entering tag: div
Entering tag: div
Entering tag: div
Entering tag: a
Entering tag: img
Exiting tag: img
Exiting tag: a
Entering tag: div
Entering tag: div
Entering tag: img
Exiting tag: img
Exiting tag: div
Entering tag: div
Entering tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: div
Exiting tag: div
Exiting tag: div
Exiting tag: div
Exiting tag: div
Exiting tag: div
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: td
Entering tag: span
Entering tag: span
Entering tag: a
Entering tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: a
Exiting tag: span
Entering tag: span
Entering tag: span
Entering tag: a
Exiting tag: a
Entering tag: span
Entering tag: a
Entering tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Entering tag: span
Entering tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: a
Exiting tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: span
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Entering tag: td
Entering tag: sup
Exiting tag: sup
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: span
Entering tag: sup
Entering tag: a
Exiting tag: a
Exiting tag: sup
Exiting tag: span
Exiting tag: th
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Entering tag: td
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Entering tag: td
Entering tag: sup
Exiting tag: sup
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Entering tag: a
Exiting tag: a
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Entering tag: tr
Entering tag: th
Exiting tag: th
Entering tag: td
Entering tag: a
Exiting tag: a
Exiting tag: td
Exiting tag: tr
Exiting tag: tbody
Exiting tag: table
```

HTML Output
```html

<table class="infobox geography vcard" style="width:22em;width:23em"> 
 <tbody>
  <tr> 
   <th colspan="2" style="text-align:center;font-size:125%;font-weight:bold;font-size:1.25em; white-space:nowrap"><span class="fn org"><span class="wrap">Dresden</span></span></th> 
  </tr> 
  <tr> 
   <td colspan="2" style="text-align:center;padding:0.7em 0.8em"><a href="/wiki/File:Dresden_montage.JPG" class="image" title="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger."><img alt="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger." src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/300px-Dresden_montage.JPG" width="300" height="390" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/450px-Dresden_montage.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/600px-Dresden_montage.JPG 2x" data-file-width="610" data-file-height="792"></a> 
    <div>
     Clockwise: Dresden at night, 
     <a href="/wiki/Dresden_Frauenkirche" title="Dresden Frauenkirche">Dresden Frauenkirche</a>, 
     <a href="/wiki/Schloss_Pillnitz" title="Schloss Pillnitz" class="mw-redirect">Schloss Pillnitz</a>, 
     <a href="/wiki/Dresden_Castle" title="Dresden Castle">Dresden Castle</a> and 
     <a href="/wiki/Zwinger_(Dresden)" title="Zwinger (Dresden)">Zwinger</a>.
    </div> </td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <td colspan="2" class="maptable" style="text-align:center"> 
    <table style="width:100%; background:none;"> 
     <tbody>
      <tr> 
       <td style="vertical-align:middle; text-align:center;"><a href="/wiki/File:Dresden_Stadtwappen.svg" class="image" title="Coat of arms of Dresden "><img alt="Coat of arms of Dresden " src="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/77px-Dresden_Stadtwappen.svg.png" width="77" height="80" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/116px-Dresden_Stadtwappen.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/154px-Dresden_Stadtwappen.svg.png 2x" data-file-width="244" data-file-height="253"></a><br> <small><b><a href="/wiki/Coat_of_arms_of_Dresden" title="Coat of arms of Dresden">Coat of arms</a></b></small></td> 
      </tr> 
     </tbody>
    </table> </td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <td colspan="2" style="text-align:center"> 
    <div class="center"> 
     <div style="width:170px;float:none;clear:both;margin-left:auto;margin-right:auto"> 
      <div style="width:170px;padding:0"> 
       <div style="position:relative;width:170px">
        <a href="/wiki/File:Germany_location_map.svg" class="image" title="Dresden  is located in Germany"><img alt="Dresden  is located in Germany" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/170px-Germany_location_map.svg.png" width="170" height="202" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/255px-Germany_location_map.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/340px-Germany_location_map.svg.png 2x" data-file-width="1073" data-file-height="1272"></a> 
        <div style="position:absolute;top:51.477%;left:82.333%"> 
         <div style="position:absolute;left:-3px;top:-3px;line-height:0">
          <img alt="Dresden " src="//upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/6px-Red_pog.svg.png" title="Dresden " width="6" height="6" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/9px-Red_pog.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/12px-Red_pog.svg.png 2x" data-file-width="64" data-file-height="64">
         </div> 
         <div style="font-size:90%;line-height:110%;position:absolute;width:6em;top:-0.75em;right:4px;text-align:right">
          <span style="padding:1px;float:right"><span class="wrap">Dresden</span></span>
         </div> 
        </div> 
       </div> 
      </div> 
     </div> 
    </div> </td> 
  </tr> 
  <tr class="mergedbottomrow"> 
   <td colspan="2" style="text-align:center">Coordinates: <span style="white-space:nowrap"><span class="plainlinks nourlexpansion"><a class="external text" href="//tools.wmflabs.org/geohack/geohack.php?pagename=Dresden&amp;params=51_2_N_13_44_E_type:city(536308)_region:DE-SN"><span class="geo-default"><span class="geo-dms" title="Maps, aerial photos, and other data for this location"><span class="latitude">51°2′N</span> <span class="longitude">13°44′E</span></span></span><span class="geo-multi-punct">﻿ / ﻿</span><span class="geo-nondefault"><span class="geo-dec" title="Maps, aerial photos, and other data for this location">51.033°N 13.733°E</span><span style="display:none">﻿ / <span class="geo">51.033; 13.733</span></span></span></a></span><span style="font-size: small;"><span id="coordinates"><a href="/wiki/Geographic_coordinate_system" title="Geographic coordinate system">Coordinates</a>: <span class="plainlinks nourlexpansion"><a class="external text" href="//tools.wmflabs.org/geohack/geohack.php?pagename=Dresden&amp;params=51_2_N_13_44_E_type:city(536308)_region:DE-SN"><span class="geo-default"><span class="geo-dms" title="Maps, aerial photos, and other data for this location"><span class="latitude">51°2′N</span> <span class="longitude">13°44′E</span></span></span><span class="geo-multi-punct">﻿ / ﻿</span><span class="geo-nondefault"><span class="geo-dec" title="Maps, aerial photos, and other data for this location">51.033°N 13.733°E</span><span style="display:none">﻿ / <span class="geo">51.033; 13.733</span></span></span></a></span></span></span></span></td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row">Country</th> 
   <td><a href="/wiki/Germany" title="Germany">Germany</a></td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row"><a href="/wiki/States_of_Germany" title="States of Germany">State</a></th> 
   <td><a href="/wiki/Saxony" title="Saxony">Saxony</a></td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row"><a href="/wiki/Districts_of_Germany" title="Districts of Germany">District</a></th> 
   <td><a href="/wiki/Urban_districts_of_Germany" title="Urban districts of Germany" class="mw-redirect">Urban district</a></td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Government</th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Lord_Mayor" title="Lord Mayor">Lord Mayor</a></th> 
   <td><a href="/w/index.php?title=Dirk_Hilbert&amp;action=edit&amp;redlink=1" class="new" title="Dirk Hilbert (page does not exist)">Dirk Hilbert</a> (<a href="/wiki/Free_Democratic_Party_(Germany)" title="Free Democratic Party (Germany)">FDP</a>)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Area</th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;City</th> 
   <td>328.8&nbsp;km<sup>2</sup> (127.0&nbsp;sq&nbsp;mi)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Population <span style="font-weight:normal">(2014-12-31)<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup></span></th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;City</th> 
   <td>536,308</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;Density</th> 
   <td>1,600/km<sup>2</sup> (4,200/sq&nbsp;mi)</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Urban_area" title="Urban area">Urban</a></th> 
   <td>780,561</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Metropolitan_area" title="Metropolitan area">Metro</a></th> 
   <td>1,143,197</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row"><a href="/wiki/Time_zone" title="Time zone">Time zone</a></th> 
   <td><a href="/wiki/Central_European_Time" title="Central European Time">CET</a>/<a href="/wiki/Central_European_Summer_Time" title="Central European Summer Time">CEST</a> (UTC+1/+2)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row">Website</th> 
   <td><a rel="nofollow" class="external text" href="http://www.dresden.de/">dresden.de</a></td> 
  </tr> 
 </tbody>
</table>
```

**Comment by amosyeo** [comment]
Hi,
Thank you for your reply,

this is my code:
public static void main(String[] args) {		try {			String USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1";			String url = "https://en.wikipedia.org/wiki/Dresden";			Document doc = Jsoup.connect(url).timeout(10000).userAgent(USER_AGENT).get();			Element tableWithDetails = doc.select("table[class=infobox geography vcard").get(0);			  tableWithDetails.traverse(new NodeVisitor() {			        public void head(Node node, int depth) {			            if(!node.nodeName().equals("#text")){				        	p("Entering tag: " + node.nodeName());				            }			        }			        public void tail(Node node, int depth) {			        	if(!node.nodeName().equals("#text")){			        		p("Exiting tag: " + node.nodeName());			        	}			        }			    });
		} catch (Exception e) {			e.printStackTrace();		}	}
HTML:
<table class="infobox geography vcard" style="width:22em;width:23em"> 
 <tbody>
  <tr> 
   <th colspan="2" style="text-align:center;font-size:125%;font-weight:bold;font-size:1.25em; white-space:nowrap"><span class="fn org"><span class="wrap">Dresden</span></span></th> 
  </tr> 
  <tr> 
   <td colspan="2" style="text-align:center;padding:0.7em 0.8em"><a href="/wiki/File:Dresden_montage.JPG" class="image" title="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger."><img alt="Clockwise: Dresden at night, Dresden Frauenkirche, Schloss Pillnitz, Dresden Castle and Zwinger." src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/300px-Dresden_montage.JPG" width="300" height="390" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/450px-Dresden_montage.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Dresden_montage.JPG/600px-Dresden_montage.JPG 2x" data-file-width="610" data-file-height="792"></a> 
    <div>
     Clockwise: Dresden at night, 
     <a href="/wiki/Dresden_Frauenkirche" title="Dresden Frauenkirche">Dresden Frauenkirche</a>, 
     <a href="/wiki/Schloss_Pillnitz" title="Schloss Pillnitz" class="mw-redirect">Schloss Pillnitz</a>, 
     <a href="/wiki/Dresden_Castle" title="Dresden Castle">Dresden Castle</a> and 
     <a href="/wiki/Zwinger_(Dresden)" title="Zwinger (Dresden)">Zwinger</a>.
    </div> </td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <td colspan="2" class="maptable" style="text-align:center"> 
    <table style="width:100%; background:none;"> 
     <tbody>
      <tr> 
       <td style="vertical-align:middle; text-align:center;"><a href="/wiki/File:Dresden_Stadtwappen.svg" class="image" title="Coat of arms of Dresden "><img alt="Coat of arms of Dresden " src="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/77px-Dresden_Stadtwappen.svg.png" width="77" height="80" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/116px-Dresden_Stadtwappen.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Dresden_Stadtwappen.svg/154px-Dresden_Stadtwappen.svg.png 2x" data-file-width="244" data-file-height="253"></a><br> <small><b><a href="/wiki/Coat_of_arms_of_Dresden" title="Coat of arms of Dresden">Coat of arms</a></b></small></td> 
      </tr> 
     </tbody>
    </table> </td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <td colspan="2" style="text-align:center"> 
    <div class="center"> 
     <div style="width:170px;float:none;clear:both;margin-left:auto;margin-right:auto"> 
      <div style="width:170px;padding:0"> 
       <div style="position:relative;width:170px">
        <a href="/wiki/File:Germany_location_map.svg" class="image" title="Dresden  is located in Germany"><img alt="Dresden  is located in Germany" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/170px-Germany_location_map.svg.png" width="170" height="202" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/255px-Germany_location_map.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Germany_location_map.svg/340px-Germany_location_map.svg.png 2x" data-file-width="1073" data-file-height="1272"></a> 
        <div style="position:absolute;top:51.477%;left:82.333%"> 
         <div style="position:absolute;left:-3px;top:-3px;line-height:0">
          <img alt="Dresden " src="//upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/6px-Red_pog.svg.png" title="Dresden " width="6" height="6" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/9px-Red_pog.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/0c/Red_pog.svg/12px-Red_pog.svg.png 2x" data-file-width="64" data-file-height="64">
         </div> 
         <div style="font-size:90%;line-height:110%;position:absolute;width:6em;top:-0.75em;right:4px;text-align:right">
          <span style="padding:1px;float:right"><span class="wrap">Dresden</span></span>
         </div> 
        </div> 
       </div> 
      </div> 
     </div> 
    </div> </td> 
  </tr> 
  <tr class="mergedbottomrow"> 
   <td colspan="2" style="text-align:center">Coordinates: <span style="white-space:nowrap"><span class="plainlinks nourlexpansion"><a class="external text" href="//tools.wmflabs.org/geohack/geohack.php?pagename=Dresden&amp;params=51_2_N_13_44_E_type:city(536308)_region:DE-SN"><span class="geo-default"><span class="geo-dms" title="Maps, aerial photos, and other data for this location"><span class="latitude">51°2′N</span> <span class="longitude">13°44′E</span></span></span><span class="geo-multi-punct">﻿ / ﻿</span><span class="geo-nondefault"><span class="geo-dec" title="Maps, aerial photos, and other data for this location">51.033°N 13.733°E</span><span style="display:none">﻿ / <span class="geo">51.033; 13.733</span></span></span></a></span><span style="font-size: small;"><span id="coordinates"><a href="/wiki/Geographic_coordinate_system" title="Geographic coordinate system">Coordinates</a>: <span class="plainlinks nourlexpansion"><a class="external text" href="//tools.wmflabs.org/geohack/geohack.php?pagename=Dresden&amp;params=51_2_N_13_44_E_type:city(536308)_region:DE-SN"><span class="geo-default"><span class="geo-dms" title="Maps, aerial photos, and other data for this location"><span class="latitude">51°2′N</span> <span class="longitude">13°44′E</span></span></span><span class="geo-multi-punct">﻿ / ﻿</span><span class="geo-nondefault"><span class="geo-dec" title="Maps, aerial photos, and other data for this location">51.033°N 13.733°E</span><span style="display:none">﻿ / <span class="geo">51.033; 13.733</span></span></span></a></span></span></span></span></td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row">Country</th> 
   <td><a href="/wiki/Germany" title="Germany">Germany</a></td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row"><a href="/wiki/States_of_Germany" title="States of Germany">State</a></th> 
   <td><a href="/wiki/Saxony" title="Saxony">Saxony</a></td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row"><a href="/wiki/Districts_of_Germany" title="Districts of Germany">District</a></th> 
   <td><a href="/wiki/Urban_districts_of_Germany" title="Urban districts of Germany" class="mw-redirect">Urban district</a></td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Government</th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Lord_Mayor" title="Lord Mayor">Lord Mayor</a></th> 
   <td><a href="/w/index.php?title=Dirk_Hilbert&amp;action=edit&amp;redlink=1" class="new" title="Dirk Hilbert (page does not exist)">Dirk Hilbert</a> (<a href="/wiki/Free_Democratic_Party_(Germany)" title="Free Democratic Party (Germany)">FDP</a>)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Area</th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;City</th> 
   <td>328.8&nbsp;km<sup>2</sup> (127.0&nbsp;sq&nbsp;mi)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th colspan="2" style="text-align:center;text-align:left">Population <span style="font-weight:normal">(2014-12-31)<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup></span></th> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;City</th> 
   <td>536,308</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;Density</th> 
   <td>1,600/km<sup>2</sup> (4,200/sq&nbsp;mi)</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Urban_area" title="Urban area">Urban</a></th> 
   <td>780,561</td> 
  </tr> 
  <tr class="mergedrow"> 
   <th scope="row">&nbsp;•&nbsp;<a href="/wiki/Metropolitan_area" title="Metropolitan area">Metro</a></th> 
   <td>1,143,197</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row"><a href="/wiki/Time_zone" title="Time zone">Time zone</a></th> 
   <td><a href="/wiki/Central_European_Time" title="Central European Time">CET</a>/<a href="/wiki/Central_European_Summer_Time" title="Central European Summer Time">CEST</a> (UTC+1/+2)</td> 
  </tr> 
  <tr class="mergedtoprow"> 
   <th scope="row">Website</th> 
   <td><a rel="nofollow" class="external text" href="http://www.dresden.de/">dresden.de</a></td> 
  </tr> 
 </tbody>
</table>

output:
Entering tag: tableEntering tag: tbodyEntering tag: trEntering tag: thEntering tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: thExiting tag: trEntering tag: trEntering tag: tdEntering tag: aEntering tag: imgExiting tag: imgExiting tag: aEntering tag: divEntering tag: aExiting tag: aEntering tag: aExiting tag: aEntering tag: aExiting tag: aEntering tag: aExiting tag: aExiting tag: divExiting tag: tdExiting tag: trEntering tag: trEntering tag: tdEntering tag: tableEntering tag: tbodyEntering tag: trEntering tag: tdEntering tag: aEntering tag: imgExiting tag: imgExiting tag: aEntering tag: brExiting tag: brEntering tag: smallEntering tag: bEntering tag: aExiting tag: aExiting tag: bExiting tag: smallExiting tag: tdExiting tag: trExiting tag: tbodyExiting tag: tableExiting tag: tdExiting tag: trEntering tag: trEntering tag: tdEntering tag: divEntering tag: divEntering tag: divEntering tag: divEntering tag: aEntering tag: imgExiting tag: imgExiting tag: aEntering tag: divEntering tag: divEntering tag: imgExiting tag: imgExiting tag: divEntering tag: divEntering tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: divExiting tag: divExiting tag: divExiting tag: divExiting tag: divExiting tag: divExiting tag: tdExiting tag: trEntering tag: trEntering tag: tdEntering tag: spanEntering tag: spanEntering tag: aEntering tag: spanEntering tag: spanEntering tag: spanExiting tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: spanEntering tag: spanExiting tag: spanEntering tag: spanEntering tag: spanExiting tag: spanEntering tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: spanExiting tag: aExiting tag: spanEntering tag: spanEntering tag: spanEntering tag: aExiting tag: aEntering tag: spanEntering tag: aEntering tag: spanEntering tag: spanEntering tag: spanExiting tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: spanEntering tag: spanExiting tag: spanEntering tag: spanEntering tag: spanExiting tag: spanEntering tag: spanEntering tag: spanExiting tag: spanExiting tag: spanExiting tag: spanExiting tag: aExiting tag: spanExiting tag: spanExiting tag: spanExiting tag: spanExiting tag: tdExiting tag: trEntering tag: trEntering tag: thExiting tag: thEntering tag: tdEntering tag: aExiting tag: aExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdEntering tag: aExiting tag: aExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdEntering tag: aExiting tag: aExiting tag: tdExiting tag: trEntering tag: trEntering tag: thExiting tag: thExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdEntering tag: aExiting tag: aEntering tag: aExiting tag: aExiting tag: tdExiting tag: trEntering tag: trEntering tag: thExiting tag: thExiting tag: trEntering tag: trEntering tag: thExiting tag: thEntering tag: tdEntering tag: supExiting tag: supExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: spanEntering tag: supEntering tag: aExiting tag: aExiting tag: supExiting tag: spanExiting tag: thExiting tag: trEntering tag: trEntering tag: thExiting tag: thEntering tag: tdExiting tag: tdExiting tag: trEntering tag: trEntering tag: thExiting tag: thEntering tag: tdEntering tag: supExiting tag: supExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdExiting tag: tdExiting tag: trEntering tag: trEntering tag: thEntering tag: aExiting tag: aExiting tag: thEntering tag: tdEntering tag: aExiting tag: aEntering tag: aExiting tag: aExiting tag: tdExiting tag: trEntering tag: trEntering tag: thExiting tag: thEntering tag: tdEntering tag: aExiting tag: aExiting tag: tdExiting tag: trExiting tag: tbodyExiting tag: tableDate: Sun, 3 Apr 2016 18:13:09 -0700

**Comment by jhy** [comment]
OK, and what's the problem? The parsed HTML DOM contains the div, it shows up in your traverse, and in the HTML output. What's your expected vs your actual? 

And can you please format your comment so we can read it?

**Comment by amosyeo** [comment]
Hi,
We managed to solve the problem by changing the user agent, the output that we sent you was mistakenly the new output after the change was done.

Date: Mon, 4 Apr 2016 11:24:46 -0700

**Comment by jhy** [comment]
Sounds good
