### ISSUE TITLE
Cannot Disable Caching

### ISSUE THREAD

**Issue by nsiatras** [jhy/jsoup#698]
Hello,

I am trying to disable caching but Jsoup always returns cached data.

The Code I am using is the following:
 Document doc = Jsoup.connect(webPageURLToScan).userAgent("Mozilla").header("Cache-control", "no-cache").header("Cache-store", "no-store").timeout(4000).get();

Is there an other way or Jsoup cannot disable caching ?

**Comment by jhy** [comment]
jsoup doesn't implement any HTTP cache. It goes straight into URL.openConnection(). What is giving you the impression that it does? Are you talking about a local, a proxy, or a server cache? Can you provide a full test case?

**Comment by nsiatras** [comment]
Hello,

I am doing the following:

```
private Document fDoc;

public void KeepGetttingData()
{
   
// I get data for first time
fDoc = Jsoup.connect(webPageURLToScan).userAgent("Mozilla").header("Cache-control", "no-cache").header("Cache-store", "no-store").timeout(4000).get();

// In that point I change the webPageURLToScan website data

// The second time I get the data the data are the same
// and that goes on.....
 fDoc = Jsoup.connect(webPageURLToScan).userAgent("Mozilla").header("Cache-control", "no-cache").header("Cache-store", "no-store").timeout(4000).get();

}
```

**Comment by jhy** [comment]
Could you address my questions? Also what environment are you on? Again, jsoup doesn't maintain any cache, so something else is caching it along the line and you need to bust through that.

**Comment by nsiatras** [comment]
Hello,

I am under Android API 21 and I get data from a remote server (Apache
2.4.16)
You are saying that JSoup does not cache things so I suppose you know what
you are talking about.

I will try to isolate a few things from the project tomorrow and I will get
back to you.

Thank you
Nikos
