### ISSUE TITLE
Should detect ?xml encoding charset

### ISSUE THREAD

**Issue by haibison** [jhy/jsoup#701]
Hi,

For example this is target URL: <http://www.elacontecer.com.uy/rss/hoy.xml>, its charset is `ISO-8859-1`.

I use Jsoup like this:

```java
final Document doc = Jsoup.connect("http://...").parser(Parser.xmlParser()).get();
System.out.println("charset=" + doc.charset());
```

The result is: `java.nio.charset.CharsetICU[UTF-8]`

Would you please check to see if it's a bug?

Thanks,

**Comment by jhy** [comment]
There's no charset defined in the HTTP header, so jsoup falls back its default of UTF8.

**Comment by haibison** [comment]
@jhy Thank you.

May I ask if it's named XML parser, it should handle XML charset?

**Comment by jhy** [comment]
Oh, I'm sorry, I missed that it has a `<?xml version="1.0" encoding="ISO-8859-1"?>` start. Yeah we should add support for that.

**Comment by jhy** [comment]
DataUtil around line 114

**Comment by haibison** [comment]
Thanks, that's great  `:-)`

And thank you again for a great library.

Have a nice day.
