### ISSUE TITLE
Bug in apidoc

### ISSUE THREAD

**Issue by IgorTatarko** [jhy/jsoup#703]
Hi, please follow the link:
https://jsoup.org/apidocs/org/jsoup/select/Elements.html#not-java.lang.String-

> **not**
> public Elements not(String query)
> Remove elements from this list that match the Selector query.
> E.g. HTML: `<div class=logo>One</div> <div>Two</div>`

//In the next string bug, look at the expression ".not("#logo");" it is not true, right version is ".not(".logo");"

> `Elements divs = doc.select("div").not("#logo"); `
> Result: divs: [`<div>Two</div>`] 

Check it, please.
Thanks.

**Comment by jhy** [comment]
Thanks!
