### ISSUE TITLE
Unselectable table...

### ISSUE THREAD

**Issue by Stephan972** [jhy/jsoup#705]
A Jsoup user has found this (terrible) HTML page:
http://gs-fall15athenaandclassic.sportsaffinity.com/tour/public/info/schedule_results2.asp?sessionguid=&flightguid=CB37D3C7-5EF7-4CCE-8918-3AC3083495A3&tournamentguid=173EB212-BADB-425F-BE03-D05CA448AD8D

He tries to select the table right under the text:

> **Winner of bracket based on total points after round robin play.**

On real browsers such as Chrome or Firefox, the table can be selected with the following CSS query:
- Chrome: `#tabs-1 > div > table:nth-child(12)`
- Firefox: `.placeholder > table:nth-child(12)`

However, with Jsoup, the table isn't found. See this [demo](http://try.jsoup.org/~iiSY6qKC-2HuwLr4OcEPiOpFF_U).

There is a workaround: `table#Table6 + table > tbody:has(tr.theadb)`

However why Jsoup can't find the table with CSS selectors similar to the browsers ones?

**See also:**
- [JSoup selector not returning result](http://stackoverflow.com/q/36960038/363573)

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
