### ISSUE TITLE
jsoup HttpConnection charset issue on http redirect Location

### ISSUE THREAD

**Issue by florisvdg** [jhy/jsoup#706]
Bit of an exceptional case, but when loading a shortened url that redirects to a url that contains the character ``` ‘ ```, it continues with a malformed url with character ``` â ``` instead.

To reproduce:
```java
Jsoup.connect("http://brabantn.ws/Q4F").get();
```
Even though the Location field seems properly encoded by the shortener server:
```
Cache-Control: private
Content-Length: 0
Date: Tue, 10 May 2016 14:28:17 GMT
Location: http://www.omroepbrabant.nl/?news/2474781303/Gestrande+ree+bij+familiebedrijf+in+Oss+doodgeschoten+%E2%80%98Dit+kan+gewoon+niet,+bizar%E2%80%99+[VIDEO].aspx
Server: Microsoft-IIS/7.5
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
```

Also works fine when visiting the url through a browser.

**Comment by jhy** [comment]
Thanks!
