### ISSUE TITLE
jsoup 1.9.1 parse bug(no response)

### ISSUE THREAD

**Issue by bobcy2015** [jhy/jsoup#707]
I found when i crawl a few webpage's html sourcecode as string, then i used jsoup.parse(htmlcontent) to convert it to Document, it will enter a strange status: CPU's usage will stay over 20%, and there're no return with the code for a long long time. But if I change to use jsoup 1.8.1 to parse the same html sourcecode. It works fine.

someone can try this webpage's html sourcecode with jsoup.parse(), then you will see the bug:
http://zt-hzrb.hangzhou.com.cn/system/2012/07/22/012014170.shtml

**Comment by jhy** [comment]
I confirmed this has the same root cause as #704 and is fixed in HEAD, pending the release of 1.9.2 which I will expedite.
