### ISSUE TITLE
Unable to get real HTML code with JSoup

### ISSUE THREAD

**Issue by fncapps** [jhy/jsoup#708]
When fetching a URL from java I'm using
 ```
Document doc = JSoup.connection(URL).get();
```
but I'm getting a HTML code that doesn't corresponds with the real web you can see in the screen from that URL. The web page is based on ASP so maybe it has to do with that.

How can I manage to get the 'real' HTML code?

**Comment by jhy** [comment]
What's the URL? What's the HTML you expected? What's the HTML you got?

Is the server sensitive to the user agent (try setting a mobile or a desktop browser UA)

Does the page contain Javascript that modifies the DOM? Jsoup doesn't execute Javascript.

**Comment by fncapps** [comment]
For example this one: https://indusnet.etsii.upm.es/gestion_escuela/login_indusnet.asp
If you see the html source code you'll see that there is nothing similar to what is being shown in the screen. Probably the page contains some JS that modifies the DOM as you are saying. In case that  Jsoup can't do this, could you tell me about any other way of achieving it?

Thanks

**Comment by jhy** [comment]
https://indusnet.etsii.upm.es/gestion_escuela/login_indusnet.asp is a frameset. Hit it and select the frame with the login page:

http://try.jsoup.org/~twfXJiIOabaf4kbokgbXoeu1wGg

That gives https://indusnet.etsii.upm.es/gestion_escuela/login_formulario.asp

http://try.jsoup.org/~AT49yYmRV4qpMCqX8MojTRbkGs4

And you can see jsoup parses both of these pages fine and can select the inputs.
