### ISSUE TITLE
Interrupt running JSoup thread

### ISSUE THREAD

**Issue by KidCrippler** [jhy/jsoup#711]
Following an issue I've previously created regarding JSoup read timeout:
[https://github.com/jhy/jsoup/issues/628]

I understand that implementing a max timer is not a top priority right now.

However, it would really help if a thread running JSoup could at least be interrupted in a normal manner and not get stuck forever.
For example - crawling the page [http://jsscxml.org/serverload.stream] **never** returns.
It's stuck in the loop within `DataUtil::readToByteBuffer`.

I tried to wrap it with a monitor thread that calls `interrupt()` on the JSoup thread if a specified amount of time has passed since it started, but an interrupt can't be consumed unless the thread periodically checks for it (for example, using `while(!Thread.isInterrupted()` instead of `while(true)`).

Any help would be appreciated,
Thanks

**Comment by ximencx** [comment]
I  have  same question。 you  method  is  set  flag   To  thread。 how  to  deal  whith question  about  life cycle  of  jsoup，example    when jsSoup  timeout  Or  when  jsoup working  I   want  to  stopit ?

**Comment by ximencx** [comment]
Thanks  you for  your answer😉

**Comment by jhy** [comment]
Thanks, implemented.
