### ISSUE TITLE
CSS selector incorrectly works with comma

### ISSUE THREAD

**Issue by unoexperto** [jhy/jsoup#713]
Could you please clarify if CSS selector that I use incorrectly works with comma or is it me not fully understanding how it should work ?

I'm trying to parse table of this page http://www.citefactor.org/journal-impact-factor-list-2014_0-A.html

Following CSS selector returns tree elements instead of two

`div.panel-body.news > table > tbody > tr:eq(2),tr:eq(1)`

but

`div.panel-body.news > table > tbody > tr:eq(1),tr:eq(2)`

returns two.

**Comment by jhy** [comment]
Looks like a precedence issue? The comma is an or operator and has high precedence. So you're query is like: `div.panel-body.news > table > tbody > tr:eq(2)` OR `tr:eq(1)`. So I guess you want

`div.panel-body.news > table > tbody > tr:eq(2), div.panel-body.news > table > tbody >tr:eq(1)`

Does that give data you want or get you closer?
