### ISSUE TITLE
Binary Incompatibility introduced in 1.8.2

### ISSUE THREAD

**Issue by mfulgo** [jhy/jsoup#714]
Code compiled against JSoup `1.8.1` (and earlier versions) may fail with a `NoSuchMethodError` when running with `1.8.2` or newer if certain methods of `Elements` are called.

Commit b9c1740 removes many of the methods that were defined on the `Elements` class in favor of inheriting them from a new parent class, `ArrayList`. Unfortunately, that's a binary-compatibility-breaking change because compiled code will attempt to call the methods on the `Elements` object itself and result in the aforementioned `NoSuchMethodError`.

A simple fix would be to re-add the methods and simply have them delegate to the super class.

**Comment by mfulgo** [comment]
cc @tdumitriu

**Comment by jhy** [comment]
Thanks for the report, and sorry about the issue. I haven't been targeting binary compatibility (vs api / source compatibility). Given the time since these changes were made and relatively low impact, will not plan on reverting this.
