### ISSUE TITLE
Inifinite loop while parsing not proper html string

### ISSUE THREAD

**Issue by moonm4n** [jhy/jsoup#716]
Hi,

We've got this error where while parsing an html string with some incorrect tags in it the parser gets stuck in an infinite loop. The problem only exist if letters with accents are present.

Example code:
```
String tmp = "<html><body><p><title>xxx yyy</ikzép> zzz</p></body></html>";
Document doc = Jsoup.parse(tmp);
```

If I replace the "é" character in the string it works as expected.

**Result:** 
The parse function never returns and doesn't accept Interrupt when trying to kill the thread (e.g. we use this function in a Future object, but we cannot kill it if it doesn't return in time).

**Expected result:**
Either return with a valid html string or have the ability to die gracefully.

Thanks!

**Comment by jhy** [comment]
Sorry you got hit with that. This was fixed in Release 1.9.2 [2016-May-17].
