### ISSUE TITLE
possible inconsistency with org.jsoup.nodes.Element.text()?

### ISSUE THREAD

**Issue by Redirion** [jhy/jsoup#718]
String tmp = "<html><body><h1><i class=\"someClass someClass2\"></i></h1></body></html>";
	doc = Jsoup.parse(tmp);
	if(doc.select("h1").get(0).text().isEmpty()) {
		doc.select("h1").get(0).text("Heading1");
	}
	System.out.println(doc.html());

prints 
`<html>
 <head></head>
 <body>
  <h1>Heading1</h1>
 </body>
</html>`

However I would have expected that the child element with the i tag gets not removed when setting new text as text() returned an empty String.
Is this intended? I have to use "prepend()" instead of "text()" to avoid this pitfall.

Will #564 be a solution for this?

**Comment by jhy** [comment]
Yes, this is intended. Per the [doc](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#text-java.lang.String-):

    Set the text of this element. Any existing contents (text or elements) will be cleared

You can use appendText / prependText if you want to preserve the child nodes.
