### ISSUE TITLE
XML Selector with any namespace

### ISSUE THREAD

**Issue by er1c** [jhy/jsoup#723]
I'm running into the same situation described here: http://stackoverflow.com/questions/23764992/parse-xml-nodes-having-text-with-any-namespace-using-jsoup

I would like to have an easy way to ignore the namespace when creating a selector.  I would probably propose: `*|E` that matches elements of type E in any namespace (wildcard) (https://jsoup.org/apidocs/org/jsoup/select/Selector.html)

**Comment by jhy** [comment]
Thanks, I merged #724
