### ISSUE TITLE
Removes double or more whitespace

### ISSUE THREAD

**Issue by bliaxiong** [jhy/jsoup#730]
Awesome library btw. Cleaning a string that contains two or more whitespace together removes them and leaves only one space. I don't know if this is a bug or was designed like that.

Example:
before:

```
{"foo": "one  two"}
```

after:

```
{"foo": "one two"}
```

**Comment by jhy** [comment]
Thanks for your feedback (and sorry for the late reply!)

This is by design as HTML does not consider runs of spaces to be meaningful. Here you are using json, which jsoup doesn't expect.
