### ISSUE TITLE
Jsoup make changes to the cookie collection

### ISSUE THREAD

**Issue by SzabKel** [jhy/jsoup#735]
If I have a `Map<String,String>`, passed to `Jsoup.connect(..).cookies(this.cookieMap)`, Jsoup will make changes to the map, while it should not bother the arguments I think (If I want to send the same cookies multiple times). I can avoid this If I pass a copy of the Collection (`.cookies(new HashMap<>(this.cookieMap))` ).

**Comment by SzabKel** [comment]
If you pass cookies to a request, the response won't contain cookies anymore.

**Comment by jhy** [comment]
Logically fixed with #1476, use #newRequest
