### ISSUE TITLE
Switch timeout from int to long in method Jsoup.parse

### ISSUE THREAD

**Issue by Hronom** [jhy/jsoup#741]
Current implementation of method `org.jsoup.Jsoup#parse(java.net.URL, int)` uses `int` for `timeoutMillis` but preferable is to use `long`, for example `Java java.lang.Thread#sleep(long)` and `private static final long htmlParseTimeout = TimeUnit.SECONDS.toMillis(10);`.

Can this be changed just for sugar use and better compatibility?

**Comment by jhy** [comment]
Sounds good, please submit a PR. Please make sure you keep the current method for compat.

**Comment by Hronom** [comment]
Ok, I will try to do it.
And one more question: mark old method as deprecated?

**Comment by Hronom** [comment]
Oh, it's looks like, cannot be done because of `java.net.URLConnection#setConnectTimeout(int)`

**Comment by jhy** [comment]
OK. Maybe add a method `timeoutSeconds(int)`? Everyone always specifies in seconds anyway.

**Comment by Hronom** [comment]
@jhy Nah, I see no reason for this... for example, `TimeUnit.MINUTES.toSeconds()` returns long, this is not that gives sugar=)

Maybe `int` is the right way...

**Comment by Hronom** [comment]
For me this question is closed, so if you want you can close this issue...
