### ISSUE TITLE
I got a problem how to get Elements table in html and has nested table inside

### ISSUE THREAD

**Issue by Freemanhack** [jhy/jsoup#742]
how can I get elements from all table and each table don't select nested table

I want to select table from id= customers,customers2,customers3
but the problem is customers3 is nested in customers2 
I don't want to use get by id and customers2 don't have any customers3 item

please help and thank you in advanced for every comment
sorry for my English
PS. for easiest way you can try in web https://try.jsoup.org/ 
[Table01.txt](https://github.com/jhy/jsoup/files/403482/Table01.txt)

**Comment by jhy** [comment]
Doesn't sounds like a bug, just about using selectors correctly. I'd suggest you hit up StackOverflow for some assistance.
