### ISSUE TITLE
Add an org.w3c.dom binding to jsoup for improved interoperability

### ISSUE THREAD

**Issue by lukaseder** [jhy/jsoup#745]
jsoup is excellent for dealing with "real world" HTML, which isn't necessarily well formed XML in its text form. But XML is an excellent tool, with wonderful features like XSLT, XPath, etc. If jsoup provided an `org.w3c.dom` binding, then all sorts of XML-related APIs could be used with jsoup.

If that's something that's interesting for you, I could definitely provide a PR for this.

**Comment by dbenesj** [comment]
There is a possibility to create org.w3c.dom.Document from org.jsoup.nodes.Document with [W3CDom.fromJsoup()](https://jsoup.org/apidocs/org/jsoup/helper/W3CDom.html#fromJsoup-org.jsoup.nodes.Document-)
I'm using XPath on the resulting w3c.Document

**Comment by lukaseder** [comment]
Oh, great, I've overlooked that. Sorry for the noise.

**Comment by dportabella** [comment]
still, it would be great that jsoup can use org.w3.dom, not only convert it to once parsed.
use case: parse a html doc, use standard xpath library and ask jsoup to return a text on these nodes.
we can use the xjoup library to use xpath on jsoup, but it is incomplet, and there are much more libraries around using org.w3.dom.
