### ISSUE TITLE
Add license file to artifact

### ISSUE THREAD

**Issue by EricDuell** [jhy/jsoup#749]
Hi, 

could you please add the MIT license file to the created archive. It would help our analysis tool that scans all used third party artifacts.

Best regards, Eric

**Comment by jhy** [comment]
Where in the jar should it go?

**Comment by EricDuell** [comment]
Most of the jars have it in root, a few add it into the META-INF folder. For tools like clmscan it doesn't matter. It scans the complete archive.

**Comment by jhy** [comment]
Thanks, done.

**Comment by EricDuell** [comment]
Well I have to thank you :)
