### ISSUE TITLE
Add new method org.jsoup.nodes.Document#xml()

### ISSUE THREAD

**Issue by ghost** [jhy/jsoup#750]
Hi,

I know there's a method `Element#html()` to generate html. However xml has a header like:

``` xml
<?xml version="1.0" encoding="utf-8"?>
```

and `Element#html()` won't generate that header, which is true, of course.

So new method `Document#xml()` would come in handy. I would suggest to put it in `Document`, because to generate an element (without any header like above), we already have `Element#html()`.

It would be great if you consider supporting this.

Thank you,

**Comment by jhy** [comment]
Calling [doc.charset(UTF8)](https://jsoup.org/apidocs/org/jsoup/nodes/Document.html#charset(java.nio.charset.Charset)) is just about equivalent to this, so not currently planning to add this.
