### ISSUE TITLE
Event parser support

### ISSUE THREAD

**Issue by fvasco** [jhy/jsoup#758]
Hi,
I need to extract from remote URL only page metadata (tags meta and title), for security and performance reasons I must not download full page and I need to read only the HEAD tag (or the first 8kb).

The class HtmlTreeBuilder works as event parser but unfortunately I can't use it.

Can you expose parsing event for HTML pages?

Thanks,
Francesco

**Comment by jokester** [comment]
Hello there,

This is not a complete solution, but FYI, the `Tokeniser` class in jsoup may be useful for your purpose. It can be used to extract tokens (start tag / end tag / text / comment) from string.

**Comment by jhy** [comment]
Same as #824
