### ISSUE TITLE
.append , the node turn in lowcase 

### ISSUE THREAD

**Issue by enzozhong** [jhy/jsoup#769]
**Code**

```
File file = new File( "/tomcat/conf/server.xml" );
String content = load( file ); 
Document document = Jsoup.parse (content , "" , Parser.xmlParser());
document.append( "<Connector />" );
System.out.println( document );
```

**Result**

```
<?xml version="1.0" encoding="UTF-8"?>
....
<connector />
```

**Question**
how can append the node in my input , not the lowcase , i am using branch "parsesettings"

**Comment by jhy** [comment]
Thanks, this is fixed now. The document retains the parser used to parse it, and therefore can remember which settings to use when parsing more content.
