### ISSUE TITLE
Parse HTML and Javascript content

### ISSUE THREAD

**Issue by jcagarcia** [jhy/jsoup#774]
Hi!

I'm parsing an HTML string that contains html tags and javascript tags using the following

````
public Document parse(String content) {
    return Jsoup.parse(content, "", Parser.xmlParser());
  }
````

The problem is that javascript elements have been included only in one line.

Also, I've try with 

````
public Document parse(String content) {
    return Jsoup.parse(content, "", Parser.htmlParser());
  }
````

and that works fine for Javascript... but HTML elements have been included without end line. Ex:

````
    <link rel="shortcut icon" href="../../static/public/img/favicon.ico" data-th-remove="all"></link>
````

has been parsed like

````
    <link rel="shortcut icon" href="../../static/public/img/favicon.ico" data-th-remove="all">
````

That doesn't work when I run my application.

How can I fix that?

Regards

**Comment by jhy** [comment]
I'm not sure I'm following. Link tags in HTML5 don't need closing tags as they are empty.

What does "javascript elements have been included only in one line" mean?

Maybe you can give your input and desired output and we can find the path.

**Comment by jcagarcia** [comment]
Hi @jhy and thanks for your answer,

I'm using `Parser.xmlParser()` under HTML file that contains javascript code formatted like:

````
jQuery(document).ready(function(){
    alert("Hello World");
});
````

After apply the `Jsoup.parse` the HTML code is parsed well, but the following javascript is written:

````
jQuery(document).ready(function(){    alert("Hello World");});
````

As you could see, Jsoup is formatting javascript in one line. For that example is not a problem... but If I have a long javascript code I'm getting only one line of code.. that's really difficult to read, debug, etc..

On the other hand, If I use `Parser.htmlParser()` empty elements  (links elements, meta elements, etc.) are generated without end tags. That's a problem if we combine JSOUP with some other technology like `THYMELEAF` that use an XML parser to read the document. 

````
org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 84; "meta" element must end with "</meta>" tag.
````

https://github.com/thymeleaf/thymeleaf/issues/160

Maybe, there are at least two possible solutions (maybe you know some better one):

* Include some configuration to use `Parser.xmlParser()` maintaining the javascript format.
* Include some parameter in `Jsoup.parse()` to specify if end tags should be included

What do you think?

Regards,

**NOTE**: We are including Jsoup project as HTML parser of the[ Spring Roo](https://github.com/spring-projects/spring-roo) project

**Comment by jcagarcia** [comment]
Hi again  @jhy 

I've just updated Spring Roo to generate applications including Thymeleaf 3.0 dependency instead of Thymeleaf dependency provided by Spring IO Platform.

https://jira.spring.io/browse/ROO-3813

Seems that it works fine using `Parser.htmlParser()` :)

Anyway, maybe you are interested on include some of the proposals I made above to be able to use previous `THYMELEAF` versions or some other technologies that doesn't support HTML5 format.

Best regards and thanks for your time and your support.

**Comment by jhy** [comment]
Hi,

Glad that you were able to find a solution. Another approach would be to disable Pretty Printing, which will preserve the line breaks of text nodes.

See for example https://try.jsoup.org/~GGpijxWoJe9-gFGibbnIRfdYxlI

**Comment by jcagarcia** [comment]
I've just tried your proposal and works fine for me.

````
  @Override
  public Document parse(String content) {
    Document doc = Jsoup.parse(content, "", Parser.xmlParser());
    doc.outputSettings().prettyPrint(false);
    return doc;
  }
````

Thanks for your support @jhy
