### ISSUE TITLE
self closing tag br

### ISSUE THREAD

**Issue by maverick42** [jhy/jsoup#775]
Hi,

I use jsoup to cleanup html text from froala javascript editor (to generate PDF with xmlworker)
In this editor when I make a new line (shift+enter) I have the following code :

`<p>paragraph1</p><p>paragraph2</p><p>line1<br>line2<br>line3</p>`

With jsoup xml parser I get :

`<p>paragraph1</p><p>paragraph2</p><p>line1<br>line2<br>line3</br></br></p>`

But I would like ... :

`<p>paragraph1</p><p>paragraph2</p><p>line1<br/>line2<br/>line3</p>`

There is an option to obtain this "clean" xml code ?

Bests 
Frédérik

**Comment by jhy** [comment]
No, because in HTML5, self closing tags don't need that trailing `/`. `<br>`, `<img>` etc is the correct form.
