### ISSUE TITLE
Quit Removing Tags 

### ISSUE THREAD

**Issue by asevans48** [jhy/jsoup#777]
JSoup is removing 'broken' tags. Try downloading this page http://business.nh.gov/nsor/. The table is completely removed when it should not be. In fact, the entire table in the center of the page is removed. This is definitely a major bug.

Some basic parsing can discover if certain tags have matching endpoints. The large problem appears to be for inputs, images, and other tags which can be self closing but are left unclosed. Such tags should be considered as closed if there is no matching end tag or end pattern "/>". Looking at previous and nested tags can discover other endpoints as well.

**Comment by asevans48** [comment]
In fact, I have code from a few years back that can kick off the process. I will post it to my github in a bit. https://github.com/asevans48. It may be confusing because it was written when my boss had a grand vision of ETLing HTML purely in Pentaho. Call the non-empty constructor (left-overs from a CS class professor telling everyone to always have an empty constructor which now that I think of it is a bad idea in this case) and then call getStringRep().

**Comment by jhy** [comment]
Hi - I'm not clear about the bug you're reporting. Can you please provide an executable failing test case, with input, expects, and the actuals?

I ran that URL and the parse tree looks fine - e.g. https://try.jsoup.org/~4cM4Ar0tL8VTZwxZcRda9U0Aoa0 - not sure which table you're referring to but the form search tables are there.

And I'm not clear on your points around empty tags that don't have closing tags. That's well supported, as is auto closing tags based on context. See e.g. https://try.jsoup.org/~mjwd9N1yWsbCWRKRYERXtjne29Y

Thanks!

**Comment by asevans48** [comment]
That is bizarre. I had to use JTidy to completely get the result. The siblings of the following and the table were being stripped out. 

    <input name="ctl00$cphMain$txtZip" type="text" id="cphMain_txtZip" AlternateText="zip" style="border:1;width:15;" />

My system without JTidy:
Apache Http Components
Java/Scala
Linux Ubuntu Xenial 16.04
User-Agent : Mozilla

**Comment by jhy** [comment]
OK, glad you found a solution to your problem.
