### ISSUE TITLE
InvocationTargetException when run

### ISSUE THREAD

**Issue by steveyushan** [jhy/jsoup#780]
Hi, When I run as Android Application under eclipse using Jsoup 1.10.1 jar, I met a exception. When I run the same code under eclipse as java application, everything goes fine. Here is the code below and stack .
String url = "https://test.glucoguide.com/GlucoGuide/foods/search?key=apple";
Document doc= Jsoup.connect(url).get();

10-26 12:08:04.140: W/System.err(22542): android.os.NetworkOnMainThreadException
10-26 12:08:04.150: W/System.err(22542): at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1148)
10-26 12:08:04.160: W/System.err(22542): at java.net.InetAddress.lookupHostByName(InetAddress.java:443)
10-26 12:08:04.160: W/System.err(22542): at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
10-26 12:08:04.160: W/System.err(22542): at java.net.InetAddress.getAllByName(InetAddress.java:214)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
10-26 12:08:04.160: W/System.err(22542): at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
10-26 12:08:04.170: W/System.err(22542): at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
10-26 12:08:04.170: W/System.err(22542): at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:571)
10-26 12:08:04.170: W/System.err(22542): at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:548)
10-26 12:08:04.170: W/System.err(22542): at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:235)
10-26 12:08:04.170: W/System.err(22542): at org.jsoup.helper.HttpConnection.get(HttpConnection.java:224)
10-26 12:08:04.170: W/System.err(22542): at com.steve.utils.FileUtils.foodMatch(FileUtils.java:228)
10-26 12:08:04.170: W/System.err(22542): at com.steve.foodtest.MainActivity.onCreate(MainActivity.java:19)
10-26 12:08:04.170: W/System.err(22542): at android.app.Activity.performCreate(Activity.java:5304)
10-26 12:08:04.170: W/System.err(22542): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
10-26 12:08:04.170: W/System.err(22542): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
10-26 12:08:04.170: W/System.err(22542): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331)
10-26 12:08:04.170: W/System.err(22542): at android.app.ActivityThread.access$1000(ActivityThread.java:143)
10-26 12:08:04.170: W/System.err(22542): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
10-26 12:08:04.170: W/System.err(22542): at android.os.Handler.dispatchMessage(Handler.java:102)
10-26 12:08:04.170: W/System.err(22542): at android.os.Looper.loop(Looper.java:136)
10-26 12:08:04.180: W/System.err(22542): at android.app.ActivityThread.main(ActivityThread.java:5291)
10-26 12:08:04.180: W/System.err(22542): at java.lang.reflect.Method.invokeNative(Native Method)
10-26 12:08:04.180: W/System.err(22542): at java.lang.reflect.Method.invoke(Method.java:515)
10-26 12:08:04.180: W/System.err(22542): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
10-26 12:08:04.180: W/System.err(22542): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
10-26 12:08:04.180: W/System.err(22542): at dalvik.system.NativeStart.main(Native Method)

**Comment by steveyushan** [comment]
Hi, When I run as Android Application under eclipse using Jsoup 1.10.1 jar, I met a exception. When I run the same code under eclipse as java application, everything goes fine. Here is the code below  and stack .
String url = "https://test.glucoguide.com/GlucoGuide/foods/search?key=apple";
Document doc= Jsoup.connect(url).get();


10-26 12:08:04.140: W/System.err(22542): android.os.NetworkOnMainThreadException
10-26 12:08:04.150: W/System.err(22542): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1148)
10-26 12:08:04.160: W/System.err(22542): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:443)
10-26 12:08:04.160: W/System.err(22542): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:294)
10-26 12:08:04.160: W/System.err(22542): 	at java.net.InetAddress.getAllByName(InetAddress.java:214)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
10-26 12:08:04.160: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
10-26 12:08:04.170: W/System.err(22542): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
10-26 12:08:04.170: W/System.err(22542): 	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:571)
10-26 12:08:04.170: W/System.err(22542): 	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:548)
10-26 12:08:04.170: W/System.err(22542): 	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:235)
10-26 12:08:04.170: W/System.err(22542): 	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:224)
10-26 12:08:04.170: W/System.err(22542): 	at com.steve.utils.FileUtils.foodMatch(FileUtils.java:228)
10-26 12:08:04.170: W/System.err(22542): 	at com.steve.foodtest.MainActivity.onCreate(MainActivity.java:19)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.Activity.performCreate(Activity.java:5304)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.ActivityThread.access$1000(ActivityThread.java:143)
10-26 12:08:04.170: W/System.err(22542): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
10-26 12:08:04.170: W/System.err(22542): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-26 12:08:04.170: W/System.err(22542): 	at android.os.Looper.loop(Looper.java:136)
10-26 12:08:04.180: W/System.err(22542): 	at android.app.ActivityThread.main(ActivityThread.java:5291)
10-26 12:08:04.180: W/System.err(22542): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-26 12:08:04.180: W/System.err(22542): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-26 12:08:04.180: W/System.err(22542): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
10-26 12:08:04.180: W/System.err(22542): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
10-26 12:08:04.180: W/System.err(22542): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jhy** [comment]
This is because Android doesn't let you make URL connections on the main thread. Otherwise your UI will block on network access.

See http://stackoverflow.com/questions/6976317/android-http-connection-exception/6986726#6986726

This isn't a jsoup thing particularly.

Also I'd highly recommend using Android Studio or IntelliJ for Android development as it will give you a warning as to what's wrong and how to fix it (use an AsyncTask or one of the helper wrappers, to get it off the main thread) as you type.

**Comment by steveyushan** [comment]
Thank you. I will move the code to thread and see if it works.
