### ISSUE TITLE
Weird result when try to parse naked table

### ISSUE THREAD

**Issue by fenghaolw** [jhy/jsoup#781]
When I tried to parse the following string
`<tr><td>Foo:</td><td>Bar:<br />XXX<br />XXX<br /></td></tr>`

It became
`<head></head>
 <body>
  Foo:Bar:
  <br>XXX
  <br>XXX
  <br>
 </body>`

I thought it should add a table tag based on the documentation. I tried both Jsoup.parse and Jsoup.parseBodyFragment

**Comment by jhy** [comment]
jsoup used to do that years ago, but when I moved it to the HTML5 spec that behaviour changed, so that it's in-line with what browsers do.
