### ISSUE TITLE
removeAttr with empty attribute syntax throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by frederic-klein** [jhy/jsoup#785]
It seems there is a bug when `removeAttr` is called for an attribute with **empty attribute syntax** like `checked` for version 1.10.1

**Example**

	String htmlString = " <input type=\"radio\" id=\"edit-rid-1\" name=\"rid\" value=\"1\" checked=\"checked\" class=\"form-radio\" />";
	
	Element element = Jsoup.parse(htmlString).getElementById("edit-rid-1");

	System.out.println(element.toString());
	System.out.println(element.hasAttr("checked"));
	element.removeAttr("checked");
	System.out.println(element.toString());

Output with **jsoup 1.9.1**

    <input type="radio" id="edit-rid-1" name="rid" value="1" checked class="form-radio">
    true
    <input type="radio" id="edit-rid-1" name="rid" value="1" class="form-radio">

Output with **jsoup 1.10.1**

    <input type="radio" id="edit-rid-1" name="rid" value="1" checked class="form-radio">
    true
    Exception in thread "main"
    java.util.ConcurrentModificationException
	    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	    at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	    at org.jsoup.nodes.Attributes.removeIgnoreCase(Attributes.java:122)
	    at org.jsoup.nodes.Node.removeAttr(Node.java:128)
	    at Webscraping.JsoupExamples.localByID(JsoupExamples.java:603)
	    at Tester.App.main(App.java:119)

So `element.removeAttr("checked");` causes the exception.

**Comment by jhy** [comment]
Hi, thanks for the report. This is the same as #759 which is fixed in on HEAD.
