### ISSUE TITLE
it I can send  request post multipart/form-data without attachment of the file

### ISSUE THREAD

**Issue by Bsplesk** [jhy/jsoup#788]
It I can send  request post multipart/form-data **without attachment of the file** :(

example curl: `curl --form "XXX=YYY" --form "MMM=" --form "SSS=" ...... https://XX.XX.XX.XX/upload`
it is impossible too, most to send jsoap.

[stackoverflow.com](http://stackoverflow.com/questions/40620308/how-to-force-jsoup-to-send-multipart-data?noredirect=1&lq=1)

**Comment by vcoder4c** [comment]
Hi @Bsplesk , did you find the solution for this case? I am trying to do the same thing, but the only solution I can do is custom the header and build the body by myself as multipart/form-data. 

@all: This request have been created for a while, is there any reaction for this?

**Comment by Bsplesk** [comment]
Hi @vcoder4c, It is good that you have opened all your solution.
It will help all who will face this problem.
This problem(and others problem) was solved in 2016, similarly by modifying the source code (unfortunately the source code is not save).
Try to adding your patch to the release (at me it hasn't turned out).
good luck :).
