### ISSUE TITLE
nextElementSibling method error

### ISSUE THREAD

**Issue by yangyuhui** [jhy/jsoup#789]
&lt;tr&gt;<br />    &lt;td&gt;本车车损&lt;/td&gt;<br />    &lt;td&gt;前杠喷漆&lt;/td&gt;<br />    &lt;td&gt;0.00&lt;/td&gt;<br />&lt;/tr&gt;<br />&lt;tr&gt;<br />    &lt;td&gt;本车车损&lt;/td&gt;<br />    &lt;td&gt;右前叶子板钣金喷漆&lt;/td&gt;<br />    &lt;td&gt;0.00&lt;/td&gt;<br />&lt;/tr&gt;<br />&lt;tr&gt;<br />    &lt;td&gt;本车车损&lt;/td&gt;<br />    &lt;td&gt;机盖钣金喷漆&lt;/td&gt;<br />    &lt;td&gt;0.00&lt;/td&gt;<br />&lt;/tr&gt;<br />&lt;tr&gt;<br />    &lt;td&gt;本车车损&lt;/td&gt;<br />    &lt;td&gt;水箱框架钣金喷漆&lt;/td&gt;<br />    &lt;td&gt;0.00&lt;/td&gt;<br />&lt;/tr&gt;<br />&lt;tr&gt;<br />    &lt;td&gt;本车车损&lt;/td&gt;<br />    &lt;td&gt;前杠喷漆&lt;/td&gt;<br />    &lt;td&gt;0.00&lt;/td&gt;<br />&lt;/tr&gt;

I use nextElementSibling()  order this Document. But the first <tr> and the five have same content ,So have an dead circulation error.

**Comment by jhy** [comment]
Can you add an example test case please? And which version are you using?

**Comment by jhy** [comment]
Closing, please feel free to reopen if you get it on the current version and have a testcase.
