### ISSUE TITLE
html inside html

### ISSUE THREAD

**Issue by Miglecz** [jhy/jsoup#790]
Lib is unable to select the 2 html tags in the following invalid source, what could be a valid "something" else more uniform:
```
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <title>title1</title>
</head>
<body></body>
</html>

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>title2</title>
</head>
<body></body>
</html>

```

**Comment by krystiangor** [comment]
If you know your input is not a valid HTML, you can parse it anyway using general XML parser.
```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;

public class JsoupIssue790 {
	public static void main(String[] args) {
		String html = "<!DOCTYPE html> <html lang=\"nl\"> <head> <meta charset=\"UTF-8\"> <title>title1</title> </head> <body></body> </html> <html lang=\"fr\"> <head> <meta charset=\"UTF-8\"> <title>title2</title> </head> <body></body> </html>";
		Document doc = Jsoup.parse(html, "", Parser.xmlParser());
		System.out.println(doc.select("html").size());
	}
}
```
output: 2

**Comment by jhy** [comment]
Yes, like @krystiangor said. If you're using the HTML parser, you're getting a HTML DOM and that means not having two `<html>` sections.

Like it says on the homepage:
jsoup implements the WHATWG HTML5 specification, and parses HTML to the same DOM as modern browsers do.
