### ISSUE TITLE
Jsoup.clean control characters throws: IllegalArgumentException: String must not be empty

### ISSUE THREAD

**Issue by micrk** [jhy/jsoup#793]
I found that when running Jsoup.clean() on a string that contains the format below, Jsoup throws: `IllegalArgumentException: String must not be empty`.
The problematic string format:
`'<a/*>'`, (where * is a control char).
i.e. `<` char followed by a letter (a-z), then any chars, `/` and any control char (ASCII 0-31) except 0, 9-10, 12-13, any chars, and a `>` char.

**Comment by jhy** [comment]
Fixed, thanks!
