### ISSUE TITLE
 In HTML parser, if a namespaced tag is in head section, moves to body section

### ISSUE THREAD

**Issue by JeryZeng** [jhy/jsoup#795]
I have a html input witch mixed by some custom tag:

```
<!DOCTYPE html>
<html xmlns:cms="http://cms">
<head lang="en">
    <meta charset="UTF-8">
	<cms:field name="web_title" display="LP" required="true" type="String"></cms:field>
    <cms:field name="description" display="LP" type="String"></cms:field>
    <cms:field name="keywords" display="LP" type="String"></cms:field>
    <cms:field name="copyRight" display="" type="String"></cms:field>
    <cms:field name="ga" display="" type="String" texttype="textarea"></cms:field>
    <cms:field name="gtm" display="" type="String" texttype="textarea"></cms:field>
    <title></title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="../res/src/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="../res/src/css/swiper-3.3.1.min.css"/>
    <link rel="stylesheet" type="text/css" href="../res/src/css/animate.min.css"/>
    <link rel="stylesheet" type="text/css" href="../res/src/css/main.css"/>
</head>
<body>
<div class="swiper-container">
    <div class="swiper-wrapper">
```
...........

And parsed by jsoup then i get a result below:
```
<!doctype html>
<html xmlns:cms="http://cms">
 <head lang="en"> 
  <meta charset="UTF-8"> 
 </head> 
 <body> 
  <cms:field name="web_title" display="" required="true" type="String"></cms:field> 
  <cms:field name="description" display="" type="String"></cms:field> 
  <cms:field name="keywords" display="" type="String"></cms:field> 
  <cms:field name="copyRight" display="" type="String"></cms:field> 
  <cms:field name="ga" display="" type="String" texttype="textarea"></cms:field> 
  <cms:field name="gtm" display="" type="String" texttype="textarea"></cms:field> 
  <title></title> 
  <meta name="keywords" content="" > 
  <meta name="description" content=""> 
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> 
  <link rel="stylesheet" type="text/css" href="../res/src/css/bootstrap.min.css"> 
  <link rel="stylesheet" type="text/css" href="../res/src/css/swiper-3.3.1.min.css"> 
  <link rel="stylesheet" type="text/css" href="../res/src/css/animate.min.css"> 
  <link rel="stylesheet" type="text/css" href="../res/src/css/main.css"> 
  <div class="swiper-container"> 
   <div class="swiper-wrapper"> 
```

the content in `head` tag moved into `body`?

I think it is not a good way to handle this situation

**Comment by krystiangor** [comment]
Can you post some example code?

**Comment by JeryZeng** [comment]
I have a html input witch mixed by some custom tag:
&lt;!DOCTYPE html&gt;
&lt;html xmlns:cms="http://cms"&gt;
&lt;head lang="en"&gt;
    &lt;meta charset="UTF-8"&gt;
	&lt;cms:field name="web_title" display="LP" required="true" type="String"&gt;&lt;/cms:field&gt;
    &lt;cms:field name="description" display="LP" type="String"&gt;&lt;/cms:field&gt;
    &lt;cms:field name="keywords" display="LP" type="String"&gt;&lt;/cms:field&gt;
    &lt;cms:field name="copyRight" display="" type="String"&gt;&lt;/cms:field&gt;
    &lt;cms:field name="ga" display="" type="String" texttype="textarea"&gt;&lt;/cms:field&gt;
    &lt;cms:field name="gtm" display="" type="String" texttype="textarea"&gt;&lt;/cms:field&gt;
    &lt;title&gt;&lt;/title&gt;
    &lt;meta name="keywords" content=""&gt;
    &lt;meta name="description" content=""&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"&gt;
    &lt;link rel="stylesheet" type="text/css" href="../res/src/css/bootstrap.min.css"/&gt;
    &lt;link rel="stylesheet" type="text/css" href="../res/src/css/swiper-3.3.1.min.css"/&gt;
    &lt;link rel="stylesheet" type="text/css" href="../res/src/css/animate.min.css"/&gt;
    &lt;link rel="stylesheet" type="text/css" href="../res/src/css/main.css"/&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div class="swiper-container"&gt;
    &lt;div class="swiper-wrapper"&gt;
...........

And parsed by jsoup then i get a result below:
&lt;!doctype html&gt;
&lt;html xmlns:cms="http://cms"&gt;
 &lt;head lang="en"&gt; 
  &lt;meta charset="UTF-8"&gt; 
 &lt;/head&gt; 
 &lt;body&gt; 
  &lt;cms:field name="web_title" display="" required="true" type="String"&gt;&lt;/cms:field&gt; 
  &lt;cms:field name="description" display="" type="String"&gt;&lt;/cms:field&gt; 
  &lt;cms:field name="keywords" display="" type="String"&gt;&lt;/cms:field&gt; 
  &lt;cms:field name="copyRight" display="" type="String"&gt;&lt;/cms:field&gt; 
  &lt;cms:field name="ga" display="" type="String" texttype="textarea"&gt;&lt;/cms:field&gt; 
  &lt;cms:field name="gtm" display="" type="String" texttype="textarea"&gt;&lt;/cms:field&gt; 
  &lt;title&gt;&lt;/title&gt; 
  &lt;meta name="keywords" content="" &gt; 
  &lt;meta name="description" content=""&gt; 
  &lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"&gt; 
  &lt;link rel="stylesheet" type="text/css" href="../res/src/css/bootstrap.min.css"&gt; 
  &lt;link rel="stylesheet" type="text/css" href="../res/src/css/swiper-3.3.1.min.css"&gt; 
  &lt;link rel="stylesheet" type="text/css" href="../res/src/css/animate.min.css"&gt; 
  &lt;link rel="stylesheet" type="text/css" href="../res/src/css/main.css"&gt; 
  &lt;div class="swiper-container"&gt; 
   &lt;div class="swiper-wrapper"&gt; 


the content in `head` tag moved into `body`?

I think it is not a good way to handle this situation

**Comment by JeryZeng** [comment]
sorry ,github doesn't show my description corretly.I escape all html tag and post agian,check it out please

**Comment by jhy** [comment]
Works per the spec and current browsers, but I agree it probably makes sense to leave unknown tags in whatever section they first present in.

You could use the XML parser if you don't want HTML normalization happening at all.

**Comment by JeryZeng** [comment]
i have use the XML parser,but itdoesn't work too

**Comment by jhy** [comment]
It looks like it does to me: https://try.jsoup.org/~qwq161GCfaD2QMRKiI5Pq1eSolc - note XML parser is enabled. Can you review?

**Comment by jkytomaki** [comment]
Hi, having a problem with this too. Any unknown tag in `head` section moves the unknown tag and all it's following siblings to inside `body`. So

`<html>
<head>
  <unknown-tag>Hello</unknown-tag>
  <title>test-title</title>
</head>
<body>
</body>`

becomes

`<html lang="en">
<head>
</head>
<body>
  <unknown-tag>Hello</unknown-tag>
  <title>Title</title>
</body>`

I would like to use HTML normalization, but also to be able to parse tags inside `head` even if there are preceding unknown tags. Loading my example above with chrome parses the title of the page to be "test-title", so its behavior may be different to jsoup?

**Comment by jhy** [comment]
I had another look at this. My current thinking is that it's better to go with the spec / what other browsers are doing. If we allow the unknown tags to stay in the head, but other browsers don't, then the normalization isn't working, and people will get unexpected / unrepeatable results.

**Comment by jkytomaki** [comment]
> If we allow the unknown tags to stay in the head, but other browsers don't, then the normalization isn't working, and people will get unexpected / unrepeatable results.

But my comment above had an example of Chrome allowing the tag to stay in head, but JSoup not. I feel the current behaviour of JSoup is unexpected for the user.

**Comment by jkytomaki** [comment]
I tested my previous example with unknown tag in head with Firefox, and the title gets correctly parsed with it as well. I'd say that browsers in general are currently handling the situation differently. Is there a case where browsers handle it the same way as JSoup, as you mention?

We have encountered multiple non-related sites where site owners have added custom tags to their head sections, breaking the parsing of other head tags with JSoup for that site. The current work-around we are using is searching for the same tags from the body of the document as well, but that is not optimal. I would love it if the default behaviour would be to continue parsing head even after encountering unknown tags, like other browsers seem to be doing, or at least allow it with some setting.

**Comment by jhy** [comment]
Can you give me an example file / URL? I made a few examples and tested (in Chrome but can review Firefox also) and they worked the way jsoup is and the spec is, afaict. The first non-head tag causes it to move to body insertion mode.

**Comment by jkytomaki** [comment]
Never mind, you are right. I was just looking at whether Chrome applies a title or a link CSS tag following an unknown tag - which it is - not whether it is moving them to body - which it also is. So Chrome works the same way as JSoup currently, it just (of course) accepts a title or a link CSS tag both in head or in the body.

I still feel a bit unhappy about the way this works, as I've found non-standard head elements to be quite common, and now one needs to look for any head element in the entire document, but maybe you're right that it's best to work in line with browsers. :man_shrugging: 

Thanks for your help.

**Comment by dustinlineweber** [comment]
Very strict AMP is one reason someone may wish this (at least optionally) worked.  See https://validator.ampproject.org/#htmlFormat=AMP4EMAIL

```
<!--
     This is the minimum valid AMP4EMAIL document. Type away
     here and the AMP Validator will re-check your document on the fly.
-->
<!doctype html>
<html ⚡4email data-css-strict>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
</head>
<body>
  Hello, AMP4EMAIL world.
</body>
</html>

```
