### ISSUE TITLE
ConcurrentModificationException when removing attributes

### ISSUE THREAD

**Issue by dflorey** [jhy/jsoup#799]
First of all: Thanks for the great Jsoup!
When removing the style attribute from a bunch of elements I'm getting this exception:

```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
	at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
	at org.jsoup.nodes.Attributes.removeIgnoreCase(Attributes.java:122)
	at org.jsoup.nodes.Node.removeAttr(Node.java:128)
```
As a note: This error started after upgrading to the latest release from 1.7.x
This is my code that produces the error:
```
Elements clearStyles = selectedElement.select("h1,h2,h3,h4,h5,ol,ul:not(.nav),li:not(.active),a,table,tr,tbody,strong,code,em,u,mark");
for (Element clearStyle : clearStyles) {
	clearStyle.removeAttr("style");
}
```

**Comment by dflorey** [comment]
As a note: This error started after upgrading to the latest release from 1.7.x

**Comment by dflorey** [comment]
Seems to be already fixed in the master branch. Compiling from the sources fixed the issue for me.

**Comment by mahmooddagga** [comment]
@dflorey how do you compile from source code , do you make library project ?

**Comment by jhy** [comment]
Download the source and run `mvn jar`

Should have a new release coming out soon though.

**Comment by naco-siren** [comment]
Same problem even with the newest version
