### ISSUE TITLE
":has" pseudo selector does not work correctly with direct childs

### ISSUE THREAD

**Issue by celyo** [jhy/jsoup#804]
Hi,

There is a problem with Element.select(String cssQuery) method. This method does not handle ":has" pseudo selector as expected (in case of direct child syntax in the passed selector). 

Here is the example:

I'm passing following document body:
```html
<p>Just another text 1</p>
<table>
<tbody>
<tr>
<td>Simple table</td>
</tr>
<tr>
<td>
<table>
<tbody>
<tr>
<td>Target nested table</td>
</tr>
<tr>
<td>
<div class="test">The target selectable tag</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>Just another text 2</p>
```

When I execute document.select("table:has(> tbody > tr > td > div.test)"), I expect the nested table to be the only element in the result but the result is empty. jQuery works exactly as I expected but Jsoup not.

P.S. I've tried with try.jsoup.org and with java code - both have similar behavior.

**Comment by lizhaohui836** [comment]
I guess it may be grammatical, I tried to execute table:has(tbody > tr > td > div.test with try.jsoup.org and the result is right.

**Comment by celyo** [comment]
No, the result is not right, because when your selector is used, both tables are returned, but I want only nested table to be returned. That's why I've used leading ">", because I wanted direct child relationship.

This is the example with jQuery that works fine:
```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("table:has(> tbody > tr > td > div.test)").css("border", "solid red");
});
</script>
</head>
<body>

<p>Just another text 1</p>
<table>
<tbody>
<tr>
<td>Simple table</td>
</tr>
<tr>
<td>
<table>
<tbody>
<tr>
<td>Target nested table</td>
</tr>
<tr>
<td>
<div class="test">The target selectable tag</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>Just another text 2</p>
</body>
</html>
```

**Comment by Shredder121** [comment]
I see the same, using leading 'general sibling' and 'direct sibling' characters.
Are we sure that [the context isn't inclusive](https://github.com/jhy/jsoup/blob/f28c024ba127fd701f0d195a359afbabff04d7a1/src/main/java/org/jsoup/select/StructuralEvaluator.java#L128) to the match?

As said, jQuery does include the context in the match using that, and using the built in `$` selector of chrome does the same. (`$('selector', context)`).

**Comment by Shredder121** [comment]
```java
@Test
public void testLeadingCombinatorIncludingContext() {
	// the context element isn't regarded as the child
	Document doc = Jsoup.parse("<h1>This will be used as context</h1><p>This should be selected</p>");
	Elements context = doc.select("h1");
	Elements paragraph = context.select("~p");
	assertEquals(1, paragraph.size());
}
```

**Comment by jhy** [comment]
I fixed this along the line somewhere - see e.g. https://try.jsoup.org/~ZOmTdFSrkFrIfrKBNBgAzuFhM1M
