### ISSUE TITLE
Jsoup out of memory

### ISSUE THREAD

**Issue by amit2103** [jhy/jsoup#806]
Hey I am getting an out of memory with Jsoup. I use document = Jsoup.parse(pageURL, 5000); to get a document. However after the code runs for sometime I see an out of memory and a instance of HtmlTreeBuilder which occupies 58% of the Java heap. Do you guys have any idea why this is happening?

**Comment by offa** [comment]
> Do you guys have any idea why this is happening?

Have you checked how big the actual website is?

**Comment by amit2103** [comment]
My initial assumption was that Jsoup will stop to load data once 1MB is
reached. Isnt it so?

**Comment by offa** [comment]
It will load and parse the data you feed in.

Btw. in your example you use `parse()` for an URL. If you want to load a website, better use [connect()](https://jsoup.org/cookbook/input/load-document-from-url)

**Comment by jhy** [comment]
Jsoup has a default limit in connect on loading 1MB of data. That's not the same as how much memory that uses though - there's the whole DOM tree construction with plenty of Java objects, and some temporary copies of the input, etc, that all use memory. Additionally you may be holding onto other used connections and documents or parsers that are limiting the available memory, or there may be too much work happening in parrallel.

We can help you debug better if you provide an actual code test that reproduces the issue, and notes on your environment (jvm, architecture, memory config, and the URL / HTML you're passing). A memory dump would be useful too.

I've had good luck diagnosing memory issues with Yourkit on Java platforms, or Android Studio if on Android (but much more limited).

**Comment by amit2103** [comment]
I found the problem with yourkit. 
To give  you more details, we have a rest resource which can send us some url (any), we parse it and create a preview for it. For this we use Jsoup. Now it may so happen that multiple threads might call Jsoup at the same time via multiple threads and there might be some parallel processing. 

I am not sure which URL was exactly passed but from the JVM dump it appears it was :- a DropBox url which now has nothing (may be data removed).  My JVM is 4GB of heap and is basically a DropWizard Rest server. There seems to be a single HtmlTreeBuilder with that amount of data :- 

Here is the info :- 

HtmlTreeBuilder 1 72 1262466680

How can I avoid this situation , clients passing in a website which crashes the JVM due to a very rich dom structure?

**Comment by jhy** [comment]
What are those columns? What units?

What objects are you retaining?

Can you capture the memory snapshot and object allocation snapshot?

It would be good if you could give the code snippet to see how you're configuring the connection. Can you confirm what input size limit you have and how you're implementing that? (Actual code would be helpful.)

As to prevention - a OOM isn't a JVM crash, it's just an exception. If I were building this, I'd be inclined to put metrics and limits on the number of active threads and tp90 & tp99 measurement of latency and size, and capture anything that exceeded expected bounds for further diagnosis. Would also put an exception handler in to catch OOMs on the parse thread, and do a full memory dump (for diagnosis), and simple recovery (your inflight and next requests would presumably still succeed).

**Comment by amit2103** [comment]
This is how I parse :-1: 
private OembedResponse parseForOembedMetadata() throws IOException, URISyntaxException, OembedException {
        OembedProvider rv = null;
        Iterator oe = this.document.getElementsByAttributeValue("rel", "alternate").iterator();

        while(oe.hasNext()) {
            Element alternate = (Element)oe.next();
            if(alternate.attr("type").equalsIgnoreCase("application/json+oembed")) {
                rv = getOembedProvider(alternate.absUrl("href"), "json");
            } else if(alternate.attr("type").equalsIgnoreCase("text/xml+oembed")) {
                rv = getOembedProvider(alternate.absUrl("href"), "xml");
            }
        }

        if(rv == null) {
            return new OembedResponse();
        } else {
            Oembed oe1 = (new OembedBuilder(HttpClientBuilder.create().build())).withProviders(new OembedProvider[]{rv}).withCacheManager(cacheManager).withCacheName(OEMBED_CACHE_NAME).withCacheManager(CacheManager.create()).withDefaultCacheAge(86400).build();
            return oe1.transformUrl(this.sourceUrl.toString());
        }
    }

**Comment by amit2103** [comment]
I am also attaching the data for HtmlTreeBuilder exported from Yourkit
[Object-explorer.xlsx](https://github.com/jhy/jsoup/files/691903/Object-explorer.xlsx)
[Objects-by-class.xlsx](https://github.com/jhy/jsoup/files/691904/Objects-by-class.xlsx)

**Comment by jhy** [comment]
You never told me you were trying to parse a 50 MB Photoshop file! That's why it blew up. PSDs have `<` chars which make a really bad parse tree if you try to parse them as HTML.

There are guards in Jsoup.Connect that protect against this. There is a MIME file type check, and a default maximum stream read.

Are you really sure you are using `Jsoup.parse(url, timeout)` to fetch the content? From the above you are using HttpClientBuilder which is part of Apache Http client. If you're using that then you're not using Jsoup to fetch it.

My suggestion is to implement as I described above, and either actually use Jsoup.Connect with the safe defaults, or implement other appropriate safeguards so you don't try to parse Photoshop / other non-HTML files, and protects you if you do.

**Comment by jhy** [comment]
`baseUri  java.lang.String [Stack Local]  "https://dl.dropboxusercontent.com/u/{cut}/{cut}.psd"`

`tokeniser  org.jsoup.parser.Tokeniser [Stack Local]	 49,372,128 `
50 MB PSD.

**Comment by amit2103** [comment]
Yea, that link was not available and I shame on me for not knowing that .psd is photoshop. But I am pretty sure I use the Jsoup.connect(uri, tieout), let em check if there is some other handling in case of exceptions.
I thought the Jsoup.connect(uri, timeout), will throw exceptions in these case, and so there might be some other way code in exception handling to do it, so  let me check.

**Comment by amit2103** [comment]
@jhy  There is code like this :- catch (UnsupportedMimeTypeException var6) {
                document = Jsoup.parse(siteConnection.getInputStream(), charset, pageURL.toString());
            }

Is there any way to safely create document for this kind of file where we get an UnsupportedMimeTypeException ? Or should we skip it altogether?

**Comment by jhy** [comment]
You took the safety off the gun and shot yourself in the foot...

If you want to ignore the content type, you can use the method [ignoreContentType()](https://jsoup.org/apidocs/org/jsoup/Connection.html#ignoreContentType-boolean-)

You would still get the default max input stream of 1MB so you might not run out of memory when parsing (but you still could depending on what you're trying to parse). The intent of ignoreContentType is if you **really** know the content is HTML but the server is sending the incorrect response. Here, clearly, you have no idea what the input type is so I would absolutely recommend against using this option or catching the exception and force parsing it like you are.

My recommendation would be to use the stock defaults of jsoup, and implement the safe guards that I described earlier.
