### ISSUE TITLE
HTMLElement interfaces

### ISSUE THREAD

**Issue by mfulton26** [jhy/jsoup#810]
Can additional classes/interfaces be added and used than simply `Element` and `FormElement`? e.g. I'd like to be able to traverse through the tree and switch off of whether elements are an `HTMLHeadingElement`, `HTMLSelectElement`, `HTMLOutputElement`, etc., etc. Each of those interfaces would then expose logic for querying the selectedIndex, value, and other things specific to that type of element.

**Comment by jhy** [comment]
Um that sounds not really like what I want from jsoup... what would the different classes do? What useful methods does an HTMLHeadingElement have that a HTMLDivElement not? The w3c DOM classes are not to my taste and I believe jsoup owes some of its usefulness to the relative simplicity of its model.

I'd suggest just switching on the tag name.

**Comment by mfulton26** [comment]
Yeah, that is fine. An HTMLSelect would probably be the most useful for querying options, groups, selections, etc. but I see your point. Thanks.

**Comment by jhy** [comment]
Select makes sense for a custom impl of form values.

**Comment by jhy** [comment]
(Will close this as a bit aged, but can revisit select tags or others if we get interest and a clear utility.)
