### ISSUE TITLE
No breaks after blocks

### ISSUE THREAD

**Issue by ValleZ** [jhy/jsoup#812]
Document document = Jsoup.parse("<html><body><div>block</div>tail</body></html>");
        assertEquals("block tail", document.body().text());
gives
        `AssertionFailedError: expected: <block tail> but was: <blocktail>`

**Comment by blasd** [comment]
+1

**Comment by jhy** [comment]
Thanks! Implemented with f9307ec96a894191e5d3782601ddb49fbfc53ea6
