### ISSUE TITLE
NullPointerException in Entities.java - codepointFromName()

### ISSUE THREAD

**Issue by gregko** [jhy/jsoup#818]
Got the following stack trace form a user of my app, using JSoup 1.10.3 snapshot:

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference
       at java.util.Arrays.binarySearch(Arrays.java:524)
       at java.util.Arrays.binarySearch(Arrays.java:494)
       at org.jsoup.nodes.Entities$EscapeMode.codepointForName(SourceFile:57)
       at org.jsoup.nodes.Entities.codepointsForName(SourceFile:137)
       at org.jsoup.parser.Tokeniser.consumeCharacterReference(SourceFile:187)
       at org.jsoup.parser.TokeniserState$38.read(SourceFile:742)
       at org.jsoup.parser.Tokeniser.read(SourceFile:50)
       at org.jsoup.parser.TreeBuilder.runParser(SourceFile:49)
       at org.jsoup.parser.TreeBuilder.parse(SourceFile:43)
       at org.jsoup.parser.HtmlTreeBuilder.parse(SourceFile:56)
       at org.jsoup.parser.Parser.parse(SourceFile:100)
       at org.jsoup.Jsoup.parse(SourceFile:58)

**Comment by gregko** [comment]
I have more info on this issue. I modified the code to return 'empty' result if either nameKeys or name parameter were null, but still got the same crash from another user (unfortunately no way of getting the original HTML code that caused it, crash reports are from Crashlytics). My change, which did not fix the issue, is:

        int codepointForName(final String name) {
            if (nameKeys == null || name == null) // GKochaniak, added - got null obj ref crash here.
                return empty;
            int index = Arrays.binarySearch(nameKeys, name);
            return index >= 0 ? codeVals[index] : empty;
        }

Analyzing the Arrays.binarySearch() code, from Android-25 (API 25, latest) source, I see that it will crash like this, if the nameKeys array contains an entry with null as the value:

    // From Android API 25 Array.java source
    private static int binarySearch0(Object[] a, int fromIndex, int toIndex,
                                     Object key) {
        int low = fromIndex;
        int high = toIndex - 1;

        while (low <= high) {
            int mid = (low + high) >>> 1;
            Comparable midVal = (Comparable)a[mid]; // GKochaniak, crash below if a[mid] is null!
            int cmp = midVal.compareTo(key);

            if (cmp < 0)
                low = mid + 1;
            else if (cmp > 0)
                high = mid - 1;
            else
                return mid; // key found
        }
        return -(low + 1);  // key not found.
    }

I guess the next thing I'll try is to patch load() function in Entities.java, to simply not add any entries to EscapeMode arrays, Could send a patch request for these changes, if needed.

**Comment by gregko** [comment]
Finally found a fix that works. In Entities.java, at the start of private static void load(EscapeMode e, String file, int size) function there is a declaration of arrays, among them:

    e.nameKeys = new String[size];

Then we go through the while(!reader.isEmpty()) loop, filling the arrays in. If for some (whatever erroneous) reason the [size] declaration was too bit, we'll be left with null pointers hanging at the end of e.nameKeys array, which will crash the binarySearch() later. Simply added a counter to know how many entries were actually read, then after exiting the while() loop, I fill the unused entries with something non-null, e.g.:

    for (; counter < size; counter++)
        e.nameKeys[counter] = "nullName" + counter;

Not the smartest solution, and I don't understand how this happens in the first place, but at least no more crashes...

Greg

**Comment by jhy** [comment]
Are you still having this issue in current versions / head? I haven't seen other reports and would expect it to be widespread (because it would happen on every startup). My guess is something in your build was breaking the path to the property files, or reading them.

**Comment by gregko** [comment]
The crash reports went away after the fixes I think I described in my post. It was not wide spread either, only occasional from some users (from over 25,000 daily), so it does not seem likely my build was faulty, but something else (even corrupt installations of the app on some devices?)

 

Greg

**Comment by jhy** [comment]
I've refactored the Entities so that it doesn't require loading a file from the jar resource, because the various Android impls are super dodgy (things like failing after the first install, and always slow). Now they're just all crammed into a .java file which gets optimized pretty well.

**Comment by gregko** [comment]
Thank you, Jonathan, appreciate very much your help and your great product!

Greg

**Comment by jhy** [comment]
Cool beans, thanks for using it :)
