### ISSUE TITLE
302跳转，followRedirects不会附加cookie

### ISSUE THREAD

**Issue by yqMac** [jhy/jsoup#823]
页面302跳转，并且需要附加本次的返回cookie。jsoup如果followRedirects的话只跳转，并不能附加本次的cookie，我只能自己手动处理这种跳转，这点很不人性化，新版本是否有了，没有的话是否考虑可以添加？

**Comment by rockswang** [comment]
可以考虑使用我的java-curl库，只用jsoup解析html
