### ISSUE TITLE
Support SAX style event parser (not just DOM) 

### ISSUE THREAD

**Issue by burtonator** [jhy/jsoup#824]
Hear me out... I know that JSoup is mostly DOM oriented but I'd like to recommend that we consider adding an optional SAX feature.

This is partially related to this issue:

https://github.com/jhy/jsoup/issues/758

but I would like to expand on a description.

Right now the TreeBuilder functionality implements the parsing we need however there is no way to listen to the parse as it happens.

We have some of our queries that are better / faster if they are just implemented together as the document is parsed (rather than CSS selectors).

This way we could just elide the searching during the parse to avoid then having to follow up by recursing into the tree.  

Perhaps "progress" can be implemented in the same framework:

https://github.com/jhy/jsoup/issues/656

**Comment by jokester** [comment]
Considering similar stuff here. Glad to know I'm not alone.

I experienced sub-optimal parsing performance a few days ago, when using jsoup in mh android app.

I can think of a few scenario where SAX-like parser can benefit:

- when the sole aim of parsing is to extract data from HTML (i.e. complete DOM is not required)
- when latency matters. A SAX parser can `emit` a portion of data immediately after it is found. This should play well with stream-ing paradigm like `RxJava`)

I may be able to start doing something in days.

**Comment by burtonator** [comment]
Hey Wang.   We're also going to do some SAX vs JDOM performance benchmarking internally.

I think what would be nice is maybe some raw Element (without emiting parent/children)

**Comment by jokester** [comment]
I have been trying to build a SAX-like parser from jsoup's existing code.

For known-to-be perfect HTMLs, I was able to construct partial DOM trees with a trivial state machine, and CSS-like selector like `>html >body >div#main >ul.class-1 >li`

However such a a simplistic SAX parser would have a very limited use for real-world HTMLs. 
There is actually a [complex rule set](http://w3c.github.io/html/syntax.html#syntax) to parse real-world HTMLs, including how to recover from mismatched tags and so on. Adapting the rules to build a complete new standard-compliance SAX parser would be beyond my available time.

I'm considering another plan: changing jsoup's DOM parser to (emit new Element upon found) and (be able to interrupt when wanted).

**Comment by jhy** [comment]
Hi folks - I have implemented a StreamParser interface in #2096 which should address the needs discussed here. Would welcome your reviews and feedback. (And yes, I know it's seven years later... :) )
