### ISSUE TITLE
Exception when connecting to an url with umlauts

### ISSUE THREAD

**Issue by SnoopyInTheMoon** [jhy/jsoup#826]
I execute the following code

Connection connection = Jsoup.connect("http://www.heizungsforum.de/board/index.php?board/6-ankündigungen").timeout(30000).method(Method.GET);
Connection.Response response = connection.execute();

The result is an exception saying: "Too many redirects occurred trying to load URL"

It has something to do with the umlaut in the url. This behaviour is new since 1.10.2.

**Comment by jhy** [comment]
This is fixed by 56a728d which is in 1.10.3. I'll leave this open until that's released. Apologies for the problems this has caused.

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3
