### ISSUE TITLE
Hot can extract text data from the <font> tag ?

### ISSUE THREAD

**Issue by sarika34** [jhy/jsoup#827]
Example: 
`<div class="ap-section-details-heading">
<span class="sprite orange-circle_stroke_small"></span>
<font>
<font class> John </font>
</font>
</div>`
I have to extract name of the person "John".

**Comment by sarika34** [comment]
element.text() is not able to extract <font> tag. Jsoup does not read <font> tag then what should I do?

**Comment by krystiangor** [comment]
Can you post your HTML again using Code formatting? It disappeared so it's hard to tell what you want to achieve.

**Comment by jhy** [comment]
(I fixed @sarika34's formatting.) Yes, `element.text()` will get it. I don't know what is giving you the impression that jsoup doesn't read the font tag? You can see that it does here: https://try.jsoup.org/~j7sto8f5whimg_0n1W6pEowh4rc

Please post a testable code snippet if you're still having issues.
