### ISSUE TITLE
ConcurrentModificationException when removeAttr() on 1.10.2

### ISSUE THREAD

**Issue by chinhodado** [jhy/jsoup#829]
I just upgraded from 1.8.3 to 1.10.2. I have this method to remove all attributes from an `Element`, taken from [here](http://stackoverflow.com/questions/18233938/jsoup-attribute-removal-on-html-tags):

    private static void removeAttributes(Element doc) {
        Elements el = doc.getAllElements();
        for (Element e : el) {
            Attributes at = e.attributes();
            for (Attribute a : at) {
                e.removeAttr(a.getKey());
            }
        }
    }

However it is throwing ConcurrentModificationException. It worked fine in 1.8.3.

Not sure if this is the same as #759, #779, #785, #799 or not.

**Comment by aug828** [comment]
This is not a bug of jsoup. Java's collection API won't allow you to modify the structure of the collection while iterating through it. The work-around is to use Iterator. The following code should work:
`private static void removeAttributes(Element doc) {
    Elements el = doc.getAllElements();
    for (Element e : el) {
        Attributes at = e.attributes();
        Iterator<String> iter = at.iterator();
       
        while (iter.hasNext()) {
             iter.removeAttr(a.getKey());
        }
    }
}`

**Comment by jhy** [comment]
Or just do it like:

```
Iterator<Attribute> it = el.attributes().iterator();
        while (it.hasNext()) {
            it.next();
            it.remove();
        }
```

I added a method node.clearAttributes() to simplify this.
