### ISSUE TITLE
Element.ownText() and Element.textNodes() strange (undocumented) results

### ISSUE THREAD

**Issue by Mrodent** [jhy/jsoup#832]
No idea whether this is intentional behaviour and/or whether previously discussed...

If you have a `<p>` with some text underneath it (i.e. `<p>some text</p>`) you expect "some text"  to be the TextNode underneath it, and you expect `ownText()` to give you "some text".  OK so far.

But if you have `<p>some text</p>trailing text`, you get two TextNodes, the second containing "trailing text".  Equally surprisingly, you get "some texttrailing text" from `ownText()`.

This behaviour is not documented under the respective methods `ownText` and `textNodes`.  Wouldn't it be preferable to have a `getTrailingTextNode()` method, and only return "some text" for `ownText()`, and only return one TextNode for `textNodes()` (i.e. unless there are more than 1 such TextNodes **actually under** the owner Element)?

**Comment by cketti** [comment]
1. What jsoup version are you using?
2. Can you provide a test case that demonstrates the issue?

The following works fine for me with current `master` (f28c024ba127fd701f0d195a359afbabff04d7a1):

```java
Document document = Jsoup.parseBodyFragment("<p>some text</p>trailing text");

Element containingElement = document.body();
assertEquals("trailing text", containingElement.ownText());
assertEquals(1, containingElement.textNodes().size());
assertEquals("trailing text", containingElement.textNodes().get(0).toString());

Element pElement = document.select("p").first();
assertEquals("some text", pElement.ownText());
assertEquals(1, pElement.textNodes().size());
assertEquals("some text", pElement.textNodes().get(0).toString());
```

**Comment by Mrodent** [comment]
Sorry, just tried your tests and they do indeed run fine.  Just downloaded Jsoup today, and I must have been mixing up my nodes, not understanding about "body" etc.  Apologies for wasting your time.
