### ISSUE TITLE
DataUtil.parseByteData charset detect issue 

### ISSUE THREAD

**Issue by hohojaeho** [jhy/jsoup#834]
If there are two meta[http-equiv=content-type] below the URL, this is not detected

http://www.hanatour.com/asp/contents/eventBoard/cp-00001.asp?hanacode=main_coupon

this site html tag is 
< head>
< META http-equiv="Content-Type" content="text/html">
< title>하나투어 :: 1등 여행사 (주)하나투어</title>
< meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
.
.
.

**Comment by cketti** [comment]
I created a fix for this: https://github.com/jhy/jsoup/pull/835
