### ISSUE TITLE
Sending large json payload with requetBody

### ISSUE THREAD

**Issue by david-romero** [jhy/jsoup#837]
We are trying to make a PUT request of type "application / json" with a fairly large payload and the result is a json lower than 255 characters.

We have reviewed the request and found this code.

`"headersSize": 2038,
         "bodySize": 255,
         "postData": {
           "mimeType": "application/json",
           "text": "[{\"objectname\":\"STATUS\",\"fields\":[{\"name\":\"ACTIVATE\",\"value\":\"E0010\"}]},{\"objectname\":\"TEXTS\",\"fields\":[{\"name\":\"Z005\",\"value\":\"Esto es una resolucion de pruebas de desarrollo\"}]},{\"objectname\":\"SERVICE_H\",\"fields\":[{\"name\":\"ZZFLD000070\",\"value\":\"PET\"}]}]"
         }`

How can we send a payload in json format with more than 255 characters?

We use this method

`Jsoup.connect(url).method.requestBody(json)`

I attached the payload we tried to send.

`[
  {
    "fields": [
      {
        "name": "ACTIVATE",
        "value": "E0010"
      }
    ],
    "objectname": "STATUS"
  },
  {
    "fields": [
      {
        "name": "ZZFLD000070",
        "value": "PET"
      }
    ],
    "objectname": "SERVICE_H"
  },
  {
    "fields": [
      {
        "name": "Z005",
        "value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      }
    ],
    "objectname": "TEXTS"
  }
]`

**Comment by mccxj** [comment]
requestBody doesn't limit the request body size, maybe you use api incorrectly.

code sample below.
```
        Jsoup.connect(echoURL)
                .method(Connection.Method.PUT)
                .header("Content-Type", "application/json")
                .requestBody(json)
                .execute();
```

**Comment by david-romero** [comment]
The problem lies in the client web. Apologize for the confusion.

I close the issue
