### ISSUE TITLE
Unnecessary double encoding of url

### ISSUE THREAD

**Issue by mircowidmer** [jhy/jsoup#839]
The url `http://test.com/&` is not treated correctly as of version 1.10.2 (or maybe even 1.10.1).

`Jsoup.connect("http://test.com/" + URLEncoder.encode("&", "UTF-8")).get();`

The url that gets passed to Jsoup is now `http://test.com/%26` because the `&` was url encoded. So everything works fine in 1.9.2 because the encodeUrl(String url) method in the HttpConnection class does not modify the given url in this example because there is no space in the given url. The same url in 1.10.2 gets encoded again in the encodeUrl() method which leads to the following url: `http://test.com/%2526` (the percent of the url passed to Jsoup is unnecessarily encoded again).

A workaround for this issue is to downgrade to 1.9.2 where the encodeUrl method was implemented differently (see below)

1.10.2:
```
private static String encodeUrl(String url) {
        try {
            URL u = new URL(url);
            return encodeUrl(u).toExternalForm();
        } catch (Exception e) {
            return url;
        }
}
```

1.9.2:
```
private static String encodeUrl(String url) {
	if(url == null)
		return null;
	return url.replaceAll(" ", "%20");
}
```

**Comment by 888bees** [comment]
Faced the same issue!

`URL url = new URL("http://en.wikipedia.org/wiki/Adolph_St%C3%B6hr");
Document notLoaded = Jsoup.parse(url, 10_000);
System.out.println(notLoaded.body().text());`

Fails with a reason 'Exception in thread "main" org.jsoup.HttpStatusException: HTTP error fetching URL. Status=400, URL=https://en.wikipedia.org/wiki/Adolph_St%25C3%25B6hr' (double encoding)

Possible solution is Apache HttpClient for external data loading:
`String DEFAULT_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36";

HttpClient client = HttpClientBuilder.create().setRedirectStrategy(new LaxRedirectStrategy()).build();
RequestConfig conf = RequestConfig.copy(RequestConfig.DEFAULT).setConnectionRequestTimeout(10_000)
				.setMaxRedirects(1).setCookieSpec(CookieSpecs.STANDARD).build();

URL url = new URL("http://en.wikipedia.org/wiki/Adolph_St%C3%B6hr");
HttpGet request = new HttpGet(url.toExternalForm());
request.setConfig(conf);
request.addHeader("User-Agent", DEFAULT_UA);

HttpResponse response = client.execute(request);
Document doc = Jsoup.parse(response.getEntity().getContent(), "UTF-8", url.toExternalForm());
		
System.out.println(doc.body().text());`

**Comment by lsoarestd** [comment]
same here. this changed in this version and my scraper "died"

**Comment by axzhcode** [comment]
same. It worked well in the 1.10.1.

**Comment by dgavrus** [comment]
I have same issue.
`Document document = Jsoup.connect(URL).get();`
My URL has param `...&AGE[]=32...`, it converts to `&AGE%255d%255d`, but it must be `&AGE%5B%5D`

**Comment by jhy** [comment]
Sorry about the issues here. This is fixed in 1.10.3 (upcoming). I fixed it back in 56a728d482ce0c88cd9513eca1e7c7585f0718f9

Will close when 1.10.3 is released

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3

**Comment by rudolfgrauberger** [comment]
It looks like the error has come back in.

```xml
	<dependency>
		<groupId>org.jsoup</groupId>
		<artifactId>jsoup</artifactId>
		<version>1.15.4</version>
	</dependency>
```

```java
      try {
                String html = Jsoup
                    .connect("https://www.transfermarkt.de/filip-kosti%C4%87/profil/spieler/161011")
                    .userAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42")
                    .get()
                    .html();
      } catch (Exception e) {
            System.out.println(e.toString());
      }
```

Results in an exception with following output

```log
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=[https://www.transfermarkt.de/filip-kosti%25C4%2587/profil/spieler/161011]
```
