### ISSUE TITLE
Maven clean cannot delete jsoup jar

### ISSUE THREAD

**Issue by axl8713** [jhy/jsoup#841]
After upgrading from 1.10.1 to 1.10.2, maven can't delete WEB-INF\lib\jsoup-1.10.2.jar while executing clean goal (org.apache.maven.plugins:maven-clean-plugin:2.4.1:clean).
Seems the file is kept locked.
I'm using Apache Tomcat 7.0.69 on Windows.

**Comment by jhy** [comment]
Sounds like a Maven or local issue? Jsoup doesn't really do anything in the build with jars...
