### ISSUE TITLE
<head> tag closed too soon

### ISSUE THREAD

**Issue by florisvdg** [jhy/jsoup#842]
Ran into some unexpected behavior after parsing this page using Jsoup: http://www.reuters.com/article/us-health-pacemakers-appliances-idUSKBN1662EX

The `<head>` tag seems to be closed too soon, causing the `<meta>` tags to appear inside of the `<body>` instead of the `<head>`.

```
Jsoup.connect("http://www.reuters.com/article/us-health-pacemakers-appliances-idUSKBN1662EX").get();
```

**Comment by cketti** [comment]
That's because `<head>` contains `<div class="linebreak"></div>`. Chrome and Firefox also end the `head` element there.

When parsing
```html
<html>
 <head>
  <meta name='one'>
  <div/>
  <meta name='two'>
 </head>
 <body></body>
</html>
```
you'll end up with:

```html
<html>
 <head>
  <meta name="one">
 </head>
 <body>
  <div></div>
  <meta name="two">
 </body>
</html>
```

That's to be expected. See https://www.w3.org/TR/html5/syntax.html#parsing-main-inhead

**Comment by jhy** [comment]
Thanks - working as current browsers / HTML5 == not a bug
