### ISSUE TITLE
TLSv1.2 Support

### ISSUE THREAD

**Issue by MarcFletcher** [jhy/jsoup#843]
I'm attempting to access a https resource using JSOUP (1.10.2 on Java 1.7) that only supports TLS1.2+:

`
String url = "https://blog.kadenze.com/2016/12/01/30-days-codevember/";
Document doc = Jsoup.connect(url).validateTLSCertificates(false).timeout(timeoutMS).get();`

Which is then throwing:

> java.net.SocketException: Connection reset

If someone could confirm this is user error or a genuine bug in the first instance that would be most appreciated.

**Comment by offa** [comment]
The code works with **Java 1.8**. Even without the `validateTSLCertificate()`.

**Comment by MarcFletcher** [comment]
I believe the resource may have been modified subsequent to my post to allow TLSv1 support until it is officially deprecated. Apologies that this ultimately makes debugging harder!

**Comment by pgpx** [comment]
Have you tried enabling TLS 1.2 using suggestions from: http://superuser.com/questions/747377/enable-tls-1-1-and-1-2-for-clients-on-java-7

**Comment by MarcFletcher** [comment]
I resolved this by modifying the static SSL context:

```
      SSLContext ctx = SSLContext.getInstance("TLSv1.2");
      TrustManagerFactory tmf = TrustManagerFactory
          .getInstance(TrustManagerFactory.getDefaultAlgorithm());
      // Using null here initialises the TMF with the default trust store.
      tmf.init((KeyStore) null);
      ctx.init(new KeyManager[0], tmf.getTrustManagers(), new SecureRandom());
      SSLContext.setDefault(ctx);
```
