### ISSUE TITLE
Follow redirect with query params

### ISSUE THREAD

**Issue by evilkid** [jhy/jsoup#844]
Jsoup removes the query param when performing a redirection.
For example,
I have a web which redirects (after login) to a location with some id: 
redirect location: https://www.masite.com/login.php?id=XXXX

However jsoup strips out the "id" param, and just redirect to https://www.masite.com/login.php, 
but you can still get the "correct" redirect link using the response.headers

I had to disable the redirect, and perform the redirection myself:

`Jsoup.connect(postResponse.header("Location")).get()`

**Comment by jhy** [comment]
This is fixed by 56a728d which is in 1.10.3. I'll leave this open until that's released.

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3
