### ISSUE TITLE
NodeTraversor performance issue with nextSibling

### ISSUE THREAD

**Issue by so21** [jhy/jsoup#847]
the function nextSibling is analysing all the sibling nodes to find the current node's postion.
The function is called twice, we could have only one call

**Comment by cketti** [comment]
Where do you get that from? `nextSibling()` uses the node's `siblingIndex` to find the next sibling in the parent's `childNodes` list. Since it's an `ArrayList` that is an O(1) lookup.

**Comment by jhy** [comment]
Please reopen if we've misunderstood
