### ISSUE TITLE
I want modify source code in Element.java

### ISSUE THREAD

**Issue by leeheekyo** [jhy/jsoup#852]
In org.jsoup.node.Element.java on line 1045, "sb.append(elementData);" should be changed to "sb.append(element)"

**Comment by cketti** [comment]
This will modify the behavior in a way so `data()` no longer does what it's documented to do.
What are you trying to accomplish? You didn't provide any explanation whatsoever.

**Comment by leeheekyo** [comment]
I wrote an issue because it seemed that the test case value did not come out correctly during checking the code.
<Test Case>
 Document document = Jsoup.parse("<div><p><a>One</a></p><b>Two</b><p>Three</p>");
 Element p = document.select("p").first();
 assertEquals("<a>One</a>", p.data()); //return false..
In this case, 'p' returns a null value. it seems some mistake. 
Data function output of the Element  seems the desired value("<a>One</a>").

**Comment by cketti** [comment]
The code sample in your comment is not displaying properly. Check out https://help.github.com/articles/creating-and-highlighting-code-blocks/ to learn how to format code blocks on GitHub.

I'm assuming you posted a variation of this test method from your PR #856:

```java
@Test
public void TestDataFunctionInElement() {
    Document doc2 = Jsoup.parse("<div><p><a>One</a></p><b>Two</b><p>Three</p>");
    Element p2 = doc2.select("p").first();
    assertEquals("<a>One</a>", p2.data()); //return false..
}
```

The thing is that `data()` only returns the "data" of an element. That's mainly to get the data between `<script>` or `<style>` tags. What you're trying to do can be accomplished by replacing `p2.data()` with `p2.html()`.

So this is not a bug in jsoup.

One could argue that if you misunderstood what `data()` is for, it's a shortcoming of the [documentation](https://github.com/jhy/jsoup/blob/f28c024ba127fd701f0d195a359afbabff04d7a1/src/main/java/org/jsoup/nodes/Element.java#L1026-L1031). Maybe it could be changed to state that `data()` is mainly useful to get the contents of `<script>` and `<style>` elements, i.e. non-HTML content inside a HTML document. For all other cases you might want to look into `Element#html()` or `Element#text()`.

**Comment by jhy** [comment]
Yep, not a bug, just use text(). I updated the docs to clarify. Thanks for the suggestion @cketti
