### ISSUE TITLE
HTML5 omit optional tags

### ISSUE THREAD

**Issue by jart** [jhy/jsoup#854]
Are you interested in something like this?

https://github.com/bazelbuild/rules_closure/commit/6c5cbe3d51ccebe0f47ec207280533f2e80d1142

**Comment by jhy** [comment]
I like the concept of making a minimal HTML5 output. I haven't really thought about the discussion in #855 much yet or what the implementation can be. Maybe provide a Strategy type object in OutputSettings to define and implement the output strategy?

**Comment by jhy** [comment]
Haven't seen much interest or traction here, so will close. But happy to review.
