### ISSUE TITLE
<div data-reactroot> is hidden

### ISSUE THREAD

**Issue by jeffreyzhang23** [jhy/jsoup#861]
the structure looks like this,
`<div id="app">` 
    `    <div data-reactroot>...</div>`
`</div>`

My code is
Element element = document.select("div#app").first();
System.out.println(element);

the output is `<div id="app"></div>`. How can I get the content below the tag "data-reactroot"?  thank you. @jhy

**Comment by krystiangorecki** [comment]
String dataReactroot= element.attr("data-reactroot");

**Comment by jeffreyzhang23** [comment]
I can only get the <div id="app"></div>. The content below the "app" named the <div data-reactroot>...</div> is invisible. So, the output of "String dataReactroot= element.attr("data-reactroot");" is "".

**Comment by krystiangorecki** [comment]
Ok, you edited first comment so I can see your html.
```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

public class JsoupIssue861 {
    public static void main(String[] args) {
        String html = "<div id=\"app\"> <div data-reactroot>...</div> </div>";
        Document document = Jsoup.parse(html);
        Element element = document.select("div#app").first();
        System.out.println(element);
        System.out.println("-----------------------------------");
        System.out.println(document.select("div[data-reactroot]").first());
        System.out.println("-----------------------------------");
        System.out.println(document.select("div[data-reactroot]").first().text());
    }
}

```
and my output is:
```
<div id="app"> 
 <div data-reactroot>
  ...
 </div> 
</div>
-----------------------------------
<div data-reactroot>
 ...
</div>
-----------------------------------
...
```
So for me nothing is hidden, and everything is visible using Jsoup 1.10.2.
