### ISSUE TITLE
Speed up matching CSS selectors and other tasks which use elementSiblingIndex()

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [jhy/jsoup#863]
Matching css selectors can be slow because finding `elementSiblingIndex()` is relatively slow. 
I have created a pull request https://github.com/jhy/jsoup/pull/862 which provides a way to cache the sibling index for all siblings which results in speeding up subsequent calls to `elementSiblingIndex()`. It would be possible to speed up other calls which effectively want to know the `elementSiblingIndex()` but do not call that method. I didn't make too many changes I would like to know if such a change to Jsoup would be acceptable or if plans already exist for speeding up CSS selectors.

**Comment by LukeButtersFunnelback** [comment]
@jhy um am i going about this the wrong way? I tried to use the google group https://groups.google.com/forum/#!forum/jsoup but my posts are just sent for review and I never see them or here anything back.

**Comment by jhy** [comment]
Apologies for the late replies on this @LukeButtersFunnelback. You are/were going about it the right way, I just haven't been able to keep up with the project for a while until now. Really appreciate your contribution.
