### ISSUE TITLE
validateTLSCertificates(false) throws SSL error

### ISSUE THREAD

**Issue by flyingfischer** [jhy/jsoup#866]
Disabling TLS validation by:
Jsoup.connect("https://jsoup.org/news/").validateTLSCertificates(false).timeout(15000).execute();

throws javax.net.ssl.SSLException: Received fatal alert: internal_error, while

The same request with activated TLS validation works:
Jsoup.connect("https://jsoup.org/news/").validateTLSCertificates(true).timeout(15000).execute();

Strange behaviour, since non-validating will cause an SSL error. While this may be a Java bug and being related to https://github.com/jhy/jsoup/issues/659, could there be a workaround (beside enabling validation).

Oracle Java HotSpot(TM) 64-Bit Server VM
build 25.111-b14 until at least 1.8.0_121-b13

UnlimitedJCEPolicyJDK8.jars

**Comment by jhy** [comment]
I deprecated the method (in favor of setSslSocketFactory), so this path can't be hit
