### ISSUE TITLE
Error: "Self closing flag not acknowledged" for self closing break

### ISSUE THREAD

**Issue by buett** [jhy/jsoup#868]
This code snippet returns invalid html with the message: "Self closing flag not acknowledged"
```java
Jsoup.isValid("<p>test<br/>test</p>")
```
Why breaks could not be self closing?

**Comment by jhy** [comment]
Because that's the spec. HTML5 doesn't use self-closing tags for tags that can't contain anything, like br, img, etc.

https://html.spec.whatwg.org/multipage/parsing.html#self-closing-flag

**Comment by beosign** [comment]
According to https://www.w3.org/TR/html5/syntax.html#void-elements , `<br/>` is *not* disallowed, see section 8.1.2.1, point 6:
> Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single "/" (U+002F) character. This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

Since `<br>` is a void element (https://www.w3.org/TR/html5/syntax.html#void-elements), `<br/>`should be considered valid.

**Comment by jhy** [comment]
Thanks, I misread this part of the spec (or was updated after implementing)

https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody

> A start tag whose tag name is one of: "area", "br", "embed", "img", "keygen", "wbr"
> Reconstruct the active formatting elements, if any.
> 
> Insert an HTML element for the token. Immediately pop the current node off the stack of open elements.
> 
> Acknowledge the token's self-closing flag, if it is set.
> 
> Set the frameset-ok flag to "not ok".
