### ISSUE TITLE
Class name with a middle blank space

### ISSUE THREAD

**Issue by ghuiii** [jhy/jsoup#869]
![image](https://cloud.githubusercontent.com/assets/5203798/25068832/ebbac08c-22a1-11e7-9a99-cf91f78d202f.png)
Selector doesn't work for this case. Is there any way to  handle it.

**Comment by ghuiii** [comment]
Finally, I found the solution:

``div.cell.item``

from [here](http://stackoverflow.com/questions/1988483/jquery-selector-classname-with-space/1988486#1988486)

**Comment by jhy** [comment]
Thanks. I need to write a FAQ and include this, as it does cause a lot of confusion.
