### ISSUE TITLE
text() returns empty string/ whitespace for multiline content

### ISSUE THREAD

**Issue by pgtaboada** [jhy/jsoup#871]
Hi,

as soon as I have elements containing line breaks, the "text()" or "ownText()" methods return only whitespace.

E.g:

```
<h2 class="myClass">

Some text
Another text

</h2>
```

`String content = docTherapeut.getElementsByClass("myClass").first().text();`

the content is empty.

Any idea?

**Comment by jhy** [comment]
Works for me: https://try.jsoup.org/~vfU9apxXRmJfPJG96F04HbwfqYY

(With pretty print on or off so it's not that.)

Can you post some an executable code snippet?
