### ISSUE TITLE
Read timed out Error Using Thread

### ISSUE THREAD

**Issue by Mdhaker** [jhy/jsoup#874]
Hello,
It's seems that Jsoup.connect doesn't support threads, when trying to load a url `Jsoup.connect(url).get()` inside a thread it gives `Read timed out` error, I don't know if there is an issue already opened about it, but I think it needs a solution.

**Comment by jhy** [comment]
Can you provide some example code please? There are tonnes of active use of jsoup.connect in async threads. It's just a standard URL connection under the hood. And your main thread is still a thread...
