### ISSUE TITLE
jsoup update to 1.10.2 breaks getting the subpage

### ISSUE THREAD

**Issue by EdwinKM** [jhy/jsoup#875]
See the following code. This site is using a "#No.Title" on page "http://mov-world.net/archiv/TV/A/"
When i used version 1.83 i managed to download this page with "%23No.Title". But this seems broken in "1.10.2"
I tried some things but i do not know how to fix this.

		String url;
		
		/* this one works fine with 1.83.
		 * If i use 1.10.2 i get a site result: "main.archive.inc.php Fehler 6: Der Ordner "%23No.Title" existiert nicht!" 
		 * 
		 */
		url = "http://mov-world.net/archiv/TV/A/%23No.Title/";
		
		
		/* 1.10.2: the next one results in the content of "http://mov-world.net/archiv/TV/A/" and not the subpage!
		 * 
		 */
		url = "http://mov-world.net/archiv/TV/A/#No.Title/";
		
		
		/* 1.10.2: this one generate a exception 
		 * java.lang.IllegalArgumentException: Malformed URL: http%3A%2F%2Fmov-world.net%2Farchiv%2FTV%2FA%2F%23No.Title%2F
		 * */
		url = URLEncoder.encode( "http://mov-world.net/archiv/TV/A/#No.Title/", "UTF-8");
		
		
		
		Response response = Jsoup.connect(url)
				.method(Method.GET)
			    .execute();
		
		Document doc = response.parse();
		
		LOG.info(doc.toString());

**Comment by EdwinKM** [comment]
in fact, 1.10.1 works fine. I suspect it has something to do with this change: "Bugfix: in Jsoup.Connect, URLs containing non-URL-safe characters were not encoded to URL safe correctly."

**Comment by rmiroballi** [comment]
I'm seeing the same behavior with encoded URLs. If the page is 'https://www.nar.realtor/educsess.nsf/programsbyTopicfrm?OpenForm&CategoryName=Hot%20Topics'
it will load into the document just fine. But the location attribute is set to 'https://www.nar.realtor/educsess.nsf/programsbyTopicfrm?OpenForm&CategoryName=Hot%2520Topics'

I switched to 1.10.1 and it's behaving as expected (thanks @EdwinKM)

**Comment by KevinSmile** [comment]
Also find the bug in version 1.10.2.

**Comment by mengyang0427** [comment]
Simply don't encode url at your side will be OK, or it would be encoded twice. Yesterday I also faced this issue when I try to upgrade from 1.8.3 to 1.10.2, after realized that I would have to change my code at several place I finally gave up and stay at 1.8.3 for a while.

Good luck.

**Comment by jhy** [comment]
This is fixed by 56a728d482ce0c88cd9513eca1e7c7585f0718f9 which is in 1.10.3. I'll leave this open until that's released. Apologies for the problems this has caused.

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3
