### ISSUE TITLE
Should normalize the input text in :contains() queries

### ISSUE THREAD

**Issue by unitydynamics** [jhy/jsoup#876]
I've been a JSoup user for a long time.  I appreciate the work that went into it!

I've found a circumstance which tripped me up.  I was using the :contains(With  Text)

(that's 2 spaces between "With" and "Text".  The raw HTML has the text this way.  But it seems JSoup matches on the normalized text.  If this is the expected behavior maybe just add a note to the documentation on it?  Thanks.  Or even better... can we use quotes to force matching against the un-normalized text?  I suppose it might be confusing if  :contains(With  Text) and  :contains("With  Text") were different.

**Comment by jhy** [comment]
It seems like it would be better to normalize the `contains` text query so we're comparing apples to apples.

**Comment by Ruefors** [comment]
I wonder if this is a formatting issue because the parser will merge extra Spaces when parsing,You also need to format a string when using the Cotaines search, such as merging extra Spaces

**Comment by jhy** [comment]
Taking another look at this and somewhat related #576. I think we can address this, make some improvements, and also maintain backwards compatibility:

 - for `:contains(text)`, normalize the selector text in the same way that the `text() ` and `ownText()` methods work. That directly fixes this issue. I conceptually like the neatness of using `:contains("text")` to use a non-normalized search, but that's a bit stringly typed, and maybe backwards in-compat.
 - introduce something like `:containsWhole` and :containsOwnWhole which uses `wholeText()` and no normalization to either the input or the query. That way we can find content including newlines, tabs, repeated spaces, etc
 - for #576, introduce `:matchesWhole` and `:matchesOwnWhole`, to work similarly for regular expressions
