### ISSUE TITLE
select("title") returns on one line when using pretty text

### ISSUE THREAD

**Issue by Joe-20667512** [jhy/jsoup#878]
I have something that uses <title>Title goes here</title>.

input:
<title>Title</title><author>Name</author>

What I expect:
<title>
  Title goes here
</title>
<author>
  Name
</author>

**What happens:**
<title>Title goes here</title>
<author>
  Name
</author>

example: https://try.jsoup.org/~rPSaJI4T6ihHEa6C2sEQHyeoiMc

**Comment by jhy** [comment]
The HTML output you linked to doesn't look like your "what happens". It's this:

Input:
```
<title>Title goes here</title><author>Author goes here</author><rating>0</rating><test></test>
```

Output:
```
<html>
 <head>
  <title>Title goes here</title>
 </head>
 <body>
  <author>
   Author goes here
  </author>
  <rating>
   0
  </rating>
  <test></test>
 </body>
</html>
```

Looks OK to me, can you clarify the problem?

**Comment by Joe-20667512** [comment]
I expect the <title> line to look like the <author> line, where it's on multiple lines
