### ISSUE TITLE
DataUtil Suggestions

### ISSUE THREAD

**Issue by thedug** [jhy/jsoup#88]
I overwrote DataUtil for 2 reasons, and you may want to consider these changes in a way that may work for your other users.

1) When there is an SocketTimeoutException, instead of throwing the exception backup, I return the bites that have already been read, this means that on a slow server or a server that never closes it's connection, we'll at least get some of the html back.
.. Maybe a custom exception would allow the exception to be reported but the bytes to also be returned.
2) I added mozilla's universalchardet to your charset detection. You may not want to ship with this dependency, but a plugable way to implement a  charset detection might be nice.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
