### ISSUE TITLE
[Proxy Error] Unrecognized SSL message, plaintext connection

### ISSUE THREAD

**Issue by jaspergould** [jhy/jsoup#880]
`                        Response loginForm = Jsoup.connect("https://site.com")
//                                .validateTLSCertificates(false)
                                .userAgent("Mozilla v1")
                                .proxy("185.22.66.40", 80)
                                .header("Content-Type", "application/json")
                                .ignoreContentType(true)
                                .ignoreHttpErrors(true)
                                .requestBody(body) 
                                .method(Method.POST)
                                .execute();`

![](http://image.prntscr.com/image/8a5427dcd66c415c9cbeaf083982e371.png)

**Comment by jaspergould** [comment]
Im added 

                        System.setProperty ("jsse.enableSNIExtension", "false");
                        System.setProperty("https.proxyHost", "185.22.66.40"); // set proxy server
                        System.setProperty("https.proxyPort", "80"); // set proxy port

to code 

and this don't work

**Comment by jhy** [comment]
I don't know how anyone can debug this issue for you as it stands. What's the site, what's the proxy, what's your JDK? I very often proxy through Charles (for example) onto ssl sites with no problem.
