### ISSUE TITLE
Wrong connecting to pages whose URL contains special UTF-8 characters

### ISSUE THREAD

**Issue by szydra** [jhy/jsoup#882]
The method Jsoup.connect() in Jsoup 1.10.2 returns a wrong Document when its argument contains Polish UTF-8 characters (e.g. "https://www.google.pl/search?q=gąska"). There is no such a bug in Jsoup 1.10.1.

**Comment by jhy** [comment]
This is fixed in 1.10.3 by 56a728d482ce0c88cd9513eca1e7c7585f0718f9

Will close this when released. Sorry about the issue!

**Comment by jhy** [comment]
jsoup 1.10.3 is out now: https://jsoup.org/news/release-1.10.3
