### ISSUE TITLE
Connection.get() Fails on Some Sites using HTTPS URLs

### ISSUE THREAD

**Issue by adxBRudolph** [jhy/jsoup#885]
Using version 1.10.2 I found failures getting pages from some sites using the HTTPS protocol. Sometimes an IOException is thrown. Sometimes the fetch of the page is redirected to the home page of the site.

I rolled back to version 1.10.1 and successfully fetched the pages with the same URLs that had the noted problems.

**Comment by cli** [comment]
I can confirm this for some Wikipedia sites, e.g. https://be.wikipedia.org/ . JSoup throws exception with HTTP code 400.

**Comment by mccxj** [comment]
bugfix at https://github.com/jhy/jsoup/commit/56a728d482ce0c88cd9513eca1e7c7585f0718f9.
it works now.
