### ISSUE TITLE
Change source language to Java 7

### ISSUE THREAD

**Issue by jhy** [jhy/jsoup#899]
jsoup has traditionally remained on Java 5 to maintain broad compatibility, but that's a very old version now. Ultimately I'd like to move it up to Java 8, but Android's [support for 8](https://developer.android.com/studio/preview/features/java8-support.html) is still a bit wooly. So for now, let's move to 7.

Note that as of writing, only the build tools in Android Studio 3 Preview support try-with-resources, so we can't use that just yet.

**Comment by jhy** [comment]
Fixed by e2ff399dfdb1d4cf4ebb639d1fc2689aa2f6f3eb

**Comment by offa** [comment]
Good news! But shouldn't this *incompatibility* to older versions manifest in a new (minor) version of jsoup?

**Comment by jhy** [comment]
Yes, it'll be in 1.11.1+. And 1.10.x is the last that was on Java 5.

**Comment by offa** [comment]
Makes sense.
