### ISSUE TITLE
Implement shallow clone?

### ISSUE THREAD

**Issue by mping** [jhy/jsoup#900]
If I want to implement a traverse-and-copy algorithm, but copying only some nodes selectively, my first idea would be to use a shallow clone and traverse the jsoup DOM.

Since the DOM is kinda immutable, how can I implement this? A shallow clone (eg: exposing `doClone` I guess) would be ideal, otherwise I would have to implement a shallow clone myself.

**Comment by jhy** [comment]
Thanks for the suggestion, makes sense.

**Comment by jhy** [comment]
Thanks; took a while but it's done :)

**Comment by mping** [comment]
Great! Thanks 👍
