### ISSUE TITLE
Jsoup fetch URL wrong

### ISSUE THREAD

**Issue by trinhvanminh2009** [jhy/jsoup#902]
Jsoup fetch URL wrong with character "%" . I'm input with this link "http://zh.vietnamplus.vn/topic/%E4%B8%9C%E7%9B%9F/131.vnp" //This link from chinese
after fetch , jsoup not found link. Because it's auto change link % is %25 . "http://zh.vietnamplus.vn/topic/%25E4%25B8%259C%25E7%259B%259F/131.vnp".
Just only have problem with chinese (character %) not problem with link don't have character "%"

**Comment by krystiangorecki** [comment]
There was a problem with URL escaping. It works on jsoup 1.10.3.

**Comment by jhy** [comment]
That's right, please upgrade to 1.10.3.

**Comment by trinhvanminh2009** [comment]
Thanks guys, I know why it happened . Because I'm didn't decode link. I'm using UTF-8 , I have to decode the link. https://www.w3schools.com/tags/ref_urlencode.asp. I did it.
@krystiangorecki  and @jhy Thank you so much.
