### ISSUE TITLE
Project :: Slimfast

### ISSUE THREAD

**Issue by jhy** [jhy/jsoup#911]
There are a couple of memory use improvements I've been thinking about:

**Text Nodes** (and related nodes like scripts, comments etc) take up more memory in the DOM than they need to, because they extend the standard base Node type, which includes slots for child nodes, and a whole Attributes object is used just to track their (almost always) singular value. If we refactor this around and introduce a Leaf Node type which doesn't hold as much data, there will be a significant memory saving.

**Attributes** take up a bunch of memory because they are implemented as Linked Hash Sets. I chose that data-structure to support fast map lookups and insert order preservation. But in practice it's very wasteful. Each entry takes up a bunch of memory (linked list: holder, next, prev, map spare capacity, etc), and iterating creates loads of garbage iterators. And because we almost always are doing case-insensitive searches, the map hit rate is pretty low. This could be refactored into a couple of arrays for large memory and CPU savings.

Memory reductions are highly leveraged improvements because smaller DOMs allow you to work with more / bigger pages, and reduced allocation time and garbage collection time means lower latencies and higher throughput.

**Comment by jhy** [comment]
Part one, **Leaf Nodes** is implemented in f71712ba5d28df09c9a5b6e3c8a37f05f5e3372d

**Comment by jhy** [comment]
Part two, **Attributes** is implemented in ea1fb65e9ff8eee82c4e379dc3236d09a5ab02e1

**Comment by jhy** [comment]
Some analysis of these changes (pages fetched today):

**Memory consumption** of retained Document

Page|File Size|1.10.3|1.11.1|Change
---|---|---|---|---
Wiki Baseball|487 KB|3,211,504 B|2,436,668 B|**-24.12%**
NYT Home|220 KB|1,205,880 B|943,808 B|**-21.73%**

**CPU Time** on Android N, Nexus 5x (milliseconds each, 100 iters mean)

Version | Page | Parse | HTML | Select
---|---|---|---|----
1.10.3 | Wiki | 55 | 170 | 2
1.11.1| | 43 | 86 | 1
1.10.3| CNN | 36 | 99 | 2
1.11.1| | 32 | 47 | 0.3
1.10.3| Amzn | 68 | 152 | 3
1.11.1| | 60 | 73 | 1|
**Avg Change** | | **-15%** | **-51%** | **-67%**

**Comment by ny83427** [comment]
Come here from one of your tweet. Very impressive work and analysis.
