### ISSUE TITLE
Potential bug - Behavior change accessing text element

### ISSUE THREAD

**Issue by davejg** [jhy/jsoup#913]
Hello,

When I moved from jsoup-1.10.2 to jsoup-1.10.3 I encountered a behavior difference accessing the text of an element.  The sample XML Snippet is below.   Is this a bug or an intentional change to behavior?

Dave

jsoup-1.10.2 Behavior
- String id = xmlDoc.select("APPENDIX").select("WEB_APPLICATION").first().select("ID").text();
- id contains "0123456"

jsoup-1.10.3 Behavior
- String id = xmlDoc.select("APPENDIX").select("WEB_APPLICATION").first().select("ID").text();
- id contains "0123456 Fake App Name http://www.fakeurl.com/ Nobody Special Oracle Enterprise Linux 7.3 Limit to URL hostname true"

XML Snippet.
`<APPENDIX>
<WEB_APPLICATION>
<ID>0123456</ID>
<NAME>Fake App Name</NAME>
<URL>http://www.fakeurl.com/</URL>
<OWNER>Nobody Special</OWNER>
<OPERATING_SYSTEM>Oracle Enterprise Linux 7.3</OPERATING_SYSTEM>
<SCOPE>Limit to URL hostname</SCOPE>
<PROGRESSIVE_SCANNING>true</PROGRESSIVE_SCANNING>
</WEB_APPLICATION>
</APPENDIX>
`

**Comment by jhy** [comment]
Hi, I'm afraid I'm not able to reproduce your issue. Here's my code:

```
public static void main(String... args) {
    String xml = "<APPENDIX> <WEB_APPLICATION> <ID>0123456</ID> <NAME>Fake App Name</NAME> <URL>http://www.fakeurl.com/</URL> <OWNER>Nobody Special</OWNER> <OPERATING_SYSTEM>Oracle Enterprise Linux 7.3</OPERATING_SYSTEM> <SCOPE>Limit to URL hostname</SCOPE> <PROGRESSIVE_SCANNING>true</PROGRESSIVE_SCANNING> </WEB_APPLICATION> </APPENDIX>";

    Document doc = Jsoup.parse(xml, "", Parser.xmlParser());
    String id = doc.select("APPENDIX").select("WEB_APPLICATION").first().select("ID").text();
    System.out.println(id);
}
```
Which produces: `0123456`, using jsoup 1.10.3.

Could you post a full working code snippet so we can find the issue?

Also a simpler expression to get the same ID field would be:

```
String id = doc.select("APPENDIX WEB_APPLICATION ID").text();
```

**Comment by davejg** [comment]
Hi,
Thanks for the simpler expression!  Yes, this is interesting.  In the example images below, I have a snippet of the code running on 1.10.2 and 1.10.3 on Netbeans with jdk 1.8.40.  What do you think?   

jsoup-1.10.2 image of program running.
![jsoup-1 10 2-image](https://user-images.githubusercontent.com/30010188/28006278-a0b6f89a-651c-11e7-9be7-9ce9462145c9.PNG)

jsoup-1.10.3 image of program running.
![jsoup-1 10 3-image](https://user-images.githubusercontent.com/30010188/28006209-5a042e40-651c-11e7-883c-e3c0655e3979.PNG)

XML input data ( with .txt appended to filename )
![testData.xml.txt](https://github.com/jhy/jsoup/files/1134637/testData.xml.txt)

java code
![testjsoup.java.txt](https://github.com/jhy/jsoup/files/1134648/testjsoup.java.txt)

**Comment by jhy** [comment]
I would look at debugging your input. Try printing out the contents of the file and also the body of the document after the parse. My guess is that your issue is not in the select, but either in the actual contents of the file (they're not what you expect) or the parse, for some reason.

**Comment by davejg** [comment]
Ok.  Thanks for the help!

**Comment by davejg** [comment]
Hi,

Ok, so I changed this line from 
  
`Document xmlDoc = Jsoup.parse(xmlPath.toFile(), "UTF-8", `"");`

to

`Document xmlDoc = Jsoup.parse(new String(Files.readAllBytes(xmlPath)), "", `Parser.xmlParser());`

and all is well.  Thanks for your help!

Dave
