### ISSUE TITLE
InputStream not closed in class org.jsoup.nodes.Entities

### ISSUE THREAD

**Issue by ltlBeBoy** [jhy/jsoup#916]
**Problem:**
InputStream is not closed in class org.jsoup.nodes.Entities which may cause exceptions in J2EE applications.

**Version:**
1.10.3

**Details:**
The class `org.jsoup.nodes.Entities` provides different `Entities#EscapeMode`s that call `org.jsoup.nodes.Entities#load(...)` to load the appropriate properties file. The file is loaded by creating an `InputStream` which is never closed. This may cause problems in some applications and may lead to an exception when undeploying a J2EE application.
A solution would be to close the input stream in a finally-block at the end of the try-catch-block that reads the content of the input stream:

    private static void load(EscapeMode e, String file, int size) {
        ...
        InputStream stream = Entities.class.getResourceAsStream(file);
        if (stream == null)
            throw new IllegalStateException("Could not read resource " + file + ". Make sure you copy resources for " + Entities.class.getCanonicalName());
        
        int i = 0;
        try {
             ByteBuffer bytes = DataUtil.readToByteBuffer(stream, 0);
             ...
        } catch (IOException err) {
             throw new IllegalStateException("Error reading resource " + file);
        } finally {
            try {
                stream.close();
            } catch (IOException ioex) {
                // ignore
            }
        }

See also [Do unclosed streams cause memory leaks in java?](https://stackoverflow.com/a/22889202/5223047)

**Comment by chchgb** [comment]
Android strictmode also report this issue, pls fix

**Comment by hameno** [comment]
Im having the same issue

**Comment by jhy** [comment]
Fixed with merge of #928
