### ISSUE TITLE
HTML documents with escaped entities unwanted modification

### ISSUE THREAD

**Issue by bdina** [jhy/jsoup#919]
When a document is parsed by JSoup escaped HTML entities are converted into their appropriate characters however when calling Document.html() the previously escaped HTML entities are missing but their characters are in their places for anything that is not a `<` `>` `&` `'` ` ` character.

I would like to have a feature that allowed me to use the parser without converting these characters, or at least preserve the HTML escaped entities.

For example, using this program:
```
public class TestJsoupProcessing {
    public static void main(String args[]) throws Exception {
        File file = new File("/tmp/ligature");
        String str = FileUtils.readFileToString(file);
        final Document doc = Jsoup.parse(str);
        doc.outputSettings(doc.outputSettings().prettyPrint(false));
        System.out.println(doc.html());
    }
}
```
With this input:
```
<html><body>
A&zwnj;B
C&nbsp;D
</body></html>
```
would output:
```
<html><body>
A&zwnj;B
C&nbsp;D
</body></html>
```
but instead (as of JSoup 1.10.3) is outputting:
```
<html><body>
AB
C&nbsp;D
</body></html>
```

**Comment by jhy** [comment]
Happy days then, as this feature exists!

https://jsoup.org/apidocs/org/jsoup/nodes/Document.OutputSettings.html

Set the charset to ascii to force characters to be escaped (the default is UTF-8 which doesn't need them to be escaped, which is why you see the output you do), and set the EscapeMode to Extended so you get all the named escapes vs the numeric ones.

**Comment by bdina** [comment]
Apologies in advance for my ignorance, but will setting the parser character set to **ascii** have any adverse affects on incoming HTML documents that were encoded in **UTF-8**?

As a follow up though, this sounds like all documents will be escaped regardless of whether the input was. I was asking for a feature that would leave the content as it was when input to the parser.

My use-case is two parts for your product, both apply to HTML documents in email:
1. parse UTF-8 encoded HTML documents (to support foreign character sets) to parse trees
2. using parse tree find-and-replace all links leaving all other content unchanged

The problem I have with use-case 2 right now is that the parser is modifying the content of the document.

**Comment by jhy** [comment]
None of this is going to have an "adverse" effect. Escaped or not the output is still valid, it's just a matter of taste what you want it to look like.

If it were me I'd just push everything out as UTF8 and only escape what really needs to be escaped. Makes the output trimmer and simpler to read for the few people who are actually looking at source.

To get what you want to do, just look at the input charset and set the outout charset to match.

jsoup always serializes from the DOM tree. It is not trying to be a no-touch filter through source.

**Comment by cyberbeat** [comment]
I would also like jsoup to optional not modify anything in the document, except changes I make. For example I try to do some modifications, and then try to diff, if the modification is correct, but then the diff is polluted with some entitiy-encoding/decoding and completed xhtml-style-attributes.
