### ISSUE TITLE
Element.text() loses leading / trailing space

### ISSUE THREAD

**Issue by nator** [jhy/jsoup#92]
I have documents with the following (valid) markup:

The text&lt;strong> has spaces: &lt;/strong>inside the strong tags!

I'm trying to remove the strong tags but when I ask the strong Element for text() it comes back without the trailing spaces so I get:

The texthas spaces:inside the strong tags!

I'm pretty sure this isn't correct behavior, but I'm not sure how to solve it. I started to write a utility function to check if the only child node is a TextNode and just use getWholeText(), but I found several examples where there's a nested link or something, so that doesn't work.

Is this fixable in a non-hacky way in JSoup? Or should I try to pre-process my documents and fix these cases with a regex?

**Comment by creativeprogramming** [comment]
I also am getting whitespaces trimmed, I'm trying to replace `<b> word </b>` with `<strong> word </strong>` but I get `<strong>word</strong>` 

```      elm.replaceWith(
                                    new Element(
                                            Tag.valueOf("strong"), "")
                                    .html(
                                            elm.html()
                                    )
                            );
```
