### ISSUE TITLE
Regression: CSS attribute selector

### ISSUE THREAD

**Issue by felipemsantana** [jhy/jsoup#926]
Using this selector: `tr[id~=linhaSel_\\d+][onclick^=redirect(']`

It matches the following HTML tag in 1.10.2:
```html
<tr id="linhaSel_0" onclick="redirect('/internet_base/processoman.do?evento=Editar&amp;chPlc=AAAS6DABaAAJrIpAAE')" class="linhapar" onmouseover="marcaSelecao(this, event)" onmouseout="marcaSelecao(this, event)" style="cursor:hand;cursor:pointer;" title="">
...
</tr>
```

But for 1.10.3 Jsoup throws:
```
org.jsoup.select.Selector$SelectorParseException: Did not find balanced maker at onclick^=redirect(
```

Probably something related to commit https://github.com/jhy/jsoup/commit/8fecf72da0c9d1d6da7ec1aab0214ff68588da88

**Comment by goforbroke1006** [comment]
Hi, @fmatoss !
You should not use apostrophe in last part of selector.
Apostrophe means that you try to define some value.
Try to use selector
tr[id~=linhaSel_\\d+][onclick^="redirect("]
I'm sure this will work =)
