### ISSUE TITLE
No Protocol Issues

### ISSUE THREAD

**Issue by SawKienSeng** [jhy/jsoup#929]
Hi everyone,
The android studio keep prompt this error and my url is "http://blog.dota2.com"

W/System.err: java.net.MalformedURLException: no protocol: 
W/System.err:     at java.net.URL.<init>(URL.java:589)
W/System.err:     at java.net.URL.<init>(URL.java:486)
W/System.err:     at java.net.URL.<init>(URL.java:435)
W/System.err:     at com.era_app.era.i_era_mobile.interfaces.EraZap.LinkPreview.LinkPreviewInteractorImpl$LinkPreviewTask.doInBackground(LinkPreviewInteractorImpl.java:202)
W/System.err:     at com.era_app.era.i_era_mobile.interfaces.EraZap.LinkPreview.LinkPreviewInteractorImpl$LinkPreviewTask.doInBackground(LinkPreviewInteractorImpl.java:158)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:316)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:776)

**Comment by mccxj** [comment]
@SawKienSeng there is nothing informaction about jsoup!?

**Comment by AllanWang** [comment]
Can you confirm that you sent it with the http, rather than like `blog.dota2.com` as seen in the browser head?

**Comment by SawKienSeng** [comment]
Hi All, after i update to "org.jsoup:jsoup:1.10.3", the "No Protocol error" disappear already.
Thank for helping.
