### ISSUE TITLE
Method <Element>.children() Returns a List of Child Nodes but Some Children Contain the parent Field as null

### ISSUE THREAD

**Issue by adxBRudolph** [jhy/jsoup#933]
I have code that is getting the list of child nodes and it loops on them and removes those children that do not have text (<Element>.hasText() == false). However I have found some HTML in pages processed where some of the children in the list returned by <Element>.children() have null as their parent field. 
This causes the following exception from the <Node>.remove() method:

> java.lang.IllegalArgumentException: Object must not be null

I have a work around in the code by skipping the removal of those children whose parent is null. 

I found this in release 1.10.3

A copy of a sample of HTML that causes this is attached.

[jsoup-child-remove-problem.html.txt](https://github.com/jhy/jsoup/files/1223581/jsoup-child-remove-problem.html.txt)

**Comment by mccxj** [comment]
@adxBRudolph can you show the detail operations or simple code?

**Comment by adxBRudolph** [comment]
Below is the code snippet that processes the children returned from the Node.children() method in a loop. It contains the work around. The variable node is an instance of Node:

```
      val nodeChildren = node.children()
      for (child <- nodeChildren) {
        if (!child.hasText) {
          if (child.parent() != null) {
            child.remove
          }
        }

```

**Comment by mccxj** [comment]
@adxBRudolph i test node "body", but it works. 
could you show the min testcase with jsoup-child-remove-problem.html.txt?

**Comment by adxBRudolph** [comment]
Sorry. I posted an incorrect HTML. Attached here is a new version of the HTML with the root node as a 

`<td>
`

 element. This is the root element the problem is found on.

I also attach the PDF file that shows screenshots of the issue for better clarity.

[jsoup-child-remove-problem_2.html.txt](https://github.com/jhy/jsoup/files/1225603/jsoup-child-remove-problem_2.html.txt)
[Jsoup Issue 933.pdf](https://github.com/jhy/jsoup/files/1225605/Jsoup.Issue.933.pdf)

I ran the same node against Jsoup 1.10.2 and it works. The number of children returned is less than returned in Jsoup 1.10.3 The next attachment shows this.
[Jsoup Issue 933 - Correct on Jsoup 1.10.2.pdf](https://github.com/jhy/jsoup/files/1225631/Jsoup.Issue.933.-.Correct.on.Jsoup.1.10.2.pdf)

**Comment by mccxj** [comment]
@adxBRudolph 

i arranged a new html like this, but the number of children of node '<td>' is 36, whether 1.10.2 or 1.10.3. 
could you please provide a test case?
```html
<html>
<body>
 <table><tr>
<td valign="top">...</td>
 </tr></table>
</body>
</html>
```

**Comment by adxBRudolph** [comment]
Hmmm. I thought that was enough of a test case.

I'll see about getting another test case.

**Comment by jhy** [comment]
Please reopen if you can find a [test case](https://stackoverflow.com/help/mcve) that repros.
