### ISSUE TITLE
java.lang.IndexOutOfBoundsException Occurs with Certain HTML in 1.10.3 but not in 1.10.2

### ISSUE THREAD

**Issue by adxBRudolph** [jhy/jsoup#935]
In a scala file I have code that is inserting HTML before a child in an Element. I have found a case where the node that has a child causes the exception "**java.lang.IndexOutOfBoundsException: Index: 0, Size: 0**" on the reference to the Jsoup call Element.child(0). The code snippet where this occurs follows:

`topNode.child(0).before(strHtml)
`

Where topNode is a `<span>` Element containing a `<p>` child as follows:

topNode:
 `<span style="font-family: Trebuchet MS, sans-serif"><p> Catilina, qualora si riunirono i partecipanti alla complotto, benché avesse realizzato per mezzo di ciascuno di loro molti fatti, preferendo ciononostante convocarli tutti e volendo incitarli, si ritirò in una parte celata dell’edificio e lì, allontanati tutti gli estranei, tenne un discorso: “Poiché in molte ed importanti occasioni vi ho conosciuti come fortissimi ed a me fedelissimi, il mio animo ha voluto dare inizio ad una enorme e bellissima impresa, anche perché ho compreso che anche per voi sono buone o cattive le cose come lo sono per me; infatti volere e non volere le stesse cose indica una salda amicizia. Dopo che lo stato è caduto sotto il comando e la brutalità di pochi potenti, sempre ogni grazia, potenza, onore, ricchezze si possono trovare presso di loro o dove essi vogliono. Non preferirete condurre una vita tramite la virtù o piuttosto perdere una vita povera e vergognosa attraverso il disonore? La vittoria è nelle nostre mani, è salda nell ‘età, l’animo è saldo e vuole; a loro al contrario per mezzo di gli anni e le ricchezze tutto si è indebolito. A loro avanzano le ricchezze, a noi manca il patrimonio anche per il necessario: un uomo, che possiede un’intelligenza forte, non può sostenere ciò. Ora codesta, codesta libertà che avete sempre voluto, oltre a ricchezze, decoro, gloria sono riposti nei vostri occhi; la sorte ha offerto tutti quei premi ai vincitori. Usatemi come volete, come capo o come soldato semplice: né l’animo né il corpo saranno lontani da voi. Tali stesse cose, come spero, farò per mezzo di voi come console, a meno che per caso mi manchi il coraggio e preferiate che vi obbedisca/serva piuttosto che comandarvi”.</p></span>`

And strHTML can be any HTML or an empty string. The reference to **topNode.child(0)** throws the error before the method **Element.before()** is called.

**This does not occur using Jsoup 1.10.2.**

The exception also has occurred with different HTML in 1.10.3 with the **Element.after()** method in the case of appending the HTML as a following sibling. 

`topNode.child(0).after(strHtml)`

The following is the exception stacktrace:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at org.jsoup.nodes.Element.child(Element.java:214)
	at ContentExt.addSiblings(ContentExt.scala:943)

```

**Comment by mccxj** [comment]
@adxBRudolph 
it works fine, whether it is 1.10.3 or not.
```java
Element root = (Element) doc.select("span").first();
System.out.println(root.child(0));
```

**Comment by adxBRudolph** [comment]
Odd. I swap out the library and restest with the same data and get the exception.

**Comment by jhy** [comment]
I can't replicate either. Can you provide environment details and a testcase?

**Comment by jhy** [comment]
Please reopen if you can find a [test case](https://stackoverflow.com/help/mcve) that repros.
