### ISSUE TITLE
Custom mime-type for file upload?

### ISSUE THREAD

**Issue by Rukifox** [jhy/jsoup#936]
Can not set mime type for file in Response, there is something like this? Not global Content-Type, only for file:

`.data("file", file.getName(), new FileInputStream(file), "image/jpeg");`

Because i have problem with default type "application/octet-stream", it doesn't approach all requests like on www.captionbot.ai/, when i'm trying to upload file using api for recognizing, server returns 500th error.

**Comment by goforbroke1006** [comment]
Hi @Rukifox 
What version of jsoup are you using?

**Comment by Rukifox** [comment]
1.10.3

**Comment by jhy** [comment]
Thanks, implemented with 4685bd091a690e219e629687bf84cc6f752eff81
