### ISSUE TITLE
Impossible to extend from default Whitelists

### ISSUE THREAD

**Issue by KazimirPodolski** [jhy/jsoup#937]
There is no way (as far as I understand) to extend from Whitelist but reuse settings of one of default whitelists (I mean basic, relaxed, etc.).

It would be nice have cloning method in Whitelist class or at least public getters for tags, attributes and the rest.

**Comment by cketti** [comment]
`Whitelist` is mutable. You can e.g. do

```java
Whitelist myWhitelist = Whitelist.basic().addTags("blink");
```

`Whitelist.basic()` and others create new instances. So doing the above won't change what future calls to `Whitelist.basic()` will return.

**Comment by spontaliku-softaria** [comment]
But I can't extend from Whitelist and get instance of my class with tags and attributes from one of default whitelists. I have to copy-paste implementation:
```java
public class MyWhitelist extends Whitelist {
// my methods
}
```
```java
public static MyWhitelist basic() {
        return (MyWhitelist) new MyWhitelist()
                .addTags(
                        "a", "b", "blockquote", "br", "cite", "code", "dd", "dl", "dt", "em",
                        "i", "li", "ol", "p", "pre", "q", "small", "span", "strike", "strong", "sub",
                        "sup", "u", "ul")
                .addAttributes("a", "href")
                .addAttributes("blockquote", "cite")
                .addAttributes("q", "cite")
                .addProtocols("a", "href", "ftp", "http", "https", "mailto")
                .addProtocols("blockquote", "cite", "http", "https")
                .addProtocols("cite", "cite", "http", "https")
                .addEnforcedAttribute("a", "rel", "nofollow");
    }
```

**Comment by cketti** [comment]
Sorry, I probably misunderstood what you're trying to achieve. Can you describe your use case? Why do you want to create a sub class of `Whitelist`?

**Comment by spontaliku-softaria** [comment]
I want to escape unsafe tags instead of remove them. I extend from Whitelist to make isSafeTag and isSafeAttribute public, then I traverse Document modifying all nodes based on Whitelist.

I also have cases where default behaviour (delete unsafe) is fine, so I'd like to use Whitelist as intented and also as a source of information about safe/unsafe tags.

**Comment by cketti** [comment]
Sounds to me like you want `isSafeTag()` and `isSafeAttribute()` be public in jsoup rather than extending `Whitelist`. I think that's a reasonable request.

**Comment by spontaliku-softaria** [comment]
Yes, that would do the trick too.
Anyway, why don't make public getters for tags and attributes? It won't harm normal usage, but would allow "strange" cases like mine to be implemented without your concern.

**Comment by msamborskiorbis** [comment]
I am also looking to override isSafeAttribute which I can't do while it is protected. I want to allow embed with an src only matching a regex and style as a attribute on all tags but specific styles.

**Comment by jhy** [comment]
Thanks for the discussion. I added an example in 6a047bfe495d4c8ae827c9522fbf3fa525d8fdd7 confirming that it is extensible as described.
