### ISSUE TITLE
JSOUP - Memory leak when parsing a big html file

### ISSUE THREAD

**Issue by guyalizi** [jhy/jsoup#938]
When trying to use the parse command with a big html input 
org.jsoup.nodes.Document doc = Jsoup.parse(bigHtml);
html size around = 25MB
The Java host process memory usage is increasing dramatically and the Garbage Collector does  not collect 
JSOUP objects.

JSOUP version : 1.10.3

**Comment by jhy** [comment]
There's a big change for document parse sizes in 1.11.1. You can build it from head until it's released.
