### ISSUE TITLE
Detect Circular redirects in case while trying to get Jsoup connect

### ISSUE THREAD

**Issue by amit2103** [jhy/jsoup#940]
What happens whan we try to get document with the following code?

Document document = Jsoup.connect(siteConnection.getURL().toString()).userAgent(USER_AGENT).get();

I am worried in case of circular redirects what will happen ? Does Jsoup keep on following the links ?

Thanks for the help

**Comment by jhy** [comment]
Yes, there's a redirect counter. Test is here - https://github.com/jhy/jsoup/blob/cde6403a3c881403a7cf06f4d7d087464038daf6/src/test/java/org/jsoup/integration/UrlConnectTest.java#L367
