### ISSUE TITLE
Html tree builder breaks web component templates inside tables

### ISSUE THREAD

**Issue by gar1t** [jhy/jsoup#941]
Jsoup surprisingly moves certain elements outside a table. I'm not sure why it does that in the first place, but it prohibits the use Jsoup of web components (e.g. Polymer), at least within the context of tables.

Here's an illustration:

https://try.jsoup.org/~O6KWXgQN6DLCJ2prct4RhnahPdI

Note that `template`, which wraps the `tr` element, is moved outside `table`. This breaks the component.

A couple questions:

- Why does the parser take such a strong approach with the DOM? The insertion and moving of tags is quite impacting, esp wrt to CSS or other selectors that rely on the structure provided.

- Is there a straight forward way to disable this behavior? I'll start down the path of providing my own tree builder (subclassing HtmlTreeBuilder I imagine) but I thought I'd raise this issue here to get some feedback first.

**Comment by cketti** [comment]
Jsoup implements the HTML5 specification which includes detailed instructions on how to parse HTML and create a DOM from it.
What you are trying to parse is not HTML. It's a template language that can contain HTML. You could try parsing it as XML if you want to avoid application of the HTML parsing rules.

**Comment by gar1t** [comment]
My apologies, I just notices my issue is a dup of #600.

My use case is exactly the same as the Closure team. This is also impacting TensorBoard. 

I'll comment on the other issue - please feel free to close this as dup.

**Comment by jhy** [comment]
Thanks, this is fixed with #901
