### ISSUE TITLE
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by wilburt** [jhy/jsoup#945]
`Document document = Jsoup.parse(response.string());` is throwing up this:
> >A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
>                                                                    java.lang.Throwable: Explicit termination method 'end' not called
>                                                                        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
>                                                                        at java.util.zip.Inflater.<init>(Inflater.java:82)
>                                                                        at java.util.zip.ZipFile.getInputStream(ZipFile.java:331)
>                                                                        at java.util.jar.JarFile.getInputStream(JarFile.java:390)
>                                                                        at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
>                                                                        at java.net.URL.openStream(URL.java:470)
>                                                                        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
>                                                                        at java.lang.Class.getResourceAsStream(Class.java:1452)
>                                                                        at org.jsoup.nodes.Entities.load(Entities.java:299)
>                                                                        at org.jsoup.nodes.Entities.access$000(Entities.java:25)
>                                                                        at org.jsoup.nodes.Entities$EscapeMode.<init>(Entities.java:53)
>                                                                        at org.jsoup.nodes.Entities$EscapeMode.<clinit>(Entities.java:42)
>                                                                        at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:372)
>                                                                        at org.jsoup.nodes.Document.<init>(Document.java:19)
>                                                                        at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:32)
>                                                                        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:42)
>                                                                        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:56)
>                                                                        at org.jsoup.parser.Parser.parse(Parser.java:100)
>                                                                        at org.jsoup.Jsoup.parse(Jsoup.java:58)
>                                                                        at com.maggy.blog.posts.providers.Blog.fromURL(Blog.java:76)
>                                                                        at com.maggy.blog.posts.providers.Blog.fromMetaData(Blog.java:58)
>                                                                        at com.maggy.blog.posts.PostsDownloadThread$1.download(PostsDownloadThread.java:80)
>                                                                        at com.maggy.blog.posts.PostsDownloadThread$1.run(PostsDownloadThread.java:53)
>                                                                        at java.lang.Thread.run(Thread.java:818)

And `Document` seems not to have any `close()` or `end()` method.

Is this a false alarm?

**Comment by jhy** [comment]
This is fixed by #928
