### ISSUE TITLE
Retaining line breaks in Jsoup.clean

### ISSUE THREAD

**Issue by geraldbostock77** [jhy/jsoup#946]
Line breaks are not always preserved by Jsoup.clean() (pretty print on) if portions of the HTML are surrounded by `<p>` tags. E.g. take the following:
```

   final static Whitelist      whitelistBreaksAndParagraphs = Whitelist.none().addTags("br", "p");
   final static OutputSettings prettyPrintOn                = new OutputSettings().prettyPrint(true);

   public static String cleanHtml(final String html)
   {
      final Document doc = Jsoup.parse(html);
      doc.outputSettings().indentAmount(0).prettyPrint(false);

      String cleanedHtml = Jsoup.clean(doc.toString(), "", whitelistBreaksAndParagraphs, prettyPrintOn);
      return cleanedHtml;
   }
```
Input       = `<p>Line 1<br>Line 2<br>Line 3</p>`

Expected =
```
<p>Line 1
<br>Line 2
<br>Line 3</p>
```
Actual = `<p>Line 1<br>Line 2<br>Line 3</p>`

By contrast, if the same input is passed in but without any `<p>` tags, then line breaks are preserved as expected.

**Comment by geraldbostock77** [comment]
Hi, any update on this? Have a customer who is impacted by this (time-sensitive) and would like to provide them a status update ASAP.

Thanks!

**Comment by geraldbostock77** [comment]
@jhy Please let me know if need more info/cannot recreate. Unfortunately customer is severely impacted by this regularly.

**Comment by jhy** [comment]
Sorry for the late reply. This is the expected behavior for now as that's considered non-significant whitespace in HTML (i.e. it renders the same)
