### ISSUE TITLE
removeClass on Element leaves/adds empty class tags

### ISSUE THREAD

**Issue by blacktoby** [jhy/jsoup#947]
Hey,
when I remove the only class from an element, it leaves an empty class tag behind. 
This behavior could be expected, but: When I remove a class on an element, which does not have a class, it adds empty class tags.

Example HTML:
```html
<table> <tbody> <tr> test </tr> </tbody> </table>
```

I parse this to Elements and do:
```java
elements.removeClass("testClass");
```

and get:
```html
<table class=""> <tbody class=""> <tr class=""> test </tr> </tbody> </table>
```

My suggestion to fix this in Element Class, avoid empty class tags:
``` java
public Element classNames(Set<String> classNames) {
        Validate.notNull(classNames);
        if(!classNames.isEmpty()){
               attributes.put("class", StringUtil.join(classNames, " "));
        }
        return this;
    }
```

Toby

**Comment by krystiangorecki** [comment]
`classNames(Set<String> classNames)` works like a setter so your change would make it impossible to remove the last class.

**Comment by krystiangorecki** [comment]
pull request https://github.com/jhy/jsoup/pull/963

**Comment by blacktoby** [comment]
Thanks for solving the issue!

**Comment by jhy** [comment]
Thanks!
