### ISSUE TITLE
Url is not redirecting

### ISSUE THREAD

**Issue by prasanna532** [jhy/jsoup#949]
Actually iam having issue trying from past one week i dint got solution

First iam having url like www.example.com\search?q=test after hitting that url it redirect some results page or if any results are not there it will redirect another page like www.example.com\noresults page

Now the problem statement is if we request the url  like below url redirection is not happening if there are no results. Is this a Bug? or is there any way to check.

Connection.Response loginForm = Jsoup.connect("https://www.example.com\search?q=test").method(Connection.Method.GET)
                .ignoreContentType(true)
                .userAgent(
                        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36")
                .followRedirects(true).execute();

**Comment by jhy** [comment]
Can you provide the real code (including the site)? It looks like a server specific issue, so that's needed to debug.
