### ISSUE TITLE
Line Breaks And Comments Not Preserved Correctly Outside <body>

### ISSUE THREAD

**Issue by apptaro** [jhy/jsoup#957]
Line breaks and comments are not preserved correctly, see below.
Tested with Jsoup 1.10.3

Test Code:
```
String html = "<!DOCTYPE html>\n" //
	+ "<!-- before html -->\n" //
	+ "<html>\n" //
	+ "<!-- before head -->\n" //
	+ "<head>\n" //
	+ "<!-- inside head -->\n" //
	+ "</head>\n" //
	+ "<!-- after head -->\n" //
	+ "<!-- before body -->\n" //
	+ "<body>\n" //
	+ "<!-- inside body -->\n" //
	+ "</body>\n" //
	+ "<!-- after body -->\n" //
	+ "</html>\n" //
	+ "<!-- after html -->\n";

Document doc = Jsoup.parse(html);
doc.outputSettings().prettyPrint(false);

System.out.println("---------------------------");
System.out.println(html);
System.out.println("---------------------------");
System.out.println(doc.html());
```

Output:
```
---------------------------
<!DOCTYPE html>
<!-- before html -->
<html>
<!-- before head -->
<head>
<!-- inside head -->
</head>
<!-- after head -->
<!-- before body -->
<body>
<!-- inside body -->
</body>
<!-- after body -->
</html>
<!-- after html -->

---------------------------
<!doctype html><!-- before html --><html><!-- before head --><head>
<!-- inside head -->
</head>
<!-- after head -->
<!-- before body -->
<body>
<!-- inside body -->

<!-- after body -->

<!-- after html -->
</body></html>
```

**Comment by jhy** [comment]
Depending on their context, line-breaks generally don't impact the text flow, so jsoup normalizes them by default. You can disable pretty-printing in the output to get closer to the original text - but that's not what jsoup is about.

**Comment by apptaro** [comment]
@jhy thank you for your response. Let me add some explanation for this. First, I am talking about the case with pretty-printing disabled so to get the output closer to the original. Second, please look closer to the output, then you see the positions of comments are wrong for  and . Comment positions are crucial because some tools use comments to mark things. For example, Adobe DreamWeaver uses  to mark library items, and  to mark used templates. So I wish Jsoup will output them correctly.
