### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by realxz** [jhy/jsoup#959]
**Jsoup version is jsoup-1.10.3**
This is My way, in AsyncTask#doInBackground，you can see the red part
![image](https://user-images.githubusercontent.com/8953156/32096201-5b9669c6-bacb-11e7-81ea-a167d425aff3.png)
![image](https://user-images.githubusercontent.com/8953156/32096264-8a1b79a8-bacb-11e7-8ee0-d3868159b67b.png)

java.lang.RuntimeException:An error occured while executing doInBackground()
--
2 android.os.AsyncTask$3.done(AsyncTask.java:304)
3 ......
4 Caused by:
5 java.util.ConcurrentModificationException:
6 java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
7 java.util.HashMap$KeyIterator.next(HashMap.java:814)
8 java.util.jar.JarVerifier.readCertificates(JarVerifier.java:266)
9 java.util.jar.JarFile.getInputStream(JarFile.java:380)
10 libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
11 java.net.URL.openStream(URL.java:470)
12 java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
13 java.lang.Class.getResourceAsStream(Class.java:1368)
14 org.jsoup.nodes.Entities.load(Entities.java:299)
15 org.jsoup.nodes.Entities.access$000(Entities.java:25)
16 org.jsoup.nodes.Entities$EscapeMode.<init>(Entities.java:53)
17 org.jsoup.nodes.Entities$EscapeMode.<clinit>(Entities.java:34)
18 org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:372)
19 org.jsoup.nodes.Document.<init>(Document.java:19)
20 org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:32)
21 org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:42)
22 org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:56)
23 org.jsoup.parser.Parser.parseInput(Parser.java:32)
24 org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:140)
25 org.jsoup.helper.DataUtil.load(DataUtil.java:47)
26 org.jsoup.Jsoup.parse(Jsoup.java:103)
27 com.tomkey.commons.tools.FileUtil.getFileWithLocalPic(FileUtil.java:159)

**Comment by jhy** [comment]
Looks like the getResourceAsStream implementation on Android is a bit crappy; slow and sensitive to CMEs if multiple threads are hitting it at once.

See other examples: 

- https://www.bountysource.com/issues/43155478-allow-for-alternate-metadatamanager-implementations 
- http://blog.nimbledroid.com/2016/04/06/slow-ClassLoader.getResourceAsStream.html
- https://github.com/googlei18n/libphonenumber/issues/606
