### ISSUE TITLE
html parse with Jsoup failed but pyquery is OK

### ISSUE THREAD

**Issue by clevertang** [jhy/jsoup#960]
url:http://www.sepb.gov.cn/fa/cms/shhj//shhj5180/shhj5185/shhj5267/2017/07/96593.htm
when parse the td like pic 
![1509351283947](https://user-images.githubusercontent.com/22960168/32160635-82c4de3c-bd8d-11e7-8908-68ad3d6e928e.jpg)
java code as below:
package Parse;

import http_utils.Send;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author tangxin
 * Date 2017/10/26
 */
public class www_sepb_gov_cn {

    private final static String HOTS = "http://www.sepb.gov.cn";
    private final static String TUBE = "offline_crawl_data";

    public static void parseContent(String targetStr, String url) {
        int billingIndex;
        String company;
        String billing_money;
        Document doc = Jsoup.parse(targetStr);
        String received_money;
        String year_quarter;
        String publish_time = doc.select("td.detDate").text();
        publish_time = publish_time.split(":")[1];
        String title = doc.select("div#ivs_title").text();
        year_quarter = getQuarter(title);
        if (title.contains("一")) {
            billingIndex = 2;
        } else if (title.contains("二")) {
            billingIndex = 3;

        } else if (title.contains("三")) {
            billingIndex = 6;
        } else if (title.contains("四")) {
            billingIndex = 6;
        } else {
            return;
        }
        Elements name = doc.select("div#ivs_content").select("tr");
        ArrayList<String> note = new ArrayList<String>();
        int flag = 0;
        int end;
        if (name.size() == 151) {
            end = name.size() - 3;
        } else {
            end = name.size() - 1;
        }
        for (int i = 0; i < end; i++) {
            Map<String, String> result = new HashMap<String, String>();
            String collection_institutions = name.eq(i).select("td").eq(0).text();
            if (collection_institutions.contains("征收")) {
                continue;
            }
            if (collection_institutions.contains("开单")) {
                continue;
            }
            if (collection_institutions.length() > 3) {
                note.add(collection_institutions);
                flag += 1;
                company = name.eq(i).select("td").eq(2).text();
                billing_money = name.eq(i).select("td").eq(billingIndex + 1).text();
                received_money = name.eq(i).select("td").eq(billingIndex + 2).text();
            } else {
                collection_institutions = note.get(flag - 1);
                company = name.eq(i).select("td").eq(1).text();
                billing_money = name.eq(i).select("td").eq(billingIndex).text();
                received_money = name.eq(i).select("td").eq(billingIndex + 1).text();
            }
            result.put("_site_record_id", company + year_quarter);
            result.put("topic", "environment_protection_information");
            result.put("collection_institutions_phone_number", "");
            result.put("publish_time", publish_time);
            result.put("url", url);
            result.put("title", title);
            result.put("year_quarter", year_quarter);
            result.put("collection_institutions", collection_institutions);
            result.put("company", company);
            if ("149,146,907.00".equals(company)) {
                continue;
            }
            result.put("billing_money", billing_money);
            result.put("received_money", received_money);
            if (year_quarter.contains("2017")) {
                Send.send(result, TUBE);
            }
        }
    }

    public static ArrayList<String> parseList(String targetStr) {
        ArrayList<String> sublinks = new ArrayList<String>();
        Document doc = Jsoup.parse(targetStr);
        Elements links = doc.select("ul.ascend_ul").select("a");
        for (Element link : links) {
            String href = link.attr("href");
            href = HOTS + href;
            sublinks.add(href);
        }
        return sublinks;

    }

    private static String getQuarter(String title) {
        Pattern p = Pattern.compile("(\\d.*)季度");
        Matcher m = p.matcher(title);
        while (m.find()) {
            title = m.group();
        }
        return title;
    }
}
and here is one test demo with python package pyquery
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     test_package
   Description :
   Author :       tangxin
   date：          2017/10/30
-------------------------------------------------
   Change Activity:
                   2017/10/30:
-------------------------------------------------
"""
import sys
from pyquery import PyQuery

__author__ = 'tangxin'
reload(sys)
sys.setdefaultencoding("utf8")
import requests

session = requests.session()
url = "http://www.sepb.gov.cn/fa/cms/shhj//shhj5180/shhj5185/shhj5267/2017/07/96593.htm"
resp = session.get(url)
result = PyQuery(resp.text, parser='html')

all_notes=result.find("div#ivs_content").find("tr")
for i in xrange(len(all_notes)):
    billing_money = all_notes.eq(i).find("td").eq(4).text()
    received_money = all_notes.eq(i).find("td").eq(5).text()
    print billing_money+"+++++"+received_money

**Comment by clevertang** [comment]
contact 961577196@qq.com please,if you need source code

**Comment by krystiangorecki** [comment]
What does it mean "parse with Jsoup failed"? What's the result? Have you tried debugging?
How do you invoke method parseContent(String targetStr, String url)?
I'm debugging your code and it works fine. After second iteration of for loop the result is:

```{received_money=759,120.00, publish_time=[2017-07-21], year_quarter=2017年第二季度, topic=environment_protection_information, company=宝钢不锈钢有限公司, title=上海市国家重点监控企业2017年第二季度排污费征收公告, collection_institutions_phone_number=, collection_institutions=上海市24011641, billing_money=758,096.60, _site_record_id=宝钢不锈钢有限公司2017年第二季度, url=http://www.sepb.gov.cn/fa/cms/shhj//shhj5180/shhj5185/shhj5267/2017/07/96593.htm}```

And these values are we see on your picture.

**Comment by clevertang** [comment]
thanks for your kind response.
the problem is caused by my datasaver,parse is right,but data in mongodb have some problem.
