### ISSUE TITLE
document don`t get all the html when the page is big

### ISSUE THREAD

**Issue by songdaohan** [jhy/jsoup#961]
[String url ="https://gcc.gnu.org/bugzilla/buglist.cgi?product=gcc&component=tree-optimization&resolution=---&limit=0&order=priority%2Cbug_severity&query_format=advanced";
Document doc = Jsoup.connect(url).get();
Elements bugs = doc.select("tr.bz_bugitem");](url)

There are 1081 trs in the page, but 'bugs' only return 946 of them. I check the variable doc in the eclipse,which show that doc  don`t get all the html of the page.

**Comment by jhy** [comment]
https://jsoup.org/apidocs/org/jsoup/Connection.html#maxBodySize-int-

Default is 1 MB, so your document input is getting cropped (because the doc is 1.3MB).
