### ISSUE TITLE
API changes analysis report for jsoup

### ISSUE THREAD

**Issue by lvc** [jhy/jsoup#962]
Hi,

I'd like to share report on API changes and backward compatibility for the jsoup library: https://abi-laboratory.pro/java/tracker/timeline/jsoup/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Auto-updated report in Json format: https://github.com/lvc/api-reports-4j/blob/master/report/jsoup.json

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jsoup-1](https://user-images.githubusercontent.com/1517837/32311341-2a6ff956-bfa9-11e7-97dd-9c0d61fc956d.png)

![jsoup-2](https://user-images.githubusercontent.com/1517837/32311340-2a407578-bfa9-11e7-80b4-afa64f99fb47.png)

**Comment by jhy** [comment]
Thanks, interesting
