### ISSUE TITLE
Malformed html

### ISSUE THREAD

**Issue by visox** [jhy/jsoup#964]
Hi, i am using happily jsoup and it works most of the time.

There is one page that gives me malformed html, first my code (scala):

```
  val con = Jsoup.connect(url)

  val userAgent = StatefulRecoverJsoupBrowser.randomUserAgent()
  con.headers(StatefulRecoverJsoupBrowser.headers(userAgent).asJava)
  con.userAgent(userAgent)
  con.followRedirects(true)
  con.validateTLSCertificates(true)
  con.ignoreHttpErrors(true)
  con.ignoreContentType(true)
  con.cookies(lastCookies.asJava)
  con.referrer(referrer)
  proxy.map(_.toProxy).foreach(con.proxy)
  con.timeout(connectionTimeout.toMillis.toInt)

  val r = con.execute()
```

for url = "https://www.mountfield.sk/elektricky-vertikutator-levita-s-1400-1zst2046"

it gives me this as a result

```
<html>
 <head></head>
 <body>
  �Is�0z�2���ͮ.IOLb'-��&amp;��*��$���"3@"�H��n���4fo�}�wx�\�Ͼ:����a�TfU�d~�s�\� $@�D����23w_"&lt;&lt;��a�p���Ѧ�t }囯�ῂ�Q��|,�
  <suw���m�j����w̗ o�6�]u�\x̗����h[u�pr�lv����<ӭ�tw�݌��3�b�il���^��+
                                                                  bfe������дi��bf}�vd��lq��:̳e�d������ѩӥ�5�a���x܎e� ����ȏ� �t�� ��{���
                                                                                                                                     m��[�v��.5�suq��@d�"xtsuu���lt�<��] r���z<����h�b)�q��ztw����w�l��+8���x��n�_r�j{����3~�q5�x#�ѡ�j>
   x�V�3���LME��E�)F�I�ub���B/�:�uv��,O&lt;���X��e��P�8.5�,9Kõ�5t*:�KE�����U�kg���a��ă���j�(Wk������i���7�+�g�[��Z�~�0M׵�'����K�rUC�R��$3#�r2�r!��䪹|�0,W'0��\��BVR ��̅��Cv�]�s�n�o'k�_7�"ƹ-�&amp;�[d�Lo}c�d���|�&amp;������������&lt;2a��Z8! a��г���Q�%�s������K'��',�)�� ���?�������"K;&gt;wV;�g������hK�T�J���ĥ fwxE���r~���m�a�������v��T�������6�8�5_�z�M�(d�c&gt;�"�w �3TE")��)��Aq/��
                                             �籹7�T�� @2�����I �����m�ɺ�$�^_����׷F�ۺ� \����A�\����׃�=ˠ��7S:���y��wr,�vk�º?����*��c � �t2YضZ�A|�/s~~��
                                                                                                                                                     �4 � �ᦳ���{�Y['����QmoAhR��ɒ]|���8��/(�c���d&amp;}�VURu��
   <i��bm~��#'���úg�(���狂�(8��j���o�>
    ��� �'���;`�o�~�p�%�%6��7_��\��z�h�A�`ۇ�&gt;`�`і�������:Nz, \��u���C�џ�Y���/"�Z J�7S����h=�|�? &lt;�O�ყB
....
```

now i tried to play with the charset but it did not help

i am using jsoup 1.10.3

if i call the url in postman i actually get proper html, i am really not sure what is the problem here

**Comment by jhy** [comment]
Hi,

I haven't been able to replicate this problem. The page is being served as UT8 and that's set in the response headers, so I didn't see anything unusual. Works out of the box with the default settings; e.g. https://try.jsoup.org/~KeKq-HPJ8DDmvtC5zrHbL2Z-AH0

What jsoup version, and what platform are you on?

Maybe one of your random UAs, or your proxy, is creating problems?

Could you paste a complete small testcase we can validate?

**Comment by visox** [comment]
So i guess the "problem" are proxies, i tried remove each setting till it worked and the problem are indeed proxies.

But i am not sure why, like mentioned my solution works for every other page but not mountfield, its a mystery so far.

Anyway the problem is probably not jsoup so this issue can be closed.

**Comment by krystiangorecki** [comment]
Seems like the response you're getting is compressed. Maybe that's some issue with proxy dropping headers so the client doesn't know it's encoded.
It's not charset you should be looking at. Try setting different encodings using `Accept-Encoding` request header. `Accept-Encoding: identity` may force server to return uncompressed response so you can check if that was the problem. Maybe you'll find some other value that will be passed by proxy and correctly decoded by client.

**Comment by visox** [comment]
thx i will try that.

**Comment by jhy** [comment]
Will close this as an integration issue. Thanks for the pointer @krystiangorecki, was thinking along similar lines. 

Please feel free to reopen if something points to a jsoup bug or workaround opportunity.

**Comment by visox** [comment]
Btw, `Accept-Encoding: identity` worked, so thx

**Comment by krystiangorecki** [comment]
I just want you to know the consequence of that. When using `identity` the data is transferred without compression. Your example page is 743 kB. If you use `deflate` it is compressed to 145 kB. You save 80% of bandwidth and time so it's worth to experiment if you plan to download and parse maaany pages.

**Comment by jhy** [comment]
If there's a proxy in the way doing something weird with gzip, won't it do the same to deflate?

Actually that makes me wonder - what if the proxy is actually asking for deflate instead of gzip, and passing that back to jsoup? Jsoup doesn't currently handle deflate.

Would be great @visox if you could capture wire logs on both sides: jsoup <-> proxy and proxy <-> server. Then we'd know what's happening for sure and could address.

**Comment by krystiangorecki** [comment]
Actually, what's stopping us from supporting `deflate`? I successfully used InflaterInputStream before and that's the solution proposed a long time ago in #556.
