### ISSUE TITLE
Attribute parsing drops a character on buffer boundary

### ISSUE THREAD

**Issue by jpsrn** [jhy/jsoup#967]
Version 1.11.1 does not handle attribute value parsing correctly when attribute value extends through the end of the character buffer (32768 characters). Jsoup will drop the next character to be read after a buffer refill.

Here's a simple code snippet reproducing the bug. The character X is dropped by jsoup.

```
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public class JsoupRepro {

    public static void main(String[] args) {

        final String preamble = "<img src=\"data:image/png;base64,";
        final StringBuilder builder = new StringBuilder(preamble);

        final int charsToFillBuffer = 1024 * 32 - preamble.length();
        for (int i = 0; i < charsToFillBuffer; i++) {
            builder.append('a');
        }

        builder.append('X'); // First character to cross character buffer boundary
        builder.append("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\" />\n");

        final String inputHtml = builder.toString();
        final Document parsedOutput = Jsoup.parse(inputHtml);

        final String imgSource = parsedOutput.select("img").attr("src");

        System.out.println("Parsed imgSrc contains character X: " + imgSource.contains("X"));
        System.out.println(parsedOutput);
    }
}
```

**Comment by kvirkki** [comment]
The previous release 1.10.3 doesn't seem to have this issue, so it's introduced in 1.11.1, it seems.

**Comment by inacioboueres** [comment]
I faced the same problem in the version1.11.1 and so was forced to rollback the version

**Comment by jhy** [comment]
Thanks for finding this and for isolating the problem. Fixed now for each attribute value type (double, single, unquoted). I still need to do another pass through the Tokeniser and make sure there are no default reads that pass through, now that the input is buffered.

(Which it wasn't in 1.10.3, which is why the issue doesn't appear there.)
