### ISSUE TITLE
Entities.canEncode() with non-fast-path encoding is not thread safe on Android (jsoup 1.11.1)

### ISSUE THREAD

**Issue by baka-kaba** [jhy/jsoup#970]
(This crash doesn't occur on 1.10.3 or 1.10.2)

I'm pulling a list of elements from a document and using several threads to parse them, but when I call ``Element.html()`` I get this exception

``
System.err: Caused by: java.lang.IllegalStateException: Current state = CODING_END, new state = CODING
System.err:     at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:1014)
System.err:     at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:923)
System.err:     at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:973)
System.err:     at org.jsoup.nodes.Entities.canEncode(Entities.java:298)
System.err:     at org.jsoup.nodes.Entities.escape(Entities.java:233)
System.err:     at org.jsoup.nodes.Attributes.html(Attributes.java:323)
System.err:     at org.jsoup.nodes.Element.outerHtmlHead(Element.java:1328)
System.err:     at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:709)
System.err:     at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:45)
System.err:     at org.jsoup.nodes.Node.outerHtml(Node.java:573)
System.err:     at org.jsoup.nodes.Element.html(Element.java:1366)
System.err:     at org.jsoup.nodes.Element.html(Element.java:1360)
System.err:     at com.testapp.JsoupMultithreadedTest$ParseTask.call(JsoupMultithreadedTest.java:49)
System.err:     at com.testapp.thread.JsoupMultithreadedTest$ParseTask.call(JsoupMultithreadedTest.java:39)
System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
System.err:     at java.lang.Thread.run(Thread.java:764)
``

The state can vary, I've also seen ``END_OF_INPUT`` and ``RESET``.

Here's an example that displays the behaviour on Android - it seems to work fine on my Windows 10 machine, but crashes every time on an Android device (Android 6.0.1) and emulator (Android 8.0). The site's encoding [is apparently](https://validator.w3.org/nu/?doc=https%3A%2F%2Fforums.somethingawful.com%2F) ``Windows 1252`` even though the content type is set as ``iso-8859-1``. Works fine with a single thread, and you can run it multithreaded on ``1.10.3`` with no problems.

```java
public class JsoupMultithreadedTest {

    private static final String pageUrl = "https://forums.somethingawful.com";
    private static final ExecutorService executor = Executors.newFixedThreadPool(2);

    public static void run() throws IOException, InterruptedException, ExecutionException {
        Document document = Jsoup.connect(pageUrl).get();
        Elements headlines = document.select(".forum");

        List<Callable<String>> tasks = new ArrayList<>();
        for (Element headline : headlines) {
            tasks.add(new ParseTask(headline));
        }

        for (Future<String> result : executor.invokeAll(tasks)) {
            System.out.println(result.get());
        }
    }

    private static class ParseTask implements Callable<String> {

        private final Element rootElement;

        private ParseTask(Element rootElement) {
            this.rootElement = rootElement;
        }

        @Override
        public String call() throws Exception {
            return rootElement.html();
        }
    }
}
```

**Comment by jhy** [comment]
Thanks. The solution is probably to put the encoder (which is present in the document and created on the html visit) into a ThreadLocal. I didn't consider that users would be serializing the same document concurrently.

As a workaround you should be able to do a document.clone() before serializing.

**Comment by baka-kaba** [comment]
I actually started parallelising it because I was profiling an app, and I saw the ``html()`` calls were taking a long time, so I wanted to try and reduce the delay the users are seeing when fetching and parsing a page. Now I've dug through the jsoup code, it's obviously the encoding that's the real problem (non-utf-8 so it's taking the slow path), but yeah - that was the motivation

I've tried your multiple Document approach and that works out, still a 2-3x speedup over single-threaded, thanks!

**Comment by jhy** [comment]
https://encoding.spec.whatwg.org/#names-and-labels defines that iso-8859-1 is an alias for Windows-1252 (because historically so many authors used the former when they meant the latter, I guess.) Should update jsoup to apply that alias, as well.

**Comment by jhy** [comment]
(Just to confirm I can replicate the issue on Android on this site.)

**Comment by jhy** [comment]
OK, this is fixed now.

It would be good to add 1252 to the fast encode path. Need to work out the relevant unicode ranges from http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT and implement a can encode for them.
