### ISSUE TITLE
StringIndexOutOfBoundsException as of jsoup 1.11.1

### ISSUE THREAD

**Issue by valodzka** [jhy/jsoup#972]
Example:

    Jsoup.parse(new URL("https://gist.githubusercontent.com/valodzka/91ed27043628e9023009e503d41f1aad/raw/a15f68671e6f0517e48fdac812983b85fea27c16/test.html"), 10_000);

**Comment by krystiangorecki** [comment]
No wonder as this document is not complete. That's just the first 64kB (65536 bytes) of data, and the last line is 
```
       <!
```

**Comment by jhy** [comment]
Thanks for the report! Fixed.
