### ISSUE TITLE
java.net.SocketException: Connection reset?

### ISSUE THREAD

**Issue by TonyJason** [jhy/jsoup#975]
![image](https://user-images.githubusercontent.com/15902558/32844236-d17c2c8e-ca5c-11e7-85b6-140ebd85a15b.png)
![image](https://user-images.githubusercontent.com/15902558/32844276-f2ce0b1e-ca5c-11e7-84c8-4ed7f9432ca1.png)
What should I do?

**Comment by jhy** [comment]
I'd suggest using StackOverflow for suggestions on this. Let's keep this site for jsoup bug tracking. 
You'll want to provide a [minimal test](https://stackoverflow.com/help/mcve) case so people can replicate (including environment and URL details.)
