### ISSUE TITLE
how to custom testValidProtocol method

### ISSUE THREAD

**Issue by yangjiacheng** [jhy/jsoup#979]
i use summernote Super Simple WYSIWYG editor, it create video tag is <iframe src="//play....."> , src arrtibute protocol is omit, so jsoup no valid, i am wantn's extends Whitelist class and ovridder testValidProtocol method, can i do? i need some code! thank

**Comment by yangjiacheng** [comment]
i use parseBodyFragment method and baseUri change to abs uri, thank

**Comment by yangjiacheng** [comment]
suggest add method  in Jsoup class,  isValid(String bodyHtml, String baseUri, Whitelist whitelist)

**Comment by rwalkerands** [comment]
Reopened the last comment as #1024.
