### ISSUE TITLE
Element.getChildrenByTag() feature request

### ISSUE THREAD

**Issue by ks280first** [jhy/jsoup#984]
It would be a nice improvement to be able to use all the Element.getElementsBy... methods without recursing into the full tree.  I'm using Java 8, so I can use streams and filter the child elements myself, but I often end up creating an Elements collection from the resulting List to make use of its functions.  Whether they're separate methods or a boolean on the current methods doesn't really matter.

**Comment by jhy** [comment]
Thanks for the idea. I generally don't like adding special case getElementsBy.. methods as they're very verbose and not flexible. And obviously just adding a boolean param as a filter option is going to be backwards incompatible.

I would suggest using the Element#select(query) method instead and use a query like ":root > tag" (call select on the element which children you want). That will scope :root to the element and then find direct descendants only. Added an example in the testcases as linked.
