### ISSUE TITLE
Regression - Boolean attributes not collapsed when using HTML syntax

### ISSUE THREAD

**Issue by pvliss** [jhy/jsoup#985]
Hello,

First off, thanks for a really useful library.

So, upgrading from 1.10.2 to 1.11.2 we see that boolean attributes are no longer collapsed when using html syntax. Example test case:

```
    @Test
    public void test() {
        Document document = Jsoup.parse(
                "<html><head></head><body><hr size=\"1\" noshade=\"\"></body></html>");
        assertEquals("<html>\n" +
                     " <head></head>\n" +
                     " <body>\n" +
                     "  <hr size=\"1\" noshade>\n" +
                     " </body>\n" +
                     "</html>",
                     document.outerHtml());
    }
```

Tracked it down to commit "Refactored Attributes to be an array pair vs LinkedHashSet " ea1fb65. The `Attibutes.html(final Appendable accum, final Document.OutputSettings out)` method no longer uses `Attribute` and **fails** to check the value of the attribute for an _empty string_(line 320). 

If I may also suggest to use `Attribute.shouldCollapseAttribute(String key, String val, Document.OutputSettings out)` instead as a single source of truth as the boolean expression is complex enough and easy to make a mistake. Not sure if this would have an impact in performance though but I am guessing that optimizer will inline the call at some point anyways?

**Comment by jhy** [comment]
Thanks! Fixed
