### ISSUE TITLE
match with quoted pattern

### ISSUE THREAD

**Issue by aditsu** [jhy/jsoup#986]
I was checking how Jsoup handles `:matches(regex)` and noticed that the parsing code is not quite robust enough. Here's a plausible example that fails:
```
final Document doc = Jsoup.parse("<div>1) foo</div>");
System.out.println(doc.select("div:matches(" + Pattern.quote("1)") + ")"));
```
This is because `Pattern.quote` doesn't escape with backslashes like Jsoup expects, but rather wraps the text between `\Q` and `\E`, with some special handling if the original text contained `\E`.

**Comment by HcPlu** [comment]
well,I have tried this case. I found out a very interesting thing that
` final Document doc = Jsoup.parse("<div>* foo</div>\n<div>\\)</div>");
System.out.println(doc.select("div:matches(" + Pattern.quote("\\)") + ")"));
System.out.println(doc.select("div:matches(" + Pattern.quote("*" + ")"));
`
it works actually.
but if , I use `Pattern.quote(")")`,it failed.So is `Pattern.quote("(")` and so char like )

So I guess maybe there is lake of some char parse like ")","(" ?

**Comment by aditsu** [comment]
@HcPlu Your last line is missing a character.
Anyway, the bug is that Jsoup doesn't recognize the `\Q … \E` escapes, and crashes on an unbalanced `)` when parsing `matches( … )`.
Your first pattern works because Jsoup sees the `)` as being escaped by the `\`.
Your second pattern works (after fixing it) because it has no `)`.

**Comment by HcPlu** [comment]
still keep my view. The (fixed)second case worked with pattern.quote.If Jsoup doesn't recognize `\Q'''\E`,how?
Taking your example,it still fails when exclude the `pattern.quote`

**Comment by HcPlu** [comment]
@aditsu

**Comment by aditsu** [comment]
Jsoup doesn't recognize `\Q` and `\E`, but after determining the regex, it creates a `Pattern` object from it, which DOES recognize `\Q` and `\E`.
So in other words, Jsoup works in 2 steps:
1) identify the regex by finding the closing `)` of the `:matches(` selector
2) create a `Pattern` from it and use it to test elements

Both steps involve some regex parsing, step 1 at a basic level and step 2 does the full job. Step 2 recognizes `\Q` and `\E` but step 1 does not, and that's where the bug is.

**Comment by SliverySky** [comment]
The bug is that chompBalance() did not ignore the bracket in \Q \E and leads to unbalanced brackets error . It should ignore. So I modify the chompBalance() by ignoring the brackets which are between \Q \E.  Then it work well. And I have committed a pull request.

**Comment by jhy** [comment]
Thanks all
