### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by elmuerte** [jhy/jsoup#993]
Using Jsoup 1.11.2 on a JRE 1.6 I get an UnsupportedClassVersionError exception.

```
java.lang.UnsupportedClassVersionError: org/jsoup/Jsoup : Unsupported major.minor version 51.0
```

From https://jsoup.org/download

> jsoup runs on Java 1.5 and up, Scala, Android, OSGi, Lambda, and Google App Engine.

Release notes of 1.11.1 do mention changing from Java 5 to Java 7. But this is rather buried in the content.

**Comment by santyC** [comment]
I'm facing this issue too.

**Comment by jhy** [comment]
Thanks, I have updated the site to reflect that Java 7 is the base requirement. I will publish it for the next release.

For 1.5 compatibility, 1.10.x is the last series with that support.
