### ISSUE TITLE
Parsing bug in HttpConnection::get and HttpConnection.Response::parse

### ISSUE THREAD

**Issue by marvk** [jhy/jsoup#995]
While working on an application that downloads and parses RSS files from [packetstormsecurity.com](https://packetstormsecurity.com/) I've found a strange behaviour: Sometimes when selecting a `pubDate` entity from an `item` entity, Jsoup would continue parsing past the closing `pubDate` tag and into the next entity.

This seems to be caused by the above mentioned methods introducing the html character codes for `<` and `>` (`&lt;` and `&gt;` respectively) while parsing the string `</pubDate>`, resulting in a pubDate entity looking like this `<pubDate>Tue, 06 Jun 2017 14:06:27 GMT&lt;/pubDate&gt;`, causing the parser to overshoot.

The bug only happens on very rare occasion for the above mentioned website, I'd guess about one to five in one thousand pages.

Since the above mentioned website is posting new items multiple times per day and thus the affected pages change, the code contains a method to find bad pages. When a bad page is found, the code will download and parse it thrice, once for each of the affected methods and once with a workaround, which uses `Jsoup::parse` and passes the body of the `HttpConnection.Response` object obtained from `Connection::execute`.

[I've created a repo](https://github.com/marvk/JsoupParseBug) that contains a [MCVE](https://stackoverflow.com/help/mcve) to reproduce the probable bug. Here is some example output from the program:

    Malformed output via Jsoup.connect(url).get():
    Wed, 07 Jun 2017 14:22:24 GMT
    Wed, 07 Jun 2017 14:21:31 GMT
    Wed, 07 Jun 2017 14:19:11 GMT
    Wed, 07 Jun 2017 14:19:03 GMT
    Wed, 07 Jun 2017 14:18:54 GMT
    Wed, 07 Jun 2017 14:18:49 GMT
    Wed, 07 Jun 2017 14:18:44 GMT
    Wed, 07 Jun 2017 14:18:38 GMT
    Wed, 07 Jun 2017 14:18:30 GMT
    Wed, 07 Jun 2017 14:18:23 GMT
    Wed, 07 Jun 2017 14:18:17 GMT
    Wed, 07 Jun 2017 14:18:12 GMT
    Wed, 07 Jun 2017 14:15:55 GMT
    Wed, 07 Jun 2017 13:47:58 GMT
    Wed, 07 Jun 2017 10:11:11 GMT
    Tue, 06 Jun 2017 23:26:00 GMT
    Tue, 06 Jun 2017 23:25:00 GMT
    Tue, 06 Jun 2017 23:24:00 GMT
    Tue, 06 Jun 2017 23:23:00 GMT
    Tue, 06 Jun 2017 14:06:27 GMT</pubDate> Gentoo Linux Security Advisory 201706-5 - Multiple vulnerabilities in D-Bus might allow an attacker to overwrite files with a fixed filename in arbitrary directories or conduct a symlink attack. Versions less than 1.10.18 are affected.
    Tue, 06 Jun 2017 14:06:16 GMT
    Tue, 06 Jun 2017 14:06:02 GMT
    Tue, 06 Jun 2017 14:05:53 GMT
    Tue, 06 Jun 2017 14:05:45 GMT
    Tue, 06 Jun 2017 14:05:34 GMT

    Malformed output via Jsoup.connect(url).execute().parse():
    Wed, 07 Jun 2017 14:22:24 GMT
    Wed, 07 Jun 2017 14:21:31 GMT
    Wed, 07 Jun 2017 14:19:11 GMT
    Wed, 07 Jun 2017 14:19:03 GMT
    Wed, 07 Jun 2017 14:18:54 GMT
    Wed, 07 Jun 2017 14:18:49 GMT
    Wed, 07 Jun 2017 14:18:44 GMT
    Wed, 07 Jun 2017 14:18:38 GMT
    Wed, 07 Jun 2017 14:18:30 GMT
    Wed, 07 Jun 2017 14:18:23 GMT
    Wed, 07 Jun 2017 14:18:17 GMT
    Wed, 07 Jun 2017 14:18:12 GMT
    Wed, 07 Jun 2017 14:15:55 GMT
    Wed, 07 Jun 2017 13:47:58 GMT
    Wed, 07 Jun 2017 10:11:11 GMT
    Tue, 06 Jun 2017 23:26:00 GMT
    Tue, 06 Jun 2017 23:25:00 GMT
    Tue, 06 Jun 2017 23:24:00 GMT
    Tue, 06 Jun 2017 23:23:00 GMT
    Tue, 06 Jun 2017 14:06:27 GMT</pubDate> Gentoo Linux Security Advisory 201706-5 - Multiple vulnerabilities in D-Bus might allow an attacker to overwrite files with a fixed filename in arbitrary directories or conduct a symlink attack. Versions less than 1.10.18 are affected.
    Tue, 06 Jun 2017 14:06:16 GMT
    Tue, 06 Jun 2017 14:06:02 GMT
    Tue, 06 Jun 2017 14:05:53 GMT
    Tue, 06 Jun 2017 14:05:45 GMT
    Tue, 06 Jun 2017 14:05:34 GMT

    Well-formed output via Jsoup.parse(Jsoup.connect(url).execute().body()):
    Wed, 07 Jun 2017 14:22:24 GMT
    Wed, 07 Jun 2017 14:21:31 GMT
    Wed, 07 Jun 2017 14:19:11 GMT
    Wed, 07 Jun 2017 14:19:03 GMT
    Wed, 07 Jun 2017 14:18:54 GMT
    Wed, 07 Jun 2017 14:18:49 GMT
    Wed, 07 Jun 2017 14:18:44 GMT
    Wed, 07 Jun 2017 14:18:38 GMT
    Wed, 07 Jun 2017 14:18:30 GMT
    Wed, 07 Jun 2017 14:18:23 GMT
    Wed, 07 Jun 2017 14:18:17 GMT
    Wed, 07 Jun 2017 14:18:12 GMT
    Wed, 07 Jun 2017 14:15:55 GMT
    Wed, 07 Jun 2017 13:47:58 GMT
    Wed, 07 Jun 2017 10:11:11 GMT
    Tue, 06 Jun 2017 23:26:00 GMT
    Tue, 06 Jun 2017 23:25:00 GMT
    Tue, 06 Jun 2017 23:24:00 GMT
    Tue, 06 Jun 2017 23:23:00 GMT
    Tue, 06 Jun 2017 14:06:27 GMT
    Tue, 06 Jun 2017 14:06:16 GMT
    Tue, 06 Jun 2017 14:06:02 GMT
    Tue, 06 Jun 2017 14:05:53 GMT
    Tue, 06 Jun 2017 14:05:45 GMT
    Tue, 06 Jun 2017 14:05:34 GMT
    
Tested on Jsoup 1.11.2

**Comment by jhy** [comment]
Interesting. Could you modify the test to write out the bad URLs and note them here? If a URL is bad, is it always bad, or does that vary?

**Comment by marvk** [comment]
> Since the above mentioned website is posting new items multiple times per day and thus the affected pages change, [...]

The affected pages change and it seems like they are not tied to specific items in the rss feed, meaning that if an items moves from page `x` to page `x+1` and page `x` was affected, page `x+1` won't necessarily be affected. 

I've just added a method that prints all affected pages as they're found.

Another curious thing I've forgot to mention is that whether a page is affected or not changes based on if the url supplied to `Jsoup::connect` has a trailing slash or not.

**Comment by jhy** [comment]
Could you save the HTML from one of the failed pages?

If you get a URL that fails and immediately reload it, does it still fail? I'm trying to determine if it's deterministic based on the content, or what.

**Comment by marvk** [comment]
Yeah, downloaded some pages and added them to the repo. As far as I can see, a URL will stay bad for at least as long as the xml on the server does not change.

**Comment by jhy** [comment]
Thanks, will take a look. Guessing it's a similar issue to #967 maybe.

**Comment by jhy** [comment]
Thanks for reporting this and the test repro. I've committed a fix. 

The problem was that the TokeniserState checked if the CharacterReader was empty before trying to read an end tag, and the isEmpty() method didn't buffer in new contents. So if an end tag just happened to be on a buffer read boundary, isEmpty() would return false, and would cause the tokenizer to read the next section as plain text given its fallback path.

Fixed by making isEmpty do a buffer up when called externally (not when internal, which would mix the bufPos counter up).

**Comment by marvk** [comment]
Just in case: This bug may also happen when passing an `InputStream` to `Jsoup::parse`, I assume that got fixed in https://github.com/jhy/jsoup/commit/b92b4f6b9b3256e97bfb6a0732bf113b6da53a4c along with the other methods, but I thought I'd let you know just in case.
